### ISSUE TITLE
Don't print migration output when running the initial setup migration

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1023]
I mostly want the initial setup migration to be invisible. We shouldn't have this in the output:

```
Running migration 00000000000000
```

This just requires special casing that version in the function which prints that line.

**Comment by juliusdelta** [comment]
Would love to work on this @sgrif if that's cool.

**Comment by Eijebong** [comment]
Sure 👍

**Comment by juliusdelta** [comment]
Awesome. i'll try to submit a PR tomorrow afternoon. Ty

**Comment by juliusdelta** [comment]
So there's a few ways to accomplish this, but the most apparent but "not so elegant" way to do it is wrapping an `if` statement before the `writeln!()` function that outputs `Running Migration 00000000000000`.

Something like:
[`/diesel/src/migrations/mod.rs#L267-L277`](https://github.com/diesel-rs/diesel/blob/master/diesel/src/migrations/mod.rs#L267-L277)
```rust
fn run_migration<Conn>(conn: &Conn, migration: &Migration, output: &mut Write)
    -> Result<(), RunMigrationsError> where
        Conn: MigrationConnection,
{
    conn.transaction(|| {
        if migration.version() !== "00000000000000" {
            try!(writeln!(output, "Running migration {}", migration.version()));
        }
        try!(migration.run(conn));
        try!(conn.insert_new_migration(migration.version()));
        Ok(())
    })
}
```

It definitely seems like it could be cleaner but I didn't want to over think it. 

The thought hole I went down was: at this point the `version` field is already defined on the `migration` at this point right? So just checking if it exists isn't possible in this scenario.

I suppose I could also check if the first version equals the last version which might look nicer imo but it's not as clear if you're reading it -> If I'm understanding the architecture correctly that is.

Thoughts? @sgrif @Eijebong

**Comment by sgrif** [comment]
That change is pretty much exactly what I want. There's really no need to overthink it (we should probably have a test that `diesel setup` followed by `diesel migration run` has no output lines with "Running migration") to make sure that a future change to the versioning doesn't break this)

**Comment by juliusdelta** [comment]
Sounds good! 👍  I'll get that done. Thanks for the direction!
