### ISSUE TITLE
Insertable derive may error if used with other schema features

### ISSUE THREAD

**Issue by skade** [diesel-rs/diesel#1032]
### Versions

- **Rust:** 1.20 nighly
- **Diesel:** 0.14.0
- **Database:** Postgres
- **Operating System** Linux/mac

### Feature Flags

- **diesel:** postgres
- **diesel_codegen:** postgres

## Problem Description

When importing schema dsl methods in the same namespace as an `Insertable` derive, the code doesn't compile.

```rust
#[macro_use] extern crate diesel;
#[macro_use] extern crate diesel_codegen;

mod schema {
    infer_schema!("dotenv:DATABASE_URL");
}

mod models {
    use super::schema::posts::dsl::posts;

    #[derive(Queryable)]
    pub struct Post {
        pub id: i32,
        pub title: String,
        pub body: String,
        pub published: bool,
    }

    #[derive(Insertable)]
    #[table_name="posts"]
    pub struct NewPost<'a> {
        pub title: &'a str,
        pub body: &'a str,
    }
}
```

https://gist.github.com/skade/9f66885d041de7f8cf88ce3788696ae1

<a id="expected"></a>
### What are you trying to accomplish?

Nothing, it just occured to me.

### What is the expected output?

```rust
cargo build
   Compiling diesel-derive-error v0.1.0 (file:///Users/skade/src/diesel-derive-error)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38 secs
```

### What is the actual output?

See linked gist above

### Are you seeing any additional errors?

No.

### Steps to reproduce

Use the file linked in the gist as lib.rs with your standard example setup.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
This is the expected behavior. The module needs to be in scope. You generally shouldn't import stuff from `dsl` outside of functions

**Comment by killercup** [comment]
Is this documented explicitly in the dsl docs? (I'll check and add if not.)

The solution to this using UFCS in the code generated by the proc macro. It
may be a good idea to this regardless, but I'll need to think about that
some more :)

Sean Griffin <notifications@github.com> schrieb am Fr. 21. Juli 2017 um
13:28:

**Comment by skade** [comment]
This is documented nowhere and came up in an innocuous attempt to extend this (working) module by following your guides.

https://github.com/rust-community/rust-campaigns-server/blob/master/src/main.rs#L47-L112

It is at least surprising and the error message is terribly unhelpful.

**Comment by sgrif** [comment]
I agree that we need to make this more clear in the documentation. I'm not sure how we can improve the error message other than a lint. 

> I find it confusing that diesel needs very tight hygienic control of the surrounding namespace or otherwise falls flat on its nose.

I don't see any way that we could work around this, unless we enforce the exact location of the table module from the crate root, which isn't something I want to do.
