### ISSUE TITLE
Diesel CLI should be released when `diesel` is released

### ISSUE THREAD

**Issue by skade** [diesel-rs/diesel#1036]
### Versions

- **Rust:** any
- **Diesel:** any
- **Database:** any
- **Operating System** any

### Feature Flags

- **diesel:** any
- **diesel_codegen:** any

## Problem Description

When configuring https://elements.heroku.com/buildpacks/sgrif/heroku-buildpack-diesel, I used the version of the diesel library we use (0.14.1) as `.diesel_version`, only to figure out that there's no `diesel_cli` version for that library version. It's surprising that the CLI and the library are not released in equal steps, so that within the frameworks, multiple user-facing components need to be used in different versions.

I admit that this is a speedbump, but speedbumps make smooth driving annoying.

### What are you trying to accomplish?

I'm still not sure.

### What is the expected output?

No email from Heroku that the build failed.

### What is the actual output?

An email from Heroku that the build failed.

### Are you seeing any additional errors?

No.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
We don't bump the patch versions of something when nothing has changed. We'll only do that for major/minor versions.
