### ISSUE TITLE
Query dsl generated by select leak private types to public interface

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#1037]
### Versions

- **Rust:** 1.19
- **Diesel:** 0.15
- **Database:** Postgres
- **Operating System** Ubuntu

### Feature Flags

- **diesel:** default-features = false, features = ["postgres", "chrono", "serde_json"]
- **diesel_codegen:** default

### What are you trying to accomplish?

Return a common select query part from a function (I know of boxed queries)

### What is the expected output?

The code compiles (even if the the returning type is somewhat complex)

### What is the actual output?

It is impossible to import all needed types, because some of them are inside of a private module of diesel. Therefore it is not possible to write down those type.

(In theory there should be a lint([private_in_public]( https://github.com/rust-lang/rust/issues/34537)) for this in rustc, but it seems like the lint failed to catch this types)

### Steps to reproduce

```rust
table! {
    groups {
        id -> Integer,
        group_name -> Text,
    }
}

fn query_groups() -> ::diesel::query_builder::SelectStatement<self::groups::table,
                                                              ::diesel::query_builder::select_clause::DefaultSelectClause,
                                                              ::diesel::query_builder::distinct_clause::NoDistinctClause,
                                                              ::diesel::query_builder::where_clause::WhereClause<
                                                                      ::diesel::expression::operators::Eq<self::groups::columns::id,
                                                                                                          ::diesel::expression::bound::Bound<::diesel::types::Integer, i32>>>>{
    use self::groups::dsl::*;
    groups.filter(id.eq(1))
}
```

```
error[E0603]: module `select_clause` is private
  --> src/lib.rs:77:63
   |
77 |                                                               ::diesel::query_builder::select_clause::DefaultSelectClause,
   |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `distinct_clause` is private
  --> src/lib.rs:78:63
   |
78 |                                                               ::diesel::query_builder::distinct_clause::NoDistinctClause,
   |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Cause

This is basically caused because `query_builder::select_clause` and similar modules [are private](https://github.com/diesel-rs/diesel/blob/master/diesel/src/query_builder/mod.rs#L16-L23). Those types are [used](https://github.com/diesel-rs/diesel/blob/master/diesel/src/query_builder/select_statement/mod.rs#L35-L41) in `query_builder::select_statement::SelectStatement` for example as default types for the generic parameters. `SelectStatement` is exported as [public type](https://github.com/diesel-rs/diesel/blob/master/diesel/src/query_builder/mod.rs#L32) in `query_builder`

Maybe this should also be reported as bug of the private_in_public lint in rustc?

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by killercup** [comment]
Yeah, seems like this lint should trigger, but I don't know the specifics.

I think the original idea was to either use [`BoxedDsl`](https://docs.rs/diesel/0.15.0/diesel/prelude/trait.BoxedDsl.html) or [`impl Trait`](https://github.com/rust-lang/rust/issues/34511). Where would you want this to be documented?

**Comment by weiznich** [comment]
As written above, I know about the alternatives. It simply seems to be inconsistent to have private types in the public interface.

**Comment by killercup** [comment]
Yes, sorry, that was a bit short. I only wanted to add some links to people finding this issue in the future had some more context. :)

I don't think we can easily fix this right now, as the types are part of the API we don't want to stabilize without carefully thinking about and discussing it. But—I also did only think about this for a minute right now. What would you do? And, do you think we should document BoxedDsl somewhere prominently as a workaround?

**Comment by sgrif** [comment]
You aren't meant to ever reference these types correctly. You should use the types in http://docs.diesel.rs/diesel/helper_types/index.html

**Comment by sgrif** [comment]
We should probably add helper types for `InnerJoin` and `LeftOuterJoin`
