### ISSUE TITLE
Attempting to serialize `BigDecimal::from_str("10000.16")` fails on PG

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1044]
To reproduce:

```rust
let connection = PgConnection::establish("...").unwrap();
let value = BigDecimal::from_str("10000.16");
sql::<Numeric>("SELECT $1")
    .bind::<Numeric, _>(value)
    .execute(&connection)
    .unwrap()
```

**Comment by Eijebong** [comment]
10 000 is suspicious since pg stores numeric values in base 10k

**Comment by lancecarlson** [comment]
When I encountered this issue, the error I got was:

error importing: DatabaseError("invalid digit in external \"numeric\" value")

**Comment by sgrif** [comment]
The representation I get for `SELECT '10000.16'::numeric` is `Positive { weight: 1, scale: 2, digits: [1, 0, 1600] }`. The value we're sending is `Positive { weight: 0, scale: 2, digits: [10000, 1600] }`

**Comment by sgrif** [comment]
The fix is relatively trivial. Just improving our test coverage and making sure this doesn't affect numbers after the decimal point as well
