### ISSUE TITLE
Question: How to set busy timeout for sqlite?

### ISSUE THREAD

**Issue by limira** [diesel-rs/diesel#1067]
Hi,

I use diesel's sqlite for my app. Now I want to set the busy timeout for my sqlite connection to 20s. I found [this](http://docs.diesel.rs/libsqlite3_sys/fn.sqlite3_busy_timeout.html), but I don't know how to use it.

Can someone help me with this!

Thank you!

**Comment by sgrif** [comment]
You can use `connection.execute` to set the pragma. https://sqlite.org/pragma.html#pragma_busy_timeout
