### ISSUE TITLE
Not working: parent.join(child.join(grandchild)) [in some cases]

### ISSUE THREAD

**Issue by valeriansaliou** [diesel-rs/diesel#1068]
### Versions

- **Rust:** rustc 1.21.0-nightly (b75d1f0ce 2017-08-02)
- **Diesel:** 0.15.2
- **Database:** PG
- **Operating System** macOS 10.12.6

### Feature Flags

- **diesel:** ["postgres"]
- **diesel_codegen:** ["postgres"]

## Problem Description

In certain relational schemas, performing a `parent.join(child.join(grandchild))` doesn't work as expected (`join` can be an `inner_join` or `left_join`, same error).

The same code, using the simpler `parent.join(child.join)` call works.

**If I change the schema and reverse the belongs_to relation between parent and child, the nested join works just fine. However that's the schema I want to rely on, plus my schema is SQL-valid.**

### What are you trying to accomplish?

I'm trying to perform a join w/ the following structure: `parent.join(child.join(grandchild))`

Given the following schema: 

```rust
table! {
    parent (id) {
        id -> Integer,
        child_id -> Integer,
    }
}

table! {
    child (id) {
        id -> Integer,
        grand_child_id -> Integer,
    }
}

table! {
    grandchild (id) {
        id -> Integer,
    }
}
```

And the following model:

```rust
#[derive(Identifiable, Queryable, Associations)]
#[belongs_to(Child)]
#[table_name="parent"]
pub struct Parent {
    pub id: i32,
    pub child_id: i32,
}

#[derive(Identifiable, Queryable, Associations)]
#[belongs_to(GrandChild)]
#[table_name="child"]
pub struct Child {
    pub id: i32,
    pub grand_child_id: i32,
}

#[derive(Identifiable, Queryable, Associations)]
#[table_name="grandchild"]
pub struct GrandChild {
    pub id: i32,
}
```

### What is the expected output?

The expected output is the equivalent of the full-SQL request:

```sql
SELECT "person_employment"."title", "company"."legal_name", "contact"."emails" FROM (
	"person_employment"
		INNER JOIN "company" ON "person_employment"."company_id" = "company"."id"
		INNER JOIN "contact" ON "company"."contact_id" = "contact"."id"
);
```

Which works just fine in a PG prompt, based on the bare SQL schema defined above.

### What is the actual output?

Getting the following error when compiling, although all relevant `belongs_to` and `enable_multi_table_joins!` are set.

```
error[E0277]: the trait bound `diesel::query_source::joins::PleaseGenerateInverseJoinImpls<parent::table>: diesel::JoinTo<child::table>` is not satisfied
   --> src/lib.rs:141:10
    |
141 |         .inner_join(child::table.inner_join(grandchild::table))
    |          ^^^^^^^^^^ the trait `diesel::JoinTo<child::table>` is not implemented for `diesel::query_source::joins::PleaseGenerateInverseJoinImpls<parent::table>`
```

### Are you seeing any additional errors?

No, only this one.

### Steps to reproduce

1. Gist: [valeriansaliou/48f441bbcdcef29f5395b87b09dc9893](https://gist.github.com/valeriansaliou/48f441bbcdcef29f5395b87b09dc9893)
2. Compile the code w/o changing it. It works. It's using the only relational schema I could get it to work with, however I don't want it this way (in this schema, a child references both its parent and grandchild)
3. Uncomment the 2 commented sections regarding schema + models and comment out the other ones.
4. Build it, you'll get the compilation error I'm talking about. This is using the schema that's more appropriate in that case, but which will never build w/ Diesel.

**Comment by sgrif** [comment]
Your names are backwards FYI. You're trying to go grandchild -> child -> parent

**Comment by valeriansaliou** [comment]
Yeah it's backwards, because otherwise I get:

```
error[E0275]: overflow evaluating the requirement `<child::table as diesel::JoinTo<grandchild::table>>::OnClause`
   --> src/lib.rs:141:34
    |
141 |         .inner_join(child::table.inner_join(grandchild::table))
```

**Comment by sgrif** [comment]
The code and error should be identical. Just your naming is wrong. What you're calling `Parent` should be called `Grandchild`. Changing the names wouldn't change the error.

**Comment by valeriansaliou** [comment]
Thanks a ton @sgrif 👍

**Comment by sgrif** [comment]
Don't thank me yet. I have a *lot* more work to do to get rid of the fallout of that change.
