### ISSUE TITLE
Cannot use DateTime in MySQL

### ISSUE THREAD

**Issue by csharad** [diesel-rs/diesel#1076]
### Versions

- **Rust:** rustc 1.21.0-nightly
- **Diesel:** 0.15.0
- **Database:** mysql Ver 14.14 Distrib 5.7.19
- **Operating System:** Ubuntu 17.04

### Feature Flags

- **diesel:** "mysql", "chrono"
- **diesel_codegen:** "mysql"

## Problem Description
I am not able to use `DateTime` in the table whereas `Timestamp` is usable. But `Timestamp` has a 2038 Year problem.

### What are you trying to accomplish?
Allow DateTime as a datatype for mysql.

**Comment by Eijebong** [comment]
Closed by #1082 

Thanks for the report :)
