### ISSUE TITLE
Update BigDecimal to 0.0.10

### ISSUE THREAD

**Issue by drager** [diesel-rs/diesel#1083]
Hey! [BigDecimal](https://crates.io/crates/bigdecimal) got support for being serialized and deserialized with serde behind a [feature](https://github.com/akubera/bigdecimal-rs/commit/8e0f185ec54400dd3a1d5580597e725b9a5b8555). It would be great if diesel could update to that version.

Thank you.

**Comment by killercup** [comment]
Is this already fixed by #1081?

**Comment by drager** [comment]
Seems like it! When can it be released?

**Comment by Eijebong** [comment]
Well, @sgrif said "tomorrow" yesterday, so I'd say next week :)
