### ISSUE TITLE
where clause with do_update()

### ISSUE THREAD

**Issue by DaveLancaster** [diesel-rs/diesel#1085]
Does on_conflict(do_update()) support a where clause? This would be super useful for something I am working on.

Thanks.

**Comment by sgrif** [comment]
No, we do not currently support `DO UPDATE ... WHERE`

**Comment by blkt** [comment]
Hello @sgrif, is this feature planned? Would you be interested in help with it?

**Comment by weiznich** [comment]
@blkt There is currently no concrete plan for this feature, but we would probably accept a well written PR.
