### ISSUE TITLE
Iterator support

### ISSUE THREAD

**Issue by jethrogb** [diesel-rs/diesel#1087]
I'd like to issue select queries that return all data lazily in the form of an iterator. I want to issue queries for a million rows or so and I don't want to allocate all the memory up front.

This seems to have been the way things worked, but it was changed in #132/#142. I don't fully understand the rationale for the change. I also don't care about associations for this particular query.

**Comment by vandenoever** [comment]
I'd very much appreciate the convenience of ORM without the memory allocation overhead. An iterator that returns shallow items that use `&str` instead of `String` would be good in low-memory use-cases.

**Comment by deankarn** [comment]
I was very much enjoying learning and experimenting with diesel until I found that it returned a `Vec` rather than an `Iterator`.

This limitation makes this library unusable in a lot of high performance, low memory and future asyncio situations.

Is there a workaround or method I'm missing to accomplish this? It would also be great if someone could explain the rationale behind moving away from iterators, perhaps there's a good reason I'm missing?

**Comment by lnicola** [comment]
Note that it's often considered a good idea to buffer the results. Reading row by row, often tends to keep the query running for a longer time, possibly decreasing concurrency on the server. Realistically, the cost of the allocation is tiny compared to the network and query latency.

Of course, buffering works better with small result sets or pagination. But if you're reading a million rows at once, there might be better approaches.

**Comment by deankarn** [comment]
@lnicola thanks for the quick response 😄

I agree in many situations such a large one time query is often avoidable. I was hoping though that the option would still be available for the user in the cases where it's unavoidable.

Thanks again!

**Comment by derekdreery** [comment]
I actually wrote some code to do this today. I'll copy it verbatim below. It uses an internal buffer and offset/limit. It would be good if I could pass my buffer to a method rather than have it allocate a new Vec every time, but I don't think this is possible currently.

```rust
//! A little abstraction to fetch database records in batches.
//!
//! TODO this currently will fail if there are concurrent connections. It should use some sort of
//! lock.
use diesel::{
    dsl::{Limit, Offset},
    prelude::*,
    query_dsl::{
        methods::{LimitDsl, OffsetDsl},
        LoadQuery,
    },
    result::Error,
};
use std::{collections::VecDeque, convert::TryInto, marker::PhantomData};

/// Get an object that implements the iterator interface.
pub fn stream_results<'conn, Record, Query, Conn>(
    query: Query,
    conn: &'conn Conn,
    buffer_size_hint: usize,
) -> impl Iterator<Item = Result<Record, Error>> + 'conn
where
    Record: 'conn,
    Query: OffsetDsl + Clone + 'conn,
    Offset<Query>: LimitDsl,
    Limit<Offset<Query>>: LoadQuery<Conn, Record>,
{
    RecordIter {
        conn,
        query,
        cursor: 0,
        buffer: VecDeque::with_capacity(buffer_size_hint),
        record_type: PhantomData,
    }
}

struct RecordIter<'conn, Record, Query, Conn> {
    conn: &'conn Conn,
    query: Query,
    /// The index of the next record to fetch from the server
    cursor: usize,
    buffer: VecDeque<Record>,
    record_type: PhantomData<Record>,
}

impl<'conn, Record, Query, Conn> Iterator for RecordIter<'conn, Record, Query, Conn>
where
    Query: OffsetDsl + Clone,
    Offset<Query>: LimitDsl,
    Limit<Offset<Query>>: LoadQuery<Conn, Record>,
{
    type Item = Result<Record, Error>;

    fn next(&mut self) -> Option<Self::Item> {
        // if the buffer isn't empty just return an element
        match self.buffer.pop_front() {
            Some(v) => return Some(Ok(v)),
            None => (), // fall through
        };
        // fill the buffer
        let fetch_amt = self.buffer.capacity();
        let query = self
            .query
            .clone()
            .offset(self.cursor.try_into().unwrap())
            .limit(fetch_amt.try_into().unwrap());
        self.cursor += fetch_amt;
        let results: Vec<Record> = match query.load(&self.conn) {
            Ok(recs) => recs,
            Err(e) => return Some(Err(e)),
        };
        for result in results {
            self.buffer.push_back(result);
        }
        // return the first record, or None if there are no more records fetched.
        self.buffer.pop_front().map(Ok)
    }
}
```

**Comment by chris13524** [comment]
I'm also interested in why we aren't using Iterators here? If you want to process all records you might not be able to pull that into memory. IMO it would make sense to expose an Iterator where underneath it runs `offset()` and `limit()` to pull records in batches on-demand.

**Comment by weiznich** [comment]
@chris13524 We are not interested in supporting iterators build on top of `offset` and `limit` as this hide a lot of complexity about the query from the user. It would for example not be possible to write queries with their own offset or limit clause, as those would get overwritten by the iterator (or the iterator needs complicated special cases for those)
Additionally it is easily possible to build something like that on top of diesel, so I do not see any need to have this in diesel itself.

**Comment by mjanda** [comment]
You could probably use cursors to implement this.

https://www.postgresql.org/docs/11/plpgsql-cursors.html

But I guess it would be quite complex change and it might not be possible for all databases.

Some crates implement prefetching N rows at a time (rust-oracle for example).

**Comment by weiznich** [comment]
@mjanda See the two issues/PR's linked in OP. The original implementation provided a method that returned a iterator based on cursors. There are reasons listed there to switch that to return a `Vec<T>` instead. I'm not sure if all of the reasoning in there is relevant anymore as the API changed quite a bit since then. Internally all of our currently supported backends are using cursors.

That said at least for me there are currently more important things to work on than this, as I think it is not useful for most cases. For the general case you end up collecting the result somewhere anywhere.
