### ISSUE TITLE
Mysql and BLOB column

### ISSUE THREAD

**Issue by bradleybeddoes** [diesel-rs/diesel#1089]
### Versions

- **Rust:** rustc 1.19.0
- **Diesel:** 0.15.2
- **Database:** Mysql
- **Operating System** OSX

### Feature Flags

- **diesel:** `mysql`
- **diesel_codegen:** `mysql`

## Problem Description
When using `infer_schema!` on a table that includes a BLOB column compilation does not complete successfully.

### What are you trying to accomplish?
Using a struct of the following definition:

``` rust
#[derive(Queryable)]
struct RSAKeyPairData {
    pub id: i64,
    pub private_key_pem: Vec<u8>,
    pub certificate_pem: Vec<u8>,
    pub published: bool,
    pub active: bool,
}
```

### What is the expected output?
Valid compilation.

### What is the actual output?
```
error[E0412]: cannot find type `Blob` in this scope
 --> src/schema.rs:5:1
  |
5 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = help: there is an enum variant `diesel::mysql::MysqlType::Blob`, did you mean to use `diesel::mysql::MysqlType`?
  = note: this error originates in a macro outside of the current crate
```

### Are you seeing any additional errors?
No.

### Steps to reproduce

``` sql
CREATE TABLE rsakeypairs (
  id SERIAL PRIMARY KEY,
  private_key_pem BLOB NOT NULL,
  certificate_pem BLOB NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT 0
)
```

Use `infer_schema!` to trigger.

n.b. `diesel print-schema` outputs:

```
table! {
    rsakeypairs (id) {
        id -> Bigint,
        private_key_pem -> Blob,
        certificate_pem -> Blob,
        published -> Bool,
        active -> Bool,
    }
}
```

Manually supplying the following `table!` definition as opposed to using `infer_schema!` removes the compilation fault and all appears to function correctly, I am not sure if `Binary` is correct here (though from docs it seems to be):

```
table! {
    rsakeypairs (id) {
        id -> Bigint,
        private_key_pem -> Binary,
        certificate_pem -> Binary,
        published -> Bool,
        active -> Bool,
    }
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by killercup** [comment]
Thanks for the report! Seems like this is just a small missing piece. And @Eijebong already opened #1090 to fix it :)

**Comment by bradleybeddoes** [comment]
Can't argue with a response as quick as that!

Thanks folks :).
