### ISSUE TITLE
Documentation - Model Annotation / Traits

### ISSUE THREAD

**Issue by notryanb** [diesel-rs/diesel#1107]
## Problem Description
Re: **Better Documentation** #853  *Models*

Documentation on model annotations (`Queryable`, `Identifiable`, `Insertable`, etc...) and the code they generate is sparse and spread out over the API documentation. Available guides ([Getting Started](http://diesel.rs/guides/getting-started/) & [All About Updates](http://diesel.rs/guides/all-about-updates/)) make mention of the derivable traits, but do not go into much depth.

### What are you trying to accomplish?
 - Create a central location to reference all the traits that can derived
 - Explain why these derives are useful or important
 - Explain how to implement the traits without the struct annotations (for comparison or writing custom ones)
 - Provide specific example use cases (and even erroneous cases?).

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by notryanb** [comment]
Now that df5a6e8d39c001a6ebe0944ee34a2068316fbacb has been merged, I believe this can now be closed.

**Comment by killercup** [comment]
Indeed! Thanks again for that awesome PR!

**Comment by zjyysc11** [comment]
，，，
