### ISSUE TITLE
Recent commit adding operator support to date causing issues for Nullable<Date>

### ISSUE THREAD

**Issue by estelendur** [diesel-rs/diesel#1109]
### Versions

- **Rust:** rustc 1.21.0-nightly (f25c2283b 2017-08-15)
- **Diesel:** SHA 01f72e1717ab26d346c3c48872f5d674fdd411c4
- **Database:** Postgresql
- **Operating System** Fedora Workstation 25

### Feature Flags

- **diesel:** ["postgres", "chrono", "uuid", "huge-tables", "extras"]
- **diesel_codegen:** ["postgres"]

## Problem Description
I am trying to set up a table with Nullable<Date> columns. Small example:
```
table! {
    master {
        id -> Integer,
        file_number -> Text,
        date_received -> Nullable<Date>,
    }
}
```

### What is the actual output?
When I try to compile, I receive the following error, along with a similar one for `diesel::types::ops::Add`:
```
error[E0277]: the trait bound `diesel::types::Nullable<diesel::types::Date>: diesel::types::ops::Sub` is not satisfied
  --> src/cls/schema.rs:19:5
   |
19 | /     table! {
20 | |         importer.debtor {
21 | |             id -> Integer,
22 | |             internal_ref -> Text,
...  |
39 | |         }
40 | |     }
   | |_____^ the trait `diesel::types::ops::Sub` is not implemented for `diesel::types::Nullable<diesel::types::Date>`
   |
   = help: the following implementations were found:
             <diesel::types::Nullable<diesel::types::SmallInt> as diesel::types::ops::Sub>
             <diesel::types::Nullable<diesel::types::BigInt> as diesel::types::ops::Sub>
             <diesel::types::Nullable<diesel::types::Numeric> as diesel::types::ops::Sub>
             <diesel::types::Nullable<diesel::types::Integer> as diesel::types::ops::Sub>
           and 2 others
   = note: this error originates in a macro outside of the current crate

```

### Steps to reproduce
Create a schema with a Nullable<Date> column and try to compile.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by killercup** [comment]
Thanks for reporting! The PR that added this was #1094. Maybe you have an idea how to fix this?

(Looks like we are also missing a test case for nullable date time types.)

**Comment by estelendur** [comment]
I'm sorry, I'm very new to Rust and don't have the first idea how to fix it.

**Comment by killercup** [comment]
No worries! I'll make sure this is fixed before we release a new version with this change.
