### ISSUE TITLE
SQLite text search doesn't work

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#1112]
I'm trying to do [text search](https://sqlite.org/fts5.html) in SQLite, but when I create a virtual FTS table, like this:
[`create virtual table foo using fts5 (content='files', path);`](https://stackoverflow.com/a/29926430/7488353)

I get this error:
```
error: proc-macro derive panicked
 --> src\models\schema.rs:1:1
  |
1 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: Could not infer table foo: StringError("Diesel only supports
tables with primary keys. Table foo has no primary key")
  = note: this error originates in a macro outside of the current crate
```
How can I get this to work? Do I have to create a FTS table with a primary key? If so, how?
Can I then declare the table using the `table!` macro?
Does diesel support the `MATCH` expression or do I have to use a custom query using the `sql!` macro?

**Comment by killercup** [comment]
First, I don't think we should try to infer virtual tables by default (just like we don't infer views). Does it work if you use `table!` (with an id column of your choosing)?

Second, we have no support for `MATCH`, but you should be able to get it to work with `diesel_infix_operator!`.

**Comment by Boscop** [comment]
How do you mean? The table only has the `path` column.

**Comment by Boscop** [comment]
I tried with this, but it gives the same error:
```rust
infer_schema!("dotenv:DATABASE_URL");

table! {
	foo(path) {
		path -> VarChar,
	}
}
```
How can I only infer tables other than `foo`?

**Comment by Boscop** [comment]
It works when I don't use the `infer_schema!` macro (because it doesn't support excluding tables), but instead write the schemas of all tables manually and then:
```rust
table! {
	foo(path) {
		path -> Text,
	}
}
```
