### ISSUE TITLE
Allowing `integer` to map to i64 for sqlite

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#1116]
When I use `id integer not null primary key autoincrement` in sqlite, I have to use `i32` in Rust but I want to have `i64` because I have a lot of records, but when I write `id bigint not null primary key autoincrement` I get:
>error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY

This is a syntactic [limitation](https://stackoverflow.com/a/24095388/7488353) of sqlite but sqlite stores all integers as arbitrary precision anyway, so it would be possible for diesel to also allow mapping integer to `i64`. 
It would be very useful!

Also, it doesn't let me use `u64` for `size_bytes unsigned bigint not null`, only i64...

**Comment by sgrif** [comment]
This has been raised before, and we decided to keep things as they are for reasons I laid out in https://github.com/diesel-rs/diesel/issues/852#issuecomment-315755841. If you need i64 keys, you can use `table!` or `diesel print-schema` and specify that the `id` column is of type `BigInt` there, but I don't think we should change the behavior of schema inference for the reasons I laid out in the previous comment.

**Comment by Boscop** [comment]
@sgrif Is it possible to override the type for a given `table.column` (use `BigInt` instead of `Integer`) during the call to `diesel print-schema`?

**Comment by WANG-lp** [comment]
@sgrif Very glad to see there is a correct method to use i64 for Sqlite.

I think https://github.com/diesel-rs/diesel/issues/80 can be also solved this method.

Maybe we can collect similar questions and solutions to a separated Wiki page to help newcomers!

**Comment by tobico** [comment]
Since it isn't explicitly mentioned here, at some point an option was added to the diesel.toml config file which offers an easy solution to this issue:

https://diesel.rs/guides/configuring-diesel-cli.html#the-sqlite_integer_primary_key_is_bigint-field

> The sqlite_integer_primary_key_is_bigint field
>
> This field allows you to configure diesel-cli to thread INTEGER PRIMARY KEY fields as BIGINT for sqlite databases. If not set > this defaults to false.
> diesel.toml
>
> ```
> [print_schema]
> sqlite_integer_primary_key_is_bigint = true
> ```

**Comment by silmeth** [comment]
That does not work for non-primary key fields. And while in general you can use `BIGINT` as type name in your Sqlite tables – that does not work for `STRICT` tables (so if you want the types to be checked by the DB logic, you’re out of luck).

And having 64 bits is more useful for non-primary key tables – I’m for example trying to store Unix timestamps as `INTEGER` in Sqlite (and it’d be nice if the program could handle dates beyond 2038).

**Comment by weiznich** [comment]
@silmeth Commenting to old closed issues is highly discouraged. If you would like to contribute to changing this we are happy to review your proposal for a solution filled as new [discussion](https://github.com/diesel-rs/diesel/discussions/new?category=ideas). I can understand that the current solution is not fitting for everyone, but that still doesn't change it magically. Someone needs to but in the work to outline a better solution and then actually spend the time implementing it.

**Comment by silmeth** [comment]
Sorry – that’s the one issue I found with a recent-ish activity which suggests a solution that does not work for me. I see now this issue has recurring mentions in the repo. It seems to have been superseded by this discussion: #4628 – leaving a link so the next person coming here sees it.

Sorry again for contributing more to the communication chaos.
