### ISSUE TITLE
Support for prepared statements in SQLite

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#1117]
SQLite prepared statements (e.g. for preventing SQL injection) can only be defined via the C API, not in raw sql like in postgres. So it can't be done with diesel's `sql` function:
https://sqlite.org/c3ref/stmt.html
http://jgallagher.github.io/rusqlite/rusqlite/struct.Statement.html

**Comment by sgrif** [comment]
I'm not sure what you're asking for? You can provide bind parameters to a query using the [`.bind`](http://docs.diesel.rs/diesel/expression/sql_literal/struct.SqlLiteral.html#method.bind). All queries are performed as prepared statements, regardless of backend.

**Comment by Boscop** [comment]
Ah, I didn't know that. Thanks!
