### ISSUE TITLE
Feature request: Boxed where clauses for delete statements

### ISSUE THREAD

**Issue by quadrupleslap** [diesel-rs/diesel#1128]
A query that has been created dynamically with `into_boxed()` can't be passed to `diesel::delete`. Is there an alternative for dynamically adding filters to deletes or is there no workaround for this feature that looks like it's missing?

**Comment by Eijebong** [comment]
I think this is probably a bug as I don't see why boxed queries shouldn't be used with a delete statement.

**Comment by sgrif** [comment]
The reason the impl isn't there is that not all boxed queries are valid delete statements. If any clause is present other than the where clause, it would result in an error. However, now that we have `filter` on `Update` and `DeleteStatement` directly, I'd be fine with a separate `BoxedDeleteStatement` and `BoxedUpdateStatement` (or even just boxing the where clause on those by default -- there's not a huge drawback to doing so)

**Comment by sgrif** [comment]
I actually think boxing the where clauses by default would have been the right way to go. Unfortunately, we can't change that now that we're post-1.0. I'm definitely interested in having `BoxedUpdateStatement` and `BoxedDeleteStatement` though. The API surface on those is relatively small. I don't think we need to support upsert for boxed update statements (unless it's easy to add support). Boxed update statements should box the values as well as the where clause.

I'm happy to mentor someone interested in working on this. It'll be a decent sized patch, but it's pretty straightforward once you understand the basics of our codebase, and `BoxedSelectStatement` is a perfect reference for this, as the implementation will be quite similar.

**Comment by ivanovaleksey** [comment]
I would like to give it a try.
However, I am not very fluent in Rust and I totally don't understand how Diesel works.
Do you have extra-patience for this? 😄

**Comment by sgrif** [comment]
@ivanovaleksey I appreciate the offer, but this has already been mostly implemented (support for delete statements is merged, I have a branch with support for update statements that I need to clean up one last thing on before pushing up)

**Comment by ivanovaleksey** [comment]
Yeah, I see merged #1534 and I wonder doesn't it close this issue.
Thank you for your work!
