### ISSUE TITLE
bash: diesel: command not found

### ISSUE THREAD

**Issue by yyolf117** [diesel-rs/diesel#1131]
I've installed "diesel_cli" but when I'm calling "diesel setup" or  "diesel_cli", the exception is "bash: diesel: command not found" or "bash: diesel_cli: command not found". What's the matter? Wasn't it supposed to insert itself into the path?

**Comment by killercup** [comment]
How'd you install it? With cargo install? It writes the binary to a path
like `.cargo/bin/`. See cargo's docs for details.

yyolf117 <notifications@github.com> schrieb am Sa. 26. Aug. 2017 um 13:00:

**Comment by yyolf117** [comment]
yes, with cargo install.

**Comment by yyolf117** [comment]
```
$ ls ~/.cargo/bin/
diesel

```

but 

```
$ diesel
bash: diesel: command not found

```

**Comment by killercup** [comment]
So, I guess `~/.cargo/bin/` isn't in `$PATH`? It probably should be! ;)

You can also tell `cargo install` to install it somewhere else, like `/usr/local/bin`.

(I _think_ rustup adds this but only for certain shells and system.)

**Comment by yyolf117** [comment]
ok, how about my last question?

**Comment by killercup** [comment]
I didn't see your edit _or_ the question in the code block.

> what if I gave it a different name? MY_DATABASE_URL

Then… you have an environment variable called `MY_DATABASE_URL`. But diesel_cli has no way of knowing that it exists or that it should even care about that. Thus, you'll need to pass it the `--database-url` argument with the (you guessed it) database url, or use the env variable name it expects.

**Comment by yyolf117** [comment]
thx.  but I can't use `DATABASE_URL` in each project I have because, of course, each connection string in each proejct is different.

**Comment by killercup** [comment]
That's what the .env file is for :) Have a look at the guide.

**Comment by yyolf117** [comment]
I didn't find anything related to "--database-url" being passed as an argument to diesel in the command line, where is it?

**Comment by killercup** [comment]
What do you mean? Have you read `diesel --help`? It's `diesel
--database-url="your url"`.
yyolf117 <notifications@github.com> schrieb am So. 27. Aug. 2017 um 05:21:

**Comment by yyolf117** [comment]
yeah, thanks.
