### ISSUE TITLE
#![recursion_limit="128"]

### ISSUE THREAD

**Issue by uncode** [diesel-rs/diesel#1133]
### Versions

- **Rust:0.16.o**
- **Diesel:0.16.0**
- **Database:Mysql**
- **Operating System:Mac OS**

### Feature Flags

- **diesel: Mysql**
- **diesel_codegen: Mysql**

### schema.rs
```
infer_schema!("dotenv:DATABASE_URL");
```

### build error
```
error: recursion limit reached while expanding the macro `numeric_expr`
 --> src/schema.rs:1:1
  |
1 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: this error originates in a macro outside of the current crate

```

**Comment by mmstick** [comment]
What was your solution?

**Comment by Eijebong** [comment]
@mmstick Do what the rust compiler tells you to do, add a `#[recursion_limit="128"]` at the root of your crate

**Comment by killercup** [comment]
> Do what the rust compiler tells you to do

I want that on a t shirt
