### ISSUE TITLE
error message could explain `execute` vs `load`

### ISSUE THREAD

**Issue by jonathanstrong** [diesel-rs/diesel#1136]
### Versions

- **Rust:** nightly 1.21 2017-08-29
- **Diesel:** 0.14
- **Database:** postgresql 9.5
- **Operating System** ubuntu 16.04

### Feature Flags

- **diesel:** postgres, uuid, serde_json, chrono
- **diesel_codegen:** postgres

## Problem Description

It took me a long time to figure out that `execute` returns at most one value (I'm assuming) while `load` returns (or can return) a collection of values. 

I got the following error message: 

```
error[E0308]: mismatched types
  --> src/main.rs:95:9
   |
95 | /         sql::<(Integer, pg_types::Uuid,)>(query)
96 | |             .execute(&db)
97 | |             .expect("query failed");
   | |_______________________________________^ expected struct `std::vec::Vec`, found usize
   |
   = note: expected type `std::vec::Vec<(i32, uuid::Uuid)>`
              found type `usize`
```
(You can't see it in the error message, but I was trying to assign the query result to a `Vec<(i32, uuid::Uuid)>`).

It would be helpful if this error message could offer some hint about the difference between `execute` vs `load`. Just thought I would share a point of confusion from someone trying to learn the library. Thanks!

## Checklist

- [ yes ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
We don't have control over the error message, but we do call this out in the getting started guide. We should make that same call out in the docs for load

**Comment by brandur** [comment]
I took a stab at adding a little more documentation in #1548 (as suggested).

IMO though, the original reporter here has a point in that this goes a little beyond a documentation problem. I've been using Diesel fairly seriously for a few weeks now and it's quite a common pattern to have a compiler protect you from misuse, but to do so in a way that doesn't help give you much of an idea as to what's actually wrong.

You'll probably eventually solve the problem, but you do so by changing things until you accidentally get it right, investing lots of time reading documentation, or by cloning Diesel's source code and examining its source and examples in the test suite. (Compiler errors are often of minimal help.)

I don't really have a suggestion on how to fix this, but I wanted to second the fact that it's a fairly major problem, especially for newcomers to Rust and Diesel.

**Comment by brandur** [comment]
Another data point: #1551. Diesel is doing something useful by not allowing a `BIGINT` to be loaded into an `i32`, but a new user is quite confused by the error message that's produced.
