### ISSUE TITLE
Use compile_error!

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#1138]
Rust 1.20 stabilized the [`compile_error!`](https://doc.rust-lang.org/stable/std/macro.compile_error.html) macro, which means we can finally output useful errors from macros and unusable feature-flag combinations!

Here are the places with code comments just waiting to use this macro:

https://github.com/diesel-rs/diesel/blob/b26472f4290c658822334b148494550b943ef991/diesel/src/macros/mod.rs#L406-L408

https://github.com/diesel-rs/diesel/blob/453d8ffbfe80bada40b79ddc2834d2b3c190b7be/diesel/src/test_helpers.rs#L50

https://github.com/diesel-rs/diesel/blob/453d8ffbfe80bada40b79ddc2834d2b3c190b7be/diesel_codegen/tests/test_helpers.rs#L50

https://github.com/diesel-rs/diesel/blob/4f87b471128061887040c703c6aa1f1ae62218d6/diesel/src/doctest_setup.rs#L144

https://github.com/diesel-rs/diesel/blob/148d0e448c95120baaa721578fe03e519b0bbf40/diesel/src/macros/insertable.rs#L501

**Comment by notryanb** [comment]
@killercup - I'd like to tackle this issue. I think I may be able to also solve #624 while doing this?

**Comment by killercup** [comment]
@notryanb it's yours!

#624 might be a bit more tricky. Do you have a good idea how to solve it? I could only come up with one medium and one hard way… (see <https://github.com/diesel-rs/diesel/issues/624#issuecomment-326586831>)

**Comment by notryanb** [comment]
👍 I'll look into #624 separately.

**Comment by sgrif** [comment]
Diesel CLI and Infer Schema should also use this in the places they currently fail to compile when built with 0 features.
