### ISSUE TITLE
Invalid sql generated

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#1141]
### Versions

- **Rust:**
- **Diesel:**
- **Database:**
- **Operating System**

### Feature Flags

- **diesel:**
- **diesel_codegen:**

## Problem Description
It is possible to generate invalid sql using diesels buildin query dsl. In detail it is possible to use `desc()` in `group_by` calls. (I didn't check any other combinations, probably this could be used in other places too)

### What are you trying to accomplish?
I've misstyped some query by accident using `group_by` instead of `order` and was surprised this was compiling after noticing this.

### What is the expected output?
A compiler error indicating `.desc()` should not be used in `group_by()` clauses.

### What is the actual output?
A runtime error indicating a invalid sql query

### Are you seeing any additional errors?
No

### Steps to reproduce
```rust
some_table::table.group_by(some_table::some_column.desc()).load(conn)?;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
`group_by` is not part of our public API. It has no expected behavior. https://github.com/diesel-rs/diesel/blob/ceed4c15b375746ed1b334e0d0ee3f8013ac09bf/diesel_tests/tests/group_by.rs#L5-L7
