### ISSUE TITLE
Consider linting test code on CI

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#1143]
We are currently telling contributors to use the [`bin/test`] script to test their changes. This script runs a ALL the `cargo test`s—with clippy enabled. Which means it catches more than our CI setup does, as the Travis only runs [the equivalent of cargo clippy](https://github.com/diesel-rs/diesel/blob/ca7b989d4457aee33eef6c5e373238b77bf74b9a/.travis.yml#L43-L50).

I think we can tell Travis to compile in a way so code in `#[cfg(test)]` gets included, but this may conflict with compiling all backends at once.

[`bin/test`]: https://github.com/diesel-rs/diesel/blob/ca7b989d4457aee33eef6c5e373238b77bf74b9a/bin/test

**Comment by sgrif** [comment]
I'm actually wondering if we should just remove clippy from `bin/test` as it increases build times quite a bit. I don't think linting the tests extensively adds nearly as much value

**Comment by killercup** [comment]
True. On the other hand, it's frustrating to see tests pass locally only to have CI fail on clippy. Do we mention `bin/check` enough in the Contributing Guide?

**Comment by sgrif** [comment]
If we removed it from `bin/test` I would say that we should not lint tests on CI either. Only lint the main code, which is what CI does currently.

**Comment by killercup** [comment]
Yep. But if people *only* use bin/test, they wont ever see clippy's wonderful suggestions for their changes

**Comment by sgrif** [comment]
Given that it's test code, I don't think that's a huge loss

**Comment by killercup** [comment]
I'm also talking about regular code. With this change, the only way to get clippy to check anything is `bin/check`

**Comment by sgrif** [comment]
I guess it's a question of whether people are running `bin/test` or `bin/check` more.

**Comment by killercup** [comment]
Well, let's just hope people find `bin/check` then 😄
