### ISSUE TITLE
Our PG upsert API is clunky and we should fix it

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1166]
I've really disliked using our upsert API in practice. You basically always need to pull `records.on_conflict(...)` into a local variable since it's going to span multiple lines, and it's really hard to name that variable. https://github.com/rust-lang/crates.io/blob/9c8947c4d171706f490dfd8dfeb932a714d252be/src/download.rs#L43-L50 https://github.com/rust-lang/crates.io/blob/9c8947c4d171706f490dfd8dfeb932a714d252be/src/categories.rs#L125-L140

I'd like to change our API to something more fluent, which more naturally allows for line breaks where they're likely to occur. I'd like to make the following changes:

```rust
// OLD
insert(records.on_conflict_do_nothing()).into(table)

// NEW
insert(records).into(table).on_conflict_do_nothing()

// OLD
insert(records.on_conflict(target, do_nothing())).into(table)

// NEW
insert(records).into(table).on_conflict(target).do_nothing()

// OLD
insert(records.on_conflict(target, do_update().set(...))).into(table)

// NEW
insert(records).into(table).on_conflict(target).do_update().set(...)

// ALTERNATE
insert(records).into(table).on_conflict(target).do_update_set(...)

// ALTERNATE 2
insert(records).into(table).on_conflict(target).do_update(...)
```

**Comment by alexcameron89** [comment]
I'll give this one a try 👍
