### ISSUE TITLE
Consider changing `insert(records).into(table)` to `insert_into(table).values(records)`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1167]
There are two main things that got me thinking about this change. The first is [this code](https://github.com/diesel-rs/diesel/pull/1165/files#diff-0f3c021dc67b888eef8a6619689208cbR19). It's a papercut, but I don't like the fact that if you get the argument to `insert` wrong, the message is going to be that you passed the wrong number of arguments to `into`. Maybe this isn't a big deal (I don't think it's ever come up in gitter), but it's a paper cut I'd like to avoid, and I think it will be easier to run into once #789 is done.

The second is that I've been thinking about an API to represent `INSERT INTO table (column_list) SELECT ...`. The best idea I've seen based on our current API is `insert(select_statement).into(column_list)`, but that feels a little implicit to me. If we changed the insert API, I could see something like `insert_into(table).columns(column_list).values(select_statement)` or `insert_into(table).from_select(column_list, select_statement)` being much more reasonable.

**Comment by sgrif** [comment]
@diesel-rs/contributors WDYT?

**Comment by samphippen** [comment]
I like it.
