### ISSUE TITLE
Help translate sql to diesel

### ISSUE THREAD

**Issue by xinghun92** [diesel-rs/diesel#1176]
I have many messages and many chats, one message belongs to only one chat and has a unique position in this chat. And I want to get messages in different chats with different positions. Does diesel support query like this?
```
select * from messages where chat_id=1 and position in (1,2,3) or chat_id=2 and position in (3,4,5) or chat_id=3 and position in (6,7,8) ...

**Comment by sgrif** [comment]
```rust
let case_1 = chat_id.eq(1).and(position.eq_any(vec![1, 2, 3]));
let case_2 = chat_id.eq(2).and(position.eq_any(vec![3, 4, 5]));
let case_3 = chat_id.eq(3).and(position.eq_any(vec![6, 7, 8]));

messages.filter(case_1.or(case_2).or(case_3))
```

**Comment by xinghun92** [comment]
How can I use it dynamically? 
```
let mut Initial = ...
for sub_case in cases {
    Initial = Initial.or(sub_case)
}
```

and what the Initial should be?

**Comment by sgrif** [comment]
You'll need to box it in that case. http://docs.diesel.rs/diesel/expression/trait.BoxableExpression.html
