### ISSUE TITLE
Review some of our really old docs

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1180]
I noticed this gem in [the docs for `insert`](https://docs.rs/diesel/0.16.0/diesel/fn.insert.html):

> This function is not exported by default.

I don't even know what I meant by that. I think I meant that `use diesel::*;` wouldn't import `insert`? That isn't true anymore, and even if it was that's not a super relevant thing to document.

It also states:

> As with other commands, the resulting query can return the inserted rows if you choose.

which is only true on PG (the only backend we support that has a `RETURNING` clause. We should probably do a pass over all the functions that have been around since 0.1 (everything in `query_builder::functions` is a good place to start).

**Comment by notryanb** [comment]
I'd like to start working on this, if no one else has already claimed. I'm also open to working with someone if they would like to help out.

**Comment by weiznich** [comment]
Also the docs for [associations](http://docs.diesel.rs/diesel/associations/index.html) seems to be out of date.

For example they are talking about using `#[belongs_to(table)]` but not about using the `joinable!()` macro. (The first is not needed anymore, the second is required now…)

**Comment by notryanb** [comment]
@weiznich - Good point. I have an issue open - #1235 addressing the associations docs (mostly just the examples), but I'll adjust the explanations as well.
