### ISSUE TITLE
Handling unsigned integer types from MySQL

### ISSUE THREAD

**Issue by davechallis** [diesel-rs/diesel#1181]
I've got a lot of MySQL tables with unsigned integer types (e.g. `id INT(10) UNSIGNED`).

I'm struggling to run queries against these with Diesel when their values exceed the positive `i32` max value.

E.g. using:

```
extern crate diesel;
#[macro_use] extern crate diesel_codegen;

use diesel::prelude::*;
use diesel::mysql::MysqlConnection;
use diesel::expression::sql;
use diesel::types::Integer;

#[derive(PartialEq, Debug, Queryable)]
struct Thing {
    id: i32
}

fn main() {
    let url = "mysql://user:pass@localhost/test"
    let conn = MysqlConnection::establish(&url).unwrap();

    let query = sql::<Integer>("SELECT 4000000000");
    query.load::<Thing>(&conn);
}
```
results in a runtime error:
```
Err(DeserializationError(StringError("Numeric overflow/underflow occurred")))
```
which is expected, as it overflows `i32`, but is an acceptable `u32` value.

Changing my struct to:
```
struct Thing {
    id: u32
}
```
instead results in a compiler error:
```
the trait `diesel::types::FromSqlRow<diesel::types::Integer, _>` is not implemented for `(u32,)
```

Is this just unsupported by Diesel, or is there a different approach I should be taking for dealing with MySQL's unsigned integers?

**Comment by killercup** [comment]
#912 reverted #782 because of `u16`, but maybe the other additions were valid?

**Comment by sgrif** [comment]
IIRC I was just straight up incorrect in #912, and we just need a PR that updates the code to not conflict with the latest master

**Comment by sgrif** [comment]
Adding this to the milestone. The solution is literally just rebasing an old PR. The longer we wait, the harder that will be.

**Comment by joshleeb** [comment]
I'd like to take this one on as a first issue :smile:

I attempted to rebase #782 with `git`, but I think it'll be easier reapply it manually instead.
