### ISSUE TITLE
Can we emit compile-error on `.select(fieldname1)` for `struct{fieldname2)`?

### ISSUE THREAD

**Issue by limira** [diesel-rs/diesel#1216]
- **Diesel:** 0.15
- **Database:** sqlite

## What I have

    CREATE TABLE tablename(
        id INTEGER NOT NULL PRIMARY KEY,
        minx INTEGER,
        miny INTEGER,
        maxx INTEGER,
        maxy INTEGER
    );

    #[derive(Serialize, Queryable)]
    struct River{
        id: i64,
        minx: Option<i32>,
        miny: Option<i32>,
        maxx: Option<i32>,
        maxy: Option<i32>
    }

## What I did
Note that there is a typo in it. I mistyped: **maxy** instead of **maxx**.

    tablename.select((id, minx, miny, **maxy**, maxy)).filter(...).load(&con);

The rust program compiled and ran without any issue, but obviously gave me a wrong result that mismatched to my intention.

Can diesel help prevent this type of error?

**Comment by sgrif** [comment]
By design, no. `Queryable` does not correspond to field names, it corresponds to the type. That said, this is on the list of things I'd like to lint for in https://github.com/diesel-rs/diesel/issues/573
