### ISSUE TITLE
Check for bad connections

### ISSUE THREAD

**Issue by jethrogb** [diesel-rs/diesel#1256]
There is currently no portable way to tell whether a database connection is still usable. Yes, queries might return an `Error`, but you can't easily tell from that whether it was just something with the query or database, or the connection. Also, when using connection pooling, you want to know when a connection is returned to the pool whether to retire it or not. This would require just querying the connection without knowing anything about its history.

I suggest adding an `fn is_usable` to `trait Connection` or similar. In Postgres, this can be implemented with `PQstatus`. MySQL hopefully has something similar.

**Comment by sgrif** [comment]
You can easily test this with `connection.execute("SELECT 1").is_ok()`. I don't think we need an explicit method for this.

**Comment by jethrogb** [comment]
That requires a network round-trip to complete. For the connection pooling use, that basically means every query now takes twice as long.
