### ISSUE TITLE
Support postgress ltree type in schema

### ISSUE THREAD

**Issue by carols10cents** [diesel-rs/diesel#1262]
We've got [a pr in crates.io to use postgres' ltree type](https://github.com/rust-lang/crates.io/pull/1122). Diesel seems to be quite happy to use this, except when it comes to the schema. 

After running the migration in that PR, of which the important part is adding a column to a table of type `ltree`:

```
ALTER TABLE categories ADD COLUMN path ltree;
```

I can run `diesel print-schema --with-docs > src/schema.rs`, and the new column with the ltree type **is** printed as I would expect:

```
table! {
    /// Representation of the `categories` table.
    ///
    /// (Automatically generated by Diesel.)
    categories (id) {

        // ...

        /// The `path` column of the `categories` table.
        ///
        /// Its SQL type is `Ltree`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Ltree,
    }
}
```

but when I try to compile crates.io using this schema, I get these errors:

```
error[E0412]: cannot find type `Ltree` in this scope
   --> src/schema.rs:117:17
    |
117 |         path -> Ltree,
    |                 ^^^^^ not found in this scope
```

I have tried this with diesel 0.16.0 and diesel master at 75ba15a91218ef040e0b379cc3e9c4bbd34f09da.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
Are we ever using that column on anything Diesel related? If not we can just delete the column from schema.rs.

Otherwise we can create a `struct Ltree;` somewhere

**Comment by sgrif** [comment]
Since this type comes from an extension, which we don't support in Diesel, I'm going to close this. Proper support for this type would be better handled by a third party crate. (See `diesel_full_text_search` for an example implementation of one)

**Comment by carols10cents** [comment]
Then I have to either delete the column for schema.rs every time I run diesel print-schema, or I have to add `use Ltree` every time i run diesel print-schema, and everyone who adds a migration to diesel and runs print-schema has to know this...

**Comment by sgrif** [comment]
Yeah I think it's worth having us keep a diff file that can be easily re-applied in crates.io
