### ISSUE TITLE
Support for ARRAY[]

### ISSUE THREAD

**Issue by kivikakk** [diesel-rs/diesel#1263]
We currently lack support for the `ARRAY[]` constructor in Postgres, and it'd be nice to have so we can use array arguments to functions.

(Context: me trying to work out what I want and @sgrif finally working out what I meant happened in chat here: https://gitter.im/diesel-rs/diesel?at=59e8bb40b20c642429219b6f)

**Comment by sgrif** [comment]
Fixed in 8fb0429
