### ISSUE TITLE
Cross-DB update-or-insert support (SQL2003 MERGE statement)

### ISSUE THREAD

**Issue by icefoxen** [diesel-rs/diesel#1272]
This is a wishlist item.

Would it be possible to support an [update-or-insert](https://en.wikipedia.org/wiki/Merge_(SQL)) operation in a way that's portable across databases?  The Postgres driver already has `upsert()`, is it possible/feasible/desirable to extend this to all drivers, and translate it into either the database-specific version of it or into a slower-but-portable version?

Thank you!

**Comment by sgrif** [comment]
I believe you are looking for [`replace_into`](http://docs.diesel.rs/diesel/fn.replace_into.html) (which was `insert_or_replace` in 0.16)
