### ISSUE TITLE
Easy way to turn Error::NotFound into an Option

### ISSUE THREAD

**Issue by icefoxen** [diesel-rs/diesel#1273]
Wishlist item.

In my Rust code I very often find myself doing:

```rust
fn get_thing() -> Result<Option<Thing>> {
    let res = thing.filter(something)
        .select(stuff)
        .load::<Thing>(connection)?;
    match res {
       Ok(thing) => Ok(Some(thing)),
       Err(diesel::result::Error::NotFound) => Ok(None),
       Err(e) => Err(e)
}
```

This tends to happen when the absence of a `Thing` is perfectly valid, and we should just, say, create a new `Thing` from defaults, or do nothing, or even just report a different sort of error (which might be recoverable) than, say, a `DatabaseError` or `DeserializationError` (which probably isn't).

Is this common enough for anyone else that it's worth making a shortcut combinator?  I'll happily make a PR for it.

**Comment by sgrif** [comment]
You can call [`.optional()`](http://docs.diesel.rs/diesel/result/trait.OptionalExtension.html#tymethod.optional). We call this out in the documentation of every method that can return `NotFound` (which is basically just [`.get_result`](http://docs.diesel.rs/diesel/prelude/trait.LoadDsl.html#method.get_result) and [`.first`](http://docs.diesel.rs/diesel/prelude/trait.FirstDsl.html#method.first)

**Comment by icefoxen** [comment]
My mistake for not seeing it then, thanks!
