### ISSUE TITLE
table field defined multiple times

### ISSUE THREAD

**Issue by uncode** [diesel-rs/diesel#1274]
![image](https://user-images.githubusercontent.com/13595898/31983479-053c8db6-b923-11e7-8f1e-d7203597a2fa.png)

but one table have only one this name 'level'

**Comment by uncode** [comment]
table! {
    level (id) {
        id -> Integer,
        name -> Varchar,
        level -> Tinyint,
        limits -> Integer,
        limite -> Integer,
    }
}

Maybe it's the problem here?

**Comment by Eijebong** [comment]
Yeah you can't have a column with the same name as the table. You can rename the column by putting a `#[sql_name="level"]` on it and renaming it to `level_` or whatever other name you can think about. http://docs.diesel.rs/diesel/macro.table.html

**Comment by uncode** [comment]
can't both use ` infer_schema!("dotenv:DATABASE_URL") ` and `table!` ?

**Comment by Eijebong** [comment]
No, you can't blacklist tables from `infer_schema!` so you have to do everything with `table!`. `diesel print-schema` will help you do that :p

**Comment by sgrif** [comment]
You could also use `infer_table_from_schema!` for the tables that you want to infer. Closing as there doesn't appear to be anything actionable here, but feel free to ask further questions here or in gitter.
