### ISSUE TITLE
error: Could not compile `mysqlclient-sys`.

### ISSUE THREAD

**Issue by ziselive** [diesel-rs/diesel#1286]
cargo install diesel_cli, error:

error: could not find native static library `mysqlclient`, maybe an -L flag is missing?

error: Could not compile `mysqlclient-sys`.

……………………
mysql version 5.7
win7 x64
rust 1.22.0-nightly

**Comment by weiznich** [comment]
Try setting `MYSQLCLIENT_LIB_DIR` to point to the directory where `mysqlclient.dll` is stored.

**Comment by forbjok** [comment]
I'm having the same issue on Windows 10 x64.
I don't have MySQL in any shape or form installed, and I have no intention of using it.
This seems like it should be an optional component only required if you are actually using MySQL.

**Comment by sgrif** [comment]
We call this out explicitly [in the getting started guide](http://diesel.rs/guides/getting-started/)

<img width="725" alt="screen shot 2017-12-03 at 1 24 56 pm" src="https://user-images.githubusercontent.com/1529387/33529387-6a91b50a-d82d-11e7-879c-4c37adce0d6e.png">

**Comment by eastuto** [comment]
for anyone wanting to actually use MySQL and who is having issues running cargo install, just to clarify adding the location of `mysqlclient.lib` to your environment variables will fix this.

E.g.

`MYSQLCLIENT_LIB_DIR=C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14`

**Comment by shijunti19** [comment]
Windows 10 can't solve this problem.


![image](https://user-images.githubusercontent.com/5392211/50535710-b5cb4980-0b87-11e9-92d2-2e5cbef3a08e.png)

![image](https://user-images.githubusercontent.com/5392211/50535712-ba8ffd80-0b87-11e9-9a3a-0f7460df1105.png)

![image](https://user-images.githubusercontent.com/5392211/50535717-d398ae80-0b87-11e9-90f7-2a02f204f20c.png)

**Comment by savovs** [comment]
The way the getting started docs are set up will fail for many first time users. We might be better off just having `cargo install diesel_cli --no-default-features --features postgres` be the default one and moving the mysql-requiring thing in "A Note on Installing diesel_cli"

I think this will be a much better first experience

**Comment by weiznich** [comment]
@savovs I don't think its a good idea to simplify the setup of one supported back end at the cost of making the setup of the other two targets more difficult.

**Comment by SOF3** [comment]
I tried everything -- adding mysqlclient.lib to $PATH, passing -L... but it is still not compiling.
![image](https://user-images.githubusercontent.com/19623715/60387413-62ee3280-9ad5-11e9-8d3b-21d713600984.png)

**Comment by foxline626** [comment]
设置这些环境变量：
PQ_LIB_DIR
SQLITE3_LIB_DIR
MYSQLCLIENT_LIB_DIR
在命令提示符或PowerShell中输入以下内容：

`setx PQ_LIB_DIR "C:\Program Files\PostgreSQL\10\lib"
[...]

setx SQLITE3_LIB_DIR "C:\SQLite"
[...]

setx MYSQLCLIENT_LIB_DIR "C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14"
[...]`

注意：您可能必须根据这些文件在PC中的位置更改路径：

libpq.lib
sqlite.lib
mysqlclient.lib

删除：C:\Users\*****\AppData\Local\Temp\cargo-insta***  文件

`cargo install diesel_cli`

![image](https://user-images.githubusercontent.com/5585408/61575683-312f2100-ab01-11e9-9e38-b901397e13ba.png)

**Comment by jellybobbin** [comment]
I'm having the same issue on Windows 7 x64.

**Comment by shamiao** [comment]
> 
> 
> Tips:
> if you build failed and follow this issue to change your environment variable, you should execute `cargo clean` before next build.
> seems cargo not re-run build script if you continue last build, and it will always get an error.

This works. Note: use `cargo clean -p mysqlclient-sys`  to only clean mysql client crate.

**Comment by ScottHuangZL** [comment]
Please download mysqlclient from: https://downloads.mysql.com/archives/c-c/

**Comment by dataf3l** [comment]
for those people on osx brew install mysql did the trick for me

**Comment by StevenInacio** [comment]
For those that still have errors on Windows, you need to install the MySQL Server (but you can skip/cancel the configuration if you do not actually want to run a server).
The Library should now be under `C:\Program Files\MySQL\MySQL Server <mysql_version>\lib\mysqlclient.lib`.

I don't know if the old library in the connector/c archive is the same than this library, but the server version worked for me.

**Comment by tryeth2021** [comment]
I have set MYSQLCLIENT_LIB_DIR to C:\Program Files\MySQL\MySQL Server 8.0\lib\mysqlclient.lib and add bin to path,installing vs 2019 build tools.Finally, runing cargo install get diesel.exe.But when I run "diesel setup",it just show error:can not find bio_set_callback_ex.

**Comment by ShayBox** [comment]
If anyone is having problems installing MySQL on Windows, it seems to be because between the C and C++ connector versions, they moved `mysqlclient.lib` to the Server not the Connector.  
So set `MYSQLCLIENT_LIB_DIR` to `C:\Program Files\MySQL\MySQL Server 8.0\lib` instead, as above hinted to

**Comment by ORCA-Soft-MiguelAngel** [comment]
> [I created a guide](https://forum.shaybox.com/blog/5-setting-up-diesel-on-windows) The TLDR is that MySQL moved `mysqlclient.lib` from the C connector to the Server between v6 and v7. Set `MYSQLCLIENT_LIB_DIR` to `C:\Program Files\MySQL\MySQL Server 8.0\lib`

This worked for me, thanks.

**Comment by anuradhaindika83** [comment]
I'm using Windows 11. In my case, I installed the latest MySQL server with the C/C++ connector. Then set an environment variable `MYSQLCLIENT_LIB_DIR` with the location `C:\Program Files\MySQL\MySQL Server 8.0\lib`. Then opened up a new PowerShell session and installed the Diesel-cli. Hopes this helps. Thanks

**Comment by bcdlbgm** [comment]
cargo clean
Setting environment variables in CLion's run configuration, and then running it, should solve the problem.

**Comment by moepitman** [comment]
Still no joy. I have MySQL Server 8.0 installed and have set MYSQL_LIB_DIR to C:\Program Files\MySQL\MySQL Server 8.0\lib. I have checked to make sure the mysqlclient.lib file is there.
Next I tried ShayBox's guide, version two, and installed vcpkg. That part worked fine. But when trying to install the libraries, it quickly fails on the first build of boost-atomic:x64-windows, with the error:
Could not find b2 in
  C:/ProgramData/vcpkg/vcpkg/installed/x64-windows/tools/boost-build
Any ideas would be appreciated.

**Comment by miaomiao1992** [comment]
> Re: Diesel CLI on Windows 10 for MySQL. If the above advice doesn't work for you, this worked for me:
> 
> * Install MySQL Server 8.0, not just the connector, sadly.
> * Put the `C:\Program Files\MySQL\MySQL Server 8.0\lib` (adjust `8.0` version number as needed) in your `PATH` variable. (`MYSQLCLIENT_LIB_DIR` environment variable might be necessary too - not sure - but it alone did not do the trick for me.)
> * To avoid complaints about `libcrypto-1_1-x64.dll` missing, be sure to also add `C:\Program Files\MySQL\MySQL Server 8.0\bin` to your `PATH` variable.
> 
> This may not be ideal, but it worked for me.

mysql8 does not support x86_64，how to solve this problem?

**Comment by mathbigai** [comment]
Hello everybody,
I managed to resolve the issue by doing the following:

- I installed version 8.0 of MySQL Server;
- I also installed C Connector in version 6.1;
- For the Environment variables, I created a User Variable called `MYSQLCLIENT_LIB_DIR`, informing the location of the MySQL Server installation LIB folder: "C:\Program Files\MySQL\MySQL Server 8.0";
- Then I created another System Variable called `DEP_MYSQLCLIENT_LIB_DIR`, informing the location "C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14";
- Then I ran the code `cargo install diesel_cli --no-default-features --features mysql` in **PowerShell**. I ran it as administrator.

Just pointing out that some of these steps may not be necessary, but I didn't have time to test each one more carefully.

**Comment by powerseed** [comment]
Nothing works in this thread. This crate is as difficult to use as it can be. 
Just one example feedback from the Rust community: https://www.reddit.com/r/rust/comments/vqnm3l/diesel_cli_is_too_much_pain_can_someone_help_me/
