### ISSUE TITLE
How can I use the raw sql?

### ISSUE THREAD

**Issue by driftluo** [diesel-rs/diesel#1294]
Hi, all, I encountered a problem, the output:
```
error[E0425]: cannot find function `sql_query` in module `diesel`
  --> src/models/articles.rs:31:27
   |
31 |         let res = diesel::sql_query(format!("select * from article_with_tag where id={} and published={}", id, admin))
   |                           ^^^^^^^^^ not found in `diesel`
```
the cargo.toml:
```
[dependencies.diesel]
features = ["postgres", "chrono"]
version = "^0.16.0"

[dependencies.chrono]
features = ["serde"]
version = "^0.4.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "^0.16.0"
```
Document said there has the `sql_query` method, but here is wrong, I want to know how to call the native sql operation

**Comment by killercup** [comment]
You are most likely looking at the API docs for the master branch, where
this was changed.

Here is the doc for 0.16:
https://docs.rs/diesel/0.16.0/diesel/expression/dsl/fn.sql.html

漂流 <notifications@github.com> schrieb am So. 5. Nov. 2017 um 09:45:

**Comment by driftluo** [comment]
Oh, thanks, However, at the moment crates' docs and readme's docs both point to the wrong address, which has a negative effect on the work

**Comment by killercup** [comment]
Good point! we should give two links in the Readme (as you are probably
looking at it in the repo's master branch) and link to docs.rs in the
Cargo.toml.

漂流 <notifications@github.com> schrieb am So. 5. Nov. 2017 um 11:08:

**Comment by killercup** [comment]
I opened #1295 to change the documentation links. As this issue is about how to use raw SQL, I'll close it.

Thanks again!
