### ISSUE TITLE
Unable to `inner_join` to multiple tables (A->B and A->C, not A->B->C)

### ISSUE THREAD

**Issue by trombonehero** [diesel-rs/diesel#1297]
### Versions

- **Rust:** `1.23.0-nightly (8b22e70b2 2017-10-31)`
- **Diesel:** `0.16.0`
- **Database:** `postgres`
- **Operating System:** any

### Feature Flags

- **diesel:**
- **diesel_codegen:** `[ "postgres" ]`

### What are you trying to accomplish?

I have a [reduced test case](https://github.com/trombonehero/diesel-join-example) that involves three types of DB-backed objects: `Room`, `User` and `Booking`. A `Booking` object represents a `User` having reserved a `Room` (e.g., for a meeting):

```sql
create table bookings (
	id serial primary key not null,
	room_id integer not null,
	user_id integer not null,

	foreign key (room_id) references rooms(id),
	foreign key (user_id) references users(id)
);
```

When I run `diesel print-schema` I see:

```
[...]
joinable!(bookings -> rooms (room_id));
joinable!(bookings -> users (user_id));
```

I'm also able to use a single `inner_join` between `Booking` and either `Room` or `User`:

```rust
/* ... */

#[derive(Debug, Identifiable, Queryable)]
pub struct Booking {
    pub id: i32,
    pub room_id: i32,
    pub user_id: i32,
}

type DieselResult<T> = Result<T, diesel::result::Error>;

impl Booking {
    pub fn with_rooms(c: &diesel::PgConnection) -> DieselResult<Vec<(Booking, Room)>> {
        use self::bookings::dsl::*;
        bookings.inner_join(rooms::table).load(c)
    }

    pub fn with_users(c: &diesel::PgConnection) -> DieselResult<Vec<(Booking, User)>> {
        use self::bookings::dsl::*;
        bookings.inner_join(users::table).load(c)
    }
}
```

Next, I want to be able to retrieve a `Vec<(Booking, Room, User)>` from the database by joining both `bookings->rooms` and `bookings->users` in the same query.

### What is the expected output?

When I try to compile:

```rust
impl Booking {
    /* ... */
    pub fn full(c: &diesel::PgConnection) -> DieselResult<Vec<(Booking, Room, User)>> {
        use self::bookings::dsl::*;

        bookings.inner_join(rooms::table)
                .inner_join(users::table)
                .load(c)
    }
}
```

I would expect Diesel to generate a query like:

```sql
SELECT * from bookings
    INNER JOIN rooms ON rooms.id = room_id
    INNER JOIN users ON users.id = user_id
```

(i.e., joining `bookings->rooms` and `bookings->users`)

### What is the actual output?

```
error[E0277]: the trait bound `__diesel_infer_schema::infer_rooms::rooms::table:  diesel::JoinTo<__diesel_infer_schema::infer_users::users::table>` is not satisfied
  --> src/lib.rs:47:18
   |
47 |                 .inner_join(users::table)
   |                  ^^^^^^^^^^ the trait `diesel::JoinTo<__diesel_infer_schema::infer_users::users::table>` is not implemented for `__diesel_infer_schema::infer_rooms::rooms::table`
```

So, Diesel seems to be trying to join `bookings->rooms` and `rooms->users`. I would've expected this if I were trying to compile:

```rust
bookings.inner_join(
    rooms::table.inner_join(
        users::table
    )
)
```

but in my use case, I'm trying to join both `rooms` and `users` with `bookings` individually.

### Steps to reproduce

1. Create an empty database, set `DATABASE_URL`
1. Clone https://github.com/trombonehero/diesel-join-example
1. Execute `cargo build`

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment]
Try to add `enable_multi_table_joins!(rooms, users);` somewhere in your crate.

**Comment by trombonehero** [comment]
That does seem to fix it... thank you!

Now I suppose the question is: what documentation fixes might help others avoid this particular pothole in the future?

**Comment by sgrif** [comment]
> what documentation fixes might help others avoid this particular pothole in the future?

We've been trying to document it a bit more in the relevant methods for the upcoming release. It appears in the docs for [`JoinDsl`](http://docs.diesel.rs/diesel/prelude/trait.JoinDsl.html) (where the methods you are calling come from), as well as [`joinable!`](http://docs.diesel.rs/diesel/macro.joinable.html) (which had to be invoked for this to work at all).

Additionally on master, both `infer_schema!` and `diesel print-schema` will generate code which invokes this for every table in your schema, making this a non-issue for most people

**Comment by trombonehero** [comment]
Ok, so it sounds like v0.17.0 will “just work”? If so, that’s great! Thanks.

**Comment by sgrif** [comment]
0.99 but yes

**Comment by onx2** [comment]
I'm running into some similar issues and I don't see any information about that macro above - Is this different in version 2?

I'm also unable to add the type definitions to `load` like `.load::<Vec<(FooBar, Foo, Bar)>>`.

```rust
let result: Vec<(FooBar, Foo, Bar)> = foo_bar::dsl::foo_bar
        .inner_join(foo::table)
        .inner_join(bar::table)
        .load(conn)
        .expect("failed");
```

```bash
{unknown}
the trait bound `(FooBar, Foo, Bar): FromStaticSqlRow<((diesel::sql_types::Uuid, diesel::sql_types::Uuid, diesel::sql_types::Uuid, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Text>, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Jsonb>, Timestamptz, Timestamptz)), Pg>` is not satisfied
the following other types implement trait `FromStaticSqlRow<ST, DB>`:
  <(T0,) as FromStaticSqlRow<(ST0,), __DB>>
  <(T1, T0) as FromStaticSqlRow<(ST1, ST0), __DB>>
  <(T1, T2, T0) as FromStaticSqlRow<(ST1, ST2, ST0), __DB>>
  <(T1, T2, T3, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST0), __DB>>
  <(T1, T2, T3, T4, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T6, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST0), __DB>>
  <(T1, T2, T3, T4, T5, T6, T7, T0) as FromStaticSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST0), __DB>>
and 24 others
required because of the requirements on the impl of `Queryable<((diesel::sql_types::Uuid, diesel::sql_types::Uuid, diesel::sql_types::Uuid, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Text>, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Jsonb>, Timestamptz, Timestamptz)), Pg>` for `(FooBar, Foo, Bar)`
required because of the requirements on the impl of `diesel::deserialize::FromSqlRow<((diesel::sql_types::Uuid, diesel::sql_types::Uuid, diesel::sql_types::Uuid, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Text>, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Jsonb>, Timestamptz, Timestamptz)), Pg>` for `(FooBar, Foo, Bar)`
required because of the requirements on the impl of `load_dsl::private::CompatibleType<(FooBar, Foo, Bar), Pg>` for `((diesel::sql_types::Uuid, diesel::sql_types::Uuid, diesel::sql_types::Uuid, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Text>, Timestamptz, Timestamptz), (diesel::sql_types::Uuid, Nullable<Jsonb>, Timestamptz, Timestamptz))`
required because of the requirements on the impl of `LoadQuery<'_, PooledConnection<ConnectionManager<PgConnection>>, (FooBar, Foo, Bar)>` for `SelectStatement<FromClause<JoinOn<diesel::internal::table_macro::Join<JoinOn<diesel::internal::table_macro::Join<jsonb_diesel::schema::foo_bar::table, jsonb_diesel::schema::foo::table, Inner>, diesel::expression::grouped::Grouped<diesel::expression::operators::Eq<NullableExpression<foo_id>, NullableExpression<jsonb_diesel::schema::foo::id>>>>, jsonb_diesel::schema::bar::table, Inner>, diesel::expression::grouped::Grouped<diesel::expression::operators::Eq<NullableExpression<bar_id>, NullableExpression<jsonb_diesel::schema::bar::id>>>>>>`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
mod.rs(1499, 15): required by a bound in `diesel::RunQueryDsl::load`
```

**Comment by weiznich** [comment]
@onx2 Our issue tracker is no support forum. Please do not post questions to old closed issues. Use the support forum to ask such questions and please include all necessary information to reproduce your problem in such a post.

**Comment by onx2** [comment]
Thanks for directing me to the correct place and apologies for causing unnecessary noise.
