### ISSUE TITLE
Diesel-cli requires empty Cargo.toml file before setup can be run

### ISSUE THREAD

**Issue by SamWhited** [diesel-rs/diesel#1300]
### Versions

- **Diesel:** 0.16.0

### Feature Flags

- **diesel:** no-default-features, postgres

## Problem Description

Diesel setup looks for `Cargo.toml` file unnecessarily.

### What are you trying to accomplish?

Setup a database for the first time in a non-Rust project.

```
$ diesel setup
Unable to find Cargo.toml in this directory or any parent directories.
$ touch Cargo.toml
$ diesel setup
Creating database: demodb
```
I would not expect diesel to require or care about having an empty Cargo.toml file in the project directory. My database migrations may be stored in a separate repo from my project or my project might not be in Rust at all and merely using diesel-cli for migrations.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by killercup** [comment]
The reason is this: You can run `diesel setup` in basically any directory of your project, and it will look for the root directory (which is where the migrations directory needs to live) by search for a Cargo.toml.

Immediate action item from this issues: Document this behavior.

Refactoring for the future: The code in diesel-cli that does this is actually not very clever, and I doubt it works will with a cargo workspace setup. Cargo has a `cargo locate-project` command, though, and we should consider switching to calling this.

**Comment by SamWhited** [comment]
That makes sense, and documentation would make this less confusing.

Maybe it could also search for a `.git` or `.hg` directory? Or if it doesn't find something just use the working directory? I'd still like to not have to create an empty Cargo.toml which I'm just going to remove after initializing the database for new projects.

**Comment by SamWhited** [comment]
It just occured to me that there might be an easy fix for this: if you don't have a Cargo.toml and are in the root of the project you can tell you're in the root because the `migrations` directory exists. If you're not in the root you can't tell where the root is, so for non rust projects it could just only work if you're in the root already instead of complaining about missing Cargo.toml every time I delete my development database and want to run migrations over again.

**Comment by sgrif** [comment]
>  if you don't have a Cargo.toml and are in the root of the project you can tell you're in the root because the migrations directory exists.

Except the command you're complaining about is `diesel setup`, which is responsible for creating the migrations directory.

> If you're not in the root you can't tell where the root is

You can always specify the directory with the `MIGRATION_DIRECTORY` environment variable, or the `--migration-dir` command line argument. Unless I'm mistaken, the only time we look for `Cargo.toml` is to decide where to create the migration directory if you haven't specified explicitly.

> I delete my development database and want to run migrations over again.

You probably just want `diesel database setup` in that case.

**Comment by SamWhited** [comment]
> Except the command you're complaining about is diesel setup, which is responsible for creating the migrations directory.

It's also used to create the database initially, so if we're spinning up the database for the first time (eg. on a new devvm) and the migrations are already created it will currently complain that cargo.toml doesn't exist even though it has a way to detect the root directory and the project doesn't need a cargo.toml.

Maybe it could look for the migrations directory and cargo.toml? Then it could still be used to create the database and wouldn't panic every time with a confusing error message.

**Comment by sgrif** [comment]
As I said, if you just want to create the database and not setup the whole project (which involves creating the migrations directory, generating default migrations, etc), you should run `diesel database setup` instead.
