### ISSUE TITLE
error: proc-macro derive panicked compiling diesel/examples/sqlite/getting_started_step_1

### ISSUE THREAD

**Issue by kjeremy** [diesel-rs/diesel#1307]
## Setup
cargo 0.22.0 (3423351a5 2017-10-06)

### Versions

- **Rust:** rustc 1.21.0 (3b72af97e 2017-10-09)
- **Diesel:** master and v0.16.0 tag
- **Database:** sqlite3
- **Operating System** Ubuntu 16.04

### Feature Flags

- **diesel:**
- **diesel_codegen:**

## Problem Description
Running `cargo build` in diesel/examples/sqlite/getting_started_step_1 results in a failure due to `proc_macro`.

### What are you trying to accomplish?
Build the example.

### What is the expected output?
A successful build.

### What is the actual output?

>   Compiling diesel_demo_step_1_sqlite v0.1.0 (file:///home/jkolb/diesel/examples/sqlite/getting_started_step_1)
     Running `rustc --crate-name diesel_demo_step_1_sqlite src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=622c23df1f565981 -C extra-filename=-622c23df1f565981 --out-dir /home/jkolb/diesel/target/debug/deps -L dependency=/home/jkolb/diesel/target/debug/deps --extern dotenv=/home/jkolb/diesel/target/debug/deps/libdotenv-68cc05c844f8f562.rmeta --extern diesel_codegen=/home/jkolb/diesel/target/debug/deps/libdiesel_codegen-22e7d1b09b47ba09.so --extern diesel=/home/jkolb/diesel/target/debug/deps/libdiesel-cfa8db5236072f2a.rmeta -L native=/home/jkolb/diesel/target/debug/build/backtrace-sys-943860c9c514961f/out/.libs`
> error: proc-macro derive panicked
>  --> src/schema.rs:1:1
>   |
> 1 | infer_schema!("dotenv:DATABASE_URL");
>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = help: message: called `Result::unwrap()` on an `Err` value: "Failed to load environment variable DATABASE_URL: environment variable not found"
>   = note: this error originates in a macro outside of the current crate
> 
> error: Could not compile `diesel_demo_step_1_sqlite`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name diesel_demo_step_1_sqlite src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=622c23df1f565981 -C extra-filename=-622c23df1f565981 --out-dir /home/jkolb/diesel/target/debug/deps -L dependency=/home/jkolb/diesel/target/debug/deps --extern dotenv=/home/jkolb/diesel/target/debug/deps/libdotenv-68cc05c844f8f562.rmeta --extern diesel_codegen=/home/jkolb/diesel/target/debug/deps/libdiesel_codegen-22e7d1b09b47ba09.so --extern diesel=/home/jkolb/diesel/target/debug/deps/libdiesel-cfa8db5236072f2a.rmeta -L native=/home/jkolb/diesel/target/debug/build/backtrace-sys-943860c9c514961f/out/.libs` (exit code: 101)

## Checklist

- [ X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
You need to set the `DATABASE_URL` environment variable, or create a `.env` file with that variable.

**Comment by kjeremy** [comment]
I forgot to mention my `.env` contains `DATABASE_URL=test.db`.  I also tried setting the environment variable and it still fails.
