### ISSUE TITLE
[sqlite] Syntax error in generated subexpression

### ISSUE THREAD

**Issue by mfr-itr** [diesel-rs/diesel#1308]
### Versions

- **Rust: 1.21**
- **Diesel: 0.16**
- **Database: sqlite**
- **Operating System: linux**

## Problem Description

My real code has a structure similar to

```rust
    let now = diesel::select(diesel::expression::now);
    let query = diesel::select(diesel::expression::now).filter(diesel::expression::now.eq(now));
    println!("{:?}", diesel::debug_query::<diesel::sqlite::Sqlite,_>(&query).to_string());
```
which produces

`SELECT CURRENT_TIMESTAMP WHERE CURRENT_TIMESTAMP = SELECT CURRENT_TIMESTAMP;`

(syntax error) instead of

`SELECT CURRENT_TIMESTAMP WHERE CURRENT_TIMESTAMP = (SELECT CURRENT_TIMESTAMP);`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

How can I make it produce valid code while waiting for the fix? The sub-expression is a primary key lookup.

**Comment by bgeron** [comment]
It seems that [at least one maintainer](https://gitter.im/diesel-rs/diesel/archives/2018/02/06) says that it's a mistake that your program compiles, until someone has the time to put a lot of work in making this work properly. (Although I think your program is fine.)

I can see two workarounds to allow sub-selects in queries. I'm personally using the second.

### Workaround 1

Write your SQL by hand. I believe you can still use Diesel to convert the results into Rust structs.

### Workaround 2

Wrap your `now` in parentheses *manually*. For instance, you can use the following code

```rust
use diesel::{Expression, AppearsOnTable, QueryResult};
use diesel::backend::Backend;
use diesel::query_builder::{AstPass, QueryFragment};

pub fn parens<T: Expression>(e: T) -> Parens<T> {
    Parens(e)
}

#[derive(Debug, Copy, Clone)]
pub struct Parens<T: Expression>(T);

impl<T: Expression> Expression for Parens<T> {
    type SqlType = T::SqlType;
}

impl<QS, T: AppearsOnTable<QS>> AppearsOnTable<QS> for Parens<T> {}

impl<DB: Backend, T: Expression + QueryFragment<DB>> QueryFragment<DB> for Parens<T> {
    fn walk_ast(&self, mut out: AstPass<DB>) -> QueryResult<()> {
        out.push_sql("(");
        self.0.walk_ast(out.reborrow())?;
        out.push_sql(")");
        Ok(())
    }
}    
```

after which you can simply write `my_query.filter(my_field.eq(parens(now)))`.

**Comment by bgeron** [comment]
If the maintainers agree that this bug should not be fixed, then they should probably close it as WONTFIX or something.

**Comment by sgrif** [comment]
@bgeron You are coming dangerously close to trolling. Last warning.

**Comment by bgeron** [comment]
Sean, I'm a user who had the same problem, I managed to solve it for myself, and so I thought I'd share it with @mfr-itr. And I thought this 2 month old ticket could use an update.

I have to admit I didn't fully understand what you said on Gitter, even after reading it multiple times, so perhaps my summary is wrong. How about you write one and I remove mine?
