### ISSUE TITLE
Insert json in to postgres,  How?

### ISSUE THREAD

**Issue by greenpdx** [diesel-rs/diesel#1310]
### Versions

- **Rust:** 1.21.0
- **Diesel:** 0.16.0
- **Database:**  postgres 9.5.10
- **Operating System** Linux ubuntu 16.04

### Feature Flags

- **diesel:** postgres serde_json
- **diesel_codegen:** posgres

## Problem Description
```
#[derive(Insertable,Debug)]
#[table_name="tst1"]
pub struct NewTst<'a> {
    pub js: &'a Json,
}
```
insertable error

### What are you trying to accomplish?
Trying to insert json into postgres and read json.

### Steps to reproduce

[https://github.com/greenpdx/jsonrpc_diesel](https://github.com/greenpdx/jsonrpc_diesel)
## Checklist

- [x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment]
Use [`serde_json::Value`](https://docs.rs/serde_json/1.0.6/serde_json/enum.Value.html) instead of that `Json` type.
