### ISSUE TITLE
infer_schema!("dontenv:DATABASE_URL") should give an error that is useful to newbies

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1313]
I'm not sure exactly what the metrics should be here (maybe this issue just goes away once proc macros 2.0 is stable and this can be `dotenv!("DATABASE_URL")` again). But there is definitely a class of arguments here which we can be reasonably sure is an error. We should give a helpful error message here if so.

**Comment by sgrif** [comment]
Hey @nrc I know you can't say when things will be stable, but do you think it'll be long enough that we should bother dealing with this?

**Comment by nrc** [comment]
I'm not really sure. In theory, there is not much work to do before we can start stabilisation (mostly making sure libraries can work, especially around hygiene). But there's no one signed up for this, so I'm not sure when it'll ever get done. I'd guess end of 2018, but it is just a guess - could be much sooner if someone jumps on it, or much longer if nobody does.

**Comment by weiznich** [comment]
This should be doable with our current implementation. We simply need to remove [those](https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/src/schema_inference.rs#L19) calls to unwrap and replace them by something returning code with a meaningful error massage using `compile_error!`.

(Probably this should be done after #1231 is merged)

**Comment by sgrif** [comment]
@weiznich FYI -- If you press `y` in Github it will convert the address bar to a "canonical URL" which will continue to work even after I merge your PRs. ;)

**Comment by weiznich** [comment]
Closed as `infer_schema!` is deprecated since a few versions.
