### ISSUE TITLE
Clippy and compile-fail tests are no longer running in CI

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1317]
I have no clue why this is happening, but I noticed that our compile-fail tests have a bad replace pattern in `Cargo.toml` and should be failing, which led me to notice they aren't running at all!

**Comment by killercup** [comment]
You probably need to remove this line

https://github.com/diesel-rs/diesel/blob/209f733b6f8bafb3463c82da9ace336a13ac4a29/.travis.yml#L57

as the `include` key occurs twice
