### ISSUE TITLE
`pg::types::Array` should implement `SqlOrd`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1339]
Turns out that `MAX(int[])` totally works. This is a trivial thing to fix, but I don't want us to start adding a ton of new features until after 1.0 is out. This needs to wait for 1.1.

**Comment by virome** [comment]
With 1.0 released, I'd like to take a stab at this one.

**Comment by killercup** [comment]
Go for it, @virome!

**Comment by sgrif** [comment]
This was fixed by #1449
