### ISSUE TITLE
Bring back `SqlLiteral::bind`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1347]
That method was deprecated when `sql_query` was added, and subsequently removed in 1.0. The interface it provided was impossible to use safely on PG or Oracle. While most places that were using it were probably able to migrate to `sql_query`, it's still a useful method to have. However, for it to be safe to embed elsewhere in the query builder, it needs to *also* be responsible for adding the bind SQL. For example, `sql("id > ? AND name != ?").bind::<Integer, _>(1).bind::<Text, _>("Sean")` should become: `sql("id > ").bind::<Integer, _>(1).sql(" AND name != ").bind::<Text, _>("Sean")`

**Comment by notryanb** [comment]
@sgrif - I'm interested in this after I get some of the documentation / guide issues out of the way.
