### ISSUE TITLE
Explore merging `r2d2-diesel` into Diesel itself

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1348]
This was brought up in the impl period working group channel. The more I think about it, the more I like this idea. I started thinking about this again recently when I was looking at [the "database" keyword on crates.io](https://crates.io/keywords/database). As of the time of this issue, r2d2 shows up before any library that people there are likely actually looking for (diesel, rusqlite, or postgres). It makes sense for that to be the case. Anybody using Diesel (except for sqlite users) or rust-postgres are almost certainly going to rely on r2d2. It'd make sense for them to remove the `database` keyword, but at the same time, neither of those libraries mentions r2d2 in their docs, so I'm not sure where people would find it.

The point of all this is that I'm warming up to the idea of merging `r2d2-diesel` into Diesel itself. I think it still needs some exploration though. I'd like to see how much of the code from https://gitter.im/rust-impl-period/WG-libs-diesel?at=5a1d24628b3a9e2c0c27d69f actually goes away if we moved it into Diesel (just having aliases in Diesel is not good enough IMO, we need to abstract over some of those types to the extent that users don't have to care about them).

If nothing else, having `impl<T: Connection> Connection for PooledConnection<T>` will help a ton, and remove the need for explicit derefs which can be annoying and confusing for newcomers.

I've placed this issue on the 1.1 milestone, but again, this issue is for "exploring" this option, not for sure making it happen.

**Comment by theduke** [comment]
@sgrif thanks for picking up my suggestion and implementing it, it's much appreciated!
