### ISSUE TITLE
`BINARY` should be a supported type name on SQLite

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1355]
It'd be given the `NUMERIC` affinity by SQLite, but I don't think that's relevant. The relevant code for this lives [here](https://github.com/diesel-rs/diesel/blob/52f306ee53dc9646f8247795b769676125739ead/diesel_infer_schema/infer_schema_internals/src/sqlite.rs#L168-L194)

**Comment by kregoslup** [comment]
I would like to work on that issue, although I think I need some guidance. I'm not sure what do you mean by `binary` type name. I checked with SQLite reference here https://www.sqlite.org/datatype3.html point 3.1.1 and there is no binary type except for BLOB. Did you mean binary collating sequences?

**Comment by MarcManiez** [comment]
It's been a while since this there hasn't been activity on this issue so I went and submitted a PR for it. I hope that's ok, @kregoslup!
