### ISSUE TITLE
Support `BEGIN EXCLUSIVE` or `BEGIN IMMEDIATE` for Sqlite.

### ISSUE THREAD

**Issue by Lymia** [diesel-rs/diesel#1356]
Sqlite uses relatively weak locking by default when just `BEGIN` is used to start a transaction. Normally, you would use `BEGIN EXCLUSIVE` or `BEGIN IMMEDIATE` rather than `BEGIN` to do such a transaction with stronger locking, however, Diesel has no support for using these.

**Comment by sgrif** [comment]
Ideally we'd handle this and #408 at the same time.
