### ISSUE TITLE
Error when deriving QueryableByName: 'expected 1 type argument'

### ISSUE THREAD

**Issue by agersant** [diesel-rs/diesel#1368]
### Versions

- **Rust:** Stable
- **Diesel:** 0.99.0
- **Database:** SQLite
- **Operating System:** Windows

### Feature Flags

- **diesel:** sqlite
- **diesel_codegen:** sqlite

## Problem Description
While updating code from https://github.com/agersant/polaris to a newer diesel version and removing deprecated constructs, the suggested steps lead to an unhelpful compilation error.

The offending piece of code is:
```rust
let query = sql::<songs::SqlType>(r#"
	SELECT s.id, s.path, s.parent, s.track_number, s.disc_number, s.title, s.artist, s.album_artist, s.year, s.album, s.artwork
	FROM playlist_songs ps
	LEFT JOIN songs s ON ps.path = s.path
	WHERE ps.playlist = ?
	ORDER BY ps.ordering
"#);
let query = query.clone().bind::<Integer, _>(playlist.id);
```

Where `songs` is a SQL table:
```rust
#[derive(Debug, Queryable, Serialize)]
pub struct Song {
	#[serde(skip_serializing)]
	id: i32,
	pub path: String,
	#[serde(skip_serializing)]
	pub parent: String,
	pub track_number: Option<i32>,
	pub disc_number: Option<i32>,
	pub title: Option<String>,
	pub artist: Option<String>,
	pub album_artist: Option<String>,
	pub year: Option<i32>,
	pub album: Option<String>,
	pub artwork: Option<String>,
	pub duration: Option<i32>,
}
```

Compiling this code with diesel 0.99.0 works but yields the following warning: `warning: use of deprecated item: use `sql_query` if you need bind parameters`.

I updated the code following the warning's recommendation:

```rust
let query = diesel::sql_query(r#"
	(unchanged)
"#);
let query = query.clone().bind::<Integer, _>(playlist.id);
songs = query.get_results(connection.deref())?;
```

I got a (reasonable) error out of it: `the trait `diesel::query_source::QueryableByName<diesel::sqlite::Sqlite>` is not implemented for `index::Song``. Let's add the corresponding derive and table_name marker:

```rust
#[derive(Debug, Queryable, QueryableByName, Serialize)]
#[table_name = "songs"]
pub struct Song {
(unchanged)
}
```

This now fails to compile with an unhelpful error:

```
#[derive(Debug, Queryable, QueryableByName, Serialize)]
                           ^^^^^^^^^^^^^^^ expected 1 type argument
```

### Steps to reproduce

Download the attached crate 
[diesel_qbn.zip](https://github.com/diesel-rs/diesel/files/1546543/diesel_qbn.zip)
and execute `cargo check`.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
Thank you for providing code to reproduce the issue. I am looking at it now.

**Comment by sgrif** [comment]
After pulling the generated code with `cargo expand`, and then compiling that to see what line is causing the issue, it appears this is caused because you have shadowed `Result` with your own type. You can work around this issue by replacing `use errors::*` with something that doesn't import `Result`, and changing the code which used that type to use `errors::Result` instead.

**Comment by agersant** [comment]
Thank you very much for taking the time to investigate!
