### ISSUE TITLE
`#[derive(QueryableByName)]` fails to compile if there is a type called `Result` in scope

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1372]
I really wish people wouldn't shadow types from Rust's prelude, but we should probably explicitly reference `std::result::Result`

**Comment by MarcManiez** [comment]
[This conversation](https://github.com/diesel-rs/diesel/pull/1379) is very thoughtful. I believe this issue has been addressed in 443f43ae and can be closed 🙂 .
