### ISSUE TITLE
We generate a poor error message when `infer_schema!` is used on an empty database

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1393]
Steps to reproduce:

Use `infer_schema!("empty_database_file.sqlite3");`

This should generate no code, but instead it errors out with "unexpected end of macro invocation".

**Comment by sgrif** [comment]
It looks like `infer_schema!` actually finishes fine, but the code it generates is `allow_tables_to_appear_in_same_query!()` which doesn't have a matcher for zero tokens

**Comment by bitemyapp** [comment]
Is "empty database" inclusive of "wrong filepath?" That was what happened in my case.

**Comment by sgrif** [comment]
Yes, pointing to a file which doesn't exist would cause SQLite to create a new database at that location, which would be empty.

**Comment by sgrif** [comment]
This was resolved.
