### ISSUE TITLE
Generate a file called `.keep` instead of `.gitkeep`.

### ISSUE THREAD

**Issue by sanmai-NL** [diesel-rs/diesel#1399]
```sh 
diesel migration generate
```
creates a `.gitkeep` as well. Do not do this if the crate isn’t under Git VCS.

**Comment by sgrif** [comment]
I guess we can call the file `.keep`.

**Comment by ocamlmycaml** [comment]
I’d like to take a stab at this issue. This would be my first rust project contribution here so i’m hoping this will be ok for that as well

**Comment by joelgallant** [comment]
If this was changed, could it also remove the old `.gitkeep` file?

**Comment by ocamlmycaml** [comment]
> If this was changed, could it also remove the old `.gitkeep` file?

hmm is that a good idea? it'll be dead code after you use `diesel_cli` once (in the newer release). I guess it's ok if I can add a TODO or issue to clean it up in a much later release

**Comment by hcheng826** [comment]
Sorry might be a dump question, what does the `.keep` file do? Is it supposed to be uploaded to the repo? For me it's an empty file. Thanks!

**Comment by Arjentix** [comment]
@hcheng826 , I come here with the same question. After googling a little bit more I've found the asnwer.

So `git` does not track empty directories. And by placing some file in directory we can make `git` track it. So `.keep` is just a stub-file for cases when `migrations` directory is empty.

So you can either delete this file if you have some files in `migrations`, or commit if you don't, or commit just for fun.

[Source](https://www.reddit.com/r/linuxquestions/comments/dae860/what_is_the_keep_file_and_why_do_i_see_it_in_many/).

**Comment by hcheng826** [comment]
@Arjentix Ah I get it. Appreciate the sharing!
