### ISSUE TITLE
`#[belongs_to]` doesn't support composite foreign key

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#1413]
The title is describing problem.

Suppose you have this schema
```sql
CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY
  -- ...
);
CREATE TABLE groups (
  id SERIAL NOT NULL PRIMARY KEY
  -- ...
);
CREATE TABLE group_members (
  user_id INTEGER NOT NULL REFERENCES users(id),
  group_id INTEGER NOT NULL REFERENCES groups(id),
 -- ...
  PRIMARY KEY (user_id, group_id)
);

CREATE TABLE member_comments (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  group_id INTEGER NOT NULL REFERENCES groups(id)
 -- ...
);
```
and you'd like to derive `Association` to member_description

```Rust
#[derive(Queriable, Ideintfiable)]
#[foreign_key(group_id, user_id)]
struct GroupMember {
  group_id: i32,
  user_id, i32,
}

#[derive(Queriable, Identifiable, Associations)]
#[belongs_to(GroupMember, foreign_key = ???)]
struct MemberComment {
  id: i32,
  group_id: i32,
  user_id: i32,
}
```

[current implementation](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/associations.rs#L44) supports only one foreign key. Are there any chance to allow composite foreign key in `belongs_to` attr?

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
At the moment we would not be able to support composite foreign keys here without making a breaking change to [`BelongsTo`](http://docs.diesel.rs/diesel/associations/trait.BelongsTo.html). At the moment we're not considering anything that would require a major version bump.

**Comment by KeenS** [comment]
Thank you. I'll use surrogate keys.
