### ISSUE TITLE
compile error on deriving `Identifiable`

### ISSUE THREAD

**Issue by qmx** [diesel-rs/diesel#1438]
### Versions

- **Rust:** `rustc 1.23.0-beta.2 (c9107ee93 2017-12-08)`
- **Diesel:** 1.0.0-rc1
- **Database:** sqlite
- **Operating System** linux x86_64

### Feature Flags

- **diesel:** sqlite
- **diesel_codegen:**

### What are you trying to accomplish?

trying to follow the association documentation https://docs.diesel.rs/diesel/associations/index.html and get a compilation error

### What is the expected output?

no build errors

### What is the actual output?

```
   Compiling association_error v0.1.0 (file:///home/qmx/tmp/association_error)
error[E0433]: failed to resolve. Use of undeclared type or module `payees`
  --> src/lib.rs:13:17
   |
13 | #[derive(Debug, Identifiable)]
   |                 ^^^^^^^^^^^^ Use of undeclared type or module `payees`
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors

error: Could not compile `association_error`.

To learn more, run the command again with --verbose.
```

### Steps to reproduce

fully reproduceable repo here https://github.com/qmx/diesel-association-error-repro

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
You need to ensure that your `payees` module is in scope, with a line such as `use schema::payees;` (Assuming that you have your `table!` or `infer_schema!` declarations in a module called `schema`).

**Comment by qmx** [comment]
good call, any suggestion on how to make this more obvious at the docs? Happy to put a PR together, as I've read it a handful times and couldn't see.

**Comment by sgrif** [comment]
We mention this in a few other places (I think the associations docs mentions it?) we could probably put that same wording in the docs for `Identifiable`.

**Comment by jblachly** [comment]
> We mention this in a few other places (I think the associations docs mentions it?) we could probably put that same wording in the docs for `Identifiable`.

Would also be nice in the guide (https://diesel.rs/guides/all-about-updates.html), example code for which puts everything (schema def macro and struct) together in `lib.rs` so that it is in scope; others following along since the getting started guide likely have the schema def macros in a separate file, which, if not brought in scope, leads to compilation failure as above.

Liking Diesel so far, thanks

**Comment by weiznich** [comment]
@jblachly We are happy to receive PR's that improve the guides. See [this](https://github.com/sgrif/diesel.rs-website/) repository for the website source code.

**Comment by jblachly** [comment]
> @jblachly We are happy to receive PR's that improve the guides. See [this](https://github.com/sgrif/diesel.rs-website/) repository for the website source code.

_et voila_
