### ISSUE TITLE
Statically linking libsqlite3-sys

### ISSUE THREAD

**Issue by souvik1997** [diesel-rs/diesel#1461]
`libsqlite3-sys` has a feature called `bundled` that builds and statically links libsqlite3. Would it be possible to add a feature to `diesel` to enable this feature of `libsqlite3-sys`?

**Comment by sgrif** [comment]
You can add `libsqlite3-sys` to your `Cargo.toml` and specify whatever features you want. See #829 and other times this has been brought up in the past.
