### ISSUE TITLE
Would you be interested in being featured on Diesel's website?

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1470]
I'm considering adding a section to the website that highlights a few production users. If you're interested in being included in this list, please reply to this issue with the name of your company, and a link to your logo that we can use (SVG preferred)

**Comment by bradurani** [comment]
Procore
https://camo.githubusercontent.com/28339e0cd0c4f5dd
b3b4f63f369ce4e38a8cb7bc/68747470733a2f2f7777772e70726f636f72652e636f6d2f696d616765732f70726f636f72655f6c6f676f2e706e67

**Comment by sgrif** [comment]
crates.io
I don't have a high res or vector logo on me, I'll have to track one down.

**Comment by KingOfThePirates** [comment]
I'm not a candidate, but I care about the rust community so I'd like to offer unsolicited advice. I like the idea. But one thing that always makes me turn away is when people link broken links or outdated information. I haven't thought the solution through, but I wanted to share the idea, just in case it was easy for you to implement / add into your website: automate the check on the last updated date of the projects you link to. If they aren't active projects and they've become stale, don't use them as examples. If there aren't enough active projects using Diesel, work on getting more people to use it. Until you have more than a couple / several, then don't activate the page and hide the link to the page of live projects that use Diesel.

I don't know how nitpicky this is, but I mean well. If it won't work to do it that way then don't do it. I haven't tested this out and don't know the implications :)

**Comment by pgab** [comment]
We are using Diesel and are going to ship it to customers within February.
https://www.giga-infosystems.com
https://gist.github.com/pgab/d1d23cd1d6fd1d5ac9e04760daba13c2

**Comment by sgrif** [comment]
I'm going to revisit this in the future, but I'll need to pay our designer to make this happen and I don't have the cash for that right now.
