### ISSUE TITLE
Windows: cargo install diesel-cli works but...

### ISSUE THREAD

**Issue by tensor-programming** [diesel-rs/diesel#1477]
I am on windows 10, and using the MSVC toolchain with latest nightly/beta and stable release.  
For a while I had the Postgres from BigSQL installed and then I removed it in favor of the official installation.  After doing this, I was able to compile the Diesel CLI fine, but now when I run it I get a dialogue box that opens up and says: 

`diesel.exe - System Error
The code execution cannot proceed because LIBPQ.dll was not found.  Reinstalling the program may fix this problem.`

I have tried uninstalling and reinstalling Diesel as well as PostgreSQL multiple times to no effect.  The PGSQL installation seems to work; I've used it with elixir ecto multiple times already.  I was considering removing rust entirely to remove any files from the old failed diesel-cli installations but this would be an extreme step.  Anyone have any ideas?  

BTW I am only installing the PG backend using `cargo install diesel_cli --no-default-features --features postgres`.  I haven't tried SQLite or MySQL.

**Comment by sgrif** [comment]
You need to make sure that `libpq.dll` is on your `%PATH%`.

**Comment by tensor-programming** [comment]
It is on my path. that's is the problem; I'm not sure why you closed this issue when it hasn't been resolved at all.

**Comment by weiznich** [comment]
>  I'm not sure why you closed this issue when it hasn't been resolved 

This issue was closed because diesels policy for open issues is the following:

> Open issues in this repo should represent something that is actionable, and that you could reasonably open a pull request to fix.

This is clearly a issue with your current setup. We will happily help you there to figure these things out, but this discussion does not belong to the issue tracker. Use our gitter room for such questions.

**Comment by sgrif** [comment]
There's nothing wrong with discussing on the issue tracker, but as mentioned the action we can take is answering your question. Typically we close issues at that point, as more often than not people don't come back and say "this fully answered my question, thanks". I'm glad to hear that you got it sorted out.

**Comment by venkat125** [comment]
> 
> 
> It is on my path. that's is the problem; I'm not sure why you closed this issue when it hasn't been resolved at all.
> I did resolve this however by using vcpkg to install a new pqlib file and then pointed cargo towards it.
> 
> I understand that you probably are sick of listening to windows users complain about their terrible ecosystem but seriously...

how to install pqlib file using vcpkg and point to cargo?

**Comment by flipbit03** [comment]
I have had a similar issue with Rust's Stable 1.42 and Windows 10

my diesel_cli tool wouldn't compile, complaining about a missing libql.lib on LINK step.

after putting both PostgreSQL's install BIN and **LIB** folders to the path, the tool compiled and linked without any hiccups.

Hope that helps someone down the line o/

**Comment by KoltesDigital** [comment]
I've encountered this issue as well.

At first, `diesel_cli` was successfully installed using [`PQ_LIB_DIR` environment variable](https://stackoverflow.com/a/65880244/14098985), and required `<pg root>/bin` to be in `PATH` to run. So Diesel CLI was working; however, `cargo build` on my project failed because `libpq.lib` is not found, therefore not taking `PQ_LIB_DIR` into account.

The solution is to add the `<pg root>/lib` to the compilers' library search paths, using `CARGO_ENCODED_RUSTFLAGS` environment variables (`ENCODED` because there is a space character in the path). Doing so also works for installing `diesel_cli`, so no need for `PQ_LIB_DIR` anymore.

Takeaway in PowerShell:

```ps1
# Machine-wide change, to directly start programs from the file explorer.
[Environment]::SetEnvironmentVariable(
    'Path',
    [Environment]::GetEnvironmentVariable(
        'Path',
        [EnvironmentVariableTarget]::Machine
    ) + ';C:\Program Files\PostgreSQL\14\bin',
    [EnvironmentVariableTarget]::Machine
)

# Only for the current session. Feel free to make it machine-wide, or put it in a profile script.
$env:CARGO_ENCODED_RUSTFLAGS = "-L`u{1f}C:\Program Files\PostgreSQL\14\lib"

# They now work!
cargo install diesel_cli --no-default-features --features postgres
cargo build
```

I have **not** put `<pg root>/lib` in `PATH`: only the former is needed to load the DLL when programs start (e.g. Diesel CLI or my project's binary).

Hope that helps too.
