### ISSUE TITLE
Write tests for `#[derive(Associations)]

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#1484]
While porting `#[derive(Associations)]` from the old macro_rules based derive to a normal procedural macro derive in #1468  we noticed that there are no tests for this derive. 
We should definitively write some tests to check if everything works as assumed.

**Comment by weiznich** [comment]
There are already [tests](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/tests/associations.rs) in `diesel_derives`

**Comment by sgrif** [comment]
They could stand to be a lot more exhaustive. For starters, there are no tests for having more than one association, using tuple structs, cases where the foreign key field is named differently than the foreign key column.
