### ISSUE TITLE
Do we need ToSql Cow to require T::Owned = ToSql?

### ISSUE THREAD

**Issue by SoniEx2** [diesel-rs/diesel#1498]
## Problem Description

It seems redundant (and annoying) that T::Owned needs ToSql, especially considering that there isn't a blanket ToSql for Borrow types. Do we need this requirement?

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
Good point. No we don't.

**Comment by sgrif** [comment]
Fixed by #1499
