### ISSUE TITLE
Unable to compile diesel v1.1.1

### ISSUE THREAD

**Issue by am0d** [diesel-rs/diesel#1508]
### Versions

- **Rust:** Nightly-2018-01-20
- **Diesel:** v1.1.1
- **Database:** Postgres
- **Operating System** Linux

### Feature Flags

- **diesel:** postgres, chrono, r2d2

## Problem Description
Unable to compile - output when compiling is:
```
   Compiling diesel v1.1.1
error[E0603]: trait `Error` is private
  --> /home/am0d/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.1.1/src/r2d2.rs:11:22
   |
11 | pub type PoolError = self::r2d2::Error;
   |                      ^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

### What are you trying to accomplish?
Compile app.

### What is the expected output?
No errors.

### What is the actual output?
See above.

### Are you seeing any additional errors?
No.

### Steps to reproduce
Attempt to compile an application with a dependency on diesel v1.1.1 with the r2d2 feature enabled.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment]
I've failed to reproduce this. Which could you post a complete minimal reproducing example(including the Cargo.lock file) somewhere?

**Comment by weiznich** [comment]
I was able to reproduce this.This is caused by a incompatible r2d2 version in your dependency tree. `cargo update -p r2d2` fixed this for me.

**Comment by am0d** [comment]
Thank you, that did fix it for me.  I was still on r2d2 0.7.4, upgrading to 0.8.2 fixed the build for me.
