### ISSUE TITLE
diesel migration down

### ISSUE THREAD

**Issue by coder543** [diesel-rs/diesel#1509]
I quickly glanced through the issues (open and closed), and didn't see anything mention this, so I figured I would. Would it make sense for there to be a subcommand on the diesel CLI that goes all the way down? 

I'm not sure how to use the `down.sql` files usefully without a command that will run through the migrations in reverse and down all of them. Instead, I have a script that will just drop the entire `public` schema, recreate it, and then run the diesel migrations when I want a clean starting point.

If I could use the diesel CLI itself to run all of the `down.sql` files in reverse, that would be really nice!

Maybe I'm missing something obvious.

**Comment by sgrif** [comment]
You can revert a single migration with `diesel migration revert`. You can reset your whole schema with `diesel database reset`. You can run `diesel --help` for a full list of commands.
