### ISSUE TITLE
Changing order of Table structs shouldn't affect compilation

### ISSUE THREAD

**Issue by allowthere** [diesel-rs/diesel#1518]
### Versions

- **Rust:** rustc 1.25.0-nightly (ae920dcc9 2018-01-22)
- **Diesel:** 1.1.0
- **Database:** sqlite
- **Operating System** Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

Changing order of Table structs shouldn't affect compilation

models.rs compiles when it looks like:

````
struct Db { 
    pub id: i32,
    pub name: String,
}
````
But not when it looks like

````
struct Db { 
    pub name: String,
    pub id: i32,
}
````

### Are you seeing any additional errors?

     the trait `diesel::deserialize::FromSql<diesel::sql_types::Integer, _>` is not implemented for `*const str`

**Comment by sgrif** [comment]
Thanks, but this is the documented behavior of `#[derive(Queryable)]`, and isn't something that will change any time soon. The type of a SQL query is represented as a tuple, which necessitates order dependence. Additionally, `Queryable` *does not* mean one-to-one with a row in a database table, meaning field names aren't particularly useful there.

If you don't want field order to be important, I recommend avoiding `#[derive(Queryable)]` and implementing the trait directly instead.

**Comment by allowthere** [comment]
Thanks, but maybe it would be helpful to point that out in the [tutorial](http://diesel.rs/guides/getting-started/), as a beginner (at diesel) wouldn't realize that struct order is important.
