### ISSUE TITLE
Insertable and chrono::DateTime<Utc> does not work

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#1541]
I am trying to make my model insertable but I have a error which I don't know how to solve.

```rust
use diesel::prelude::*;
use chrono;
use chrono::prelude::*;
use super::schema::*;

#[derive(Debug, Clone, Queryable, Insertable)]
#[table_name = "punishments"]
pub struct Punishment {
    pub user_id: i32,
    pub server_id: i32,
    pub start_time: DateTime<Utc>,
    pub duration: chrono::Duration,
    pub reason: String,
}
```

```
models.rs:6:35
  |
6 | #[derive(Debug, Clone, Queryable, Insertable)]
  |                                   ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `chrono::DateTime<chrono::Utc>`
  |
  = note: required because of the requirements on the impl of `diesel::Expression` for `&'insert chrono::DateTime<chrono::Utc>`
  = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Text>` for `&'insert chrono::DateTime<chrono::Utc>`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: the trait bound `chrono::Duration: diesel::Expression` is not satisfied
```

I use:

- `sqlite`
- `diesel = "1"`

**Comment by sgrif** [comment]
`Datetime` does not have a time xone. The appropriate type is `NaiveDateTime`

**Comment by vityafx** [comment]
Can we have a list of all available types for use with diesel? And also with all backends (pg, sqlite, mysql, and so on)? This would be very useful.

**Comment by vityafx** [comment]
Tried to change to `NaiveDateTime`:

```rust
error[E0277]: the trait bound `chrono::NaiveDateTime: diesel::Expression` is not satisfied
 --> models.rs:6:35
  |
6 | #[derive(Debug, Clone, Queryable, Insertable)]
  |                                   ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `chrono::NaiveDateTime`
  |
  = note: required because of the requirements on the impl of `diesel::Expression` for `&chrono::NaiveDateTime`
  = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Text>` for `&chrono::NaiveDateTime`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by Eijebong** [comment]
You're probably missing the `chrono` feature on diesel

**Comment by vityafx** [comment]
@Eijebong 
I don't miss it:

```toml
r2d2-diesel = "1"
r2d2 = "0.8"

[dependencies.diesel]
version = "1"
features = ["sqlite", "chrono"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]
```

**Comment by vityafx** [comment]
The diesel migration sql script:

```sql
-- Your SQL goes here
CREATE TABLE punishments (
    user_id INTEGER NOT NULL,
    server_id INTEGER NOT NULL,
    start_time TEXT NOT NULL,
    duration TEXT NOT NULL,
    reason TEXT NOT NULL,
    PRIMARY KEY (user_id, server_id)
)
```

**Comment by Eijebong** [comment]
Ha, that's why, you have to tell diesel this is a datetime. Either change the type of `start_time` to `DATETIME` (or is it `TIMESTAMP` ?) in your migration or lie to diesel when you describe the table with `table!` and replace `Text` by `Timestamp` for that column (can't do that if you're using `infer_schema!`)

**Comment by vityafx** [comment]
Checked again - there is nothing like `FromSql<Text, Sqlite>`, I was wrong. But there are two more questions I need answers for.

**Comment by sgrif** [comment]
http://docs.diesel.rs/diesel/sql_types/struct.Timestamp.html

You'll need to call your type `TIMESTAMP` or `DATETIME` on the SQL end for `infer_schema!` to infer that you want to store that sort of data in this column.

**Comment by vityafx** [comment]
Thank you. I somehow thought that the `DATETIME` is not proper type for the sqlite 3 database. Actually it is, so everything is fine. As for infer_schema, I don't use it but use `print-schema` instead as it was suggested in the `diesel.rs` website.

**Comment by sgrif** [comment]
`infer_schema!` and `diesel print-schema` use the same logic. I was referring to either one. ;)
