### ISSUE TITLE
How can I store `chrono::Duration` in the sqlite 3 database with diesel?

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#1542]
I wanna have a duration field in my table. However, I don't know what type to use for it, because, looking at [chrono types implementation](https://github.com/diesel-rs/diesel/blob/master/diesel/src/sqlite/types/date_and_time/chrono.rs) for sqlite I think it is impossible.
According to the [`chrono::Duration` documentation](https://docs.rs/chrono/0.4.0/chrono
/struct.Duration.html), it can be stored as `BIGINTEGER` in the sqlite3 table, since it is:

> ISO 8601 time duration with nanosecond precision. This also allows for the negative duration; see individual methods for details.

So, my guess is to implement that via storing in sqlite3 table with `BIGINTEGER` type and implementing `FromSql` and `ToSql` traits for the `chrono::Duration` by calling the [`chrono::Duration::nanoseconds()`](https://docs.rs/chrono/0.4.0/chrono/struct.Duration.html#method.nanoseconds) static method.

**Comment by weiznich** [comment]
You will need to add a [new type wrapper](https://github.com/rust-unofficial/patterns/blob/master/patterns/newtype.md) for the `chrono::Duration` type. Derive `AsExpression` and `FromSqlRow` for that type. After that you need to implement `ToSql` and `FromSql` for your new type in respect to `BIGINTEGER`. 
See [this testcase](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs) as an example for supporting custom rust types.

**Comment by vityafx** [comment]
@weiznich Can't I simply implement `FromSql` and `Tosql` for the `chrono::Duration` as it is done for the `NaiveDateTime`, `NaiveDate` and `NaiveTime` structures?

**Comment by weiznich** [comment]
No you can't because you own neither `chrono::Duration` nor `FromSql`/`ToSql`

**Comment by vityafx** [comment]
Oh, well, I was not clear enough :) I wanted this to be done in the `diesel` itself if it is not. I think it is not, especially for `v.1.1.1`, so [I did my own implementation](https://github.com/vityafx/diesel/commit/e44698f2567bdd525f432d9ed80178fc584f0250).

**Comment by vityafx** [comment]
@weiznich Could you help me with implementing this in my fork? It seems to me it does not work even so:

```
models.rs:6:35
  |
6 | #[derive(Debug, Clone, Queryable, Insertable)]
  |                                   ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `chrono::Duration`
  |
  = note: required because of the requirements on the impl of `diesel::Expression` for `&chrono::Duration`
  = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::BigInt>` for `&chrono::Duration`
```

**Comment by weiznich** [comment]
You need to add impl for `AsExpression` for `&'a chrono::Duration` similar to that ones in [this file](https://github.com/diesel-rs/diesel/blob/master/diesel/src/type_impls/date_and_time.rs)

(I'm not sure if `chrono::Duration` will be accepted as a supported type for sqlite.)

**Comment by vityafx** [comment]
@weiznich looks like it worked, thanks.

**Comment by sgrif** [comment]
I don't think we would support duration support for SQLite.

**Comment by vityafx** [comment]
@sgrif could you explain please? Why not?

**Comment by sgrif** [comment]
We don't typically support types that don't have a direct database mapping to a SQL type. Even if we did, there's no obvious way to store it, and you wouldn't be able to do anything useful with it.

**Comment by vityafx** [comment]
@sgrif This is sad. I have implemented `chrono::Duration` for both `postgresql` and `sqlite` backends, all tests are passed and everything works good. the `chrono::Duration` type is nothing more but just `i64` value with nanoseconds, so it absolutely fits into the `BigInteger` types of SQL which is exactly 8 bytes for both `postgresql` and `sqlite`.

**Comment by vityafx** [comment]
@sgrif So, what is wrong with `Duration` exactly, since it is just a number which can be stored perfectly fine? You still think it is so bad to have an implementation for it?

**Comment by sgrif** [comment]
SQLite has no corresponding interval type to store it as. I'd expect `now + Duration` to work if we supported durations. It wouldn't.

**Comment by vityafx** [comment]
@sgrif what do you think about that? https://github.com/vityafx/diesel-chrono-duration

Could you review it please? :-[
