### ISSUE TITLE
Unable to build for testing and contributing

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#1543]
I have a problem: [the diesel framework does not have a database serialization for `chrono::Duration`](https://github.com/diesel-rs/diesel/issues/1542)
So, I forked the project and made [changes as I wanted](https://github.com/vityafx/diesel/commit/e44698f2567bdd525f432d9ed80178fc584f0250). However, I can't run `cargo test`:

```
$ cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling all_about_updates v0.1.0 (file:///home/user/diesel/examples/postgres/all_about_updates)
   Compiling diesel_demo_step_2_mysql v0.1.0 (file:///home/user/diesel/examples/mysql/getting_started_step_2)
   Compiling diesel_demo_step_1_mysql v0.1.0 (file:///home/user/diesel/examples/mysql/getting_started_step_1)
   Compiling all_about_inserts v0.1.0 (file:///home/user/diesel/examples/postgres/all_about_inserts)
   Compiling diesel_demo_step_2_pg v0.1.0 (file:///home/user/diesel/examples/postgres/getting_started_step_2)
   Compiling diesel_demo_step_3_mysql v0.1.0 (file:///home/user/diesel/examples/mysql/getting_started_step_3)
   Compiling diesel_demo_step_1_pg v0.1.0 (file:///home/user/diesel/examples/postgres/getting_started_step_1)
error[E0282]: type annotations needed
  --> examples/postgres/all_about_updates/src/lib.rs:45:9
   |
45 |         debug_query(&diesel::update(posts).set(draft.eq(false))).to_string()
   |         ^^^^^^^^^^^ cannot infer type for `DB`

error: aborting due to previous error
```

I can't even add my diesel for as dependency to my project which uses it so I can be at least sure that it works as expected.
How to test it and how to add my fork as a dependency instead of it from the using `crates-io`?

Versions:
- rustc 1.25.0-nightly (0c6091fbd 2018-02-04)
- rustc 1.23.0 (766bd11c8 2018-01-01)
- diesel 1.1.1

**Comment by weiznich** [comment]
Please add informations about what compiler version you tried to use

**Comment by Eijebong** [comment]
You need to enable at least one feature. `cargo test --features sqlite` for example

**Comment by vityafx** [comment]
@weiznich I have added the information you asked for.
@Eijebong The result is still the same. I had tried that before, actually. This was what I started with.

**Comment by Eijebong** [comment]
Ha you're running tests from the root, that's probably why. We don't do that. You should use `bin/test` instead to run all tests

**Comment by vityafx** [comment]
@Eijebong well, was written it somewhere and I missed that? :)
Okay, what about using it in my project then? How can I add my local fork as a dependency correctly?

**Comment by Eijebong** [comment]
It's written there https://github.com/diesel-rs/diesel/blob/master/CONTRIBUTING.md#setting-up-diesel-locally (5.)

To use it in your project, you can add a [`[replace]`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-replace-section) section in your Cargo.toml

**Comment by Eijebong** [comment]
You also need to pin your compiler to the same version we're using, you can find it there: https://github.com/diesel-rs/diesel/blob/master/.travis.yml#L45

**Comment by vityafx** [comment]
@Eijebong could you provide an example of how I add the `diesel` into the `[replace]` section please? I tried that today but with no success:

```toml
[dependencies.diesel]
version = "1"
features = ["sqlite", "chrono"]

[replace]
"diesel:1.1.1" = { path = "../../diesel/" }
```

According to what I see during the compilation, my `replace` section is ignored.

**Comment by weiznich** [comment]
A replace section will only work in a workspace as far as I know, so you need to add [workspace] to Cargo.toml.

**Comment by vityafx** [comment]
I have a project without workspaces which uses `diesel`. Can I use local `diesel` there?

**Comment by weiznich** [comment]
Just add an line with `[workspace]` into your `Cargo.toml` and it should work. Alternatively you could try to use a [`[patch]`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section) section. (I've never tried this)

**Comment by vityafx** [comment]
The `patch` section does not work for me at all, looks like it is not even parsed.

**Comment by vityafx** [comment]
Fixed that by adding a `diesel_derives` as a replacement, so finally it looks like:

```toml
[dependencies.diesel]
version = "1"
features = ["sqlite", "chrono"]

[replace]
"diesel:1.1.1" = { path = "../../diesel/diesel" }
"diesel_derives:1.1.0" = { path = "../../diesel/diesel_derives" }

[workspace]
```

**Comment by akatech** [comment]
Have the same bug:
 error: cannot find macro `impl_Insertable!` in this scope
 --> <proc-macro source code>:1:1
I need help
