### ISSUE TITLE
Problem:something wrong with official guide.

### ISSUE THREAD

**Issue by hoobean1996** [diesel-rs/diesel#1551]
### Versions
- **Rust:**  Nightly
- **Diesel:** 1.0.0
- **Database:** MySQL5.7
- **Operating System** OSX

## Problem Description
Follow Official Guide,When I Finished `**show_posts.rs**`,and I execute `**cargo run --bin show_posts**`,a error occurs.

--> src/bin/show_posts.rs:14:10
   |
14 |         .load::<Post>(&connection)
   |          ^^^^ the trait `diesel::deserialize::FromSql<diesel::sql_types::BigInt, diesel::mysql::Mysql>` is not implemented for `i32`
   |

What  does this mean?
How can I solve it?

Thanks very much.

**Comment by brandur** [comment]
`BigInt` is representative of the `BIGINT` SQL type. You can see from [the MySQL documentation on integer types here](https://dev.mysql.com/doc/refman/5.7/en/integer-types.html) that `BIGINT` is an 8-byte integer. That's inherently incompatible with an `i32` which is 32 bits (or 4 bytes).

Solution: try `i64` instead.

(Disclaimer: I'm not a maintainer of this project, but hopefully this is helpful.)

**Comment by sgrif** [comment]
Above comment is correct. Either use `i64` on the Rust side, or change the type to `INTEGER` on the SQL side.

**Comment by hoobean1996** [comment]
Thanks,

**Comment by cjen07** [comment]
Thanks, just solved my problem.
