### ISSUE TITLE
Comparing Errors

### ISSUE THREAD

**Issue by derekdreery** [diesel-rs/diesel#1562]
It would be helpful if it were possible to compare errors using (Partial)Eq, and also implement things like Hash/Ord for datastructures. I'm not sure if this is really possible, but if not it may be possible to work around this by implementing PartialEq by making any trait object comparisons falsey.

What are your thoughts on this? Do you think it would be useful?

**Comment by killercup** [comment]
What's your use case? Matching on the error variant is usually the way to go.

**Comment by derekdreery** [comment]
I'm trying to create my own [ErrorKind] setting the ConnectionError as the cause.

[ErrorKind]: https://boats.gitlab.io/failure/error-errorkind.html

**Comment by derekdreery** [comment]
Nice one!!
