### ISSUE TITLE
Document our policy for minimum supported Rust versions and when they can be bumped

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1576]
This has been discussed internally some, but we should figure out the right place to document it. Last time we discussed it, we decided the following:

- Bumping the minimum Rust version is not considered a major breaking change.
- The minimum version should only be bumped if we have a good reason
  - Convenience/cleaning up code is not a good reason

I think we should also add to the policy that we will not bump the minimum Rust version in a patch version of Diesel.

/cc @diesel-rs/core Does that sound about right?

I think we should probably document this in two places. One for users, and one for contributors. For the user-facing docs, perhaps the top of the changelog is a good place to document it? Right after where we specify our semver policy, we could add: "Increasing the minimum supported version of Rust is not considered a breaking change, but it will only be done in major or minor versions.".

For contributors I think we need to say something like "It is ok to increase the minimum supported version of Rust, but only if it is *required* to implement your feature. If it is possible to implement without relying on more recent features, you should do so". I have no clue where we'd document that.

We should also probably figure out what our current minimum supported version is and add it to the test matrix (maybe only check that things compile, don't need another full run)

**Comment by tcmal** [comment]
It seems like this is already being done with `nightly-2018-02-02`, Just tried compiling with `nightly-2018-02-01` and it failed with `can't find crate for 'rustc_const_eval'` (clippy-lints).

**Comment by sgrif** [comment]
That's an irrelevant error, the version of clippy we use is tied to a specific nightly, and isn't expected to work with other versions.

**Comment by tcmal** [comment]
Ah, my bad.

**Comment by pksunkara** [comment]
What are you thinking right now? `clap` only promises supports for the last 2 versions of rust. Which means we can't bump MSRV past 1.48 now. Anything before that is free game.

**Comment by weiznich** [comment]
As a first step we need to define what MSRV does actually mean for us. Does it mean that all versions of our dependencies need to support our MSRV or not? I tend to define it more like: There is some set of dependency versions that support our MSRV, but that's not necessarily the latest or default version picked by cargo. I would also add that we test this in our CI using `-Z minimal-versions` to resolve all dependencies to their minimal supported version. This should be somehow documented as part of our changelog?
Now to the question when to bump that version: Here I wouldn't go for some concrete rule like the last 2 rust version or something like that. Instead I would say: We don't bump the minimal supported rust version to follow some general scheme. Instead it's fine to bump the minimal supported rust version to use some newly released feature if there is a clear benefit in using this feature. That means if we could write equal code without a certain feature we just should not depend on that feature, but if we need some specific feature (for example some future async fix, whatever) we should not need to wait til it's available. As a general rule I would state that bumping the MSRV is only something that is acceptable for a new minor version of diesel. As this would be a feature release nerveless, persons that have a specific requirements for MSRV's can just continue to use the older version.

**Comment by pksunkara** [comment]
> We don't bump the minimal supported rust version to follow some general scheme. ...

Yeah, that is what clap does. But the additional requirement is that we don't use a new feature from the recent 2 versions of rust. That way it makes sure that the MSRV even when bumped is always 2 versions away.

**Comment by weiznich** [comment]
I see currently no driving motivation to add such a additional constraint to our policy. I would leave open the possibility to depend on the latest rust stable version as long as possible, as such rules place a quite serve constraint on possible designs and feature additions. I mean as long as nobody requests it and put at least some amount of work into this requirement it does not seem to be that important for our users.

**Comment by weiznich** [comment]
We now explicitly state on top of our [changelog page](http://diesel.rs/changelog.html) that:

> All user visible changes to this project will be documented in this file. This project adheres to Semantic Versioning, as described for Rust libraries in RFC #1105 For any named minimal supported Rust version we guarantee that it is possible to build Diesel with the default features enabled using some set of dependencies. Those set of dependencies is not necessarily an up to date version of the specific dependency. We check this by using the unstable -Z minimal-version cargo flag. Increasing the minimal supported Rust version will always be coupled at least with a minor release.

Which essentially means that:

* We document a MSRV (also by setting the corresponding `Cargo.toml` field)
* We can bump that version in minor releases (As of now we do that whenever we feel that a new feature simplifies some implementation in diesel or allows us to improve a certain public API)
* We do not consider updates from a dependency as diesel-MSRV breaking, as long as it is possible to build diesel with some version of that dependency.

I feel that this pretty much covers what this issue was supposed to decide
