### ISSUE TITLE
Read & Write over separate connection

### ISSUE THREAD

**Issue by flip111** [diesel-rs/diesel#1588]
Is there any support to separate read and write queries over different connections? This is useful for Sqlite where you can write with one connection but read with multiple using [write ahead logging](https://sqlite.org/wal.html). I think this could also be useful if you have one write-master database server and a couple of read-slave database servers (obviously another platform than sqlite). Is there any method to inspect querybuilder-queries or handwritten queries at compile time to see if they are read or write?

**Comment by sgrif** [comment]
> Is there any support to separate read and write queries over different connections?

Yes. This would work the same as any other database driver. Create users with read access vs read/write access, and establish the connection using those.

> Is there any method to inspect querybuilder-queries or handwritten queries at compile time to see if they are read or write?

No, there is not.
