### ISSUE TITLE
`diesel database --help` inconsistent with completion output

### ISSUE THREAD

**Issue by taktoa** [diesel-rs/diesel#1593]
Steps to reproduce:

- Run `cargo install diesel_cli`.
- Run `diesel bash-completion > diesel-completions.bash; source diesel-completions.bash` in Bash or ZSH.
- Run `diesel database --help`. The output lists three subcommands: `help`, `reset`, and `setup`.
- Type `diesel database <TAB>`. The completion menu gives _four_ subcommands: `help`, `reset`, `setup`, and `drop`!
- Running `diesel database drop --help` indicates that there is indeed such a command, but it is hidden!

I compiled `diesel_cli` version `1.1.0` under `rustc 1.26.0-nightly (322d7f7b9 2018-02-25)` by running `cargo install diesel_cli`. I am on NixOS, which is a complicating factor in a lot of cases, but I don't think that should affect this bug. If you can't reproduce it I can try to get more information on why it is happening.

I suggest that however it is you are generating the `--help` output for commands, it should be made automatically consistent with the completions.

**Comment by weiznich** [comment]
Our cli arguments are entirely handled by [clap](https://github.com/kbknapp/clap-rs). Those crate generates help and bash completions for us. 
`diesel database drop` is marked as [hidden](https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/cli.rs#L81) subcommand, therefore it is not shown in `diesel database --help`
I'm not sure if that's the intended of clap or if we should report it as bug there.

**Comment by taktoa** [comment]
Ah, then there are two conceivable bugs here:
1. Why is `diesel database drop` marked as hidden? If it's not intended to be used, why does it exist?
2. Perhaps `clap`'s bash completion generation should not emit hidden subcommands.

**Comment by sgrif** [comment]
`git blame` brings us to https://github.com/diesel-rs/diesel/commit/b7cad847919008f96cde90b74c311d7862ecb645 which gives context as to why it was hidden. That said, I don't know that it *needs* to be, and I'd be fine with a PR that un-hides it.
