### ISSUE TITLE
Run without an active database

### ISSUE THREAD

**Issue by jneumann** [diesel-rs/diesel#1606]
I'm attempting to write a library so that I can use it as a backend for a text editor that I am working on. The details of this project are irrelevant, but I would like to use sqlite as a file format. I'm running into issues when I am setting up migrations (I'm guessing I will run into further issues along the way), because I do not have a database created when the library is initially loaded. I started to look at the CLI source code to see if I could figure out what it was doing. Since that is a general purpose tool, there is a lot of code that I don't need for this project.

Is there a documented way to write a program that creates a database from scratch programatically?

**Comment by weiznich** [comment]
Using the [`embed_migrations!`](https://docs.rs/diesel_migrations/1.1.0/diesel_migrations/macro.embed_migrations.html) macro from `diesel_migrations` it is possible to store the sql migrations inside your application binary. If the backend is sqlite and the database does not exist a call to `embedded_migrations::run` will create a new database file.

**Comment by jneumann** [comment]
If I'm understanding the documentation correctly, `establish_connection()` returns a struct that implements `diesel::prelude::Connection`, correct?

**Comment by sgrif** [comment]
Yes. In your case that's probably a `SqliteConnection`

**Comment by jneumann** [comment]
I kind of forgot I opened this issues. Thanks for the help, you guys rock!
