### ISSUE TITLE
Changed column names in `table!` don't make it to `joinable!`

### ISSUE THREAD

**Issue by toddobryan** [diesel-rs/diesel#1609]
## Setup
Latest version

## Problem Description
Using `print-schema` on a pre-existing database, columns named `type` are correctly changed to `type_` with a `#[sql_name = "type"]` attribute, but the underscore is not added in the `joinable!` macro later, leading to errors.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by meven** [comment]
I would like to claim this issue.

I understand the issue at stake is that in print_schema.rs:250 the outputed foreign_key column does not pass through the RESERVED_NAMES filter in `inference.rs`.

So I wonder which way to go from there, the simplest way I can come up with is to swap in
```
            writeln!(f, "{}", Joinable(foreign_key))?;
```
the foreign_key with the `rust_name` using `tables: Vec<TableData>` to find the `ColumnDefinition` and the rust_name.

Or in `inference.rs` there could be a post process in `load_foreign_key_constraints` to apply the RESERVED_NAMES filter or foreign keys as it is done on primary keys line 147.

**Comment by meven** [comment]
ping @Eijebong does my take make sense ?
Should I propose a fix, right away ?

**Comment by meven** [comment]
ping @Eijebong 
I would like to claim this issue, does this mentoring offer still stands ?
I'd like to discuss a little design, but after that I should be able to make a pull request with tests.

**Comment by Eijebong** [comment]
Sure, go for it. If you need help we can either discuss it here or on our gitter channel (sorry missed the other ping)
