### ISSUE TITLE
Queryable with nested structure

### ISSUE THREAD

**Issue by weiwei-lin** [diesel-rs/diesel#1613]
Is there a way to query with nested structure?

```
#[derive(Queryable)]
struct Foo {
    foo1: i32,
    foo2: i32
}

#[derive(Queryable)]
struct FooBar {
    foo: Foo,
    bar: i32
}

let result = some_table.first::<FooBar>(&conn);
```

I'm aware that there's `QueryableByName`, but it seems to require constructing raw query and can't be used with normal queries (e.g. `some_table.filter(...).first(&conn)`).

**Comment by sgrif** [comment]
You'll need to nest your columns to match the nesting of your structure. For example:

```
some_table
    .select(((foo1, foo2), bar))
    .first::<FooBar>(&conn)
```
