### ISSUE TITLE
 environment variable `DATABASE_URL` not defined

### ISSUE THREAD

**Issue by haruhinoshana** [diesel-rs/diesel#1614]
hi good evening im new on using diesel i use it with rocket ... i do try to work diesel on rocket but i got 
 environment variable `DATABASE_URL` not defined error

heres my code 
#![feature(plugin)]
#![plugin(rocket_codegen)]
#[macro_use] 
extern crate rocket;
extern crate diesel;
extern crate dotenv;

use diesel::prelude::*;
use diesel::r2d2::{ConnectionManager, Pool, PooledConnection};
use dotenv::dotenv;
use std::env;

// An alias to the type for a pool of Diesel SQLite connections.
type MysqlPool = Pool<ConnectionManager<MysqlConnection>>;

// The URL to the database, set via the `DATABASE_URL` environment variable.
static DATABASE_URL: &'static str = env!("DATABASE_URL");

/// Initializes a database pool.
fn init_pool() -> Pool {
    let manager = ConnectionManager::<MysqlConnection>::new(DATABASE_URL);
    Pool::new(manager).expect("db pool");
}

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite()
    .manager(init_pool())
    .mount("/", routes![index])
    .launch();
}

my rust version  1.27.0-nightly (637ac17c5 2018-04-03)

**Comment by weiznich** [comment]
This error message means that the environment variable `DATABASE_URL` is not set at compile time. See the documentation of [`env!`](https://doc.rust-lang.org/std/macro.env.html) for details.
