### ISSUE TITLE
Let's make sure adding custom SQL types out of crate is a reasonable experience

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#162]
This likely just requires cleaning up and exposing the macros in `types/imps/mod.rs`, and writing up a documentation page on how to do this.

**Comment by sgrif** [comment]
This is the main focus of 1.1

**Comment by sgrif** [comment]
It's done.

**Comment by sid0** [comment]
Hi @sgrif -- you mentioned that there would be a doc page on how to do this. I looked for it but couldn't find it -- could you link to it?

**Comment by sid0** [comment]
OK, I found https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs. Looks promising.
