### ISSUE TITLE
Boxed Queries are not thread safe.

### ISSUE THREAD

**Issue by seunlanlege** [diesel-rs/diesel#1625]
### Versions

- **Rust:** rustc 1.26.0-nightly (ae544ee1c 2018-03-29)
- **Diesel:** { version = "1.1.0" }
- **Database:** postgres
- **Operating System** 

### Feature Flags

- **diesel:** ["postgres"]

## Problem Description
`disel`
```rust
	let query = payments::table.filter(payments::company_id.eq(companyId)).into_boxed(); // adding `.into_boxed()` causes `query` to no longer be thread safe
	let future = async::query(move |conn| query.get_result::<models::Payment>(conn));
```

`async::query` will spawn the closure on a futures cpupool and requires that the closure contain thread safe items. 

### What is the actual output?
```zsh
error[E0277]: the trait bound `diesel::query_builder::QueryFragment<diesel::pg::Pg>: std::marker::Send` is not satisfied
  --> src/services/paymenthistory/paymenthistory.rs:23:15
   |
23 |     let future = async::query(move |conn| query.get_result::<models::Payment>(conn));
   |                  ^^^^^^^^^^^^ `diesel::query_builder::QueryFragment<diesel::pg::Pg>` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `diesel::query_builder::QueryFragment<diesel::pg::Pg>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<diesel::query_builder::QueryFragment<diesel::pg::Pg>>`
   = note: required because it appears within the type `std::boxed::Box<diesel::query_builder::QueryFragment<diesel::pg::Pg>>`
   = note: required because it appears within the type `diesel::query_builder::BoxedSelectStatement<'_, (diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, db::schema::db_enum_impl_Status::StatusMapping, diesel::sql_types::Text, diesel::sql_types::Text), db::schema::payments::table, diesel::pg::Pg>`
   = note: required because it appears within the type `[closure@src/services/paymenthistory/paymenthistory.rs:23:28: 23:81 query:diesel::query_builder::BoxedSelectStatement<'_, (diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, diesel::sql_types::BigInt, db::schema::db_enum_impl_Status::StatusMapping, diesel::sql_types::Text, diesel::sql_types::Text), db::schema::payments::table, diesel::pg::Pg>]`
note: required by `db::async::query`
  --> src/db/async.rs:24:1
   |
24 | / pub fn query<T, F, R>(f: F) -> impl Future<Item = T, Error = result::Error>
25 | | where
26 | |     T: Send + 'static,
27 | |     F: FnOnce(&Conn) -> R + Send + 'static,
...  |
49 | |     })
50 | | }
   | |_^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `paysquare`.

To learn more, run the command again with --verbose.
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
Thank you for the report. However, making boxed queries `Send` would require a major breaking change, and isn't likely to happen right now. I suggest waiting until the query has been moved into your closure to box it, or just constructing the query entirely on that thread.

**Comment by mehcode** [comment]
@sgrif @weiznich As Diesel 2.x is being worked on now. Can this be reconsidered? Otherwise boxed async queries aren't going to be feasible. We just need the `Send` bound.

**Comment by JohnTitor** [comment]
I'll re-open this issue because we're considering #1990 now. (Feel free to re-close if this is already invalid.)

**Comment by perseoGI** [comment]
> Thank you for the report. However, making boxed queries `Send` would require a major breaking change, and isn't likely to happen right now. I suggest waiting until the query has been moved into your closure to box it, or just constructing the query entirely on that thread.

Hi! Im trying to performe a boxed query using rocket v5 (which seems not to support diesel v2...)
How do you suggest "waiting until the query has been moved"

I'm using `boxed_query` because it make it tons easy to add filters, sorting... based on some rocket parameters.

**Comment by weiznich** [comment]
@perseoGI Please don't ask support questions in closed issues in our issue tracker. They are off topic here, as the issue tracker is reserved for technical discussions. Use the discussion forum for such questions. Also be sure to include a minimal reproducible example of your problem there.
