### ISSUE TITLE
hi diesel mysql unsize issue.

### ISSUE THREAD

**Issue by haruhinoshana** [diesel-rs/diesel#1627]
hi im new in using rust iron and diesel and i'm doing a sample project i got  using rust iron with r2d2 diesel cli mysql.....  heres the error.

error[E0308]: mismatched types
  --> src/dal/models/user.rs:82:23
   |
82 |             Ok(new_user) => Ok(new_user),
   |                                ^^^^^^^^ expected struct `dal::models::user::User`, found usize
   |
   = note: expected type `dal::models::user::User`
              found type `usize`

error[E0308]: mismatched types
  --> src/dal/models/post.rs:36:23
   |
36 |             Ok(new_post) => Ok(new_post),
   |                                ^^^^^^^^ expected struct `dal::models::post::Post`, found usize
   |
   = note: expected type `dal::models::post::Post`
              found type `usize`

heres the code... 

	pub fn create(user: &NewUser, connection: &DieselConnection, logger: &Logger) -> Result<User, diesel::result::Error> {
		let statement = diesel::insert(user)
		.into(users::table);

		info!(logger, "Executing Query"; "query" => debug_sql!(statement), "user" => format!("{:?}", user));

		let new_user = statement.execute(&**connection);
		//<User>

		match new_user {
			Ok(new_user) => Ok(new_user),
			Err(error) => {
				warn!(logger, "Error creating user"; o!("error" => format!("{:?}", error)));
				Err(error)
			},
		}
	}

help me please im newbie.

**Comment by weiznich** [comment]
[`execute`](http://docs.diesel.rs/diesel/query_dsl/trait.RunQueryDsl.html#method.execute) returns the number  of affected rows. 
For mysql there is no way that an insertstatment returns the inserted row, this needs a distinct query.

**Comment by sgrif** [comment]
See http://docs.diesel.rs/diesel/macro.sql_function.html to use custom SQL functions.
