### ISSUE TITLE
Add compiler error for DISTINCT ON that doesn't match initial ORDER BY expressions

### ISSUE THREAD

**Issue by connec** [diesel-rs/diesel#1641]
For example:

```rust
table! {
    entries (id) {
        id -> Int4,
        name -> Text,
        date -> Timestamp,
    }
}

// Attempt to get the latest entries for each `name`
entries
    .order_by(date.desc())
    .distinct_on(name)
    .load(&conn)
```

This compiles fine, but inevitably causes "SELECT DISTINCT ON expressions must match initial ORDER BY expressions" when executed.

The correct version, of course, is:

```rust
entries
    .order_by((name, date.desc()))
    .distinct_on(name)
    .load(&conn)
```

According to [the PostgreSQL docs](https://www.postgresql.org/docs/9.5/static/sql-select.html#SQL-DISTINCT) `DISTINCT ON` is valid with no ordering, or with a matching prefix. I don't know enough about Rust to have any idea how feasible it is to encode that in the types, but it would be a neat sanity check!

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
I'm not sure that it's possible for us to encode this (without a breaking change), but we definitely *should* be
