### ISSUE TITLE
Segmentation fault: 11 when running diesel setup

### ISSUE THREAD

**Issue by msathis** [diesel-rs/diesel#1645]
### Versions

- **Rust:** rustc 1.25.0 
- **Diesel:** diesel_cli 1.2.0
- **Database:**
- **Operating System** Mac OS X

Always i get `Segmentation fault: 11` whenever i try to run any diesel-cli commands.

**Comment by sgrif** [comment]
This is likely some sort of issue with your installation of whatever backends you're using. Unfortunately, with the information you've provided, there is no way that we could reproduce or provide additional help. Please feel free to comment here with more details if you still need help.
