### ISSUE TITLE
Rollback transactions on panic

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#1646]
Related to https://github.com/sfackler/r2d2/issues/31

Transactions should be rolled back if the inner function panics. The rollback code should take care not to panic in this case, to avoid double panics. Failure to do this can result in connections being returned to the pool with open transactions, which means database locks are held indefinitely, and future uses of the connection will cause further panics.

**Comment by sgrif** [comment]
I disagree that this should be handled in Diesel. Transactions that do not explicitly commit will be rolled back when the connection is dropped. This is a problem *specific* to connection pooling, and should be handled there.

**Comment by Diggsey** [comment]
I strongly disagree with this decision: the transaction function creates a scope for the transaction, and it is fully expected that the transaction not be open after the end of that scope, regardless of how the scope is left. That's not a problem that's specific to connection pooling.
