### ISSUE TITLE
Timestamptz lacks arithmetic (and more) operations

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#1656]
As described in the [document](https://www.postgresql.org/docs/9.6/static/functions-datetime.html) both `timestamp` and `timestamp with time zone` can be operated with arithmetic operations, but diesel implements `Add` and `Sub` only ofr `Timestamp`. Similarly, as reported in #1514 , `now` should be able to be treated as timestamp with time zone.

I'll implement it, if it is acceptable.

**Comment by KeenS** [comment]
:)

**Comment by notryanb** [comment]
Resolved in #1657
