### ISSUE TITLE
Will mongodb be supported?

### ISSUE THREAD

**Issue by shuaizhiwen** [diesel-rs/diesel#1662]
## Problem Description
I want to use mongodb in rust. You want to make mongodb and MySQL easy to switch. Diesel intends to support mongodb, and many noder use mongodb, so we hope to support this feature.

### What are you trying to accomplish?
It is not clear whether supporting Mongo in diesel is correct, but there is a similar implementation in node, and it feels that the cost will be smaller and, of course, it will lose a lot of database features. I am a rust beginner. I may have more wrong questions. Please forgive me.

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
Nope, Mongo is not something we are planning on supporting.

**Comment by ddimaria** [comment]
@shuaizhiwen this was announced last week: https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver

**Comment by JimLynchCodes** [comment]
@ddimaria the "rust driver" is just a library for querying a mongo database with rust functions.

Diesel provides more things such as migrations that I would like to use with mongo as well.

**Comment by weiznich** [comment]
@JimLynchCodes To make that clear: Diesel is designed to be used with relational, sql based, databases. MongoDB is no relational database, therefore we won't support it.
