### ISSUE TITLE
derive(Table) functionality

### ISSUE THREAD

**Issue by theduke** [diesel-rs/diesel#1668]
Quite a while ago I wrote a small crate that allows deriving a Table implementation for a struct.

I never published it, but used it in multiple projects: https://github.com/theduke/diesel_derive_table
I think it's quite handy.
Especially with something like CockroachDB where `print-schema` does not work it helps to prevent quite a bit of duplication. 

I talked with @sgrif a bit in Gitter before implementing this, and I remember him not being very enthused about it.

I still think it's really useful as an alternative workflow.

If the maintainers think this would be nice to have in core, I can whip up a PR.

Sample usage:

```rust
#[macro_use] extern crate diesel_derive_table

#[derive(Table, Queryable, AsChangeset, Insertable, Identifiable)]
#[table_name="reddit_posts"]
#[primary_key(uuid)]
pub struct RedditPost {
    #[column_type="Text"]
    #[column_name="my_uuid"]
    pub uuid: String,
    #[column_type="BigInt"]
    pub created_at: i64,
}
```

**Comment by sgrif** [comment]
I think you should publish this as a separate crate and see how it goes.
