### ISSUE TITLE
Support summation into 128-bit integer

### ISSUE THREAD

**Issue by coder543** [diesel-rs/diesel#1692]
If I have a table that has a 64-bit `value` column in it, it would be nice to be able to `sum()` it into a 128-bit integer, rather than having to pull in some `BigDecimal` crate, now that 128-bit integers are in stable Rust. For 32-bit integers, they currently `sum()` into a 64-bit integer, so I think this is a nice symmetry to add. Personally, I would like to have the option to `sum()` into a same-sized type like the Rust stdlib does, but it is also nice to ensure there will not be an overflow by summing into a larger type.

Right now, the following code:

```rust
use db::schema::some_table::dsl::*;
use diesel::dsl::sum;
some_table
    .filter(user.eq(self.id))
    .select(sum(value))
    .first::<i128>(conn)
    .unwrap()
```

yields this error:

```rust
error[E0277]: the trait bound `i128: diesel::Queryable<diesel::sql_types::Nullable<diesel::sql_types::Numeric>, _>` is not satisfied
   --> src/db.rs
    |
    |             .first::<i128>(conn)
    |              ^^^^^ the trait `diesel::Queryable<diesel::sql_types::Nullable<diesel::sql_types::Numeric>, _>` is not implemented for `i128`
    |
    = note: required because of the requirements on the impl of `diesel::query_dsl::LoadQuery<_, i128>` for <snip>
```

**Comment by sgrif** [comment]
Thanks, but there's no SQL type which maps to a 128 bit integer. Numeric is neither an integer type, nor is it limited to 128 bits.

**Comment by coder543** [comment]
So there's no way we can make it type-safe for summing a column that we know is made of 64-bit integers into a 128-bit integer value? At compile time we have all the information needed, don't we?

**Comment by sgrif** [comment]
Possibly, but that would require:

- Moving away from the actual semantics of the database
- Introducing a new SQL type, which does not actually exist
- Changing the behavior of `sum` (breaking change)
- Dropping support for older versions of Rust

It's definitely possible for you to do this in a third party crate though, by introducing a new SQL type, and defining a new `sum` function with `sql_function!`.
