### ISSUE TITLE
Fail generation of diesel_infer_schema documentation

### ISSUE THREAD

**Issue by aplanas** [diesel-rs/diesel#1695]
Checking the diesel "getting started" documentation there is a link to the `infer_schema!` macro. This link is broken, maybe because the documentation for this macro cannot be generated in https://docs.rs

https://docs.rs/crate/diesel_infer_schema/1.2.0/builds/94816

**Comment by sgrif** [comment]
I've addressed this in 1.3.0. However, the compiler is hitting an ICE, so there's either a bug in Rust itself or the fork that docs.rs is using. https://docs.rs/crate/diesel_infer_schema/1.3.0/builds/100665 Please open a bug for one of those projects.
