### ISSUE TITLE
Make Boxed Queries Cloneable

### ISSUE THREAD

**Issue by Narfinger** [diesel-rs/diesel#1698]
At the moment Boxed Queries (resulting from into_boxed()) are not cloneable.
My use case is that I want to keep constructing the query in a different part of the code and keep it in a struct. Periodically I want to execute the query and load the result but of course, keep the struct.

Is there a reason why this is not cloneable?

**Comment by sgrif** [comment]
`Clone` is not object safe. We can never make them cloneable.

**Comment by dullbananas** [comment]
This would be possible by using `Rc` instead of `Box`

**Comment by weiznich** [comment]
@dullbananas `Rc` won't work as we want to have a type that implements `Send`. Maybe `Arc` would work. Happy to accept a PR for that as long as it does not regress performance.

**Comment by dullbananas** [comment]
Should [`DynClone`](https://docs.rs/dyn-clone/latest/dyn_clone/) be added as a supertrait of `BoxableExpression`?

**Comment by weiznich** [comment]
@dullbananas Thats not possible as that would be a breaking change. We generally want to avoid breaking changes.
