### ISSUE TITLE
Use `cargo clippy` instead of the clippy plugin

### ISSUE THREAD

**Issue by oli-obk** [diesel-rs/diesel#1709]
We're planning on removing the clippy plugin interface, because rustc will remove it someday anyway. All that is required on your end is to remove the clippy feature and replace all cfgs that depend on it with the `cargo-clippy` feature which is automatically enabled by cargo clippy.

So you can then use `cargo clippy` instead of `cargo build --features=clippy`. Note that cargo clippy requires a `cargo install clippy` first.

**Comment by oli-obk** [comment]
Citing @sgrif in https://github.com/rust-lang-nursery/rust-clippy/pull/2712#issuecomment-391057884

> cargo clippy is a separate command that requires recompiling all the crates again (adding minutes to the feedback cycle), and that I have to remember to run in the first place. Running it as a separate step makes sense for CI, but hurts the work flow for local development.

That is a serious downside. But I think I have a solution. Do a `cargo install clippy` and set `RUSTC_WRAPPER` to `clippy-driver` (e.g. via an `.env` file) or change the appropriate setting in `.cargo/config` to `clippy-driver`. This should replace all compilation with clippy. It might require some adjustments on our side, but technically `cargo check` should then "just work"^TM

**Comment by weiznich** [comment]
Was fixed by #1789
