### ISSUE TITLE
diesel_cli v1.3 print-schema broken on WIN10

### ISSUE THREAD

**Issue by Deedasmi** [diesel-rs/diesel#1723]
## Setup
With diesel_cli 1.2:

`diesel print-schema` gives correct output.

With diesel_cli 1.3:
`diesel print-schema` gives 
> Access is denied. (os error 5)

### Versions

- **Rust:** nightly-2018-05-14/1.26 Stable
- **Diesel:** 1.3
- **Database:** PG10
- **Operating System** WIN10

### Feature Flags

- **diesel:** Postgres

## Checklist

- [ X ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ X ] This issue can be reproduced on Rust's stable channel.

Doing some troubleshooting, but it's 1 am and I might pass out. Will figure out cause tomorrow at latest.

**Comment by Deedasmi** [comment]
Why would it work on the previous version then? I downgraded to 1.2 and it worked fine.

I've tracked the error down to https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/print_schema.rs#L57, but haven't figured out why its failing yet.

**Comment by Deedasmi** [comment]
```
extern crate tempfile;
use tempfile::NamedTempFile;
use std::fs::File;
use std::io;

fn main() -> Result<(), io::Error> {
    let tempfile = NamedTempFile::new()?;
    let mut out = File::create(tempfile)?;
    Ok(())
}
```

Fails on my system. Seems like this is an issue with tempfile.

**Comment by weiznich** [comment]
Is your temp directory writable for your current user? If not this seems more like a system configuration issue.

**Comment by Deedasmi** [comment]
Opened https://github.com/Stebalien/tempfile/issues/56.

Made a better test where I can write a PathBuf file, but not a NamedTempFile. This one looks... fun lol.

**Comment by Deedasmi** [comment]
I actually think diesel is using tempfile incorrectly. https://docs.rs/tempfile/3.0.2/src/tempfile/file/mod.rs.html#371-374

NamedTempFile already creates a `File`. By passing it to `File::create()` NamedTempFile happily dereferences down to a path to the file it already created, and the OS tries to create a file at a path that already has a file descriptor open.

**Comment by KodrAus** [comment]
@Deedasmi that's right, `NamedTempFile::new` will create the temporary file it wraps before it returns.
