### ISSUE TITLE
the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied

### ISSUE THREAD

**Issue by llxxbb** [diesel-rs/diesel#1731]
- **Rust:** 1.28-nightly
- **Diesel:** 1.3.0
- **Database:** sqlite
- **Operating System** win 10

 diesel = { version = "1.3", default-features = false, features = ["sqlite","chrono"] }

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied
  --> C:\Users\llxxb\.cargo\registry\src\github.com-1ecc6299db9ec823\diesel-1.3.0\src\expression\count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Add` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

**Comment by weiznich** [comment]
It's a rustc bug, see #1700 #1701 #1705 #1711 #1729, #1730 , rust-lang/rust#50825 and rust-lang/rust#51042

**Comment by BartMassey** [comment]
Looks like a change to `rustc` was pushed about 4 hours ago that is reported to resolve this issue. This would be a good time to close it, if it hadn't been closed 14 days ago. :-)  rust-lang/rust/pull/#51042

**Comment by Eijebong** [comment]
It's not merged yet ;)

**Comment by BartMassey** [comment]
Indeed. So maybe we should wait to have closed the issue a little longer. :-)
