### ISSUE TITLE
SQL `is` and query params

### ISSUE THREAD

**Issue by kamek-pf** [diesel-rs/diesel#1733]
I'm playing with `sql_query`, here's the structure I'm trying to deserialize :
```rust
#[derive(Debug, QueryableByName)]
#[table_name = "some_table"]
struct User {
    id: i32,
    some_bool: bool,
}
```

Rust query looks like this :
```rust
let users: Vec<User> = sql_query(include_str!("test.sql"))
    .bind::<Bool, _>(true)
    .get_results(&cn)?;
```

SQL query looks like this :
```sql
select id, some_bool from some_table where some_bool = $1
```

Everything works fine with the above query, the following however, doesn't work :
```sql
select id, some_bool from some_table where some_bool is $1
```
I get a `DatabaseError(__Unknown, "syntax error at or near \"$1\"")`

Hardcoding the value works though :
```sql
select id, some_bool from some_table where some_bool is true
```

**Comment by weiznich** [comment]
Diesel basically passes the raw sql string without any change to the database, so this seems to be a restriction in postgresql itself or libpq. (So nothing diesel could do much about).
From looking at the [postgres operator overview](https://www.postgresql.org/docs/current/static/functions-comparison.html) it seems that there are only specific arguments are supported after is (and therefore no bind).
