### ISSUE TITLE
Can't implement InternalSaveChangesDsl for another backend

### ISSUE THREAD

**Issue by pgab** [diesel-rs/diesel#1736]
### Versions

- **Rust:** nightly-2018-03-07-x86_64-unknown-linux-gnu
- **Diesel:** 1.2.2
- **Database:** Oracle 12g
- **Operating System** Ubuntu 18.04

## Problem Description
I am trying to get another backend for diesel working. Namely oracle/oci. Therefore I need to implement e.g. ```InternalSaveChangesDsl```. Since all oracle/oci related code is currently outside of diesel, it is impossible to implement this. Please note that I made `save_changes_dsl` public.

### What is the actual output?
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for a type parameter
  --> src/oracle/query_dsl/save_changes_dsl.rs:15:1
   |
15 | / impl<T, U> InternalSaveChangesDsl<OciConnection, U> for T
16 | |     where
17 | |         T: Copy + Identifiable,
18 | |         T: AsChangeset<Target = <T as HasTable>::Table> + IntoUpdateTarget,
...  |
26 | |     }
27 | | }
   | |_^
```
### Steps to reproduce
There is some code at https://github.com/GiGainfosystems/diesel-oci/tree/feature/save_changes_dsl available. I also had to change some diesel code: https://github.com/GiGainfosystems/diesel/tree/feature/save_changes_dsl
Within `diesel/diesel_tests` I run
```
cargo +nightly test --features oracle
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
@weiznich Has an idea about how to fix this.
