### ISSUE TITLE
Diesel does not currently support tables with primary keys consisting of more than 5 columns...

### ISSUE THREAD

**Issue by joshgev** [diesel-rs/diesel#1740]
Hi everyone,

My typical approach is to write my SQL queries by hand and embed them in Rust code, but I am looking into Diesel as an alternative methodology, especially because my current task would be facilitated by the ability to generate queries dynamically.  

In any case, I ran into the following message when trying to create a new table using `diesel migration generate`:

```
Diesel does not currently support tables with primary keys consisting of more than 5 columns. Table privileges has 6 columns in its primary key. Please open an issue and we will increase the limit.
```

I'd like to see this limitation relaxed because it would be difficult for me to reduce the number of columns on this particular table).  

To sate my own curiosity, I'd be interested to hear why there is a limitation imposed by Diesel at all.

Thanks in advance for any help!

**Comment by weiznich** [comment]
See #1702 for a fix

**Comment by joshgev** [comment]
@weiznich Fantastic!  Thanks a ton.  I will check it out right now.

**Comment by joshgev** [comment]
Yeah, that worked; I will close this issue.  Thanks again, @weiznich.
