### ISSUE TITLE
Please create a nowtz for working with Timestamptz

### ISSUE THREAD

**Issue by lholden** [diesel-rs/diesel#1752]
Due to a lack of implicit conversions currently if one wants to perform something such as

```
accessed_at.lt(now - 15.minutes())
```

Where accessed_at is a `Timestamptz`, one instead has to write:

```
accessed_at.lt(now.into_sql::<Timestamptz>() - 15.minutes())
```

Adding something like `nowtz` to the Diesel DSL would allow us to instead write:

```
accessed_at.lt(nowtz - 15.minutes())
```

**Comment by sgrif** [comment]
After implementing this, I'm not sure it really makes sense to have this in Diesel. The use case feels very niche, and not something that I think is worth maintaining in our own codebase -- Especially since you can have this in your own code base:

```rust
fn nowtz() -> AsExprOf<now, Timestamptz> {
    now.into_sql()
}
```

**Comment by berkus** [comment]
Ok, will add this to my codebase.. And probably many more will..

Is it possible to add this simple function in diesel just once instead?
