### ISSUE TITLE
We have a discourse forum now

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1756]
There's a clear need for a place to discuss topics which are too asynchronous for gitter, but too non-actionable for Github issues. I've set up a Discourse forum to host those discussions. The driving discussion (and initial set of topics I've opened) are about Diesel 2.0. This should also be considered a place to ask for help as an alternative to gitter. You can find it at https://discourse.diesel.rs/

This issue will be left open for 7 days for visibility (if anyone with the ability to close issues sees this more than 7 days from now, please close this. I forgot.)

**Comment by erlend-sh** [comment]
If you've got some Issues you'd like to move over, we have a tool for that:

https://meta.discourse.org/t/introducing-github-issues-to-discourse/46671

p.s. looks like someone forgot to close this ;)
