### ISSUE TITLE
https://docs.diesel.rs/ certificate is invalid for this domain

### ISSUE THREAD

**Issue by Fiedzia** [diesel-rs/diesel#1759]
docs.diesel.rs uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

**Comment by weiznich** [comment]
Duplicate of #1755

**Comment by sgrif** [comment]
It appears this has been fixed.
