### ISSUE TITLE
Diesel complains that it can't find Cargo.toml despite successfully running migrations

### ISSUE THREAD

**Issue by SamWhited** [diesel-rs/diesel#1760]
### Versions

- **Rust:** 1.28.0 nightly
- **Diesel:** 1.3.1
- **Database:** postgres
- **Operating System** arch

### Feature Flags

- **diesel:** postgres

## Problem Description

When running any migration command (eg. diesel migration redo) migrations complete successfully, but diesel complains:

> Unable to find Cargo.toml in this directory or any parent directories.

I don't have a Cargo.toml because I am not using Cargo.

### What is the expected output?

No unnecessary warnings about a build system that I am not using.

### What is the actual output?

> Unable to find Cargo.toml in this directory or any parent directories.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

eg.

```
$ diesel migration redo
Rolling back migration 2018-06-13-215447_init
Running migration 2018-06-13-215447_init
Unable to find Cargo.toml in this directory or any parent directories.
```

**Comment by sgrif** [comment]
Looks like this error occurs when Diesel CLI looks for a config file (the default location is in the same place as `Cargo.toml`)
