### ISSUE TITLE
Implement Unsigned<Tinyint> for MySql

### ISSUE THREAD

**Issue by RazrFalcon** [diesel-rs/diesel#1771]
### Versions

- **Diesel:** 1.3.2

### Feature Flags

- **Diesel:** mysql

## Problem Description

Looks like `diesel::mysql::types::Unsigned` is not implemented for `u8`, aka `Tinyint`.

### What are you trying to accomplish?

Use the `TINYINT` type.

### What is the actual output?

```
error[E0277]: the trait bound `u8: diesel::Queryable<diesel::sql_types::Unsigned<diesel::sql_types::Tinyint>, diesel::mysql::Mysql>` is not satisfied
```

### Steps to reproduce

Use this SQL to generate the schema

```sql
CREATE TABLE test (
    id INT,
    score TINYINT UNSIGNED
)
```

```rust
table! {
    test (id) {
        id -> Integer,
        score -> Nullable<Unsigned<Tinyint>>,
    }
}
```

and try to query it:
```rust
#[derive(Queryable)]
pub struct Test {
    pub id: i32,
    pub score: Option<u8>,
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
For the record, `SMALLINT` is not the same as `TINYINT` but there does appear to be a legitimate omission here.

**Comment by RazrFalcon** [comment]
Yes. I've mistaken. Updated the post.
