### ISSUE TITLE
How to use FromSql, FromSqlRow, and Queryable?

### ISSUE THREAD

**Issue by spease** [diesel-rs/diesel#1774]
Hi, I have a number of newtypes that need to get moved into a SQL database. These are generally either:
1) Straight wrapper around a type that diesel already supports
2) Wrapper around a dimensioned type that needs to do a conversion
3) Wrapper around a complex type that needs to deserialize from a string

It isn't clear to me when each of the above types should be implemented or derived. I've read the getting started guides and the reference docs, but it doesn't seem like it's laid out anywhere.

Thanks.

**Comment by weiznich** [comment]
See [this](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs) test case for an example. For future questions please use our [gitter channel](https://gitter.im/diesel-rs/diesel)
