### ISSUE TITLE
Can't use CLI to migrate and create composite primary key table

### ISSUE THREAD

**Issue by losvedir** [diesel-rs/diesel#1779]
## Setup

This is my `up.sql`:

```sql
create table vehicle_movements (
  vehicle_id varchar not null,
  stop_id varchar not null,
  arrived_at int,
  departed_at int,
  primary key (vehicle_id, stop_id)
)
```

This is what happens when I try to migrate:

```
➜  hawkeye git:(master) ✗ diesel migration run
Diesel only supports tables with primary keys. Table vehicle_movements has no primary key
```

But I _do_ have a primary key - a composite one, specified at the end of the `create table`. I see from #450 that supposedly there is support for composite primary keys, so I don't know if I'm doing something wrong or not.

### Versions

- **Rust:** 1.27.0
- **Diesel:** crate - 1.3.2, CLI - 1.3.1
- **Database:** Postgres 10
- **Operating System** OS X

### Feature Flags

- **diesel:** `--without-default-features --feature postgres`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by nocduro** [comment]
I had this problem as well, here's how to reproduce:

* try to run migration on table without primary key:

```sql
create table vehicle_movements (
  vehicle_id varchar not null,
  stop_id varchar not null,
  arrived_at int,
  departed_at int
)
```

* get error message
* edit up.sql to include composite key:

```sql
create table vehicle_movements (
  vehicle_id varchar not null,
  stop_id varchar not null,
  arrived_at int,
  departed_at int,
  primary key (vehicle_id, stop_id)
)
```

* `diesel migration run` then fails with the same error

I fixed it by running `diesel migration revert` which dropped the tables, and then re-running `diesel migration run`

**Comment by sgrif** [comment]
The above comment is likely correct. It sounds like you edited a migration without re-running it, or your schema for some other reason does not match what you expect it to be.
