### ISSUE TITLE
Trait `diesel::expression::NonAggregate` is not implemented for `diesel::dsl::CountStar`

### ISSUE THREAD

**Issue by ondj** [diesel-rs/diesel#1781]
### Versions

- **Rust:** 1.27.0
- **Diesel:** 1.3.2
- **Database:** PostgreSQL
- **Operating System:** Windows 10

### Feature Flags

```toml
diesel = { version = "1.3.0", features = ["postgres", "chrono", "r2d2"] }
```

## Problem Description

I am trying to get results from db grouped by column `serial_to` and get `serial_to` with number of entries for that serial.

### What are you trying to accomplish?

Send to database SQL query like this:
```sql
SELECT COUNT(*), serial_to FROM inet GROUP BY serial_to
```

### What is the expected output?

`Vec<(i32, i64)>`

### What is the actual output?

Compilation error:
```
error[E0277]: the trait bound `diesel::dsl::CountStar: diesel::expression::NonAggregate` is not satisfied
  --> src/stats.rs:25:10
   |
25 |         .select((inet::serial_to, count_star()))
   |          ^^^^^^ the trait `diesel::expression::NonAggregate` is not implemented for `diesel::dsl::CountStar`
   |
   = note: required because of the requirements on the impl of `diesel::Expression` for `(database_schema::inet::columns::serial_to, diesel::dsl::CountStar)`
   = note: required because of the requirements on the impl of `diesel::query_dsl::select_dsl::SelectDsl<(database_schema::inet::columns::serial_to, diesel::dsl::CountStar)>` for `database_schema::inet::table`

error[E0599]: no method named `group_by` found for type `diesel::query_builder::SelectStatement<database_schema::inet::table, diesel::query_builder::select_clause::SelectClause<(database_schema::inet::columns::serial_to, diesel::dsl::CountStar)>>` in the current scope
  --> src/stats.rs:26:10
   |
26 |         .group_by(inet::serial_to)
   |          ^^^^^^^^ private field, not a method
   |
   = note: the method `group_by` exists but the following trait bounds were not satisfied:
           `&diesel::query_builder::SelectStatement<database_schema::inet::table, diesel::query_builder::select_clause::SelectClause<(database_schema::inet::columns::serial_to, diesel::dsl::CountStar)>> : diesel::GroupByDsl<_>`
           `&mut diesel::query_builder::SelectStatement<database_schema::inet::table, diesel::query_builder::select_clause::SelectClause<(database_schema::inet::columns::serial_to, diesel::dsl::CountStar)>> : diesel::GroupByDsl<_>`
```

### Are you seeing any additional errors?

No

### Steps to reproduce

Database schema can be simple:
```rust
table! {
    inet (hash) {
        hash -> Binary,
        serial_to -> Int4,
    }
}
```

This is compiled correctly and works:
```rust
let stats: Vec<i32> = inet::table
        .select(inet::serial_to)
        .group_by(inet::serial_to)
        .load(&connection)?;
```
But this shows complication errors:
```rust
let stats: Vec<(i32, i64)> = inet::table
        .select((inet::serial_to, count_star()))
        .group_by(inet::serial_to)
        .load(&connection)?;
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by vmalloc** [comment]
Also hitting this issue and was wondering if there is a workaround to getting it work...

**Comment by vmalloc** [comment]
I managed to work around it by replacing `count_star()` with `diesel::dsl::sql<diesel::sql_types::BigInt>("count(*)")`. Yuck, but works...

**Comment by sgrif** [comment]
Diesel doesn't currently support `.group_by`, and for that reason we don't allow mixing aggregate/non-aggregate expressions. You can use the workaround above until we introduce support for group by

**Comment by ralpha** [comment]
> I managed to work around it by replacing `count_star()` with `diesel::dsl::sql<diesel::sql_types::BigInt>("count(*)")`. Yuck, but works...

Used the workaround above. If someone will find this in the future. 

It is: `diesel::dsl::sql::<diesel::sql_types::BigInt>("count(*)")` Otherwise it will not work. (was missing `::`)

**Comment by jendakol** [comment]
The workaround works for me too (v 1.4.5), with `sum` SQL function:
```
            invoices::table
                .left_outer_join(invoice_rows::table)
                .select((
                    invoices::all_columns,
                    diesel::dsl::sql::<diesel::sql_types::Float>("sum(invoice_rows.price)"),
                ))
                .filter(invoices::id.eq(id as i32))
                .first(conn)```

**Comment by bitemyapp** [comment]
This saved me a bunch of time, thanks for posting the workarounds y'all.

**Comment by jcramb** [comment]
Also ran into this issue over three years later - thank you from the future for the workaround.

**Comment by weiznich** [comment]
Just as a headsup: Diesel >=2.0 supports group by clauses so this workaround is not longer required.
