### ISSUE TITLE
The attribute `table_name` is currently unknown to the compiler and may have meaning added to it in the future

### ISSUE THREAD

**Issue by raintears** [diesel-rs/diesel#1782]
It keeps complaining about #[table_name = "users"] and I don't see what's wrong.

I have two tables in ```schema.rs```
```

table! {
    school (id) {
        id -> Varchar,
        location -> Varchar,
    }
}

table! {
    users (email) {
        email -> Varchar,
        password -> Varchar,
    }
}
```
This is my user.rs everything looks fine to me

```
#[table_name = "users"]
#[derive(Serialize, Deserialize)]
pub struct User {
    pub email: String,
    pub password: String
}
```

It works for school.rs though

```
#[table_name = "schools"]
#[derive(Serialize, Deserialize)]
pub struct School {
    pub id: i32,
    pub location: String
}
```

**Comment by sgrif** [comment]
This is a known issue in Rust that is caused by `#![feature(proc_macro)]`, there is nothing Diesel can do about it.

**Comment by sgrif** [comment]
Actually I lied, this is because you don't need any of the `#[table_name]` attributes you've applied. Just delete them.

**Comment by BlakeGilstrap** [comment]
Apologies for necro.

@sgrif Do you mind explaining why `#[table_name]` was not required in this case and/or when it _should_ be used?  I'm seemingly running into this error but my pattern doesn't match above exactly.

`schema.rs`

```rust
table! {
    my_metadata_table {...}
}

```

`metadata.rs`
```rust
use schema::my_metadata_table;

#[table_name = "my_metadata_table"]
#[derive(Deserialize, Queryable, Serialize)]
pub struct Metadata { ... } 

```

And I get same error as mentioned here.
