### ISSUE TITLE
Documentation does not build on Rust 1.29.0

### ISSUE THREAD

**Issue by nabijaczleweli** [diesel-rs/diesel#1792]
### Versions

- **Rust:** `rustc 1.29.0-nightly (12ed235ad 2018-07-18)`
- **Diesel:** both latest release (`1.3.2`), as well as latest `master` ( `765b782f7f94932cf129bc603dc5909d7155e9fe`)
- **Database:** N/A
- **Operating System:** Windows, Linux (though probably all are affected)

### Feature Flags

- **diesel:** both none (default), as well as `["32-column-tables", "sqlite", "chrono", "r2d2"]` (though probably all are affected)

## Problem Description

When building the documentation, `cargo doc` produces warnings, which, due to `deny(warnings)`, cause an error – meaning you *can not* build `diesel` docs on current nightly.

### What are you trying to accomplish?

Build documentation for my project (and, transitively, `diesel`).

### What is the expected output?

```
[...]
Documenting diesel v1.3.2
[...]
Documenting sudoku-backend v0.1.0
[...]
Finished release [optimized] target(s) in Xm Ys
```

### What is the actual output?

A [multitude of errors](https://travis-ci.com/Galactim/Sudoku/jobs/135407228#L2462-L2527), ending with

```
note: lint level defined here
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.2/src/lib.rs:131:9
    |
131 | #![deny(warnings, missing_debug_implementations, missing_copy_implementations, missing_docs)]
    |         ^^^^^^^^
    = note: #[deny(intra_doc_link_resolution_failure)] implied by #[deny(warnings)]
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
error: Could not document `diesel`.
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

Run `cargo doc` on current nightly on this crate (be it directly or transitively).

### Steps to fix

One could either (a) fix the documentation errors, or (b) replace, as mentioned [previously](https://github.com/diesel-rs/diesel/pull/1789#issuecomment-406272805), [`src/lib.rs#L131`](https://github.com/diesel-rs/diesel/pull/1789/files#diff-7ab3c70a207718b2fce878a8f925a415R131). with

```rust
#![cfg_attr(feature = "dox", deny(warnings, missing_debug_implementations, missing_copy_implementations, missing_docs))]
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case) — however, it will be *too late* to fix this once current nightly hits stable (I am not submitting this with a light heart, having not met the checkbox, but close me if you've got to).

**Comment by kennytm** [comment]
A dependency currently breaks downstream crates because `rustdoc` has not stabilized `--cap-lints` yet, which prevents Cargo from utilizing it. Stabilization is underway (rust-lang/rust#52354) but it will likely take several days.

**Comment by sgrif** [comment]
Please re-open if this is still an issue once it hits beta.

**Comment by jesskfullwood** [comment]
I assume this is the reason that the 'latest release' docs (linked in the README) on `docs.rs` are broken - https://docs.rs/diesel/1.3.2/diesel/ - because as I recall `docs.rs` uses nightly for its builds

**Comment by sgrif** [comment]
Actually, it's because the nightly that docs.rs uses is super old and has bugs that have since been fixed.

**Comment by theduke** [comment]
@sgrif building with current nightly fails again at the moment for me.

Enabled features: `["sqlite", "r2d2", "chrono"]`.

Error:

```
error[E0275]: overflow evaluating the requirement `<&_ as insertable::Insertable<_>>::Values`
  |                                                                         
  = help: consider adding a `#![recursion_limit="512"]` attribute to your crate
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(_, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(_, _, _), &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((_, _, _), _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((_, _, _), _, _), &_, &_)`
.....
.......
```

**Comment by weiznich** [comment]
@theduke That seems to be an issue with rustdoc. I've already reported that against rustc, see https://github.com/rust-lang/rust/issues/54524.
Unfortunately I've no clue what exactly is causing this.
