### ISSUE TITLE
How get  the list of fields + types on a query?

### ISSUE THREAD

**Issue by mamcx** [diesel-rs/diesel#1794]
I'm building a small ORM-like library and wish to use diesel to handle the low-level stuff. All need to be using only raw sql, but I need to know in query, which names + types is returning:

`SELECT *, 1, now(), 'hello' as world`

so I can map dynamically. Is this possible with diesel? All the info assume is using the custom DSL, not much in how use sql directly (like https://github.com/StackExchange/Dapper?)

**Comment by sgrif** [comment]
We don't expose anything that parses your SQL queries for you. You'll likely need to use something much lower level which exposes specific details about its prepared statements
