### ISSUE TITLE
Setting up the schema file according to diesel.toml when running `embed_migrations!` macro

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#1805]
Could the `embed_migrations!` macro also initialize the schema file as `diesel migration run` does?

Rust 1.27.2
Diesel 1.3 (both in Cargo.toml of my binary crate and diesel-cli itself).

In the [changelog file](https://github.com/diesel-rs/diesel/blob/master/CHANGELOG.md#fixed-3) it is said:

> 
> Fixed
> 
>     diesel print-schema and infer_schema! now properly handle unsigned types in MySQL
> 
> Deprecated
> 
>     diesel_infer_schema has been deprecated. diesel print-schema is now the only way to generate database schema. Diesel CLI can be configured to automatically regenerate your schema file when migrations are run. See diesel.rs/guides/configuring-diesel-cli for details.

But I still want to perform migrations automatically and to generate my schema file automatically also. If `diesel migration run` setup the schema, why `embed_migrations!` does not?

**Comment by sgrif** [comment]
`embed_migrations!` is something that generates code at compile time, not an external tool that is run separately. Having that macro modify a file in your project as a side effect of being compiled would be extremely confusing. Not to mention that there's no guarantee that `embed_migrations!` will get compiled before `src/schema.rs` -- which would lead to a compiler error about code that doesn't exist.

**Comment by vityafx** [comment]
@sgrif I am doing `embed_migrations!` in my build.rs so there is no problem at all to do that.

**Comment by sgrif** [comment]
> embed_migrations! is something that generates code at compile time, not an external tool that is run separately. Having that macro modify a file in your project as a side effect of being compiled would be extremely confusing.

This still applies to `build.rs`

**Comment by vityafx** [comment]
Wow, that's sad news. Thank you for this link :(

**Comment by vityafx** [comment]
Can I still have a file in src directory which includes contents from generated file in the target directory? According the link you posted, this will not violate any rules because the directory will remain unchanged.
