### ISSUE TITLE
Cannot find macro `table!` and cannot find derive macro `Queryable`

### ISSUE THREAD

**Issue by biot023** [diesel-rs/diesel#1811]
### Versions

- **Rust: rustc 1.27.2 (58cc626de 2018-07-18)**
- **Diesel: 1.3.2**
- **Database: PostgreSQL**
- **Operating System: Ubuntu 18.04**

### Feature Flags

- **diesel:**

## Problem Description

I followed the getting started tutorial and that worked okay.
But now I'm seeing these errors when I run `cargo check` on another project I'm trying to use diesel on.

* error: cannot find macro `table!` in this scope
* error: cannot find derive macro `Queryable` in this scope

The first in particular is in a file generated by diesel.

### What are you trying to accomplish?

Implementing the same functionality as the "getting started" tutorial, pretty much.

### What is the expected output?

That it should compile (or show me some other errors).

### What is the actual output?

> $ cargo check --verbose
>        Fresh unicode-xid v0.1.0
>        Fresh cc v1.0.18
>        Fresh libc v0.2.42
>        Fresh void v1.0.2
>        Fresh cfg-if v0.1.4
>        Fresh ucd-util v0.1.1
>        Fresh rustc-demangle v0.1.9
>        Fresh lazy_static v1.0.2
>        Fresh utf8-ranges v1.0.0
>        Fresh byteorder v1.2.4
>        Fresh bitflags v1.0.3
>        Fresh matches v0.1.7
>        Fresh proc-macro2 v0.4.9
>        Fresh proc-macro2 v0.3.8
>        Fresh memchr v2.0.1
>        Fresh time v0.1.40
>        Fresh rand v0.4.2
>        Fresh unreachable v1.0.0
>        Fresh regex-syntax v0.6.2
>        Fresh quote v0.6.4
>        Fresh quote v0.5.2
>        Fresh aho-corasick v0.6.6
>        Fresh num-traits v0.2.5
>        Fresh thread_local v0.3.5
>        Fresh serde v1.0.70
>        Fresh pq-sys v0.4.6
>        Fresh syn v0.14.7
>        Fresh syn v0.13.11
>        Fresh backtrace-sys v0.1.23
>        Fresh num-integer v0.1.39
>        Fresh regex v1.0.2
>        Fresh uuid v0.6.5
>        Fresh synstructure v0.9.0
>        Fresh serde_derive v1.0.70
>        Fresh diesel_derives v1.3.0
>        Fresh backtrace v0.3.9
>        Fresh chrono v0.4.5
>        Fresh failure_derive v0.1.2
>        Fresh diesel v1.3.2
>        Fresh failure v0.1.2
>        Fresh dotenv v0.13.0
>     Checking dp v0.1.0 (file:///home/me/work/home/rust/dp/dp)
>      Running `rustc --crate-name dp src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=b98d1f9a214d87e3 -C extra-filename=-b98d1f9a214d87e3 --out-dir /home/me/work/home/rust/dp/dp/target/debug/deps -C incremental=/home/me/work/home/rust/dp/dp/target/debug/incremental -L dependency=/home/me/work/home/rust/dp/dp/target/debug/deps --extern serde_derive=/home/me/work/home/rust/dp/dp/target/debug/deps/libserde_derive-0da1fdb6e3476cb6.so --extern uuid=/home/me/work/home/rust/dp/dp/target/debug/deps/libuuid-d10e8fac523e9907.rmeta --extern chrono=/home/me/work/home/rust/dp/dp/target/debug/deps/libchrono-64c508931f79b192.rmeta --extern serde=/home/me/work/home/rust/dp/dp/target/debug/deps/libserde-082b5e8e59eeb2b9.rmeta --extern diesel=/home/me/work/home/rust/dp/dp/target/debug/deps/libdiesel-3a4cd3de6c40644c.rmeta --extern dotenv=/home/me/work/home/rust/dp/dp/target/debug/deps/libdotenv-d099a357f49696b9.rmeta --extern matches=/home/me/work/home/rust/dp/dp/target/debug/deps/libmatches-368d41e99865b973.rmeta -L native=/usr/lib/x86_64-linux-gnu -L native=/home/me/work/home/rust/dp/dp/target/debug/build/backtrace-sys-6dfb52fe4b98ef15/out`
> error: cannot find macro `table!` in this scope
>  --> src/schema.rs:1:1
>   |
> 1 | table! {
>   | ^^^^^
> 
> error: cannot find derive macro `Queryable` in this scope
>  --> src/models.rs:1:10
>   |
> 1 | #[derive(Queryable)]
>   |          ^^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> error: Could not compile `dp`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name dp src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=b98d1f9a214d87e3 -C extra-filename=-b98d1f9a214d87e3 --out-dir /home/me/work/home/rust/dp/dp/target/debug/deps -C incremental=/home/me/work/home/rust/dp/dp/target/debug/incremental -L dependency=/home/me/work/home/rust/dp/dp/target/debug/deps --extern serde_derive=/home/me/work/home/rust/dp/dp/target/debug/deps/libserde_derive-0da1fdb6e3476cb6.so --extern uuid=/home/me/work/home/rust/dp/dp/target/debug/deps/libuuid-d10e8fac523e9907.rmeta --extern chrono=/home/me/work/home/rust/dp/dp/target/debug/deps/libchrono-64c508931f79b192.rmeta --extern serde=/home/me/work/home/rust/dp/dp/target/debug/deps/libserde-082b5e8e59eeb2b9.rmeta --extern diesel=/home/me/work/home/rust/dp/dp/target/debug/deps/libdiesel-3a4cd3de6c40644c.rmeta --extern dotenv=/home/me/work/home/rust/dp/dp/target/debug/deps/libdotenv-d099a357f49696b9.rmeta --extern matches=/home/me/work/home/rust/dp/dp/target/debug/deps/libmatches-368d41e99865b973.rmeta -L native=/usr/lib/x86_64-linux-gnu -L native=/home/me/work/home/rust/dp/dp/target/debug/build/backtrace-sys-6dfb52fe4b98ef15/out` (exit code: 101)

### Are you seeing any additional errors?

No.

### Steps to reproduce

Running `cargo check` on my codebase.

I have the following lines in my `src/lib.rs` file in this order:

```
extern crate diesel;
// ...
use diesel::prelude::*;
// ...
mod schema;
mod models;
```

The diesel-generated `src/schema.rs` file looks like this:

```
table! {
    users (id) {
        id -> Int4,
        email -> Varchar,
        given_name -> Varchar,
        family_name -> Varchar,
        crypted_password -> Varchar,
        admin -> Bool,
        deleted -> Bool,
    }
}
```

And the `src/models.rs` file looks like this:

```
#[derive(Queryable)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub given_name: String,
    pub family_name: String,
    pub crypted_password: String,
    pub admin: bool,
    pub deleted: bool,
}

```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
> 

    error: cannot find macro table! in this scope
    error: cannot find derive macro Queryable in this scope

This sounds like that the `#[macro_use]` annotation is missing on your `extern crate diesel;` import.

(I closed this issue because there is nothing actionable for the diesel team here. Feel free to response here or use our [gitter channel](https://gitter.im/diesel-rs/diesel) to ask future questions.)

**Comment by dataf3l** [comment]
biot023's answer helped!

**Comment by zwhitchcox** [comment]
> use our [gitter channel](https://gitter.im/diesel-rs/diesel) to ask future questions.)

Just wanted to point out that I would never have found this solution in the gitter channel, but it did help me here!

**Comment by zwhitchcox** [comment]
So it seems counterproductive to keep answering the same questions over and over on the gitter channel when you could just answer them once and make them googleable

**Comment by zwhitchcox** [comment]
> @zwhitchcox Gitter chat results are also indexed by google and show up in the search results if they are relevant. Also it is not useful to comment twice here with basically the same massage.

I did not realize that...also I did not comment twice with basically the same message. I would've just added it, but github marks your post as edited, and then people don't know what you edited. So, I could've just deleted the post and reposted it with the added information, but then it sends people multiple notifications, so it seemed preferable to just make another comment.

**Comment by christian-oudard** [comment]
Could someone update the tutorial to include the `#[macro_use]` annotation?

**Comment by weiznich** [comment]
@christian-oudard I'm not sure what you are revering to. Literally the first example showing rust code in the getting started guide already includes the necessary `#[macro_use]` annotation.

**Comment by christian-oudard** [comment]
`src/bin/show_posts.rs` is missing it, just a minor detail.

**Comment by weiznich** [comment]
@christian-oudard We are happy to receive a PR for this, though technically speaking `#[macro_use]` is not necessary to make exactly this example working.

**Comment by endermaz41** [comment]
@weiznich  actually it is needed, without the macro statement, the code does not compile.

**Comment by weiznich** [comment]
@endermaz41 `src/bin/show_posts.rs` compiles without `#[macro_use]`. Thats something w test in our CI. Generally speaking you are right, at least as soon as you use the `table!` macro or any similar macro you will need to have an `#[macro_use] extern crate diesel;` in your crate root.
