### ISSUE TITLE
Diesel CLI doesn't work with busybox `patch`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1817]
On gitter the following error was reported: ` stderr: patch: can't open 'src/db/schema.rs': File exists`. They were using busybox. Installing GNU patch appeared to fix the issue. That error message corresponds to `EEXIST`, which is likely coming from passing `O_EXCL` to `open`. I can confirm that busybox uses that, not sure about GNU.

If that is in fact the case, the solution is to close all open handles to the file before shelling out to `patch`. I'm not sure if that's actually a feasible option though, since our file is sometimes a tempfile (when I say I'm not sure though, I mean I'm *actually* not sure. Since `patch` overrides the file, it does make our previous handle invalid. If we were faced with a pathological tempfile system that immediately deletes the file when all handles to it are closed, I'm not sure if we even work *today*)

In any case, we need to:

- Determine if we can support busybox patch
- If yes, add a test for it which handles both updating `src/schema.rs` and printing to stdout
- If no, document this fact, and improve our error messaging
  - Ideally we would explicitly detect the existence of busybox vs GNU, but if that's not possible we can probably just look for `File exists` in stderr and say "you may be using busybox, we only support GNU"

I'm fine with a PR to improve our error message in the short term while we figure out if we can even support busybox.

**Comment by weiznich** [comment]
Fixed by using `diffy` instead of shelling out to a environment provided `patch` command.
See #2448
