### ISSUE TITLE
Support batch insert for pooled sqlite connections and/or make it clear that connection pooling shouldn't be used with SQLite

### ISSUE THREAD

**Issue by tahahawa** [diesel-rs/diesel#1822]
This was used to help reproduce the issue.

https://gitlab.com/tahahawa/discord-markov-bot/blob/eae22b1744348b70b5ceccbe9db148b34352b41b/src/commands/helper.rs

The code: 
```Rust
let conn = sql_pool.get().unwrap();
let _ = diesel::replace_into(messages::table)
    .values(message_vec)
    .execute(&conn)
    .expect("Error inserting values");
```

Causes:

```
error[E0277]: the trait bound `diesel::sqlite::Sqlite: diesel::backend::SupportsDefaultKeyword` is not satisfied
   --> src/commands/helper.rs:184:10
    |
184 |         .execute(&conn)
    |          ^^^^^^^ the trait `diesel::backend::SupportsDefaultKeyword` is not implemented for `diesel::sqlite::Sqlite`
    |
    = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<diesel::sqlite::Sqlite>` for `diesel::insertable::BatchInsert<'_, models::InsertableMessage, schema::messages::table>`
    = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<diesel::sqlite::Sqlite>` for `diesel::query_builder::InsertStatement<schema::messages::table, diesel::insertable::BatchInsert<'_, models::InsertableMessage, schema::messages::table>, diesel::query_builder::insert_statement::Replace>`
    = note: required because of the requirements on the impl of `diesel::query_dsl::load_dsl::ExecuteDsl<diesel::r2d2::PooledConnection<diesel::r2d2::ConnectionManager<diesel::SqliteConnection>>, diesel::sqlite::Sqlite>` for `diesel::query_builder::InsertStatement<schema::messages::table, diesel::insertable::BatchInsert<'_, models::InsertableMessage, schema::messages::table>, diesel::query_builder::insert_statement::Replace>`
```

Current fix:
Change `&conn` to `&*conn`

### Versions

- **Rust:**  1.28.0
- **Diesel:**  1.3.2
- **Database:** SQLite with R2D2 pooling
- **Operating System**  Arch Linux

### Feature Flags

- **diesel:**  ["sqlite","r2d2"]

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by BlockCat** [comment]
I have the exact same issue, is this being worked on?

**Comment by JeanMertz** [comment]
I ran into the same issue. It seems that SQLite does not support the `DEFAULT` keyword.

See also: https://github.com/diesel-rs/diesel/issues/157, https://github.com/diesel-rs/diesel/pull/164 and https://github.com/diesel-rs/diesel/pull/166.

I'm actually not sure what happens when you dereference `&conn` to `&*conn` as @tahahawa suggested, but given that this is not supported by SQLite, my guess would be that any fields not defined are actually kept blank? I haven't checked this.

**Comment by otavio** [comment]
@JeanMertz I've been bitten by this today; it turns out that single insert works fine.
