### ISSUE TITLE
Associations with generic types

### ISSUE THREAD

**Issue by moulins** [diesel-rs/diesel#1827]
I have the following two tables (with the corresponding `schema!`s):
```rust
#[derive(Debug, Queryable, Insertable, Identifiable)]
#[table_name = "foos"]
pub struct Foo<'a> {
    id: i32,
    stuff: Cow<'a, String>
}

#[derive(Debug, Queryable, Insertable, Identifiable, Associations)]
#[belongs_to(Foo)]
#[table_name = "bars"]
pub struct Bar {
    id: i32,
    foo_id: i32
}
```

The `#[derive(Associations)]` fail with `expected lifetime parameter`, because there is no way to refer to the generic lifetime `'a` of `Foo` in the `#[belongs_to]`. Did I overlook something which could allow me to use the derive?

------

Of course, I can implement `BelongsTo` manually, and everything seems to work:

```rust
impl<'a> BelongsTo<Foo<'a>> for Bar {
    type ForeignKey = i32;
    type ForeignKeyColumn = schema::bars::foo_id;
    
    fn foreign_key(&self) -> Option<&Self::ForeignKey> {
        Some(&self.foo_id)
    }

    fn foreign_key_column() -> Self::ForeignKeyColumn {
        schema::bars::foo_id
    }
}
```
But it would be nicer if we could specify these kinds of generic lifetimes, maybe with something like: `#[belongs_to(type="for<'a> Foo<'a>")]`?

**Comment by sgrif** [comment]
This is something we should support, but I'd like to see more discussion around what the API should be. We 100% need the lifetime declared in `belongs_to`, but I'm wondering if just `belongs_to("Foo<'a>")` makes more sense

**Comment by sgrif** [comment]
I think allowing elided lifetimes as the syntax makes perfect sense.

**Comment by moulins** [comment]
Nice, thanks for the work!
