### ISSUE TITLE
Switch to Azure for Windows CI

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1838]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

Appveyor has consistently been painful and slow for us to use, I'd like to look at whether Azure's CI option is an improvement.

**Comment by weiznich** [comment]
The first point in the [getting started](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts) there mentions that we could not just reuse the github org, but have to create a new one there:

> You need an Azure DevOps organization. If you don't have one, you can [create one for free](https://go.microsoft.com/fwlink/?LinkId=307137). If your team already has one, then make sure you're an administrator of the project you want to use.

**Comment by RaleighHokie** [comment]
You would still use your GitHub org, no need to migrate that, in that step you are creating an organization in Azure DevOps (our top level container is also called an organization) that you would then use to build your existing GitHub org with Azure Pipelines.

**Comment by jeremyepling** [comment]
@sgrif / @weiznich , I updated our docs to clarify that an Azure DevOps organization is different than a GitHub organization. People often use the same name for both so there's alignment between then.
