### ISSUE TITLE
Add support for date/time to SQLite

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#184]
Currently SQLite has no support for any of the date/time types. Let's add support back for these, as well as `SystemTime`. We should probably have an intermediate struct which others can reason about, similar to how we handled `PgDate` and friends.

**Comment by aperezdc** [comment]
There's an attempt to implement this in PR #344 — which is a bit old and seems to need some love.

**Comment by euclio** [comment]
Any way I can help get this moving? What still needs to be done?

**Comment by kballard** [comment]
Same here. I'd love to see this get done, and I'm happy to help if someone wants to provide some direction.

**Comment by killercup** [comment]
@euclio @kballard sorry, I wasn't watching this issue. We would definitely appreciate your help! I'm not sure I can really follow it, but I think the main issue with #344 is that we need to make sure that SQLite gives us date/times in a format we can definitely parse.

Maybe you can drop by [our Gitter room](https://gitter.im/diesel-rs/diesel) and we see how we can tackle this?

**Comment by Eijebong** [comment]
Oh, I missed this one :o 

Can this be closed now or is SQLite still missing something regarding date/time ? (see #887)

**Comment by sgrif** [comment]
Yeah, I think so. I had envisioned broader support than #887 added, but I don't see any way to do that since we *have* to do string parsing with these types.

**Comment by gentoo90** [comment]
Are there any plans to add schema inference for `DATE`, `TIME`, `DATETIME` and `TIMESTAMP`?
Currently (`master`, 560f650a89ffd283888362) they all fail:
```
diesel/diesel_cli $ sqlite3 test_datetime.db 'CREATE TABLE test (id INTEGER PRIMARY KEY, dt DATETIME)'
diesel/diesel_cli $ echo 'DATABASE_URL=test_datetime.db' > .env
diesel/diesel_cli $ RUST_BACKTRACE=1 cargo run print-schema
    Finished release [optimized] target(s) in 0.0 secs
     Running `/home/igor/projects/rust/diesel/target/release/diesel print-schema`
thread 'main' panicked at 'Could not load table `test`: StringError("Error determining type of test.dt: Unsupported type: datetime")', /checkout/src/libcore/result.rs:859
```

**Comment by Eijebong** [comment]
Yeah, it makes sense. Fixing it

**Comment by Eijebong** [comment]
This is now fixed. @gentoo90, thanks for the report :)

**Comment by gentoo90** [comment]
Thanks for the fix!
