### ISSUE TITLE
Using diesel_cli for development only and running migrations from the binary

### ISSUE THREAD

**Issue by kpcyrd** [diesel-rs/diesel#1840]
I'm not sure if this has been requested before, but I couldn't find anything in the issue tracker or the docs. If there's something, please point me to it.

My usecase is somewhat straightforward. I'm writing a small application that uses sqlite and I would like to use diesel to abstract the database layer (the examples in the guides look really good!).

What makes my usecase special: It seems diesel is supposed to be used together with diesel_cli in a way that an administrator runs migrations on the database before upgrading to a new version. This is a very sensible choice for deployments with multiple deployments that talk to a central database.

My usecase is much simpler in the way that only a local sqlite is used. This means that I don't want to ask the user to run database migrations manually, instead I want to have this part in my binary so I can trigger both the database initialization and execute migrations if needed.

Ideally, diesel_cli would only be used by developers in my usecase, while the user doesn't need to know what diesel is or how to run database migrations. :)

Please let me know what you think!

**Comment by weiznich** [comment]
You are basically describing the current state :wink:
(You are looking for diesel-migrations, especially [`embed_migrations!`](https://docs.rs/diesel_migrations/1.2.0/diesel_migrations/macro.embed_migrations.html))
