### ISSUE TITLE
[rfc] add methods for extracting `diesel::result::Error::NotFound`

### ISSUE THREAD

**Issue by derekdreery** [diesel-rs/diesel#1843]
I am proposing something like the following

```rust
// in `diesel::result`

pub trait ResultExt<T> {
    pub extract_not_found(self) -> Result<Option<T>, Error>;
}

impl<T> ResultExt<T> for Result<T, Error> {
    pub extract_not_found(self) -> Result<Option<T>, Error> {
        match self {
            Ok(t) => Ok(Some(t)),
            Err(Error::NotFound) => Ok(None),
            Err(e) => Err(e)
        }
    }
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. Apologies if I missed anything.

**Comment by sgrif** [comment]
http://docs.diesel.rs/diesel/result/trait.OptionalExtension.html#tymethod.optional

**Comment by derekdreery** [comment]
Urgh, I was sure I'd looked. Apologies.
