### ISSUE TITLE
Add a function to embedded_migrations! to check if migration is needed

### ISSUE THREAD

**Issue by kpcyrd** [diesel-rs/diesel#1845]
It seems right now two functions are exported in the module that is generated by `embedded_migrations!`:

- `run`
- `run_with_output`

I would like to have a 3rd function, along the lines of `fn migrations_needed() -> bool`, that can be used to check if migrations are available/needed.

The idea is that this function can be used to determine if `embedded_migrations::run` needs to be executed and also to inform the user that migrations are going to be executed:

```rust
if embedded_migrations::migrations_needed() {
    println!("executing migrations);
    embedded_migrations::run(&db)?;
}
```

**Comment by sgrif** [comment]
Thank you for the feature request. We're currently in the process of a cleanup of the issue tracker, and aren't currently accepting feature requests (there will be an official policy written soon, but the TL;DR is that open issues should reflect something that is a bug or on our immediate roadmap).

We're happy to discuss feature requests, but the place to do so is discourse.diesel.rs, not the issue tracker.
