### ISSUE TITLE
Update versions of syn/quote/proc-macro2

### ISSUE THREAD

**Issue by bobtwinkles** [diesel-rs/diesel#1848]
## Setup
Add `diesel = 1.3` to a crate's Cargo.toml

### Versions

- **Rust:** `rustc 1.29.0-nightly (12ed235ad 2018-07-18)` or `rustc 1.27.1 (5f2b325f6 2018-07-07)`
- **Diesel:** 1.3.2
- **Database:** N/A
- **Operating System** N/A

### Feature Flags

- **diesel:** N/A

## Problem Description
Using `serde` and `diesel` in the same project result in 2 versions of the `syn`/`quote`/`proc-macro2` constellation of crates being compiled. It would be better if this didn't happen.

### What are you trying to accomplish?
Use `serde` and `diesel` in the same crate

### What is the expected output?
Only one version of `syn`/`quote`/`proc-macro2` is compiled.

### What is the actual output?
Two versions are compiled:
From `serde_derive 1.0.78` we have:
  - `proc-macro2 0.4.19`
  - `quote 0.6.8`
  - `syn 0.15.4`

From `diesel_derive 1.3.0`:
  - `proc-macro2 0.3.8`
  - `quote 0.5.2`
  - `syn 0.13.11`

### Are you seeing any additional errors?
No.

### Steps to reproduce
Add Serde and Diesel to the same crate

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by bobtwinkles** [comment]
For what it's worth, I'm willing to take a stab at fixing this if nobody else is working on it.

**Comment by Eijebong** [comment]
https://github.com/diesel-rs/diesel/commit/54b21b0d8d285ebce1c9df363a5b2eecf3e8298e It's already on master

**Comment by bobtwinkles** [comment]
Awesome, thanks!
