### ISSUE TITLE
Possible to bundle sqlite in binary?

### ISSUE THREAD

**Issue by brycefisher** [diesel-rs/diesel#1860]
## Problem Description
I'm looking at the various rust bindings for sqlite in rust for a personal project. I see that diesel uses libsqlite3-sys for sqlite. Is it possible to compile sqlite into my final binary with diesel as can be done with rusqlite?

**Comment by sgrif** [comment]
https://github.com/diesel-rs/diesel/blob/master/diesel_cli/Cargo.toml#L43

**Comment by Mcat12** [comment]
@sgrif That `sqlite-bundled` feature is in `diesel_cli`, not `diesel`. Is there an equivalent way to do this with the actual Diesel library?

**Comment by weiznich** [comment]
Just add `libsqlite3-sys = { version = ">=0.8.0, <0.13.0", optional = true, features = ["bundled"] }` to your Cargo.toml.

**Comment by Mcat12** [comment]
@weiznich Right, but what about when Diesel changes the version range? Optimally we would not have to change anything.

**Comment by weiznich** [comment]
@Mcat12 Diesel will not bump the minimal supported version of any dependency without of a major version bump of diesel. Sot that's not a big concern.
Also we cannot and will not export any feature flag of any of our dependencies. That won't scale.
