### ISSUE TITLE
barrel-migrations is broken

### ISSUE THREAD

**Issue by SWW13** [diesel-rs/diesel#1864]
### Versions
- **Rust:** nightly (rustc 1.29.0 (aa3ca1994 2018-09-11))
- **Diesel:** 1.3.3 / master
- **Database:** psql
- **Operating System** linux

### Feature Flags
- **diesel:** `barrel-migrations,postgres`

## Problem Description
Using the `barrel-migrations`-feature is broken in the current diesel / barrel version.

### What are you trying to accomplish?
Use diesel with barrel as described in https://github.com/spacekookie/barrel/blob/master/guides/diesel-setup.md.

### What is the expected output?
Working migrations.

### What is the actual output?
[diesel 1.3.3, barrel <= 0.2.0]
```bash
$ diesel migration run
Running migration mod.rs
Received an empty query
```

[diesel master, barrel master]
```bash
$ diesel migration run
Running migration mod.rs
Executing migration script /path/to/project/migrations/2018-09-21-125612_init_db/mod.rs/up.sql
Failed with: Received an empty query
```

### Are you seeing any additional errors?
[diesel 1.3.3, barrel <= 0.2.0]
The temporary created migration project build fails silently in the background:
```bash
$ cargo build
   Compiling tmp-generator v0.0.0 (file:///tmp/barrel.nkunnkN46LTx)                                                                                                                                 
error: couldn't read "/path/to/project/migrations/2018-09-21-125612_init_db/mod.rs/mod.rs": Not a directory (os error 20)
 --> src/main.rs:8:1
  |
8 | include!("/path/to/project/migrations/2018-09-21-125612_init_db/mod.rs/mod.rs");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `tmp-generator`.

To learn more, run the command again with --verbose.
```

### Steps to reproduce
Follow https://github.com/spacekookie/barrel/blob/master/guides/diesel-setup.md.

## Checklist
- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
  You're kidding?! `diesel_cli` with `barrel-migrations` doesn't build on stable.

---

This seems to be a problem in combination with `barrel`, I'm going to investigate this further.

**Comment by sgrif** [comment]
Barrel is a separate project, and is not maintained by Diesel. Please open an issue with that project instead.

**Comment by spacekookie** [comment]
There already is an issue. I doubt that it's actually the code in `diesel` that's causing the issue. But I'll have a look at it tomorrow.
