### ISSUE TITLE
Custom sql function with rust implementation

### ISSUE THREAD

**Issue by giovanniberti** [diesel-rs/diesel#1877]
Is it possible to have a rust function/operator calling in SQL/Diesel DSL?
I need it to store and retrieve passwords from a db, and I'm using the `scrypt` crate, which has a `scrypt_check` function, so I can't use the simple `.eq()` function from diesel's dsl.

**Comment by sgrif** [comment]
This is entirely dependent on how your database works. For SQLite, yes. For other DBs you would need to write an extension for your database server which is outside of the scope of Diesel.
