### ISSUE TITLE
Dynamically Loading values into Select Statements

### ISSUE THREAD

**Issue by acycliczebra** [diesel-rs/diesel#1887]
I want to load values dynamically into my select statement. Is this possible in Diesel?

I would Ideally like to be able to pass a vector that I can dynamically generate, and get back as dynamically typed values in return.

Here's a simplified version of the problem:
```
let columns = binding_at_runtime(); // at runtime, either returns ("a",), ("b",), ("a", "b") or ("b", "a"), or ("a", "b", "c"), or ("a", "c", "b"), etc.
let data: Vec<Vec<Value>> = my_table.select(columns).load(&conn)?;
```

Thanks everyone!

**Comment by weiznich** [comment]
How would `Value` looks like in that case?

(I've closed this issue because our issue tracker should only contain actionable bugs where someone is actively working on or where we are looking for help. For feature request use our [forum](https://discourse.diesel.rs/))
