### ISSUE TITLE
Insert Embedded Struct for AsChangeset

### ISSUE THREAD

**Issue by lancecarlson** [diesel-rs/diesel#1917]
Will diesel support #[diesel(embed)] on AsChangeset structs? Would be nice for reuse between Insertable and "update-able" structs.

**Comment by technetos** [comment]
This would be really cool integrated into diesel.  In the meantime I happen to do exactly this in a macro I wrote and your welcome to come check it out.   [link-to-macro](https://github.com/technetos/postgres-resource/blob/master/postgres_resource_derive/src/lib.rs#L419-L443)

**Comment by sgrif** [comment]
> Will diesel support #[diesel(embed)] on AsChangeset structs?

Yes. I just haven't gotten around to implementing it. IIRC the last time I worked on it, there was a weird interaction between `treat_none_as_null = "true"` and `embed` on an `Option` field that I wanted to think about. Feel free to open a PR for this, though.

**Comment by vnghia** [comment]
Hello, how is the status of this feature ?. I could try to work on it if nobody does right now.

**Comment by weiznich** [comment]
@vnghia That's not implemented yet, but we would be grateful to receive a PR for this. 

You can find the code for the derive here: https://github.com/diesel-rs/diesel/blob/09d5e1050a40d698b10af98bd10495c98ccfaa7f/diesel_derives/src/as_changeset.rs

The `Insertable` derive already supports the `embed` attribute: https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/insertable.rs
You might be able to use that as blue print for how to approach the implementation.

**Comment by prestontw** [comment]
Hello! This is probably a dumb question, but is the code in the linked PR available on the latest version from crates.io? I was trying to use `#[diesel(embed)]` for a struct with `#[derive(AsChangeset)]`, but I was getting

```
error[E0412]: cannot find type `attributes` in module `crate::schema::contacts`
  --> src/model.rs:41:9
   |
41 |     pub attributes: ContactAttributes,
   |         ^^^^^^^^^^ not found in `crate::schema::contacts`

error[E0425]: cannot find value `attributes` in module `crate::schema::contacts`
  --> src/model.rs:41:9
   |
41 |     pub attributes: ContactAttributes,
   |         ^^^^^^^^^^ not found in `crate::schema::contacts`
```

Checking the latest commit in the `2.2.x` branch, I don't see the code from the PR (https://github.com/diesel-rs/diesel/blob/55d90e04e570f9fb88b69eb0f6ceed58ea92b652/diesel_derives/tests/as_changeset.rs). Checking the `2.2.x` docs (https://docs.diesel.rs/2.2.x/diesel/prelude/derive.AsChangeset.html) and the docs linked from crates.io (https://docs.rs/diesel/2.2.7/diesel/prelude/derive.AsChangeset.html), I don't see the documentation from the linked PR either.

If I check the latest docs from `master` (https://docs.diesel.rs/master/diesel/prelude/derive.AsChangeset.html), I can see support for this attribute. And if I patch crates.io with 

```toml
[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "828e51f848d31390632d1b19c760df404642e0c6" }
```

then I no longer encounter the above errors.

Thank you for all of the work! Let me know if a MWE would be helpful.

**Comment by vnghia** [comment]
It is not yet available. I've been ussing git url for a while now
