### ISSUE TITLE
`single_value` and non-nullable field

### ISSUE THREAD

**Issue by alexfedoseev** [diesel-rs/diesel#1918]
I'm trying to use `single_value` function in `INSERT` statement with non-nullable field to ensure validity of reference:

```rust
table! {
  data (id) {
    id -> Int4,
    title -> Text,
    project_id -> Int4,
  }
}
```

```rust
diesel::insert_into(data::table)
  .values((
    data::project_id.eq(
      projects::table
        .select(projects::id)
        .filter(
          projects::id
            .eq(&project_id)
            .and(projects::user_id.eq(&user_id)),
        ).single_value(),
    ),
    data::title.eq(&msg.title),
  )).get_result::<Data>(&*self.pool.get())
```

But it gives me type error since `single_value` always returns `Nullable` but `project_id` is non-nullable. In this case, if this sub-select returns `NULL` it means something really fishy is going on and I don't mind unwrapping this `NULL` on db level (i.e. just receive DB error on Rust side) but I'm not sure if it's possible within current api. Is there any way to do this w/ ORM or I should fallback to raw SQL? (or any other advice how to handle such scenario is appreciated)

**Comment by alexfedoseev** [comment]
SQL that I'm attempting to express via DSL:

```sql
INSERT INTO data (title, project_id)
SELECT $1, $2
WHERE EXISTS(
  SELECT * FROM projects
  WHERE id = $2 AND user_id = $3
)
RETURNING *
```

Not sure yet if it's possible to express such `SELECT`.

**Comment by weiznich** [comment]
As you noted that's not certain that this will return really a value, because there could be no value :wink:.
Therefore diesel itself will not provide such a function.

That said it is possible to extend diesel in your crate to provide something that does exactly this:

```rust

struct AssertNotNull<T, ST>(T, ::std::marker::PhantomData<ST>);

fn unsafe_assert_not_null<T, ST>(t: T) -> AssertNotNull<T, ST>
where T: Expression<SqlType = Nullable<ST>>,
      ST: NotNull
{
    AssertNotNull(t, Default::default())
}

impl<T, ST> Expression for AssertNotNull<T, ST>
where T: Expression<SqlType = Nullable<ST>>,
      ST: NotNull,
{
    type SqlType = ST;
}

impl<DB, T, ST> QueryFragment<DB> for AssertNotNull<T, ST>
where T: QueryFragment<DB>,
      DB: Backend
{

    fn walk_ast(&self, pass: AstPass<DB>) -> Result<(), Error> {
        self.0.walk_ast(pass)
    }
}
```

Then just wrap the corresponding query into `unsafe_assert_not_null(your_query)`.

**Comment by alexfedoseev** [comment]
Thanks! One more question: is it possible w/ DSL perform such `SELECT`?

```sql
SELECT $1, $2
WHERE EXISTS(
  SELECT * FROM projects
  WHERE id = $2 AND user_id = $3
)
```

My naive implementation doesn't work:

```rust
// `foo` & `bar` are dynamic values
diesel::select((&foo, &bar)).filter(diesel::select(exists(
  projects::table
    .filter(projects::id.eq(&project_id))
    .filter(projects::user_id.eq(&user_id)),
)));
```

**Comment by weiznich** [comment]
Maybe the following:
``rust
diesel::select((&foo, &bar)).filter(exists(diesel::select(
  projects::table
    .filter(projects::id.eq(&project_id))
    .filter(projects::user_id.eq(&user_id)),
)));
```

**Comment by alexfedoseev** [comment]
Eh, nope, this doesn't work either. I'll move to forums w/ this one. Thanks for help!

**Comment by toxeus** [comment]
The workaround described above isn't required on latest master since https://github.com/diesel-rs/diesel/pull/2820 has been merged.
