### ISSUE TITLE
r2d2::Error vs diesel::r2d2::Error

### ISSUE THREAD

**Issue by mocsy** [diesel-rs/diesel#1919]
Hi
I am trying to change .unwrap to ? in some of my diesel code.
I got: `the trait bound diesel::r2d2::Error: std::convert::From<r2d2::Error> is not satisfied`

Is this by intention/design or just something not yet done?
the get() method of diesel::r2d2::Pool returns r2d2::Error and not diesel::r2d2::Error, that's how I ran into this

**Comment by sgrif** [comment]
See http://docs.diesel.rs/diesel/r2d2/type.PoolError.html

**Comment by Lindenk** [comment]
This is still a problem. The only workaround seems to be importing and maintaining the correct version of `r2d2` manually.

**Comment by weiznich** [comment]
1. As Sean pointed out above the error type is reexported with a different name in the `diesel::r2d2` module.
2. That issue is now over an year closed. If you think that issue some old issue has regressed please open a new issue.
