### ISSUE TITLE
Diesel logo should be yellow instead of red

### ISSUE THREAD

**Issue by ejunker** [diesel-rs/diesel#1922]
This isn’t a big issue but I thought I would mention it just so you are aware of it. Gasoline is stored in red containers  and yellow containers are used for diesel.

From the Wikipedia page on diesel:
> In the US, diesel is recommended to be stored in a yellow container to differentiate it from kerosene and gasoline, which are typically kept in blue and red containers, respectively.

Feel free to close this issue.

**Comment by Rio** [comment]
Also don't forget to add the appropriate label to indicate that it's synthetic diesel to be [EU compliant](http://europa.eu/rapid/press-release_MEMO-18-6102_en.htm).

> Diesel-type fuels: square. B7, B10, XTL, etc. (“B” stands for specific biodiesel components present in diesel, the XTL stands for synthetic diesel and indicates that it is not derived from crude oil);

![](http://ec.europa.eu/avservices/avs/files/video6/repository/prod/photo/store/store2/14/P038414-693973.jpg)

**Comment by sgrif** [comment]
You're not the first person to have brought this up. Yellow isn't correct for folks outside of the US, either. It varies by country (though no country uses red as far as I know. :wink:)
