### ISSUE TITLE
PostgreSQL database connection fails: No such file or directory

### ISSUE THREAD

**Issue by RalfJung** [diesel-rs/diesel#1934]
### Versions

- **Rust:** rustc 1.31.0 (abe02cefd 2018-12-04)
- **Diesel:** 1.3.3
- **Database:** PostgreSQL 11.1
- **Operating System** Linux, Debian testing

### Feature Flags

- **diesel:** postgres

## Problem Description

Establishing a DB connection to a postgresql server with the URL `postgres://r@/ff-node-monitor` fails saying
```
BadConnection("could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n")
```

### What are you trying to accomplish?

Connecting to a PostgreSQL server.

### What is the expected output?

A successful connection.

### What is the actual output?

```
BadConnection("could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n")
```

It seems like the PID is off-by-1 for some reason:
```
$ ls /var/run/postgresql/ -lah
total 8,0K
drwxrwsr-x  3 postgres postgres  120 Dez  8 12:23 .
drwxr-xr-x 36 root     root     1,1K Dez  8 09:32 ..
drwxr-s---  2 postgres postgres  120 Dez  8 12:33 11-main.pg_stat_tmp
-rw-r--r--  1 postgres postgres    5 Dez  8 12:23 11-main.pid
srwxrwxrwx  1 postgres postgres    0 Dez  8 12:23 .s.PGSQL.5433
-rw-------  1 postgres postgres   69 Dez  8 12:23 .s.PGSQL.5433.lock
```

I don't know how diesel and postgres interact here. `psql` itself is working fine. This also used to work fine several weeks ago, but since then both postgres and diesel were updated.

### Are you seeing any additional errors?

No.

### Steps to reproduce

```rust
fn main() {
  use diesel::pg::PgConnection;
  use diesel::connection::Connection;
  PgConnection::establish("postgres://r@/ff-node-monitor").unwrap();
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case.)

(This stable-only requirement makes it a *lot of work* to create a bugreport, when the issue only occurs in a nightly-only project. For errors like this one, I don't think it is reasonable.)

**Comment by RalfJung** [comment]
Turns out Debian considers it normal to change the psql DB port during a DB upgrade.  Hence my DB now listens on port 5433, where it previously listened on 5432.  I find that rather startling, but it's not diesel's problem.

**Comment by weiznich** [comment]
Seems like this is a configuration error. 

The "requirement" to reproduce this on stable is coming from a time where we got the same bug report about some known nightly breakage several times a day.
