### ISSUE TITLE
`NOW(6)` and `sql_function` vs `no_arg_sql_function`

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#1938]
I'm not sure whether this a bug or just a documentation issue + a feature request.

### What are you trying to accomplish?

I want to call the MySQL function `NOW(6)` in order to get a precise timestamp (`NOW()` on its own does not include fractions of a second)

## Problem Description

Initially I tried defining the function with a single integer argument using `sql_function!`. However, this does not work because MySQL expects the `6` to be constant, and so it can't be substituted in as a prepared statement.

Next I tried defining a stored function in a migration, and then calling that with the help of `sql_function!` with no arguments. However, the `sql_function!` macro does not allow defining functions with zero arguments.

After some more searching, I found the `no_arg_sql_function!` macro, but this does not allow changing the name of the defined function.

Either the `sql_function!` macro should support functions with no arguments, or the `no_arg_sql_function!` macro should be more easily discover-able, and should allow using a different name on the SQL side from the rust side.

Also, it may be worth changing the built-in `now` function to always return a more precise result when using the MySQL backend.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
For a case like this, it seems like just using [`sql`](http://docs.diesel.rs/diesel/dsl/fn.sql.html) is the easiest solution if you want something lightweight. If you want something that's used in Diesel's query builder, you can certainly create a struct that represents this.

```
#[derive(Debug, Copy, Clone, QueryId)]
pub struct Now6;

impl Expression for Now6 {
    type SqlType = Timestamp;
}

impl NonAggregate for Now6 {}

impl QueryFragment<MySql> for Now6 {
    fn walk_ast(&self, mut out: AstPass<Mysql>) -> QueryResult<()> {
        out.push_sql("NOW(6)");
        Ok(())
    }
}
```
