### ISSUE TITLE
error: linking with `link.exe` failed: exit code: 1181

### ISSUE THREAD

**Issue by ScottHuangZL** [diesel-rs/diesel#1939]
### Versions

- **Rust:**
rustc 1.33.0-nightly (2d3e909e4 2018-12-22)
- **Diesel:**
diesel_cli v1.3.1
- **Database:**
postgres
postgres (PostgreSQL) 11.1
- **Operating System**
Win10 64
### Feature Flags
cargo install diesel_cli --no-default-features --features postgres  --verbose

- **diesel:**

## Problem Description
error: linking with `link.exe` failed: exit code: 1181
 = note: LINK : fatal error LNK1181:

**error: aborting due to previous error

error: failed to compile `diesel_cli v1.3.1`, intermediate artifacts can be found at `C:\Users\SCOTT_~1\AppData\Local\Temp\cargo-installK72CX1`

Caused by:
  Could not compile `diesel_cli`.**
### What are you trying to accomplish?
build the diesel_cli

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by join2nk** [comment]
adding this to cargo.toml dependences work
```
rusqlite = { version = "0.29.0", features = ["bundled"] }
```
