### ISSUE TITLE
Add support for PostgreSQL composite types composed from other ones

### ISSUE THREAD

**Issue by manifest** [diesel-rs/diesel#1940]
### Versions

- **Rust:**
rustc 1.31.1 (b6c32da9b 2018-12-18)
rustup 1.16.0 (beab5ac2b 2018-12-06)
- **Diesel:**
master branch, rev=59aa49b
- **Database:**
PostgreSQL
- **Operating System**
macOS

### Feature Flags

- **diesel:**
["postgres", "uuid", "chrono"]

## Problem Description
I have two PostgreSQL composite types. One is constructed from another.
```rust
create type account_id as (
    label text,
    audience text
);

create type agent_id as (
    account_id account_id,
    label text
);
```
It's simple to implement a pair of `ToSql` and `FromSql` for the first type `agent_id(label, audience)`. The problem is to implement the same traits for the second type `agent_id(account_id(label, audience), label)` since there are no implementations of `WriteTuple` for records of records.

### What are you trying to accomplish?
```rust
#[derive(SqlType)]
#[postgres(type_name = "agent_id")]
#[allow(non_camel_case_types)]
pub struct Agent_id;

impl ToSql<Agent_id, Pg> for AgentId {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
        self.account_id.to_sql(out)?;
        WriteTuple::<(Account_id, Text)>::write_tuple(
            &(
                out,
                &self.label,
            ),
            out,
        )
    }
}
```

### What is the expected output?
no compilation error

### What is the actual output?
compilation error
```rust
the trait bound `&mut diesel::serialize::Output<'_, W, diesel::pg::Pg>: diesel::serialize::ToSql<transport::sql::Account_id, diesel::pg::Pg>` is not satisfied
   --> src/transport/mod.rs:366:13
    |
366 |             WriteTuple::<(Account_id, Text)>::write_tuple(
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `diesel::serialize::ToSql<transport::sql::Account_id, diesel::pg::Pg>` is not implemented for `&mut diesel::serialize::Output<'_, W, diesel::pg::Pg>`
    |
    = note: required because of the requirements on the impl of `diesel::serialize::WriteTuple<(transport::sql::Account_id, diesel::sql_types::Text)>` for `(&mut diesel::serialize::Output<'_, W, diesel::pg::Pg>, &std::string::String)`
    = note: required by `diesel::serialize::WriteTuple::write_tuple`
```

### Are you seeing any additional errors?
no

### Steps to reproduce
1. Add migration with the sql types
2. Add the implementation of `ToSql`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
The error you're getting from the compiler is correct. You're passing it the output stream as the first element of your tuple, which doesn't really make any sense. You haven't included the definition of your `AgentId` type. Assuming it has an `agent_id` field, your first usage of `out` should be `self.agent_id`. You will also need to provide `impl ToSql<Agent_id, Pg> for AgentId` if you haven't already done so.

**Comment by manifest** [comment]
@sgrif sorry I forgot about type definitions. Could you please elaborate what should be a first argument for `WriteTuple::<(Account_id, Text)>::write_tuple` for the the following case? It isn't clear because the first argument for in my case is a Record.

```rust
#[derive(Debug, Clone, FromSqlRow, AsExpression)]
#[sql_type = "sql::Account_id"]
pub(crate) struct AccountId {
    label: String,
    audience: String,
}

#[derive(Debug, Clone, FromSqlRow, AsExpression)]
#[sql_type = "sql::Agent_id"]
pub(crate) struct AgentId {
    label: String,
    account_id: AccountId,
}

pub mod sql {

    use super::AccountId;
    use super::AgentId;

    use diesel::deserialize::{self, FromSql};
    use diesel::pg::Pg;
    use diesel::serialize::{self, Output, ToSql, WriteTuple};
    use diesel::sql_types::{Record, Text};
    use std::io::Write;

    #[derive(SqlType)]
    #[postgres(type_name = "account_id")]
    #[allow(non_camel_case_types)]
    pub struct Account_id;

    impl ToSql<Account_id, Pg> for AccountId {
        fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
            WriteTuple::<(Text, Text)>::write_tuple(&(&self.label, &self.audience), out)
        }
    }

    impl FromSql<Account_id, Pg> for AccountId {
        fn from_sql(bytes: Option<&[u8]>) -> deserialize::Result<Self> {
            let (label, audience): (String, String) =
                FromSql::<Record<(Text, Text)>, Pg>::from_sql(bytes)?;
            Ok(AccountId::new(&label, &audience))
        }
    }

    #[derive(SqlType)]
    #[postgres(type_name = "agent_id")]
    #[allow(non_camel_case_types)]
    pub struct Agent_id;

    impl ToSql<Agent_id, Pg> for AgentId {
        fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
            WriteTuple::<(Account_id, Text)>::write_tuple(
                &(
                    ...
                    &self.label,
                ),
                out,
            )
        }
    }

}
```
