### ISSUE TITLE
Projects using diesel master fail to compile unless a replace for `diesel_derives` is specified

### ISSUE THREAD

**Issue by ZeGentzy** [diesel-rs/diesel#1941]
### Versions

- **Rust:** rustc 1.31.1 (b6c32da9b 2018-12-18)
- **Diesel:** master
- **Database:** Irrelevant
- **Operating System** Arch Linux 4.19.6.a

### Feature Flags

- **diesel:**
## Problem Description

Diesel doesn't compile. This is caused by this commit: https://github.com/diesel-rs/diesel/commit/1fdad5b931ed4bc5f442f7505a016f8d07052b2b

### What are you trying to accomplish?

I wanted to use the latest master for #1771.

### What is the expected output?

Well, compiling.

### What is the actual output?

https://gist.github.com/ZeGentzy/9486867d1141e6af2a5144257c663cf5

### Steps to reproduce

I have just installed a fresh copy of Rust (through rustup).
Just make a new project with this `Cargo.toml`:
```
[package]
name = "diesel_test"
version = "0.1.0"
authors = ["Hal Gentz <zegentzy@protonmail.com>"]
edition = "2018" # doesn't effect error

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel.git" }
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by ZeGentzy** [comment]
Apparently the `Cargo.toml` above is not enough, instead you need to clone diesel manually and do the following:
```
[package]
name = "diesel_test"
version = "0.1.0"
authors = ["Hal Gentz <zegentzy@protonmail.com>"]
edition = "2018"

[dependencies]
diesel = { path = "diesel/diesel" }

[replace]
"diesel_derives:1.3.0" = { path = "diesel/diesel_derives" }
```

Hopefully this gets documented somewhere or diesel_derives gets a version bump or something.

**Comment by sgrif** [comment]
This really isn't something we can prevent. Diesel as a project is a set of crates which evolve as a whole package. `diesel_derives` relies on internal, private APIs of Diesel, which may change or break freely between versions. `diesel_derives` is not expected to work with a different version of `diesel`. If you're pointing at master for one, you will need to point at master for the other. This isn't something we're able to automate for you.

Note that your assertion of needing to clone manually is incorrect, you can use the `replace` or `patch` sections of `Cargo.toml` for this, which are well documented in Cargo's documentation.
