### ISSUE TITLE
Diesel+ Ipnetwork

### ISSUE THREAD

**Issue by toplinuxsir** [diesel-rs/diesel#1942]
### Versions

- **Rust:** 1.31.1
- **Diesel:** 1.33
- **Database:** postgresql
- **Operating System** Debian 9.0

### Feature Flags

- **diesel:**

## Problem Description

^^ the trait `diesel::Queryable<diesel::sql_types::Inet, diesel::pg::Pg>` is not implemented for `diesel_op::model::ipnetwork::IpNetwork`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
You need to enable the "network-address" feature.

**Comment by toplinuxsir** [comment]
I have already enabled the network-address
```
diesel={version="1.3", features=["postgres", "chrono", "r2d2", "network-address"]}
```

**Comment by weiznich** [comment]
Diesel 1.3 does not support ipnetwork 0.13. You need to use version 0.12. 
The next diesel version will add support for 0.13.
