### ISSUE TITLE
can not call into_boxed()

### ISSUE THREAD

**Issue by toplinuxsir** [diesel-rs/diesel#1943]
### Versions

- **Rust:** 1.31
- **Diesel:** 1.33
- **Database:** postgres
- **Operating System** debian 9.2

### Feature Flags

- **diesel:**

## Problem Description
```
table! {
    radpostauth (id) {
        id -> Int8,
        username -> Text,
        pass -> Nullable<Text>,
        reply -> Nullable<Text>,
        calledstationid -> Nullable<Text>,
        callingstationid -> Nullable<Text>,
        authdate -> Timestamptz,
    }
}


```

error[E0283]: type annotations required: cannot resolve `_: diesel::backend::Backend`
  --> src/diesel_op/msg.rs:57:32
   |
57 |     let query = radacct::table.into_boxed();

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
You need to do exactly what the error message tells you to do: `radacct::table.into_boxed<YourDBType>()` where YourDBType is some concrete database type (`Pg`, `Sqlite` or `Mysql`).

**Comment by toplinuxsir** [comment]
Thanks , I got it!
