### ISSUE TITLE
Ease JSONB usage

### ISSUE THREAD

**Issue by z0mbie42** [diesel-rs/diesel#1950]
### Versions

- **Diesel:** 1.3.3
- **Database:** Postgres

### Feature Flags

- **diesel:** ["postgres", "uuid", "serde_json"]

## Problem Description

As far as I'm aware, the official way to deal with `JSONB` values in postgres is by using `serde_json::Value`.
Today I tried to use a `struct` instead
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct Body {
    pub text1: String,
    pub text2: String,
}

#[derive(Debug, Identifiable, Queryable)]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub body: Body,
    pub published: bool,
}

#[derive(Insertable)]
#[table_name="posts"]
pub struct NewPost {
    pub title: String,
    pub body: Body,
}
```

to use postgres as a sort of hybrid relational / document store. But it was really not straightforward, I had to manually implement `Queryable` for `Post` (see https://github.com/z0mbie42/diesel_json/blob/master/src/models.rs) and never had success to get it working.
```
error[E0277]: the trait bound `models::Body: diesel::query_builder::QueryFragment<_>` is not satisfied
  --> src/main.rs:34:10
   |
34 |         .get_result(conn)
   |          ^^^^^^^^^^ the trait `diesel::query_builder::QueryFragment<_>` is not implemented for `models::Body`
   |
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<_>` for `&models::Body`
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<_>` for `diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>`
   = note: required because of the requirements on the impl of `diesel::insertable::InsertValues<schema::posts::table, _>` for `diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>`
   = note: required because of the requirements on the impl of `diesel::insertable::InsertValues<schema::posts::table, _>` for `(diesel::insertable::ColumnInsertValue<schema::posts::columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &std::string::String>>, diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>)`
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<_>` for `diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<schema::posts::columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &std::string::String>>, diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>), schema::posts::table>`
   = note: required because of the requirements on the impl of `diesel::query_builder::QueryFragment<_>` for `diesel::query_builder::InsertStatement<schema::posts::table, diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<schema::posts::columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &std::string::String>>, diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>), schema::posts::table>, diesel::query_builder::insert_statement::Insert, diesel::query_builder::returning_clause::ReturningClause<(schema::posts::columns::id, schema::posts::columns::title, schema::posts::columns::body, schema::posts::columns::published)>>`
   = note: required because of the requirements on the impl of `diesel::query_dsl::LoadQuery<_, _>` for `diesel::query_builder::InsertStatement<schema::posts::table,diesel::query_builder::ValuesClause<(diesel::insertable::ColumnInsertValue<schema::posts::columns::title, diesel::expression::bound::Bound<diesel::sql_types::Text, &std::string::String>>, diesel::insertable::ColumnInsertValue<schema::posts::columns::body, &models::Body>), schema::posts::table>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`
```

until I found https://github.com/terry90/diesel_as_jsonb which does it automagically by simply deriving a trait:
```rust
#[derive(Debug, Serialize, Deserialize, AsJsonb)]
pub struct Body {
    pub text1: String,
    pub text2: String,
}
```

### What are you trying to accomplish?

Ease the use of a `JSONB` field with a typed `struct`.

### What is the expected output?

incorporate a macro like https://github.com/terry90/diesel_as_jsonb in diesel core

As i'm new to Rust, I'll enjoy to create a PR with a little help / guidance.

**Comment by weiznich** [comment]
In my opinion such a thing does not need to be in diesel core. Our general rule is to only provide `ToSql`/`FromSql` implementations for things that basically cannot fail. That's not the case here because those implementations will fail as soon as some other json than the expected in the column.

That said it's already not that hard to write the corresponding code to use a struct for a json field in your crate:
```rust
#[derive(FromSqlRow, AsExpression, Debug, Serialize, Deserialize)]
#[sql_type = "Jsonb"]
pub struct Body {
    pub text1: String,
    pub text2: String,
}

impl FromSql<Jsonb, Pg> for Body {
    fn from_sql(bytes: Option<&[u8]>) -> deserialize::Result<Self> {
        let value = <serde_json::Value as FromSql<Jsonb, Pg>>::from_sql(bytes)?;
        Ok(serde_json::from_value(value)?)
    }
}

impl ToSql<Jsonb, Pg> for Body {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
        let value = serde_json::to_value(self)?;
        <serde_json::Value as ToSql<Jsonb, Pg>>::to_sql(out)
    }
}
```

Also note that this custom derive from that third party crate does use an internal api and may break at any time (cc @terry90)

The error message if the implementation above is missing is not great, but there is not much diesel could do here, because those errors are generated by rustc and we have no way to tell rustc point to this or that.

I closing this issue because I see nothing actionable for diesel here.

**Comment by weiznich** [comment]
It's always possible to do this as macro or third party derive if you think that's to much boilerplate code.

**Comment by z0mbie42** [comment]
Thank you for the explanation and the example, I'll try to implement this macro.

**Comment by weiznich** [comment]
A simple macro doing this should just be
```rust

macro_rules! impl_jsonb_boilerplate {
    ($name: ident) => {
        impl ::diesel::deserialize::FromSql<::diesel::sql_types::Jsonb, ::diesel::sql_types::Pg> for $name {
             fn from_sql(bytes: Option<&[u8]>) -> diesel::deserialize::Result<Self> {
                 let value = <::serde_json::Value as ::diesel::deserialize::FromSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg>>::from_sql(bytes)?;
                 Ok(::serde_json::from_value(value)?)
            }
        }

        impl ::diesel::serialize::ToSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg> for $name {
             fn to_sql<W: ::std::io::Write>(&self, out: &mut ::diesel::serialize::Output<W, Pg>) -> ::diesel::serialize::Result {
                 let value = ::serde_json::to_value(self)?;
                <::serde_json::Value as ::diesel::serialize::ToSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg>>::to_sql(out)
             }
        }
    }
}

impl_jsonb_boilerplate!(Body);
```

**Comment by apiraino** [comment]
I came here looking how to implement a `jsonb` field with Diesel. Me, too, I was puzzled and had to search a bit to get a sense of the many errors (sometimes cryptic) Diesel returns, plus figuring our all the needed imports. This issue was key to understand how to do it, but as of today the code suggested is not valid anymore.

Here's an updated version:
```
use diesel::deserialize::FromSql;
use diesel::pg::Pg;
use diesel::serialize::{Output, ToSql};
use std::io::Write;

impl FromSql<Jsonb, Pg> for Body {
    fn from_sql(bytes: Option<&[u8]>) -> diesel::deserialize::Result<Self> {
        let value = <serde_json::Value as FromSql<Jsonb, Pg>>::from_sql(bytes)?;
        Ok(serde_json::from_value(value)?)
    }
}

impl ToSql<Jsonb, Pg> for Body {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> diesel::serialize::Result {
        let value = serde_json::to_value(self)?;
        <serde_json::Value as ToSql<Jsonb, Pg>>::to_sql(&value, out)
    }
}
```

and the "simple" macro becomes:
```
macro_rules! impl_jsonb_boilerplate {
    ($name: ident) => {
        impl ::diesel::deserialize::FromSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg>
            for $name
        {
            fn from_sql(bytes: Option<&[u8]>) -> diesel::deserialize::Result<Self> {
                let value = <::serde_json::Value as ::diesel::deserialize::FromSql<
                    ::diesel::sql_types::Jsonb,
                    ::diesel::pg::Pg,
                >>::from_sql(bytes)?;
                Ok(::serde_json::from_value(value)?)
            }
        }

        impl ::diesel::serialize::ToSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg> for $name {
            fn to_sql<W: ::std::io::Write>(
                &self,
                out: &mut ::diesel::serialize::Output<W, ::diesel::pg::Pg>,
            ) -> ::diesel::serialize::Result {
                let value = ::serde_json::to_value(self)?;
                <::serde_json::Value as ::diesel::serialize::ToSql<
                    ::diesel::sql_types::Jsonb,
                    ::diesel::pg::Pg,
                >>::to_sql(&value, out)
            }
        }
    };
}

impl_jsonb_boilerplate!(Body);
```

@weiznich This is to say that I understand you folks when you want your API to stay barebone, but for us "end-users" a `jsonb` is just another field we would like to use without figuring out details that steal time from working on the real business logic. Yes, me too, I'm relatively a newbie and it took me some time to figure out how to fix the suggestion above.

If you don't feel that a custom derive is the proper solution, you can figure out a better one. 

Diesel is the best (and "only") ORM in the Rust world, we all love it but I respectfully ask you to reconsider.

**Comment by weiznich** [comment]
@apiraino I do not see any reason the reconsider anything here.
Our policy for supported type conversions remains:
*  Every possible value of the database type must be representable in the rust type and vice versa
* It must be a commonly used type

The first point is not fullfilled for this conversation.

 If this really is an issue for real world code it is easily possible to publish a third party crate doing this.

(Also: What's the difference between your code and the macro I've posted above? On the first glance I could not spot anything different...)

**Comment by apiraino** [comment]
Ok, I understand your point - thanks for explaining. It works, so in the end that's what matters :-)

About the diff, yes, it's very subtle, here it is (hope I didnt introduce bugs):
```--- a/src/utils.rs
+++ b/src/utils.rs
 macro_rules! impl_jsonb_boilerplate {
     ($name: ident) => {
+        impl ::diesel::deserialize::FromSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg>
-        impl ::diesel::deserialize::FromSql<::diesel::sql_types::Jsonb, ::diesel::sql_types::Pg>
             for $name
         {
             fn from_sql(bytes: Option<&[u8]>) -> diesel::deserialize::Result<Self> {
@@ -53,13 +53,13 @@ macro_rules! impl_jsonb_boilerplate {
         impl ::diesel::serialize::ToSql<::diesel::sql_types::Jsonb, ::diesel::pg::Pg> for $name {
             fn to_sql<W: ::std::io::Write>(
                 &self,
+                out: &mut ::diesel::serialize::Output<W, ::diesel::pg::Pg>,
-                out: &mut ::diesel::serialize::Output<W, Pg>,
             ) -> ::diesel::serialize::Result {
                 let value = ::serde_json::to_value(self)?;
                 <::serde_json::Value as ::diesel::serialize::ToSql<
                     ::diesel::sql_types::Jsonb,
                     ::diesel::pg::Pg,
+                >>::to_sql(&value, out)
-                >>::to_sql(out)
             }
         }
     };
```

**Comment by z0mbie42** [comment]
It may work, but as we can see from @apiraino's patch, maintaining a 3rd party crate which may break across diesel's version is not good.

@weiznich What are examples of  value that cannot be expressed in Rust can be in JSOB, or vice versa?


I still think that adding this in Diesel would greatly improve developer experience and thus could help Rust's adoption which by the virtuous circle of open source, will improve Rust libraries quality.

**Comment by weiznich** [comment]
To be clear my code snipped above never worked because of typos and copy paste errors. All API's used to implement this are part of our stable API. Any change breaking this implementation would either be considered a breaking change resulting in major version bump or is a bug and should be fixed as soon as reported.

@z0mbie42 For the general mapping there is `Jsonb` <-> `serde_json::Value`. That works for every value. Now just assume diesel provides a mechanism to convert arbitrary rust structs `Jsonb` fields. Now what happens if you store a `User` and try to load a `Post` from the same `Jsonb` field. This will result in a run time error (and is against the first point of our type policy). Therefore no such feature will be provided by diesel itself.

**Comment by terry90** [comment]
@weiznich What about thinking about something to restrict this behavior ? Like adding a field containing the type (e.g "_diesel_type": "xxx::User") or something else.

**Comment by weiznich** [comment]
I do not see how this would help, now you only could detect that the conversion would fail.

**Comment by clouds56** [comment]
Now the signature of `ToSql` changed, how to achieve this in 2.0?
```rust
impl<DB: Backend> FromSql<Jsonb, DB> for ItemContent
  where serde_json::Value: FromSql<Jsonb, DB> {
  fn from_sql(bytes: diesel::backend::RawValue<DB>) -> diesel::deserialize::Result<Self> {
    serde_json::from_value(serde_json::Value::from_sql(bytes)?).map_err(|e| e.into())
  }
}
impl<DB: Backend> ToSql<Jsonb, DB> for ItemContent
  where serde_json::Value: ToSql<Jsonb, DB> {
  fn to_sql<'b>(&'b self, out: &mut diesel::serialize::Output<'b, '_, DB>) -> diesel::serialize::Result {
    let value = serde_json::to_value(self)?;
    value.to_sql(out) // error[E0597]: `value` does not live long enough
  }
}
```

**Comment by weiznich** [comment]
@clouds56 Checkout [this part of the migration guide](https://github.com/diesel-rs/diesel/blob/master/guide_drafts/migration_guide.md#2-0-0-to-sql) for potential solutions. Otherwise please don't comment on old closed issues with semi-releated stuff. Either open a new discussion thread for this or use the existing diesel 2.0. migration discussion

**Comment by dima74** [comment]
Working version for **diesel V2**:

```rust
use diesel::deserialize::FromSql;
use diesel::pg::{Pg, PgValue};
use diesel::serialize::{Output, ToSql};
use diesel::sql_types::Jsonb;
use diesel::{AsExpression, FromSqlRow};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, FromSqlRow, AsExpression)]
#[diesel(sql_type = Jsonb)]
pub struct Body {
    pub text1: String,
    pub text2: String,
}

impl FromSql<Jsonb, Pg> for Body {
    fn from_sql(bytes: PgValue<'_>) -> diesel::deserialize::Result<Self> {
        let value = <serde_json::Value as FromSql<Jsonb, Pg>>::from_sql(bytes)?;
        Ok(serde_json::from_value(value)?)
    }
}

impl ToSql<Jsonb, Pg> for Body {
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, Pg>) -> diesel::serialize::Result {
        let value = serde_json::to_value(self)?;
        <serde_json::Value as ToSql<Jsonb, Pg>>::to_sql(&value, &mut out.reborrow())
    }
}
```
