### ISSUE TITLE
Provide a connection pool that implements Connection traits

### ISSUE THREAD

**Issue by mehcode** [diesel-rs/diesel#1958]
Direct usage

```rust
let client = diesel::Client::<SqliteConnection>::open("sqlite://some_file.db")?;

// will checkout a connection from the pool, perform the query, and return the connection
let results = users::table.load(&client)?;
```

Get a connection directly

```rust
let client = diesel::Client::<SqliteConnection>::open("sqlite://some_file.db")?;
let connection = client.establish()?; // or .get
```

Client would have a builder API for customizing the pool

```rust
let client = diesel::Client::<SqliteConnection>::builder()
  .max_open_connections(15) // or .max_size
  .build("sqlite://some_file.db")?;
```

At first we will just wrap `r2d2`, without exposing it in the API of `diesel::Client`. I would like to explore alternative connection pools and connection pool design however as we discuss async/await as asynchronously checking out a connecting is important. Perhaps expanding on the experiment in https://github.com/khuey/bb8 ?

**Comment by zimmi** [comment]
This also allows for a `transaction`method that only checks a connection out of the pool if the callback given to it interacts with the database. If that's not the case, the overhead of the `transaction` method is essentially zero. That's useful for abstraction layers that provide unit of work semantics: Imagine a web framework that wants to guarantee transaction-per-request but doesn't know in advance if the transaction / database connection is needed at all.

**Comment by weiznich** [comment]
@zimmi That won't work this way because starting a transaction requires doing a call to the database. Once the control flow has entered the user provided closure there is no way to achieve that, therefore that needs to be done before calling the closure. There is no way to check if a given closure will interact with the database or not.

**Comment by weiznich** [comment]
That's not planed to be implemented in diesel itself. Such a connection pool could and should be implemented as third party crate.
