### ISSUE TITLE
how to connect to Oracle database ?

### ISSUE THREAD

**Issue by magj2006** [diesel-rs/diesel#1965]
### Versions

- **Rust:**1.32
- **Diesel:**1.40
- **Database:** Oracle
- **Operating System** Linux

### Feature Flags

- **diesel:** oracle

## Problem Description
there was an error that with features: `oracle` but `diesel` does not have these features when I use feature oracle, so how to connect to Oracle database ?

## Checklist

- [# ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [# ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Oracle is no supported back end therefore it is not possible to connect to a oracle database using diesel. Also we do not have any plans to add support for this to diesel.
That said there is [diesel-oci](https://github.com/GiGainfosystems/diesel-oci) that implements such an back end outside of diesel. It does work but is not finished yet. Also it requires a nightly compiler and a patched diesel version. What is planed is to upstream those changes. 

Closed as Won't fix.

**Comment by magj2006** [comment]
> 
> 
> Oracle is no supported back end therefore it is not possible to connect to a oracle database using diesel. Also we do not have any plans to add support for this to diesel.
> That said there is [diesel-oci](https://github.com/GiGainfosystems/diesel-oci) that implements such an back end outside of diesel. It does work but is not finished yet. Also it requires a nightly compiler and a patched diesel version. What is planed is to upstream those changes.
> 
> Closed as Won't fix.

I got it, Thank you!!!

**Comment by PhilippMDoerner** [comment]
@weiznich I entirely respect your decision to not support Oracle here and I do not require it for any of my own usecases (I use sqlite for my own hobbyprojects mostly). Your statement just made me curious as to what lead to the decision. I have no idea about what considerations go into this (other than maybe popularity of the given db, which I'd assume Oracle's is somewhat sizeable (?)), so I'm curious how support for a given database type is/was decided.

**Comment by weiznich** [comment]
@PhilippMDoerner The main argument for this decision is that sqlite, mysql and postgresql are freely available for any contributor. That's not the case for the oracles database system. Additionally adding features requires that someone maintains that work. As diesel has already not that much maintainers adding new features is something that needs good reasons. On top of that is diesel designed in such a way that it is possible implement support for another database as third party crate, so that someone that really needs this support can provide a corresponding implementation.

**Comment by PhilippMDoerner** [comment]
@weiznich Thank you very much for taking the time! Makes a lot of sense to me
