### ISSUE TITLE
Two broken links in diesel::associations doc

### ISSUE THREAD

**Issue by Darksonn** [diesel-rs/diesel#1969]
On the documentation page for [diesel::associations][1] a few links aren't rendered as links.

The two paragraphs below each contains a non-rendered link.

>Next lets look at how to load the children for more than one parent record. [belonging_to][belonging-to] can be used to load the data, but we'll also need to group it with its parents. For this we use an additional method grouped_by

> [grouped_by] is called on a Vec<Child> with a &[Parent]. The return value will be Vec<Vec<Child>> indexed to match their parent. Or to put it another way, the returned data can be passed to zip, and it will be combined with its parent.

  [1]: https://docs.diesel.rs/diesel/associations/index.html

**Comment by weiznich** [comment]
Thanks for reporting them :+1:
Would you mind opening a PR fixing them?
