### ISSUE TITLE
diesel migration run|pending|etc panics if connection fails (instead of outputing a formatted user friendly message)

### ISSUE THREAD

**Issue by hbobenicio** [diesel-rs/diesel#1980]
### Versions

- **Rust:** rustc 1.32.0
- **Diesel:** diesel 1.4.0
- **Database:** postgresql 11.1 (but irrelevant for this issue)
- **Operating System:** Linux Ubuntu 18.04 LTS (bionic)

### Feature Flags

- **diesel:** diesel-cli (diesel migration command)

## Problem Description

`diesel migration pending|run|etc...` panics if database is down (connection refused).

### What are you trying to accomplish?

run `diesel migration` commands

### What is the expected output?

A better user friendlier formatted output from the CLI. Panicking is just odd, because it's an error with good typed context to output.

### What is the actual output?

```
$ diesel migration pending
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionError(BadConnection("could not connectto server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n"))', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### Are you seeing any additional errors?

Maybe more CLI commands suffer from the same issue? (I just tested with `diesel migration` though)

### Steps to reproduce

1. set `DATABASEURL=...` on `.env` to a valid URL that points to some random host/port/db which doen't have a db server listening to.
2. run `diesel migration pending` or `diesel migration run`.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by mikeumus** [comment]
I'm facing this issue now too.

**Comment by weiznich** [comment]
@mikeumus Please always include information in such comments. As currently written your comment is not helpful as it does not contain any information about which diesel version you are using, which command causes which error message and so on.
