### ISSUE TITLE
cli schema generation insert Nullable with sqlite INTEGER PRIMARY KEY

### ISSUE THREAD

**Issue by paullgdc** [diesel-rs/diesel#1984]
### Versions

- **Rust:** 1.32
- **Diesel:** 1.4.0
- **Database:** sqlite
- **Operating System** linux (ubuntu 16.04)

### Feature Flags

- **diesel:** ["sqlite"]

## Problem Description
When running `diesel migration run` with a migration creating a table on an sqlite database, with a field tagged as `INTEGER PRIMARY KEY`, diesel-cli creates a field `id -> Nullable<Integer>` which is wrong because the primary key can't be `NULL`

### Steps to reproduce

create a new project
```bash
cargo init
diesel migration generate create_table
DATABASE_URL=new.sqlite3 diesel migration run
```
with this migration 
```SQL
CREATE TABLE data (
    id INTEGER PRIMARY KEY
);
```

creates this schema.rs
```rust
table! {
    data (id) {
        id -> Nullable<Integer>,
    }
}
```

## Checklist

-  [x]  I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by paullgdc** [comment]
Also according to sqlite documentation
"Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. " https://www.sqlite.org/syntax/table-constraint.html
So in the the case of non `INTEGER` primary key, it is right to make the column Nullable

**Comment by sgrif** [comment]
We ask SQLite for this information, and SQLite is telling us that the column is nullable. I agree that it's going to auto increment the rowid even if you didn't ask it to do so when you try to give it null, but I'm not sure we want to special case this when SQLite is clearly retaining this information.

```
sqlite> drop table data;
sqlite> create table data (id integer primary key);
sqlite> pragma table_info('data');
0|id|integer|0||1
sqlite> drop table data;
sqlite> create table data (id integer primary key not null);
sqlite> pragma table_info('data');
0|id|integer|1||1
```

**Comment by paullgdc** [comment]
Ok then, I'll just add `NOT NULL` to the field. It seems to do the trick.
