### ISSUE TITLE
Find a replacement for the deprecated `HasSqlType::row_metadata` function for use in third party backends

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#1985]
### Versions

- **Diesel:** 2.0

## Problem Description

Diesel 2.0 will remove `HasSqlType::row_metadata()` because it was deprecated and should not be used any more.  Unfortunately implementing a function like this is required to implement a third party backend that adds support for oracle databases. In detail such a backend implementation requires (One need to tell oci what types are coming back…) that there is some way to get a list of response sql types that could be [iterated at runtime](https://github.com/GiGainfosystems/diesel-oci/blob/re_rebalance_coherence/src/oracle/connection/stmt.rs#L177). (Basically just that what `HasSqlType::row_metadata()` has done before.)

Without any deeper investigation I see 2 solutions for this problem:
(Just a unordered mind dump…)

* Add something like `HasSqlType::row_metadata()` back to diesel. Probably just as new trait implemented for all supported tuple sizes?
* Specify that such a backend would be responsible on their own to implement such a trait proposed in the first variant. That would imply that they need to implement trait for tuples up to the same size that diesel implements it's own traits. A way to simplify that would to make the internal `__diesel_for_each_tuple!` macro part of the public api. That would easily allow custom backends (and other crates) to integrate with diesel implement some trait for all tuples up to a certain length approach.

After writing this up I have the feeling that the second solution may be slightly more fitting because that would allow other things than this specific use case. The downside of such an approach would be that we commit to implementing our traits for tuples with a fixed number of elements. That will hold true as long as we do not move to another internal representation (hlists for example) or rust gains the ability to use variadic generics. (Both events would justify a major release therefore exposing that macro should be fine) 

cc @pgab

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
Making `__diesel_for_each_tuple!` public API seems reasonable to me

**Comment by sgrif** [comment]
(Probably not exactly as it is right now)

**Comment by weiznich** [comment]
So I've tried to implement that with the existing `__diesel_for_each_tuple!` in diesel-oci. Basically it's not possible to do that because we cannot change the trait bounds [here](https://github.com/GiGainfosystems/diesel-oci/blob/re_rebalance_coherence/src/oracle/connection/mod.rs#L132) 😞
