### ISSUE TITLE
error: linking with `link.exe` failed: exit code: 1181

### ISSUE THREAD

**Issue by JordiOfRivia** [diesel-rs/diesel#2003]
Hey, all
I'm following the getting started guide from diesel.
when i run the command 
 cargo install diesel_cli --no-default-features --features postgres

i get the following error code in the console 
error: linking with `link.exe` failed: exit code: 1181 

Does somebody has a solution for my problem?

**Comment by weiznich** [comment]
That sounds like your linker is missing libpq as native library somewhere. See our [CI setup](https://github.com/diesel-rs/diesel/blob/master/azure-pipelines.yml#L142) for a working example.

I close this issue because this is nothing actionable for the diesel team.
