### ISSUE TITLE
Emitted schema could use comments from database

### ISSUE THREAD

**Issue by eropple** [diesel-rs/diesel#2005]
So I'm new to Diesel, and I apologize if this has already been suggested, but I couldn't find it after some searching. :)

One of the things about Diesel that I really like--as somebody who is generally suspicious of generated code--is how clear and straightforward the generated `schema.rs` file is. However, there's one thing that's bugging me: any comments in the database are ignored. Comments are not in the SQL standard, but both Postgres and MySQL support some flavor of them (and Postgres's can be [deep](https://www.postgresql.org/docs/9.1/sql-comment.html)!). Historically I've always been a big fan of their use, but I'm also the sort of developer who always has a Postgres console open anyway. It'd be handy purely as reference, and might encourage a little bit more clarity, to surface these somehow in `schema.rs`. I can see a couple ways this could be useful right off the top of my head:

- tagging tables and columns for display in documentation tools (both Postgres and MySQL, at least, support column and table comments)
- surfacing comments on constraints/unique indexes (Postgres supports these) when handling a constraint violation error

Obviously this is not a super-high priority item (and I might give it a try myself as I get more comfortable with Rust, I am a novice at this) but given the way Diesel seems happy to get comfortable with Postgres features--and others I'm sure, but I'm a Postgres user by default--this could be a handy way to help treat the database as the arbiter of truth and better sync up one's data layer with one's schema.

Anyway, Diesel seems awesome so far. Thanks!

**Comment by weiznich** [comment]
Thats implemented in https://github.com/diesel-rs/diesel/pull/3281
