### ISSUE TITLE
Suggestion: Change `like` default on PostgreSQL

### ISSUE THREAD

**Issue by asonix** [diesel-rs/diesel#2006]
## Problem Description
As noted in the [docs for `like` and `not_like`](https://docs.rs/diesel/1.4.1/diesel/expression_methods/trait.TextExpressionMethods.html#method.like), MySQL and SQLite use case insensitive queries, while PostgreSQL defaults to case-sensitive queries. It might make more sense to default `like` and `not_like` to produce `ILIKE` queries for PostgreSQL, and provide another postgres-specific query for case-sensitive likeness. This could help applications using diesel to be generic across databases.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Diesel does not try to hide differences between databases, therefore the `like` functions behave like the underlying implementation behaves. For postgresql there is also an [`ilike` function](http://docs.diesel.rs/diesel/expression_methods/trait.PgTextExpressionMethods.html#method.ilike) exposed. The basic reason for that is that we don't try to hide the underlying sql. A user should be able to see which sql is generated by just looking at the dsl written query (at least whenever possible).

I don't think we will chance that policy anytime soon therefore I close this issue.  For applications generic across different databases it is possible to abstract over that using some custom trait. That is also possible as third party crate, so maybe just publish it if you think there is some value for others there?
