### ISSUE TITLE
Converting snake_case to CamelCase

### ISSUE THREAD

**Issue by NicholasLYang** [diesel-rs/diesel#2012]
### Versions

- **Rust:** rustc 1.33.0-nightly (b43986184 2019-01-11)
- **Diesel:** 1.4.1
- **Database:** PostgreSQL 10.4
- **Operating System** macOS 10.14

### Feature Flags

- **diesel:** postgres

## Problem Description
snake_case types in Diesel get converted to an unusual `Capitalized_snake_case`

### What are you trying to accomplish?
I'm trying to add a postgres enum to my schema. I'm defining the type name as `action_type`, but when it gets added to the schema it's converted to `Action_type`. IF I try using CamelCase in the SQL it gets converted to Actiontype (no surprise since case is generally ignored in SQL)

### What is the expected output?
`ActionType`

### What is the actual output?
`Action_type`

### Are you seeing any additional errors?
Nope

### Steps to reproduce
Here's the migration that generates the types and corresponding tables:
```
CREATE TABLE roles (
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);

CREATE TYPE ActionType AS ENUM ('create', 'read', 'update', 'delete');
CREATE TYPE ActionModifier AS ENUM ('all', 'self');

CREATE TABLE permissions (
id SERIAL PRIMARY KEY,
role_id INTEGER REFERENCES roles(id) NOT NULL,
resource_name VARCHAR,
action ActionType,
modifier ActionModifier
);

CREATE TABLE user_roles (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) NOT NULL,
role_id INTEGER REFERENCES roles(id) NOT NULL
);
```

Or just check [this](https://github.com/NicholasLYang/diesel-camel-case) out (you'll need to add an .env file with the DATABASE_URL).
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by mocsy** [comment]
Last I checked enums weren't supported by diesel.
Here is what I'd use instead:
action TEXT NOT NULL CHECK(action IN ('create', 'read', 'update', 'delete')),

I haven't seen this Camel_casing issue yet.

**Comment by NicholasLYang** [comment]
They actually are! I'm using [diesel-derive-enum](https://github.com/adwhit/diesel-derive-enum). It's fairly decent except I need to add an `import_types` and then suppress the unused import warnings in `schema.rs`.
