### ISSUE TITLE
diesel_cli does nothing when run windows 10

### ISSUE THREAD

**Issue by akrantz01** [diesel-rs/diesel#2015]
### Versions

- **Rust:** 1.33.0
- **Diesel:** 1.4.0
- **Database:** PostgreSQL 11
- **Operating System:** Windows 10 Build 1809

### Feature Flags

- **diesel:**

## Problem Description
Whenever I try to run `diesel.exe` with any subcommand or flag, it returns with no output.
```
PS C:\Users\alex> diesel.exe
PS C:\Users\alex>
```
I have already looked at #487 and #843, but to no avail.

### What are you trying to accomplish?
I am trying to get the diesel cli installed and running for a project.

### What is the expected output?
I expect there to be any output at all.

### What is the actual output?
Nothing
```
PS C:\Users\alex> diesel.exe
PS C:\Users\alex>
```

### Are you seeing any additional errors?
No

### Steps to reproduce
1. `$env:PQ_LIB_DIR = "C:\Program Files\PostgreSQL\11\lib"`
2. `$env:SQLITE3_LIB_DIR = "C:\Program Files\SQLite3"`
3. Add `C:\Program Files\PostgreSQL\11\lib` and `C:\Program Files\SQLite3` to `PATH`
3. `cargo install diesel_cli --no-default-features --features postgres,sqlite`
4. `diesel.exe --help`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
What's the exit code you're getting?

**Comment by akrantz01** [comment]
I'm not sure, how do I check?

**Comment by sgrif** [comment]
That would depend on what shell you're using. Google "{your shell} get exit code"

**Comment by akrantz01** [comment]
I got -107374151. It doesn't seem right, but it stayed consistent through multiple runs from `echo $LASTEXITCODE`

**Comment by sgrif** [comment]
That is `0xC0000135` in hex, which is a missing DLL. You should have received a popup window telling you what's missing.

**Comment by akrantz01** [comment]
I didn't get it from PowerShell, but when I ran it in command prompt, I got the error message:
> The code execution cannot proceed because SSLEAY32.dll was not found. Reinstalling the program may fix this problem.

**Comment by akrantz01** [comment]
Fixed it. I found that `SSLEAY32.dll` is from OpenSSL and did not have it installed. For those looking, you can down load the dlls from [https://indy.fulgan.com/SSL/](https://indy.fulgan.com/SSL/)

**Comment by fclinux** [comment]
> Fixed it. I found that `SSLEAY32.dll` is from OpenSSL and did not have it installed. For those looking, you can down load the dlls from https://indy.fulgan.com/SSL/

unluckily the Diesel setup has the same issue and it do not run anymore. I tried to use cmd and that is so bad.

**Comment by rikkigouda** [comment]
> That is `0xC0000135` in hex, which is a missing DLL. You should have received a popup window telling you what's missing.

How did you know this code means a missing DLL? Is there a reference for these codes?

**Comment by Magicloud** [comment]
@fclinux @rikkigouda The reason you got here, might be because of the crappy Windows Terminal, which loses the executable loader error. I used the Git Bash (comes with git, I think) to see the DLL missing errors.
