### ISSUE TITLE
Database error on custom SQL type for not implemented PostgreSQL type EAN13

### ISSUE THREAD

**Issue by ackxolotl** [diesel-rs/diesel#2016]
I'm trying to use the `EAN13` data type for barcodes from the `isn` module of PostgreSQL as described [here](https://www.postgresql.org/docs/current/isn.html). Since diesel has no built-in support for `EAN13` (yet), I've tried to implement my own SQL type. Unfortunately I'm stuck with a database error:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "no binary output function available for type ean13")', src/libcore/result.rs:997:5```

The SQL code for my table is quite simple:

```sql
CREATE TABLE users
(
  id      SERIAL PRIMARY KEY,
  name    TEXT  NOT NULL UNIQUE,
  barcode EAN13 NOT NULL,
  balance MONEY NOT NULL DEFAULT 0
);
```

And this is my model (without any actual implementation for the traits yet):

```rust
use diesel::deserialize::{self, FromSql};
use diesel::pg::Pg;
use diesel::serialize::{self, IsNull, Output, ToSql};
use diesel::sql_types::BigInt;
use diesel::*;
use std::io::Write;

table! {
    users (id) {
        id -> Int4,
        name -> Text,
        barcode -> Int8,
        balance -> Money,
    }
}

#[derive(SqlType, Debug, PartialEq, FromSqlRow, AsExpression)]
#[postgres(type_name = "ean13")]
pub struct Ean13(pub i64);

impl ToSql<BigInt, Pg> for Ean13 {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
        Ok(IsNull::No)
    }
}

impl FromSql<BigInt, Pg> for Ean13 {
    fn from_sql(bytes: Option<&[u8]>) -> deserialize::Result<Self> {
        Ok(Ean13(8))
    }
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub barcode: Ean13,
    pub balance: diesel::data_types::PgMoney,
}
```

Am I doing something wrong here? Or is this a bug?

**Comment by weiznich** [comment]
I think the issue here is that you tell diesel to treat the barcode field as `Int8`/`BigInt`. 

Try something like the following:

```rust
#[derive(SqlType)]
#[postgres(type_name = "ean13")]
pub struct Ean13;

table! {
    use diesel::sql_types::*;
    use super::Ean13;

    users (id) {
        id -> Int4,
        name -> Text,
        barcode -> Ean13,
        balance -> Money,
    }
}

#[derive(Debug, PartialEq, FromSqlRow, AsExpression)]
#[sql_type = "Ean13"]
pub struct Ean13Wrapper(pub i64);

impl ToSql<Ean13, Pg> for Ean13Wrapper {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Pg>) -> serialize::Result {
        Ok(IsNull::No)
    }
}

impl FromSql<Ean13, Pg> for Ean13Wrapper {
    fn from_sql(bytes: Option<&[u8]>) -> deserialize::Result<Self> {
        Ok(Ean13(8))
    }
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub barcode: Ean13Wrapper,
    pub balance: diesel::data_types::PgMoney,
}
```

**Comment by ackxolotl** [comment]
Thanks for your response. I've changed the types and the code compiles. Unfortunately, the runtime error hasn't changed a bit:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "no binary output function available for type ean13")', src/libcore/result.rs:997:5```

Any other ideas? I mean I should at least be able to get a user by its name, right? I'm not even "touching" the barcode field yet :-/

**Comment by sgrif** [comment]
That error looks like there's no binary protocol support for that type. Unfortunately, Diesel only transmits data using binary transmission, so there's not much that can be done here

**Comment by ackxolotl** [comment]
Ok, so this is indeed caused by the database and one would have to implement these binary input/output functions in PostgreSQL. Or would it be feasible to transmit the data from/to Diesel in another way?

**Comment by sgrif** [comment]
There'd need to be binary input/output functions on the PG side

**Comment by ackxolotl** [comment]
Yeah, I see. That's what I said, didn't I? Guess you can close the issue then. Thanks ;)

**Comment by sgrif** [comment]
Sorry, I was trying to clarify that part of what you said is correct, and not

> Or would it be feasible to transmit the data from/to Diesel in another way?
