### ISSUE TITLE
Runtime error: error while loading shared libraries: libpq.so.5

### ISSUE THREAD

**Issue by msfragala** [diesel-rs/diesel#2030]
### Versions

- **Rust:** 1.33.0 (stable)
- **Diesel:** 1.4.2
- **Database:** PostgreSQL
- **Operating System**: Amazon Linux AMI 2017.03

### Feature Flags

- **diesel:** postgres, chrono, serde_json

## Problem Description
Keep seeing this runtime error:

```
/var/task/bootstrap: error while loading shared libraries: libpq.so.5:
cannot open shared object file: No such file or directory
```

To the best of my knowledge, my [build script](https://github.com/msfragala/diesel-issue-demo/blob/master/build.sh) installs PostgreSQL correctly

### What are you trying to accomplish?
I'm trying to use Diesel in an AWS Lambda, using [Now](https://zeit.co/now) to handle the infrastructure (it uses Amazon Linux AMI 2017.03 and runs a user-defined build script for setup). _I'm just including these details for full context; I don't think Now's platform is contributing to the issue._

### Steps to reproduce
I have a [repository here](https://github.com/msfragala/diesel-issue-demo) that includes my code and schema (not that I think they're the problem), as well as the build script that installs PostgreSQL in my Lambda function

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by paulocsanz** [comment]
`sudo yum install postgresql-devel`?

**Comment by msfragala** [comment]
Tried using sudo, to no avail. I've also verified that:
- `libpq.so.5`  is located in `/usr/lib64`
- `LD_LIBRARY_PATH` includes `/usr/lib64`
- `PQ_LIB_DIR` includes `/usr/lib64`

**Comment by msfragala** [comment]
This seems to be a limitation of my lambda deployment service (shared libraries not available at runtime), so closing this ticket
