### ISSUE TITLE
Feature request: AsChangeset batch update

### ISSUE THREAD

**Issue by torepettersen** [diesel-rs/diesel#2032]
I want to do a batch update of multiple items in the same table. But I don't see a way to do that in a single query. Currently, I am doing that with multiple queries:

```rust
conn.transaction(|| {
  items.iter()
    .map(|item| {
      diesel::update(posts::table)
        .set(item)
        .get_result::<Post>(&conn)
    })
    .collect()
})
```

Would that be possible to do with a single query like this, assuming items is a vector of a struct that implemts AsChangeset and Identifiable:

```rust
#[derive(AsChangeset, Identifiable)]
#[table_name="posts"]
struct UpdatePost<'a> {
  id: i32,
  title: &'a str,
}

let items = vec![
  UpdatePost { "id": 1, "title": "Title" },
  UpdatePost { "id": 2, "title": "Title" },
]

diesel::update(posts::table)
  .set(items)
  .get_results::<Post>(&conn)
```

**Comment by sgrif** [comment]
There's no way in SQL to do this in a single query. Also note that your current code updates *the entire table* multiple times. I'd recommend reading http://diesel.rs/guides/all-about-updates/

**Comment by toreskogp** [comment]
Thanks for pointing out my mistake, I was under that impression that the id was automatically filtered if the Identifiable derive was added.

Is there then any way to build up the queries and send them simultaneously to the DB, to avoid doing a separate call for each item?
I have also had a look at batch_execute, but if I can understand the documentation correctly, that seems to only support raw queries?

**Comment by weiznich** [comment]
Closed as the original idea does not really work due to limitations in SQL. If someone comes up with a better solution please open a feature request post in our discussion forum.
