### ISSUE TITLE
Feature request: jsonb merge operator for postgres

### ISSUE THREAD

**Issue by lutter** [diesel-rs/diesel#2036]
Postgres supports merging two jsonb objects with the `||` operator. I recently needed that and implemented it [here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/jsonb.rs) but haven't been able to turn this into a proper PR.

If it's easy to integrate in its current form, I'd love to see that. If not, I am perfectly fine with "please make a PR" as a response to this issue.

Either way, I also need Postgres key deletion operator (`data::jsonb - key::text`) but haven't been able to work out the types for that one. Anything that you could do to include that in Diesel would be hugely appreciated!

**Comment by weiznich** [comment]
I think it would be fine to have that in diesel itself, but I don't see anyone from the contributor team implementing this anytime soon.
That said: The linked implementation is basically all that is required on implementation side. To upstream that in diesel the following minor parts are missing:
* Add some documentation
* Add a test case
* Add a compile-fail test to verify that this only compiles using the postgres backend

So if someone is interested, just open a PR :wink:

**Comment by weiznich** [comment]
Also there is #44 which is related to this.

**Comment by weiznich** [comment]
Implemented by https://github.com/diesel-rs/diesel/pull/3035
