### ISSUE TITLE
Replace `http` with `https` in some files

### ISSUE THREAD

**Issue by JohnTitor** [diesel-rs/diesel#2040]
## Summary

We use domain `diesel.rs` and can visit not just `http://diesel.rs` but also `https://diesel.rs`. This is not important change, but we might have to unify these url in some files (e.g. `Cargo.toml`), perhaps `https`?

(And we can replace url in repository's website line.)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by TomPridham** [comment]
looks like this can be closed?
