### ISSUE TITLE
diesel print-schema output disagrees with rustfmt

### ISSUE THREAD

**Issue by jshholland** [diesel-rs/diesel#2048]
### Versions
- **Diesel:**
```
$ diesel --version # from `cargo install diesel_cli`
diesel 1.4.0
```
### Steps to reproduce

```
$ cargo new test && cd test
$ diesel setup
$ diesel migration generate test
$ cat > migrations/*_test/up.sql <<EOF
CREATE TABLE foos ( id SERIAL PRIMARY KEY );
CREATE TABLE bars ( id SERIAL PRIMARY KEY, foo_id INTEGER NOT NULL REFERENCES foos );
EOF
$ diesel migration run
$ cat src/schema.rs
$ cat src/schema.rs 
table! {
    bars (id) {
        id -> Int4,
        foo_id -> Int4,
    }
}

table! {
    foos (id) {
        id -> Int4,
    }
}

joinable!(bars -> foos (foo_id));

allow_tables_to_appear_in_same_query!(
    bars,
    foos,
);
$ echo "pub mod schema;" > src/lib.rs
$ cargo fmt
$ cat src/schema.rs
table! {
    bars (id) {
        id -> Int4,
        foo_id -> Int4,
    }
}

table! {
    foos (id) {
        id -> Int4,
    }
}

joinable!(bars -> foos (foo_id));

allow_tables_to_appear_in_same_query!(bars, foos,);
```
Ideally the content of `schema.rs` would already be in a format acceptable to rustfmt, so that I don't end up generating a bunch of VCS file modified noise every time one of them changes the output of the other.

**Comment by weiznich** [comment]
I'm not sure if it's even possible to fix that, because this marco will be split into several lines as soon as you add more tables. The exact point where this split happens depends on table name length, table name count and rustfmt settings (max line length)

**Comment by sgrif** [comment]
We could theoretically generate `#![rustfmt(skip)]`, but I'm not sure if it's really worth it since this can be done with `schema.patch` and the overwhelming majority of folks will have enough tables that this doesn't matter (if we ever do really substantially disagree with rustfmt in more substantial cases we probably want to find out about it)

**Comment by jblachly** [comment]
This was addressed in https://github.com/diesel-rs/diesel/pull/2462

(However, the new version of diesel_cli with these changes is not yet available on crates.io)
