### ISSUE TITLE
How to add support for Range<Time> Type

### ISSUE THREAD

**Issue by dnldsht** [diesel-rs/diesel#2055]
### Versions

- **Rust:** 1.18.1 nightly
- **Diesel:** 1.4.2
- **Database:** postgresql
- **Operating System** linux

### Feature Flags

- **diesel:** ["postgres", "chrono"]

## Problem Description
I dont know how to extend diesel to support a time range. 

I have created this type in sql
```sql
CREATE FUNCTION time_mi(time1 time, time2 time) RETURNS float AS $$
    SELECT EXTRACT(epoch FROM time1-time2)/3600; 
$$ LANGUAGE sql immutable;

CREATE TYPE timerange AS RANGE (
    subtype = time,
    subtype_diff = time_mi
);
```

In the schema appeared this new type
```rust
table! {
    shift (id) {
        ...
        hours -> Timerange,
    }
}
```
I have tried to declare a new type in rust but it is not reconized
```rust
pub type Timerange = Range<sql_types::Time>;
```

This is the error
```bash
error[E0412]: cannot find type `Timerange` in this scope
 --> src/schema.rs:6:18
  |
6 |         hours -> Timerange,
  |                  ^^^^^^^^^ help: a type alias with a similar name exists: `Daterange`
```

I tried to change `Timerange` in schema.rs to `Range<Time>` but can't implement `HasSqlType<Range<Time>> for Pg`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
Like anywhere else in Rust, you need to import a type with `use` before you can reference it. e.g.

```rust
table! {
    use diesel::sql_types::*;
    use path::to::TimeRange;

    foo {
        id -> Integer,
        time_range -> TimeRange,
    }
}
```

If you're generating your schema file with `diesel_cli`, you can specify this in the `import_types` field. See http://diesel.rs/guides/configuring-diesel-cli/ or `diesel print-schema --help` for more details. If you need additional help, please ask in our gitter room or discourse.
