### ISSUE TITLE
QueryableByName not working with string fields

### ISSUE THREAD

**Issue by mikedilger** [diesel-rs/diesel#2070]
### Versions

- **Rust:** 1.34.2
- **Diesel:** 1.4.2
- **Database:** sqlite3
- **Operating System**  ArchLinux

### Feature Flags

- **diesel:** sqlite

## Problem Description

`QueryableByName` doesn't work for structs that contain strings and which are not annotated with `#[table_name]`.  The compile error indicates that `SqlQuery` doesn't implement `LoadQuery` in that use case.

### What are you trying to accomplish?

I'm trying to run a complex SQL query that returns some custom columns not related to any predefined table, including some strings.  Then I'm trying to execute it with sql_query() and get_result().

I made a crate to demonstrate:  See https://github.com/mikedilger/demoissue

It compiles fine if I take the string field out.

### What is the expected output?

Expected it would compile.

### What is the actual output?

````
  Compiling demoissue v0.1.0 (/tmp/demoissue)
error[E0277]: the trait bound `diesel::query_builder::sql_query::UncheckedBind<diesel::query_builder::SqlQuery, i32, diesel::sql_types::Integer>: diesel::query_dsl::LoadQuery<_, Ages>` is not satisfied
  --> src/main.rs:37:10
   |
37 |         .get_result::<Ages>(conn)
   |          ^^^^^^^^^^ the trait `diesel::query_dsl::LoadQuery<_, Ages>` is not implemented for `diesel::query_builder::sql_query::UncheckedBind<diesel::query_builder::SqlQuery, i32, diesel::sql_types::Integer>`
   |
   = help: the following implementations were found:
             <diesel::query_builder::sql_query::UncheckedBind<Query, Value, ST> as diesel::query_dsl::LoadQuery<Conn, T>>

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `demoissue`.

To learn more, run the command again with --verbose.
````

### Are you seeing any additional errors?

no

### Steps to reproduce

$ git clone https://github.com/mikedilger/demoissue
$ cd demoissue
$ cargo build

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
This issue here is that a sql type is never a rust type like `String`. If you change the SqlType of `somestuff` to `Text` (the same type you used in your `table!` definition) this just works fine.

**Comment by mikedilger** [comment]
Thank you.
