### ISSUE TITLE
How to handle PG XML data type?

### ISSUE THREAD

**Issue by joelparkerhenderson** [diesel-rs/diesel#2072]
I'm a new user, with a typical PostgreSQL database that has a column `foo` with data type `xml`.

How do I have Diesel handle this `xml` data type? For example when Diesel does a migration, I see the `schema.rs` file successfully has the line `foo -> Nullable<Xml>` yet this line fails Rust compilation, saying Xml `not found in this scope`.

Question 1: Am I missing something obvious? I don't understand why Diesel would self-create something that doesn't compile.

Question 2: I have searched the Diesel docs and various help sites, and as far as I can tell, Diesel does not currently provide an Xml data type. How can Diesel add this capability? My understanding from PostgreSQL is that the xml data type is essentially equivalent input/output a text field. For example could Diesel add a new Xml type? And/or just adjust the schema generator so it outputs `foo -> Nullable<Text>`?  
 
Question 3: As a new user, I would like very much to see documentation of if/how/when to work with the `schema.rs` file when there are unsupported types. Is the developer supposed to edit the file manually to adjust for the types? If Diesel updates that file after a migration, then I would expect developer edits to get written over. What's the best way to manage this?

Thanks in advance for help.

**Comment by sgrif** [comment]
> I don't understand why Diesel would self-create something that doesn't compile.

Diesel CLI doesn't know about what types Diesel does or doesn't support, or what third party crates you have that may add support for additional types. The only way to know if it actually compiles is to try compiling it, which isn't something that would make sense for Diesel CLI to do automatically.

>  I have searched the Diesel docs and various help sites, and as far as I can tell, Diesel does not currently provide an Xml data type.

This is correct. 

>  How can Diesel add this capability?

This isn't something we're likely to add to Diesel in the near future, but you can implement this in your own crate (I recommend `diesel-postgres-xml` as a name). We need to write a full guide for this, but take a look at https://github.com/diesel-rs/diesel/blob/bfdddefaa80b732eb656e1ac01c92f10653c904f/diesel_tests/tests/custom_types.rs for a simple example, and https://github.com/lholden/diesel_pg_hstore for an example of a real world crate (note: I have no clue how up to date the code in that crate is)

> My understanding from PostgreSQL is that the xml data type is essentially equivalent input/output a text field.

I don't know what the underlying transmission looks like, but you should probably test this extensively before making this assumption.

> And/or just adjust the schema generator so it outputs foo -> Nullable<Text>?

You can provide a patch file for this. http://diesel.rs/guides/configuring-diesel-cli/#the-patchfile-field

> Is the developer supposed to edit the file manually to adjust for the types? If Diesel updates that file after a migration, then I would expect developer edits to get written over. What's the best way to manage this?

See the guide linked above.

**Comment by joelparkerhenderson** [comment]
Thanks! For other people who may find this useful, here's how I created the patch file, and what it looks like.

```
$ diesel migration redo
$ sed -i.bak 's/<Xml>/<Text>/' schema.rs
$ git diff -U0 > src/schema.patch
$ git add src/schema.patch
$ git commit -am "Add schema patch to revise <Xml> to <Text>"
```

Example patch file that shows one item revised:

```
diff --git a/src/schema.rs b/src/schema.rs
index 92ff4d2..d8b6f8a 100644
--- a/src/schema.rs
+++ b/src/schema.rs
@@ -47 +47 @@ table! {
-        foo -> Nullable<Xml>,
+        foo -> Nullable<Text>,
```
