### ISSUE TITLE
#[belongs_to()] silently ignores additional parameters

### ISSUE THREAD

**Issue by therealpadams** [diesel-rs/diesel#2091]
### Versions

- **Rust:** rustc 1.37.0-nightly (400b409ef 2019-06-09)
- **Diesel:** 1.4.2

## Problem Description

When a model has multiple associations, the developer might intuitively do the following:
- belongs_to(Parent1, Parent2)

...whereas they are supposed to do:

- belongs_to(Parent1)
- belongs_to(Parent2)

When passing multiple parameters to belongs_to the compiler will silently ignore the second association and the code will compile. The problem is not exposed until the developer tries to call belonging_to(Parent2).

### What are you trying to accomplish?

Create a model with two parent associations so I can call belonging_to() for either of those parents.

### What is the expected output?

The compiler should warn about the incorrect syntax for belongs_to() and advise on the proper syntax. From a usability perspective, allowing multiple associations to be passed to belongs_to() would be an intuitive solution.

### What is the actual output?

Nothing. The code will compile silently without error (unless belonging_to(Parent2) is called.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### Thanks

A massive thanks to the maintainers and contributors to Diesel. This is a really great ORM.

**Comment by weiznich** [comment]
That is probably caused by [this code](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/associations.rs#L116). If anyone is willing to look into this just ping me for help/mentoring/…

**Comment by Mcat12** [comment]
@weiznich I looked into this and added the special warning in #2147. Due to the proc macro diagnostics being a nightly feature, the warning is eventually just printed to the console by default. Let me know if there's a better way to do this.

**Comment by sgrif** [comment]
Is there actually nothing emitted? We have tests which say this would have emitted:

> warning: Unrecognized option Parent2

with a span pointing to the problematic code on nightly, and just printing to stdout on stable

**Comment by Mcat12** [comment]
Previously it would emit a warning with "Unrecognized option {}". The change is to emit a more specific message if the option looks like an extra parent.
