### ISSUE TITLE
[diesel_cli] Support redo and revert all applied migrations

### ISSUE THREAD

**Issue by viniciusd** [diesel-rs/diesel#2095]
It would be very helpful if it were possible to run both `diesel migration redo all` and `diesel migration revert all`, those would be very welcome on some CI setups.
For example, on testing both upgrade and downgrade migrations.

As a side enhancement, both redo and revert could support an integer number N of migrations in order to acting on the latest N migrations.

However, my main goal here is supporting an `all` option.

I am not familiar with diesel's code, yet I would be willing to take it as initial contact with both its code base and Rust itself. Some mentoring would be welcomed, but this look likes trivial enough for me to endeavour by myself.

**Comment by weiznich** [comment]
The main entry point for the migration command is in [`diesel_cli`](https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/main.rs#L79).  If you have any specific questions or need help somewhere, just ask here or on our [gitter channel](https://gitter.im/diesel-rs/diesel). Also opening a WIP PR is creating a good place for discussions about implementation related things.

**Comment by viniciusd** [comment]
Is that a green flag? May I proceed with it?

**Comment by weiznich** [comment]
:+1:

**Comment by theredfish** [comment]
I can take this issue if nobody is working on it. I'm interested by these features.
@weiznich / @viniciusd  is it ok?

**Comment by weiznich** [comment]
@theredfish Feel free to work on this feature.

**Comment by viniciusd** [comment]
Go for it @theredfish , I will love to go over it. A lot has happened since then and I couldn't start working at this issue.

**Comment by weiznich** [comment]
Fixed by #2401
