### ISSUE TITLE
diesel does not generate schema when using postgres schema

### ISSUE THREAD

**Issue by prettynatty** [diesel-rs/diesel#2096]
### Versions

- **Rust:** 1.35.0
- **Diesel:** 1.4.2
- **Database:** PostgreSQL 11
- **Operating System** macOS

### Feature Flags

- **diesel:** postgres, chrono

## Problem Description

When I use DATABASE_URL like this: `DATABASE_URL="postgres://user@localhost/mydb" #?options=-c search_path%3Dtest"` both `diesel print-schema` and `diesel migration run` generate empty schema.rs.
When I use default postgres schema (without search_path) it generates normal schema.

**Comment by weiznich** [comment]
We do not parse the database url, we just pass it down to libpq. 
For `diesel print-schema` just use the `-s` flag to specify the schema, for migrations just specify the target schema as part of the migration.

**Comment by 192709** [comment]
Dear Weiznich, your solution wrt. print-schema is clear to me, however, what do you mean with 'just specify the target schema as part of the migration?" I do not get it - can you provide an example?
