### ISSUE TITLE
Making SqliteValue public and soundness question

### ISSUE THREAD

**Issue by udoprog** [diesel-rs/diesel#2098]
Hey,

So I'm currently doing something like the following to reduce the number of copies when reading a custom binary type from sqlite:

```rust
impl FromSql<Binary, Sqlite> for Uuid {
    fn from_sql(input: Option<&<Sqlite as Backend>::RawValue>) -> deserialize::Result<Self> {
        let input = diesel::not_none!(input);
        let input = input.read_blob();
        let mut bytes = uuid::Bytes::default();
        let l = usize::min(bytes.len(), input.len());
        bytes[..l].copy_from_slice(&input[..l]);
        let uuid = Uuid::from_bytes(bytes);
        Ok(uuid)
    }
}
```

I'm not sure this is _fine_. It seems a bit odd that `SqliteValue` freely permits reinterpreting a value using e.g. `read_blob` or `read_integer`. sqlite documentation suggests that these functions are safe to use on incompatible types, but would return some default value in case a conversion is not possible.

Another problem I'm having is that `SqliteValue` is not public, and therefore there's no easily accessible documentation for it. I can obviously still access it through the associated type on the `Sqlite` backend so it would be nice if it was.

Could we make `SqliteValue` public so that it's easier to provide specialized implementations, and would that be sound?

**Comment by weiznich** [comment]
> Another problem I'm having is that SqliteValue is not public, and therefore there's no easily accessible documentation for it. I can obviously still access it through the associated type on the Sqlite backend so it would be nice if it was.

That's by design. Using `<Sqlite as Backend>::RawValue` is the official supported way. Also all functions on that type are considered private. 

The right performance optimal way to implement something like that would be:

```rust
impl FromSql<Binary, Sqlite> for Uuid {
    fn from_sql(input: Option<&<Sqlite as Backend>::RawValue>) -> deserialize::Result<Self> {
        let bytes = <*const [u8] as FromSql<Binary, Sqlite>>::from_sql(input)?;
        let bytes = unsafe {&*bytes};
        assert_eq!(bytes.len(), UUID_BYTE_SIZE);
        let uuid = Uuid::from_slice(bytes);
        Ok(uuid)
    }
}
```

If you don't want that unsafe there, just use `Vec<u8>` instead of the raw pointer.

**Comment by udoprog** [comment]
All right, it's a bit unfortunate we don't have a sound APIs which doesn't require the use of `unsafe`, but I'll take it. Thanks!

**Comment by weiznich** [comment]
There is a sound api, just use `Vec<u8>` instead of the raw pointer. Without explicit copy step we cannot provide a meaning full lifetime for the original buffer of data from the database, therefore this is exposed as raw pointer. (Because it is the responsibility of the user to ensure that this pointer does not leak from the actual `FromSql` implementation)

**Comment by udoprog** [comment]
As stated initially, the goal is to reduce copies. I'm aware that `Vec<u8>` works as well.

I'm reminded of the first part of the issue. Doesn't `SqliteValue`'s public methods pose a soundness hole?

For example, it's possible to create an invalid `&str` using `SqliteValue::read_text` thorough the `RawValue` associated type in safe code.

**Comment by weiznich** [comment]
Yes, therefore that type is hidden and not considered part of the public API.
(And yes, those methods shouldn't be public at all…)

**Comment by udoprog** [comment]
> Yes, therefore that type is hidden and not considered part of the public API.

For `SqliteValue::read_text` it seems a bit trickier. Because of the use of `str::from_utf8_unchecked` it relies on something like the column being of `TEXT` type with an UTF-8 encoding. Since `SqliteValue` is constructed for any column type I don't see how this function alone can be safe. It could be safely used in some other context. But this function should probably still be marked as unsafe to avoid allowing breaking `&str` invariants in safe code.

Compare with `read_blob`. Since it doesn't make any assumptions about encoding, it's safe.

**Comment by udoprog** [comment]
So re-reading the documentation for `sqlite3_column_text`, it does guarantee that the returned data is UTF-8: https://www.sqlite.org/c3ref/column_blob.html

All is well. Thanks!
