### ISSUE TITLE
update libsqlite3-sys

### ISSUE THREAD

**Issue by arve0** [diesel-rs/diesel#2100]
### Versions

- **Rust:** 1.34.2
- **Diesel:** 1.4.2
- **Database:** sqlite
- **Operating System** mac os

### Feature Flags

- **diesel:** sqlite

## Problem Description
I expected diesel to build when having both rusqlite and diesel as dependency.

### What are you trying to accomplish?
Building examples of actix-web with recent rusqlite, when having diesel in same workspace. https://github.com/actix/examples/pull/148

### What is the expected output?
Non failing build

### What is the actual output?
```
error: multiple packages link to native library `sqlite3`, but a native library can be linked only once

package `libsqlite3-sys v0.9.1`
    ... which is depended on by `diesel v1.4.2`
    ... which is depended on by `diesel-rusqlite v0.1.0 (/private/tmp/diesel-rusqlite)`
links to native library `sqlite3`

package `libsqlite3-sys v0.15.0`
    ... which is depended on by `rusqlite v0.19.0`
    ... which is depended on by `diesel-rusqlite v0.1.0 (/private/tmp/diesel-rusqlite)`
also links to native library `sqlite3`
```

### Are you seeing any additional errors?
No.

### Steps to reproduce
```sh
/tmp $ mkdir diesel-rusqlite
/tmp $ cd diesel-rusqlite/
/t/diesel-rusqlite $ cargo init
     Created binary (application) package
/t/diesel-rusqlite (master|…) $ echo 'diesel = { version = "1.4.2", features = ["sqlite"] }' >> Cargo.toml
/t/diesel-rusqlite (master|…) $ echo 'rusqlite = "0.19"' >> Cargo.toml
/t/diesel-rusqlite (master|…) $ cargo build
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by arve0** [comment]
Note that rusqlite 0.19 was released today, but the same holds for 0.18 released april 24.

**Comment by weiznich** [comment]
It would be great if you can open a PR bumping [this](https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L19) version (and also that one in `diesel_cli`).

**Comment by phiresky** [comment]
For some reason, diesel v1.4.3 is still trying to pull a really outdated version of libsqlite3-sys for me:

```
package `libsqlite3-sys v0.9.1`
    ... which is depended on by `diesel v1.4.3`
    ... which is depended on by `migrations_internals v1.4.0`
    ... which is depended on by `diesel_migrations v1.4.0`
    ... which is depended on by `track-pc-usage-rs v0.1.0 (/home/tehdog/data/dev/2020/track-pc-usage-rs)`
links to native library `sqlite3`

package `libsqlite3-sys v0.16.0`
    ... which is depended on by `rusqlite v0.20.0`
    ... which is depended on by `track-pc-usage-rs v0.1.0 (/home/tehdog/data/dev/2020/track-pc-usage-rs)`
```

Which means even the outdated rusqlite v0.20.0 can't be used?

**Comment by weiznich** [comment]
Diesel supports [the following version range: `libsqlite3-sys = { version = ">=0.8.0, <0.17.0", optional = true, features = ["min_sqlite_version_3_7_16"] }`](https://github.com/diesel-rs/diesel/blob/066bc412d7ead423e71de811b1dac9428a63712c/diesel/Cargo.toml#L19). So this seems to be an issue with your setup. Have you tried to run `cargo update`?

**Comment by phiresky** [comment]
I know, that's why I intentionally set my rusqlite dependency to 0.20.0 instead of 0.21.0... I've previously deleted the Cargo.lock file and tried other stuff, but it refused to install a version  0.15.0 of rusqlite.

To be honest, I don't know what happened, but I just ran

`cargo update -p libsqlite3-sys:0.9.1 --precise 0.15.0`

and that fixed it.
