### ISSUE TITLE
Forgetting to add Identifiable to a struct results in a confusing error message

### ISSUE THREAD

**Issue by dcermak** [diesel-rs/diesel#2101]
### Versions

- **Rust:** 1.35.0
- **Diesel:** 1.4.2
- **Database:** sqlite
- **Operating System:** openSUSE Tumbleweed

### Feature Flags

- **diesel:** from `Cargo.toml`: `["sqlite"]`

## Problem Description

I've started using diesel and defined a bunch of structs with associations (https://docs.diesel.rs/diesel/associations/index.html). By my own mistake, I forgot to make one of the structs `Identifiable`:
``` rust
#[derive(Queryable, PartialEq, Debug)]
#[table_name = "accounts"]
pub struct Account {
}
```
In combination with the `#[table_name = "accounts"]` directive, I obtain the following (and imho rather confusing) error message from `cargo build`:
```
error[E0658]: The attribute `table_name` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/db.rs:37:3
   |
37 | #[table_name = "accounts"]
   |   ^^^^^^^^^^
```

I am not sure if this is even possible, but if yes, please consider somehow creating a different error message. I know that the mistake I made is rather foolish and won't happen to anyone used to diesel, but a beginner might find this helpful.

### What are you trying to accomplish?

Experimenting with diesel.rs for an application that I am building.

### What is the expected output?

If possible at all, maybe a more helpful error message like: "struct is not Identifiable, cannot specify table_name"

### What is the actual output?

see above.

### Are you seeing any additional errors?

Yes: 
```
warning: unused import: `accounts`
 --> src/db.rs:3:21
  |
3 | use crate::schema::{accounts, mailboxes, messages};
  |                     ^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default
```
but it didn't really help me identifying the error.

### Steps to reproduce

Create this struct:
```
#[derive(Queryable, PartialEq, Debug)]
#[table_name = "accounts"]
pub struct Account {
}
```
in `src/db.rs` and add `mod schema; mod db;` to `main.rs` or `lib.rs`. Run `cargo build`.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
This error is emitted by rustc itself, therefore we cannot do anything here unfortunately. 

I'm closing this issue because this is nothing actionable for the diesel team.

**Comment by dcermak** [comment]
> This error is emitted by rustc itself, therefore we cannot do anything here unfortunately.
 
I was afraid this would be the case.

Still, thanks for you taking the time!
