### ISSUE TITLE
How can I bind non fixed amount of values to raw sql?

### ISSUE THREAD

**Issue by incker** [diesel-rs/diesel#2103]
Not actually is a bug, but a little annoying to deal with

    let fields = vec![
        "string 1",
        "string 2",
        "string 3",
    ...
    ];

    let mut query = sql_query(&raw_sql);

    for field in fields {
        query = query.bind::<Varchar, _>(field);
    }

The problem is `query.bind()` return different types.
first bind return `UncheckedBind` which differ from `SqlQuery` 
second bind return `UncheckedBind` which differ by type from `UncheckedBind`  from first bind

Not sure how to bind non-fixed amount of values. (`raw_sql` is also generic, but have no problems with that)

Forward thank you!

**Comment by weiznich** [comment]
With diesel 1.4 this is not possible. #1975 Already added a way to do this for the current master branch, so the next release will contain it.

**Comment by incker** [comment]
> With diesel 1.4 this is not possible. #1975 Already added a way to do this for the current master branch, so the next release will contain it.

Thank you, it will be also good if there will be a use example. As any way I do not understand how to use `BoxedSqlQuery` when it'll be next release

**Comment by weiznich** [comment]
PR's to update the documentation are welcome :wink:

**Comment by sgrif** [comment]
Closing as there's no actionable bug here.
