### ISSUE TITLE
`diesel::r2d2::ConnectionManager` and `PgConnection` should be `UnwindSafe`

### ISSUE THREAD

**Issue by rustonaut** [diesel-rs/diesel#2105]
### Versions

- **Rust:** *
- **Diesel:** `1.4.2`
- **Database:** `postgres`  (and others)
- **Operating System** *

### Feature Flags

- **diesel:** `r2d2`

## Problem Description

Using r2d2 pool with `panic::catch_unwind`. _Note that this is not a new feature, r2d2 pool is by design meant to be used across threads, which are like `catch_unwind` but do not have that neet assertion for unwind safety `catch_unwind` has_.  So the pool or anything related to it being unwind unsafe means that there is _already_ a bug for some of the most common diesel use cases: Using it with worker threads, e.g. in a multi threaded web server.

This issue is about impl. of `UnwindSafe` not thinks being unwind safe, if any component is unwind unsafe a issue should be open for that seperately (I think). 

For `Pool` to be unwind safe all parts need to be unwind safe:
- `ConnectionManager`
- `T: Connection`
- `T =PgConnection` =>
   - `StatementCache`
   - `AnsiTransactionManager` (not realy unwind safe leading to following bug: https://github.com/diesel-rs/diesel/issues/2104.)
   - `PgMetadataCache`

### What are you trying to accomplish?

Using `catch_unwind` to handle internal server errors.

### What is the expected output?

Pool should implement `UnwindSafe` (as it needs to be unwind safe anyway for it's normal multi-thread usage).

### What is the actual output?

Pool does not implement `UnwindSafe`.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
`ConnectionManager` could be made unwind safe, but `PgConnection` is inherently not unwind safe. It uses interior mutability quite a bit, has external state in the form of transactions and a persistent DB connection, and relies on a C library which has its own invariants that may be violated. Making `PgConnection` be `UnwindSafe` would fundamentally break the contract of that trait.
