### ISSUE TITLE
Example DATABASE_URL of "file:test.db" creates db that cannot be read by sqlite3(1)

### ISSUE THREAD

**Issue by rjloura** [diesel-rs/diesel#2107]
### Versions

- **Rust:** 1.35
- **Diesel:** 1.4.2
- **Database:** sqlite3
- **Operating System** Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

Following the example [here](https://github.com/diesel-rs/diesel/tree/master/examples/sqlite/getting_started_step_3) results in a file named `file:test.db` to be created.  It seems that the intent is to have the `file:` portion be a URI, but it ends up as part of the file name.  A file named "test.db" is also created.  Diesel operates just fine with this, but attempts to open `file:test.db` or `test.db` with the sqlite(1) tool (ver 3.22.0) are successful, but it appears that no data has been written to the database.

```
~/rust/diesel_demo$ cargo run --bin show_posts
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/show_posts`
Displaying 2 posts
a
----------

a

Example post
----------

This is an example.

```

```
~/rust/diesel_demo$ sqlite3 file\:test.db 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .tables
sqlite> select * from posts;
Error: no such table: posts
sqlite> .quit
~/rust/diesel_demo$ sqlite3 test.db 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .tables
sqlite> select * from posts;
Error: no such table: posts
sqlite> .quit

```

Note that modifying `DATABASE_URL` to be "file_test.db" works fine with both diesel and the `sqlite3` tool.

### What are you trying to accomplish?
View entries created by diesel with sqlite tool.

### What is the expected output?
see above

### What is the actual output?
see above

### Are you seeing any additional errors?
No, and that is probably a bug in sqlite3(1)

### Steps to reproduce
See above.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Fixed by https://github.com/diesel-rs/diesel/pull/1292/ + this is not part of any release yet therefore the examples on the master branch may differ.
