### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by qrilka** [diesel-rs/diesel#2112]
## Problem Description

Link for "SqlQuery::into_boxed" at https://docs.diesel.rs/diesel/query_builder/struct.BoxedSqlQuery.html results in 404

### What is the expected output?

Probably it should point to https://docs.diesel.rs/diesel/query_builder/struct.SqlQuery.html#method.into_boxed

### What is the actual output?

error 404

**Comment by JohnTitor** [comment]
Thanks! I opened #2114.
