### ISSUE TITLE
Implement Debug for BoxedSqlQuery

### ISSUE THREAD

**Issue by jkmartindale** [diesel-rs/diesel#2115]
**Diesel:** master branch
**Database:** MariaDB 10.0.37

## What do you want to do, and how do you expect Diesel to support you with that?
I'm making some queries that involve some raw SQL (in a similar fashion to #2103), which of course can be error-prone. If a query is malformed I'll get a runtime panic with a message from the database that my SQL is malformed, but I can't actually see the final query sent to the database. This makes it a bit tougher to do debugging.

`SqlQuery` already has a `Debug` implementation, but if I'm binding to the query in a loop and using `BoxedSqlQuery`, I have to store the `SqlQuery` to a separate variable right before calling `into_boxed()` in order to get the debug info. I also won't get to see the variables bound to the query.

## How might this be added to Diesel?
Adding an `impl Debug` block for `BoxedSqlQuery`, probably in `query_builder::sql_query`.

## What are possible alternatives?
Using and extending the robust query builder instead of shooting myself in the foot with raw SQL.

## Are there any disadvantages?
The `Debug` trait is nontrivial because of `BoxedSqlQuery.binds` having type `Vec<Box<dyn Fn(AstPass<DB>) -> QueryResult<()> + 'f>>`. That's a bit over my head, which is why I haven't written my own implementation.

**Comment by sgrif** [comment]
A `Debug` impl on this struct wouldn't be able to show you anything other than "Yup, this is a `BoxedSqlQuery`". It sounds like you're looking for http://docs.diesel.rs/diesel/fn.debug_query.html

**Comment by jkmartindale** [comment]
Oops, I guess I'm not as familiar with Diesel's API as I'd like to be. Thanks!
