### ISSUE TITLE
unclear panic message on pool new if database cannot be reach

### ISSUE THREAD

**Issue by wescande** [diesel-rs/diesel#2118]
### Versions

- **Rust:** rustc 1.37.0-nightly (8ebd67e4e 2019-06-27)  and rust in https://github.com/emk/rust-musl-builder
- **Diesel:** 1.4.2
- **Database:** Postresql
- **Operating System** Linux (Docker in aws cloud ECS And Manjaro)

### Feature Flags

- **diesel:**  postgres + r2d2 + chrono

## Problem Description
pool creation panic without clear log

### What are you trying to accomplish?
```
let manager = ConnectionManager::<PgConnection>::new(DATABASE_URL);
let pool = Pool::new(manager).expect("Failed to create pool");
```
But I made a mistake and I open the port of DATABASE_URL to the wrong IP (or just give it the wrong port). It panic and I have no clue to found what was the root cause.

### What is the expected output?
> thread 'main' panicked at 'Failed to create pool: Error(EXPLICIT_MESSAGE)', src/libcore/result.rs:999:5
where EXPLICIT_MESSAGE could be something like "cannot reach database" or "connection failed", or even better if possible "host is up but port is filtered".

### What is the actual output?
> thread 'main' panicked at 'Failed to create pool: Error(None)', src/libcore/result.rs:999:5

### Steps to reproduce

Setup your database and do not open port on the server, or do not allow the diesel server ip or set the wrong (closed)port.
Then start your pool.
There should be a 30 sec wait (more or less, on my computer it's 38s)
Then it panic with the Error(none) message

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
This comes from r2d2, not Diesel. You can open an issue at https://github.com/sfackler/r2d2
