### ISSUE TITLE
Migration crashes when adding a variant to an enum

### ISSUE THREAD

**Issue by Elrendio** [diesel-rs/diesel#2122]
### Versions

- **Rust:** rustc 1.36.0 (a53f9df32 2019-07-03) (Stable)
- **Diesel:** 1.4.2
- **Database:** Postgresql
- **Operating System** Mac OS High Sierra version 10.13.3 (17D47)

### Feature Flags

- **diesel:** postgres, r2d2, serde_json.

## Problem Description
During a first migration I created an enum called repackage_contract with code in `up.sql`
```sql
CREATE TYPE repackage_contract AS enum(
	'Stockly_ExpressWithAcknowledgement',
	'Stockly_ExpressWithoutAcknowledgement',
	'Stockly_StandardWithAcknowledgement',
	'Stockly_StandardWithoutAcknowledgement',
	'Wing_ExpressWithAcknowledgement',
	'Wing_ExpressWithoutAcknowledgement',
	'Wing_StandardWithAcknowledgement',
	'Wing_StandardWithoutAcknowledgement'
);
```

A few weeks later I need to add two variant to this enum, tried to write my up migration as:
```sql
ALTER TYPE repackage_contract ADD VALUE 'Gemmalog_StandardWithAcknowldegement';
ALTER TYPE repackage_contract ADD VALUE 'Gemmalog_StandardWithoutAcknowldegement';
```

When running `diesel --database-url "my-local-uri" migration run` I get the error:
```
Running migration 2019-07-13-162103_add-gemmalog
Executing migration script /Users/elrendio/Workspace/Stockly/Main/Repackages/migrations/2019-07-13-162103_add-gemmalog/up.sql
Failed with: ALTER TYPE ... ADD cannot run inside a transaction block
```

### What are you trying to accomplish?
I am trying to add a variant to an existing enum.

### What is the expected output?
The  migration works and the enum has the added variants.

### What is the actual output?
The  migration crashes.

### Are you seeing any additional errors?
No.

### Steps to reproduce
 - Create a new database my_test_db in a local postgresql database server.
 - run `cargo init test_crate && cd test_crate` in terminal.
 - Update your Cargo.toml and add diesel as dependency version 1.4.2 with flags postgres, r2d2, serde_json:
```toml
[dependencies]
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "serde_json"] }
```
 - Get diesel cli by running `cargo install diesel_cli`
 - Setup diesel by running `diesel setup`
 - Create initial migration by running `diesel migration generate initial`
 - Update your `up.sql` to:
```sql
CREATE TYPE repackage_contract AS enum(
	'Stockly_ExpressWithAcknowledgement',
	'Stockly_ExpressWithoutAcknowledgement',
	'Stockly_StandardWithAcknowledgement',
	'Stockly_StandardWithoutAcknowledgement',
	'Wing_ExpressWithAcknowledgement',
	'Wing_ExpressWithoutAcknowledgement',
	'Wing_StandardWithAcknowledgement',
	'Wing_StandardWithoutAcknowledgement'
);

```
 - Update your `down.sql` to:
```sql
DROP TYPE IF EXISTS "repackage_contract";
```
 - Run migration with `diesel --database-url "postgres://username:not-the-pwd@localhost/my_test_db" migration run`
 - Create new migration by running `diesel migration generate add_variant`
 - Update your `up.sql` to:
```sql
ALTER TYPE repackage_contract ADD VALUE 'Gemmalog_StandardWithAcknowldegement';
ALTER TYPE repackage_contract ADD VALUE 'Gemmalog_StandardWithoutAcknowldegement';
```
 - Update your `down.sql` to:
```sql
ALTER TYPE repackage_contract DROP VALUE 'Gemmalog_StandardWithoutAcknowldegement';
ALTER TYPE repackage_contract DROP VALUE 'Gemmalog_StandardWithAcknowldegement';
```
 - Try to run migration with `diesel --database-url "postgres://username:not-the-pwd@localhost/my_test_db" migration run`
 - You should see the error in the terminal.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
You can follow https://github.com/diesel-rs/diesel/pull/2061 for running migrations outside of a transaction.

**Comment by Elrendio** [comment]
Thanks for the info, I'll wait for the PR to be merged then :)
