### ISSUE TITLE
Connection state gets corrupted when an panic occurs in a transaction

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#2124]
### Versions

- **Rust:** rustc 1.36.0 (a53f9df32 2019-07-03)
- **Diesel:** 1.4,2
- **Database:** PostrgreSQL, psql (11.4 (Ubuntu 11.4-0ubuntu0.19.04.1), server 9.6.13)
- **Operating System** Ubuntu 19.04

### Feature Flags

- **diesel:** `["postgres", "r2d2"]`

## Problem Description

When a panic occurs in a transaction, connection gets corrupted and all the following transaction fails, like #2123 .
I'm not sure if this is a bug or intentional behavior but in this setup, connection in the connection pool gets unsound and it will be used other threads. It causes a disaster.
Thus I want it to be fixed.

I guess one way to address this issue is check `TransactionManager`'s `depth` in `is_valid` of connection pool implementation.

### What are you trying to accomplish?

Writing an application, especially using [`actix`](https://github.com/actix/actix)'s Actor for transaction runner.

### What is the expected output?

`Ok(1)` 

### What is the actual output?

`Err(AlreadyInTransaction)`

### Steps to reproduce

run code below

Cargo.toml
```toml
[package]
name = "diesel-bug-report"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = {version = "1.4.0", features = ["postgres", "r2d2"]}
```

src/main.rs
```rust
use diesel::pg::PgConnection;
use diesel::prelude::*;
use diesel::r2d2::{ConnectionManager, Pool};
use diesel::result::Error;
use std::thread;

fn main() {
    // create thread pool
    let manager = ConnectionManager::<PgConnection>::new(
        "postgres://user:password@localhost/database".to_string(),
    );
    let pool = Pool::builder()
        .build(manager)
        .expect("Failed to create pool.");

    // run a transaction in a thread.
    let pool2 = pool.clone();
    let handle = thread::spawn(move || {
        let conn = pool2.get().unwrap();
        conn.transaction(|| -> Result<(), Error> {
            // panics it
            panic!("panic");
        })
    });
    let ret = handle.join();
    // gets error
    println!("{:?}", ret);

    // other transaction after panic
    // Note: though we are using connection pool, as its implementation is a stack,
    //       we always get the connection used before.
    let conn = pool.get().unwrap();
    let ret = conn
        .build_transaction()
        .serializable()
        .run(|| conn.execute("SELECT 1"));
    // must be Ok(1) but get Err(AlreadyInTransaction)
    println!("{:?}", ret);
}

```

output

```
thread '<unnamed>' panicked at 'panic', src/main.rs:21:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Err(Any)
Err(AlreadyInTransaction)
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
Thank you for the issue. Our connections are not panic safe, and should not be retained after a panic. r2d2 currently does so, and this has been brought up [multiple](https://github.com/diesel-rs/diesel/issues/2105) [times](https://github.com/diesel-rs/diesel/issues/2104) [before](https://github.com/diesel-rs/diesel/pull/2020). There is an open PR to r2d2 to fix this there.

**Comment by KeenS** [comment]
Thank you for your comment. I lacked care.
