### ISSUE TITLE
[Feature Request] PostgreSQL Large Objects

### ISSUE THREAD

**Issue by leo-lb** [diesel-rs/diesel#2127]
Hello,

For a project, I would need to store [large objects](https://www.postgresql.org/docs/11/largeobjects.html) within PostgreSQL, however, I could not find support for it in the documentation, so I am creating this issue to motivate implementation.

Thank you

**Comment by leo-lb** [comment]
https://github.com/sfackler/rust-postgres-large-object

**Comment by weiznich** [comment]
Could you write a few words about how you would image that such an API would look like and what are the advantages of having it integrated into diesel itself? 
For me it seems like this would be completely decoupled form the normal diesel api, therefore just using the linked crate seems to be a usable solution.

**Comment by leo-lb** [comment]
> Could you write a few words about how you would image that such an API would look like and what are the advantages of having it integrated into diesel itself?
> For me it seems like this would be completely decoupled form the normal diesel api, therefore just using the linked crate seems to be a usable solution.

Being able to get types with Read/Write traits implemented on structures that have Oid values that correspond to large objects for example

**Comment by weiznich** [comment]
Could you type out a short example how the user facing code would look like? I'm not sure if fully understand what you exactly imaging.

**Comment by leo-lb** [comment]
SQL:
```
CREATE TABLE lo_table (
    lo OID
);
```

Rust:
```
#[derive(Queryable)]
struct LoTable {
    lo LargeObject,
}

impl LoTable {
    fn query_one(conn: &PgConnection) -> Result<LoTable, diesel::result::Error> {
        use crate::schema::lo_table::dsl;

        dsl::lo_table.get_result(conn)
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut row = LoTable::query_one(....)?;

    std::io::copy(&row.lo, std::io::stdout())?; // Write large object to stdout
    row.seek(std::io::SeekFrom::Start(0))?; // Seek to beginning
    row.write_all(&[0; 1024])?; // Write 1024 zeroes to large object

    Ok(())
}
```

**Comment by sgrif** [comment]
I'm not convinced this needs explicit support in Diesel. Large object functionality is fully exposed on the server, so this could be handled by another library using `sql_function!`.

**Comment by weiznich** [comment]
As pointed out by Siân this could be done via `sql_function!` in a third party library. If that requires additional support in diesel itself please open a feature request post in our discussion forum.

**Comment by mleonhard** [comment]
Diesel currently does not support accessing [Postgres large objects](https://www.postgresql.org/docs/13/largeobjects.html).  The suggested workaround is to use a different library for accessing large objects.  I'm having trouble getting this to work.  I don't understand how to use [`diesel::sql_function!`](https://docs.diesel.rs/1.4.x/diesel/macro.sql_function.html) to access large objects.  I see four potential solutions:
1. Add to [`diesel::pg::PgConnection`](https://docs.diesel.rs/1.4.x/diesel/pg/struct.PgConnection.html) a way to borrow the underlying [`postgres::Client`](https://docs.rs/postgres/0.19.1/postgres/struct.Client.html) struct to use with the traits in [`postgres_large_object` crate](https://docs.rs/postgres_large_object/0.7.1/postgres_large_object/).  Ideally, large object operations would be included in the Diesel transaction.
1. Add a [`diesel::pg::PgConnection`](https://docs.diesel.rs/1.4.x/diesel/pg/struct.PgConnection.html) constructor that borrows a [`postgres::Client`](https://docs.rs/postgres/0.19.1/postgres/struct.Client.html).  Then we can use Diesel with connections from any connection pool, such as [`r2d2_postgres`](https://docs.rs/r2d2_postgres/0.18.0/r2d2_postgres/).  Ideally, Diesel will use any existing transaction on the client.  Then we can use one transaction to put a large object, let the database generate the OID, and then use Diesel to insert the OID into a table.
1. Use a separate connection pool for large object operations.  This will severely harm performance.  This is the only solution that works right now.
1. Add support for large objects directly into Diesel.  This is the proposal above.  Here's a simplified version:
   - Make Diesel map [Postgres Object Identifier type](https://www.postgresql.org/docs/current/datatype-oid.html) to Rust `u32`.
   - Add methods to `PgConnection`:
      - `pub fn create_large_object(&mut self, oid: Option<u32>) -> diesel::result::QueryResult<u32>` which calls [`lo_create `](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-CREATE).
      - `pub fn remove_large_object(&mut self, oid: u32) -> diesel::result::QueryResult<()>` which calls [`lo_unlink`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-UNLINK) and returns `Err(diesel::result::Error::NotFound)` when `lo_unlink` returns -1.
      - `pub fn read_large_object(&'a mut self, oid: u32) -> diesel::result::QueryResult<PgLargeObjectReader<'a>>` which calls [`lo_open`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-OPEN) with `INV_READ` mode.  The returned object implements [`std::io::Read`](https://doc.rust-lang.org/stable/std/io/trait.Read.html) and calls [`lo_read`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-READ).  It calls [`lo_close`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-CLOSE) on drop.
      - `pub fn write_large_object(&'a mut self, oid: u32) -> diesel::result::QueryResult<PgLargeObjectWriter<'a>>` which calls [`lo_open`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-OPEN) with `INV_WRITE` mode.  The returned object implements [`std::io::Write`](https://doc.rust-lang.org/stable/std/io/trait.Write.html) and calls [`lo_write`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-WRITE).  It calls [`lo_close`](https://www.postgresql.org/docs/13/lo-interfaces.html#LO-CLOSE) on drop.

Can we please re-open this feature request and implement # 1 or # 2 above?  If one of them is already possible, then let's document how to do it.  I'm willing to make the PR.

**Comment by weiznich** [comment]
@mleonhard Neither your first nor your second "solution" are possible to implement, as diesel does not use `postgres::Client` internally. `diesel::pg::PgConnection` uses `libpq` internally not the pure rust implementation, because of historic reasons and for performance reasons.
As already written above: It's totally possible to use the `sql_function!` interface on your own to define the corresponding [server side functions](https://www.postgresql.org/docs/current/lo-funcs.html).

**Comment by mleonhard** [comment]
Thank you for the link to the [Postgres Large Object Server-Side Functions](https://www.postgresql.org/docs/current/lo-funcs.html).  I missed them earlier.  I think I can make this work. :)

**Comment by mleonhard** [comment]
It working!  Storing binaries in Postgres lets me eliminate my app's dependency on DigitalOcean Spaces (S3).  Thank you, @sgrif & @weiznich, for making and maintaining Diesel and for being so helpful on these issues.

Code to use Postgres Large Objects Server Side Functions with Diesel:
```rust
// models.rs
use diesel::pg::types::sql_types::Oid;
use diesel::sql_types::{BigInt, Binary, Integer};
sql_function! {
    /// Creates a large object with OID `loid` and stores `data` in it.
    /// Returns an error if `loid` already exists.
    /// If `loid` is zero, chooses a free OID for the new object.
    ///
    /// Returns the OID of the new object.
    ///
    /// See <https://www.postgresql.org/docs/current/lo-funcs.html>.
    fn lo_from_bytea(loid: Oid, data: Binary) -> Oid
}
sql_function! {
    /// Gets the large object with OID `loid`.
    /// Returns an erorr if the object doesn't exist.
    ///
    /// See <https://www.postgresql.org/docs/current/lo-funcs.html>.
    fn lo_get(loid: Oid) -> Binary
}
sql_function! {
    /// Deletes the large object with OID `loid`.
    /// Returns 1 on success and -1 on failure.
    ///
    /// See <https://www.postgresql.org/docs/current/lo-funcs.html> and
    /// <https://www.postgresql.org/docs/current/lo-interfaces.html#LO-UNLINK>.
    fn lo_unlink(loid: Oid) -> Integer
}
```

Example write:
```rust
let photo_oid = select(lo_from_bytea(0, photo_bytes_cursor.into_inner()))
    .get_result::<u32>(&conn)
    .unwrap();
```

Example read:
```rust
use crate::schema::photos;
let photo_oid_values: Vec<u32> = photos::table
    .select(photos::photo_oid)
    .filter(photos::id.eq(photo_id))
    .filter(photos::account_id.eq(account_id))
    .limit(1)
    .load::<u32>(&conn)
    .unwrap();
if photo_oid_values.is_empty() {
    return Err(Response::empty_404());
}
let mut photo_bytes: Vec<u8> = select(lo_get(photo_oid_values[0]))
    .get_result::<Vec<u8>>(&conn)
    .unwrap();
photo_bytes.shrink_to_fit();
return Ok(Response::from_data("image/jpeg", photo_bytes));
```
