### ISSUE TITLE
Diesel fails to compile schema.rs when tables have more than 32 columns

### ISSUE THREAD

**Issue by sergeken** [diesel-rs/diesel#2129]
### Versions

- **Rust:** 1.36.0
- **Diesel:** 1.4.0
- **Database:** Postgresql
- **Operating System** Arch Linux

### Feature Flags

- **diesel:** 1.36.0

## Problem Description
When compiling a an application that has tables of more than 32 columns rustc gives unclear error messages.  Commenting enough fields (doesn't matter which one nor type) up to 32 fields allows to build/compile.

### What are you trying to accomplish?
build an application with cargo build

### What is the expected output?
a successful build (compilation)

### What is the actual output?
error[E0277]: the trait bound `(database::schema::authorisation::columns::id, database::schema::authorisation::columns::request_type, database::schema::authorisation::columns::status, database::schema::authorisation::columns::card, database::schema::authorisation::columns::terminal, database::schema::authorisation::columns::transaction_type, database::schema::authorisation::columns::terminal_conditions, database::schema::authorisation::columns::transaction_amount_amount, database::schema::authorisation::columns::transaction_amount_currency, database::schema::authorisation::columns::billing_amount_amount, database::schema::authorisation::columns::billing_amount_currency, database::schema::authorisation::columns::settlement_amount_amount, database::schema::authorisation::columns::settlement_amount_currency, database::schema::authorisation::columns::expiry_month, database::schema::authorisation::columns::expiry_year, database::schema::authorisation::columns::card_sequence_number, database::schema::authorisation::columns::card_holder_name, database::schema::authorisation::columns::transaction_timestamp, database::schema::authorisation::columns::settlement_date, database::schema::authorisation::columns::authorisation_code, database::schema::authorisation::columns::mcc, database::schema::authorisation::columns::card_acceptor_code, database::schema::authorisation::columns::merchant_name, database::schema::authorisation::columns::merchant_city, database::schema::authorisation::columns::merchant_country, database::schema::authorisation::columns::stan, database::schema::authorisation::columns::rrn, database::schema::authorisation::columns::aid, database::schema::authorisation::columns::network_code, database::schema::authorisation::columns::processing_timestamp, database::schema::authorisation::columns::input_channel, database::schema::authorisation::columns::output_channel, database::schema::authorisation::columns::is_authorised): diesel::Expression` is not satisfied
  --> src/database/schema.rs:35:1

### Are you seeing any additional errors?
no

## Checklist

- [ Y] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [Y ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Diesel implements some traits for tuples. Because of rust does not have variadic generics we need to provide a distinct impl for each tuple size. Because compile time gets exponentially worse while providing more impl we decided to provide only support for 32 columns by default. There are [those](https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L48-L53) feature flags which provide support for bigger tables at the cost of higher compilation times.

Closed because this is no actionable issue for use.

**Comment by Arcovv** [comment]
Thanks!
