### ISSUE TITLE
Remove cyclomatic-complexity-threshold from clippy.toml

### ISSUE THREAD

**Issue by rjloura** [diesel-rs/diesel#2136]
### Versions

- **Rust:** 1.36
- **Diesel:**  1.4.2 patched to github master
- **Database:** sqlite3
- **Operating System** Linux 4.15

### Feature Flags

- **diesel:** sqlite

## Problem Description
When running `cargo clippy` on my project that depends on diesel the following error is reported, and clippy build aborts:
```
    Checking diesel v1.4.2 (https://github.com/diesel-rs/diesel#0b6c59e3)
error: error reading Clippy's configuration file `/home/rui/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/0b6c59e/clippy.toml`: found deprecated field `cyclomatic-complexity-threshold`. Please use `cognitive-complexity-threshold` instead.
```

### What are you trying to accomplish?
Run clippy

### What is the expected output?
`Finished dev [unoptimized + debuginfo] target(s) in 20.88s`

### What is the actual output?
See above

### Are you seeing any additional errors?
No

### Steps to reproduce
Run `cargo clippy`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

I replaced `cyclomatic-complexity-threshold` with `cognitive-complexity-threshold` in clippy.toml, and `cargo clippy` now builds.

**Comment by rjloura** [comment]
Works fine on rust 1.34.

**Comment by JohnTitor** [comment]
Related to https://github.com/diesel-rs/diesel/pull/2089
