### ISSUE TITLE
Positive/negative infinity in Postgres Timestampz can't be deserialized

### ISSUE THREAD

**Issue by tecywiz121** [diesel-rs/diesel#2139]
### Versions

- **Rust:** rustc 1.36.0-nightly (9b67bd42b 2019-05-01)
- **Diesel:** 1.4.2
- **Database:** PostgreSQL 9.5.17
- **Operating System:** Ubuntu 16.04.6 LTS

### Feature Flags

- **diesel:** `["chrono", "postgres", "r2d2"]`

## Problem Description

PostgreSQL's timestamp and interval types support positive and negative infinity as possible values. See the [documentation](https://www.postgresql.org/docs/9.0/datatype-datetime.html#AEN5647) for details.

### What are you trying to accomplish?

 I wanted to use positive infinity to represent an event that continues forever. When diesel deserializes an `infinity` timestamp, it errors out.

### What is the expected output?

I'd like to see something like:

```rust
enum Timestamp {
    Finite(u64),
    Infinity,
    NegativeInfinity,
}
```

### What is the actual output?

When a row contains a timestamp with either positive or negative infinity, Diesel returns [this error](https://github.com/diesel-rs/diesel/blob/77afd4d09421b9db06665b831a7770eec7fd4425/diesel/src/pg/types/date_and_time/chrono.rs#L27):

```
Tried to deserialize a timestamp that is too large for Chrono
```

### Steps to reproduce

1. `CREATE TABLE foo ( col TIMESTAMP WITH TIME ZONE );`
2. `INSERT INTO foo VALUES ('infinity');`
3. Create a diesel struct and try to deserialize the row.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
It is easily possible to add support for own types in third party code. Just follow [this example](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs#L22-L47).
As the error message says there is not much we can to there to support that with chrono, until chrono adds support for such large timestamps.
