### ISSUE TITLE
How to get associations when having 2 foreign keys referencing the same table?

### ISSUE THREAD

**Issue by gh67uyyghj** [diesel-rs/diesel#2142]
First off, thank you so much for creating this great project. Really one of the best ORMs in any language tbh. I know this is not a bug but I wasted a day googling on this and couldn't find an answer.

My DB setup

```
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  <....OMITTED COLUMNS....>
)


CREATE TABLE users_follows (
  follower_id  INTEGER  NOT NULL,
  followed_id  INTEGER  NOT NULL,
  PRIMARY KEY  (follower_id, followed_id),
  FOREIGN KEY  (follower_id)  REFERENCES  users (id),
  FOREIGN KEY  (followed_id)  REFERENCES  users (id)
)

```

where the model of `users` is simply something like

```
#[derive(Debug, Queryable, Deserialize, Serialize, Identifiable, Associations)]
pub struct User {
    pub id: i32,
    pub username: String,
   // other fields
}
```

Now, how do I get a `Vec<User>` that are `follower`s belonging to some `followed` `User`?

**Comment by sgrif** [comment]
You can't. You can use the built-in associations for one or none of them, and have custom functions for the others. If you had two associations, what should the following do?:

```
UserFollow::belonging_to(&user)
```

**Comment by sgrif** [comment]
To answer your second question:

Now, how do I get a Vec<User> that are followers belonging to some followed User?

```
users::table
    .inner_join(user_follows::table.on(user_follows::follower_id.eq(users::id)))
    .filter(user_follows::followed_id.eq(some_user.id))
```

If you have further questions, please ask in our gitter or discourse -- the issue tracker is not a help forum. I'm going to close this as there's no actionable issue here.
