### ISSUE TITLE
`is_some` and `is_none` alternatives to `is_null` and `is_not_null`

### ISSUE THREAD

**Issue by VictorKoenders** [diesel-rs/diesel#2151]
When dealing with diesel code, a user might expect `is_some()` to work, considering the database models are mapped to `Option<T>`. Currently, the method `is_not_null()` has to be used.

Under water the method `is_some()` would map to `is_not_null()`, and `is_none()` would map to `is_null()`

**Comment by weiznich** [comment]
The diesel sql dsl is build as near as possible to the corrsponding sql, so naming this functions `is_not_null` and `is_null` makes sense. I do not see any reason why we should change that to more rustic names.
