### ISSUE TITLE
Docker container with diesel CLI

### ISSUE THREAD

**Issue by vbrandl** [diesel-rs/diesel#2156]
It would be cool to have an official `diesel-cli` container, so I can deploy an application as a `docker-compose` setup.

My idea is to start the database first, mount the migrations and a `.env` file into the `diesel-cli` container, execute `diesel migration run`, wait for the container to terminate and start the application afterwards.

This would enable painless updates of the application.

**Comment by weiznich** [comment]
At least for me that's out of the scope of the current project. We don't have the bandwidth to maintain a docker container on top of the actual code. So I close this issue as not actionable.

Beside of that: You probably want to look into `diesel_migrations::embed_migrations!` which would remove the need of `diesel migration run` in your docker container.

**Comment by vbrandl** [comment]
Thanks for pointing out `diesel_migrations::embed_migrations`. This solves my problem
