### ISSUE TITLE
How to insert nullable sequence / raw SQL record structures with postgres?

### ISSUE THREAD

**Issue by ronaldslc** [diesel-rs/diesel#2158]
I have a problem that I can't figure out. I have a field that may be null, or it could be a smallint type that is obtained from a sequence.

What is the recommended way, or is it even possible to use a record structure to perform insertion?

I have looked in the direction of the implementation of the `now` struct in expressions/functions, I've tried to implement ToSQL with AsExpression derive, but nothing seems to work.

Incidentally, is it possible to insert using raw SQL expressions within a record structure optionally? For example in the following structure

```rust
struct Record<'a> {
    pub id: &'a Uuid,
    pub optional_sequence: Option<i32>,
    pub record_time: Option<DateTime<Utc>>
}

table! {
    records (id) {
        id -> Uuid,
        optional_sequence -> Nullable<Int2>,
        record_time -> Nullable<Timestamptz>,
    }
}
```

How would I be able to perform insertion into `record_time` field using `now()` for some queries or a specific time for others, or even `NULL` for some under a single API, and how would I be able to insert `NULL` for `optional_sequence` or `nextval('record_seq')` for others, without resorting to manual SQL?

Thanks in advance for any advice.

**Comment by weiznich** [comment]
The issue tracker is used to track bugs and feature requests. Please use [our gitter channel](https://gitter.im/diesel-rs/diesel) to ask questions.

To give you a quick pointer here: Use the tuple insert variant.
