### ISSUE TITLE
where is the example code about datetime in Mysql?

### ISSUE THREAD

**Issue by najcit** [diesel-rs/diesel#2160]
### Versions

- **Rust:**1.36.0-x86_64-pc-windows-msvc
- **Diesel:** 1.4.0
- **Database:** 8.0.17
- **Operating System** Windows 10

### Feature Flags

- **diesel:**
diesel = { version = "1.4.0", features = ["mysql", "chrono"] }

## Problem Description
the trait `diesel::Queryable<diesel::sql_types::Datetime, diesel::mysql::Mysql>` is not implemented for `diesel::sql_types::Datetime`

### What are you trying to accomplish?
known how to use the type about `datetime`

### What is the actual output?
^^^^ the trait `diesel::Queryable<diesel::sql_types::Datetime, diesel::mysql::Mysql>` is not implemented for `diesel::sql_types::Datetime`

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Our issue tracker is used to track bugs and feature request for diesel. For asking questions please use our [gitter channel](https://gitter.im/diesel-rs/diesel).

To answer that specific question see [this section](http://docs.diesel.rs/diesel/index.html#serializing-and-deserializing) of our documentation.

> Diesel maps "Rust types" (e.g. i32) to and from "SQL types" (e.g. diesel::sql_types::Integer). You can find all the types supported by Diesel in the sql_types module. These types are only used to represent a SQL type. You should never put them on your Queryable structs.

**Comment by Jovons** [comment]
Actually I am wondering if this is a bug. I added a column of datetime in getting-started demo,
```
CREATE TABLE `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `create_time` DATETIME default NOW(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
```
And then the automatically generated schema.rs has :
```
table! {
    posts (id) {
        id -> Integer,
        title -> Varchar,
        body -> Text,
        published -> Bool,
        create_time -> Nullable<Datetime>,
    }
}
```
And then, it gives a compiling error:
the trait `FromSql<diesel::sql_types::Nullable<diesel::sql_types::Datetime>, Mysql>` is not implemented for `chrono::naive::datetime::NaiveDateTime`

However, if changed Nullable<Datetime> to Timestamp, the error is gone.
Like this example:
https://github.com/pymongo/diesel_crud/blob/main/src/main.rs
