### ISSUE TITLE
PostgreSQL: LISTEN on PG_NOTIFY

### ISSUE THREAD

**Issue by nathanloisel** [diesel-rs/diesel#2166]
Hey guys,
I'm looking for listening on pg_notify event from PostgreSQL.
I don't find it, is it planned to be implemented soon?
It's a really useful feature for complex data streaming applications and it will be very valuable for diesel.

**Comment by weiznich** [comment]
@sgrif Stated [here](https://gitter.im/diesel-rs/diesel?at=5c3ce4a639596c372bdfca50) the following regarding to `notify`/`listen` support in diesel:

> I wouldn't want to support it in Diesel at the moment. When we switch to async io, we'll need to rewrite the PG adapter to drop libpq, and having to support LISTEN will make the new driver way more complex

So I will close this issue as not actionable for the diesel team.

**Comment by LucaCappelletti94** [comment]
Hi! Have any updates on this issue since 2019?

**Comment by weiznich** [comment]
@LucaCappelletti94 It's highly discouraged to post to old closed issues. Please use the discussion forum for such questions.

**Comment by LucaCappelletti94** [comment]
Is the forum Gitter? Or where else?
