### ISSUE TITLE
docker image fails with "128-column-tables" configin Cargo.tomal

### ISSUE THREAD

**Issue by kushwahashiv** [diesel-rs/diesel#2170]
### Versions

- **Rust:** v1.36
- **Diesel:** v1.4.2
- **Database:** psogresql
- **Operating System** docker image on macOS Mojave

### Feature Flags

- **diesel:**
I have following diesel configuration in Cargo.toml

```cmd diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2", "128-column-tables"] }```

## Problem Description

```cmd
Caused by:
  process didn't exit successfully: `rustc --crate-name diesel /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="128-column-tables"' --cfg 'feature="32-column-tables"' --cfg 'feature="64-column-tables"' --cfg 'feature="bitflags"' --cfg 'feature="chrono"' --cfg 'feature="default"' --cfg 'feature="postgres"' --cfg 'feature="pq-sys"' --cfg 'feature="r2d2"' --cfg 'feature="with-deprecated"' -C metadata=9664616789b5cfb9 -C extra-filename=-9664616789b5cfb9 --out-dir /app/target/release/deps -L dependency=/app/target/release/deps --extern bitflags=/app/target/release/deps/libbitflags-49c6973d41782421.rmeta --extern byteorder=/app/target/release/deps/libbyteorder-5b2e40d569377389.rmeta --extern chrono=/app/target/release/deps/libchrono-d6fcf2ba62ca6b7a.rmeta --extern diesel_derives=/app/target/release/deps/libdiesel_derives-82c547776241e08d.so --extern pq_sys=/app/target/release/deps/libpq_sys-ae7062b0ce6cba8a.rmeta --extern r2d2=/app/target/release/deps/libr2d2-5eb27e2ed043be9e.rmeta --cap-lints allow -L native=/usr/lib/x86_64-linux-gnu` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Without future information it is not possible to do anything here. Is there any specific build error beside of `error: build failed?` Maybe you are running out of system resources? (In this case there is nothing diesel could do here. Maybe open a issue at rustc that it is using to much resources to compile diesel then?).

**Comment by kushwahashiv** [comment]
@weiznich you are right. just closing the issue here.
