### ISSUE TITLE
Diesel CLI has a wrong assumption about mysql.sock location

### ISSUE THREAD

**Issue by pronebird** [diesel-rs/diesel#2171]
### Versions

- **Rust:** 1.39-nightly
- **Diesel:** 1.4.2
- **Database:** mysql
- **Operating System** macOS

### Feature Flags

- **diesel:** mysql

## Problem Description

Running diesel-cli with 

```diesel setup --database-url mysql://root:root@localhost:8889/mydb``` 

prints out:

>Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

It seems to me that the CLI assumes the location of the `mysql.sock` file if the hostname is `localhost`. Replacing `localhost` with `127.0.0.1` makes CLI to go through the TCP connection and successfully set up the database.

For the record `mysql.sock` exists and it's at a different location than usual. I think the CLI should either fallback to using TCP when it can't locate the `/tmp/mysql.sock` and at least output a warning.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Diesel does not make any assumptions there, we are just passing down the connection string to libmysqlclient.

I'm closing this issue because it seems to be a libmysqlclient issue, not a diesel issue.

**Comment by pfrenssen** [comment]
If you use `localhost` in MySQL it assumes you have MySQL installed natively on the local machine and will try to connect through the socket. This fails if you don't have it installed but are using a container or are forwarding a port. To inform MySQL to use TCP transport, use `127.0.0.1` as the hostname instead of `localhost`.

**Comment by dbidwell94** [comment]
> If you use `localhost` in MySQL it assumes you have MySQL installed natively on the local machine and will try to connect through the socket. This fails if you don't have it installed but are using a container or are forwarding a port. To inform MySQL to use TCP transport, use `127.0.0.1` as the hostname instead of `localhost`.

THANK YOU! I've been trying to run diesel migrations for a while now through a dockerized database with no success. This 100% solved my issue.
