### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by zoechi** [diesel-rs/diesel#2172]
I think 
> `diesel bash-completion > /etc/bash_completion.d/diesel`

should be updated to
```
sudo bash -c 'sudo /home/my-user-name/.cargo/bin/diesel completions bash > /etc/bash_completion.d/diesel'
```

With the command from the README.md I got errors like

> sudo diesel bash-completion > /etc/bash_completion.d/diesel
bash: /etc/bash_completion.d/diesel: Permission denied

> WARNING: `diesel bash-completion` is deprecated, use `diesel completions bash` instead

**Comment by weiznich** [comment]
Please open a PR :wink:

**Comment by shirshak55** [comment]
hmm by the way i think diesel supports zsh also right?
