### ISSUE TITLE
Diesel not support Posgres 12.0?

### ISSUE THREAD

**Issue by ScottHuangZL** [diesel-rs/diesel#2184]
### Versions

- **Rust:**
rustc 1.40.0-nightly (8431f261d 2019-09-29)
- **Diesel:**
1.4.2
- **Database:**
Postgres 12
- **Operating System**
Win 10 X64
with visual studio 19 preview 4
### Feature Flags

- **diesel:**
cargo install diesel_cli --no-default-features --features postgres

## Problem Description

I am able install diesel cli with sqlite & mysql.  It is work.

**But failed for Postgres.**
It can successful build with below comand: 
**cargo install diesel_cli --no-default-features --features postgres**

However, when you run diesel.exe, it would pop up a dialog and show error.

Do diesel cli need some enhancement to adapt latest PG12?

### What are you trying to accomplish?
To generate diesel for both mysql/sqlite/posgres.
It seems mysql & sqlite version is ok.
But PG version is failed. (Can success build and generate diesel.exe, but that exe not work)

### What is the expected output?
diesel.exe can run smoothly

### What is the actual output?
diesel.exe would pop up a box to show error:  cannot start with error 0xc000007b

### Are you seeing any additional errors?
no. 

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
The error code indicates that you are trying to use a 32bit library in a 64bit binary/build/system. Please double check that the installed version of libpq matches your system.

Generally speaking: As long as there are no breaking API changes in libpq (or more concrete: as long as the underlying binary protocol does not change in an incompatible way) new postgres versions are compatible with diesel.

**Comment by ScottHuangZL** [comment]
But what I download is: postgresql-12.0-1-windows-x64
It mean it is x64 not 32bit, right?

**Comment by ScottHuangZL** [comment]
I find the issue: I put one old libpq.dll in system folder before.
After delete that dll, and set correct path to pq12 lib, the diesel cli can run smoothly.
Thanks.
