### ISSUE TITLE
sqlite:// is not handled properly

### ISSUE THREAD

**Issue by CugeDe** [diesel-rs/diesel#2185]
### Versions

- **Rust:** 1.39.0-nightly
- **Diesel:** 1.4.2
- **Database:** sqlite
- **Operating System**  Archlinux 5.2.9

### Feature Flags

- **diesel:** sqlite

## Problem Description
Having an URL starting by sqlite:// is not properly handled.

file: `diesel_cli/src/database.rs`
```rust
impl Backend {
    fn for_url(database_url: &str) -> Self {
        match database_url {
            // ...
            #[cfg(feature = "sqlite")]
            _ => Backend::Sqlite,
```
From what I see in the file presented above, when the CLI receives an URL that does not start with "postgres://" | "postgresql://" | "mysql://", it defines `Backend` as sqlite. No problem with that.

The problem is coming from the fact that if I enter an URL starting with "sqlite://", it is not handled properly. Why ?

file: `diesel_cli/src/database.rs`
```rust
fn create_database_if_needed(database_url: &str) -> DatabaseResult<()> {
    match Backend::for_url(database_url) {
        #[cfg(feature = "postgres")]
        Backend::Pg => {
            // ...
        }
        #[cfg(feature = "sqlite")]
        Backend::Sqlite => {
            if !::std::path::Path::new(database_url).exists() {
                println!("Creating database: {}", database_url);
                SqliteConnection::establish(database_url)?;
            }
        }
        #[cfg(feature = "mysql")]
        Backend::Mysql => {
            // ...
        }
```
Here, when Backend::Sqlite is matched, you check if the path does not already exist. With "sqlite://", it will never exist. Not a problem to create but if setup is ran again, ...

On top of that, I can't manage to have a successful return from the CLI when I use an URL starting with "sqlite://".

```bash
$ diesel setup --database-url "sqlite://database.sqlite"
Creating database: sqlite://database.sqlite
Unable to open the database file
```

```bash
$ diesel setup --database-url "sqlite:///tmp/database.sqlite"
Creating database: sqlite://database.sqlite
Unable to open the database file
```
#### file: .env
```
DATABASE_URL=sqlite:///tmp/database.sqlite
```
#### pure CLI
```bash
$ diesel setup --database-url "sqlite:///tmp/database.sqlite"
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

Thanks for reading.

CugeDe

**Comment by weiznich** [comment]
You are looking at the source code of the master branch while using the last release. The corresponding code changed after the last release so this is currently expected behaviour. The next release will support `sqlite://…`
