### ISSUE TITLE
Neither #[changeset_options(treat_none_as_null="true")] or Option<Option<T>> not working

### ISSUE THREAD

**Issue by sabahtalateh** [diesel-rs/diesel#2190]
### Versions

- **Rust:** 1.38
- **Diesel:** 1.4.2
- **Database:** Postgres
- **Operating System** macos

### Feature Flags

- **diesel:**

## Problem Description
Neither Option<Option<T>> or #[changeset_options(treat_none_as_null="true")] not working. Compiler fails with 
```error[E0277]: the trait bound `std::option::Option<&str>: diesel::AppearsOnTable<schema::posts::table>` is not satisfied
  --> src/models.rs:17:10
   |
17 | #[derive(AsChangeset)]
   |          ^^^^^^^^^^^ the trait `diesel::AppearsOnTable<schema::posts::table>` is not implemented for `std::option::Option<&str>`
   |
   = note: required because of the requirements on the impl of `diesel::AppearsOnTable<schema::posts::table>` for `&std::option::Option<&str>`
   = note: required because of the requirements on the impl of `diesel::query_builder::AsChangeset` for `diesel::expression::operators::Eq<schema::posts::columns::title, &std::option::Option<&str>>`
```
or
```error[E0277]: the trait bound `std::option::Option<&str>: diesel::AppearsOnTable<schema::posts::table>` is not satisfied
  --> src/models.rs:17:10
   |
17 | #[derive(AsChangeset)]
   |          ^^^^^^^^^^^ the trait `diesel::AppearsOnTable<schema::posts::table>` is not implemented for `std::option::Option<&str>`
   |
   = note: required because of the requirements on the impl of `diesel::AppearsOnTable<schema::posts::table>` for `&std::option::Option<&str>`
   = note: required because of the requirements on the impl of `diesel::query_builder::AsChangeset` for `diesel::expression::operators::Eq<schema::posts::columns::title, &std::option::Option<&str>>`
```

### What are you trying to accomplish?
Trying to pass the second Diesel guide - AsChangeset section

### What is the expected output?
Successful compilation

### What is the actual output?
Errors

### Are you seeing any additional errors?
No, just error from description

### Steps to reproduce
Just follow http://diesel.rs/guides/all-about-updates/ AsChangeset section

## Checklist

- [+] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [+] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
`posts::title` is a non nullable column therefore it make no sense to insert a null value there, as such an update statement would clause a runtime query error.
Diesel is catching that issue and refuses to compile the query.

**Comment by sabahtalateh** [comment]
@weiznich Got it, thanks, I thought that it is no matter if it the field nullable or not in the schema file
