### ISSUE TITLE
Support custom aggregate functions using the sqlite backend

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#2191]
Diesel currently provides a quite nice interface for custom sql functions using the sqlite backend, but it is not possible to write custom aggregate functions yet. 

Starting points for an implementation:
* `sqlite::connection::raw::RawConnection` has [a function to register custom sql functions](https://github.com/diesel-rs/diesel/blob/master/diesel/src/sqlite/connection/raw.rs#L67-L110). A similar function is required for aggregating functions. See the  [Sqlite documentation](https://www.sqlite.org/c3ref/create_function.html) for which parameters need to be passed. Both functions should share code where possible.
* `sqlite::connection::function` defines some boiler plate code that does setup/teardown before/after calling a user provided function inside of a sql function. Maybe this needs to be extended to handle some special cases for aggregating functions.
* `SqliteConnection` defines a function to [register custom sql functions]. A similar function is required for aggregating functions. 
* The `sql_function!` proc macro provides some code generation for defining the necessary types used to call such a function. The [already existing](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/sql_function.rs#L138-L196) function there needs to be extended to expose functions to register the aggregating function using the methods implemented in the previous steps. Depending on the [`is_aggregate`](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/sql_function.rs#L24) flag either methods to register aggregating or non aggregating functions should be generated.
* Write some test cases [here](https://github.com/diesel-rs/diesel/blob/master/diesel/src/sqlite/connection/mod.rs#L326). See the already existing test cases for inspiration.

Open questions:
* How exactly does the user facing interface look like? It could be a good idea not to take two closure but a custom trait defining the two required methods

**Comment by thekuom** [comment]
I would like to start on this if you're still looking to have this functionality

**Comment by weiznich** [comment]
Yes we are still interested in this functionality. If you have any questions/problems while trying to implement this, be sure to ask for help here or in our gitter channel. Also opening a WIP PR to get some early feedback on the code could be a good idea.

**Comment by weiznich** [comment]
Closed by #2325
