### ISSUE TITLE
Execute PRAGMA query using diesel::sql_query

### ISSUE THREAD

**Issue by anler** [diesel-rs/diesel#2206]
### Versions

- **Rust:** rustc 1.38.0 (625451e37 2019-09-23)
- **Diesel:** 1.4.3  (
- **Database:** Sqlite 3.30.1
- **Operating System** Manjaro Linux 5.3.6-1

### Feature Flags

- **diesel:** default, r2d2, sqlite
- **libsqlite3-sys:** sqlcipher

## Problem Description

When trying to build a raw `PRAGMA` query using `sql_query` diesel throws the error:

```
DatabaseError(__Unknown, "near \"?\": syntax error")
```

### What are you trying to accomplish?

I'm trying to execute the given query against the database in order to tell `sqlcipher` it should encrypt the database file:

```rust
let query = sql_query("PRAGMA key = ?").bind::<sql_types::Text, _>("secret");
```

### What is the expected output?

I would expect the query to succeed.

### What is the actual output?

The error: `DatabaseError(__Unknown, "near \"?\": syntax error")`.

Debugging the query yields: `PRAGMA key = ? -- binds: ["secret"]`

### Are you seeing any additional errors?

No

### Steps to reproduce

1. Create an Sqlite connection
2. Create the query `sql_query("PRAGMA key = ?").bind::<sql_types::Text, _>("secret")`
3. Execute the query `query.execute(&connection)`

## Checklist

- [X ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
There's not much we can do here because sqlite does [not support binds with pragma's. ](http://sqlite.1065341.n5.nabble.com/PRAGMA-doesn-t-support-parameter-binds-td45863.html#a45866)
To make your query work you need to use `format!` or something similar to construct your sql query. Please not that this could lead to possible vulnerable code with user provided input because of sql injections.

**Comment by anler** [comment]
Just my luck haha. Thanks a lot @weiznich, it was driving me crazy :sweat_smile:

**Comment by christian-oudard** [comment]
Another warning: the PRAGMA call returns "ok", so you have to catch the result like this:

```
    let _:Result<String> = conn.query_row("PRAGMA key=password", params![], |row| { row.get(0) });
```
