### ISSUE TITLE
How to statically link sqlite?

### ISSUE THREAD

**Issue by gophobic** [diesel-rs/diesel#2207]
Hello and thanks for he great crate, how to statically link `sqlite` when its feature is enabled? the feature seems to only add `libsqlite3-sys` which in turn needs `bundled` feature to be enabled, when I add `libsqlite3-sys` as a separate dependency in my application `Cargo.toml`. The application can't be built with the error

```bash
error: multiple packages link to native library `sqlite3`, but a native library can be linked only once
```

I have to bundle `sqlite` inside my final binary so please I appreciate any help of how to do this

**Comment by weiznich** [comment]
Please double check that you don't have a duplicated version of `libsqlite3-sys` in your dependency tree. You need to use the same version as diesel. (A cargo update may fix that).
Additionally: The diesel issue tracker is used to track actionable feature requests and bug reports for the diesel team. For questions please use our [gitter channel](https://gitter.im/diesel-rs/diesel) or the [forum](https://discourse.diesel.rs/)
