### ISSUE TITLE
Update major versions of dependencies

### ISSUE THREAD

**Issue by incker** [diesel-rs/diesel#2209]
Hello,
Actually I would like to increase a dependency version of `url` and `dotenv ` crate only, as I have duplicates versions in my `Cargo.lock`. But I have collect also which other dependency could be increased:

**diesel/diesel/Cargo.toml**

    [dependencies]
    url = "2.1.0"
    quickcheck = "0.9.0"
    uuid = "0.8.1"
    [dev-dependencies]
    dotenv = "0.15.0"
    quickcheck = "0.9.0"

**diesel/diesel_cli/Cargo.toml**

    [dependencies]
    dotenv = "0.15.0"
    toml = "0.5.3"
    barrel = "0.6.2"
    libsqlite3-sys = "0.16.0"
    url = "2.1.0"
    [dev-dependencies]
    difference = "2.0.0"
    regex = "1.3.1"
    url = "2.1.0"

**diesel/diesel_migrations/Cargo.toml**

    [dependencies]
    dotenv = "0.15.0"

**diesel/diesel_derives/Cargo.toml**

    [dev-dependencies]
    dotenv = "0.15.0"

**diesel/diesel_tests/Cargo.toml**

    [build-dependencies]
    dotenv = "0.15.0"
    [dependencies]
    dotenv = "0.15.0"

Forward thank you!

**Comment by weiznich** [comment]
Would be great to get PR's updating the dependencies.

**Comment by mh84** [comment]
I can care about this.

**Comment by thedanvail** [comment]
If this hasn't been resolved, I'd like to start on this tonight.

**Comment by vadixidav** [comment]
It seems that `dotenv` is actually breaking right now, making it impossible to run `cargo install diesel_cli`:

```rust
error[E0659]: `error_chain` is ambiguous (derive helper attribute vs any other name)
  --> /home/worleyg/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:35:7
   |
35 |     #[error_chain(foreign)]
   |       ^^^^^^^^^^^ ambiguous name
```

This upgrade should likely be performed soon. I am just getting started with diesel, so I don't know if I can verify it works appropriately after performing the upgrade, but I can open a PR with the version updates today. I will try and get it working right now since I need to install it now.

**Comment by thedanvail** [comment]
Sounds good.

**Comment by vadixidav** [comment]
Actually, I will leave it be. I downloaded the repository locally and got it to build due to the file at https://github.com/diesel-rs/diesel/blob/master/rust-toolchain. It forced the installation of an appropriate Rust version. This is good enough for me currently.

**Comment by weiznich** [comment]
@vadixidav This is probably caused by https://github.com/rust-lang/rust/issues/66508. Which rustc version do you use?

**Comment by vadixidav** [comment]
@weiznich I was a few days behind, but I updated to latest nightly and was still receiving the issue:

worleyg@computer:~/code/psqlcom$ rustc --version
rustc 1.41.0-nightly (5c5b8afd8 2019-11-16)
worleyg@computer:~/code/psqlcom$ cargo install diesel_cli
    Updating crates.io index
  Installing diesel_cli v1.4.0
   Compiling libc v0.2.66
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.11
   Compiling cfg-if v0.1.10
   Compiling pkg-config v0.3.17
   Compiling autocfg v0.1.7
   Compiling getrandom v0.1.13
   Compiling cc v1.0.48
   Compiling bitflags v1.2.1
   Compiling memchr v2.2.1
   Compiling smallvec v1.0.0
   Compiling matches v0.1.8
   Compiling pq-sys v0.4.6
   Compiling byteorder v1.3.2
   Compiling ppv-lite86 v0.2.6
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling percent-encoding v1.0.1
   Compiling rustc-demangle v0.1.16
   Compiling lazy_static v1.4.0
   Compiling ucd-util v0.1.5
   Compiling serde v1.0.104
   Compiling regex v0.2.11
   Compiling unicode-width v0.1.7
   Compiling utf8-ranges v1.0.4
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling remove_dir_all v0.5.2
   Compiling strsim v0.8.0
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.11
   Compiling synom v0.11.3
   Compiling num-traits v0.2.10
   Compiling num-integer v0.1.41
   Compiling c2-chacha v0.2.3
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling textwrap v0.11.0
   Compiling mysqlclient-sys v0.2.4
   Compiling libsqlite3-sys v0.16.0
   Compiling syn v0.11.11
   Compiling idna v0.1.5
   Compiling quote v1.0.2
   Compiling time v0.1.42
   Compiling atty v0.2.13
   Compiling aho-corasick v0.6.10
   Compiling rand_core v0.5.1
   Compiling url v1.7.2
   Compiling clap v2.33.0
   Compiling backtrace-sys v0.1.32
   Compiling rand_chacha v0.2.1
   Compiling rand v0.7.2
   Compiling chrono v0.4.10
   Compiling tempfile v3.1.0
   Compiling backtrace v0.3.40
   Compiling error-chain v0.10.0
   Compiling derive-error-chain v0.10.1
   Compiling diesel_derives v1.4.1
   Compiling serde_derive v1.0.104
   Compiling dotenv v0.10.1
error[E0659]: `error_chain` is ambiguous (derive helper attribute vs any other name)
  --> /home/worleyg/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:27:7
   |
27 |     #[error_chain(custom)]
   |       ^^^^^^^^^^^ ambiguous name
   |
note: `error_chain` could refer to the derive helper attribute defined here
  --> /home/worleyg/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:22:17
   |
22 | #[derive(Debug, error_chain)]
   |                 ^^^^^^^^^^^
note: `error_chain` could also refer to the derive macro imported here
  --> /home/worleyg/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:10:1
   |
10 | #[macro_use]
   | ^^^^^^^^^^^^

**Comment by vadixidav** [comment]
@weiznich Actually, it looks like in the above I messed up and was using the wrong version. I set my default toolchain to current nightly in rustup.

**Comment by weiznich** [comment]
So this was caused by a old nightly affected by that bug? If it happens at a newer nightly, please open a bugreport at the rustc repo linking the issue mentioned above.

**Comment by thedanvail** [comment]
This issue is really showing me how much I don't understand about Cargo.toml

**Comment by giganteous** [comment]
Chiming in as I'd like to see dotenv moved to 0.15. It fixes a bug in parsing env vars that contain newlines. It silently stops parsing, and I had my DATABASE_URL at the bottom. I fixed it by reordering, but I'm sure others might or will be bitten by this.

It is currently pinned on ``dotenv = ">=0.8, <0.11"``.

Will this issue be picked up or closed? I can file a separate issue for my problem with dotenv < 0.15.

**Comment by weiznich** [comment]
@giganteous See #2223.

**Comment by incker** [comment]
I think I will close this issue to make some clean up.
As it already 4 month passed and issue is partial solved..

If you think that issue is still actual - better make new one with fresh dependency request.
Forward thank you!
