### ISSUE TITLE
migrations: allow backend specific steps

### ISSUE THREAD

**Issue by ensc** [diesel-rs/diesel#2220]
### Versions

- **Diesel:** 1.4.0

### Feature Flags

- **diesel:**  `sqlite` xor `postgres`

## Problem Description

The SQL in the migration steps depends usually on the databaes backend.  E.g. `diesel-cli` itself creates an initial `up` step with

```sql
CREATE OR REPLACE FUNCTION diesel_manage_updated_at(_tbl regclass) RETURNS VOID AS $$
```

which works only with postgresql but fails with sqlite..

Using alternate migration diractories might be a way to fix this but it means that large parts of migration code must be replicated across the backends.

It would be nice to disable/enable execution of steps depending on the used backend.

In-SQL statements like

```sql
-- #[begin(postgres)]
CREATE OR REPLACE FUNCTION diesel_manage_updated_at(_tbl regclass) RETURNS VOID AS $$
-- #[end(postgres)]
```

to selectively enable sql blocks might be the perfect solution but are probably not easy to implement.

Instead of, I suggest backend specific filenames like

```
up-sqlite.sql
up-pgsql.sql
down-pgsql.sql
```

When such a file exists it is preferred over the generic `up.sql` resp. `down.sql`

So, you can share large parts of the migration between the backends and move only the specific parts into separate steps.

**Comment by weiznich** [comment]
We see migrations as something highly backend specific. Sharing a migration between different backends is in my opinion an anti pattern and does generally not work well as soon as you use some more specific data types. 
If you want to use something that abstract migrations over different backends I think barrel supports that. It has some integration with diesel as far as I'm aware.
