### ISSUE TITLE
Support generate expended version of 'table!' for ide

### ISSUE THREAD

**Issue by s97712** [diesel-rs/diesel#2237]
Ide cannot analyze the `table!` macro, can provide some option for `# diesel migration` that generates the expanded `table!` version for ide?

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
That's a bug in your ide, not in diesel. Raise that issue there. 
Generating such a "expanded" variant would greatly decrease usability for nearly all users, so that's not an option for me.
