### ISSUE TITLE
diesel_cli should warn when creating empty migrations

### ISSUE THREAD

**Issue by dns2utf8** [diesel-rs/diesel#2244]
I noticed that diesel_cli generated empty migrations.
It took my a while to realize the error because the command returned successfully.

### Versions

- **Rust:** rustc 1.39.0 (4560ea788 2019-11-04)
- **Diesel:** 1.4.0
- **Database:** sqlite
- **Operating System** Kubuntu (Linux 5.3.0-24-generic)

### Feature Flags

- **diesel:** sqlite

### What are you trying to accomplish?

Generate table migrations.

### What is the expected output?

```bash
$ diesel migration generate create_reports_table
Error: empty migration
```

### What is the actual output?

```bash
$ diesel migration generate create_reports_table
Creating migrations/2019-12-16-194937_create_reports_table/up.sql
Creating migrations/2019-12-16-194937_create_reports_table/down.sql
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by dns2utf8** [comment]
Do I assume correctly that the generate function is not implemented yet?

https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/main.rs#L170-L179

Or do I need to enable a specific feature?

**Comment by weiznich** [comment]
Everything there work as expected. Diesel will not generate any SQL there for new migrations. This command is only used to create a template for you to write the actual migrations. Generating actual SQL there is not in scope for diesel.
