### ISSUE TITLE
Suport for ARRAY[][] in migration

### ISSUE THREAD

**Issue by stfl** [diesel-rs/diesel#2249]
### Versions

- **Rust: 1.40.0-nightly**
- **Diesel: 1.4.0**
- **Database: postgres 12**
- **Operating System: Linux**

### Feature Flags

- **diesel: ["postgres"] **

## Problem Description

I am using a multidimentional array as a column in postgres

`up.sql`
```sql
CREATE TABLE ... (
...
inputs FLOAT4[][] NOT NULL,
...
);
```

### What is the expected output?

I'd like to have the output in `src/schema.rs` to be

```
inputs -> Array<Array<Float4>>,
```

in order to use it with a struct member of `inputs: Vec<Vec<f32>>`

### What is the actual output?

```
inputs -> Array<Float4>,
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
`float4[][]` is not a unique type. It is identical to `float4[]`. There is no way we could distinguish this.

```plain
[local] sean@sean=# create table foo (id integer, bar int[][]);
Time: 13.531 ms
[local] sean@sean=# \d+ foo;
                                     Table "public.foo"
 Column |   Type    | Collation | Nullable | Default | Storage  | Stats target | Description
--------+-----------+-----------+----------+---------+----------+--------------+-------------
 id     | integer   |           |          |         | plain    |              |
 bar    | integer[] |           |          |         | extended |              |
```

**Comment by stfl** [comment]
I see. Thanks for looking into this.
Although, [PostgreSQL: Documentation: 12: 8.15. Arrays](https://www.postgresql.org/docs/12/arrays.html) states it differently. I wonder how it is implemented then?!

**Comment by sgrif** [comment]
The number of dimensions is sent at runtime. The docs clearly state that it does not keep track of any dimension or size information you give it.

> However, the current implementation ignores any supplied array size limits, i.e., the behavior is the same as for arrays of unspecified length.

> The current implementation does not enforce the declared number of dimensions either. Arrays of a particular element type are all considered to be of the same type, regardless of size or number of dimensions. So, declaring the array size or number of dimensions in CREATE TABLE is simply documentation; it does not affect run-time behavior.

**Comment by stfl** [comment]
Apperently I haven't fully read the doc. Thanks for pointing this out again.
