### ISSUE TITLE
Add to_sql_with to Insertable derive and from_sql_with to Queryable derive

### ISSUE THREAD

**Issue by vadixidav** [diesel-rs/diesel#2250]
In `serde` there is a field attribute called [`serialize_with`](https://serde.rs/field-attrs.html#serialize_with). This lets you control the process of serialization. Additionally, there is [`deserialize_with`](https://serde.rs/field-attrs.html#deserialize_with) which does the opposite: it lets you control the process of deserialization.

In `diesel`, I currently have the following situation:

```rust
#[derive(Queryable)]
pub struct MyType {
    id: i32,
    data_timestamp: DateTime<Utc>,
}

#[derive(Insertable)]
#[table_name = "tablename"]
pub struct NewMyType {
    data_timestamp: DateTime<Utc>,
}
```

The above code will not actually work. The reason being is that Diesel only implements `Insertable` and `FromSql` for `chrono::NaiveDateTime`. This is reasonable, since it is up to us to determine the timezone of the timestamp. However, I do not want the timestamp to ever be passed around as a `chrono::NaiveDateTime`, since local time and utc time could easily get messed up. Ideally, I would like to write an annotation to tell `diesel` how to transform the `DateTime<Utc>` to `NaiveDateTime` at the time of insertion and vice-versa at the time of querying.

The temporary solution for me is to have two types: one with data in the type that interfaces with the database and one with the data that is in the type-safe format. This leads to more duplication of code. The above example demonstrates that, at least with timestamps, the code duplication could be avoided.

My recommended solution is to have something like the following:

```rust
#[derive(Queryable)]
pub struct MyType {
    id: i32,
    #[diesel(from_sql_with = Utc::from_utc_datetime)]
    data_timestamp: DateTime<Utc>,
}

#[derive(Insertable)]
#[table_name = "tablename"]
pub struct NewMyType {
    #[diesel(to_sql_with = DateTime::<Utc>::naive_utc)]
    data_timestamp: DateTime<Utc>,
}
```

This syntax would let you pass a function to transform the item before or after the query. `from_sql_with` will let you convert a type into the type in the struct you get back from the query. `to_sql_with` will let you convert a type that is to be added to a query to a different type first. There may be better ways of achieving the same effect, but this seems simple to me, and other methods can be added later with different syntax.

The only caveat I can think of is that procedural macros may not be able to determine what the argument and return type are of the function passed. We can get around that by just making the unknown type explicit by adding some extra syntax such as `#[diesel(to_sql_with = DateTime::<Utc>::naive_utc -> NaiveDateTime)]`.

**Comment by vadixidav** [comment]
Another problem that I noticed is that when you use [`load`](https://docs.diesel.rs/diesel/query_dsl/trait.RunQueryDsl.html#method.load), you have to load it as one vector and then create a new vector to move the data to. This results in double the number of allocations. This could be improved by adding something like `load_map`, but this ticket's proposed solution would also solve that problem.

**Comment by weiznich** [comment]
It's not as simple with serdes `deserialize_with`/`serialize_with`, because there happens a bit more in `Queryable` and `Insertable` (or better: We don't have as much information there as you thing).
That said: 
* For loading values the documentation [lists](http://docs.diesel.rs/diesel/deserialize/trait.Queryable.html#examples) multiple examples how to customize the behaviour.
* For insert: Don't use a struct implementing `Insertable` here, use a tuple inserts. So something like:
```rust
#[derive(Insertable)]
#[table_name = "tablename"]
pub struct InnerMyType {
   other_field: i32,
}

pub struct NewMyType {
    data_timestamp: DateTime<Utc>,
    other: InnerMyType
}

fn insert_something(data: NewMyType, conn: &PgConnection) {
    diesel::insert_into(tablename::table)
        .values((
             data.other,
             tablename::date_timestamp.eq(data.datetimestamp.naive_utc()),
         )).execute(&conn);
} 
```

> Another problem that I noticed is that when you use load, you have to load it as one vector and then create a new vector to move the data to. This results in double the number of allocations. This could be improved by adding something like load_map, but this ticket's proposed solution would also solve that problem.

I don't think that's a problem in practice, because a database call has a cost some magnitudes higher than one or two allocations. Or to word it in a other way: The time of doing a allocation more is probably inside the noise level of the time required to do a database call.
