### ISSUE TITLE
BoxableExpression for expressions including multiple tables?

### ISSUE THREAD

**Issue by netvl** [diesel-rs/diesel#2259]
I need to dynamically construct an expression which refers columns in different tables, specifically, to do something like
```sql
SELECT *
FROM table1
WHERE EXISTS(
  SELECT *
  FROM table2
  WHERE table2.field = table1.field AND whatever
)
```
This condition in the nested WHERE is supposed to be dynamic, depending on the user input. Unfortunately, `BoxableExpression` requires the implementing expression to be `SelectableExpression`, which effectively requires it to reference only a single table.

What is the suggested way to do this? Unfortunately, the queries in my case are rather complex, and I'd like not to fall back to `into_boxed()` on the queries level.

**Comment by netvl** [comment]
Interesting - it seems that omitting the first argument for `BoxedExpression` allows the compiler to infer something there, which makes my code compile! I guess the issue can be closed then, since it actually does work, but I'm curious what type is actually used there - it does not look like that the usual "assign to wrong type" trick works here:
```
error[E0277]: the trait bound `db::schema::chats::columns::id: diesel::SelectableExpression<()>` is not satisfied
   --> src/db/analyses.rs:139:13
    |
139 |             Box::new(chats::id.eq(analysis_chats::chat_id));
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `diesel::SelectableExpression<()>` is not implemented for `db::schema::chats::columns::id`
```

**Comment by weiznich** [comment]
You normally don't need to name a concrete type there. If you really need to name a type there, something like 
```rust
BoxableExpression<
                diesel::dsl::InnerJoin<table1::table, table2::table>,
                diesel::pg::Pg,
                SqlType = diesel::sql_types::Bool,
            >,
```

should work there.
