### ISSUE TITLE
can not install diesel_cli

### ISSUE THREAD

**Issue by skytraveler** [diesel-rs/diesel#2262]
I am using windows subsystem for linux and ubuntu 18.04 
I have installed mysql

mysqld --version
mysqld  Ver 5.7.28-0ubuntu0.18.04.4 for Linux on x86_64 ((Ubuntu))

cargo install diesel_cli --no-default-features --features mysql
Updating crates.io index
Installing diesel_cli v1.4.0
Compiling libc v0.2.66
Compiling proc-macro2 v1.0.6
Compiling unicode-xid v0.2.0
Compiling syn v1.0.11
Compiling cfg-if v0.1.10
Compiling autocfg v0.1.7
Compiling getrandom v0.1.13
Compiling cc v1.0.48
Compiling matches v0.1.8
Compiling pkg-config v0.3.17
Compiling memchr v2.2.1
Compiling smallvec v1.1.0
Compiling byteorder v1.3.2
Compiling ppv-lite86 v0.2.6
Compiling unicode-xid v0.0.4
Compiling quote v0.3.15
Compiling rustc-demangle v0.1.16
Compiling ucd-util v0.1.5
Compiling bitflags v1.2.1
Compiling serde v1.0.104
Compiling lazy_static v1.4.0
Compiling percent-encoding v1.0.1
Compiling regex v0.2.11
Compiling utf8-ranges v1.0.4
Compiling unicode-width v0.1.7
Compiling strsim v0.8.0
Compiling ansi_term v0.11.0
Compiling remove_dir_all v0.5.2
Compiling vec_map v0.8.1
Compiling unicode-bidi v0.3.4
Compiling unicode-normalization v0.1.11
Compiling synom v0.11.3
Compiling num-traits v0.2.10
Compiling num-integer v0.1.41
Compiling regex-syntax v0.5.6
Compiling c2-chacha v0.2.3
Compiling thread_local v0.3.6
Compiling mysqlclient-sys v0.2.4
Compiling textwrap v0.11.0
Compiling syn v0.11.11
Compiling idna v0.1.5
Compiling quote v1.0.2
Compiling time v0.1.42
Compiling atty v0.2.13
Compiling aho-corasick v0.6.10
Compiling backtrace-sys v0.1.32
Compiling url v1.7.2
Compiling rand_core v0.5.1
Compiling clap v2.33.0
Compiling rand_chacha v0.2.1
Compiling chrono v0.4.10
Compiling rand v0.7.2
Compiling backtrace v0.3.40
Compiling error-chain v0.10.0
Compiling tempfile v3.1.0
Compiling derive-error-chain v0.10.1
Compiling serde_derive v1.0.104
Compiling diesel_derives v1.4.1
Compiling dotenv v0.10.1
Compiling diesel v1.4.3
Compiling migrations_internals v1.4.0
Compiling toml v0.4.10
Compiling diesel_cli v1.4.0
error: linking with cc failed: exit code: 1
|
= note: "cc" "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.0.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.1.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.10.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.11.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.12.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.13.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.14.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.15.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.2.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.3.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.4.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.5.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.6.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.7.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.8.rcgu.o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.diesel.22v69qy5-cgu.9.rcgu.o" "-o" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd" "/tmp/cargo-installeR5eQP/release/deps/diesel-cf170451c2ef5dbd.1xwtd4qg16lxzs4h.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-installeR5eQP/release/deps" "-L" "/tmp/cargo-installeR5eQP/release/build/backtrace-sys-1a6aebb71cfa0dd5/out" "-L" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installeR5eQP/release/deps/libtoml-a800970f0460bb56.rlib" "/tmp/cargo-installeR5eQP/release/deps/libtempfile-9ec52111a42045c6.rlib" "/tmp/cargo-installeR5eQP/release/deps/librand-2e218f9dd22fd69d.rlib" "/tmp/cargo-installeR5eQP/release/deps/librand_chacha-5de6e76f777a428a.rlib" "/tmp/cargo-installeR5eQP/release/deps/libc2_chacha-ef44b2631c00a7ab.rlib" "/tmp/cargo-installeR5eQP/release/deps/libppv_lite86-602040b3513c5a3c.rlib" "/tmp/cargo-installeR5eQP/release/deps/librand_core-91c49ba4e7a64dd7.rlib" "/tmp/cargo-installeR5eQP/release/deps/libgetrandom-9319bb17a7920a37.rlib" "/tmp/cargo-installeR5eQP/release/deps/libremove_dir_all-db34d75216f65548.rlib" "/tmp/cargo-installeR5eQP/release/deps/libserde-05c09b7abcc0d989.rlib" "/tmp/cargo-installeR5eQP/release/deps/libmigrations_internals-f3bc3658bbb9940c.rlib" "/tmp/cargo-installeR5eQP/release/deps/libdotenv-e3075da9ac0617fc.rlib" "/tmp/cargo-installeR5eQP/release/deps/libregex-350ab771a70383f9.rlib" "/tmp/cargo-installeR5eQP/release/deps/libutf8_ranges-e690882cacf84307.rlib" "/tmp/cargo-installeR5eQP/release/deps/libregex_syntax-34b64173b6667055.rlib" "/tmp/cargo-installeR5eQP/release/deps/libucd_util-01623b26644180cc.rlib" "/tmp/cargo-installeR5eQP/release/deps/libthread_local-c268d604cfb06141.rlib" "/tmp/cargo-installeR5eQP/release/deps/liblazy_static-1ac663810698d57a.rlib" "/tmp/cargo-installeR5eQP/release/deps/libaho_corasick-984b4d57ae0fefd7.rlib" "/tmp/cargo-installeR5eQP/release/deps/libmemchr-136b150cf6925c95.rlib" "/tmp/cargo-installeR5eQP/release/deps/liberror_chain-9bd558f7a62a40b3.rlib" "/tmp/cargo-installeR5eQP/release/deps/libbacktrace-91cf28befe9f6d5d.rlib" "/tmp/cargo-installeR5eQP/release/deps/libbacktrace_sys-7195791faaf7b005.rlib" "/tmp/cargo-installeR5eQP/release/deps/libcfg_if-5de741bf7bde9e6a.rlib" "/tmp/cargo-installeR5eQP/release/deps/librustc_demangle-62820fb8deb2a001.rlib" "/tmp/cargo-installeR5eQP/release/deps/libdiesel-81342a017dcafb23.rlib" "/tmp/cargo-installeR5eQP/release/deps/liburl-d4e1be91150a08b1.rlib" "/tmp/cargo-installeR5eQP/release/deps/libpercent_encoding-72df33845894a95a.rlib" "/tmp/cargo-installeR5eQP/release/deps/libidna-ca7b9a76b45716d6.rlib" "/tmp/cargo-installeR5eQP/release/deps/libunicode_normalization-4194c2fb94eee8c4.rlib" "/tmp/cargo-installeR5eQP/release/deps/libsmallvec-f0ca9a777b264e9f.rlib" "/tmp/cargo-installeR5eQP/release/deps/libunicode_bidi-46e3531e5060d8f7.rlib" "/tmp/cargo-installeR5eQP/release/deps/libmatches-2fd616810e598c9e.rlib" "/tmp/cargo-installeR5eQP/release/deps/libmysqlclient_sys-c8071e18de276760.rlib" "/tmp/cargo-installeR5eQP/release/deps/libbyteorder-822f0bec1d1244d2.rlib" "/tmp/cargo-installeR5eQP/release/deps/libclap-a4af8b963c8a87b2.rlib" "/tmp/cargo-installeR5eQP/release/deps/libvec_map-f7ba0085f2e7f035.rlib" "/tmp/cargo-installeR5eQP/release/deps/libtextwrap-5e7fa01993c06ef1.rlib" "/tmp/cargo-installeR5eQP/release/deps/libunicode_width-0330de2489ea4b3a.rlib" "/tmp/cargo-installeR5eQP/release/deps/libstrsim-1fab5f7ae35164ec.rlib" "/tmp/cargo-installeR5eQP/release/deps/libbitflags-afbaad57ee28944c.rlib" "/tmp/cargo-installeR5eQP/release/deps/libatty-76d33be42c407b3f.rlib" "/tmp/cargo-installeR5eQP/release/deps/libansi_term-6218860094e4ddd4.rlib" "/tmp/cargo-installeR5eQP/release/deps/libchrono-b76b6b9259a739a1.rlib" "/tmp/cargo-installeR5eQP/release/deps/libnum_integer-c9edda593bac1d18.rlib" "/tmp/cargo-installeR5eQP/release/deps/libnum_traits-b5b910a2652d0fd2.rlib" "/tmp/cargo-installeR5eQP/release/deps/libtime-8633d2c15e27ba0e.rlib" "/tmp/cargo-installeR5eQP/release/deps/liblibc-a3ed7ca3b18df2bb.rlib" "-Wl,--start-group" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-2fc6a82edb153902.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-630ffed2e1e07834.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-6446f16272645d47.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c550137bccb49271.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-8d757937eefa93aa.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-ba2042c8604ab098.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-19d7694f60b13fbe.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-2815c8c5f2634a4c.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-bc891fb57b0491f5.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-16b7a4b505309b50.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-cd257d77e471adf0.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-f42d2447425df771.rlib" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-b595534e124234fd.rlib" "-Wl,--end-group" "/home/lucas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-e5bbafde7b1e8c46.rlib" "-Wl,-Bdynamic" "-lmysqlclient" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
= note: /usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: failed to compile diesel_cli v1.4.0, intermediate artifacts can be found at /tmp/cargo-installeR5eQP

Caused by:
could not compile diesel_cli.

To learn more, run the command again with --verbose.

**Comment by shirshak55** [comment]
have u installed visual studio stuff?

**Comment by skytraveler** [comment]
> have u installed visual studio stuff?
yes, I have vscode insider version installed. dose it matter?

**Comment by shirshak55** [comment]
Sorry i thought its windows but u are running via wsl ubuntu. Did u installed build dependencies etc on ubuntu? Can u compile other project not just diesel? I think its a general issue not diesel one tho.

**Comment by weiznich** [comment]
@skytraveler You need to install libmysqlclient. Depending on your operating system and enviroment you may need to set a environment variable to have the linker looking at the right place for this library. See the documentation/Readme of `mysqlclient_sys` for more details.

**Comment by skytraveler** [comment]
thanks you @weiznich

**Comment by ravirajb** [comment]
But why's the installation of mysql is necessary, when I run the diesel_cli only for sqlite in MacOS?

**Comment by shirshak55** [comment]
@ravirajb because he might have choosed mysql in features section at Cargo.toml. Installation of mysql is not needed if you are not using mysql.
