### ISSUE TITLE
Unable to install diesel for use with sqlite

### ISSUE THREAD

**Issue by MrTanoshii** [diesel-rs/diesel#2264]
### Versions

- **Rust:** rustc 1.40.0 (73528e339 2019-12-16)
- **Diesel:** N/A
- **Database:** SQLite version 3.30.1 2019-10-10 20:19:45
- **Operating System** Windows 10 Home 64x build 1909

## Problem Description
Unable to install diesel with sqlite feature

### What are you trying to accomplish?
I am attempting to install diesel with the sqlite feature using the following command `cargo install diesel --no-default-features --features sqlite` (I've also tried `cargo install diesel_cli` unsuccessfully because I do not have mysql and other packages)

### What is the actual output?
`error: specified package `diesel v1.4.3` has no binaries`

### Steps to reproduce
Note: I am new to rust so everything is a fresh install

- Installed rust using the windows installer
- SQLite dll and tools downloaded from https://www.sqlite.org/download.html, extracted and PATH variable added
- Install diesel using `cargo install diesel --no-default-features --features sqlite`

## Cargo.toml dependencies

[dependencies]
diesel = { version = "1.4.3", features = ["sqlite"] }
dotenv = "0.15.0"

Note: On an interesting note, I am able to cargo build my empty project with no problems at all and the build log even indicates a successful `Compiling diesel v1.4.3`

**Comment by weiznich** [comment]
As the [getting started guide](https://diesel.rs/guides/getting-started/) notes you to install `diesel_cli`, while your crate should depend on `diesel`. So this is expected behaviour.

For errors about mysql and other packages: Try disabling the default features and only enable the sqlite feature.
