### ISSUE TITLE
clarify `eq_any' cache penalties for subqueries

### ISSUE THREAD

**Issue by ensc** [diesel-rs/diesel#2266]
### Versions

- **Diesel:**  1.4.3

## Problem Description

[Documentation](https://docs.diesel.rs/diesel/expression_methods/trait.ExpressionMethods.html#method.eq_any) states

> ```rust
> fn eq_any<T>(self, values: T) -> In<Self, T::InExpression> 
> ```
> Queries using this method will not be placed in the prepared statement cache

But [comments](https://github.com/diesel-rs/diesel/blob/master/diesel/src/connection/statement_cache.rs#L31) in the code say

```rust
//!     - `IN` with subselects are cached (assuming the subselect is safe to
//!        cache)
```

Will queries like

```rust
some_dsl::attr.eq_any(other_table.select(other_dsl::id)))
```

be cached?  If so, the documentation mentioned fist should be updated.

**Comment by weiznich** [comment]
Queries containing an `eq_any` with a subquery use the prepared statement cache, but only if the there is nothing else in the query that prevents using the statement cache.

If someone touches the documentation, it should probably be updated to mention that you could also pass a subquery in the first place 🙈

**Comment by smtaylorslc** [comment]
Hey @weiznich, I know this is pretty old but if it's still open I'd be happy to take a stab at it.

**Comment by weiznich** [comment]
@smtaylorslc It's still open, so feel free to open a PR.
