### ISSUE TITLE
Feature request: derive Default of the table struct

### ISSUE THREAD

**Issue by lispc** [diesel-rs/diesel#2282]
I have a struct using table as generic type parameters. Inside the struct method, values are inserted into database like this:

```
let table: Tab = ??;
diesel::insert_into(table).values(entries).execute(&conn);
```

`table` here is the table struct [defined here](https://github.com/diesel-rs/diesel/blob/master/diesel/src/macros/mod.rs#L657) . It is difficult to get a instance object from the unit struct type.

My current solution is 

```
let table: Tab = unsafe { (*(0 as *const Tab)).clone() }; 
```

If [Default] is derived on the table struct, it will be much easier like this:

```
let table: Tab = Tab::default();
```

If you think this modification is ok, I can make a PR.

**Comment by weiznich** [comment]
There is already [`diesel::associations::HasTable`](http://docs.diesel.rs/diesel/associations/trait.HasTable.html) to construct table there. Having a `Default` impl for the generated structs is probably fine, so if you have time please open a PR.
