### ISSUE TITLE
Can't run `diesel_migrations` without SQLite / MySQL support

### ISSUE THREAD

**Issue by Razican** [diesel-rs/diesel#2288]
### Versions

- **Rust:** rustc 1.42.0-nightly (f43c34a13 2020-02-02)
- **Diesel:** 1.4.3 (from https://github.com/GiGainfosystems/diesel/tree/feature/dynamic_queries)
- **Database:** postgres (PostgreSQL) 11.6
- **Operating System:** Fedora release 31 (Thirty One)

### Feature Flags

- **diesel:** `["postgres", "chrono", "uuid", "numeric", "network-address", "serde_json"]`
- **diesel_migrations:** `["postgres"]`

### What are you trying to accomplish?

I'm trying to dynamically apply migrations on a database when the program launches. The schema is dynamic, and would like to be able to update it with a new release.

### What is the expected output?

The program compiles normally.

### What is the actual output?

I get an error when compiling `diesel_migrations`:
```
  = note: /usr/bin/ld: cannot find -lsqlite3
          /usr/bin/ld: cannot find -lmysqlclient
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `migrations_macros`.
```

### Are you seeing any additional errors?

Not for now

### Steps to reproduce

 - In a GitHub Action, install `libpq-dev` to work with PostgreSql.
 - Build the binary.
 - `diesel_migrations` won't build since it requires SQLite and MySQL development libraries, even if only the `postgres` feature is selected.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Our CI says [that this](https://github.com/diesel-rs/diesel/issues/2288?email_source=notifications&email_token=AAMY2EECKH4IH5U47UZGYBLRBFCCHA5CNFSM4KPUWCL2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IK3MOAQ) works fine. 

You must have something different in your `Cargo.toml` that enables the `sqlite` and `mysql` feature for diesel. 

(Closed because I cannot reproduce this with diesel master)

**Comment by Razican** [comment]
Can confirm, this was related to `diesel-dynamic-schema` now having all backends as default after [this][commit] commit. I would suggest following `diesel`'s approach of selecting the backend you want, without any default :)

[commit]: https://github.com/GiGainfosystems/diesel-dynamic-schema/commit/cf69bb9054c935ab362e0198bd45e21b4205b83a
