### ISSUE TITLE
Feature request: The equivalent of `print-schema` as a library

### ISSUE THREAD

**Issue by NilsIrl** [diesel-rs/diesel#2300]
Possibly inside of `disel_migration`, allow the user to retrieve the schema. I don't have a clear idea of what the API would look like though.

Use case: allow `disel_migration` to be used as `diesel migration run`.

**Comment by weiznich** [comment]
Could you elaborate how you would use such an API? Without that this is not actionable and will be closed in a few days.

**Comment by NilsIrl** [comment]
The use case would be to generate `schema.rs` at compile time.

**Comment by weiznich** [comment]
See https://crates.io/crates/diesel_infer_schema.

**Comment by NilsIrl** [comment]
It's deprecated :(.

If a PR was to be submitted, would it be accepted?

**Comment by weiznich** [comment]
See https://github.com/diesel-rs/diesel/pull/1720/commits/7dcd9a365ce0e45c85cd6c2437fb7d1631f50fd5 for information why it was removed. I do not see any reason to change this decision as the existing `diesel_infer_schema` version continues to work. If there is a real need for this it is always possible to provide  this functionality as third party crate.
