### ISSUE TITLE
Could we factor out some of the cli functionality into a library?

### ISSUE THREAD

**Issue by gilescope** [diesel-rs/diesel#2301]
The diesel cli is great. We're wondering if we could code against that functionality directly rather than having to call out to the process? - is it possible that the cli could just deal with the arguments so that the rest is accessible programatically from a lib as well as via the cli? Is this a direction you'd be comfortable heading in? / Would you accept a PR to that effect?

**Comment by weiznich** [comment]
Could you please add more concrete information on what you exactly want to extract from diesel cli? Otherwise this issue is not actionable for us and will be closed soon.

**Comment by gilescope** [comment]
Any code in a binary is effectively private and not callable from another rust library. I think this really is a flaw in rust - dotnet had the same when it started out in life and then they made EXEs callable from libraries and there was much rejoicing. I'll close this and try and get rust fixed instead.
