### ISSUE TITLE
Add support for `CURRENT_DATE`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#2307]
Given that we support `CURRENT_TIMESTAMP`, the lack of `CURRENT_DATE` feels like an omission. While you can hack it with `date(now)`, I keep finding myself wishing there was a direct way to reference this. Given that `now` means `CURRENT_TIMESTAMP`, I think there's precedent for `today` meaning `CURRENT_DATE`. This is supported by all backends we support (and is in the ISO standard I believe).

The code for `now` can be pretty much directly re-used for this

**Comment by Darth-Revan** [comment]
Seems to be a reasonable addition to the API. I'd like to give it shot. I already looked into the code of `now` and it should be quite easy to adapt it.

**Comment by weiznich** [comment]
Sure go. If there is anything unclear feel free to ping me on gitter or here.

**Comment by Darth-Revan** [comment]
An implementation of `today` has been added in #2317

**Comment by TaKO8Ki** [comment]
@weiznich @Darth-Revan 
Can I take over this PR #2317?

**Comment by weiznich** [comment]
@TaKO8Ki Sure
