### ISSUE TITLE
DebugQuery is panicking on output if changeset contains None values for required fields in schema

### ISSUE THREAD

**Issue by Roxe322** [diesel-rs/diesel#2308]
### Versions

- **Rust:** rustc 1.41.0 (5e1a79984 2020-01-27)
- **Diesel:** diesel = { version = "1.4", features = ["postgres", "r2d2", "serde_json", "chrono"] }
- **Database:** Postgres
- **Operating System** MacOS

### Feature Flags

- **diesel:** ["postgres", "r2d2", "serde_json", "chrono"]

## Problem Description
So, I have a table described with such schema:
```
table! {
    resources(id) {
        id -> Int4,
        status -> Int2,
        fetch_url -> Varchar,
    }
}
```
I also have a Changeset: 
```
#[derive(AsChangeset)]
#[table_name = "resources"]
pub struct ResourceChangeset {
    pub fetch_url: Option<String>,
    pub status: Option<i16>
}
```
So when I try to println! or dbg! such query, it makes panic
```
let query: UpdateStatement<_, _, _> = diesel::update(
    resources::table
        .filter(resources::id.eq(1))
)
.set(ResourceChangeset {
    fetch_url: None,
    status: None
});
let sql = debug_query::<Pg, _>(&query);
println!("{}", sql);
```
### What are you trying to accomplish?
I want debug_query to be output properly.

### What is the expected output?
I don't really know

### What is the actual output?
https://gist.github.com/Roxe322/fc337197e467d9cbe2c4b1c33a3d676e

### Are you seeing any additional errors?
No, only that above

### Steps to reproduce
 I think, you need:

1. Schema with not null fields
2. Changeset with optional fields for that schema
3. Try to provide update with None s in changeset

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
As this does not generate any query at all I'm not sure what behaviour we would expect here. Panicking is probably a valid option here.
