### ISSUE TITLE
Add `DatabaseErrorKind` variants for connection errors

### ISSUE THREAD

**Issue by LLFourn** [diesel-rs/diesel#2322]
On 1.4.3, if you lose your connection to a postgres database and try to make a query you will get:

```
Err(
    DatabaseError(
        __Unknown,
        "server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n",
    ),
)
```

or

```
Err(
    DatabaseError(
        UnableToSendCommand,
        "no connection to the server\n",
    ),
)
```

For obvious reasons, It would be useful to be able to identify a bad connection.

**Comment by weiznich** [comment]
We are happy to accept a PR adding this error variant

**Comment by henryboisdequin** [comment]
I would like to work on this issue.

**Comment by weiznich** [comment]
@henryboisdequin Feel free to go for it :+1:

**Comment by weiznich** [comment]
@henryboisdequin Feel free to go for it :+1:

**Comment by hi-rustin** [comment]
@weiznich @LLFourn How can I reproduce this problem? Because I want to determine the error code of it. Can you help me with the steps to reproduce it?

**Comment by weiznich** [comment]
@hi-rustin I think one way to reproduce the problem is to kill/stop the postgres server while some query is running. That's probably something that's not that easy to time, though.

**Comment by hi-rustin** [comment]
> @hi-rustin I think one way to reproduce the problem is to kill/stop the postgres server while some query is running. That's probably something that's not that easy to time, though.

This results in the following error: [08006] An I/O error occurred while sending to the backend.

**Comment by LLFourn** [comment]
> 
> 
> @hi-rustin I think one way to reproduce the problem is to kill/stop the postgres server while some query is running. That's probably something that's not that easy to time, though.

I was stopping the server after a connection was established and then try and make a query which is easy to do. Doing it during a query might also yield a different error code.

**Comment by hi-rustin** [comment]
@weiznich I reproduced the issue locally, but the error does not have ResultField::SqlState, maybe we need to match the message to add the error variant?

**Comment by weiznich** [comment]
@hi-rustin Matching the error message is a possible solution, but only as long as the error message remains stable over various postgres versions.

**Comment by hi-rustin** [comment]
> @hi-rustin Matching the error message is a possible solution, but only as long as the error message remains stable over various postgres versions.

I'll check tomorrow. Thanks for your reply!

**Comment by hi-rustin** [comment]
Tested 13.4, 12.8, 11.13, 10.18, 9.6, all with the same error.
