### ISSUE TITLE
[diesel_migrations documentation] brocken link to embed_migrations

### ISSUE THREAD

**Issue by p-alik** [diesel-rs/diesel#2324]
https://github.com/diesel-rs/diesel/blob/18d8de31953c071cd97a6ccf2b3749a1e082b09a/diesel_migrations/migrations_internals/src/lib.rs#L44

The aforementioned link in markdown produces https://docs.rs/crate/diesel_migrations/macro.embed_migrations.html. See  [diesel_migrations](https://docs.rs/crate/diesel_migrations/1.4.0).

Correct target is https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html

**Comment by weiznich** [comment]
The problem there is if we change the link as suggested it will break [here](https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/) (and any other place that hosts the documentation). This seems to be a fundamental issue with docs.rs. As we are not maintaining that service I do not see how to fix that.

**Comment by p-alik** [comment]
rust-lang/docs.rs/issues/204 seems to be issue you mentioned. According to this [comment](https://github.com/rust-lang/docs.rs/issues/204#issuecomment-454090352) there is no appropriate solution available yet. The only absolute link. Wouldn't it be an option?

**Comment by weiznich** [comment]
An absolute link is not an appropriate because that would "break" the link anywhere else that is not docs.rs. (For example on the diesel website.)

Closed because this is not actionable, due to https://github.com/rust-lang/docs.rs/issues/204
