### ISSUE TITLE
Feature request: Support for dynamic set operations

### ISSUE THREAD

**Issue by urkle** [diesel-rs/diesel#2327]
Currently I have found information about .into_boxed() which allows a dynamic "where" clause.  However I have not found any equivalent to do so with the "set" clause of an update statement.

It would be nice to not be required to know exactly which fields I am going to update by to have some flexibility to it. e.g.

```rust
let mut query = diesel::update(my_table.filter(my_table::id.eq(input.id))).into_set_boxed();

if input.duration.is_some() {
    query = query.add_set(my_table.duration.eq(input.duration.unwrap());
}

if input.name.is_some() {
    query = query.add_set(my_table.name.eq(input.name.unwrap());
}

if query.is_set() {
    query.execute(&connection);
} else {
    // nothing was set
}

```

**Comment by weiznich** [comment]
That's already supported by types implementing/deriving `AsChangeset`. See the [corresponding guide](https://diesel.rs/guides/all-about-updates/) for more information.
