### ISSUE TITLE
I cannot connect to my schema

### ISSUE THREAD

**Issue by dancespiele** [diesel-rs/diesel#2334]
### Versions

- Rust: 1.42.0
- Diesel: 1.4
- Database: Postgres
- Operating System: FreeBSD

## Problem Description
I cannot connect to my schema

### What are you trying to accomplish?
connect to my schema

### What is the actual output?
`db pool: Error(Some("invalid URI query parameter:\"currentSchema\"\n"))', src/db.rs:13:5` 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by dancespiele** [comment]
I could archive it with `sql_query` and `CustomizeConnection` but I think it could be easier and more intuitive select a Schema

**Comment by weiznich** [comment]
Please make a concrete proposal how you think that this could be simplified. Otherwise I think the documentation on the accepted options in a connection url are pretty clear for postgres, which means I do not see any issue here and will close this soon if no more information are added.

**Comment by weiznich** [comment]
Closed as not actionable.
