### ISSUE TITLE
Call stored procedure from diesel?

### ISSUE THREAD

**Issue by Muqito** [diesel-rs/diesel#2335]
### Versions

- **Rust: rustc 1.43.0-nightly (564758c4c 2020-03-08)**
- **Diesel: 1.0.0**
- **Database: MariaDB '8.0.19'**
- **Operating System: Microsoft Windows 10 PRO Build 18363**

### Feature Flags

- **diesel: mysql, chrono**

## Problem Description
I want to call a stored procedure with diesel

### What are you trying to accomplish?
Calling a stored procedure with diesel, ex: ```CALL get_user(1);```

### What is the expected output?
```
user = User {
    id: 1,
    name: "Christoffer",
    created_at: 2020-03-22T19:28:46,
}
```

### What is the actual output?
thread 'main' panicked at 'Couldn't get result: DeserializationError("No metadata exists")'

### Are you seeing any additional errors?
No

### Steps to reproduce
See the following [git repo](https://github.com/Muqito/diesel-stored-procedure)

## Checklist

- [x] I have Googled, but I haven't found anyone with the same error, only reference I find is in the [source (ofc)](https://docs.rs/diesel/1.4.3/src/diesel/mysql/connection/stmt/mod.rs.html#125)
- [x] Googled stored procedure in diesel and found the following [gitter discussion](https://gitter.im/diesel-rs/diesel/archives/2018/08/24)

Maybe it's not possible?

**Comment by weiznich** [comment]
Your stored procedure does not return anything. That means there is nothing that could be loaded by `get_results` there. In such cases prefer to use `.execute`.

**Comment by Muqito** [comment]
> Your stored procedure does not return anything. That means there is nothing that could be loaded by `get_results` there. In such cases prefer to use `.execute`.

Hello

So, if I understand you correctly I cannot use a stored procedure for a select?

Regarding using execute for a stored procedure, looking at [this](https://docs.diesel.rs/diesel/query_dsl/trait.RunQueryDsl.html#method.execute)

"When asking the database to return data from a query, load should probably be used instead."

I thought about using a view; but I need to be able to use parameters.

I also thought about including the query from a .sql file and populating the parameters with the bind param; but I couldn't find anywhere where I could use a named param for binding.

Would you be able to point me in the right direction?

**Comment by Muqito** [comment]
> Your stored procedure does not return anything. That means there is nothing that could be loaded by `get_results` there. In such cases prefer to use `.execute`.

Hello

Thank you for replying so quickly!

So there is no way for me to return the rows of a select statement in a stored procedure? (like with some NodeJS libraries)

I need to return the rows, is it better to just load in the query as a str and bind the params instead?

Thanks in advance!

**Comment by weiznich** [comment]
> So there is no way for me to return the rows of a select statement in a stored procedure? (like with some NodeJS libraries)

There is nothing preventing that, as long as `libmysqlclient` is giving us the required information about the result set. (If this query returns something then there is an bug in `libmysqlclient, as it has no metadata about the structure of the result.) Then using `.load`/`.get_results` is the right way.
As I'm never used any nodejs library I cannot say you what they can do and how it's done there.

> I need to return the rows, is it better to just load in the query as a str and bind the params instead?

I probably would just go that way. Basically just do `sql_query(include_str!("your_query.sql")).bind("whatever").load(…)`. So you have the sql query in a separate file and your editor can do syntax highlighting/linting/… there.

**Comment by Muqito** [comment]
> > So there is no way for me to return the rows of a select statement in a stored procedure? (like with some NodeJS libraries)
> 
> There is nothing preventing that, as long as `libmysqlclient` is giving us the required information about the result set. (If this query returns something then there is an bug in `libmysqlclient, as it has no metadata about the structure of the result.) Then using `.load`/`.get_results` is the right way.
> As I'm never used any nodejs library I cannot say you what they can do and how it's done there.
> 
> > I need to return the rows, is it better to just load in the query as a str and bind the params instead?
> 
> I probably would just go that way. Basically just do `sql_query(include_str!("your_query.sql")).bind("whatever").load(…)`. So you have the sql query in a separate file and your editor can do syntax highlighting/linting/… there.

Thank you! Yes I ended up doing the "your_query.sql" thing :)

Cheers
