### ISSUE TITLE
Mismatched r2d2 Error type

### ISSUE THREAD

**Issue by Evian-Zhang** [diesel-rs/diesel#2336]
### Versions

- **Rust:** 1.42.0
- **Diesel:** 1.0
- **Database:** Postgresql
- **Operating System** Ubuntu 18.04

### Feature Flags

- **diesel:** "postgres", "r2d2"

### What are you trying to accomplish?

I want to handle the r2d2 connection error by converting `diesel::r2d2::Error` to my own `Error` type.

### What is the expected output?

Successfully convert.

### What is the actual output?

expected enum `diesel::r2d2::Error`, found struct `r2d2::Error`

### Are you seeing any additional errors?

No

### Steps to reproduce

My own `Error` type:

```rust
// impls `Debug`, `Display` and `Error` trait
enum Error {
    R2d2Error(diesel::r2d2::Error)
}
```

Error handling code:

```rust
// created `manager` by `ConnectionManager::<PgConnection>::new`
// expected type: `std::result::Result<diesel::r2d2::Pool<ConnectionManager<PgConnection>>, Error>
diesel::r2d2::Pool::builder()
    .connection_timeout(Duration::from_secs(CONNECTION_TIMEOUT)
    .build(manager)
    .or_else(|r2d2_error| Err(Error::ConnectionError(r2d2_error)))
```

where error occurs at `r2d2_error`in `Err(Error::ConnectionError(r2d2_error)`: expected enum `diesel::r2d2::Error`, found struct `r2d2::Error`.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
As the compiler error message states the error returned from the `r2d2` pool builder is a `r2d2::Error`, not a `diesel::r2d2::Error`. That is something we do not have any control of as it is coming directly from `r2d2`.
(Note this error type is also re-exported from diesel as [`diesel::r2d2::PoolError`](http://docs.diesel.rs/diesel/r2d2/type.PoolError.html).

Closed as this is not fixable.

**Comment by Evian-Zhang** [comment]
> As the compiler error message states the error returned from the `r2d2` pool builder is a `r2d2::Error`, not a `diesel::r2d2::Error`. That is something we do not have any control of as it is coming directly from `r2d2`.
> (Note this error type is also re-exported from diesel as [`diesel::r2d2::PoolError`](http://docs.diesel.rs/diesel/r2d2/type.PoolError.html).

@weiznich From the [API doc](http://docs.diesel.rs/diesel/index.html), `diesel::r2d2::Pool`'s `builder()` method returns a type of `diesel::r2d2::Builder`, `diesel::r2d2::Builder`'s `build()` method returns a type of `Result<Pool<M>, Error>`, while if I click the `Error`, it turns out the struct `diesel::r2d2::Error`. Is it wrong?

**Comment by weiznich** [comment]
Yes that documentation is wrong. I've never noticed that. As those links are generated by rustdoc itself, we cannot do much about it. In my opinion this is a rustdoc bug, so it would be great if you fill an issue in the rustc repo for this.
