### ISSUE TITLE
[Feature Request] #[serialize_as] for Insertable, like #[deserialize_as] for Queryable

### ISSUE THREAD

**Issue by pheki** [diesel-rs/diesel#2344]
#1852 added `#[deserialize_as]` for `Queryable` and `QueryableByName`, which I found to be very useful. It is stated in that PR that it was intended to follow that PR with an equivalent `#[serialize_as]` attribute for `Insertable` and `AsChangeset`. I was looking for it and I'd find it really helpful. Is that still on the roadmap?

Thanks!

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment]
It is still on the roadmap in terms of we would accept a PR implementing this feature. As far as I know none of the regular contributors is currently working on this.

**Comment by pheki** [comment]
That's great! unfortunately I don't have the bandwith to understand diesel internals + implement it right now

**Comment by thomaseizinger** [comment]
If I were to give this a shot, would I target current master or the 1.4 branch?

**Comment by weiznich** [comment]
@thomaseizinger New features always targeting the master branch.
