### ISSUE TITLE
Diesel should "retry" or "wait" or "ping" for DB before setup

### ISSUE THREAD

**Issue by frederikhors** [diesel-rs/diesel#2345]
Frequently I need to execute "diesel setup" after newly dockerized postgresql start.

The thing is sometimes postgresql server is not up yet and diesel don't wait and fail.

Is there a way I can tell diesel to "retry" or "wait" or "ping"?

**Comment by weiznich** [comment]
There is no way to tell diesel cli for a certain event. Your shell already provides tools doing this, so it would be not logical to implement that in diesel_cli too. The probably easiest way is to just call `sleep 10` or something like that after starting postgresql and before running diesel_cli.

Closed as this is not actionable for the diesel team.
