### ISSUE TITLE
cargo install diesel_cli installs outdated version 1.4.0. Why?

### ISSUE THREAD

**Issue by Mingun** [diesel-rs/diesel#2349]
### Versions

- **Rust:** rustc 1.42.0 (b8cedc004 2020-03-09)
- **Diesel:** not yet defined
- **Database:** sqlite
- **Operating System:** Windows 10

### Feature Flags

- **diesel:**

## Problem Description
When I try to install diesel_cli via
```bash
cargo install diesel_cli --no-default-features --features sqlite-bundled
```
cargo installs only version 1.4.0, although version 1.4.4 is availible. Why? And how install the latest?

### What are you trying to accomplish?
Install diesel_cli

### What is the expected output?
Install latest version -- 1.4.4 in that case

### What is the actual output?
Successfully installed version 1.4.0

### Are you seeing any additional errors?
No

### Steps to reproduce
```bash
$ cargo new project
$ cd project
$ cargo install diesel_cli --no-default-features --features sqlite-bundled
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
The release page explicitly mentions that we have released `diesel` version 1.4.4, not `diesel_cli`, as the cli only contains some helper functionalities that do not change between different patch versions.

Closed as everything is as expected.

**Comment by Mingun** [comment]
In that case can you please update [Getting started](http://diesel.rs/guides/getting-started/) guide to clearly state, that version of diesel cli not necessary will match diesel version itself?

I think, that notice can be added after:

>Diesel provides a separate CLI tool to help manage your project. Since it's a standalone binary, and doesn't affect your project's code directly, we don't add it to Cargo.toml. Instead, we just install it on our system.
> 
>> cargo install diesel_cli

**Comment by weiznich** [comment]
I'm not sure I understand why the version of `diesel_cli` even needs to match the version of `diesel` in your understanding. Our stability guarantee is that each 1.x version is compatible with all newer 1.x versions, therefore it does not really matter which version of diesel_cli you are use. From this point of view I do not see any reason to add a notice there, as this stability guarantee is basically the same as for most other rust projects.

**Comment by Mingun** [comment]
There are no separate `diesel` and `diesel CLI` entities in the user's mind. Therefore, by installing the `diesel` command (although using the name `diesel_cli` in the `cargo install` command), following the instructions on the `diesel.rs` site, you can expect the latest version to be installed. And when I see that there is a version that is not the last according to the diesel site, it immediately raises the question of why so. Won't there be any problems because of it? Therefore, it is desirable to prevent such issues immediately.

> Our stability guarantee is that each 1.x version is compatible with all newer 1.x versions, therefore it does not really matter which version of diesel_cli you are use.

Your say that because you know it. The version doesn't go up for nothing. So some bugs are fixing. It will be offensive to hit some bug, fight it and find out that it is fixed in next patch. These questions aren't intertwined with stability, just being able to let people check that what they're doing -- right, that's the way it should be.

You can see itself that on your issue tracker there are constantly the same questions. I don't think people create them because they want to hurt you. So, that's call that really something is unclear and it is desirable to describe that explicitly.
