### ISSUE TITLE
Is it possible to use environment variables in table_name attribute  ?

### ISSUE THREAD

**Issue by GopherJ** [diesel-rs/diesel#2353]
### Versions

- **Rust:** latest
- **Diesel:** latest
- **Database:** latest
- **Operating System** LinuxMint

### Feature Flags

- **diesel:** all

## Problem Description

How to use environment variables in table_name attribute? 

### What are you trying to accomplish?

```rust
#[derive(Insertable)]
#[table_name = "casbin_rules"]   // instead of using a static string, can we use environment variable?
pub(crate) struct NewCasbinRule<'a> {
    pub ptype: &'a str,
    pub v0: &'a str,
    pub v1: &'a str,
    pub v2: &'a str,
    pub v3: &'a str,
    pub v4: &'a str,
    pub v5: &'a str,
}


```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
No that's not supported.

Closed as this is nothing actionable for the diesel team. Our issue tracker is a place to track bugs and actionable feature requests, that are coordinated with the diesel team. For everything else please use the gitter channel or our forum.
