### ISSUE TITLE
How to achieve dynamic filter

### ISSUE THREAD

**Issue by zzh787272581** [diesel-rs/diesel#2356]
I want to implement multiple query condition filtering, and to implement dynamic filter method

### Versions

- **Rust:**1.42.0
- **Diesel:** diesel = { version = "1.0.0", features = ["postgres","chrono"] }
- **Database:** postgres
- **Operating System** 

### Feature Flags

- **diesel:**

## Problem Description
```
let mut query = file_paths::table
        .inner_join(files::table.on(files::id.eq(file_paths::file_id)))
        .filter(files::temp_id.gt(0));

    if !params.start_time.is_empty() {
        if let Ok(st) = NaiveDateTime::parse_from_str(params.start_time.as_str(), "%Y-%m-%d %H:%M:%S") {
            query = query.filter(files::created_at.ge(st));
        }
    }

    let file_rows: Vec<FileInfo> = query
        .limit(limit)
        .offset(offset)
        .order(file_paths::id.desc())
        .select((file_paths::id,
                 files::name,
                 files::hash,
                 file_paths::module,
                 file_paths::soft_name,
                 file_paths::version,
                 file_paths::os_bit,
                 files::temp_id
        )).load(connect).expect("Error loading file_paths");
```

##problem
 ```
query = query.filter(files::created_at.ge(st));
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `diesel::expression::operators::Gt`, found struct `diesel::expression::operators::And`
```

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
You are looking for [`QueryDsl::into_boxed`](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed)

In general please do not use our issue tracker to ask questions. We have a gitter channel and a forum for this. Our issue tracker is a place for us to track bugs and feature request, not to answer support questions.
