### ISSUE TITLE
NonAggregate modifications broke code that doesn't touch aggregation

### ISSUE THREAD

**Issue by Ten0** [diesel-rs/diesel#2368]
We have implemented the following for setting a `Nullable<Timestamptz>` to either null or now dynamically (about 5 months ago):

```rust
#[cfg(feature = "with_chrono")]
pub fn optional_now(
	is_not_null: bool,
) -> Box<
	dyn diesel::BoxableExpression<
		(),
		diesel::pg::Pg,
		SqlType = diesel::sql_types::Nullable<diesel::sql_types::Timestamptz>,
	>,
> {
	use chrono::{DateTime, Utc};
	use diesel::{
		dsl::now,
		prelude::*,
		sql_types::{Nullable, Timestamptz},
	};
	if is_not_null {
		Box::new(now.into_sql::<Nullable<Timestamptz>>())
	} else {
		// There doesn't seem to be an expression that always represents null
		Box::new(Option::<DateTime<Utc>>::None.into_sql::<Nullable<Timestamptz>>())
	}
}
```

This broke as of be0854094c79ae99ba3c893242a4be358ac0b0c5, giving the following error:
```
   --> lib.rs:150:3
    |
150 |         Box::new(now.into_sql::<Nullable<Timestamptz>>())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `diesel::expression::is_aggregate::No`, found struct `diesel::expression::is_aggregate::Never`
    |
    = note: required for the cast to the object type `dyn diesel::expression::BoxableExpression<(), diesel::pg::backend::Pg, SqlType = diesel::sql_types::Nullable<diesel::pg::types::sql_types::Timestamptz>, IsAggregate = diesel::expression::is_aggregate::No>`

error[E0271]: type mismatch resolving `<diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::pg::types::sql_types::Timestamptz>, std::option::Option<chrono::datetime::DateTime<chrono::offset::utc::Utc>>> as diesel::expression::ValidGrouping<()>>::IsAggregate == diesel::expression::is_aggregate::No`
   --> lib.rs:153:3
    |
153 |         Box::new(Option::<DateTime<Utc>>::None.into_sql::<Nullable<Timestamptz>>())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `diesel::expression::is_aggregate::No`, found struct `diesel::expression::is_aggregate::Never`
    |
    = note: required for the cast to the object type `dyn diesel::expression::BoxableExpression<(), diesel::pg::backend::Pg, SqlType = diesel::sql_types::Nullable<diesel::pg::types::sql_types::Timestamptz>, IsAggregate = diesel::expression::is_aggregate::No>`
```

From what I understand, this is not expected breakage as described in #2251.

(By the way if this could instead work with just `Option<now>` that would be much better ^^)

**Comment by Ten0** [comment]
Doesn't this mean `BoxableExpression` should also be implemented when `T: ValidGrouping<(), IsAggregate = Never>` ?
Is this about using the same trick as we used [here](https://github.com/diesel-rs/diesel/issues/2001#issuecomment-562111021) ?

**Comment by weiznich** [comment]
> From what I understand, this is not expected breakage as described in #2251.

It's explicitly listed as open question there, so I would call that expected behaviour for now. We need to decide how to handle group by clauses in general for `BoxableExpression`. There are several potential solutions here:
- Make `BoxableExpression` generic over the group by clause
- Forbid the usage in queries containing a group by clause
- Restrict `BoxableExpression` to be basically `NonAggregate`
- possible other things I've forgot about.

Its an area where someone needs to do some experimentation which solution would have which implications and what is even possible to implement.

Beside of that: The next major release is 2.0, so it's to break existing code in cases where it is needed. If we decide to leave the current workaround in place we should add a note to the changelog/upgrade guide.

**Comment by Ten0** [comment]
Oh right I missed that mention on second read because it was not listed in "User impact". Thank you. 

I agree it's ok to break stuff, though I would like to underline that I'm currently unaware of an alternate way to achieve what I'm trying to achieve. Is there one I missed, or is this capability gone from diesel from now?

**Comment by weiznich** [comment]
The builtin `BoxableExpression` does currently not support this use case. That does not mean you cannot get this working, as you basically can just define your own version on `BoxableExpression` somewhere in your crate if required. There you can easily adjust the trait bounds as required.

As a general note: Master is the branch where development happens. This implies that not everything must work all the time, as we need to do the development somewhere. As it's not officially released we generally do not advice using that somewhere.

**Comment by Ten0** [comment]
Thank you. I'm currently experimenting with `BoxableExpression` generic over the group by clause (with () as default), though removing the constraint `IsAggregate=No` on `ValidGrouping<()>`, requiring/allowing to specify it when boxing does not seem to require adding that generic type parameter on `BoxableExpression`.

**Comment by weiznich** [comment]
I think that would be a fine solution, as long as the compilation fails if you try to add a `BoxableExpression` to the query containing some `group by` clause, that would make this expression invalid.
