### ISSUE TITLE
the trait `ValidGrouping<(t::columns::a, t::columns::b)>` is not implemented for `t::columns::b`

### ISSUE THREAD

**Issue by Ten0** [diesel-rs/diesel#2370]
I'm trying to get the following query to run (simplified for issue): 

```rust
some_table::table
	.group_by((some_table::id, some_table::created_at))
	.select((some_table::id, some_table::created_at))
	.load::<(i32, DateTime<Utc>)>(db)?;
```

This broke as of be0854094c79ae99ba3c893242a4be358ac0b0c5, giving the following error:

```
the trait `diesel::expression::ValidGrouping<(some_table::columns::id, some_table::columns::created_at)>` is not implemented for `some_table::columns::id`
   |
   = help: the following implementations were found:
             <some_table::columns::id as diesel::expression::ValidGrouping<()>>
             <some_table::columns::id as diesel::expression::ValidGrouping<some_table::columns::id>>
```

I suppose that is due to the fact we are in the middle of a rework of the "GROUP BY" support, but opening this in case this was not expected to break/is easy to fix.

**Comment by weiznich** [comment]
This is currently expected :wink:
We probably will only support group by clauses containing a single column/expression in 2.0 as adding support for the composite case is quite a bit work, but will not require a breaking change. 

To add the corresponding comment from the PR for visibility here

> An idea would be to have some proc macro attribute that applies globally to the schema.rs file and that just collects all columns and tables in this file. Then it can generate all required brute force impls. (This would also remove the need for allow_tables_to_appear_in_same_query!)

Adding this to the diesel 2.1 milestone as it's currently not planed for diesel 2.0. If someone feels like tackling this feel free to pick this issue up, but don't expect to much mentoring or something like that yet.

**Comment by Ten0** [comment]
For reference: https://github.com/diesel-rs/diesel/pull/2251#discussion_r361623060 (Easier to understand where the complexity is with your initial comment ^^)

In the meantime, I've built a reasonable workaround:
```rust
macro_rules! allow_group_by {
    ($($col: ty),+) => {
        allow_group_by!(($($col),+); $($col),+);
    };
    ($group_by:ty; $($col_for: ty),+) => {
        $(
            impl
                ::diesel::expression::ValidGrouping<$group_by> for $col_for
            {
                type IsAggregate = diesel::expression::is_aggregate::Yes;
            }
        )+
    };
}

allow_group_by!(schema::some_table::id, schema::some_table::created_at);
```
where you would make one call to `allow_group_by!` per tuple on which you actually need to group by.

Perhaps we could provide this macro within Diesel ?

**Comment by weiznich** [comment]
As this macro is clearly a workaround I'm not happy with adding something like this to diesel, as removing stuff that's in the public API is quite hard (= requires a major version bump). Additionally this is a feature that is not supported yet on already released diesel versions + it is "easily" possible to write the required impls outside of diesel with the new release I would rather not add such a macro as temporary workaround for a single version. What probably should be done is having some sentence in the documentation about how to support composite group by clauses. (But again, this API isn't even on master public yet)
