### ISSUE TITLE
Better error handing with belonging_to for non references

### ISSUE THREAD

**Issue by ralpha** [diesel-rs/diesel#2380]
## Setup
I used the code from: https://docs.diesel.rs/diesel/associations/index.html
```
use schema::{posts, users};

#[derive(Identifiable, Queryable, PartialEq, Debug)]
#[table_name = "users"]
pub struct User {
    id: i32,
    name: String,
}

#[derive(Identifiable, Queryable, Associations, PartialEq, Debug)]
#[belongs_to(User)]
#[table_name = "posts"]
pub struct Post {
    id: i32,
    user_id: i32,
    title: String,
}

let user = users.find(2).get_result::<User>(&connection)?;
let users_post = Post::belonging_to(&user)
    .first(&connection)?;
let expected = Post { id: 3, user_id: 2, title: "My first post too".into() };
assert_eq!(expected, users_post);
```
This code works, as it should.
But when changing the line from:
```
let users_post = Post::belonging_to(&user)
```
to (the `&` is removed )
```
let users_post = Post::belonging_to(user)
```

The compiler gives an error that is very hard to figure out:
```
error[E0277]: the trait bound `Post: diesel::BelongingToDsl<User>` is not satisfied
  --> src/main.rs:30:29
   |
30 |     let _users_post: Post = Post::belonging_to(user)
   |                             ^^^^^^^^^^^^^^^^^^ the trait `diesel::BelongingToDsl<User>` is not implemented for `Post`
   |
   = note: required by `diesel::BelongingToDsl::belonging_to`

error: aborting due to previous error
```
This error is not so useful. 
An error like this could be **much** more helpful:
```
error[E0308]: mismatched types
  --> src/main.rs:30:48
   |
30 |     let _users_post: Post = Post::belonging_to(user)
   |                                                ^^^^
   |                                                |
   |                                                expected reference, found struct `User`
   |                                                help: consider borrowing here: `&user`
   |
   = note: expected reference `&_`
                 found struct `User`

error: aborting due to previous error
```

To find this tiny mistake I had to create a new project and just change bit by bit to find where it started giving me the error.

So giving better errors would real help here.

### Versions

- **Rust:** 1.43.0 (4fb7144ed 2020-04-20)
- **Diesel:** 1.4.4
- **Database:** Postgres
- **Operating System** Linux

### Feature Flags

- **diesel:** ["postgres", "r2d2"]

**Comment by weiznich** [comment]
Error messages are emitted by rustc, not by diesel. That implies we do not have any real control about which error messages are shown to the user. Therefore please elaborate what exactly could be done on diesel side to improve the situation. For suggestions how to improve rustc output please open issues at their repository.

**Comment by ralpha** [comment]
I know errors are not an easy issue to solve (if they can at all, without rustc changes).
But if `belonging_to` always expects a reference to an object. You could change:
https://github.com/diesel-rs/diesel/blob/0b7bb3c7775b091ce9e48df748b75f2103d36c43/diesel/src/query_dsl/belonging_to_dsl.rs#L53

to 
```
fn belonging_to(other: &T) -> Self::Output;
```
I know these changes will trickle back up the chain and might require bigger changes. (but I hope not) But then the compiler knows that it expects a reference and not an object.

**Comment by weiznich** [comment]
It does already know that it expects a reference, because the only existing impls are such that have a reference type as `T`, so I'm not sure if this would change/improve the error message.

**Comment by weiznich** [comment]
Closed as this cannot be fixed on diesel side without loosing current capabilities as pointed out in the comment above.
