### ISSUE TITLE
Trait `std::ops::Add` not implemented for columns of type `Unsigned<Integer>`

### ISSUE THREAD

**Issue by mclytar** [diesel-rs/diesel#2382]
### Versions

- **Rust:** 1.42
- **Diesel:** 1.4.4
- **Database:** MySQL 8.0.17
- **Operating System:** Windows 10

### Feature Flags

- **diesel:** `mysql`

## Problem Description
The trait `std::ops::Add` is not implemented for columns of type `Unsigned<Integer>`.
In particular, the following code compiles correctly:
```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;

table! {
    item (item_id) {
        item_id -> Unsigned<Integer>,
        name -> Varchar,
        value -> Integer,
    }
}

fn main() {
    use crate::item::dsl::*;

    diesel::update(item)
        .set(value.eq(value + 1));
}
```
while the following does not:
```rust
#[macro_use]
extern crate diesel;

use diesel::prelude::*;

table! {
    item (item_id) {
        item_id -> Unsigned<Integer>,
        name -> Varchar,
        value -> Unsigned<Integer>,
    }
}

fn main() {
    use crate::item::dsl::*;

    diesel::update(item)
        .set(value.eq(value + 1));
}
```
In particular, the compiler gives the following error:
```
error[E0369]: cannot add `{integer}` to `item::columns::value`
  --> src\main.rs:18:29
   |
18 |         .set(value.eq(value + 1));
   |                       ----- ^ - {integer}
   |                       |
   |                       item::columns::value
   |
   = note: an implementation of `std::ops::Add` might be missing for `item::columns::value`
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Already fixed on master by https://github.com/diesel-rs/diesel/pull/2278

**Comment by alfonso-eusebio** [comment]
@weiznich Sorry to comment here, but I didn't want to open a new ticket just for the question:

Is there any **workaround** to do this on `Unsigned<Tinyint>` using the current release (v1.4.4)?

Thanks!

**Comment by weiznich** [comment]
Not that I'm aware of
