### ISSUE TITLE
Inserting BigDecimal with scale into Postgres is broken

### ISSUE THREAD

**Issue by leoyvens** [diesel-rs/diesel#2385]
### Versions

- **Rust:**
1.43

- **Diesel:**
current master, commit 968e7f79c

- **Database:**
Postgres

- **Operating System**
Linux

### Feature Flags

- **diesel:**
postgres, numeric

## Problem Description
First, thanks for continuing to maintain Diesel.

Inserting a BigDecimal as a numeric in Postgres is and probably has always been broken for any number with power of ten > 0 (or scale < 0 in BigDecimal terms). Looking at the current code https://github.com/diesel-rs/diesel/blob/master/diesel/src/pg/types/numeric.rs#L90, it's full of unchecked casts and arithmetic which are vulnerable to silent overflows.

Given this, I'd recommend to anyone inserting BigDecimals into Postgres that you avoid using the Diesel support and instead cast text values to numeric.

### What are you trying to accomplish?
Insert a BigDecimal with a scale.

### What is the expected output?
It works.

### What is the actual output?
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
DatabaseError(__Unknown, "invalid scale in external \"numeric\" value")', src/main.rs:31:5
```

### Are you seeing any additional errors?
No.

### Steps to reproduce
Run this https://github.com/leoyvens/diesel-numeric-bug.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
I would be happy to review a PR fixing this, otherwise I do not plan to work on this in foreseeable future by myself.

For a potential fix the provided example should be used as test case. Adding additional test cases would be great.
