### ISSUE TITLE
Update dev-dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [diesel-rs/diesel#2393]
Hello,

I'm trying to package diesel for Fedora, but found that many dev-dependencies are outdated. Would it be possible to upgrade them?

Thanks in advance!

https://github.com/diesel-rs/diesel/blob/fe87242595ef70abe9a1f4a745f40d3c7110b1bb/diesel/Cargo.toml#L42-L43

https://github.com/diesel-rs/diesel/blob/master/diesel_cli/Cargo.toml#L43

https://github.com/diesel-rs/diesel/blob/master/diesel_derives/Cargo.toml#L19

https://github.com/diesel-rs/diesel/blob/master/diesel_migrations/Cargo.toml#L19

**Comment by weiznich** [comment]
I'm open to some contribution here, otherwise that's not on top of my todo list now, so feel free to submit corresponding PR's.

**Comment by ignatenkobrain** [comment]
I'll try to find time for that.

**Comment by weiznich** [comment]
Fixed by #2405 and #2509
