### ISSUE TITLE
Include LICENSE files in all sub-crates

### ISSUE THREAD

**Issue by ignatenkobrain** [diesel-rs/diesel#2394]
Hello,

I'm packaging diesel for Fedora and found that most(all?) diesel-related crates on crates.io do not contain LICENSE files. This is solved by either copying LICENSE files into the directories with Cargo.toml or adding symlinks there. I don't know which way you prefer, so did not send PR.

Thanks for cooperation!

**Comment by weiznich** [comment]
I'm not a lawyer, but as all relevant crates contain a corresponding entry in their `Cargo.toml` + there is an `LICENSE` in the root folder (which applies for all crates, as they share the same licence) I do not see an issue here.

**Comment by ignatenkobrain** [comment]
@weiznich the Apache-2.0 requires that source is being present along the sources which are stored on crates.io. And the real location from where people get crates is tarballs from crates.io, for example https://crates.io/api/v1/crates/diesel_migrations/1.4.0/download

And such tarball does not contain the license text which is requirement of Apache-2.0.

Do you see any issue with having symlink to the top-level LICENSE-* files from sub-crates?

**Comment by weiznich** [comment]
I would probably accept a PR changing the current setup. In general I do consider that more to be an crates.io/cargo issue as crates do explicitly say which license they are using. 

Instead of symlinking/copying the top-level `LICENSE-APACHE` file I would probably just the [`include` manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) to include the corresponding file explicitly. (Someone needs to double check if that's actually accepted by cargo)

**Comment by ignatenkobrain** [comment]
@weiznich include won't work since files are outside of the crate folder…

**Comment by weiznich** [comment]
It's a workspace, so I'm not sure if it's "outside" for cargos definition.

**Comment by ignatenkobrain** [comment]
@weiznich well, the issue is not with cargo or projects, but licensing weirdness. For example, if you say MIT, but there are over 20 MIT variations over there so you need to actually put proper license file to be clear to users. cargo does as much as it can to require something for being set, but licensing problems are… hard.

> It's a workspace, so I'm not sure if it's "outside" for cargos definition.
> (If it's "outside", please link the relevant code/documentation)

Well, anything above Cargo.toml of sub-crate is "outside". Oh yeah, the include will look even much more horrible because in that case you need to specify all files you want to include... And keep that updated. Anyway, if you would try - it won't include those.
