### ISSUE TITLE
Diesel initial setup migration comments are unclear or not up-to-date

### ISSUE THREAD

**Issue by theredfish** [diesel-rs/diesel#2397]
### Versions

- **Rust:** rustc 1.42.0 (b8cedc004 2020-03-09)
- **Diesel:** 1.4.3
- **Database:** Postgresql
- **Operating System** Ubuntu

### Feature Flags

- **diesel:** postgres

## Problem Description

The migration file `00000000000000_diesel_initial_setup/up.sql` contains a comment explaining that future changes tothis file will be added to existing projects as new migrations :

```
-- This file was automatically created by Diesel to setup helper functions
-- and other internal bookkeeping. This file is safe to edit, any future
-- changes will be added to existing projects as new migrations.
```
Performing `diesel migration redo` or `diesel database reset` will correctly take the changes into account. However the changes are not "added to existing projects as new migrations".

Did I misunderstand? Or has the feature been removed?

## Checklist
- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
The sentence "added to existing projects as new migrations" refers to changes to the initial setup migration that diesel will create on it's own for internal reasons. So if we decide to add a new sql helper function or something like that, we will do that as new migration, not by modifying the existing `00000000000000_diesel_initial_setup` one.

**Comment by theredfish** [comment]
Ok thank you !
