### ISSUE TITLE
bigdecimal version requirement

### ISSUE THREAD

**Issue by jebrosen** [diesel-rs/diesel#2402]
`diesel`'s `Cargo.toml` (both `master` and `1.4.x`) supports a somewhat awkward range of versions of `bigdecimal`:

https://github.com/diesel-rs/diesel/blob/45da0109a8b085e4aad629e64c0bb2d17f84c486/diesel/Cargo.toml#L32

Ever since `bigdecimal` `0.1.2` was released on April 26, I have seen a few questions about this because cargo now selects `0.1.2` if a user's `Cargo.toml` has `0.1.0`. It's not obvious (especially to new users) that they have to depend on bigdecimal `<=0.1.0` (or `=0.1.0`) in order to restrict their own dependency to the one that `diesel` has.

`0.1.x` should never break compatibility, so would `>=0.0.10, <0.2` be acceptable for this dependency instead?

**Comment by weiznich** [comment]
We would be happy to receive a PR for this as long as it is backward compatible with the already accepted version range.
