### ISSUE TITLE
No migration refresh, no ability to force re-run migration.

### ISSUE THREAD

**Issue by thorlucas** [diesel-rs/diesel#2411]
### Versions

- **Rust:**  rustc 1.43.1
- **Diesel:** 1.4.4
- **Database:** sqlite
- **Operating System** macOS Catalina 10.15.4

### Feature Flags

- **diesel:** sqlite

## Problem Description
Diesel refuses to automatically rerun migrations when a migration file is changed. Additionally, there is no way to refresh or force rerun all migrations. Creating a new migration and deleting the old one does not run down first so it throws errors. 

### What are you trying to accomplish?
I changed my schema and I would like to rerun the migrations to reflect this. This should work similar to Laravel's `php artisan migrate:refresh`.

### What is the expected output?
It should rerun all migrations or the ones I have selected, calling down first, then up.

### What is the actual output?
No migrations are run. When creating a new migration with the same name and deleting the old one, down is not called first so it says the table already exists.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
First of all: Please do not assume that diesel works like other ORM's you know. In general that's not the case.
Migrations are not meant to be changed afterwards as we cannot answer for the general case what has been changed and how to reapply them. You have several options here:

* Add a new migration and execute it with `diesel migration run`
* Change the last migration and execute it with `diesel migration redo` (only works if `down.sql` stays compatible with the old version)
* Change an arbitrary migration and rebuild the database with `diesel database reset` (will drop the database and all data, so be careful here)

I'm closing this issue as everything here is working as designed from my point of view.
