### ISSUE TITLE
Error: Number of parameters must be between 0 and 65535

### ISSUE THREAD

**Issue by ralpha** [diesel-rs/diesel#2414]
## Setup
When using `.insert_into(..).values(...)` and the values is a vector with a length larger then `65535` Postgress will trigger the following error: `Error saving coordinates: DatabaseError(UnableToSendCommand, "number of parameters must be between 0 and 65535\n")`
(`coordinates` is the table I want to insert the values to).

When the length is smaller then 65535 everything works fine.

### Versions

- **Rust:** 1.45.0-nightly
- **Diesel:** 1.4.4
- **Database:** postgres (r2d2) version 11.7
- **Operating System** Linux

### Feature Flags

- **diesel:** ["postgres", "r2d2"]

## Problem Description
When inserting more then 65535 items into a table it gives an error that can be handled and even prevented by Diesel.

### What are you trying to accomplish?
Inserting (a lot of) elements into a table.

### What is the expected output?
That all the items are just inserted without an error. Diesel should be able to break the query into 2-3 pieces and insert them that way.
I know this comes with a lot of other things to thing about but maybe this should be considered. 
If this is not going to be implemented, well at least we know now ;)

### What is the actual output?
The error mentioned earlier

### Steps to reproduce
Set up a database and generate a lot of elements (more then 65535).
Insert them all into the database with 1 call. Example:
```rust
diesel::insert_into(coordinates::table)
    .values(list_of_a_lot_of_elements)
    .execute(conn)
    .expect("Error saving coordinates");
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
You are hitting a limitation that is based in the libpq wire-protocol, which is something that is out of control for diesel. 
In theory it should be able to break such queries into 2-3 pieces as you mentioned, but in practice I do not see how this could work with our current query builder setup, that basically assumes that you only get one statement per query ast node. If someone figures out how to do that without rewriting diesel I'm open for to discuss a well written PR here.
Beside of that I think I will close this issue as won't fix.
