### ISSUE TITLE
Sqlite `STRING` type.

### ISSUE THREAD

**Issue by rubdos** [diesel-rs/diesel#2417]
##  Setup

I'm [retrofitting](https://gitlab.com/rubdos/whisperfish/) an existing *Sqlite* database for a free (and open source) mobile application. I prefer to use the *exact* same schema as before, implementing bug-for-bug compatibility.

### Versions

- **Rust:** rustc 1.43.0 (4fb7144ed 2020-04-20)
- **Diesel:** diesel 1.4.0
- **Database:** Sqlite
- **Operating System** Arch Linux, Debian Linux

### Feature Flags

- **diesel:** defaults

## Problem Description

The Sqllte `STRING` type is not recognised.

### What are you trying to accomplish?

Using an existing schema, where the Sqlite `STRING` "type" is used.

### What is the expected output?
A working `diesel print-schema` that's able to dump a correct `schema.rs`, eg

```rust
table! {
    session (id) {
        id -> Nullable<Integer>,
        source -> Nullable<Text>,
        message -> Nullable<Text>,
        timestamp -> Nullable<Integer>,
        sent -> Nullable<Integer>,
        received -> Nullable<Integer>,
        unread -> Nullable<Integer>,
        is_group -> Nullable<Integer>,
        group_members -> Nullable<Text>,
        group_id -> Nullable<Text>,
        group_name -> Nullable<Text>,
        has_attachment -> Nullable<Integer>,
    }
}
```

create the database (`diesel setup` works) and try to print the schema (`diesel print-schema`).

### What is the actual output?

```
rsmet@arch-club ~/src/whisperfish (git)-[master] % diesel print-schema
Unsupported type: string
```

### Steps to reproduce
Create a migration such as

```sql
CREATE TABLE session (
    id INTEGER PRIMARY KEY,
-- it works when source is TEXT
    source STRING,
-- it works when message is TEXT
    message STRING,
    timestamp INTEGER,
    sent INTEGER DEFAULT 0,
    received INTEGER DEFAULT 0,
    unread INTEGER DEFAULT 0,
    is_group INTEGER DEFAULT 0,
    group_members TEXT,
    group_id TEXT,
    group_name TEXT,
    has_attachment INTEGER DEFAULT 0
);
```

run `diesel setup && diesel print-schema`.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case) I didn't test this, but I don't imagine this has anything to do with rustc versions :-)

## Possible solution

N.b. I'm not a regular in Sqlite.

A `STRING` type gets affinity `NUMERIC` in Sqlite (as opposed to `TEXT` which gets `TEXT`); I think Diesel might prefer to map this "type" on `diesel::sql_types::Text` by default instead.

**Comment by weiznich** [comment]
According to the [sqlite documentation](https://www.sqlite.org/datatype3.html) such a type would be seen as numeric internally. I would be open for a change that infers unknown types on sqlite numeric, but we cannot ever infer all the application specific type mappings for sqlite. End the end those can be anything as sqlite does not really have a strong type system.

I'm closing this as won't fix.

As a workaround you can write the affected `table!` macro calls manually and just use the correct types there.
