### ISSUE TITLE
diesel migrations cannot use views

### ISSUE THREAD

**Issue by Skarlett** [diesel-rs/diesel#2418]
views are not added into the database by `diesel migration` cli

## Setup
```
create table service_index(
    ...
);

CREATE VIEW services AS SELECT ip, port, identifer, is_online
FROM service_data where is_online > 0;

```
### Versions

- **Rust:*rustc 1.44.0-nightly (e82734e56 2020-04-11)*
- **Diesel: *1.4.0*
- **Database:*sqlite3 - 3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837bb4d6*
- **Operating System*Linux archlinux 4.19.122-1-MANJARO #1 SMP Sun May 10 14:02:27 UTC 2020 x86_64 GNU/Linux*

### Feature Flags

- **diesel:* sqlite3*

## Problem Description
Views do not appear to be committed during migrations when running (`up.sql`)

### What are you trying to accomplish?
Attempting to use "views" feature in sqlite3.

### What is the expected output?
None.

### What is the actual output?
It does not place view in database.

### Are you seeing any additional errors?
No.

### Steps to reproduce
Attempt to use views
```sql
create table foo(
    baz int primary key,
    yak int
);

CREATE VIEW quick_foo AS SELECT yak
FROM foo where yak > 0;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by 3NdR1m** [comment]
May I ask why this issue was closed? This problem is still present today and arguably diminish the ability to interact with a database.

**Comment by weiznich** [comment]
@3NdR1m Because it's a duplicate of #43.
