### ISSUE TITLE
Dead table! error link

### ISSUE THREAD

**Issue by nabijaczleweli** [diesel-rs/diesel#2420]
### Versions

- **Diesel:** HEAD (4f642f8fa3e5ef696f150709c88f2d27b0d81bfa), 1.4.4

## Problem Description

`table!` error link "https://docs.diesel.rs/diesel/macro.table.html" is dead.

### What are you trying to accomplish?

Use the error output.

### What is the expected output?

A working link.

### What is the actual output?

https://github.com/diesel-rs/diesel/blob/4f642f8fa3e5ef696f150709c88f2d27b0d81bfa/diesel/src/macros/mod.rs#L291-L298

### Steps to reproduce

Misuse `table!`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
As we restructured the folder structure of the doc web page this is kind of expected. I'm open for contributions to fix this here. In general I'm in favor of not having absolute links as part of the source code to prevent such things from happening again.

**Comment by weiznich** [comment]
Fixed by adding back the corresponding files + removing the references from source code in https://github.com/diesel-rs/diesel/commit/c5efb42d01c5e3ff0f45b241fe969ea793720f35
