### ISSUE TITLE
Is there a plan to support MSSQL?

### ISSUE THREAD

**Issue by songlinshu** [diesel-rs/diesel#2423]
Hello! Is there a plan to support MSSQL?

**Comment by weiznich** [comment]
We do not plan add support for another backend to diesel itself. That said, it is possible to implement support for custom backends outside of diesel. See [diesel-oci](https://github.com/GiGainfosystems/diesel-oci) for example. If someone attempts to implement such a backend we are willing to answer questions about implementation specific problems, but the actual implementation needs to be done by someone else.
