### ISSUE TITLE
Feature request: support where clause for upsert

### ISSUE THREAD

**Issue by s97712** [diesel-rs/diesel#2430]
Postgresql upsert support where clause, such as below query: 
```sql
INSERT INTO table VALUES(...)  ON CONFLICT (id) DO UPDATE SET ... WHERE ...
```
Consider adding this feature for diesel?

**Comment by weiznich** [comment]
We would be happy to accept a PR for this, but at least I do not have any plan to invest much time in this feature anytime soon.

**Comment by ropottnik** [comment]
I'd like to give it a try. Can you assign me?

**Comment by ropottnik** [comment]
thanks @JohnTitor
