### ISSUE TITLE
Multiple foreign keys to same table

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#2432]
### What are you trying to accomplish?

I have a table with paragliding flights and a table with locations. A flight can have a launch location and a landing location.

```sql
...
launch_at INTEGER REFERENCES locations(id) ON DELETE NO ACTION,
landing_at INTEGER REFERENCES locations(id) ON DELETE NO ACTION,
...
```

I then tried to create a query that joins the location on the flights to create aggregations (number of launches and landings at a specific location). In pure SQL:

```sql
SELECT l.*, count(f1.*) as launches, count(f2.*) as landings
FROM locations l
LEFT JOIN flights f1 on f1.launch_at = l.id
LEFT JOIN flights f2 on f2.landing_at = l.id
GROUP BY l.id
ORDER BY landings desc;
```

In Diesel:

```rust
Location::belonging_to(user)
    .left_join(flights::table).on(flights::launch_at.eq(Some(locations::id)))
    ...
```

However, the `JoinTo` trait is not implemented:

```
194 |         .left_join(flights::table).on(flights::launch_at.eq(Some(locations::id)))
    |          ^^^^^^^^^ the trait `diesel::JoinTo<schema::flights::table>` is not implemented for `schema::locations::table`
```

I tried to add the `joinable` macro:

    joinable!(flights -> locations (launch_at));
    joinable!(flights -> locations (landing_at));

However, that generated conflicting impls:

```
error[E0119]: conflicting implementations of trait `diesel::JoinTo<schema::locations::table>` for type `schema::flights::table`:
  --> src/schema.rs:88:1
   |
87 | joinable!(flights -> locations (launch_at));
   | -------------------------------------------- first implementation here
88 | joinable!(flights -> locations (landing_at));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `schema::flights::table`
```

### What is the expected output?

Tables with multiple foreign keys to the same other table should be joinable.

### What is the actual output?

See above

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Your query is nearly correct. It needs to be 
```rust
Location::belonging_to(user)
    .left_join(flights::table.on(flights::launch_at.eq(Some(locations::id))))
```

As the documentation has a correct example [here](http://docs.diesel.rs/1.4.x/diesel/query_dsl/trait.JoinOnDsl.html#method.on) and [here](http://docs.diesel.rs/1.4.x/diesel/query_dsl/trait.QueryDsl.html#with-explicit-on-clause) I'm closing this as not an issue.

**Comment by dbrgn** [comment]
Ahh, thank you! I should have re-checked against the docs...

**Comment by dessalines** [comment]
How do I do multiple ons? IE `inner join table2 on table1.id = table2.id and table1._second_id = table2.second_id` I can't find an `.on(...).and`
