### ISSUE TITLE
Support for AWS RDS DATA API

### ISSUE THREAD

**Issue by emiddleton** [diesel-rs/diesel#2442]
## Description
I would like to use diesel to create microservices on AWS lambda, but straight postgresql connections do not scale well.  AWS offers a rest based API[1] that wraps the postgresql/mysql queries and handles scaling the database (Aurora Serverless[2]).  It would be good if diesel supported this interface.  There are is official support for this API through rusoto_rds_data crate[3].  I would be interested on working on this but would need some pointers on the best approach to take.

1. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html
2. https://aws.amazon.com/rds/aurora/serverless/
3. https://docs.rs/rusoto_rds_data/

**Comment by weiznich** [comment]
We are not interested in having such a connection implementation in diesel itself, as it is tailored for a specific closed source system and therefore hard to test for contributors. That said diesel is generally designed in such a way that it is possible to implement connections/custom backends as third party crates. (See [diesel-oci](https://github.com/GiGainfosystems/diesel-oci) as an example). For the actual implementation I would probably do something like in [this PR, which adds another connection implementation](https://github.com/diesel-rs/diesel/pull/2257/files#diff-7e06ffc7fba2d2773c1ff25eadbfed18R1) for the postgres backend.

Closed as this is nothing that is actionable by the diesel team itself. If there are specific questions about how to approach an implementation feel free the ping me in our gitter channel. If there are blockers in our API that prevent a third party implementation open a new issue with the specific details. We will try to figure out how to extend our API in an appropriated way then.
