### ISSUE TITLE
SQLite column type REAL is turned into Float instead of Double

### ISSUE THREAD

**Issue by the-emerald** [diesel-rs/diesel#2444]
### Versions

- **Rust:** 1.44.1
- **Diesel:** 1.4.5
- **Database:** SQLite
- **Operating System:** Ubuntu 18.04.4 LTS x86_64

### Feature Flags

- **diesel:** `sqlite`, `numeric`, `64-column-tables`, `r2d2`

## Problem Description

A column of data type `REAL` in SQLite is translated into a `Float` in the table macro that is used in `schema.rs`. According to [diesel.rs documentation](https://docs.diesel.rs/1.4.x/diesel/sqlite/enum.SqliteType.html#variant.Float) a `Float` will become an `f32`, but [SQLite documentation](https://www.sqlite.org/datatype3.html) says that:
> "REAL. The value is a floating point value, stored as an 8-byte IEEE floating point number."

...which is a `f64` in Rust if I am not mistaken.

However, using `DOUBLE` instead of `REAL` gives the correct types - even though they are represented the same way in SQLite.

Example input:
```sql
CREATE TABLE example (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    foo REAL NOT NULL,
    bar REAL NOT NULL,
    kitty REAL NOT NULL,
)
```

### What is the expected output?
```rs
table! {
    tissues (id) {
        id -> Integer,
        foo -> Float,
        bar -> Float,
        kitty -> Float,
    }
}
```

### What is the actual output?
```rs
table! {
    tissues (id) {
        id -> Integer,
        foo -> Double,
        bar -> Double,
        kitty -> Double,
    }
}
```

### Steps to reproduce
1. Make a migration with the SQL snippet shown in Problem Description
2. Run the migration.
3. Notice that the generated `schema.rs` does not produce `Double`s but produces `Float`s.
4. Try again with `DOUBLE` instead of `REAL` in the migration and intended behaviour is shown.

N.B.: this commit fixed the issue in a project of mine: https://github.com/the-emerald/capra-planner/commit/816f7a69da43a9fb2a30e3645868ac4c8691b6ad

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Sqlite's does not really have a static type system at all. Even if a column has `REAL` as type it will happily store a text value for example. Based on this we decided to infer the types for columns on your own based on the type name, roughly following the SQL standard/what postgres does. This leads to the decision that a `Float` column maps to `f32`, but a `Real`/Double` column to `f64` even if the underlying field is able to store a `f64` value in all cases.


Closed as expected behavior.

**Comment by arthmis** [comment]
@weiznich should the `REAL` column map to `Float` or `Double` for sqlite? Your comment above implies it should map to `Double` but the diesel cli maps it to a `Float`.

**Comment by weiznich** [comment]
@arthmis I'm not sure what you expect to hear from me. Whatever might be the correct default does not really matter at this point anymore as changing the current behaviour is a huge breaking change. That's also the same with https://github.com/diesel-rs/diesel/issues/2330 and https://github.com/diesel-rs/diesel/issues/4627. Changing that requires a larger rework on how type mapping in diesel-cli is done in general, you are welcome to contribute a design there that doesn't add specific flags for all backends and types.
