### ISSUE TITLE
Fulltext index support

### ISSUE THREAD

**Issue by ShaneEverittM** [diesel-rs/diesel#2456]
# Versions

- **Rust:**
1.46.0-nightly
- **Diesel:**
1.4.1
- **Database:**
MySQL 8.0.21
- **Operating System**
KDE Neon 5.19

Is there any support for the following syntax:
`SELECT * from table where match(col1, col2) against ("query_term" in boolean mode)`
Or am I stuck using a raw sql query for fulltext searches.

**Comment by weiznich** [comment]
It's not supported by diesel's dsl out of the box, but it is possible to extend diesels query-dsl in such a way to add support for such operations in a third party crate. See [diesel_full_text_search](https://github.com/diesel-rs/diesel_full_text_search/) as an example of such an extension crate. 
Additionally as support for postgres fulltext functionality is provided as third party crate, I would like to handle this for MySQL similarly. This does not mean that we as the diesel team are interested in writing such a crate in a foreseeable future, just that we currently don't want to include this functionality in diesel itself.

**Comment by ShaneEverittM** [comment]
Makes sense. If I could ask, is the specific match(...) against (...) syntax of mysql too involved to be extended in using diesel_infix_operator?

**Comment by weiznich** [comment]
`match (…) against (…)` likely needs a fully custom query node implementation.
