### ISSUE TITLE
Documentation pages for 1.4 have broken source links

### ISSUE THREAD

**Issue by nickodell** [diesel-rs/diesel#2459]
## Problem Description

Links to source code from documentation on 1.4.x pages are broken.

Example:

On [this page](https://docs.diesel.rs/diesel/fn.sql_query.html), click [src]. The link is broken.

**Comment by JohnTitor** [comment]
Note that the correct link is https://docs.diesel.rs/1.4.x/diesel/index.html, not https://docs.diesel.rs/diesel/index.html.
Where did you find that link? If something points to it, we could update it to avoid confusion.

**Comment by nickodell** [comment]
I googled the search term "rust diesel execute sql." The first hit is https://docs.diesel.rs/diesel/fn.sql_query.html

**Comment by JohnTitor** [comment]
So, I think we cannot take any action here - the actual docs for 1.4.x work well and diesel.rs points to it correctly. If you have any idea that we can do here, feel free to reach out. Thanks for reporting!

**Comment by weiznich** [comment]
It's fixed now for me
