### ISSUE TITLE
Unable to create table named "user"

### ISSUE THREAD

**Issue by cbzehner** [diesel-rs/diesel#2472]
### Versions

- **Rust:** rustc 1.43.1 (8d69840ab 2020-05-04)
- **Diesel:** 1.4.4
- **Database:** postgres (PostgreSQL) 12.3
- **Operating System** macOS 10.15.5

### Feature Flags

- **diesel:** { version = "1.4.4", features = ["postgres"] }

## Problem Description

Creating a table with the name `user` results in an error with no actionable result `Failed with: syntax error at or near "user"`. Changing the table name to the plural form `users` resolves this issue. This doesn't occur with `posts`, both `posts` and `post` are valid and are able to be created correctly.

### What are you trying to accomplish?

Create a table with the name `user`

### What is the expected output?

`Running migration 2020-07-29-150248_create_user` succeeds.

### What is the actual output?

```bash
❯ diesel migration run
Running migration 2020-07-29-145952_create_post

❯ diesel migration generate create_user
Creating migrations/2020-07-29-150248_create_user/up.sql
Creating migrations/2020-07-29-150248_create_user/down.sql

❯ diesel migration list
Migrations:
  [X] 00000000000000_diesel_initial_setup
  [X] 2020-07-29-145952_create_post
  [ ] 2020-07-29-150248_create_user

❯ diesel migration run
Running migration 2020-07-29-150248_create_user
Executing migration script /Users/cbzehner/Projects/open-source/diesel-singular-table-names/diesel_demo/migrations/2020-07-29-150248_create_user/up.sql
Failed with: syntax error at or near "user"
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

I created a repository based on the first few steps of the [getting started](http://diesel.rs/guides/getting-started/) guide to showcase the issue.

1. Clone https://github.com/cbzehner/diesel_user_table_creation_error
1. Run `diesel setup` locally
1. Run `diesel migration run` and experience the error.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by cbzehner** [comment]
Please let me know if I missed something or have a syntax error. This struck me as particularly odd, so I'm looking forward to finding out what the cause might be 😁

**Comment by weiznich** [comment]
Seems like "user" is a reserved keyword in postgresql. You need to explicit quote your table names in such cases, so the following migration works fine:
```sql
CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL,
)
```

Closed as this is not a diesel issue.
