### ISSUE TITLE
Cannot use embedded_migrations with rocket DbConn

### ISSUE THREAD

**Issue by miiila** [diesel-rs/diesel#2477]
### Versions

- **Rust:** 1.46.0-nightly
- **Diesel:** 1.4.4
- **Database:** Postgres
- **Operating System** MacOS

### Feature Flags

- **diesel:**

### What are you trying to accomplish?
I want to run embedded migrations macro together with Rocket way of handling db connection (https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html).

### What is the expected output?
I can pass a connection to migrations.

### What is the actual output?
```
error[E0614]: type `fn(db::embedded_migrations::diesel::r2d2::PooledConnection<<db::embedded_migrations::diesel::PgConnection as rocket_contrib::databases::Poolable>::Manager>) -> db::PostgresDbConn {db::PostgresDbConn}` cannot be dereferenced
```

### Are you seeing any additional errors?
Nothing relevant

### Steps to reproduce

```
use rocket_contrib::database;
use rocket_contrib::databases::diesel;

#[database("postgres")]
pub struct PostgresDbConn(diesel::PgConnection);

embed_migrations!("./migrations/");

pub fn run_migrations() {
    embedded_migrations::run_with_output(&*PostgresDbConn, &mut std::io::stdout()).unwrap()
}
```

Based on the link above, this should be the right approach to get raw PgConnection.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

(rocket requires Nigthly for now, but should be gone very very soon, so I hope it still qualifies :-))

Thank you for all your help and big kudos for such a great library!

**Comment by weiznich** [comment]
As this involves a `rocket` provided `Connection` type I cannot see how this is related to diesel. If `rocket` decided to provide a wrapper type around our connection types it's their responsibility to implement the traits required by `diesel`. Or to word it differently: To fix that we would need to depend on `rocket` end implement the corresponding trait for their types, which is not possible because that would be then a cyclic dependency. Please raise this in the rocket issue tracker.

Closed as this is no issue we can fix on our side.

**Comment by miiila** [comment]
@weiznich Thanks for the explanation, I was wondering where should I post this and decided to start here, especially as it looks like it is related to migration. If I am reading the error message correctly, it complains about the `db::embedded_migrations::diesel::r2d2::PooledConnection` type that cannot be dereferenced (if I am talking nonsense, bear with me, I am still learning Rust domain :-)).

Is there anything special about the migration that would require special handling? I will definitely raise this with Rocket, however I would like to understand more the migration case as it looks like it works ok in standard usage.

Thank you again for the help.

**Comment by weiznich** [comment]
The error message mentions some function like type that seems to coming from rocket itself. So rustc bascially complains here that you cannot dereference a reference to a function. (As I do not use rocket by myself I'm not sure what this type represents and where it is comming from. It's probably generated by the `#[database("postgres")]` proc macro attribute there.

As for calling `embedded_migrations::run_with_output`: It will accept a reference to any type that implements [`diesel_migration::MigrationConnection`](http://docs.diesel.rs/1.4.x/diesel_migrations/trait.MigrationConnection.html).

**Comment by miiila** [comment]
@weiznich Thank you very much for the explanation, makes sense.
