### ISSUE TITLE
The repository homepage-link should point to a https-origin, but doesn't

### ISSUE THREAD

**Issue by Bernd-L** [diesel-rs/diesel#2481]
On the [diesel repository page](https://github.com/diesel-rs/diesel) the link points to <http://diesel.rs/>, but it should point to <https://diesel.rs/>.

![image](https://user-images.githubusercontent.com/18219148/89797624-6bfc6080-db2b-11ea-81c2-780efeb09596.png)

Not a big deal, but I thought it was worth mentioning 🤷

**Comment by dsluo** [comment]
This is because the repository page doesn't force https. See #1073.

**Comment by Bernd-L** [comment]
> This is because the repository page doesn't force https. See #1073.

Why does it force http? Furthermore, if someone, for some reason *really* wants http, then they could still remove the s from their address bar.

Https has long become the default and is what most users expect. I think it's wrong to assume that people want http instead of the more secure variant.

Official links in the documentation should always point to https.  
And so should the one in the description this issue is about.

By the way: GitHub pages supports https: <https://github.blog/2018-05-01-github-pages-custom-domains-https/> (as pointed out here: https://github.com/diesel-rs/diesel/issues/1073#issuecomment-454028331


Please *fix* this *issue*.

**Comment by dsluo** [comment]
It doesn't force http. It just doesn't force either http or https.
