### ISSUE TITLE
cargo updating diesel to use uuid 0.8.1

### ISSUE THREAD

**Issue by btv** [diesel-rs/diesel#2483]
### Versions

- **Rust:**: 1.45.2
- **Diesel:**: 1.4.5
- **Database:** Postgres11
- **Operating System**: Arch Linux

### Feature Flags

- **diesel:**`{ version = "^1.4", features = ["postgres", "r2d2", "uuidv07", "chrono", "network-address", "serde_json"] }`
- **uuid:** `{ version= ">=0.7.0, <0.8", features=["serde", "v4"] }`

## Problem Description
When running `cargo update`, even with `uuidv07` set, it downloads and tries to compile diesel with uuid 0.8.1 in diesel.

I have a code base that is working with uuid version `0.7.4` and it compiles without issue. Without changing anything in `Cargo.toml`, `cargo update` is updating diesel to use uuid 0.8.1. As seen here from an exert from `cargo tree`:

```
── diesel v1.4.5
│   ├── bitflags v1.2.1
│   ├── byteorder v1.3.4
│   ├── chrono v0.4.13 (*)
│   ├── diesel_derives v1.4.1
│   │   ├── proc-macro2 v1.0.19 (*)
│   │   ├── quote v1.0.7 (*)
│   │   └── syn v1.0.38 (*)
│   ├── ipnetwork v0.16.0
│   │   └── serde v1.0.115 (*)
│   ├── libc v0.2.74
│   ├── pq-sys v0.4.6
│   ├── r2d2 v0.8.9
│   │   ├── log v0.4.11 (*)
│   │   ├── parking_lot v0.11.0 (*)
│   │   └── scheduled-thread-pool v0.2.5
│   │       └── parking_lot v0.11.0 (*)
│   ├── serde_json v1.0.57 (*)
│   └── uuid v0.8.1
```

### What is the actual output?
I get lots of errors similar to:
```
#[derive(Debug, Clone, Serialize, Deserialize, Insertable, Default)]
   |                                                ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `uuid::Uuid`
```

### Are you seeing any additional errors?
No, all errors are related to copies of the one above.

### Steps to reproduce

* Have configuration of `uuid` and `diesel` crates as above.
* Create a datatype that has `#[derive(Insertable)]`
* run `cargo build`

Thank you in advance for your help. I'm happy to help in anyway that I can with this.
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Cargo pulls in the latest available version by default. That's nothing under what diesel can control. We support both `uuid 0.7` and `uuid 0.8`. To force cargo into choosing `uuid 0.7` you can use `cargo update -p "uuid:0.8.1" --precise=0.7.4`

**Comment by btv** [comment]
Thank you for the comment and for showing how to do a cargo update to avoid this issue, I do appreciate the hand holding. Quick question, in your response you say that you support uuid 0.8, but my situation above doesn't seem to reflect that. If uuid 0.8 compiled without an error I wouldn't have opened a ticket. Is that statement based on the future v2 release? Is there another package feature like `uuidv8` that I'm not aware of? Any information to help with my understanding is greatly appreciated.

**Comment by weiznich** [comment]
> If uuid 0.8 compiled without an error I wouldn't have opened a ticket. Is that statement based on the future v2 release? Is there another package feature like uuidv8 that I'm not aware of? Any information to help with my understanding is greatly appreciated.

[Diesel 1.4.5 already supports uuid 0.8.x](https://github.com/diesel-rs/diesel/blob/1.4.x/diesel/Cargo.toml#L27) behind the `uuidv07` feature flag. Diesel 2.0 will just cleanup the feature flags in such a way that we drop support for uuid versions < 0.7. In fact your `cargo tree` output already shows `uuid 0.8.1` as direct dependency of diesel, so I do not understand what you actually request here from diesel. (As pointed out above choosing `uuid 0.8` instead of `uuid 0.7` what seems to be required from some other dependency of your application is something that is done by cargo and not by diesel. We cannot control that.)

**Comment by btv** [comment]
Thank you again for the explanation. Your `cargo update -p "uuid:0.8.1" --precise=0.7.4` command is what's working for me. I still need to figure out why my application isn't following the same version requirements in cargo. But, to your point, that's not diesel's problem; that's mine.
