### ISSUE TITLE
Feature request: add an `optional` expression method for build conditional queries.

### ISSUE THREAD

**Issue by s97712** [diesel-rs/diesel#2492]
Consider the following usage:
```rust
let keyword = Some("%keyword%");

schema::post::table
 .filter(title.optinoal().like(title))
 .or_filter(summary.optinoal().like(keyword))

```
When the keyword is `None`, the where clause will be `where true or true`, when keyword is `Some("%keyword%")`,  the where clause will be `where title like '%keyword%' or summary like '%keyword%'`.
That will be make it easier to build conditional queries.

**Comment by weiznich** [comment]
It's not clear for me what's the advantage of this approach over the following already supported approach:

```rust
let mut query = schema::post::table.into_boxed();

if let Some(title) = title {
    query = query.filter(schema::posts::title.like(title));
}

if let Some(keyword) = keyword {summary
    query = query.or_filter(schema::post::summary.like(keyword));
}
```

In contrast to the proposed approach this generates exactly the query you specify and does not introduce some place holder statements on sql side.

I'm closing this issue as it is not clear for me what are the advantages of this approach + it is definitively possible to implement as that as third party crate.
```
