### ISSUE TITLE
database connection url encoding

### ISSUE THREAD

**Issue by ChristianYeah** [diesel-rs/diesel#2493]
I tried to connect to the test server with / in the password, the connection string like, ```mysql://user:abc/BDE@127.0.0.1:3306/db```

this will raise error like
```
port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'abc'
```

I tried to use percent-encoding like  ```mysql://user:abc%2FBDE@127.0.0.1:3306/db```

however, this causes connection failed, error code 1045, (using password: YES)

I tried the username & password in DataGrip, it works as normal.

**Comment by p-alik** [comment]
I guess that's an issue for underlying [url](https://docs.rs/url/2.1.1/url/) crate.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b2612afaf1d6d782dd79766461e15636

**Comment by ChristianYeah** [comment]
> I guess that's an issue for underlying [url](https://docs.rs/url/2.1.1/url/) crate.
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b2612afaf1d6d782dd79766461e15636

In case of I percent-encoded the password, and at the mean time, despite the urlsplit problem, I believe it's the problem from aiomysql as well. The password from site-packages/databases/core.py:412 returns unquoted password(as I've already encoded), the aiomysql connect method won't unquote the password as well, and it passes the quoted password directly.

**Comment by weiznich** [comment]
As explained in the url crate issue that's how urls work, therefore I'm closing this issue as won't fix.
