### ISSUE TITLE
pgAdmin 4 issue

### ISSUE THREAD

**Issue by sunnyseeds** [diesel-rs/diesel#2496]
I'm using pgAdmin 4 and whenever I try run diesel setup I get the following error:

Creating database: test_diesel
authentication method 10 not supported

**Comment by p-alik** [comment]
That's no issue for this repository. See https://www.postgresql-archive.org/pgadmin4-2-0-and-Scram-td5987040.html

**Comment by sunnyseeds** [comment]
> That's no issue for this repository. See https://www.postgresql-archive.org/pgadmin4-2-0-and-Scram-td5987040.html

Thanks for your reply and for providing the link but I'm still unable to connect with diesel. 
I'm able to connect with deadpool_postgres automatically without changing anything but whenever I use diesel I get the error above.

**Comment by weiznich** [comment]
That's definitively a configuration issue on postgres side, so nothing actionable for our issue tracker. Therefore I'm closing this issue now. 
Feel free to use our gitter channel to ask for help, but please provide all necessary information.
