### ISSUE TITLE
within `MysqlConnection`, the trait `Sync` is not implemented for `NonNull<mysqlclient_sys::st_mysql>`

### ISSUE THREAD

**Issue by whizsid** [diesel-rs/diesel#2497]
# Setup

I want to share my mysql connection across multiple `tokio` threads using `diesel::r2d2` module.

```rust

extern crate diesel;
extern crate r2d2;
extern crate tokio;

use diesel::mysql::MysqlConnection;
use diesel::r2d2::ConnectionManager;

fn main() {
    let manager = ConnectionManager::<MysqlConnection>::new("mysql://localhost/mydb");
    let pool = r2d2::Pool::builder().build(manager).expect("Failed to create pool.");

    for _ in 0..2{
        let pool = pool.clone();
        tokio::spawn(async move {
            let connection = pool.get().unwrap();

        });
    }
}
```

### Versions

- **Rust:** rustc 1.48.0-nightly (73dc675b9 2020-09-06)
- **Diesel:** 1.4.5
- **Database:** mysql
- **Operating System** Arch Linux

### Feature Flags

- **diesel:** mysql, chrono, r2d2

### What is the expected output?

Share my MysqlConnection across tokio async threads.

### What is the actual output?

```
error: future cannot be sent between threads safely
   --> src/browsers.rs:43:9
    |
43  |         tokio::spawn(async move {
    |         ^^^^^^^^^^^^ future created by async block is not `Send`
    |
   ::: /home/ramesh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/spawn.rs:127:21
    |
127 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::spawn`
    |
    = help: within `MysqlConnection`, the trait `Sync` is not implemented for `NonNull<mysqlclient_sys::st_mysql>`
note: future is not `Send` as this value is used across an await
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Database connections are fundamentally not `Sync`. Therefore that's not possible. You may want to share the pool itself across the async boundary.

Closed as everything works as expected.

**Comment by whizsid** [comment]
@weiznich  I could reproduce it. But figured it out. I have used the same db connection after called an async function. We need to create a new database connection after an each async function called.

***Wrong***
```rust
let db = pool.get().unwrap();

get_seller(&db);

foo().await;

get_product(&db);
```

***Solution***
```rust
let db = pool.get().unwrap();

get_seller(&db);

foo().await;

let pool = pool.clone();
let db = pool.get().unwrap();

get_product(&db);

```
