### ISSUE TITLE
raw identifier's prefix not dropped when matching column names

### ISSUE THREAD

**Issue by toxeus** [diesel-rs/diesel#2501]
### Problem Description

Using a `QueryableByName` struct with raw identifiers will end up using the `r#` raw identifier prefix when matching the column name.

### What are you trying to accomplish?

I'm trying to populate a struct by using `sql_query()` on a column which name is a reserved rust keyword. Therefore, a raw identifier is used in the struct: `r#type`.

### What is the expected output?

I'd expect no errors and a successful serialization of the struct. As a workaround, some attribute macro that allows to override the column name would also work. Please note, that the column doesn't appear in `table!` where an attribute macro for overriding the name would exist.

### What is the actual output?

> Column `r#type` was not present in query

### Are you seeing any additional errors?

No.

### Steps to reproduce
```rust
#[test]
fn raw_identifiers() {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, QueryableByName)]
    struct Foo {
        #[sql_type = "Integer"]
        r#type: i32,
    }

    let conn = connection();
    let data = sql_query("SELECT 1 AS type").get_result(&conn);
    assert_eq!(Ok(Foo { r#type: 1 }), data);
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
So I've rechecked the documentation of [`QueryableByName`](https://docs.diesel.rs/1.4.x/diesel/deserialize/trait.QueryableByName.html#deriving) here. It states the following:

>If the name of a field on your struct is different than the column in your table! declaration, or if you are deriving this trait on a tuple struct, you can annotate the field with #[column_name = "some_column"]. For tuple structs, all fields must have this annotation.

Which means there is a way to specify the name of the column explicitly. 

I'm closing this issue now as this is "fixed" in my opinion. Having seperate rules for raw identifiers don't seem like a good idea for me. Using the provided attribute is the much better solution for any non default behavior in my opinion.
