### ISSUE TITLE
No support for txid_snapshot data type of postgresql

### ISSUE THREAD

**Issue by yihuang** [diesel-rs/diesel#2505]

**Comment by weiznich** [comment]
Closed because issue does not contain any information that could be used to reproduce it.

**Comment by yihuang** [comment]
> Closed because issue does not contain any information that could be used to reproduce it.

Added exact script to reproduce it now.

**Comment by weiznich** [comment]
We do not plan to provide support for this type out of the box, therefore this issue remains closed as everything works as indented. If you want to add support for this type on your own as third party crate, have a look at the custom types draft guide in this repository.
