### ISSUE TITLE
SQlite database 'is' and 'is not' operators are missing

### ISSUE THREAD

**Issue by zdenek-crha** [diesel-rs/diesel#2513]
### Versions

- **Rust:**  1.40
- **Diesel:** 1.4.5
- **Database:** SQLite
- **Operating System** GNU/Linux (Debian)

### Feature Flags

- **diesel:**  [ "sqlite" ]

## Problem Description

The sqlite operators `is` and `is not` are not available in expression dsl.

### What are you trying to accomplish?

I have a database with two nullable columns which both hold uuid (last uuid seen on remote and last uuid archived localy). To see which rows in the table are elegible for archiving, I have to select all rows where `last_seen` and `last_archived` are not equal. Ie either one of them is `NULL` or both are set and their values differ.

There are rows with all combinations of those two columns in database. 

Using  `filter(dsl::last_seen.ne(dsl::last_archived))` which generates SQL query using `!=` operator and **returns empty result set**. I've run the SQL directly on  database directly and the behaviour is exactly same. 

I have been pointed to `is` and `is not` sqlite operators that allow comparison with null (https://sqlite.org/lang_expr.html, section 2) and when I replace `!=` with `is not` the query returns expected results.

Unfortunately, `diesel` does not support those operators for `sqlite` database.

**Comment by weiznich** [comment]
As a official supported workaround you can just use [`diesel_infix_operator!`](http://docs.diesel.rs/1.4.x/diesel/macro.diesel_infix_operator.html) to define your own version of this operators. 
Given that workaround this issue is for me not high priority, which means I would happily accept a PR adding support for this features as long as it is well written, but I will not work on support for this myself.

**Comment by zdenek-crha** [comment]
@weiznich Thanks for pointing me to the `diesel_infix_operator!`, I will give it a try.

**Comment by Voodlaz** [comment]
@weiznich I want to work on this

**Comment by weiznich** [comment]
@Voodlaz Sure feel free to submit a PR

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
@weiznich Can you provide some help please? I'm not quite sure how to support these two operators, is there an example I can refer to?

**Comment by weiznich** [comment]
@hi-rustin Those two operators are very similar to `IS DISTINCT FROM` and `IS NOT DISTINCT FROM` for the postgresql backend. This means you can use the implementation of those operators as general orientation which parts are required:

* [Definition of the corresponding operators](https://github.com/diesel-rs/diesel/blob/fe989447932a6c6674d0f781bd5e715d21518d73/diesel/src/pg/expression/operators.rs#L5-L6). 
* [Implementation of the corresponding expression dsl extension](https://github.com/diesel-rs/diesel/blob/fe989447932a6c6674d0f781bd5e715d21518d73/diesel/src/pg/expression/expression_methods.rs#L10-L66)
* [Definition of the corresponding helper types](https://github.com/diesel-rs/diesel/blob/fe989447932a6c6674d0f781bd5e715d21518d73/diesel/src/pg/expression/helper_types.rs#L18-L24)

As we don't have any sqlite specific expression methods yet, you also need to reexport the corresponding types/traits at the right locations:
* [Helper types](https://github.com/diesel-rs/diesel/blob/fe989447932a6c6674d0f781bd5e715d21518d73/diesel/src/expression/helper_types.rs#L119-L121)
* [Expression dsl methods](https://github.com/diesel-rs/diesel/blob/fe989447932a6c6674d0f781bd5e715d21518d73/diesel/src/expression_methods/mod.rs#L24-L26)
