### ISSUE TITLE
Duplicate foreign keys are silently dropped in print-schema output

### ISSUE THREAD

**Issue by e-fominov** [diesel-rs/diesel#2524]
### Versions

- **Rust:** rustc 1.48.0-nightly (f68e08933 2020-09-19)
- **Diesel:** diesel 1.4.1
- **Database:** PostgreSQL 12
- **Operating System** Ubuntu 20.04

### Feature Flags

- **diesel:** postgresql

## Problem Description

Tables with multiple foreign keys pointing the same target are silently dropped from joinable! macro outputs of print-schema

### What are you trying to accomplish?

I want to have a table with two foreign keys pointing the same target table.
Use case: I want to track object positions in warehouse. Each object has current position and default position where it should be returned after use. 

### What is the expected output?

Expecting to have joinable! for both possible joins, or at least for one, or at least a warning message.

### What is the actual output?

no joinable! in schema.rs for the table with two foreign keys

### Are you seeing any additional errors?

diesel print-schema silently ignores the problem

### Steps to reproduce

Here is valid PostgreSQL schema
```
CREATE TABLE A
(
    id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4()
);
CREATE TABLE B
(
    id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    current_A UUID,
    default_A UUID,
    CONSTRAINT fk_B_A_current
        FOREIGN KEY (current_A)
            REFERENCES A(id)
            ON DELETE RESTRICT,
    CONSTRAINT fk_B_A_default
        FOREIGN KEY (default_A)
            REFERENCES A(id)
            ON DELETE RESTRICT
);
```

running ```diesel print-schema``` will produce no joinable! marcos in schema.rs . But if I remove one of constraints (any), it will produce one

here is the line in source code which drops them: https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/infer_schema_internals/foreign_keys.rs#L40

This workaround works for me: 
1. define both foreign keys in PostgreSQL schema
2. keep diesel print-schema generate no joinable!
3. write it manually outside of schema.rs with first foreign key
4. second foreign key join can used in joins by explicitly calling  `.left_join(table.on(...))` syntax

Most simple solution is to output one join and drop second, this will keep everything working 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
This is expected behavior as otherwise `first::table.inner_join(second::table)` would be ambiguous.
