### ISSUE TITLE
Unable to launch Rocket with Diesel on Alpine container 

### ISSUE THREAD

**Issue by jcvar** [diesel-rs/diesel#2526]
### Versions

- **Rust:** nightly x86_64-unknown-linux-musl
- **Diesel:** 1.4.5
- **Database:** MySQL 8.02
- **Operating System:** Alpine (I believe 13.2)

### Feature Flags

- **diesel:** mysql

## Problem Description

Can't run Rocket app inside an Alpine Linux container.

I can't get Diesel to establish a database connection when launching my container. I've been trying to troubleshoot this issue for several hours now and finally made some progress that can narrow this issue down. 

### What are you trying to accomplish?

Run a Rocket app with Diesel inside a container based on Alpine Linux.

Making an image which includes all build files from cargo isn't an option, so with a two-stage build, I repackage my app's binary in a container with a lighter base image. After several compile errors, I found it was necessary to install MySQL's client in order to `cargo build --release`.

To my understanding, when building with cargo all libraries are statically linked, needing nothing outside of them to run. To test a lighter image, I used Debian, which is what the rust images use as base, to create the final image and it needed the MySQL client in order to run as expected (easily installed, just as it's done to compile).

Now, to go even lighter, using the `x86_64 musl` target for Alpine, there are no issues using the same MySQL libs to compile,
and it requires a MySQL client as well to run, but whichever way I choose to install it (`mysql-client`, `mariadb-client`, `mariadb-dev`), my app stops just as it fetches the config params from Rocket.toml.
 
### What is the expected output?

Launch Rocket app, with Diesel connection pool.

### What is the actual output?

Program stops after displaying Rocket config parameters, including database details as the last line, and before the 'launched' success message:
```
=> [extra] databases: { mysql_db = { url = "mysql://user:pass@dburl.amazonaws.com/db-name" } }
``` 

### Are you seeing any additional errors?

No, changing Rocket's log variable has no effect.

### Steps to reproduce

Clone repo:
```
git clone https://github.com/GraderUN/subject-ms.git
```
Set login data for a MySQL database in Rocket.toml
```toml
[global.databases]
mysql_db = { url = "mysql://user:pass@dburl.amazonaws.com/db-name" }
```
Run migrations
```
diesel migration run
```
Build Docker image 
```
docker build -t subject:alp -f Dockerfile.alp .
docker run -p 4000:4000 subject:alp
```

Expected output can be reached with a Debian image as base:
```
docker build -t subject:deb -f Dockerfile.deb .
docker run -p 4000:4000 subject:deb
``` 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case) `(Rocket expects rust nightly)`

Thank you for reading this issue, I hope there is a solution as easy as it was to code using this package.

**Comment by weiznich** [comment]
We do not support rust nightly. Please provide a minimal reproduciple example that does not requiere rocket or any other non requiered third party dependency.

**Comment by jcvar** [comment]
Understood, I'll iterate on the examples and update if necessary.
Thank you.

**Comment by jiangxiaoqiang** [comment]
> 

did you fixed this problem, I am facing the same issue.

**Comment by jiangxiaoqiang** [comment]
did you fixed this problem, I am facing the same issue.  @jcvar

**Comment by weiznich** [comment]
@jiangxiaoqiang Our issue tracker is no support forum, but a platform for contributors to organize their work. So please don't use it to ask for support here. Use the discussion forum for such questions and include all relevant details (diesel version, relevant code, error message, ...) there.
