### ISSUE TITLE
Joins with sql_query where column names conflict

### ISSUE THREAD

**Issue by cameronpickham** [diesel-rs/diesel#2543]
The root of my issue is Diesel's inability to perform multiple joins on the same table in a single query (due to the lack of aliasing). My attempt at a workaround is to construct a raw query using `sql_query`. However, when there are columns of the same name across multiple tables in the query, the deserialization results in column values being overwritten by the values of that column from the other table. What is the suggested approach?

**Comment by weiznich** [comment]
You need to indroduce unique names via `expr as some_name` for each column in your select clause.

As you already know joining a table more that once is currently not easily possible via the diesel dsl, as this would require support for aliasing. There is #2254 for that. Something like that can be adjusted to work to work in third party crates.
