### ISSUE TITLE
Feature request: implement Rocket's Responder trait for Diesel errors behind a feature gate

### ISSUE THREAD

**Issue by tbarusseau** [diesel-rs/diesel#2552]
### What do you want to do, and how do you expect Diesel to support you with that?

Implement [Rocket's `Responder` trait](https://api.rocket.rs/v0.4/rocket/response/trait.Responder.html) for Diesel errors.

This would allow Rocket + Diesel code to directly return errors through `?` in routes without any boilerplate code.

This would also allow much more detailed Rocket responses, since we would have much more error information at hand than going through a wrapper type, which means losing information.

### How might this be added to Diesel?

This could be added in-source, behind a feature flag, but it would probably not be desirable as it would mean adding `rocket` as a `diesel` dependency. As such, it could probably be possible to work similarly to `rocket` with a `diesel-contrib` crate? Full disclosure, I don't really know if that's easily achievable with the current codebase.

### What are possible alternatives?

The same alternative there is to implementing foreign traits on foreign types: create a wrapper type and `impl` the foreign trait on this type, then `impl` `From<OriginalType>` on your wrapper type.

### Are there any disadvantages?

I don't think there are but would love to hear about it if there are some.

If that's possible, I'd love to implement it myself, but I'm not sure where to look in the source code :smiley:

**Comment by weiznich** [comment]
Is there any reason why this needs to be done in diesel and cannot be done in rocket or a third-party crate? 
I really do not want to add rocket as dependency of diesel for the following reasons:

* It is nightly only (at least for now), that's a no-go for diesel.
* It is a quite heavy dependency in term of number of sub-dependencies. For adding such a dependency I really want to see more justification than "just": It makes integrating with this framework easier where only a fraction of diesels user base is using that framework.

Additionally rocket is already providing methods to integrate [diesel with rocket](https://docs.rs/rocket_contrib/0.4.5/rocket_contrib/databases/index.html#provided). I believe the best place for providing such a integration would be this crate, as there is already some integration there.
