### ISSUE TITLE
undefined reference to `sqlite3_create_function_v2'

### ISSUE THREAD

**Issue by capripio** [diesel-rs/diesel#2560]
### Versions

- **Rust:** 2018
- **Diesel:** diesel = { version = "1.4.4", features = ["sqlite", "r2d2", "chrono"] }
- **Database:** sqlite3
- **Operating System** Centos 6.9

## Problem Description

I am trying to compile my rust application and getting following error.

  = note: /root/actix-web-app/target/debug/deps/libdiesel-eac6304bb856f51c.rlib(diesel-eac6304bb856f51c.diesel.cvxxcjjw-cgu.15.rcgu.o): In function `diesel::sqlite::connection::raw::RawConnection::register_sql_function::h4bb9882fd4031b1f':
          /root/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.5/src/sqlite/connection/raw.rs:87: undefined reference to `sqlite3_create_function_v2'
          collect2: ld returned 1 exit status

### What are you trying to accomplish?

Compile Actix Web App

### Are you seeing any additional errors?

same error message when tried to install diesel-cli

## Checklist

- [ ✔] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [✔ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
`sqlite3_create_function_v2` was added in libsqlite3 version 3.7.3 released in 2010. This error message indicates that you are using a libsqlite3 that is missing this function, either because your verion is more than 10 years old or because you use a patched variant of libsqlite3. Both is not supported by diesel.
