### ISSUE TITLE
Document out-of-order migrations behaviour.

### ISSUE THREAD

**Issue by kevincox** [diesel-rs/diesel#2561]
## Problem Description

I can not find any documentation for how Diesel handles out-of-order migrations. Will it skip them, apply them, raise an error or do something else?

### What are you trying to accomplish?

When working on a team, migrations may be added in different changes. If the higher number migrations gets merged first the lower number one still needs to be applied.

### What is the expected output?

Ideally all migrations would be run exactly once. But any way this needs to be documented.

### What is the actual output?

It is not documented.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
It's documented [here](https://github.com/diesel-rs/diesel/blob/fef3b93824bc7abaae0b3f41c9c2ca6b984bb027/diesel_migrations/migrations_internals/src/lib.rs#L116-L128)
