### ISSUE TITLE
pool builder max_size unable to set `max_user_connections`

### ISSUE THREAD

**Issue by subhojit777** [diesel-rs/diesel#2562]
## Setup

Rust web-app using actix-web interacting with MySQL database via diesel.

### Versions

- **Rust:** rustc 1.47.0 (18bf6b4f0 2020-10-07)
- **Diesel:** diesel v1.4.2
- **Database:** mysql  Ver 8.0.13 for macos10.14 on x86_64 (MySQL Community Server - GPL)
- **Operating System** macOS v10.15.6

### Feature Flags

- **diesel:** ["mysql", "chrono", "r2d2"]

## Problem Description

`Pool::builder().max_size(1)` is not restricting MySQL's configured `max_user_connections`. `max_user_connections` is set to 1, however the pool is unable to restrict the maximum number of connection. `max_size()` should be able to do it, however it is not working.

Although the `dbg` outputs 1 here, but I am still getting the error `User <username> already has more than 'max_user_connections' active connections` when I run the app.

```rust
        let pool = Pool::builder()
            .max_size(max_database_pool_size)
            .build(manager)
            .expect("Failed to create pool.");
        dbg!(pool.max_size());
```

FYI: the `MAX_DATABASE_POOL_SIZE` variable is set as 1.

### What are you trying to accomplish?

I want to control the maximum number of connections the pool can have.

### What is the expected output?

With database's `max_user_connections` set as 1, and with `Pool::builder().max_size(1)` I should be able to initiate the app successfully.

### What is the actual output?

```
[src/bin/index.rs:34] pool.max_size() = 1
[2020-11-10T03:54:26Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:27Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:28Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:29Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:32Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:39Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
[2020-11-10T03:54:52Z ERROR r2d2] User questionnaire already has more than 'max_user_connections' active connections
thread 'actix-rt:worker:1' panicked at 'Failed to create pool.: Error(Some("User questionnaire already has more than \'max_user_connections\' active connections"))', src/bin/index.rs:33:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt:worker:3' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/subhojit/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/server.rs:250:36
thread 'actix-rt:worker:2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/subhojit/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/server.rs:250:36
```

### Are you seeing any additional errors?

No

### Steps to reproduce

Cargo.toml

```toml
actix-web = { version = "2.0.0", features = ["openssl"] }
diesel = { version = "^1.4", features = ["mysql", "chrono", "r2d2"] }
dotenv = "0.13.0"
```

.env

```
MAX_DATABASE_POOL_SIZE=1
```

main.rs

```rust
async fn greet(req: HttpRequest) -> impl Responder {
    let name = req.match_info().get("name").unwrap_or("World");
    format!("Hello {}!", &name)
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();
    env_logger::init();

    HttpServer::new(|| {
        let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set.");
        let max_database_pool_size: u32 = env::var("MAX_DATABASE_POOL_SIZE")
            .unwrap()
            .as_str()
            .parse::<u32>()
            .unwrap();
        let manager = ConnectionManager::<MysqlConnection>::new(database_url);

        let pool = Pool::builder()
            .max_size(max_database_pool_size)
            .build(manager)
            .expect("Failed to create pool.");
        dbg!(pool.max_size());

        App::new()
            .data(pool.clone())
            .route("/", web::get().to(greet))
            .route("/{name}", web::get().to(greet))
    })
    .bind("0.0.0.0:8088")
    .unwrap()
    .run()
    .await
}
```

diesel print-schema

```
table! {
    answers (id) {
        id -> Integer,
        user_id -> Integer,
        created -> Timestamp,
        option_id -> Integer,
    }
}

table! {
    options (id) {
        id -> Integer,
        data -> Varchar,
        user_id -> Integer,
        question_id -> Integer,
        created -> Timestamp,
    }
}

table! {
    presentations (id) {
        id -> Integer,
        title -> Varchar,
        user_id -> Integer,
        created -> Timestamp,
    }
}

table! {
    questions (id) {
        id -> Integer,
        title -> Varchar,
        created -> Timestamp,
        presentation_id -> Integer,
        user_id -> Integer,
    }
}

table! {
    users (id) {
        id -> Integer,
        name -> Varchar,
        created -> Timestamp,
    }
}

allow_tables_to_appear_in_same_query!(
    answers,
    options,
    presentations,
    questions,
    users,
);
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
A few things to note here:

* Can you reproduce that issue without using any third party dependency like `actix_web`? If not then this sounds like `actix_web` is not behaving like you expected, by for example creating more than one pool as part of the startup process. Then that's clearly not a diesel/r2d2 issue. Your log messages make it at least plausible that actix is calling the initialization closure more than once.
* Diesel is not implementing the pool mechanism itself, we are using the [`r2d2` crate](https://github.com/sfackler/r2d2) here. If you really believe that's an issue with the connection pooling and not your usage you should report an issue there, but without any third party dependency (read: without `actix_web` and without `diesel`)

**Comment by subhojit777** [comment]
I was indeed not able to see the error after I moved the pool creation out of the HttpServer closure, however the app stopped working. I don't think this issue is related to diesel. Thank you!
