### ISSUE TITLE
Document boxed functions

### ISSUE THREAD

**Issue by fishrockz** [diesel-rs/diesel#2568]
How should I define functions that return boxed queries?

Some queries end up being used a lot, I have a standard query that many other functions use and build upon.

But the return types end up being HUGE https://gitlab.com/pointswaves/points-that-need-doing/-/blob/master/src/routes_site.rs#L158

Is there a way to use the types defined in my models.rs or schema.rs to define the return type rather than the raw diesel types?

If some one could point me to the right bit of the docs? or failing that, Can some one explane how to do this and where the doc should live and i am happy to add some

**Comment by weiznich** [comment]
First of all: `BoxedSelectStatement` is not part of our public api. Types that are not documented in our API documentation are not covered by any semver considerations. They can change at any point in time and we do not provide support for them. To refer to such types in a supported way you may want to use the type defs from `diesel::dsl` and [that one](https://docs.diesel.rs/1.4.x/diesel/macro.table.html#boxedquery) from the `table!` macro.

**Comment by weiznich** [comment]
I should add here that we would be happy to receive a PR improving the discoverability of this features.
