### ISSUE TITLE
Do diesel really need up.sql & down.sql ?

### ISSUE THREAD

**Issue by erihsu** [diesel-rs/diesel#2573]
After diesel migration, it automatically generate database schema according to **up.sql**, which define the structure with table macro. However, after generating schema, do I really need sql file further ?

**Comment by weiznich** [comment]
You don't need any migrations to generate your schema. Diesel happily generates a db schema from an existing database.
Closed as our issue tracker is not the right place for asking questions. Please use our forum or our gitter channel for questions.
