### ISSUE TITLE
Unexpected CLI dynamic link error

### ISSUE THREAD

**Issue by tema3210** [diesel-rs/diesel#2575]
### Versions

- **Rust:** 1.48.0
- **Diesel:** 1.4.5
- **Database:** PostgreSQL 12
- **Operating System** Windows 10

### Feature Flags

- **diesel:** no-default-features, postgres

## Problem Description
I was trying to install **diesel-cli**, but cargo error was on linking with complain that it cannot open "libpq.lib".
I copy-pasted this lib into cargo link path\ (after last didn't work) modified `\.cargo\config` included link path as following:
```toml
[target.x86_64-pc-windows-msvc.pq]
rustc-link-search = ["C:\\Program Files\\PostgreSQL\\12\\lib"]
rustc-link-lib = ["libpq"]
```
then i got `diesel-cli` compiled, but it didn't work: it was asking for dynamic `libpq.dll`; after i inserted it in place along with diesel binary i got this:
 ```
playa@DESKTOP-UTUMEU6 MINGW64 ~/.cargo/bin
$ diesel
C:/Users/playa/.cargo/bin/diesel.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

### Steps to reproduce
I did `cargo install diesel-cli --no-default-features --features postgres
` using MINGW64 bash and faced link problem.
When I fixed that, I got dynamic link error.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
This is an error message that indicates that your environment is not configured correctly. You need to make `libpq.dll` available for the dynamic linker used on your platform. Please checkout the manual of the your platform/the dynamic linker used by your platform on how to do this.

Closed as this is not a diesel issue + our issue tracker is not the right place to ask questions. Use the gitter channel or our forum for that.

**Comment by Archsx** [comment]
Have you solved the problem? I got the same problem..

**Comment by Archsx** [comment]
Here I  record how I solved this problem , hoping to help people who come across this page later. I'm using windows 10, things went well until execute
 
`diesel setup`

 I got error: 

`error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

I got no clue about what was missing.  I found the path to diesel.exe is `C:\Users\myName\.cargo\bin\diesel`,  just double click it   and it shows it can't find three file: *libintl-9.dll*, *libcrypto-1_1-x64.dll*,  and *some dll file I just forgot its name*.  anyway, These three files are actually located in the folder 

`C:\Program Files\PostgreSQL\14\bin`

add it to PATH variable 

after that, maybe you should retart computer .

it is a workaround, but it works.

**Comment by willmendil** [comment]
that did. The error should indecate that this could be a solution
