### ISSUE TITLE
Problem to add backend to support odbc driver to sql server/oracle.

### ISSUE THREAD

**Issue by unitsoftrover** [diesel-rs/diesel#2578]
I am interesting to add odbc to diesel based the exists mysql backend. I change the mysql mod name and feature to odbc, and modified some statement "::mysql::" to "::odbc::" in diesel basic code. when compile, reasy problem:
error[E0277]: the trait bound `odbc::backend::Mysql: sql_types::HasSqlType<sql_types::Timestamp>` is not satisfied
   --> diesel\src\query_builder\insert_statement\mod.rs:464:6
    |
464 | impl QueryFragment<Mysql> for InsertOrIgnore {
    |      ^^^^^^^^^^^^^^^^^^^^ the trait `sql_types::HasSqlType<sql_types::Timestamp>` is not implemented for `odbc::backend::Mysql`
    |
    = help: the following implementations were found:
              <odbc::backend::Mysql as sql_types::HasSqlType<odbc::types::Unsigned<sql_types::BigInt>>>
              <odbc::backend::Mysql as sql_types::HasSqlType<odbc::types::Unsigned<sql_types::Integer>>>
              <odbc::backend::Mysql as sql_types::HasSqlType<odbc::types::Unsigned<sql_types::SmallInt>>>
              <odbc::backend::Mysql as sql_types::HasSqlType<odbc::types::Unsigned<sql_types::TinyInt>>>
I can't find some where to impl TimeStamp in mysql, but mysql work well. is it derived from atttribues?

![image](https://user-images.githubusercontent.com/45359384/100424846-23ac8280-30c9-11eb-8f19-879c9296789b.png)

**Comment by unitsoftrover** [comment]
![image](https://user-images.githubusercontent.com/45359384/100425342-fc09ea00-30c9-11eb-8f18-57ba85c07d0e.png)

**Comment by unitsoftrover** [comment]
I can't find somewhere to impl Timestamp in mysql, but it work. is it derive from Attributes?

**Comment by weiznich** [comment]
Just to leave a few notes here:

* We won't accept any new backend in tree anytime soon, as it is possible to implement such a backend outside of diesel.
* You are aware of [diesel-oci](https://github.com/GiGainfosystems/diesel-oci)?

As for your question: The impl for `HasSqlType<Timestamp> for Mysql` is generated via [this](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/sql_types/mod.rs#L342) derive. For a custom backend you likely need to bring your own derive or just manually implement the corresponding trait. 

Generally speaking we see our issue tracker as place to track bugs and feature requests for diesel itself, not as place to ask question and look for support. We have an quite active gitter channel and a forum for looking for support and asking questions. 
Closed as this is not really actionable for diesel itself.
