### ISSUE TITLE
Add support for `HAVING` clauses

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#2581]
With #2571 merged diesel now officially supports `GROUP BY` causes. As mentioned in #210 we have no concrete planes for supporting `HAVING` clauses in the next release. I've opening this issue to just have one for `HAVING` clauses + write down some notes for potential contributors. So if anyone is interested in adding support for such clauses feel free to open a PR.

Steps to add support for `HAVING` clauses:
* Define a `HavingDsl` trait similar to the existing [`FilterDsl`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_dsl/filter_dsl.rs#L12) trait
* Add a generic impl for all tables, similar to [this impl](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_dsl/filter_dsl.rs#L20) for `FilterDsl`.
* Add support for `HAVING` clauses to our query builder:
    + Add a `NoHavingClause` similar to [`NoWhereClause`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_builder/where_clause.rs#L31-L37)
    + Add a `HavingClause<Expr>` similar to [`WhereClause<Expr>`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_builder/where_clause.rs#L71-L83)
    + Add another generic field to [`SelectStatement`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_builder/select_statement/mod.rs#L40-L58) containing the having clause. Default that generic parameter to `NoHavingClause`. Add this generic parameter to all impls in that file.
    + Make all of the impls in [`diesel/src/query_builder/select_statement/dsl_impl.rs](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_builder/select_statement/dsl_impls.rs) generic over the new generic paramater.
    + Fix all compilation errors coming from the newly added field by forwarding the having clause to the newly constructed select statement structs.
    + Implement `HavingDsl` for `SelectStatement`
    + Add another boxed field to [`BoxedSelectStatement`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_builder/select_statement/boxed.rs#L32) containing the boxed `HAVING` clause
    + Implement `HavingDsl` for `SelectStatement`
* Add a helper type to `diesel::dsl` (Similar to [`diesel::dsl::Filter<Source, Filter>`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/lib.rs#L225)
* Add a `having` method + some documentation to `QueryDsl`, similar to [`filter()`](https://github.com/diesel-rs/diesel/blob/6cd920184782745a46ee77d29ce20215228b9ed6/diesel/src/query_dsl/mod.rs#L470)
* Add a few tests to `diesel_tests`

**Comment by dnamsons** [comment]
I would like to work on this issue

**Comment by weiznich** [comment]
@dnamsons Sure, go for it. If you hit any issue feel free to reach out for me here or in our gitter channel. Opening a WIP PR is also probably a good idea to get early feedback on the implementation.

**Comment by hi-rustin** [comment]
@dnamsons Are you continuing to do it? I would like to try this issue.

**Comment by hi-rustin** [comment]
@dnamsons I will try to implement this feature, please feel free to contact me if you are still working on it.

**Comment by weiznich** [comment]
@hi-rustin I think it's fine to work on this feature, but you should use the existing WIP PR as basis, to keep the work done by dnamsons. Their PR already implements this feature, but misses a few points as outlined in the review there. It shouldn't be to hard to fix them.

**Comment by weiznich** [comment]
Closed by #2754
