### ISSUE TITLE
In-memory SQLite database w/ diesel::r2d2

### ISSUE THREAD

**Issue by agersant** [diesel-rs/diesel#2583]
### Versions

- **Diesel:** 1.4.5
 **Database:** SQLite

### Feature Flags

- **diesel:** sqlite, r2d2

## Problem Description

Hello. I have an application using Diesel with a connection pool from `diesel::r2d2`. When running concurrent unit tests, I have to make sure each test works with a independent database to avoid interference. This requirement is a bit inconvenient for a file-based DB like SQLite, as each test needs to generate its unique DB name.

I am exploring the idea of simplifying my tests by using in-memory databases. I can see `r2d2-sqlite` exposes a way to create a `ConnectionManager` for an in-memory database ([docs](https://docs.rs/r2d2_sqlite/0.17.0/r2d2_sqlite/struct.SqliteConnectionManager.html#method.memory) ). However, I can't see anything similar exposed through `diesel::r2d2` ([docs](https://docs.rs/diesel/1.4.5/diesel/r2d2/struct.ConnectionManager.html)).

Is this currently possible currently and if not, could it become possible in a future version?

Many thanks!

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case)

**Comment by weiznich** [comment]
Have you tried to just use `:memory:` as connection url while setting up your `ConnectionManager`? The [documentation](https://docs.rs/diesel/1.4.5/diesel/prelude/struct.SqliteConnection.html) on `SqliteConnection` explicitly mentions that `:memory:` is a valid connection url. 

Closed as I do not see anything actionable here + our issue tracker is not the right place to ask questions or look for support. Please use our gitter channel or our forum for that.
