### ISSUE TITLE
Feature Request - Access change for ValuesClause.values to make it easier to extend diesel to build Conditional Insert Statements

### ISSUE THREAD

**Issue by robinbernon** [diesel-rs/diesel#2593]
# Feature Request

## Feature Description

I would like to create conditional insert statements using diesel for use with postgres.
In particular I would like to create the insert statements without using any db plugins so would like the statements to be in the form of:

```
INSERT INTO table_name
SELECT 'field1_value', 'field2_value', etc
WHERE NOT EXISTS (
    SELECT 1 FROM table_name WHERE [Bunch of conditional statements can be applied here..]
);
```

## Issue I'm having

I can build out most of the query by myself through extensions although the 'select ....' line from query above is hard to produce.
Ideally it would be good to get this line from running obj.values() to get the ValuesClause<T, Tab> struct, and then take the values field from here to go ahead and construct my query. The issue here is that the access to this field is currently scoped in access to just the diesel crate so I am unable to do this:

```
#[doc(hidden)]
#[derive(Debug, Clone, Copy)]
pub struct ValuesClause<T, Tab> {
    pub(crate) values: T,
    _marker: PhantomData<Tab>,
}
```

If the field can be made to just pub then I can take the field and run something like:

```
pub fn walk_ast(&self, mut out: AstPass<DB>) -> QueryResult<()> {
    if self.values.is_noop()? {
        DefaultValues.walk_ast(out)?;
    } else {
        out.push_sql("(");
        self.values.column_names(out.reborrow())?;
        out.push_sql(") SELECT ");
        self.values.walk_ast(out.reborrow())?;
    }
    Ok(())
}
```

Once i've got my select line I can then use it with other QueryFragments to construct my conditional insert statement.

Anyone  mind if I go ahead a submit a PR for this removal of (crate)?

**Comment by weiznich** [comment]
Could you elaborate why you cannot just use the built-in support for [insert from select](http://docs.diesel.rs/1.4.x/diesel/fn.insert_into.html#insert-from-select)?

**Comment by robinbernon** [comment]
I wasn't sure how you would transform Vec<InsertableItemStruct> into diesel::SelectableExpression<()> so that you could apply it to the insert from select statement. Is there any easy way to do this?

**Comment by weiznich** [comment]
Ok, now I'm honestly confused. Why would you need to have a `Vec<InsertableItemStruct>` for a insert from select statement? Those are designed to be used to with existing data from existing tables. If that's not the case you probably try to do something wired, which would mean you should write down a complete motivating example.

**Comment by robinbernon** [comment]
> Ok, now I'm honestly confused. Why would you need to have a `Vec<InsertableItemStruct>` for a insert from select statement? Those are designed to be used to with existing data from existing tables. If that's not the case you probably try to do something wired, which would mean you should write down a complete motivating example.

**Comment by robinbernon** [comment]
Ah ok that's my issue - I don't want to insert existing data here.. As you can see from my first example in my first comment I want to insert new data under a where condition. Is there something about this you would like me to explain more?

**Comment by weiznich** [comment]
Please write down a complete example what are your input data and how you want to insert them exactly and why you cannot use existing API's there.

**Comment by robinbernon** [comment]
Ok sure, here is my issue in a condensed form:

I have a table with columns: id, field1, field2... etc.
I have an index on field1.
When doing a random select on a particular value in field1 I might get back ~0-10 rows at most.
I want to make sure that when inserting a row that field1 and field2 in combination are unique.

As I only get around 0-10 rows for a specific value in field1 I don't want to use a composite unique key for (field1, field2) - Instead I would prefer to index field1 and then filter first for field1 and then filter for field2 before adding the row, a bit like this:

```
INSERT INTO table_name
SELECT 'field1_value', 'field2_value', etc
WHERE NOT EXISTS (
    SELECT 1 FROM table_name WHERE field1='field1_value' AND field2='field2_value'
);
```

Does this make it a bit more clear?

**Comment by weiznich** [comment]
It's clearer now, but I do not understand why you want to use this complex likely inefficient scheme in favor of just using `UPSERT` statements. Could you collaborate on that?

**Comment by robinbernon** [comment]
The upsert option will only work for me if I add Unique(field1, field2) to the table. I think having this composite constraint is less efficient than just running a conditional check before the insert. Are there any issues with changing `pub(crate) values: T` to `pub values: T`?

**Comment by weiznich** [comment]
> The upsert option will only work for me if I add Unique(field1, field2) to the table. I think having this composite constraint is less efficient than just running a conditional check before the insert.

So the point is that you want to enforce some constrain here that you've not written down in your database schema. I would call this an antipattern in database design. If they are unique you really should add the correct constrain there, as this enables the database to do certain optimizations for queries.


> Are there any issues with changing pub(crate) values: T to pub values: T?

Yes, those are considered internal because making them public would prevent any future change (and therefore innovation) here. I would probably open to make them public if I see a clear use case but I'm unable to do that here. Additionally your current query can be written just by using the existing query builder (See the documentation for `IntoSql` + `diesel::select` + `diesel::dsl::exists` + that one for insert from select statements linked above).

**Comment by robinbernon** [comment]
Sorry I'm a little confused, how can I create my `select 'field1_value' 'field2_value' ..etc` line without using that private values field?

**Comment by weiznich** [comment]
`diesel::select(1.into_sql::<Integer>)` will create the some select statement like this: `SELECT $1` with the bind `$1` set the `1`. You can then append any filter that you want there + I've already linked the docs for insert from select above.

Anyway I think I will close this issue now as this seems to be fixed for me. For additional questions about this topic please use our gitter channel or open a post in the forum.

**Comment by robinbernon** [comment]
I was asking about this line though: `select 'field1_value' 'field2_value' ..etc`. Your previous answer doesn't explain how I can get this line. I still think the only general way of doing it is by accessing the values field

**Comment by weiznich** [comment]
This is my last comment here. For anything else please reread everything again, and if that does not help ask in the gitter channel or on the forum, as this is an issue tracker that is used to track bugs and such things and that is not meant to be used for unrelated support questions.

Additionally :
a) You've chosen a rather inefficient way of doing things. That's fine, but that does not mean diesel should just support that as I think that's an antipattern
b) I've given linked all required documentation to write such an query on your own.

> I was asking about this line though: select 'field1_value' 'field2_value' ..etc. Your previous answer doesn't explain how I can get this line. 

I mean the comment above has an example that just uses a different value for your selects. I think you should be able to adjust that, if not it's just `diesel::select(("field1_value".into_sql::<Text>(), "field2_value".into_sql::<Text>())`.

**Comment by robinbernon** [comment]
OK sure I get that, I just wanted to have it by using the values object as then it would have been automatic so I could have avoided adding it by hand like this - that's all. I guess I'll have to do this manually then...

**Comment by robinbernon** [comment]
Plus I don't think it is inefficient. Filtering through 5 or so elements is a better trade then adding a composite unique constraint to the table.
