### ISSUE TITLE
error: Could not compile `mysqlclient-sys`. 

### ISSUE THREAD

**Issue by dot2com** [diesel-rs/diesel#2594]
原因是编译的时候找不到mysql对应的库，所以报错

解决方案如下：

安装 MySQL Connector/C  download address https://downloads.mysql.com/archives/c-c/

设置环境变量：

- MYSQLCLIENT_LIB_DIR

默认 在 C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14

然后 执行 `cargo install diesel_cli --no-default-features --features mysql`

**Comment by weiznich** [comment]
Please do provide an English issue text if you open an issue in this repo.

**Comment by dot2com** [comment]
> Please do provide an English issue text if you open an issue in this repo.



The reason is that the library corresponding to mysql cannot be found when compiling, so an error is reported

The solution is as follows:

Install MySQL Connector/C download address https://downloads.mysql.com/archives/c-c/

Set environment variables:

MYSQLCLIENT_LIB_DIR
The default is C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14

Then execute cargo install diesel_cli --no-default-features --features mysql

Install Microsoft Build Tools

Address https://visualstudio.microsoft.com/downloads/ to install the Visual Studio 2019 generation tool.
In the Visual Studio 2019 tool drop-down menu, select the Visual Studio 2019 build tool and download it, and then install it.

During installation, check the C++ generation tool in the workload, and check English in the language pack to start the installation.
**Finally, don't forget to install python** It is said that the bottom layer uses python to connect to the database. I don't know if it is true. After installing python, it succeeded.

**Comment by weiznich** [comment]
> Finally, don't forget to install python It is said that the bottom layer uses python to connect to the database. I don't know if it is true. After installing python, it succeeded.

Just to clarify that: Diesel does not depend on python in any way. You don't need to install python to use diesel.

**Comment by ganlvtech** [comment]
`mysqlclient-sys` doesn't work with MySQL 8.0. I must download and install [MySQL Connector/C] (https://downloads.mysql.com/archives/c-c/) and set `MYSQLCLIENT_LIB_DIR` to `C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14`, instead of using bundled lib under `C:\Program Files\MySQL\MySQL Server 8.0\lib`.

**Comment by zemelLeong** [comment]
> `mysqlclient-sys` doesn't work with MySQL 8.0. I must download and install [MySQL Connector/C] (https://downloads.mysql.com/archives/c-c/) and set `MYSQLCLIENT_LIB_DIR` to `C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14`, instead of using bundled lib under `C:\Program Files\MySQL\MySQL Server 8.0\lib`.

Not work for me.
![image](https://user-images.githubusercontent.com/26835087/121830765-5d0cae80-ccf8-11eb-9152-58c4d381d3bd.png)

```
PS H:\rust-workspace\hello-rocket> cargo run
   Compiling mysqlclient-sys v0.2.4
   Compiling diesel v1.4.7
error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `mysqlclient-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by zemelLeong** [comment]
> `mysqlclient-sys` doesn't work with MySQL 8.0. I must download and install [MySQL Connector/C] (https://downloads.mysql.com/archives/c-c/) and set `MYSQLCLIENT_LIB_DIR` to `C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14`, instead of using bundled lib under `C:\Program Files\MySQL\MySQL Server 8.0\lib`.

It's solved. Execute `cargo clean` before `cargo run`.

**Comment by AkhilSharma90** [comment]
hey guys, just a heads up - I had numerous issues installing Diesel-CLI and I've done this now finally. Diesel maintainers must notice -
A lot of WSL (or Linux subsystem for windows) users will face issue after issue for installing Diesel.
You need to ensure you install MySQL and all libraries and drivers in the WSL subsystem itself, Diesel was unable to refer the ones at my windows system level. Only then it will work.

Diesel maintainers - you may need to include a separate section for WSL/ WSL2 users. Diesel is unstable here.

**Comment by weiznich** [comment]
@AkhilSharma90 Old issues like this one are really to wrong place for such comment. 
Otherwise feel free to submit a PR improving the documentation (be sure to checkout existing possible closed PR's for related work.) I personally cannot offer an accurate guide for all possible WSL installation as I do not have access to such an environment and I doubt that there is a single coherent WSL environment.
