### ISSUE TITLE
Diesel Migrations fails compilation with `README.md` in migrations directory

### ISSUE THREAD

**Issue by zedseven** [diesel-rs/diesel#2595]
### Versions

- **Rust: 1.48.0**
- **Diesel: v1.4.5**
- **Diesel_Migrations: v1.4.0**
- **Database: SQLite**
- **Operating System: Windows 10**

### Feature Flags

- **diesel: default**
- **diesel_migrations: default**

## Problem Description
Having a simple `README.md` file in the migrations directory causes the `embed_migrations!` macro to fail compilation.

### What are you trying to accomplish?
Just general use of the `embed_migrations!` macro. I added a `README.md` to the migrations directory to document what it was for.

### What is the expected behaviour?
Diesel would recognize `README.md` is not a directory, and ignore it.

### What is the actual output?
Diesel assumes `README.md` is a directory and attempts to access `up.sql` within it, which of course fails.

```
error: couldn't read \\?\C:\Users\Zacc\rust\open_dat\migrations\README.md\up.sql: The system cannot find the path specified. (os error 3)
 --> src\db\mod.rs:6:1
  |
6 | diesel_migrations::embed_migrations!("migrations");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `open_dat`
```

### Are you seeing any additional errors?
No, just this.

### Steps to reproduce
The issue can be reproduced with this snippet of code and a migrations directory with a `README.md` file in it:
```rust
#[macro_use]
extern crate diesel_migrations;

diesel_migrations::embed_migrations!("migrations");

fn main() {}
```

Deleting the `README.md` file from the directory immediately solves the problem, but this is not a desired solution and feels like avoiding the problem rather than fixing it.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. - *#140 and #141 are relevant, but seem to be focused on files within the sub-directories of the migrations dir*
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case) - *tested on the latest releases of both stable and nightly*

**Comment by weiznich** [comment]
Thanks for the well written bug report. 
This should be rather simple to fix, as we just need to filter out all non directories in this function [here](https://github.com/diesel-rs/diesel/blob/06494e8bdfe774bac9be5cab488b3d0cbec97f4e/diesel_migrations/migrations_internals/src/lib.rs#L315). 
I mark this as "help wanted" as this is something that is not high priority for me.

**Comment by mrceperka** [comment]
Rather simple fix, indeed. That's why I've attempted to fix it :)

**Comment by Voodlaz** [comment]
So, Do we have a fix or not?
