### ISSUE TITLE
Give a more complete example of how sum and avg functions could be used

### ISSUE THREAD

**Issue by sideralis** [diesel-rs/diesel#2596]
This is not an issue but I can't get sum or avg working.

I have one table _data_ with a column _temp_ (which is a i16 or `temp -> Nullable<Int2>` in schema.rs).

I tried:
```
        let source = data::dsl::data
            .select(dsl::avg(data::dsl::temp)); 
        let avg_data = source.get_result(&con).unwrap();
```
but when compiling, I got this:
```
54 |         let avg_data = source.get_result(&con).unwrap();
   |             ^^^^^^^^ consider giving `avg_data` a type
```
So I changed to:
```
        let avg_data: sql_types::Numeric = source.get_result(&con).unwrap();
```
But then I got:
```
54 |         let avg_data: sql_types::Numeric = source.get_result(&con).unwrap();
   |                                                   ^^^^^^^^^^ the trait `Queryable<diesel::sql_types::Nullable<diesel::sql_types::Numeric>, Pg>` is not implemented for `diesel::sql_types::Numeric`
```
I can't find a solution to solve this...

Help is welcome.

**Comment by weiznich** [comment]
As mentioned in several places in the documentation: Types from `diesel::sql_types` are not designed to hold any value on rust site. See the documentation of those sql typea for compatible rust types.
Also: Pleaseask further questions in our gitter channel or in our forum, not in the issue tracker.

**Comment by sideralis** [comment]
Thanks for your answer.
Yes, I know and sorry for that, but I could not find the forum and still can't find it...
I will try gitter in the worst case.

**Comment by weiznich** [comment]
The forum can be found [here](https://discourse.diesel.rs/). 
Closed as this is nothing that is actionable for anyone of the contributors.

**Comment by Arcovv** [comment]
Hi @sideralis 
This is required nullable, so:

```rust
let avg_data: Option<i64> = source.get_result::<Option<i64>>(&con).unwrap();
```
