### ISSUE TITLE
Feature: `diesel_migrations::run_pending_migrations`, allow to specify other output then stdio

### ISSUE THREAD

**Issue by SirWindfield** [diesel-rs/diesel#2619]
Hey!

First off, thanks for taking your free time to maintain `diesel`, it's really a great crate!

I am using the `diesel_migrations::run_pending_migrations` function in one of my applications that also uses `tracing` and was wondering if it is somehow possible to redirect the output of the migrations that get normally printed to the terminal to some other `Write` implementation maybe? The same way it's possible with `embedded_migrations::run`. 

Both seem to work differently under the hood, although I am not sure if it has any consequences to always run `embedded_migrations::run` instead of `diesel_migrations::run_pending_migrations` in production. If there aren't then using `embedded_migrations::run` might be a valid alternative.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by weiznich** [comment]
If you want to customize how `diesel_migrations::run_pending_migrations` handles the output consider using [`diesel_migrations::run_migrations`](http://docs.diesel.rs/1.4.x/diesel_migrations/fn.run_migrations.html) which exposes this functionality.

As for the difference between `embedded_migrations::run` and `diesel_migration::run_pending_migrations`: The `embed_migrations!` macro embedded all your migrations at compile time into the final binary, whereas `diesel_migrations::run_pending_migrations` does perform a runtime lookup of the migrations in your migrations directory. In the end that means if you deploy you code somewhere where you need to also apply the migrations using `embed_migrations!` means you only need to deploy the final binary, using `diesel_migrations::run_pending_migrations` means you also need to deploy your migrations directory.

Closed as this is no actionable bug report. Please use our gitter channel for further questions.

**Comment by SirWindfield** [comment]
Ah sorry, I missed the gitter chat part! Thanks for still answering the question though!
