### ISSUE TITLE
posts::table.into_boxed() could not compile successful

### ISSUE THREAD

**Issue by nopol** [diesel-rs/diesel#2621]
### Versions

- **Rust:** rustc 1.49.0 (e1884a8e3 2020-12-29)
- **Diesel:** 1.4.5
- **Database:**  mysql-5.7.24
- **Operating System** macOS 10.13.4

### Feature Flags

- **diesel:** diesel = { version = "1.4.5", features = ["mysql"] }

## Problem Description

```
#[derive(Queryable)]
#[derive(Serialize)]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub published: bool,
}


table! {
    posts (id) {
        id -> Integer,
        title -> Varchar,
        body -> Text,
        published -> Bool,
    }
}
```

```rust
use crate::schema::posts;

pub fn page(&self, page: PostPage) -> Pagination<Post>{
    let connection = establish_connection();
    let mut query = posts::table.into_boxed();
    if page.title.len() > 0 {
        query.filter(title.eq(page.title.clone()));
    }
    let total = query.count()
        .get_result(&connection)
        .unwrap_or(0);

    let mut rows = vec![];
    if total > 0 {
        rows = query
            .offset(page.get_offset())
            .limit(page.page_size)
            .load::<Post>(&connection)
            .expect("Error loading posts");
    }
    Pagination {
        total,
        page_index: page.page_index,
        page_size: page.page_size,
        page_count: calc_page_count(total, page.page_size),
        rows: rows
    }
}
```

### What is the expected output?

compile success

### What is the actual output?

```
18 |         let mut query = posts::table.into_boxed();
   |             --------- move occurs because `query` has type `diesel::query_builder::BoxedSelectStatement<'_, (diesel::sql_types::Integer, diesel::sql_types::Text, diesel::sql_types::Text, diesel::sql_types::Bool), table, Mysql>`, which does not implement the `Copy` trait
19 |         if page.title.len() > 0 {
20 |             query.filter(title.like(page.title));
   |             ----- value moved here
21 |         }
22 |         let total = query.count()
   |                     ^^^^^ value used here after move
```

When I change `let mut query = posts::table.into_boxed();` to `let mut query = posts.as_query();`, it compile success. But the filter did not work, database return all records.

**Comment by Mingun** [comment]
You need to utilize return value of the `filter` method.

Diesel team probably should add `#[must_use]` attribute here and for other similar traits:
https://github.com/diesel-rs/diesel/blob/a4b8031f6a096c8ea4032e7d8f05711d7f0dea1a/diesel/src/query_dsl/filter_dsl.rs#L12-L18

**Comment by nopol** [comment]
> You need to utilize return value of the `filter` method.
> 
> Diesel team probably should add `#[must_use]` attribute here and for other similar traits:
> https://github.com/diesel-rs/diesel/blob/a4b8031f6a096c8ea4032e7d8f05711d7f0dea1a/diesel/src/query_dsl/filter_dsl.rs#L12-L18

Thank you very much. I change the code to `query = query.filter(title.eq(page.title.clone()));` and it works.

**Comment by Mingun** [comment]
I think, that you can convert your issue into a task for adding `#[must_use]` attributes, because absence of them lead to your error and that can be fixed.

**Comment by weiznich** [comment]
@Mingun I'm quite sure that `#[must_use]` would not have been triggered in that case, as lints only get evaluated after the borrow checker. 

Otherwise it seems reasonable to add a few more `#[must_use]` attributes on all `QueryDsl` methods. Would be happy to receive a PR for that.

**Comment by WuJiY** [comment]
> > You need to utilize return value of the `filter` method.
> > Diesel team probably should add `#[must_use]` attribute here and for other similar traits:
> > https://github.com/diesel-rs/diesel/blob/a4b8031f6a096c8ea4032e7d8f05711d7f0dea1a/diesel/src/query_dsl/filter_dsl.rs#L12-L18
> 
> Thank you very much. I change the code to `query = query.filter(title.eq(page.title.clone()));` and it works.

How to solve this problem？

`let total = query.count()
   |                     ^^^^^ value used here after move`

**Comment by weiznich** [comment]
@WuJiY This is an issue tracker, it is used by the diesel team to track bugs. It's not a place to ask questions or otherwise get support.
