### ISSUE TITLE
Can't run migration with ```DELIMITER $$```

### ISSUE THREAD

**Issue by gjvnq** [diesel-rs/diesel#2622]
### Versions

- **Rust:** 1.50
- **Diesel:** 1.4.5 (diesel_cli reports 1.4.1)
- **Database:** MariaDB
- **Operating System** Manjaro Linux

### Feature Flags

- **diesel:** default ones

## Problem Description

diesel-cli seems to not understand the ```DELIMITER``` SQL command.

### What are you trying to accomplish?

Add triggers using SQL.

### What is the expected output?

```
Running migration 2021-01-17-202047_db
```

### What is the actual output?

```
Failed with: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$
CREATE TRIGGER `my_db`.`group_AFTER_INSERT`
AFTER INSERT ON ...' at line 1
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

1. ```diesel migration generate db```
2. Put the following in ```up.sql```:
```sql

CREATE TABLE IF NOT EXISTS `object_type` (
  `uuid` CHAR(36) NOT NULL,
  `type` CHAR(5) NOT NULL,
PRIMARY KEY (`uuid`));

CREATE TABLE IF NOT EXISTS `group` (
  `uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(190) NOT NULL,
  `comments` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`uuid`));

DELIMITER $$
CREATE TRIGGER `my_db`.`group_AFTER_INSERT`
AFTER INSERT ON `my_db`.`group`
FOR EACH ROW
BEGIN
	INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'G');
END$$
```
3. Run ```diesel migration run```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

## Workarround

I did discover I can workarround this issue by using a "less standard" syntax:

```sql
CREATE TRIGGER `my_db`.`group_AFTER_INSERT`
AFTER INSERT ON `my_db`.`group`
FOR EACH ROW
BEGIN
	INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'G');
END; -- This semicolon is necessary
```

**Comment by weiznich** [comment]
As the error message mentions this is not a diesel issue, but your database system (MariaDB) does just not support the SQL you've provided. Diesel does not preprocess the SQL provided for migrations in any way.

Closed as this is not a diesel issue.

**Comment by gjvnq** [comment]
Actually it does support because I tried to run it and it worked.

According to the [official documentation](https://mariadb.com/kb/en/delimiters/), MariaDB not only supports but recommends the use of ```DELIMITER``` when creating procedures.

**Comment by weiznich** [comment]
According to the documentation you've linked above `DELIMITER` is something that gets interpreted by the `mysql` client part (so the console application you type your queries into). Diesel talks directly with the server, so there is no need for setting a custom `DELIMITER` there. For future reference the following syntax works just fine:

```SQL
CREATE TRIGGER `my_db`.`group_AFTER_INSERT`
AFTER INSERT ON `my_db`.`group`
FOR EACH ROW
BEGIN
	INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'G');
END;
```
