### ISSUE TITLE
SQL UNIQUE with multiple foreign keys

### ISSUE THREAD

**Issue by cemoktra** [diesel-rs/diesel#2623]
### Versions

- **Rust:** 1.49.0
- **Diesel:** 1.4.2
- **Database:** MariaDB
- **Operating System** Linux / Ubuntu

### Feature Flags

- **diesel:** mysql

### What are you trying to accomplish?
I'm trying to create a schema for an existing database.

### What is the expected output?
A working schema.rs

### What is the actual output?
`Unexpected null for non-null column`

### Are you seeing any additional errors?
No

### Steps to reproduce

Put the following in an up.sql and do a migration:
```
CREATE TABLE tab_key1(
    id bigint NOT NULL auto_increment,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tab_key2(
    id bigint NOT NULL auto_increment,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tab_key3(
    id bigint NOT NULL auto_increment,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tab_key4(
    id bigint NOT NULL auto_increment,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tab_problem (
  id bigint NOT NULL auto_increment,
  key1 bigint NOT NULL,
  key2 bigint NOT NULL,
  key3 bigint NULL,
  some_value varchar(25) NULL,
  key4 bigint NULL,

  PRIMARY KEY (id),
  UNIQUE (key1, key2),
  CONSTRAINT `key1` FOREIGN KEY (key1) REFERENCES tab_key1(id),
  CONSTRAINT `key2` FOREIGN KEY (key2) REFERENCES tab_key2(id),
  CONSTRAINT `key3` FOREIGN KEY (key3) REFERENCES tab_key3(id),
  CONSTRAINT `key4` FOREIGN KEY (key4) REFERENCES tab_key4(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```

I tried to create a minimal example to reproduce this for multiple hours now, but the minimal example always works as expected. The root of the problem is the usage of the 'UNIQUE' keyword with two or more foreign keys.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Please provide a corresponding schema (as `CREATE TABLE` statements) to reproduce this, otherwise this is not really actionable for any contributor.

**Comment by cemoktra** [comment]
As i said, i spend multiple hours already trying to do that. Will try again later

**Comment by cemoktra** [comment]
Ok updated. Today it was easier
