### ISSUE TITLE
The column is of type varchar[] changing the column type to text[]

### ISSUE THREAD

**Issue by Acidic9** [diesel-rs/diesel#2641]
### Versions

- **Rust:** 1.23.1
- **Diesel:** 1.4.4
- **Database:** Postgres
- **Operating System** MacOS

### Feature Flags

- **diesel:** `["postgres", "r2d2"]`

## Problem Description
In a migration file, I am trying to create a column of type `VARCHAR(255)[]`, but Diesel warns me when running the migration with:

> The column `images` is of type `varchar[]`. This will cause problems when using Diesel. You should consider changing the column type to `text[]`.

### What are you trying to accomplish?
Create a column of type `VARCHAR(255)[]`.

### What is the expected output?
A successful migration with no warnings.

### What is the actual output?
> The column `images` is of type `varchar[]`. This will cause problems when using Diesel. You should consider changing the column type to `text[]`.

### Are you seeing any additional errors?
No, just the warning.

### Steps to reproduce
Create a migration with the following in `up.sql`:

```sql
CREATE TABLE reviews (
  id SERIAL PRIMARY KEY,
  images TEXT[]
)
```

And run `diesel migration run` to execute the migration.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Basically a duplicate if #287.

**Comment by weiznich** [comment]
Closed in favor of the original issue. We are aware of that (obviously, because we print out a warning for this already). We do not have any plans to support this anytime soon for the reasons listed in the original issue. For an "easy" fix we would need to have some form of specialization in rust.
