### ISSUE TITLE
Linker problems when cross compiling for diesel_migrations

### ISSUE THREAD

**Issue by benjumanji** [diesel-rs/diesel#2650]
### Versions

- **Rust:** 1.50.0
- **Diesel:** 1.4
- **Database:** sqlite
- **Operating System** Linux

### Feature Flags

- **diesel:** --no-default-features --features=sqlite

## Problem Description

Linker fails to fix -lsqlite during compilation when using diesel_migrations. What is strange is that I can compile for instance `diesel_cli` with no problems. I am targetting armv7hf (for rpi3) using a docker image with a buildroot sysroot. Like I say, `diesel_cli` compiles with zero problems.

### What are you trying to accomplish?

Cross compile for arm using diesel_migrations.

### What is the expected output?

Successful compilation.

### What is the actual output?

```
   Compiling migrations_macros v1.4.2
     Running `rustc --crate-name migrations_macros /root/.cargo/registry/src/github.com-1ecc6299db9ec823/migrations_macros-1.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' -C metadata=1211d62f9b26583c -C extra-filename=-1211d62f9b26583c --out-dir /root/src/target/release/deps -L dependency=/root/src/target/release/deps --extern migrations_internals=/root/src/target/release/deps/libmigrations_internals-4a20060daf56c112.rlib --extern proc_macro2=/root/src/target/release/deps/libproc_macro2-50e619617746faae.rlib --extern quote=/root/src/target/release/deps/libquote-208091f87c334260.rlib --extern syn=/root/src/target/release/deps/libsyn-9e10c4fa6eead2f2.rlib --extern proc_macro --cap-lints allow`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.0.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.1.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.10.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.11.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.12.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.13.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.14.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.15.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.2.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.3.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.4.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.5.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.6.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.7.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.8.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.migrations_macros.a2lsmz7g-cgu.9.rcgu.o" "-o" "/root/src/target/release/deps/libmigrations_macros-1211d62f9b26583c.so" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.34sx4ayatflay3pa.rcgu.o" "/root/src/target/release/deps/migrations_macros-1211d62f9b26583c.5ozhyf17py9jdyx.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/root/src/target/release/deps" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/src/target/release/deps/libsyn-9e10c4fa6eead2f2.rlib" "/root/src/target/release/deps/libquote-208091f87c334260.rlib" "/root/src/target/release/deps/libproc_macro2-50e619617746faae.rlib" "/root/src/target/release/deps/libunicode_xid-58c7cba263b075d3.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-bba0624c33176ddd.rlib" "/root/src/target/release/deps/libmigrations_internals-4a20060daf56c112.rlib" "/root/src/target/release/deps/libdiesel-0339a2541a78f4d0.rlib" "/root/src/target/release/deps/liblibsqlite3_sys-dba280873a2c0db6.rlib" "/root/src/target/release/deps/libbyteorder-c5fbf75adf997589.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f77337c1826707d.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e238540f8faf9927.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-78f8506dd5004913.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-c0e64497deb085aa.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-217a514dc8d845c6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-65e4f8df4b8bbd73.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-fec1b74170245419.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e74f867eb2f15322.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-72a374d36f3d0a31.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-cb9206ed96de54c3.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-33ee81149d314805.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-2e8740599b11634b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-241cf59851357bea.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-edc29aa8c04b480f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-6a141406945fda5a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2408224b4af46d83.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d36087076e1dd756.rlib" "-Wl,-Bdynamic" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lsqlite3
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `migrations_macros`

Caused by:
  process didn't exit successfully: `rustc --crate-name migrations_macros /root/.cargo/registry/src/github.com-1ecc6299db9ec823/migrations_macros-1.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' -C metadata=1211d62f9b26583c -C extra-filename=-1211d62f9b26583c --out-dir /root/src/target/release/deps -L dependency=/root/src/target/release/deps --extern migrations_internals=/root/src/target/release/deps/libmigrations_internals-4a20060daf56c112.rlib --extern proc_macro2=/root/src/target/release/deps/libproc_macro2-50e619617746faae.rlib --extern quote=/root/src/target/release/deps/libquote-208091f87c334260.rlib --extern syn=/root/src/target/release/deps/libsyn-9e10c4fa6eead2f2.rlib --extern proc_macro --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

Copy any project using diesel_migrations into artfuldodge/debian-cross-rust-build-base:0.16.0 and try to build it (this docker image has the buildroot sys and env vars all setup with cargo on the path. For instance note that `cargo install --target=armv7-unknown-linux-gnueabihf --no-default-features --features=sqlite diesel_cli` inside `docker run --rm -it artfuldodge/debian-cross-rust-build-base:0.16.0 bash` works with zero problems. I'll whip together a github repo with a full repo soonish, I just wanted to write this out while I had the chance.

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
You need to provide a version of `libsqlite3` that matches your target. Also according our issue template this is nothing that should be opened as bugreport here.

**Comment by benjumanji** [comment]
Way to go for actually reading the issue. What a joke.

**Comment by benjumanji** [comment]
I  just want to make it clear: I have a working linker setup for this. Other parts of the diesel project compile just fine, it's just diesel_migrations that doesn't. I have a version that matches my target otherwise `diesel_cli` wouldn't compile would it? Anyway hopefully this issue can save other people from wasting their time trying to get this to work.

**Comment by weiznich** [comment]
I don't understand your problem: The linker says there is no matching `libsqlite3` in your environment. You need to provide a matching one, otherwise it won't work. 
If it works for `diesel_cli` it means that you do something different there, not that diesel is broken or something like that. 

Nerveless we make it more than clear that our issue tracker is not the place to provide support for something like this. Please use the corresponding channels for this. 


> Anyway hopefully this issue can save other people from wasting their time trying to get this to work.

I think we communicated more than clearly that our issue tracker is not the place to document things. Either open a topic at the discussion part about this, or ask in our gitter channel.

> I just want to make it clear: I have a working linker setup for this. Other parts of the diesel project compile just fine, it's just diesel_migrations that doesn't. I have a version that matches my target otherwise diesel_cli wouldn't compile would it? 

That's all correct, but have you read your error message completely? It is looking for a libsqlite3 version for your build system as diesel is also a build dependency of the migration macros for various reasons. So as I've written above: You need to provide a matching libsqlite3 version.

**Comment by benjumanji** [comment]
> If it works for diesel_cli it means that you do something different there, not that diesel is broken or something like that.

It is amazing how sure you are of that, but that's not true. I have all the linking stuff setup in the environment. Every other project I am using finds libraries just fine. dbus, diesel etc. I have no special per project or per library setup. Just a regular cargo and some environment variables.

```
AR_armv7_unknown_linux_gnueabihf=/home/builder/buildroot-2019.11.1/output/host/bin/arm-buildroot-linux-gnueabihf-ar
CC_armv7_unknown_linux_gnueabihf=/home/builder/buildroot-2019.11.1/output/host/bin/arm-buildroot-linux-gnueabihf-gcc
BINDGEN_EXTRA_CLANG_ARGS=--sysroot=/home/builder/buildroot-2019.11.1/output/host/arm-buildroot-linux-gnueabihf/sysroot
PATH=/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PKG_CONFIG=/home/builder/buildroot-2019.11.1/output/host/bin/pkg-config
```

The supplied pkg-config can find sqlite just fine. Anyway, nbd. I'll just avoid diesel_migrations. Thanks for your time.

> I think we communicated more than clearly that our issue tracker is not the place to document things. Either open a topic at the discussion part about this, or ask in our gitter channel.

I didn't open this for documentation purposes. I'm just hoping that now it's obvious that I'm not going to get anywhere with it that it can at least serve that purpose.

**Comment by weiznich** [comment]
> It is amazing how sure you are of that, but that's not true. I have all the linking stuff setup in the environment. Every other project I am using finds libraries just fine. dbus, diesel etc. I have no special per project or per library setup. Just a regular cargo and some environment variables.

Would I get 1$ per person that claims that this is not true, I would probably be very rich already. The point is we test that it works in general as part of our CI and additionally `diesel_migrations` is not different to `diesel` or `diesel_cli` here. It just needs to all dependencies for the target it is compiled to.  That really only leaves the following possibilities:
* It's something missing in your environment (and that's the case in 99,9% of the cases or so)
* It's a compiler bug
* It's a linker bug


> I didn't open this for documentation purposes. I'm just hoping that now it's obvious that I'm not going to get anywhere with it that it can at least serve that purpose.

I would like to know where our contributing documentation is not clear that you should only open an issue for an actual bug report and not for anything else, like linker errors. If you actually believe this is a bug I would expect to you elaborate why this is 
a) Not a duplicate of already existing linker errors.
b) Not an issue with your environment. This would include any information about installed dependencies and so on.
b) A issue in diesel and not for example a linker issue, as issue in some dependency or in rustc itself

>  Anyway, nbd. I'll just avoid diesel_migrations. Thanks for your time.

It's your decision to use diesel, but as soon as you interact with our project I expect that you somehow respect our contribution documentation. Yes that requires some time reading this document, but you would have get answer for your problem at other locations more easily and without all the trouble. Anyway that's the amount of work I expect someone to do that's coming here and asking for support for something I've doing in my free time. If you don't want to do that, either don't comment here or pay someone to solve your problem.
Also if you reread  my answers (or your actual error message :shrug:) above again you will see the solution for your problem.

**Comment by benjumanji** [comment]
> The point is we test that it works in general as part of our CI and additionally diesel_migrations is not different to diesel or diesel_cli here.

Ok. I made a repro with a nice reproducible environment. Two projects, completely empty. One depends on diesel only, one depends on diesel and diesel migrations. One compiles, the other doesn't. Just run the two shell scripts in the root. You can see that they are identical in their cargo invocations, the only difference is the bind mount.

https://github.com/benjumanji/diesel_repro

**Comment by weiznich** [comment]
That's all fine, but have you tried that what I've suggested [above](https://github.com/diesel-rs/diesel/issues/2650#issuecomment-783358925) yet?

**Comment by tesaguri** [comment]
`migrations_macros` is a procedural macro and compiles against the host, whereas `diesel` (cross) compiles against the target. So you need to have `libsqlite3` for both environments and also an ability to specify correct library for each target in a single `cargo build` run.

In my crate, I'm doing the following in the [`Dockerfile`] and everything works fine (in addition, I'm using [`cross`] for cross compilation, which might be relevant).

```dockerfile
RUN dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libsqlite3-dev libsqlite3-dev:armhf
ENV PKG_CONFIG_ALLOW_CROSS_armv7_unknown_linux_gnueabihf=1 \
    PKG_CONFIG_PATH_armv7_unknown_linux_gnueabihf='/usr/lib/arm-linux-gnueabihf/pkgconfig'
```

Alternatively, if you do not need dynamic linking, you may want to static link against `libsqlite` by specifying the following in `[dependencies]` of `Cargo.toml`, which should reduce the complexity of cross compilation.

```toml
libsqlite3-sys = { version = ">=0.8.0, <0.19.0", optional = true, features = ["bundled"] }
```

[`cross`]: https://crates.io/crates/cross
[`Dockerfile`]: https://github.com/tesaguri/pipitor/blob/958256007fd4c8fbe8be1848fbfdb7639aac4c8b/docker/armv7-unknown-linux-gnueabihf/Dockerfile

**Comment by benjumanji** [comment]
> is a procedural macro and compiles against the host.

TIL, thanks.

**Comment by ilyazzz** [comment]
This has been resolved for me by the migrations rework.
