### ISSUE TITLE
error occurred: Failed to find tool. Is `gcc.exe` installed? while cargo install diesel_cli --no-default-features --features "sqlite-bundled"

### ISSUE THREAD

**Issue by GabrielBG0** [diesel-rs/diesel#2678]
### Versions

- **Rust:1.48.0**
- **Database: Sqlite**
- **Operating System: windows 10**
## Problem Description
I'm following the get started tutorial and when I try to install diesel cli i get this error message when using `cargo install diesel_cli --no-default-features --features "sqlite-bundled"`:
`error: failed to run custom build command for `libsqlite3-sys v0.18.0`

Caused by:
  process didn't exit successfully: `*\AppData\Local\Temp\cargo-install7xv7rN\release\build\libsqlite3-sys-0e739e5ad9d937ff\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=SQLITE_MAX_VARIABLE_NUMBER
  cargo:rerun-if-env-changed=SQLITE_MAX_EXPR_DEPTH
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-DSQLITE_HAVE_ISNAN" "-o" "*\AppData\\Local\\Temp\\cargo-install7xv7rN\\release\\build\\libsqlite3-sys-a8e9f4042b6f0b14\\out\\sqlite3/sqlite3.o" "-c" "sqlite3/sqlite3.c"

  --- stderr

  error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)

warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v1.4.1`, intermediate artifacts can be found at `C:\Users\gabre\AppData\Local\Temp\cargo-install7xv7rN`

Caused by:
  build failed`

**Comment by weiznich** [comment]
If you use the `sqlite-bundled` you need to provide a C compiler that is able to build sqlite.
Closed as this is not a diesel issue.
