### ISSUE TITLE
Document more about the expected behavior of Connection::establish

### ISSUE THREAD

**Issue by keepsimple1** [diesel-rs/diesel#2679]
https://github.com/diesel-rs/diesel/blob/c2366e8a0ba7d97c6824b6e0cd5705c9710e0cc1/diesel/src/connection/mod.rs#L41

The current doc does not mention what happens if the `database_url` does not exist. Should the method create a new database automatically? Or, is it implementation-dependent? It seems like SQLite3 driver does create a new database if not exists yet, mostly because of its C FFI. But there is no doc for SQLite3 `establish` implementation: https://github.com/diesel-rs/diesel/blob/c2366e8a0ba7d97c6824b6e0cd5705c9710e0cc1/diesel/src/sqlite/connection/mod.rs#L57 .

It will be helpful to spell out what is the expected behavior in this case.

**Comment by weiznich** [comment]
We are happy to receive a PR for this. The behaviour is implementation specific, so there is no way to document this in a general way.
