### ISSUE TITLE
Improve our documentation hosting

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#268]
Right now we just have docs.diesel.rs, which points to the gh-pages branch of this repo, which is automatically updated when the build is green on master. What I'd like to do is host docs for each version as well. I'd like `docs.diesel.rs/0.5.0` to point at the latest version, `docs.diesel.rs/current` to point at the latest release, and `docs.diesel.rs/nightly` to point at master. If it makes things easier, we can probably have the master branch live on a separate subdomain.

If anybody is interested in tackling this as a PR, just let me know what I need to do in terms of branches/dns records if anything. I'd like the process to remain semi-automated

**Comment by mcasper** [comment]
Do we want `docs.diesel.rs/<VERSION>` to support every historical version of diesel, or just the most recent (major?) release? Just the past couple releases?

**Comment by sgrif** [comment]
Probably every historical major/minor version, but not patch versions

**Comment by dikaiosune** [comment]
Are the current docs building with all features enabled? As an example, I see `uuid` as an optional crate in Cargo.toml, but searching the current docs doesn't return any results about UUID columns.

**Comment by sgrif** [comment]
We're meant to doc with all features enabled, but I believe I forgot to add `uuid`. Might be worth adding an `all` feature so there's a more local place to update this as new features are added.

**Comment by weiznich** [comment]
That's fixed since #2269
