### ISSUE TITLE
`RETURNING` for SQLite

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#2683]
SQLite now supports `RETURNING`: http://antonz.org/sqlite-3-35/
https://sqlite.org/releaselog/3_35_0.html

It would be great if diesel could support it as well :)

**Comment by Talden** [comment]
It looks support for sqlite-3.35 merged in https://github.com/rusqlite/rusqlite/pull/917 in the last 24 hours.

No idea when that might reach a libsqlite3-sys release or what it will take for diesel to be in a position to take such a release.

The CTE and RETURNING changes both have the potential for measurable improvements.  DROP COLUMN is a nice quality-of-life change too.
