### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by hi-rustin** [diesel-rs/diesel#2765]
Our contribution guide is missing content on how to debug diesel codebase locally, e.g. how to run and test each crate individually.

Maybe we can provide some commands to contributors.

cc: @weiznich

**Comment by weiznich** [comment]
[This script](https://github.com/diesel-rs/diesel/blob/master/bin/test) runs all tests + also outputs the corresponding commands. Maybe that should be stated clearer in the contributions docs? 
Generally I would like to avoiding giving specific commands there, as they become out of date quite soon.

**Comment by hi-rustin** [comment]
> [This script](https://github.com/diesel-rs/diesel/blob/master/bin/test) runs all tests + also outputs the corresponding commands. Maybe that should be stated clearer in the contributions docs?

Maybe we can prompt people to go to that sh and look for a separate test command?

**Comment by weiznich** [comment]
Sounds reasonable :+1:

**Comment by hi-rustin** [comment]
> Sounds reasonable 👍

I'll improve it tomorrow.
