### ISSUE TITLE
sqlite: not possible to use SQL functions without Arguments

### ISSUE THREAD

**Issue by toxeus** [diesel-rs/diesel#2790]
### Versions

- **Rust:** 1.52.1
- **Diesel:** master
- **Database:** Sqlite
- **Operating System:** Linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

[This condition](https://github.com/diesel-rs/diesel/blob/7587a3bda93bcbe8d44a22f8537da157b953ae5e/diesel_derives/src/sql_function.rs#L245) skips the code generation of `register_impl` and `register_nondeterministic_impl` for SQL functions without arguments. Because the [documentation](https://docs.diesel.rs/master/diesel/prelude/macro.sql_function.html#sql-functions-without-arguments) doesn't mention any limitations for Sqlite SQL functions without arguments, I'm assuming this to be a bug. 

I've tracked down the [commit that introduced that regression]( https://github.com/diesel-rs/diesel/commit/dd05ee2588f80f240896bd8c95cd8539d706d7e7#diff-3dc6bb01ed73137c473d075bf6f9ae482857b07fdfd5aa7d95691705daaebc6bR235) but its commit message doesn't help to understand why the condition was changed.

### What are you trying to accomplish?

I want to use a SQL function without arguments with Sqlite.

### What is the expected output?

No errors.

### What is the actual output?

> cannot find function `register_nondeterministic_impl` in module `foo`

### Are you seeing any additional errors?

No.

### Steps to reproduce

```rs
sql_function! {
    fn foo() -> Text;
}
fn main() {
    let conn = diesel::SqliteConnection::establish(":memory:");
    foo::register_impl(&conn, || "foo".to_string());
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Technically speaking this is a feature request, as no version of diesel did support sqlite functions without argument. The check in question is there because otherwise the proc macro generates invalid code for sql functions without argument. 
We are happy to receive an PR to fix this, otherwise at least for me personally that's nothing that has priority right now.
