### ISSUE TITLE
#[derive(Insertable)] panics when I use #[column_name = "type"]

### ISSUE THREAD

**Issue by msrd0** [diesel-rs/diesel#2792]
### Versions

- **Rust:** 1.52.1
- **Diesel:** 1.4.6
- **Database:** postgresql
- **Operating System:** ArchLinux

### Feature Flags

- **diesel:** `{ version = "1.4", features = ["32-column-tables", "chrono", "postgres", "serde_json"], default-features = false }`

## Problem Description

This code panics:

```rust
#[derive(Insertable)]
struct Foo {
        #[column_name = "type"]
        ty: String
}
```

### What are you trying to accomplish?

I'm trying to insert rows into a table that has a column called `type`, which must not be used as an identifier in rust. #2501 suggests to use `#[column_name = "type"]` but that doesn't work either.

### What is the expected output?

A correct implementation of `Insertable`.

### What is the actual output?

```
error: proc-macro derive panicked
 --> src/main.rs:3:10
  |
3 | #[derive(Insertable)]
  |          ^^^^^^^^^^
  |
  = help: message: expected identifier
```

### Are you seeing any additional errors?

Yes, `#[derive(AsChangeset)]`produces the same panic.

### Steps to reproduce

Try to compile above code

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  ~~and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)~~  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
#2501 is related to `QueryableByName`, not to `Insertable` so that comment from there does not apply here.
Generally you cannot use `type` as ident in rust, as it is a reserved keyword. Use the corresponding column name from the `table!` macro instead.

Closed as this isn't a bug

**Comment by msrd0** [comment]
Thanks for the advice. Still, it's sad to see that error messages like this one with an incorrect span and an error message that can easily be mistaken for an issue with the macro and not my input for the macro aren't considered bugs.

**Comment by weiznich** [comment]
@msrd0 To be fair: The wording of your bug report is not about the incorrect span of the error message. For me this bug report does look like someone that seeks to get support in our issue tracker, which is definitively the wrong place for such things.
I agree that this error message could be improved, but this should be tracked in a separate issue with precise information what's wrong with that error message and how that can be improved. Feel free to submit such an issue.
