### ISSUE TITLE
DeleteStatement need or_filter function

### ISSUE THREAD

**Issue by Ali-Mirghasemi** [diesel-rs/diesel#2812]
hi 
i'm using diesel crate and now i need or_filter function for DeleteStatement 
just like using or_filter in Select query

something like that
```
let mut query = diesel::delete(notifications).into_boxed();

        for id in ids {
            if id != -1 {
                query = query.or_filter(notification_id.eq(id));
            }
        }

        query
            .filter(user_id.eq(1))
            .execute(_conn)?
```

**Comment by weiznich** [comment]
Closed as this is an issue tracker and not a help forum. Please use any of the linked support channel to ask questions.
