### ISSUE TITLE
failed to continue `diesel setup`

### ISSUE THREAD

**Issue by halldong** [diesel-rs/diesel#2818]
## Setup
By following the [official example](https://diesel.rs/guides/getting-started.html), I cannot keep going after setting up `.env` file.

### Versions
- **Rust:** rustc 1.53.0 (53cb7b09b 2021-06-17)
- **Diesel:** 1.4.1
- **Database:** PostgreSQL 12.0
- **Operating System** Ubuntu 20.04.2 LTS

### Feature Flags

- **diesel:** just `diesel setup` in the official example

## Problem Description
It remind me that **password authentication failed**.
This is a postgresql db on the cloud. I have correctly setup the whitelist, fqdn, port, etc.
With the same information inside `.env` (**copy** & **paste**), I can easily login by using `psql`:
```bash
# psql -h fqdn -p port -d diesel_demo -U user -W
Password:
psql (12.7 (Ubuntu 12.7-0ubuntu0.20.04.1), server 12.4)
Type "help" for help.

diesel_demo=> \d
Did not find any relations.
diesel_demo=>
```

### What are you trying to accomplish?
I'm trying to setup database with diesel.

### What is the expected output?
The `diesel setup` command should log in as normal and setup the database.

### What is the actual output?
```bash
# nvim -p .env
# cat .env
DATABASE_URL=postgres://user:password@fqdn:port/diesel_demo
# diesel setup
Creating database: diesel_demo
FATAL:  password authentication failed for user "user"
```

### Are you seeing any additional errors?
Yeah, the following error also repeated shown in the cloud log:
```
DETAIL: Password does not match for user "user". Connection matched pg_hba.conf line 4: "host all all 0.0.0.0/0 md5"
FATAL: 28P01: password authentication failed for user "user"
```

### Steps to reproduce
just as [this page](https://diesel.rs/guides/getting-started.html)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
***Searched with no similar result.***
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case)
***Yeah, I'm using rust stable version.***
- [x] This issue can be reproduced without requiring a third party crate
***Of course, I'm just following the starting example in official page.***

**Comment by weiznich** [comment]
> With the same information inside .env (copy & paste), I can easily login by using psql:
> ```
> # psql -h fqdn -p port -d diesel_demo -U user -W
> ```

That's not what psql considers to be the same information. The following command uses exactly the same login information as provided by diesel:
```
psql postgres://user:password@fqdn:port/diesel_demo
```
I expect that this will fail with exactly the same error message, which means this is not a diesel issue but an issue with your database configuration.

I'm closing this issue as this is not a general diesel issue, but an issue with your setup. We do not consider our issue tracker as support forum. Use the discussion forum or the gitter channel for such questions instead.

**Comment by halldong** [comment]
to leave a mesg: the reason here is because of a special character within my password that should be escaped.
