### ISSUE TITLE
⚠ diesel setup not finding .env file

### ISSUE THREAD

**Issue by danbugs** [diesel-rs/diesel#2833]
## Setup
- Following the [Getting Started](https://diesel.rs/guides/getting-started) tutorial, I installed the Diesel CLI with `cargo install diesel_cli --no-default-features --features postgres`.

### Versions

- **Rust:** 1.53.0
- **Diesel:** 1.4.1
- **Database:** PostgreSQL
- **Operating System:** Windows 10 64-bit

## Problem Description

After running:
```
echo DATABASE_URL=postgres://<omitted-username>:<omitted-password>@<omitted-host>/<omitted-db> > .env
diesel migration generate create_posts
```

I get: 
```
Creating migrations directory at: C:\Users\<omitted-user>\source\repos\diesel_demo\migrations
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.
```

As per the Diesel CLI [README](https://github.com/diesel-rs/diesel/tree/master/diesel_cli), I was expecting `diesel setup` to link to my newly created .`env` file that is at the root of my project (i.e., same level as Rust's `src` folder). Is the `.env` in the wrong place? I attempted moving it inside the `src` folder but nothing changed.

### Sidenote

It all works fine when I run `diesel setup --database-url=postgres://<omitted-username>:<omitted-password>@<omitted-host>/<omitted-db>`, I just wish I could make use of the convenience of the `.env` file.

(ps. I've deleted the subsequent headers in this bug report because the bug is fairly simple)

**Comment by weiznich** [comment]
Thanks for opening this bug. Generally our issue tracker is the wrong place to ask for support. Please use the forum or the gitter channel for future questions. 

As for the bug report: Unfortunately your report is missing the following important information to reproduce the problem:

* A exact sequence of commands that you have executed starting from the point where you created a new cargo project. This should be self contains and only this should be required to reproduce the problem. It should also contain "minor" things like installing diesel cli, changing folders and so on.
* Which shell did you use to execute those commands.

As other thing I want to note that we initialize dotenv based variables [here](https://github.com/diesel-rs/diesel/blob/1.4.x/diesel_cli/src/main.rs#L61) so I guess that this is an error with your setup (likely) or a dotenv issue (unlikely, as this works for other users)

> (ps. I've deleted the subsequent headers in this bug report because the bug is fairly simple)

Those are not optional, please readd them and answer those questions. If you don't feel the template makes much sense for your report that normally means you should ask in the forum or the gitter channel for help first.

**Comment by danbugs** [comment]
> Generally our issue tracker is the wrong place to ask for support. Please use the forum or the gitter channel for future questions.

I'm sorry — would you prefer I close this issue? Let me know! 

> A exact sequence of commands that you have executed starting from the point where you created a new cargo project. This should be self contains and only this should be required to reproduce the problem. It should also contain "minor" things like installing diesel cli, changing folders and so on.

I've really just followed exactly what is described on the [Getting Started](https://diesel.rs/guides/getting-started) guide. Regardless, I apologize — I definitely could have been clearer. 

Here are the exact sequence of commands I followed: 
![img](https://i.imgur.com/FiYLMR4.png)

> Which shell did you use to execute those commands.

I am using PowerShell.

> As other thing I want to note that we initialize dotenv based variables here so I guess that this is an error with your setup (likely) or a dotenv issue (unlikely, as this works for other users)

I've attempted re-starting from scratch and I'm still getting the same error. In fact even after using the `--database-url` and proceeding further with the [Getting Started](https://diesel.rs/guides/getting-started) guide, I still fail when running the code related from the "src/bin/show_posts.rs" part:
```
pub fn establish_connection() -> PgConnection {
    dotenv().ok();

    let database_url = env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    PgConnection::establish(&database_url)
        .expect(&format!("Error connecting to {}", database_url))
}
```

That is, I get:
```
panicked at 'DATABASE_URL must be set: NotPresent', src/lib.rs:17:10        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace'
```

> Those are not optional, please readd them and answer those questions. If you don't feel the template makes much sense for your report that normally means you should ask in the forum or the gitter channel for help first.

I'm sorry — I shouldn't have assumed those were optional or that the information I provided was sufficient. I'm adding the missing sections from the initial bug report below in an attempt to remedy my mistake. Again though, while I'd appreciate any help, do let me know if you'd prefer I just drop this entirely.

### What are you trying to accomplish?
I am attempting to complete the [Getting Started](https://diesel.rs/guides/getting-started) guide.

### What is the expected output?
I was expecting `diesel setup` to connect to my database through the `.env` file without having to specifically use the `--database-url` flag.

### What is the actual output?
It indicates that `diesel setup` could not locate my `.env` file:
```
Creating migrations directory at: C:\Users\<omitted-user>\source\repos\diesel_demo\migrations
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.
```

### Are you seeing any additional errors?
No.


### Steps to reproduce
```
cargo new --lib diesel_demo
cd diesel_demo
```

Now, in `Cargo.toml`, I added: 
```
[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
```

Next up, I installed the Diesel CLI. Here's how:
```
cargo install diesel_cli --no-default-features --features postgres
```

After this, I created my `.env` file and attempted to run setup:
```
echo DATABASE_URL=postgres://<omitted-username>:<omitted-password>@<omitted-host>/<omitted-db> > .env
diesel setup
```

Here's when I got the error message that indicated that `diesel setup` couldn't find the `.env` file:
```
Creating migrations directory at: C:\Users\<omitted-user>\source\repos\diesel_demo\migrations
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by danbugs** [comment]
Nvm — Fixed the issue! I'm not sure why but it looks like using:
```
echo DATABASE_URL=postgres://<omitted-username>:<omitted-password>@<omitted-host>/<omitted-db> > .env
```

... to create the `.env` file was the issue. After deleting it and manually re-creating it on VSCode, the problem fixed itself! Just to be sure, I attempted going through the [Getting Started](https://diesel.rs/guides/getting-started) guide one more time but creating the `.env` file manually this time around and it all worked!

I'm closing the issue! ;D

**Comment by weiznich** [comment]
Thanks for coming back to report this :+1:

**Comment by petzki** [comment]
I got the same issue and managed to also fix it using VSCode to create the file. The difference between the files was that  the file created from command line had UTF-16 LE encoding and the other one was UTF-8. It should probably be mentioned in the getting started page or to fix parsing the file to accept different encodings.
I am on also on Windows 10 and using powershell.

**Comment by weiznich** [comment]
@petzki Can you report that as issue to the [corresponding crate](https://github.com/allan2/dotenvy) that's used by diesel for `.env` support? That would be helpful.

**Comment by weiznich** [comment]
@petzki Can you provide an broken example `.env` file in the linked dotenvy issue?
