### ISSUE TITLE
uuid load error

### ISSUE THREAD

**Issue by grubxy** [diesel-rs/diesel#2850]
### Versions

- **Rust:rustc 1.55.0-nightly**
- **Diesel:1.4.7**
- **Database:postgresql**
- **Ubuntu20.04**

### Feature Flags
```
diesel = { version = "1.4.7", features = [ "chrono","postgres", "r2d2","uuidv07","serde_json"] }
diesel_migrations = "1.4.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
anyhow = "1.0.42"
thiserror = "1.0.26"
serde = "1.0.127"
serde_json = "1.0.66"
serde_derive = "1.0.127"
rocket = { version = "0.5.0-rc.1", features = ["json", "uuid"] }
```
## Problem Description

```
#[derive(Debug, Clone, Serialize, Deserialize, Queryable, Insertable, Identifiable)]
#[serde(crate = "rocket::serde")]
#[table_name = "companys"]
pub struct Company {
    pub id: Uuid,
    pub phone: Option<String>,
    pub name: Option<String>,
    pub attach: Option<String>,
    pub create_at: NaiveDateTime,
    pub update_at: NaiveDateTime,
    pub verify: bool,
}
```

schema.rs: 
```
table! {
    companys (id) {
        id -> Uuid,
        phone -> Nullable<Varchar>,
        name -> Nullable<Varchar>,
        attach -> Nullable<Text>,
        create_at -> Timestamp,
        update_at -> Timestamp,
        verify -> Bool,
    }
}
```

when insert company,it's ok; but when load the uuid, it's panic.

```     
use self::companys::dsl::*;        
let _id: Vec<uuid::Uuid> = companys.select(id).load(conn).expect("test error");
```
```
thread 'rocket-worker-thread' panicked at 'test error: DeserializationError(Error(Build(Error { expected: 16, found: 36 })))', src/company.rs:66:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What are you trying to accomplish?
I want to get the uuid.

### What is the expected output?
load the uuid ok

### What is the actual output?
error occur : DeserializationError(Error(Build(Error { expected: 16, found: 36 })))

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Please provide the complete code including the insert statement that is required to reproduce this, otherwise this is not actionable for anyone. At least the following information are required:
* A minimal standalone project showing this issue. (Something where I can just run `cargo run` and observe the crash)
* The corresponding database schema
* The confirmation that you can reproduce this on a stable compiler without any third party dependency (depending on uuid is fine for that)

**Comment by grubxy** [comment]
Hi @weiznich , the issue can be reproduced in my env, so I checkout all. I add a simple repo : https://github.com/grubxy/test_diesel.git
with complete code and just depend on Uuid.

**Comment by weiznich** [comment]
So I had a look at you repo and I think I found the issue: Your `schema.rs` does not match your actual database schema.

schema.rs: 
```rust
table! {
    test_companys (id) {
        id -> Uuid,
    }
}
```

Database schema
```sql
CREATE TABLE test_companys (
  id VARCHAR PRIMARY KEY
)
```

Note that the database schema declares the field as `VARCHAR`, while your `schema.rs` declares the field as `Uuid`. This is an error on your side. You should use the diesel cli tool to generate the `schema.rs` file based on your database to prevent such mismatches from happening.

Closed as this is not an issue in diesel.

**Comment by grubxy** [comment]
thanks
