### ISSUE TITLE
Failing to compile diesel_codegen-0.5.4 on rust nightly 2016-04-19

### ISSUE THREAD

**Issue by Cottonwoods** [diesel-rs/diesel#292]
Hope this is the right place to report this: failing the compilation of included library diesel_codegen with error: attempted access of field `node` on type `&syntax::ast::StructField`, but no field with that name was found in attr.rs

This is when I try to build diesel_demo. I tried to compile on stable 2016-04-11 with --no-default-features --features with-syntex & get mismatched types from build.rs instead: expected `&mut syntex::Registry`, found `&mut main::syntex::Registry`

Cargo versions were 0.11.0 & 0.9.0 respectively. Let me know if I need to include any more information.

Thanks

**Comment by sgrif** [comment]
The officially supported nightly version for 0.5.4 was `nightly-2016-03-11`. Please update to 0.6.0 to use with `nightly-2016-04-09` or later (syntex 0.31.0)

**Comment by sgrif** [comment]
I need to update `diesel_demo` now that it's dependencies are updated... Will report back when it's done

**Comment by sgrif** [comment]
`diesel_demo` should be up to date.

**Comment by sgrif** [comment]
The getting started guide on diesel.rs should be up to date.

**Comment by sgrif** [comment]
Let me know if you have any more issues. :)

**Comment by Cottonwoods** [comment]
Sounds good, thanks
