### ISSUE TITLE
Setting None on nullable types in postgtresql sets text type

### ISSUE THREAD

**Issue by Corallus-Caninus** [diesel-rs/diesel#2945]
## Setup
currently migrating into postgres
### Versions

- **Rust:**
- latest
- **Diesel:**
- 1.4.4 (1.4.8 cant handle UUIDs)
- **Database:**
- postgresql
- **Operating System**
- linux container

### Feature Flags
uuidv07 postgres
- **diesel:**

## Problem Description
when creating None for types Nullable<Timestamp> the postgres database stores as type Text if all column entries are None.

### What are you trying to accomplish?
I would like to have these stored in the correct schema as timestamps type that have null entries

### What is the expected output?
see above

### What is the actual output?
see above

### Are you seeing any additional errors?
UUID only works for v1.4.4 with feature uuidv07

### Steps to reproduce
create a postgres table with a column of Nullable<timestamp>.
in the ORM set that column to None for all entries
duplicate this table in the database as an empty table with the same schema
try to "insert into new_empty_table from select * from original_table;"
                            let ao= problem_table_sync{
                                id: Uuid::new_v4(),
                                a: a,
                                o: o,
                                e: Some(uuid_cast.unwrap()),
                                u: u,
                                ao: None,
                                oe: b.created_on,
                                eu: x.created_on,
                                ui: None,
                            };

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x ] This issue can be reproduced without requiring a third party crate except UUID which is rust and diesel standard

**Comment by Corallus-Caninus** [comment]
My boss didn't give me db access nor told me the correct schema this isn't diesels fault.

**Comment by weiznich** [comment]
> UUID only works for v1.4.4 with feature uuidv07

The uuid related tests pass for all 1.4.x release. I guess this is caused by your project using a different uuid version than diesel. You should be able to fix that by using the same uuid version than diesel.
