### ISSUE TITLE
Are BoxableConnection methods usable?

### ISSUE THREAD

**Issue by ahwatts** [diesel-rs/diesel#2956]
## Setup

Create a new Rust project, make the following changes:

Cargo.toml:
```toml
[package]
name = "diesel-test"
version = "0.1.0"
edition = "2021"
[dependencies.diesel]
git = "https://github.com/diesel-rs/diesel"
features = ["default", "mysql"]
```

src/main.rs:
```rust
use diesel::{MysqlConnection, backend::Backend, migration::Migration};

struct TestMigration;

impl<DB: Backend> Migration<DB> for TestMigration {
    fn run(&self, conn: &mut dyn diesel::connection::BoxableConnection<DB>) -> diesel::migration::Result<()> {
        if conn.is::<MysqlConnection>() {
            todo!()
        }
        todo!()
    }

    fn revert(&self, conn: &mut dyn diesel::connection::BoxableConnection<DB>) -> diesel::migration::Result<()> {
        todo!()
    }
    fn metadata(&self) -> &dyn diesel::migration::MigrationMetadata {
        todo!()
    }
    fn name(&self) -> &dyn diesel::migration::MigrationName {
        todo!()
    }
}

fn main() {
    println!("Hello, world!");
}
```

### Versions

- **Rust:** rustc 1.56.1 (59eed8a2a 2021-11-01)
- **Diesel:**  v2.0.0 (https://github.com/diesel-rs/diesel#19db25af)
- **Database:** any
- **Operating System** Windows 10

### Feature Flags

- **diesel:** `default`, `mysql`

## Problem Description

The above code fails to compile, with the following error:

```
C:\Users\Andrew\Projects\diesel-test> cargo build
   Compiling diesel-test v0.1.0 (C:\Users\Andrew\Projects\diesel-test)
error[E0271]: type mismatch resolving `<MysqlConnection as Connection>::Backend == DB`
 --> src\main.rs:7:17
  |
5 | impl<DB: Backend> Migration<DB> for TestMigration {
  |      -- this type parameter
6 |     fn run(&self, conn: &mut dyn diesel::connection::BoxableConnection<DB>) -> diesel::migration::Result<()> {
7 |         if conn.is::<MysqlConnection>() {
  |                 ^^ expected struct `Mysql`, found type parameter `DB`
  |
  = note:      expected struct `Mysql`
          found type parameter `DB`

For more information about this error, try `rustc --explain E0271`.
error: could not compile `diesel-test` due to previous error
```

### What are you trying to accomplish?

Ultimately, I want to make a migration that is aware of which database it's trying to migrate, and potentially do slightly different things depending on that database. It seems like that's what the `BoxableConnection` methods are for, but if there's a way to make them work, I can't figure out how to make that happen syntactically.

## Checklist

- [✔️] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
There appears to be a related discussion here: https://github.com/diesel-rs/diesel/discussions/2707
- [✔️] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [✔️] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
This is expected behaviour. If you write a backend specific migration you should make that clear in your implementation of the `Migration` trait by setting the `DB` parameter to a specific backend.
