### ISSUE TITLE
Do not use the error message to figure out whether the connection was closed

### ISSUE THREAD

**Issue by Emm** [diesel-rs/diesel#2957]
Following the discussion in #2935, it appears that Diesel use string matching to figure if the Postgres connection to the server was closed, in `src/pg/connection/result.rs` (`CLOSED_CONNECTION_MSG`)

This is problematic for two reasons, as:
- matching on error messages is inherently fragile and discouraged by Postgres
- Postgres error messages are localized

The correct solution involves using `PQStatus()` on the raw connection and checking whether this returns `CONNECTION_BAD`

**Comment by weiznich** [comment]
Closed by #3135
