### ISSUE TITLE
Provide an easy way to "insert or replace" or conditionally insert 

### ISSUE THREAD

**Issue by llogiq** [diesel-rs/diesel#296]
I'm thinking about using diesel in a project, where I get a stream of data that may contain duplicates, and I want only distinct data in my database, so an insert or replace statement would be quite helpful. I should note that I plan to use the sqlite backend. What are my options?

**Comment by sgrif** [comment]
We don't have any support for upsert at the moment, but this is something I'd like to add in the future. See https://github.com/diesel-rs/diesel/issues/196. I'm going to bump this to the 0.7 milestone, as SQLite in particular should be extremely easy to support for this case. I'll see if I can add it today.

**Comment by llogiq** [comment]
I see. No hurry, I'll need some time to finish the rest anyway. Thank you for the quick response! :+1:

**Comment by sgrif** [comment]
No problem. SQLite also supports specifying that upsert should occur in the table's schema. Worst case, you could always specify the `ON CONFLICT` clause for the primary key (or whatever index it is that you're wanting this behavior on). Diesel generally doesn't have opinions about how you structure your schema (with exception of things that we just don't handle yet, like composite primary keys)
