### ISSUE TITLE
Document what to do when pooled connection rollback fails

### ISSUE THREAD

**Issue by mleonhard** [diesel-rs/diesel#2963]
[`diesel::connection::Connection::transaction`](https://docs.rs/diesel/1.4.8/diesel/connection/trait.Connection.html#method.transaction) docs say:
> ```rust
> fn transaction<T, E, F>(&self, f: F) -> Result<T, E> where
>     F: FnOnce() -> Result<T, E>,
>     E: From<Error>,
> ```
> Executes the given function inside of a database transaction
> 
> If there is already an open transaction, savepoints will be used instead.
> 
> If the transaction fails to commit due to a `SerializationFailure`, a rollback will be attempted. If the rollback succeeds, the original error will be returned, otherwise the error generated by the rollback will be returned. In the second case the connection should be considered broken as it contains a uncommitted unabortable open transaction.

I'm using [`diesel::r2d2::Pool`](https://docs.rs/diesel/1.4.8/diesel/r2d2/struct.Pool.html) with [`diesel::r2d2::ConnectionManager::<PgConnection>`](https://docs.rs/diesel/1.4.8/diesel/r2d2/struct.ConnectionManager.html).  I need the docs to answer these two questions:
- How can I close a connection with an uncommited and unabortable transaction and avoid returning it to the pool?
- Is this even necessary when using the connection pool?

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Generally speaking: If something is not documented we do not guarantee a certain behavior. That's in most cases not because the docs are missing but because we haven't decided whats the right behavior there.
In this specific case we would be happy if someone starts a discussion what behavior should be guaranteed here. If that's decided we happily accept a PR updating the implementation and the documentation.
The discussion in #2935 might be relevant here as well.

**Comment by chusteven** [comment]
I hope someone corrects me if I'm wrong, but I believe that the user doesn't need to close the connection themself as this is handled by [the `r2d2` code](https://github.com/sfackler/r2d2/blob/c572a8250923f7f157f73b5700e64d21d598ccb6/src/lib.rs#L86-L95) -- [these lines](https://github.com/sfackler/r2d2/blob/c572a8250923f7f157f73b5700e64d21d598ccb6/src/lib.rs#L496-L510) in particular look to be closing the connection

As far as `diesel` it seems to me like we implement the ["interface"](https://github.com/sfackler/r2d2/blob/c572a8250923f7f157f73b5700e64d21d598ccb6/src/lib.rs#L69-L96) for an r2d2 connection [here](https://github.com/diesel-rs/diesel/blob/7184f128a3c1435d12b32f413b14b6632e2f753c/diesel/src/r2d2.rs#L94-L112); individual backends, then, would need to implement the `is_broken()` method themselves like:
* [pg](https://github.com/diesel-rs/diesel/blob/a12f95f70d8f32eaefb42ec9d4e4b93904a51c96/diesel/src/pg/connection/mod.rs#L179-L185)
* [mysql](https://github.com/diesel-rs/diesel/blob/a12f95f70d8f32eaefb42ec9d4e4b93904a51c96/diesel/src/mysql/connection/mod.rs#L146-L152)
* [sqlite](https://github.com/diesel-rs/diesel/blob/a12f95f70d8f32eaefb42ec9d4e4b93904a51c96/diesel/src/sqlite/connection/mod.rs#L143-L149)

which all look extremely similar in that they depend on the `transaction_state` of the current `Connection` struct

I'd be happy to add documentation where relevant -- I'm guessing [this module](https://github.com/diesel-rs/diesel/blob/a12f95f70d8f32eaefb42ec9d4e4b93904a51c96/diesel/src/r2d2.rs) would be the place to do it, though I'm not entirely sure on which struct/trait documentation best belongs

**Comment by weiznich** [comment]
@chusteven Yes your observations are correct. That was not the case at the time this issue got filled. Adding the corresponding documentation would be a welcome change :+1:. We should use some formulation that states this behaviour for our concrete connection implementations, but that does not make a general statement for all connections there.
