### ISSUE TITLE
*ANY* breaking changes that we want to make in the near future

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#298]
Right now the plan is to have 0.7 be the last release before 1.0. That means that we should start seriously thinking about anything we might want to break in the near future. This does _not_ mean that we should feel rushed to get remaining major features out. Only that we should address anything we expect to cause breaking changes.

A few things that we should look at off the top of my head
- `group_by` support, and how this affects `NonAggregate`. Honestly, I think we're so far from this that it'll have to wait until 2.0 if it needs breaking changes (it might not need breaking changes though). This likely requires some form of negative reasoning in the language. Regardless, I need to take a swing at it before 1.0
- Logging. Does this eliminate the need for `debug_sql!` and the `Debug` backend?
- Reforming joins to work with multiple tables. Does the improved association support in 0.7 eliminate the majority of the need for this?

**Comment by iqualfragile** [comment]
maybe support for composite primary keys? I guess that would mean some changes, not sure if the api would change though.

**Comment by sgrif** [comment]
Yes you are right we should attempt to explore that in 0.7 or 0.8

**Comment by sgrif** [comment]
Everything in this issue has been resolved. `group_by` is going to wait for 2.0. Logging has been removed from the milestone (we can add it backwards compatibly I think, though it'll require a default impl of the `set_logger` method on `Connection` which panics). Joins have been sufficiently reformed.

**Comment by sgrif** [comment]
Also...

> Right now the plan is to have 0.7 be the last release before 1.0

Yeah, that worked out well... >_>
