### ISSUE TITLE
`cfg_attr` does not work in combination with `diesel` derive attribute

### ISSUE THREAD

**Issue by Ten0** [diesel-rs/diesel#2983]
### Versions

- **Rust:** Latest stable
- **Diesel:** Latest master (8a53cb7c8a09ae891df6c104d1c8a03d51ee07fc)
- **Database:** Postgres
- **Operating System** Linux

### Feature Flags

- **diesel:** postgres

## Problem Description
`cfg_attr` does not work in combination with `diesel` derive attribute

### What are you trying to accomplish?
```rust
#[cfg_attr(
	feature = "diesel-by-alpha3-as-char3",
	derive(diesel::AsExpression, diesel::FromSqlRow)
)]
#[cfg_attr(
	feature = "diesel-by-alpha3-as-char3",
	diesel(sql_type = diesel::sql_types::Text)
)]
pub enum Alpha3 {
	/// Aruba
	ABW,
	/// Afghanistan
	AFG,
}
```

### What is the expected output?
*compiles*

### What is the actual output?
```
At least one `sql_type` is needed for deriving `AsExpression` on a structure.
```
If however I remove the `cfg_attr` on the diesel attribute, this compiles (but then obviously fails to compile when the feature is disabled).

### Steps to reproduce
Add to the code above a FromSql/ToSql implementation
```rust
#[cfg(feature = "diesel-by-alpha3-as-char3")]
impl<DB> diesel::deserialize::FromSql<diesel::sql_types::Text, DB> for Alpha3
where
	DB: diesel::backend::Backend,
	String: diesel::deserialize::FromSql<diesel::sql_types::Text, DB>,
{
	fn from_sql(bytes: diesel::backend::RawValue<DB>) -> diesel::deserialize::Result<Self> {
		todo!()
	}
}

#[cfg(feature = "diesel-by-alpha3-as-char3")]
impl<DB> diesel::serialize::ToSql<diesel::sql_types::Text, DB> for Alpha3
where
	DB: diesel::backend::Backend,
	str: diesel::serialize::ToSql<diesel::sql_types::Text, DB>,
{
	fn to_sql<'b>(&'b self, out: &mut diesel::serialize::Output<'b, '_, DB>) -> diesel::serialize::Result {
		todo!()
	}
}
```

## Notes

Might be related to #2626 @pksunkara ?

**Comment by weiznich** [comment]
A first step to debug this would be to dump the attributes passed to diesel_derives [here](https://github.com/diesel-rs/diesel/blob/master/diesel_derives/src/model.rs#L65).

**Comment by pksunkara** [comment]
Looks to be more of a Rust macro expansion related issue. There was a ton of work recently done on this but I am not sure if that work included `cfg_attr` related expansion.

**Comment by pksunkara** [comment]
Now that we bumped the MSRV to 1.56, this might be fixed. @Ten0 can you check?

**Comment by pksunkara** [comment]
Confirmed that this has been fixed.

**Comment by Ten0** [comment]
Indeed! Sorry for missing your previous message.
