### ISSUE TITLE
how to inner join by content of column

### ISSUE THREAD

**Issue by evergreen-trading-systems** [diesel-rs/diesel#3013]
how do i do a inner join by content of column - like asked here https://stackoverflow.com/questions/23276344/like-operator-in-inner-join-in-sql
if i have table A, table B, both has example column
i want to join B to A by contents of example column
Table A: example.com, Table B: www.example.com - this would match join
Table A: example.com, Table B: google.com - this would not match join

**Comment by evergreen-trading-systems** [comment]
Does not seem possible because type cannot be guaranteed? But it should because Diesel knows the types of every column.

**Comment by weiznich** [comment]
Our issue tracker is not the right place to ask questions. Please use the discussion forum or the gitter channel for this. 
Additionally the issue template is mandatory, so removing it results closing the issue without comment in the future.
