### ISSUE TITLE
Unable to use order_by with some columns after using distinct_on

### ISSUE THREAD

**Issue by polc** [diesel-rs/diesel#3018]
### Versions

- **Rust: 1.57.0**
- **Diesel: current main branch**
- **Database: Postgres 13.3**
- **Operating System: Arch Linux**

### Feature Flags

- **diesel: postgres, r2d2, chrono**

### What are you trying to accomplish?

I'm trying to convert the following SQL query to Diesel DSL : 

```sql
select distinct on (o.id) o.id, g.id, u.id
from public.user u
inner join public.group g on u.group_id = g.id
inner join public.org o on g.org_id = o.id
order by o.id, g.created_at desc, u.created_at desc;
``` 

```rust
use diesel::{ExpressionMethods, allow_tables_to_appear_in_same_query, joinable, QueryDsl, table};

table! {
  user (id) {
    id -> Text,
	created_at -> Timestamp,
	group_id -> Text,
  }
}

table! {
  group (id) {
    id -> Text,
	created_at -> Timestamp,
	org_id -> Text,
  }
}

table! {
  org(id) {
    id -> Text,
  }
}

joinable!(user -> group (group_id));
joinable!(group -> org (org_id));

allow_tables_to_appear_in_same_query!(
    user,
    group,
    org,
);

fn main() {
    user::table
        .inner_join(group::table.inner_join(org::table))
        .distinct_on(org::id)
        .select((org::id, group::id, user::id))
        .order_by((org::id, group::created_at.desc(), user::created_at.desc()));
}
```

### What is the actual output?

```
error[E0277]: the trait bound `(org::columns::id, Desc<group::columns::created_at>, Desc<user::columns::created_at>): query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<org::columns::id>>` is not satisfied
  --> reports/src/main.rs:39:10
   |
39 |         .order_by((org::id, group::created_at.desc(), user::created_at.desc()));
   |          ^^^^^^^^ the trait `query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<org::columns::id>>` is not implemented for `(org::columns::id, Desc<group::columns::created_at>, Desc<user::columns::created_at>)`
   |
   = note: required because of the requirements on the impl of `OrderDsl<(org::columns::id, Desc<group::columns::created_at>, Desc<user::columns::created_at>)>` for `SelectStatement<FromClause<JoinOn<diesel::query_source::joins::Join<user::table, SelectStatement<FromClause<JoinOn<diesel::query_source::joins::Join<group::table, org::table, Inner>, Grouped<diesel::expression::operators::Eq<diesel::expression::nullable::Nullable<group::columns::org_id>, diesel::expression::nullable::Nullable<org::columns::id>>>>>>, Inner>, Grouped<diesel::expression::operators::Eq<diesel::expression::nullable::Nullable<user::columns::group_id>, diesel::expression::nullable::Nullable<group::columns::id>>>>>, query_builder::select_clause::SelectClause<(user::columns::id, group::columns::id, org::columns::id)>, DistinctOnClause<org::columns::id>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `reports` due to previous error
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
This is caused by the following trait bound: https://github.com/diesel-rs/diesel/blob/45823853ed795cbe5a78a8a7d7d0f7a4cd7883fd/diesel/src/query_builder/select_statement/dsl_impls.rs#L267

An existing impl exists, but not for `Expr` itself, but for `OrderClause<Expr>`:
https://github.com/diesel-rs/diesel/blob/45823853ed795cbe5a78a8a7d7d0f7a4cd7883fd/diesel/src/type_impls/tuples.rs#L373

A possible fix would:
1. Change the trait bound from `Expr: ValidOrderingForDistinct<D>` to `OrderClause<Expr>: ValidOrderingForDistinct<D>`
2. Verify that all existing tests pass
3. Add a few test cases to `diesel_tests` to verify possible combinations work fine. This should include the following cases:
    + The provided example query (the join is not relevant)
    + Additional cases that use `.asc()` or `.desc()` on the first item of the order clause
