### ISSUE TITLE
Unable to sort columns used in a DISTINCT ON

### ISSUE THREAD

**Issue by polc** [diesel-rs/diesel#3020]
Follow-up of a bug discovered here : https://github.com/diesel-rs/diesel/pull/3019#issuecomment-1013075368

### Versions

- **Rust: 1.57**
- **Diesel: master (https://github.com/diesel-rs/diesel/commit/a213fe232a122f35a812b0ce0269708a1845a4c9)**
- **Database: Postgres 13.3**

### Feature Flags

- **diesel: postgres**

## Problem Description

We are unable to sort the columns used in `distinct_on`. For example, here  we are unable to sort `users::id` by descending order  :

```rust
use diesel::{ExpressionMethods, QueryDsl, table};

table! {
  users (id) {
    id -> Text,
    name -> Text,
  }
}

let _ = users::table
    .distinct_on(users::id)
    .select(users::id)
    .order_by((users::id.desc(), users::name));
```
```
13 |     .order_by((users::id.desc(), users::name));
|          ^^^^^^^^ the trait `query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<columns::id>>` is not implemented for `diesel::query_builder::order_clause::OrderClause<(diesel::expression::operators::Desc<columns::id>, columns::name)>`
|
= help: the following implementations were found:
<diesel::query_builder::order_clause::OrderClause<(T,)> as query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<T>>>
<diesel::query_builder::order_clause::OrderClause<(__D, T0)> as query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<__D>>>
<diesel::query_builder::order_clause::OrderClause<(__D, T0, T1)> as query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<__D>>>
<diesel::query_builder::order_clause::OrderClause<(__D, T0, T1, T2)> as query_dsl::order_dsl::ValidOrderingForDistinct<DistinctOnClause<__D>>>
and 14 others
= note: required because of the requirements on the impl of `OrderDsl<(diesel::expression::operators::Desc<columns::id>, columns::name)>` for `SelectStatement<FromClause<users::table>, diesel::query_builder::select_clause::SelectClause<columns::id>, DistinctOnClause<columns::id>>`
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by timonbimon** [comment]
+1

**Comment by weiznich** [comment]
@timonbimon Please do not comment to older issues if you have nothing to contribute. This only adds noise for all involved people.
