### ISSUE TITLE
create postgres user via sql_query with params throw an error

### ISSUE THREAD

**Issue by Corfus** [diesel-rs/diesel#3064]
### Versions

- **Rust:** 1.58.1
- **Diesel:** 1.4.8
- **Database:** PostgreSQL 14.1
- **Operating System** Ubuntu 20.04.4

### Feature Flags

- **diesel:** postgres

### What are you trying to accomplish?

I try to create new postgres users with the `sql_query` function with parameters.

```rust
sql_query("CREATE USER $1 WITH PASSWORD '$2'")
        .bind::<Text, _>(&name)
        .bind::<Text, _>(&password)
        .execute(&conn)
        .unwrap();
```

### What is the expected output?

It should create a new user.

### What is the actual output?

`DatabaseError(__Unknown, "syntax error at or near \"$1\"")'`

### Are you seeing any additional errors?

If I don't use the param syntax I can create new users:

```rust
sql_query("CREATE USER admin WITH PASSWORD 'admin'")
        .execute(&conn)
        .unwrap();
```

And the param syntax works, if i use it in an SELECT call:

```rust
#[derive(Debug, QueryableByName)]
struct TestStruct {
    #[sql_type = "Text"]
    text: String
}

...

let list = sql_query("SELECT $1 as text")
        .bind::<Text, _>(&name)
        .load::<TestStruct>(&conn)
        .unwrap();
    println!("{:?}", list);
```

So I don't understand why I can create new users via query and I can use the params in another case, but I can't combine them.
It would be great to use it with diesel directly.

### Steps to reproduce

```rust
use diesel::{Connection, PgConnection, RunQueryDsl, sql_query};
use diesel::sql_types::Text;

fn establish_connection() -> PgConnection {
    let database_url = "postgres://anthill:anthill@localhost:15432/anthill".to_string();
    PgConnection::establish(&database_url)
        .expect(&format!("Error connecting to {}", &database_url))
}

fn create_pg_user(name: &String, password: &String) {
    let conn = establish_connection();

    sql_query("CREATE USER $1 WITH PASSWORD $2")
        .bind::<Text, _>(&name)
        .bind::<Text, _>(&password)
        .execute(&conn)
        .unwrap();
}


fn main() {
    create_pg_user(&"admin".to_string(), &"password".to_string());
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for raising this report. This error indicates that posgres does not allow bind parameters in this position. 
 Closed as this is not a diesel bug, as we don't do any query processing for `sql_query`.
