### ISSUE TITLE
Diesel doesn't generate `belonging_to` trait for structs with derive associations

### ISSUE THREAD

**Issue by ch3ck** [diesel-rs/diesel#3082]
### Versions

- **Rust**: *rustc 1.61.0-nightly (6a7055661 2022-02-27)*
- **Diesel:** *diesel 1.4.1*
- **Database:** *Postgres 14.0*
- **Operating System:**  *Debian 11.14-0+deb10u1*

### Feature Flags

- **diesel:* features = ["chrono", "extras", "postgres", "r2d2"]*

## Problem Description
Just like in #1203 , diesel does not generate the `belonging_to` trait for table associations using the `belongs_to` derive macro.

### What are you trying to accomplish?
I'm trying to fetch all classes attended by registered students

```rust
#[derive(Identifiable, PartialEq, Queryable, Insertable)]
#[table_name = "applicant"]
pub struct User {
    pub id: i32,
    pub email: Vec<u8>,
    ...
}

#[derive(Identifiable, Queryable, Associations, Insertable)]
#[belongs_to(User, foreign_key = "email")]
#[table_name = "classes"]
pub struct Class {
    pub id: i32,
    pub email: Vec<u8>,
    pub school: String,
    ...
}
...

let students = users::table.load::<User>(conn).unwrap();
let classes = Class::belonging_to(&users).load::<Token>(conn).grouped_by(&users).unwrap();
let students_classes = users.into_iter().zip(tokens).collect::<Vec<_>>();
```

generates the error:

```bash
 Class::belonging_to(&users).load::<Token>(conn).grouped_by(&users).unwrap()
    |   ^^^^^^^^^^^^ function or associated item not found in `Class`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `belonging_to`, perhaps you need to implement it:
            candidate #1: `BelongingToDsl`

```

### What is the expected output?

No error

### What is the actual output?

```bash
 Class::belonging_to(&users).load::<Token>(conn).grouped_by(&users).unwrap()
    |   ^^^^^^^^^^^^ function or associated item not found in `Class`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `belonging_to`, perhaps you need to implement it:
            candidate #1: `BelongingToDsl`
```

### Are you seeing any additional errors?

No

### Steps to reproduce

```bash
gh repo clone ch3ck/dieserr && cd dieserr && cargo build
```

## Checklist

- [x] #1203
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by ch3ck** [comment]
Issue fixed, no longer necessary

**Comment by rcasurion** [comment]
What is the fix for this?

**Comment by weiznich** [comment]
@rcasurion Thats impossible to answer in the general case. Please open a new discussion thread with your question instead of commenting on old closed issues. Include at least some information about your setup, the relevant code and the exact error message as emitted by the compiler.
