### ISSUE TITLE
Issue in using infer_schema!

### ISSUE THREAD

**Issue by inxi-pc** [diesel-rs/diesel#309]
Hi,

When i flow the guide book to learn diesel using, i create schema.rs file and add the 

content : 

```rust
infer_schema!(env::var("DATABASE_URL").expect("DATABASE_URL must be set"));
```

Because my project .env file has been used, and it is toml format, not be compatible.

So i create a new file named env.diesel, and in my main.rs file, add this content:

```rust

    dotenv::from_filename("env.diesel").ok();
```

But i got the comlier error:

```rust

src/database/schema.rs:3:15: 3:74 error: expected string literal
src/database/schema.rs:3 infer_schema!(env::var("DATABASE_URL").expect("DATABASE_URL must be set"));
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/database/schema.rs:3:1: 3:76 note: in this expansion of infer_schema! (defined in src/main.rs)
error: aborting due to previous error

```

Could you help me? thanks very much.

**Comment by mfpiccolo** [comment]
The recommended approach is to use the dotenv! macro provided by the doenv crate.

`infer_schema!(dotenv!("DATABASE_URL"))`

**Comment by inxi-pc** [comment]
@mfpiccolo  hi, thanks..but could i use other way like my mentioned, because my .env file is using in project, and format is not compatible dotenv..

**Comment by mfpiccolo** [comment]
Both infer_schema! and dotenv! are compiler plugins which are expanding out code.  This means that dotenv! will expand out to be a string literal at compile time.  You can use env! in the standard library but you will have to get the the env set during compile time. 

https://doc.rust-lang.org/std/macro.env!.html

**Comment by inxi-pc** [comment]
@mfpiccolo  you means my mentioned way is in run time, so we cant use this. Because the macro! only can accept the string literal?

```rust 
infer_schema!(env::var("DATABASE_URL").expect("DATABASE_URL must be set"));
```

The way in complier time is a little not friendly..

i have a matter, dotenv! also get content from file, if we can set a string literal param for dotenv!?

**Comment by mfpiccolo** [comment]
I mean you could just pass the database url to infer_schema!

`infer_schema!("postgresql://localhost/some_database");`

**Comment by mfpiccolo** [comment]
Seems like what you really if you are looking for a way to load ENV from another file through the dotenv!.  You may want to open an issue here if that is the case https://github.com/slapresta/rust-dotenv.

**Comment by sgrif** [comment]
You can pass a string literal, or compile time macro that generates a string literal (like `dotenv!` if you're using the `rust-dotenv` crate, or `env!` from the standard library).

> The way in complier time is a little not friendly..

That's the tradeoff of a compiled language. We can't just evaluate arbitrary Rust code.
