### ISSUE TITLE
Installing diesel_cli without e.g. feature `sqlite` can lead to cryptic errors

### ISSUE THREAD

**Issue by deadalusai** [diesel-rs/diesel#310]
I have installed `diesel_cli` without SQLite support (as the SQLite libraries are not installed on my system):

```powershell
cargo install diesel_cli --no-default-features --features "postgres"
```

Invoking `diesel` with an invalid database url generates a cryptic error message:

```
> diesel database setup --database-url=https://localhost/test-db
thread '<main>' panicked at 'internal error: entered unreachable code: The backend function should ensure we never get here.', C:\Users\benjaminf\.cargo\registry\src\github.com-88ac128001ac3a9a\diesel_cli-0.6.1\src\database.rs:73
```

While the fix is simple (use the correct protocol), I did have to examine the source code to puzzle out the error message. Perhaps an improved error message could be implemented?

```rust
panic!(format!("The {0} backend is not supported. You must recompile with feature `{0}` enabled", other))
```

**Comment by sgrif** [comment]
@mcasper We should probably improve the check if SQLite isn't present, since we won't have that branch.

@deadalusai Your issue is that you're not giving a valid PG URL. It should start with `postgres://` or `postgresql://`
