### ISSUE TITLE
Initial setup migration isn't displayed

### ISSUE THREAD

**Issue by Enforcer007** [diesel-rs/diesel#3104]
### Versions

- **Rust:**1.59.0
- **Diesel:**1.4.8
- **Database:**postgres
- **Operating System:**Ubuntu

### Feature Flags

- **diesel:** postgres

## Problem Description
Trying to follow the steps mentioned in [getting-started guide](http://diesel.rs/guides/getting-started)

When running `diesel migration run` command. The initial migration is not printed in the console. 

### What are you trying to accomplish?
Print the initial migration step to the console.

### What is the expected output?
`Running migration 00000000000000_diesel_initial_setup` should be printed

### What is the actual output?
Prints only `Running migration 2022-03-30-031139_create_posts`

### Are you seeing any additional errors?
Nope

### Steps to reproduce
I'm sharing the video that has the steps.

https://user-images.githubusercontent.com/6951100/160848396-25021b19-4d7e-4346-80ee-5ce74847d2bc.mp4

**Comment by weiznich** [comment]
This is expected behaviour. See https://github.com/diesel-rs/diesel/pull/1042 for details.
