### ISSUE TITLE
MysqlConnection.set_config_options invalidates the default time zone of the database configuration

### ISSUE THREAD

**Issue by januwA** [diesel-rs/diesel#3112]
### Versions

- **Rust:** 1.59.0
- **Diesel:** 1.4.4
- **Database:** mysql
- **Operating System** CentOS Stream 8

### Feature Flags

- **diesel:**

## Problem Description

The mysql configuration file sets the default time_zone

```sh
# cat /etc/my.cnf | grep time_zone -C 1
[mysqld]
default-time_zone = '+8:00'
port            = 3306
```
But I found that diesel resets the time_zone for every link:
```rs
impl MysqlConnection {
    fn prepare_query<T>(&self, source: &T) -> QueryResult<MaybeCached<Statement>>
    where
        T: QueryFragment<Mysql> + QueryId,
    {
    
    ...

    fn set_config_options(&self) -> QueryResult<()> {
        self.execute("SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT'))")?;

       // here
        self.execute("SET time_zone = '+00:00';")?;


        self.execute("SET character_set_client = 'utf8mb4'")?;
        self.execute("SET character_set_connection = 'utf8mb4'")?;
        self.execute("SET character_set_results = 'utf8mb4'")?;
        Ok(())
    }
}
```

### What are you trying to accomplish?

Do not overwrite `my.cnf` when linking by default, or how to override how `set_config_options` is executed

### What is the expected output?

`time_zone = '+8:00'`

### What is the actual output?
`time_zone = '+00:00'`

### Are you seeing any additional errors?
null

### Steps to reproduce
null

## Checklist

When I comment out `self.execute("SET time_zone = '+00:00';")?;` I get the correct time after data insert

```rs
    fn set_config_options(&self) -> QueryResult<()> {
        self.execute("SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT'))")?;
        // self.execute("SET time_zone = '+00:00';")?;
        self.execute("SET character_set_client = 'utf8mb4'")?;
        self.execute("SET character_set_connection = 'utf8mb4'")?;
        self.execute("SET character_set_results = 'utf8mb4'")?;
        Ok(())
    }
```

**Comment by weiznich** [comment]
This is expected behaviour. See https://github.com/diesel-rs/diesel/commit/7da43282d1e9aef3bac7f15cdc4ec3a2bfd4dc01 and #1024 for reasons.
Additionally our check list is not optional. Removing it from the template generally results in closing the bug report as incomplete.
