### ISSUE TITLE
Compiler error on latest nightly rust

### ISSUE THREAD

**Issue by derekdreery** [diesel-rs/diesel#313]
Do other people get this? Downloaded latest nightly before testing.

```
diesel_codegen-0.6.1/src/insertable.rs:86:46: 86:54 error: no associated item named `empty` found for type `syntax::ptr::P<_>` in the current scope
/home/rdodd/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86         cx.typaram(span, str_to_ident("DB"), P::empty(), None),
```

**Comment by killercup** [comment]
I'm pretty sure that's fixed by #312, but it's not on crates.io yet.

Also, you should always use the nightly version that diesel_codegen uses (e.g., `multirust update nightly-2016-04-08 && rustup override add nightly-2016-04-08`).

**Comment by brookst** [comment]
Yes this was the reason for #312, I should have stated that was the error. Either work off of diesel master or use a nighty prior to 2016-04-25.

**Comment by derekdreery** [comment]
Thanksyou :+1:
