### ISSUE TITLE
Diesel_codegen won't compile

### ISSUE THREAD

**Issue by SphinxC0re** [diesel-rs/diesel#317]
Running `rustc /home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/lib.rs --crate-name diesel_codegen --crate-type dylib -C prefer-dynamic -g --cfg feature=\"nightly\" --cfg feature=\"postgres\" --cfg feature=\"diesel\" -C metadata=f1388be2227ebc98 -C extra-filename=-f1388be2227ebc98 --out-dir /home/sphinxc0re/Dokumente/Projekte/simply-say/target/debug/deps --emit=dep-info,link -L dependency=/home/sphinxc0re/Dokumente/Projekte/simply-say/target/debug/deps -L dependency=/home/sphinxc0re/Dokumente/Projekte/simply-say/target/debug/deps --extern diesel=/home/sphinxc0re/Dokumente/Projekte/simply-say/target/debug/deps/libdiesel-85b76bcc9835dd7c.rlib --cap-lints allow -L native=/usr/lib`
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86:46: 86:54 error: no associated item named `empty` found for type `syntax::ptr::P<_>` in the current scope
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86         cx.typaram(span, str_to_ident("DB"), P::empty(), None),
                                                                                                                                                                                     ^~~~~~~~
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86:46: 86:54 note: in this expansion of vec! (defined in <std macros>)
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86:46: 86:54 note: in this expansion of vec! (defined in <std macros>)
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/insertable.rs:86:46: 86:54 note: in this expansion of include!
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/queryable.rs:64:42: 64:50 error: no associated item named `empty` found for type `syntax::ptr::P<_>` in the current scope
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/queryable.rs:64     cx.typaram(span, str_to_ident(name), P::empty(), None)
                                                                                                                                                                                ^~~~~~~~
/home/sphinxc0re/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/diesel_codegen-0.6.1/src/queryable.rs:64:42: 64:50 note: in this expansion of include!
error: aborting due to 2 previous errors

**Comment by killercup** [comment]
Fixed in #312, not yet on crates.io.

**Comment by SphinxC0re** [comment]
Oh, okay thank you. When will this be updated on crates.io?

**Comment by killercup** [comment]
No idea, that's up to Sean :)

You can use `diesel = {git = "https://github.com/diesel-rs/diesel"}` in the meantime, though.

**Comment by sgrif** [comment]
🔜™

I'm currently in the process of moving and haven't had much time to work on things. 0.7 is almost ready to go, though. I'll see if I can roll a patch version with only the nightly change when I'm at my computer though.

**Comment by SphinxC0re** [comment]
Still won't compile

**Comment by sgrif** [comment]
You can also use an older nightly for the time being
