### ISSUE TITLE
Unable to open the database file

### ISSUE THREAD

**Issue by LEGOL2** [diesel-rs/diesel#3183]
### Versions

- **Rust:** `stable-x86_64-pc-windows-msvc` `rustc 1.61.0 (fe5b13d68 2022-05-18)`
- **Diesel:** diesel_cli 1.4.1
- **Database:** sqlite
- **Operating System** windows 11 21H2

### Feature Flags

- **diesel:** 

## Problem Description
```
λ diesel setup --database-url='sqlite://localhost/myBestDb'
Creating database: 'sqlite://localhost/myBestDb'
Unable to open the database file
```

### What are you trying to accomplish?
Use diesel cli tool to create an sqlite database, using "sql-bundled" feature, so I don't have to have libsqlite3 on my pc.

```
cargo install diesel_cli --no-default-features --features "sqlite-bundled"
diesel setup --database-url='sqlite://localhost/myBestDb'
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

Things I've also tried to compile from source with "sqlite-bundled" feature

**Comment by BlackDex** [comment]
For sqlite you need to provide a path to a file. If you do not have a directory called `localhost` then this will fail.
Either try to use a full path to the correct file, or use a correct relative location.
SQLite is not a network based connection.

**Comment by LEGOL2** [comment]
Thanks for help, I've replaced my `--database-url` argument with `--database-url=..\myBestDb.db` and it works fine.
