### ISSUE TITLE
Env variable interpolation with DATABASE_URL does not work

### ISSUE THREAD

**Issue by johhnry** [diesel-rs/diesel#3210]
### Versions

- **Rust:** rustc 1.61.0-nightly
- **Diesel:** v1.4.8
- **Database:** Postgresql
- **Operating System** Pop!_OS 22.04

### Feature Flags

- **diesel:** `cargo install diesel_cli --no-default-features --features postgres`

### What are you trying to accomplish?

Trying to interpolate environment variables for the `DATABASE_URL`:

```env
# .env

POSTGRES_USER=username
POSTGRES_PASSWORD=password
POSTGRES_DB=engine

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost/${POSTGRES_DB}"
```

### What is the expected output?

Using the `dotenvy` crate (v0.15.1) the output is:

```rust
use dotenvy::dotenv;
use std::env;

fn main() {
    dotenv().ok();
    println!("DATABASE_URL={}", env::var("DATABASE_URL").unwrap());
}
```

```
DATABASE_URL=postgres://username:password@localhost/engine
```

### What is the actual output?

Running `diesel setup` doesn't work:

```
Creating database: $%7BPOSTGRES_DB%7D
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "${POSTGRES_USER}"
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for opening this issue. As your code snippet does not contain any diesel related code I would like to understand why you filled this issue here instead of in the dotenvy issue tracker?

**Comment by johhnry** [comment]
Hi @weiznich,

Thanks for answering my issue. I am using Diesel 1.4.8, what do you mean by using a version "compiled from the master branch"?

Also I first tried interpolating variables with the `dotenv` crate then I saw that you were using the most recent `dotenvy` so I modified my post according to that and it seems to work.

I just saw that the `diesel_cli` `v1.4.1` uses `dotenv` instead of `dotenvy`: https://crates.io/crates/diesel_cli/1.4.1/dependencies is it normal?

**Comment by weiznich** [comment]
As you already noticed does the master branch contain many changes compared to the 1.4.1 release. This is expected as development needs to happen somewhere. These changes include the switch from dotenv to dotenvy. That's why I'm asking if that also happens with either a diesel-cli version compiled from the master branch via `cargo install diesel_cli --git https://github.com/diesel-rs/diesel` or by installing the 2.0.0-rc.0 version by crates.io

**Comment by johhnry** [comment]
All right thanks I understand now (didn't know you could install directly from git).

It works with `diesel 2.0.0-rc.0`!

**Comment by weiznich** [comment]
Thanks for reporting back
