### ISSUE TITLE
infer_schema! fails for boolean/bool

### ISSUE THREAD

**Issue by iqualfragile** [diesel-rs/diesel#322]
i get

```
src/schema.rs:1:1: 1:40 error: Unsupported type: boolean
src/schema.rs:1 infer_schema!(dotenv!("DATABASE_URL"));
```
or 
```
src/schema.rs:1:1: 1:40 error: Unsupported type: bool
src/schema.rs:1 infer_schema!(dotenv!("DATABASE_URL"));
```

im using rust nightly 2016-04-09 and diesel 0.6.1 with sqlite enabled
cargo.toml look like this:
```
[dependencies]
diesel = "0.6.1"
diesel_codegen = { version = "0.6.1", default-features = false, features = ["nightly", "sqlite"] }
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
```

my crete table statement is:
```
create table messages (
        hash blob PRIMARY KEY,
        head BOOL,
        content blob not NULL
);
```
my model is:
```
#[derive(Debug,Clone)]
pub struct Hash(pub [u8;32]);

#[derive(Queryable,Debug)]
pub struct Messages {
    pub hash: Hash,
    pub head: bool,
    pub content: Vec<u8>,
}
```

**Comment by sgrif** [comment]
Can you try pointing at master? This should have been resolved by https://github.com/diesel-rs/diesel/commit/ccad1510c197d73dbfd474c9f9a82d470055e486, which will be released later this week.

**Comment by iqualfragile** [comment]
damn, second fixed bug in diesel i run in today.

**Comment by sgrif** [comment]
Sorry! I've been moving to another country for the last 2 weeks so I
haven't had time to finish the release.  😔

**Comment by iqualfragile** [comment]
btw on the embracing sqlite philosophy of untyped sql: i really really don't think thats a good idea, i would just handle it as if the type definitions would be definitive, just like postgress does. there is not really a good usecase for storing different types into the same collumn anyways.
just fail with a good error message if someone put stupid values into the db.

**Comment by sgrif** [comment]
Yeah, that's likely the direction we'll continue with -- just means that
we'll be chasing edge cases for a while
