### ISSUE TITLE
An incorrect foreign_key variable for the belongs_to attribute should trigger the same compile time check that occurs when an incorrect foreign_key is determined by diesel. 

### ISSUE THREAD

**Issue by dennismarwood** [diesel-rs/diesel#3272]
## Setup
Rust: rustc 1.62.1 (e092d0b6b 2022-07-16)
Diesel: 1.4.1
Database: mysql
Operating System Ubuntu 20.04.4

## Problem Description
The  belonging_to attribute will cause a compile error (error: proc-macro derive panicked) if it cannot find the expected default value. However, it will not perform the same check if the user specifies an incorrect foreign_key value. 

### What are you trying to accomplish?
Expand error checking to look at what the user provided and throw an error if it is not valid.

### What is the expected output?
A "error: proc-macro derive panicked" should be displayed if an incorrect foreign_key is supplied. And the nice message on how to fix it "help: message: No field with column name foo_fiz_id".

### What is the actual output?
No output. No error is thrown.

### Are you seeing any additional errors?
No.

### Steps to reproduce
Follow the steps at https://docs.rs/diesel/latest/diesel/associations/index.html . But specify an incorrect foreign_key for the belongs_to attribute.

## Checklist

- [x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.

- [x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Please provide a complete minimal example. (To be clear this issue does not match the code in your example in the gitter channel because it does use a valid column name there, as id exists on your table.)

**Comment by dennismarwood** [comment]
Yes, I see that now. I guess I should not have opened this just before calling it a night. :)
