### ISSUE TITLE
Error when testing crate diesel_codegen

### ISSUE THREAD

**Issue by Coding-Doctors** [diesel-rs/diesel#329]
I'm getting this error after running `cargo test`, I'm using the nightly version `diesel v0.6.1 (https://github.com/diesel-rs/diesel.git#2af2eaa3)` in my dependencies, (which looks like `diesel_codegen     = { git = "https://github.com/diesel-rs/diesel.git", default-features = false, features=["nightly", "sqlite"] }` in my cargo.toml) however I'm unsure whats causing this since it seems to come and go after installing diesel_cli. This is reproducable off and on locally and on travis.

```
error: plugin `diesel_codegen` only found in rlib format, but must be available in dylib format
```

My rust version is:
`rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)`
My cargo version is:
`cargo 0.11.0-nightly (b304305 2016-05-06)`

**Comment by sgrif** [comment]
You should be able to work around this temporarily by cloning the repo down and pointing at the path instead of at git.

**Comment by sgrif** [comment]
Caused by https://github.com/diesel-rs/diesel/commit/f90217f80320e922323d9906dd1028e94eb1c954

**Comment by TheDoctorsLife** [comment]
Same issue when cloning it down and pointing at the path. https://travis-ci.org/Alchemist-rs/Alchemist/jobs/130398227

**Comment by sgrif** [comment]
I'll see if I can come up with reliable steps to reproduce, as I've seen this locally intermittently but I'm not sure what caused it. In the short term you can just revert the commit I referenced in the previous comment to work around

**Comment by TheDoctorsLife** [comment]
Any update on this?

**Comment by sgrif** [comment]
Haven't had a ton of time to look into it yet

**Comment by sgrif** [comment]
I fixed it by deleting `diesel_codegen`.
