### ISSUE TITLE
Insertable derive macro causes struct properties to fail to compile with `error: unnecessary qualification` error when `-Dunused_qualifications` rustc flag used

### ISSUE THREAD

**Issue by mikemcdermottredjack** [diesel-rs/diesel#3313]
## Setup
.cargo/config:
[target.'cfg(all())']
rustflags = [
    "-Dunused_qualifications"
]

lib.rs: 
use diesel::Insertable;

#[derive(Insertable)]
struct MyTable {
    my_column: i32
}

cargo.toml:
[dependencies]
diesel = { version = "~2.0", features = ["postgres", "postgres_backend", "chrono", "r2d2", "uuid"], default-features = false }

### Versions

Rust: 1.63
Diesel: 2.0.0
Database: PgSQL
OS: MacOS

## Problem Description
Building with rustc -Dunused_qualifications causes properties of structs using the Insertable derive macro to fail with an unnecessary qualification error, regardless of whether or not the property of the struct is used.

### What is the expected output?
No error

### What is the actual output?
Error

### Are you seeing any additional errors?
No

### Steps to reproduce
See attached test project for minimal reproducible example
[test_diesel_bug.tar.gz](https://github.com/diesel-rs/diesel/files/9529720/test_diesel_bug.tar.gz)

Run cargo build on the project. 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
Yes

**Comment by saethlin** [comment]
It looks like in the provided example the `#[derive(Insertable)]` expands to:
```rust
#[allow(unused_imports)]
const _: () = {
    use diesel;
    use diesel::insertable::Insertable;
    use diesel::internal::derives::insertable::UndecoratedInsertRecord;
    use diesel::prelude::*;
    impl Insertable<my_tables::table> for MyTable {
        type Values = <(
            std::option::Option<diesel::dsl::Eq<my_tables::my_column, i32>>,
        ) as Insertable<my_tables::table>>::Values;
        fn values(
            self,
        ) -> <(
            std::option::Option<diesel::dsl::Eq<my_tables::my_column, i32>>,
        ) as Insertable<my_tables::table>>::Values {
            (std::option::Option::Some(my_tables::my_column.eq(self.my_column)),)
                .values()
        }
    }
    impl<'insert> Insertable<my_tables::table> for &'insert MyTable {
        type Values = <(
            std::option::Option<diesel::dsl::Eq<my_tables::my_column, &'insert i32>>,
        ) as Insertable<my_tables::table>>::Values;
        fn values(
            self,
        ) -> <(
            std::option::Option<diesel::dsl::Eq<my_tables::my_column, &'insert i32>>,
        ) as Insertable<my_tables::table>>::Values {
            (std::option::Option::Some(my_tables::my_column.eq(&self.my_column)),)
                .values()
        }
    }
    impl UndecoratedInsertRecord<my_tables::table> for MyTable {}
};
```
I feel like there should be an `#[automatically_derived]` in here?

**Comment by weiznich** [comment]
There is unfortunately no ways for proc-macros to check for items in scope. Therefore we need to always generate fully qualified references to types/traits/.... Additionally as  `unused_qualifications` is an allowed by default  lint I do consider as a minor issue. This means I likely will not spend time on fixing this by myself, but I would accept a PR for that.

**Comment by saethlin** [comment]
Does `#[automatically_derived]` not help with this?

**Comment by weiznich** [comment]
It might or it might not. As pointed out above: I personally do not want to invest my time here, so feel free to try it. I accept any solution that does not change the generated rust code (adding attributes like that or `#[allow]` is ok)

**Comment by weiznich** [comment]
It might or it might not. As pointed out above: I personally do not want to invest my time here, so feel free to try it. I accept any solution that does not change the generated rust code (adding attributes like that or `#[allow]` is ok)

**Comment by mikemcdermottredjack** [comment]
@saethlin  I'll take a stab at fixing this. I would like the opportunity to learn.

**Comment by weiznich** [comment]
@mikemcdermottredjack The relevant generation code is here: https://github.com/diesel-rs/diesel/blob/9502a9fd3df61bcfd59c63fecb79e242802e99d6/diesel_derives/src/insertable.rs#L117

You can just add a `#![deny(unused_qualifications)]` here to test whether the fix works or not: 
https://github.com/diesel-rs/diesel/blob/9502a9fd3df61bcfd59c63fecb79e242802e99d6/diesel_derives/tests/insertable.rs#L1

**Comment by mikemcdermottredjack** [comment]
I found the source of this issue. In `diesel_derives/src/insertable.rs` there are a few instances where `Option` is defined unnecessarily as `std::option::Option` in the proc macro. Changing this fixes the issue. I can submit a PR but it appears I don't have permission to publish my branch (`git push origin branch_name` results in a 403 error)

**Comment by weiznich** [comment]
@mikemcdermottredjack That's unfortunately not possible as this would break usecases where the derive is used in a scope containing some other item named `Option`. So for example it would break code like this:

```rust
type Option = std::option::Option<i32>;

#[derive(Insertable)] 
struct Foo {
 // …
}
```

I see two potential solutions here:
* Design and implement a rust proc-marco API that checks whether a certain name is in scope or not (That's a lot of work)
* Figure out some way to just suppress this lint for the generated code (More a workaround, but easy to apply)

As mentioned above: I would accept a PR for the second solution (also for the first one if someone ever implements that, but that seems unlikely)

**Comment by mikemcdermottredjack** [comment]
> Figure out some way to just suppress this lint for the generated code (More a workaround, but easy to apply)

This seems to do the trick (diesel_derives/src/insertable.rs): 

```
 #[allow(unused_qualifications)]
 #insert_owned

 #[allow(unused_qualifications)]
 #insert_borrowed
```

**Comment by weiznich** [comment]
As pointed out quite a few times before: It's not a priority to provide a fix for this for me. I will accept a PR for this, but won't write any code. That's likely my last response here as I've already spend more time than necessary on this (non-)issue.
