### ISSUE TITLE
Diesel 2.0: Wrong `postgres_type` naming

### ISSUE THREAD

**Issue by omid** [diesel-rs/diesel#3314]
### Versions
- **Rust:** Latest
- **Diesel:** 2.0
- **Database:** PostgreSQL
- **Operating System:** Linux

### Feature Flags
- **diesel:** postgres

## Problem Description
When there is a custom type, which it's name contains capital letters. The generated name in the `schema.rs` file will be in lower case, like the following example:

```
pub mod sql_types {
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "poststatus"))]
    pub struct PostStatus;
}
```

In this case, inserting a row (it needs to contain the custom type), will return an error like this:
```
thread 'main' panicked at 'Error saving new post: SerializationError(FailedToLookupTypeError(PgMetadataCacheKey { schema: None, type_name: "poststatus" }))', src/lib.rs:30:10
```

postgres also reports this:
```
ERROR:  type "poststatus" does not exist
STATEMENT:  SELECT "pg_type"."oid", "pg_type"."typarray" FROM "pg_type" WHERE ("pg_type"."oid" = quote_ident($1)::regtype::oid) LIMIT $2
```

The same can happen for other queries, like select by the custom type, or update or so on.

### Steps to reproduce
- Clone this sample project: https://github.com/omid/diesel_demo
- Run postgresql
- Configure `.env` file
- Run `make`, then you will see the error
- It will work if you go to `schema.rs` and change `poststatus` to `PostStatus`, and run `cargo run --bin write_post`

**Comment by Ten0** [comment]
This would probably be the issue:
https://github.com/diesel-rs/diesel/blob/cb185429d1ed8550f25615e84c14534692da8bda/diesel_cli/src/infer_schema_internals/pg.rs#L46

And there's the same on the mysql side:
https://github.com/diesel-rs/diesel/blob/cb185429d1ed8550f25615e84c14534692da8bda/diesel_cli/src/infer_schema_internals/mysql.rs#L155

@weiznich any particular reason why there is a to_lowercase call here or should we just remove them?

**Comment by weiznich** [comment]
> @weiznich any particular reason why there is a to_lowercase call here or should we just remove them?

I cannot remember a particular reason for this + this seems to cause this bug. Removing the `.to_lowercase()` call in the postgres implementation should be fine as long as all tests continue to pass. @omid Mind filling a PR for this which removes the call + adds something like your type definition as test case?

**Comment by omid** [comment]
@weiznich sure, will try my best
