### ISSUE TITLE
Wrong documentation around sqlite datetime / inference not taking tz into account

### ISSUE THREAD

**Issue by Sytten** [diesel-rs/diesel#3320]
### Versions

- **Rust:1.61**
- **Diesel:2.0.0**
- **Database:Sqlite**
- **Operating System**

### Feature Flags

- **diesel: time**

## Problem Description

It looks like the documentation surrounding timestamps for Sqlite is wrong.
Specially https://github.com/diesel-rs/diesel/blob/e9a951f1dc8ae893c31002ea2e00690c91e86ce4/diesel/src/sql_types/mod.rs#L335 and https://github.com/diesel-rs/diesel/blob/e9a951f1dc8ae893c31002ea2e00690c91e86ce4/diesel/src/sql_types/mod.rs#L342

The `FromSql` to `ToSql` traits are only implemented for `TimestamptzSqlite` for `OffsetDateTime`. Which currently you have to change manually in the schema since there is no inference for it.

### What are you trying to accomplish?

- Allow inference to automatically detect the TZ version
- Change the documentation to reflect that
- (Maybe) Rename `TimestamptzSqlite` since it's pretty ugly, but I guess there is a reason behind that choice

I will do the change if we agree on what the behaviour should be.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
> The FromSql to ToSql traits are only implemented for TimestamptzSqlite for OffsetDateTime.

This is correct. The documentation is wrong there and needs to be changed. PR's welcome.

> Which currently you have to change manually in the schema since there is no inference for it.

That's how it's currently designed as we have no way to infer the correct type here. See the corresponding discussion here for details: https://github.com/diesel-rs/diesel/pull/3087#discussion_r827332271 There is just no straight forward way to automatically infer whether a column supports time zones or not by only knowing the type name. That all written: I'm open for suggestions here.

> (Maybe) Rename TimestamptzSqlite since it's pretty ugly, but I guess there is a reason behind that choice

That's mostly to indicate that this type has different semantics than the `Timestamptz` type from postgres. I'm open to deprecating and renaming it to something better if someone comes up with an obvious better name.

**Comment by Sytten** [comment]
The PR is on my todo, I built a custom type of datetime that uses the offset datetime under the hood so that is also a path that works well (and if you implement Deref then is it basically the same output).

Well for sqlite we can whatever we want in the column type so we could add support for timestamptz? What do you think?

Is there really a need to differentiate? I get the idea but if we can emulate the feature of postgres it could use the same name. The only annoying thing with the name currently is that you have to import in the generated schema file, you can't just type  `TimestamptzSqlite` (though `Timestamptz` is available if postgres is enabled).

**Comment by weiznich** [comment]
> The only annoying thing with the name currently is that you have to import in the generated schema file, you can't just type TimestamptzSqlite (though Timestamptz is available if postgres is enabled).

That's something that should definitively fixed by just adding a reexport for `TimestamtzSqlite` in `diesel::sql_types` (if the sqlite feature is enabled)
