### ISSUE TITLE
Allow full path for tables in joinable! macro

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#333]
It's currently only possible to pass an identifier as table to the joinable! macro (and also the #[belongs_to] and #[has_many] annotations).
Possible:

``` rust
use some_module::my_table_a;

joinable!(my_table_a -> my_table_b (some_field));
```

Not possible:

``` rust
joinable!(some_module::my_table_a -> my_table_b (some_field));
```

Results in:

```
error: no rules expected the token `::`
  --> src/lib.rs:19:28
19 |> joinable!(some_module::my_table_a -> my_table_b (some_field));
   |>                      ^^
```

**Comment by Eijebong** [comment]
The problem is that we can't just change those `ident` by `path` as a path cannot be followed by a `->` nor by a `(` so it would require changing to something like `joinable!(foo::bar => baz::lol { foo::bar::field })`
