### ISSUE TITLE
Let infer_schema also infer associations

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#335]
infer_schema could also try to infer some associations from foreign key constrains and add the corresponding implementations of JoinTo.

For example the following case:

``` sql
CREATE TABLE A(id SERIAL PRIMARY KEY, b_id INTEGER REFERENCES B(id));
```

It should be possible to let the macro implement the following association(or something similar to this):

``` rust
joinable!(a -> b (b_id));
```

This could probably be implemented after the release of diesel 1.0, but keep in mind it could be a minor breaking if you implement this relation already manually.

**Comment by Eijebong** [comment]
I think this one can be closed now that #1070 and #1077 have landed.
