### ISSUE TITLE
sqlite `returning_clauses_for_sqlite_3_35` DatabaseError(Unknown, "near "RETURNING": syntax error")'

### ISSUE THREAD

**Issue by raed667** [diesel-rs/diesel#3354]
### Versions

- **Rust:** rustc 1.64.0 (a55dd71d5 2022-09-19)
- **Diesel:** diesel 2.0.0
- **Database:** sqlite v3.39.4 
- **Operating System** rust:latest

### Feature Flags

- **diesel:**  `[ "sqlite", "returning_clauses_for_sqlite_3_35",]`

## Problem Description

When running locally the `RETURNING` statement works correctly.  When running inside a Docker image it throws an error: `DatabaseError(Unknown, "near \"RETURNING\": syntax error")'`

### Steps to reproduce

I have created a reproduction repository with a minimal setup here: https://github.com/raed667/sqlite-returning-docker 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for providing a reproducible example. This always helps finding the underlying issue.

I've applied the following path to your repo to get the linked sqlite version.

```diff
diff --git a/src/main.rs b/src/main.rs
index ad0cbe0..bd615e4 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -5,9 +5,13 @@ mod db;

 fn main() {
     println!("Hello, world!");
+    use diesel::prelude::*;

     let connection = &mut establish_connection();

+    let version = diesel::dsl::sql::<diesel::sql_types::Text>("select sqlite_version()").get_result::<String>(connection).unwrap();
+    dbg!(version);
+
     let user = insert_user(connection);

     println!("Inserted user id={}", user.id)
```

This returns the following output:

```
[src/main.rs:13] version = "3.34.1"
```

This output indicates that there is another older libsqlite3 version in your container. This version is linked by rustc to your binary and it's too old to support `RETURNING`. You need to use the newer version. Checkout the documentation of `libsqlite3-sys` for how to setup the correct path.

Closed as this is not an issue in diesel.

**Comment by raed667** [comment]
Thanks a bunch for the help !

**Comment by raed667** [comment]
Just in case someone reads this in the future. I added the following line to `Cargo.toml`

```toml
[dependencies]
rusqlite = { version = "0.27", features = ["bundled"] }
```

Which basically bundles sqlite with the library.
