### ISSUE TITLE
[diesel_cli] There should be a way to provide backend specific migrations

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#336]
I'm trying to support postgresql and sqlite in my application. To write the migrations for both I need to do some small changes in my migrations. For example changing postgres `BIGSERIAL PRIMARY KEY` into `INTEGER PRIMARY KEY`.

It would be great to allow writing backend specific migrations. For example in each migration directory could be a up.sql file which contains a migration that should be executed on all backends. Or there could be a up.sqlite.sql and a up.pg.sql file which contains backend specific sql for this migration.

**Comment by sgrif** [comment]
There is a "way" to do this right now, by supplying a migration directory manually. I'm not sure that maintaining schemas on multiple backends in the same code base is a common enough use case to warrant any support beyond that.

**Comment by toudi** [comment]
oh, I was just about to ask the same question :D I actually thought that in the SQL file there could be like a comment section or something, like:

````
create table ... ( whatever your default syntax is )
--- backend: sqlite ( or postgreSQL )
create table .... ( whatever the backend-specific syntax is )
```

**Comment by sgrif** [comment]
Closing as I don't see this being a feature that we pursue any time soon.
