### ISSUE TITLE
Weird retention on cached sqlite connection

### ISSUE THREAD

**Issue by FirelightFlagboy** [diesel-rs/diesel#3408]
### Versions

- **Rust: 1.65**
- **Diesel: 2.0.2**
- **Database: Sqlite**
- **Operating System: Linux 6.0.8**

### Feature Flags

- **diesel: sqlite, r2d2**

### What are you trying to accomplish?

I have create a gist for the problem <https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874> (only work on linux to inspect `/prod/:pid/fd` folder)

On a project, I was opening `sqlite` connections to a database using `diesel`.
We found out that if we have a long lived `SqliteConnection` (<https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874#file-main-rs-L17-L21>)
and we opened a few other `SqliteConnection` (with the same configuration as the long lived one) (<https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874#file-main-rs-L25-L28>)
and drop them after some time (<https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874#file-main-rs-L32>)
Those connection would remain opened until the long lived one is closed (<https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874#file-main-rs-L36>).

### What is the expected ~output~ result ?

Only 1 connection to be opened to the database file or the few other `sqlite` connections fds to be closed when they're dropped.

### What is the actual output ?

Connection are still opened under `/proc/:pid/fd`

```text
lrwx------ 1 foo foo 64 14 nov.  10:45 10 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 100 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 102 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 104 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 106 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 108 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 110 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 112 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 114 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 116 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 118 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 12 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 120 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 122 -> /tmp/database.sqlite
lrwx------ 1 foo foo 64 14 nov.  10:45 124 -> /tmp/database.sqlite
...

Opened connections result:
                 pre = 0
                iter = 3
         before drop = 203
          after drop = 103
long connection drop = 0

diff after - before = -100
diff after - iter   = 100
```

> When dropping `connections` we close 100 fds but 100 other fds are still open (of the 200's)

### Steps to reproduce

Actual gist: <https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874>

:warning: Work on linux only because we read the folder `/prod/:pid/fd`

> Note: that problem arise only with the conjunction of using `pragma` and executing a query on each connection.
> You can try that by changing the flags at <https://gist.github.com/FirelightFlagboy/73ad3dfab2c861cbc8a8940e36869874#file-main-rs-L11-L13>

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Can you explain why you believe that this is a bug in diesel and not somewhere else? 

We open sqlite connections via the corresponding C function here: https://github.com/diesel-rs/diesel/blob/027be9b155a3439ede6c947bd1de30cd8954c3c4/diesel/src/sqlite/connection/raw.rs#L47 and close them via a `Drop` impl here: https://github.com/diesel-rs/diesel/blob/027be9b155a3439ede6c947bd1de30cd8954c3c4/diesel/src/sqlite/connection/raw.rs#L213

[The documentation of `sqlite3_open_v2`](https://www.sqlite.org/c3ref/open.html) indicates that we need to call `sqlite3_close` on the corresponding ptr to close the database connection. Everything else is handled by sqlite internally. Based on this I cannot see how that's a bug in diesel.

**Comment by FirelightFlagboy** [comment]
Hi @weiznich 

Thank you for reaching me out.

For your question:
> Can you explain why you believe that this is a bug in diesel and not somewhere else?

I've done more testing (especially testing with only `libsqlite3-sys`) and I've the same behavior without using `diesel`.

So it's not a bug in `diesel`.

Since the problem isn't related to `diesel` I'll close this issue.

Thank you for your time

**Comment by weiznich** [comment]
Thanks for coming back and reporting your findings
