### ISSUE TITLE
update online docs

### ISSUE THREAD

**Issue by durka** [diesel-rs/diesel#341]
[They](http://docs.diesel.rs/diesel/index.html) are out of date.

**Comment by sgrif** [comment]
What part of them is out of date? They're updated automatically when the build passes

**Comment by durka** [comment]
They didn't seem to match the crates.io version we were looking at on IRC, but I guess we were confused.

**Comment by sgrif** [comment]
Yeah, they track master at the moment. The plan is to have the docs.diesel.rs URL track the latest release once we're post 1.0
