### ISSUE TITLE
Infer_schema! generates joinable for composite Foreign Key

### ISSUE THREAD

**Issue by lochetti** [diesel-rs/diesel#3446]
## Setup
The following repository was used to setup and reproduce the problem: https://github.com/lochetti/diesel_joinable_composite_fk

The problem is reproduced just by running the migration with the print_schema enabled.

### Versions

- **Rust**: 1.65
- **Diesel**: 2.0.2
- **Database**: Postgresql
- **Operating System**: Fedora 37

### Feature Flags

- **diesel:**["32-column-tables", "chrono", "numeric", "postgres", "r2d2", "without-deprecated"]

## Problem Description
According to [the documentation](https://docs.diesel.rs/diesel/macro.joinable.html)  we didn't expect to have a joinable being created between the second and third tables, since the only relationship between them is the composite foreign key.

A more dangerous implication of this problem is that it seems that diesel chooses the first column to be the joinable which could lead to wrong joining strategies. This can be verified by changing the order of the columns in the definition of the foreign key, in the migration file, which generates a different join strategy.

### What are you trying to accomplish?
I'm trying to be sure that the infer_schema only creates joinables that are correct, and in that case the joinable created could not be correct.

### What is the expected output?
I expect to don't have a joinable between those tables, according to the documentation provided.

### What is the actual output?
See the schema.rs file in the [setup repository](https://github.com/lochetti/diesel_joinable_composite_fk/blob/main/src/schema.rs).

### Are you seeing any additional errors?
No.

### Steps to reproduce
1. clone the repository
2. configure a postgres database_url in the .env file
3. Run `diesel setup` .
4. See the outputed schema.rs file

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues. 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for opening this issue. I've tried to reproduce this based on the provided repository, but for me it does not output 2 foreign keys.

Can you please verify that you:
* Use the latest version of diesel_cli
* That your example actually reproduces the issue
* Add more information about your environment (postgres version, …)

**Comment by lsunsi** [comment]
I tried to reproduce here with @lochetti 's repo (me and him found this weird behavior together), and got the same results. The image I'm using is `docker.io/postgres:11.5-alpine`. The schema committed to repository is unchanged after db setup.

**Comment by lochetti** [comment]
I have tested in various docker postgres images.

- docker.io/postgres:10 -> I was able to reproduce the problem
- docker.io/postgres:11 -> I was able to reproduce the problem
- docker.io/postgres:12 -> Don´t show the error. Looks like it's ok.
- docker.io/postgres:13 -> Don´t show the error. Looks like it's ok.
- docker.io/postgres:14 -> Don´t show the error. Looks like it's ok.
- docker.io/postgres:15 -> Don´t show the error. Looks like it's ok.

So, it looks like the problem only happens in versions older than 12.

**Comment by weiznich** [comment]
Thanks for coming back to report that this is problem depending on the used postgres version. As this does only affect older postgres versions I do not consider that as a critical bug. I would accept a fix nevertheless as long as it does not break newer postgres versions.

The relevant code is here: 
https://github.com/diesel-rs/diesel/blob/027be9b155a3439ede6c947bd1de30cd8954c3c4/diesel_cli/src/infer_schema_internals/information_schema.rs#L191

This code loads the foreign key constraints from the information schema. We likely miss some condition there to make this work on older postgres version. It might be helpful to just dump the query via `diesel::debug_query` and try to modify the relevant parts in a local postgres command line. You don't need to run `diesel setup` anytime to reproduce the issue. `diesel print-schema` has the same behavior.

**Comment by weiznich** [comment]
Thanks for the update. I was able to reproduce the described problem. See #3451 for a fix.

**Comment by lochetti** [comment]
Thanks @weiznich ! Is there anything else that I could do to help?

**Comment by weiznich** [comment]
@lochetti It might be helpful to verify that the proposed fix works:

* on your real code
* on all postgres versions you've tested above

**Comment by lochetti** [comment]
@weiznich , I have looked and there are two things that I want to highlight:
1. I don´t see, anymore, cases of composite foreign key creating joinables :)
2. But, I do see joinables being created for simple foreign keys on tables that also have composite foreign keys.

I actually liked this behaviour better, because we can have a simple and a composite foreign key between two tables AND still have the joinable being created for the simple foreign key. With that said, this might contradict the third bullet point that says that no joinable will be genarated when "There is more than one foreign key connecting two tables
", as you can see [here](https://docs.diesel.rs/diesel/macro.joinable.html). 

Also I tested diesel setup on my real project using postgres 11 until 15, and all generated schemas file were the same.

**Comment by weiznich** [comment]
@lochetti Thanks for checking out the fix and pointing out these issues. I've pushed another version which should address that as well.

**Comment by lochetti** [comment]
Great! Let me know when I can test this new push.

**Comment by weiznich** [comment]
@lochetti Should be ready for tests

**Comment by lochetti** [comment]
@weiznich I have tested with the new push and now everything looks ok:
- I don't see, anymore, cases of composite foreign key creating joinables :)
- And, the third bullet point of the [documentation](https://docs.diesel.rs/diesel/macro.joinable.html) is respected.

Again, I have tested on my reala project using postgres from 11 until 15.
