### ISSUE TITLE
Push the 0.6.2 version?

### ISSUE THREAD

**Issue by KokaKiwi** [diesel-rs/diesel#345]
The crate `r2d2-diesel` use the crates.io release of `diesel`, which cause problem with the git version because `diesel` is at version `0.6.1` on the git repository.
Why not bumping the git version to `0.6.2` to in order to fix this?

**Comment by sgrif** [comment]
r2d2-diesel uses `diesel = ">= 0.5.0, < 0.7.0"`

**Comment by nox** [comment]
You published diesel 0.6.2 but it's not in the Git repository. Did it become closed-source?

**Comment by Eijebong** [comment]
@nox  https://github.com/diesel-rs/diesel/releases/tag/v0.6.2

**Comment by nox** [comment]
Ok, you just forgot to push the branch then?

https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L3

**Comment by sgrif** [comment]
There is no branch, it was a single cherry picked commit

**Comment by nox** [comment]
That doesn't explain why `master` isn't 0.6.2. Could you make `master` the 0.6.2 version as expected?

**Comment by sgrif** [comment]
Because 0.6.2 was a minor patch on 0.6.1 done long after master had changes
that I didn't want to release
