### ISSUE TITLE
Diesel 1.4.8 requries Chrono with `oldtime`

### ISSUE THREAD

**Issue by gahag-cw** [diesel-rs/diesel#3452]
### Versions

- **Diesel:** 1.4.8

### Feature Flags

- **diesel:** `chrono`

## Problem Description

Diesel 1.4.8 requires `chrono` as:
```
chrono = { version = "0.4", optional = true }
```

While Diesel 2.0.2 requiers `chrono` as:
```
chrono = { version = "0.4.20", optional = true, default-features = false, features = ["clock", "std"] }
```

The issue is that the default features from `chrono` contain the `oldtime` feature, which in turn requires a version of `time` that has [known security issues](https://github.com/time-rs/time/issues/293). Is there a chance we can get a new patch release for the 1.4 series disabling the default features from `chrono`?

**Comment by weiznich** [comment]
Thanks for opening this issue. We do not provide support for old 1.x releases anymore. We just do not have the capacity to maintain mor than one diesel version in our free time.
