### ISSUE TITLE
Backend-agnostic connections

### ISSUE THREAD

**Issue by flying-sheep** [diesel-rs/diesel#346]
I’d like to create a `impl Connection for PgOrSqliteConnection` or at least a `Box<Connection>` but the former requires me to implement dozens of interfaces and the latter is impossible due to the associated `Backend` type.

**Comment by sgrif** [comment]
Connections aren't object safe, and basically never will be able to with Rust as it is today. You'll have to write your functions as `fn foo<T: Connection>(conn: &T)`
