### ISSUE TITLE
the trait bound `(diesel::sql_types::Integer, diesel::sql_types::Text, diesel::sql_types::Integer): load_dsl::private::CompatibleType<diesel_demo::models::Person, _>` is not satisfied

### ISSUE THREAD

**Issue by PeHo89** [diesel-rs/diesel#3461]
For days I am trying to set up Diesel now but I can't manage to do it. I always end up with this type of error message. I am almost sure I implemented everything the way it is shown (except the data model).

What do I need to do in order to get rid of this error?

I am very grateful for every kind if help. Thanks!

<img width="1396" alt="Screenshot 2022-12-25 at 18 24 26" src="https://user-images.githubusercontent.com/26039145/209476981-b9a9928d-7fbb-44c2-9474-a8aa1ce2f025.png">

**Comment by Guileas** [comment]
@PeHo89 I ran into the same problem today how did you solved it?

**Comment by mohe2015** [comment]
> @PeHo89 I ran into the same problem today how did you solved it?

This usually means that the rows you `select`ed (by default all rows) (in this case the tuple `(Integer, Text, Integer)`) doesn't match the struct members into which you want to `load`. So either the members in the `Person` struct are not in the same order or they are not equal to the Rust analogue `i32, String, i32` (I think it's i32, not sure)

**Comment by Guileas** [comment]
Thanks @mohe2015 problem solved, that was it  and I forgot to add the `chrono` feature flag in my `Cargo.toml` file.
