### ISSUE TITLE
Diesel does not resolve hostname via nsswitch

### ISSUE THREAD

**Issue by MasinAD** [diesel-rs/diesel#3463]
### Versions

- **Rust:** ? whatever is used by https://github.com/dani-garcia/vaultwarden to build the binary
- **Diesel:** 2.0.2
- **Database:** mariadb Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapper
- **Operating System**: Debian 11 Bullseye

### Feature Flags

- **diesel:** I don't know. Does https://github.com/dani-garcia/vaultwarden/blob/main/Cargo.lock#L612 help?

## Problem Description
For full problem description refer to https://github.com/dani-garcia/vaultwarden/issues/3056

In short: Diesel complains about not being able to resolve hostname `db`. The machine where vaultwarden is running on can resolve this hostname. The vaultwarend developer suggests reporting the issue here.

### What are you trying to accomplish?
Name resolution in a bunch of nspawn containers so that I'm not dependent on hard configuring IP addresses which might change on reboot of the host or restart of the container service.

### What is the expected output?
Diesel just asking the OS to resolve the name.

### What is the actual output?
Diesel not able to resolve a name perfectly fine to resolve.
```
Dec 28 01:04:22 vaultwarden vaultwarden[1132]: [2022-12-28 01:04:22.611][vaultwarden::util][WARN] Can't connect to database, retrying: DieselCon.
Dec 28 01:04:22 vaultwarden vaultwarden[1132]: [CAUSE] BadConnection(
Dec 28 01:04:22 vaultwarden vaultwarden[1132]:     "Unknown server host 'db' (-3)",
Dec 28 01:04:22 vaultwarden vaultwarden[1132]: )
```
### Are you seeing any additional errors?
No.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case) **Haha, very funny. I'm no developer.** Please check if there are any constraints on name resolution in your code, e.g. "if it's no FQDN then refuse to resolve or something like that."
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for opening this bug report. Diesel itself does not perform the network calls in question. These are performed by `libmysqlclient`. As of this I do not consider this as an issue in diesel.
