### ISSUE TITLE
Questions: Composite data types and foreign keys

### ISSUE THREAD

**Issue by flying-sheep** [diesel-rs/diesel#347]
Hi, I’m confused how things play together.

I have a `Record` struct with some fields and want to insert those fields’ values into an `assigned_records` table together with to some group key.

is it possible to do this or do i need to create a relation table:

```sql
CREATE TABLE assigned_records (
	id INTEGER PRIMARY KEY,
	record_id INTEGER REFERENCES records (id),
	group_id INTEGER REFERENCES groups (id)
)
```

---

How do foreign keys in general work? do i get their relations represented in rust somehow or are they simply u32 fields and can be used in joins?

**Comment by sgrif** [comment]
They're simply i32 fields, treated like any other field. We don't take indexes into account.
