### ISSUE TITLE
diesel_cli: `diesel database reset` does not escape database name

### ISSUE THREAD

**Issue by dikaiosune** [diesel-rs/diesel#350]
I have an ill-advised database name in use on my laptop with a dash in the name. Issue:

```
$ diesel database reset
Dropping database: name-withdash
ERROR:  syntax error at or near "-"
LINE 1: DROP DATABASE IF EXISTS name-withdash
                                    ^
```

I tried putting together a PR to escape the name, but the diesel_cli tests are aborting for me before I make any changes (panic in a panic). I'll take another run at it later when I have some time on a different machine.

**Comment by mcasper** [comment]
😲
