### ISSUE TITLE
#[changeset_for(table_name)] only implements save_changes if there is a field called id on the struct

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#354]
The documentation states that `save_changes` is implemented if the struct contains a field called like the primary key:

> If the struct has a field for the primary key, an additional function, save_changes<T: Queryable<..>>(&self, connection: &Connection) -> QueryResult<T>, will be added to the model. This will persist any changes made, and return the resulting record. It is intended to be a shorthand for filtering by the primary key.

[Codegen](https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/src/model.rs#L41) implements `save_changes` only if there is a field called `id`.  Either we should fix the documentation or we add support for custom primary keys here.

**Comment by sgrif** [comment]
This is fixed in 0.7
