### ISSUE TITLE
How to use Postgresql's date and bytea column type?

### ISSUE THREAD

**Issue by Matrix-Zhang** [diesel-rs/diesel#355]
follow the started-guide, i want to add a post create date column with date type and a picture with bytea type, but i don't know how to do this, any sample please... 3ks

**Comment by Matrix-Zhang** [comment]
any one can help me? right now, i can quey the record with the PgTimestamp type, 
```
#[derive(Queryable, Debug, Clone)]
pub struct DevicePeriod {
    pub id: i32,
    pub device_id: i32,
    pub date_time: PgTimestamp,
    pub confirmed: bool
}
```

but how to write the insertable ? 
```
#[insertable_into(device_period)]
pub struct NewDevicePeriod<'a> {
    pub device_id: i32,
    pub date_time: NaiveDateTime //here, will build error, change to PgTimestamp is ok, but the chrono timestamp is since 1970
}
```

**Comment by Matrix-Zhang** [comment]
i found the pg types sources have to_sql for NaiveDateTime, but i don't know how to use it

**Comment by sgrif** [comment]
Hey sorry for the delay in responding. You need to enable the `chrono` feature to deal with dates. PG date will map to `chrono::NaiveDate`. bytea maps to `Vec<u8>`, but you may need to point at master if you're using the `infer_schema!` macro.
