### ISSUE TITLE
Aggregate + non-aggregate expressions not allowed where they should be

### ISSUE THREAD

**Issue by SteelAlloy** [diesel-rs/diesel#3574]
### Versions

- **Rust: 1.66.0**
- **Diesel: 2.0.3**
- **Database: PostgreSQL**
- **Operating System: Linux**

### Feature Flags

- **diesel: ["uuid", "postgres", "r2d2", "numeric", "chrono", "serde_json"]**

## Problem Description

The following query gives some errors, mixing aggregate and non-aggregate expressions
```rust
diesel::table! {
    foo (uuid, date) {
        uuid -> Uuid,
        date -> Date,
    }
}

foo::table
        .select((foo::uuid, diesel::dsl::max(foo::date)))
        .group_by(foo::uuid)
```

### What are you trying to accomplish?

I'm trying to translate this valid SQL query to diesel dsl

```sql
CREATE TABLE foo (
    uuid uuid PRIMARY KEY NOT NULL,
    date timestamp DEFAULT now() NOT NULL
);

SELECT uuid, max(date) date FROM foo GROUP BY uuid;
```

### What is the expected output?

Being able to mix such expressions when it's valid sql

### What is the actual output?

```
error[E0277]: the trait bound `diesel::expression::is_aggregate::No: MixedAggregates<diesel::expression::is_aggregate::Yes>` is not satisfied
   --> src/graphql/entities/user.rs:392:10
    |
392 |         .select((foo::uuid_1, diesel::dsl::max(foo::date)))
    |          ^^^^^^ the trait `MixedAggregates<diesel::expression::is_aggregate::Yes>` is not implemented for `diesel::expression::is_aggregate::No`
    |
    = help: the following other types implement trait `MixedAggregates<Other>`:
              <diesel::expression::is_aggregate::No as MixedAggregates<diesel::expression::is_aggregate::Never>>
              <diesel::expression::is_aggregate::No as MixedAggregates<diesel::expression::is_aggregate::No>>
    = note: required for `(db::schema::foo::columns::uuid_1, diesel::expression::functions::aggregate_ordering::max::max<diesel::sql_types::Date, db::schema::foo::columns::date>)` to implement `ValidGrouping<()>`
    = note: required for `SelectStatement<FromClause<db::schema::foo::table>>` to implement `SelectDsl<(db::schema::foo::columns::uuid_1, diesel::expression::functions::aggregate_ordering::max::max<diesel::sql_types::Date, db::schema::foo::columns::date>)>`
```

### Are you seeing any additional errors?

No, many thanks for your hard work

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.

If you are unsure if your issue is a duplicate of an existing issue please link the issue in question here

- https://github.com/diesel-rs/diesel/issues/1586

- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
This is "expected" as we assume that the call to the `group_by` function appears before the `select` call. This assumption is made to have somewhat clearer error messages here (so that they point at least to the `.select()` call instead of only pointing at the query). So for reference the following query compiles:

```rust
foo::table
        .group_by(foo::uuid)
        .select((foo::uuid, diesel::dsl::max(foo::date)))
```

That written: I just checked the documentation and it does not mention this restriction at all. We should probably have that in the documentation of `.select` and `.group_by`. So that's at least a missing/bad documentation bug.

**Comment by oganexon** [comment]
Thanks, it does indeed work better in this order
I can add this to the documentation if I have time

**Comment by wowinter13** [comment]
@weiznich I'll check and update docs
