### ISSUE TITLE
(slightly) more readable migration filenames?

### ISSUE THREAD

**Issue by davidszotten** [diesel-rs/diesel#358]
What would you think about inserting an underscore between the date and time in the generated migration filenames? 

for the odd occasion when typing (tab completing) in a terminal, i found it hard to scan the list of migrations to figure out which number to add to disambiguate and continue tab completing:

```
$ rm migrations/2016061<TAB>
20160612132127_add_foo/      20160614173422_add_bar/       20160615123204_add_baz/
20160614153823_add_quu/      20160615122959_add_quux/
```

vs something like?

```
20160612_132127_add_foo/      20160614_173422_add_bar/       20160615_123204_add_baz/
20160614_153823_add_quu/      20160615_122959_add_quux/
```

**Comment by killercup** [comment]
I'm pretty sure you can write it like `20160612-132127_add_foo` or even `2016-06-12T13-21-27_add_foo`. The 'version' is determined by the filename part before the first `_`.

- - -

Browsing through the migration code, it looks like for all entries in the `migrations/` directory, [`migration_from(path)`](https://github.com/diesel-rs/diesel/blob/f0a75bbcb56e2764da6ec5fd12dd950726b837d4/diesel/src/migrations/migration.rs#L12) is called, which tries to build a tuple struct with `(path, version)`, where the 'version' is determined by [`version_from(path)`](https://github.com/diesel-rs/diesel/blob/f0a75bbcb56e2764da6ec5fd12dd950726b837d4/diesel/src/migrations/migration.rs#L36). This is where it gets interesting: It just splits the string at the first `_` and returns the first part:

```rust
.split("_")
.nth(0)
```

**Comment by davidszotten** [comment]
the dates are prepended by the cli when calling e.g. `diesel migration generate foo`. 

indeed, as you've discovered, internally diesel seems to only use the first part:
```
table __diesel_schema_migrations
+----------------+----------------------------+
|        version | run_on                     |
|----------------+----------------------------|
| 20160612132127 | 2016-06-15 11:38:36.130818 |
| 20160614153823 | 2016-06-15 11:38:36.130818 |
| 20160614173422 | 2016-06-15 11:38:36.130818 |
| 20160615122959 | 2016-06-15 11:38:36.130818 |
| 20160615123204 | 2016-06-15 11:38:36.130818 |
+----------------+----------------------------+
SELECT 5
Time: 0.002s
```

hence this issue

**Comment by killercup** [comment]
Ah, got it. So you basically want to change the generate output, not the underlying migration organisation stuff.

**Comment by davidszotten** [comment]
yes, though having the identifiers in the migrations table also separated with an underscore might also be helpful i guess

**Comment by sgrif** [comment]
I'm fine with improving the readability of these. I like @killercup's suggestion of using dashes instead of underscores. I'd like to continue to keep the rules of "what is the version" simple (and right now that rule is anything before the first underscore)

**Comment by Eijebong** [comment]
This can be close now that #827 has been merged :)
