### ISSUE TITLE
r2d2::Error vs diesel::r2d2::Error -- REGRESSION

### ISSUE THREAD

**Issue by lermana** [diesel-rs/diesel#3615]
### Versions

- **Rust:** `rustc 1.65.0 (897e37553 2022-11-02)`
- **Diesel:** `diesel = { version = "2", features = ["chrono", "postgres", "r2d2", "serde_json"] }`
     - `r2d2 = "0.8.10"`

- **Database:** `PostgreSQL 15.2`
- **Operating System** `MacOS Monterey 12.6` 

## Problem Description

In trying to propagate errors from a DB-interaction function up through a (blocking) closure in a (`actix`) HTTP handler, I had to manually import and implement `r2d2::Error` directly, as opposed to `diesel::r2d2 ...` e.g.
```
use r2d2;

...

impl From<r2d2::Error> for HandledDbError {
    fn from(e: r2d2::Error) -> Self {
        Self::DB_POOL_ERROR(e)
    }
}
```

Came across what looks to be the same problem in a prior issue, and comment there said to open a new one if this was encountered: https://github.com/diesel-rs/diesel/issues/1919

**Comment by weiznich** [comment]
Thats not a regression. The reexport as [`diesel::r2d2::PoolError`](https://docs.diesel.rs/2.0.x/diesel/r2d2/type.PoolError.html) exists on the version named in the report.

Closed as this works as designed.
