### ISSUE TITLE
Add support for Uuid to SQLite

### ISSUE THREAD

**Issue by flosse** [diesel-rs/diesel#364]
It would be nice to be able to use `uuid::Uuid` within the structs in combination of SQLite!

**Comment by sgrif** [comment]
As far as I'm aware there is no data type in SQLite that maps to UUID?

**Comment by flosse** [comment]
> As far as I'm aware there is no data type in SQLite that maps to UUID?

I'm sorry. You're totally right!

**Comment by theduke** [comment]
There is no UUID type in sqLite, but you could just store the UUID as a `BYTE` (or `TEXT`).

Automatic serializaton here would be a very welcome feature.

**Comment by theduke** [comment]
No there is not, but the UUID could just be (de)serialized to  `BINARY` or `TEXT`, which would be much nicer than having to convert manually. @sgrif

**Comment by 0xcaff** [comment]
I've implemented storing UUIDs in SQLite using `BINARY(128)` using a wrapper type in my package.

Code:
https://github.com/forte-music/core/blob/fc9cd6217708b0dd6ae684df3a53276804479c59/src/models/id.rs#L67-L121

SQL:
https://github.com/forte-music/core/blob/feature/sync-engine/migrations/2018-05-14-200933_setup/up.sql#L1-L12

Usage:
https://github.com/forte-music/core/blob/fc9cd6217708b0dd6ae684df3a53276804479c59/src/models/album.rs#L10-L21

I can make a pull request with an adaptation of this code if anyone is interested.

**Comment by sameer** [comment]
I'm interested @0xcaff, would appreciate it if you have the time to do a PR for this.

**Comment by 0xcaff** [comment]
I’d like thoughts from a contributor before making a PR. Thoughts @sgrif?

**Comment by weiznich** [comment]
Our policy for including mappings between certain SQL types an rust types is like following:
* Either a rust type is able to represent all possible values of the matched SQL type and  also the SQL type could represent all values of the rust type
* Or the type is a fundamental type like boolean.
The first condition is not fulfilled because there at `Text` and also `Binary` values that are no valid uuid's (for example all shorter or longer values)
In my opinion also the second point is not fulfilled because uuid is not that fundamental like for example booleans. (If anyone from @diesel/core disagrees, pleas response here :wink:)

Given that (and given that it is quite easy to write a new type wrapper for this outside of diesel) I would say that impl should not be part of diesel itself.

**Comment by 0xcaff** [comment]
Playing devils advocate here.

I'd argue that uuid is a fundamental type. Many applications use the `uuid` create and diesel already has support for using it with some SQL dialects (postgres). It's a useful thing to have around built, tested and discover-able for users of the library. Writing a new type wrapper is annoying because of the need for boilerplate type conversion code.

Also, `chrono::NaiveDate` violates these rules. It is serialized as `TEXT` for SQLite. https://github.com/diesel-rs/diesel/blob/85e0007684d7547379d1fa69de5146b04695bc19/diesel/src/sql_types/mod.rs#L267-L282

**Comment by weiznich** [comment]
In my opinion `NaiveDate` (and similar types) falls in the same category like booleans. They are fundamental in such a way that it is not possible to write larger application without using them. So not supporting the is not an option.
On the other hand it is possible to write large application without using uuid's, because for nearly all use cases using a 64 bit identifier should be enough.

**Comment by sgrif** [comment]
We also support it because SQLite does have a ton of built-in functions for dealing with dates. Yes, it represents them as strings, but that's ultimately an implementation detail, not something relevant to whether the type exists or not. Importantly, there is a *canonical* way to represent a date in SQLite. 

That is not the true of UUIDs. We could store the raw bytes, or we could store the text representation. It's not obvious which we should choose, and we would be incompatible with existing databases when we choose one or the other.

Ultimately when there's a clear representation of a type and semantically it exists for a given backend, we support it even if there's some mismatch. For example, even PG's datetime type supports a different range of dates than chrono. Given that SQLite is fully dynamically typed, if we really wanted to only support what strictly could be represented, the *only* type that we could support for SQLite is `Vec<u8>`. We do have to draw the line somewhere though, and this is where we've chosen to draw it for the time being.

**Comment by MightyPork** [comment]
Here is an updated version of the code shared by @0xcaff , as I couldn't get the original to work anymore.
Really wish this was part of the crate, so we wouldn't have to use the wrapper. But, it works.

The "uuid" feature really should be called "postgres-uuid", took me a while to figure out it isn't implemented for sqlite

```rust
use uuid;
use std::io::prelude::*;
use diesel::deserialize::{self, FromSql};
use diesel::serialize::{self, IsNull, Output, ToSql};
use diesel::sql_types::{Binary};
use diesel::sqlite::Sqlite;
use diesel::backend::Backend;
use std::fmt::{Display, Formatter};
use std::fmt;

#[derive(Debug, Clone, Copy, FromSqlRow, AsExpression, Hash, Eq, PartialEq)]
#[sql_type = "Binary"]
pub struct UUID(pub uuid::Uuid);

impl UUID {
    pub fn random() -> Self {
        Self(uuid::Uuid::new_v4())
    }
}

impl From<UUID> for uuid::Uuid {
    fn from(s: UUID) -> Self {
        s.0
    }
}

impl Display for UUID {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromSql<Binary, Sqlite> for UUID {
    fn from_sql(bytes: Option<&<Sqlite as Backend>::RawValue>) -> deserialize::Result<Self> {
        let bytes = not_none!(bytes);
        uuid::Uuid::from_slice(bytes.read_blob()).map(UUID).map_err(|e| e.into())
    }
}

impl ToSql<Binary, Sqlite> for UUID {
    fn to_sql<W: Write>(&self, out: &mut Output<W, Sqlite>) -> serialize::Result {
        out.write_all(self.0.as_bytes())
            .map(|_| IsNull::No)
            .map_err(Into::into)
    }
}
```

**Comment by GTB3NW** [comment]
+1 for rename of the feature. I've spent about an hour looking into this only to find out the type is only compat with PG. Using rusqlite allows for UUID usage as BLOB format, it would be really nice to see, but if it violates your standards then :(

**Comment by w4** [comment]
Following on from @MightyPork's code, you can make the backend generic for all database types supporting the `Binary` type:

```
impl<B: diesel::backend::Backend> diesel::deserialize::FromSql<Binary, B> for UUID
where
    Vec<u8>: diesel::deserialize::FromSql<Binary, B>
{
    fn from_sql(bytes: Option<&B::RawValue>) -> diesel::deserialize::Result<Self> {
        let value = <Vec<u8>>::from_sql(bytes)?;
        uuid::Uuid::from_slice(&value).map(UUID).map_err(|e| e.into())
    }
}

impl<B: diesel::backend::Backend> diesel::serialize::ToSql<Binary, B> for UUID
where
    [u8]: diesel::serialize::ToSql<Binary, B>
{
    fn to_sql<W: Write>(&self, out: &mut diesel::serialize::Output<W, B>) -> diesel::serialize::Result {
        out.write_all(self.0.as_bytes())
            .map(|_| diesel::serialize::IsNull::No)
            .map_err(Into::into)
    }
}
```

**Comment by teschmitt** [comment]
Based on [w4](#issuecomment-922156645)'s and [MightyPork](#issuecomment-797119628)'s solutions (which seem to require diesel v1.x), [I adapted their UUID module for diesel v2.1.5](https://gist.github.com/teschmitt/e8526a2823d2e436b8c9aa70d6247751):

```rust
use diesel::{
    backend::Backend,
    deserialize::{self, FromSql},
    serialize::{self, Output, ToSql},
    sql_types::Binary,
    AsExpression, FromSqlRow,
};
use std::fmt::{self, Display, Formatter};
use uuid;

#[derive(Debug, Default, Clone, Copy, FromSqlRow, AsExpression, Hash, Eq, PartialEq)]
#[diesel(sql_type = Binary)]
pub struct UUID(pub uuid::Uuid);

impl UUID {
    pub fn new_v4() -> Self {
        Self(uuid::Uuid::new_v4())
    }
}

impl From<UUID> for uuid::Uuid {
    fn from(s: UUID) -> Self {
        s.0
    }
}

impl From<uuid::Uuid> for UUID {
    fn from(s: uuid::Uuid) -> Self {
        UUID(s)
    }
}

impl Display for UUID {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl<B: Backend> FromSql<Binary, B> for UUID
where
    Vec<u8>: FromSql<Binary, B>,
{
    fn from_sql(bytes: <B as Backend>::RawValue<'_>) -> deserialize::Result<Self> {
        let value = <Vec<u8>>::from_sql(bytes)?;
        uuid::Uuid::from_slice(&value)
            .map(UUID)
            .map_err(|e| e.into())
    }
}

impl<B: Backend> ToSql<Binary, B> for UUID
where
    [u8]: ToSql<Binary, B>,
{
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, B>) -> serialize::Result {
        self.0.as_bytes().to_sql(out)
    }
}
```

This has worked for me in a small SQLite-based project.

**Comment by adam-53-r** [comment]
> Based on [w4](#issuecomment-922156645)'s and [MightyPork](#issuecomment-797119628)'s solutions (which seem to require diesel v1.x), [I adapted their UUID module for diesel v2.1.5](https://gist.github.com/teschmitt/e8526a2823d2e436b8c9aa70d6247751):
> 
> ```rust
> use diesel::{
>     backend::Backend,
>     deserialize::{self, FromSql},
>     serialize::{self, Output, ToSql},
>     sql_types::Binary,
>     AsExpression, FromSqlRow,
> };
> use std::fmt::{self, Display, Formatter};
> use uuid;
> 
> #[derive(Debug, Default, Clone, Copy, FromSqlRow, AsExpression, Hash, Eq, PartialEq)]
> #[diesel(sql_type = Binary)]
> pub struct UUID(pub uuid::Uuid);
> 
> impl UUID {
>     pub fn new_v4() -> Self {
>         Self(uuid::Uuid::new_v4())
>     }
> }
> 
> impl From<UUID> for uuid::Uuid {
>     fn from(s: UUID) -> Self {
>         s.0
>     }
> }
> 
> impl From<uuid::Uuid> for UUID {
>     fn from(s: uuid::Uuid) -> Self {
>         UUID(s)
>     }
> }
> 
> impl Display for UUID {
>     fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
>         write!(f, "{}", self.0)
>     }
> }
> 
> impl<B: Backend> FromSql<Binary, B> for UUID
> where
>     Vec<u8>: FromSql<Binary, B>,
> {
>     fn from_sql(bytes: <B as Backend>::RawValue<'_>) -> deserialize::Result<Self> {
>         let value = <Vec<u8>>::from_sql(bytes)?;
>         uuid::Uuid::from_slice(&value)
>             .map(UUID)
>             .map_err(|e| e.into())
>     }
> }
> 
> impl<B: Backend> ToSql<Binary, B> for UUID
> where
>     [u8]: ToSql<Binary, B>,
> {
>     fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, B>) -> serialize::Result {
>         self.0.as_bytes().to_sql(out)
>     }
> }
> ```
> 
> This has worked for me in a small SQLite-based project.

Could it be possible to save it in Text instead of Binary?

**Comment by teschmitt** [comment]
> Could it be possible to save it in Text instead of Binary?

Saving it as text is the default behavior which you get when you declare the field as `uuid_text` in the migration:

```sql
create table posts
(
    id uuid_text not null primary key,
    text text not null,
);
```
Then you just need to remember to always convert to and from String when writing and reading from the DB. If you want to map it transparently, I suppose you could do it analog to the implementation above:

Replace `Binary` with `Text` and fiddle around with the `to_sql()` and `from_sql()` methods:

```rust
// ...

#[diesel(sql_type = Binary)]
pub struct UUID(pub uuid::Uuid);

// ...

impl<B: Backend> FromSql<Text, B> for UUID
where
    String: FromSql<Text, B>,
{
    fn from_sql(bytes: <B as Backend>::RawValue<'_>) -> deserialize::Result<Self> {
        let value = String::from_sql(bytes)?;
        uuid!(value).map(UUID).map_err(|e| e.into())
    }
}

impl<B: Backend> ToSql<Binary, B> for UUID
where
    str: ToSql<Text, B>,
{
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, B>) -> serialize::Result {
        self.0.to_string().to_sql(out)
    }
}
```

I haven't tested this so you might have to put some more work into the methods, but that would be the rough idea.

**Comment by adam-53-r** [comment]
> ```rust
> impl<B: Backend> ToSql<Binary, B> for UUID
> where
>     str: ToSql<Text, B>,
> {
>     fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, B>) -> serialize::Result {
>         self.0.to_string().to_sql(out)
>     }
> }
> ```
It would'nt let me do this because of str needing lifetime annotations or something like that (sorry I'm pretty new).

Eventually I saw [this](https://docs.diesel.rs/master/diesel/serialize/trait.ToSql.html#examples) in the documentation and ended up with this implementation that works fine:
```rust
// ...

impl<B: Backend> FromSql<Text, B> for UUID
where
    String: FromSql<Text, B>,
{
    fn from_sql(bytes: <B as Backend>::RawValue<'_>) -> deserialize::Result<Self> {
        let value = String::from_sql(bytes)?;
        uuid::Uuid::from_str(&value.as_str())
            .map(UUID)
            .map_err(|e| e.into())
    }
}

impl ToSql<Text, Sqlite> for UUID
where
    String: ToSql<Text, Sqlite>,
{
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, Sqlite>) -> serialize::Result {
        out.set_value(self.0.as_hyphenated().to_string());
        Ok(IsNull::No)
    }
}
```

Thank you very much for your help @teschmitt

**Comment by RedIODev** [comment]
> Based on [w4](#issuecomment-922156645)'s and [MightyPork](#issuecomment-797119628)'s solutions (which seem to require diesel v1.x), [I adapted their UUID module for diesel v2.1.5](https://gist.github.com/teschmitt/e8526a2823d2e436b8c9aa70d6247751):
> 
> use diesel::{
>     backend::Backend,
>     deserialize::{self, FromSql},
>     serialize::{self, Output, ToSql},
>     sql_types::Binary,
>     AsExpression, FromSqlRow,
> };
> use std::fmt::{self, Display, Formatter};
> use uuid;
> 
> #[derive(Debug, Default, Clone, Copy, FromSqlRow, AsExpression, Hash, Eq, PartialEq)]
> #[diesel(sql_type = Binary)]
> pub struct UUID(pub uuid::Uuid);
> 
> impl UUID {
>     pub fn new_v4() -> Self {
>         Self(uuid::Uuid::new_v4())
>     }
> }
> 
> impl From<UUID> for uuid::Uuid {
>     fn from(s: UUID) -> Self {
>         s.0
>     }
> }
> 
> impl From<uuid::Uuid> for UUID {
>     fn from(s: uuid::Uuid) -> Self {
>         UUID(s)
>     }
> }
> 
> impl Display for UUID {
>     fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
>         write!(f, "{}", self.0)
>     }
> }
> 
> impl<B: Backend> FromSql<Binary, B> for UUID
> where
>     Vec<u8>: FromSql<Binary, B>,
> {
>     fn from_sql(bytes: <B as Backend>::RawValue<'_>) -> deserialize::Result<Self> {
>         let value = <Vec<u8>>::from_sql(bytes)?;
>         uuid::Uuid::from_slice(&value)
>             .map(UUID)
>             .map_err(|e| e.into())
>     }
> }
> 
> impl<B: Backend> ToSql<Binary, B> for UUID
> where
>     [u8]: ToSql<Binary, B>,
> {
>     fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, B>) -> serialize::Result {
>         self.0.as_bytes().to_sql(out)
>     }
> }
> 
> This has worked for me in a small SQLite-based project.

I use this version but have trouble using it with nullable UUIDs. I have the following code:
```rust
#[derive(Debug, Queryable, Selectable)]
#[diesel(table_name = super::schema::account)]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
pub struct Account {
    #[diesel(deserialize_as = UUID)]
    id: Uuid,
    name: String,
    desc: Option<String>,
    type_: Option<String>,
    #[diesel(deserialize_as = Option<UUID>)]
    parent_id: Option<Uuid>,
    read_only: Option<i32>,
    #[diesel(deserialize_as = Option<UUID>)]
    password: Option<Uuid>,
    #[diesel(deserialize_as = Option<UUID>)]
    prefix: Option<Uuid>,
}
```
and get the following error:
```
error[E0277]: the trait bound `std::option::Option<Uuid>: TryFrom<std::option::Option<UUID>>` is not satisfied
 --> src/db/models.rs:8:17
  |
8 | #[derive(Debug, Queryable, Selectable)]
  |                 ^^^^^^^^^ the trait `From<std::option::Option<UUID>>` is not implemented for `std::option::Option<Uuid>`, which is required by `std::option::Option<UUID>: TryInto<_>`
  |
  = help: the following other types implement trait `From<T>`:
            <std::option::Option<&'a T> as From<&'a std::option::Option<T>>>
            <std::option::Option<&'a mut T> as From<&'a mut std::option::Option<T>>>
            <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing::span::EnteredSpan>>
            <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing::span::Span>>
            <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing_core::span::Current>>
            <std::option::Option<&'static tracing_core::metadata::Metadata<'static>> as From<&'a tracing_core::span::Current>>
            <std::option::Option<Box<(dyn QueryFragment<DB> + Send + 'a)>> as From<diesel::query_builder::order_clause::NoOrderClause>>
            <std::option::Option<Box<(dyn QueryFragment<DB> + Send + 'a)>> as From<diesel::query_builder::order_clause::OrderClause<Expr>>>
          and 8 others
  = note: required for `std::option::Option<UUID>` to implement `Into<std::option::Option<Uuid>>`
  = note: required for `std::option::Option<Uuid>` to implement `TryFrom<std::option::Option<UUID>>`
  = note: required for `std::option::Option<UUID>` to implement `TryInto<std::option::Option<Uuid>>`
  = note: this error originates in the derive macro `Queryable` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I understand what the compiler is asking for, but I can't do what he is asking as I can't implement From<Option<UUID>> for Option<Uuid> due to orphan rule.
I think it's kinda strange that this is not a blanket implementation of Option.
```rust
impl<T, U> From<Option<T>> for Option<U> 
where U: From<T> {...}  
```
would be easy to implement.
Or am I using the deserialize_as macro wrong and there is a way to do this?

**Comment by weiznich** [comment]
Old closed issues are not the right place to ask support question. Please fill a new discussion thread including all relevant details (== minimal reproducible example of your problem) if you have questions about something. 

I'm going to lock this issue now, given the history of people posting semi-related questions here.
