### ISSUE TITLE
breaking change from 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by ahl** [diesel-rs/diesel#3659]
## Problem Description

We have some code that looks a little like this:

```rust
pub struct Test<DB>(PhantomData<DB>)
where
    DB: Backend<BindCollector = RawBytesBindCollector<DB>>;
```

That was fine under 2.0.4, but fails to compile under 2.1.0.

### What are you trying to accomplish?

Upgrading to 2.1.0

### What is the expected output?

Compilation success.

### What is the actual output?

```
error[E0107]: missing generics for associated type `diesel::backend::Backend::BindCollector`
   --> src/lib.rs:7:17
    |
7   |     DB: Backend<BindCollector = RawBytesBindCollector<DB>>;
    |                 ^^^^^^^^^^^^^ expected 1 lifetime argument
    |
note: associated type defined here, with 1 lifetime parameter: `'a`
   --> /Users/ahl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.1.0/src/backend.rs:112:10
    |
112 |     type BindCollector<'a>: crate::query_builder::bind_collector::BindCollector<'a, Self> + 'a;
    |          ^^^^^^^^^^^^^ --
help: add missing lifetime argument
    |
7   |     DB: Backend<BindCollector<'a> = RawBytesBindCollector<DB>>;
    |                              ++++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `with-210` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

### Are you seeing any additional errors?

No

### Steps to reproduce

See https://github.com/ahl/diesel-issue-repro

```console
$ (cd with-204; cargo build)
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
$ (cd with-210; cargo build)
   Compiling with-210 v0.1.0 (/Users/ahl/src/diesel-issue-repro/with-210)
error[E0107]: missing generics for associated type `diesel::backend::Backend::BindCollector`
   --> src/lib.rs:7:17
    |
7   |     DB: Backend<BindCollector = RawBytesBindCollector<DB>>;
    |                 ^^^^^^^^^^^^^ expected 1 lifetime argument
    |
note: associated type defined here, with 1 lifetime parameter: `'a`
   --> /Users/ahl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.1.0/src/backend.rs:112:10
    |
112 |     type BindCollector<'a>: crate::query_builder::bind_collector::BindCollector<'a, Self> + 'a;
    |          ^^^^^^^^^^^^^ --
help: add missing lifetime argument
    |
7   |     DB: Backend<BindCollector<'a> = RawBytesBindCollector<DB>>;
    |                              ++++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `with-210` (lib) due to previous error
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for filling this bug report. I'm currently on vacation, so just a short answer here: The `BindCollector` type was part of a [trait marked as explicitly not part of the stable API](https://docs.diesel.rs/2.0.x/diesel/backend/trait.HasBindCollector.html) of diesel 2.0. That reserved us the right to change that type in a future release, which is what happened with diesel 2.1. Now the good news is that with diesel 2.1 this [associated type was moved to a trait](https://docs.diesel.rs/2.1.x/diesel/backend/trait.Backend.html) that's part of the stable API.

**Comment by weiznich** [comment]
So I'm back from my holidays and I've double checked that again:

The relevant associated type is not part of the API documentation if `diesel` is build without the `i-implement-a-third-party-backend-and-opt-into-breaking-changes` feature flag: https://docs.rs/diesel/2.0.4/diesel/backend/trait.Backend.html (note the private `HasBindCollector` trait there). This means that the associated type was not part of the public diesel API, which in turn means that this is not considered to be a breaking change. 

That written: It's a bit unfortunate that you could access that without enabling the corresponding feature flag :(
