### ISSUE TITLE
diesel migrations labels migrations with wrong datetime

### ISSUE THREAD

**Issue by nklskyoy** [diesel-rs/diesel#3664]
## Setup

```
[dependencies]
diesel = "2.1.0"
diesel_migrations = "2.1.0"
rusqlite = "0.29.0"
```

### Versions

- **Rust:** rustc 1.70.0
- **Diesel:** 2.1.0
- **Database:**
- **Operating System** mac

### Feature Flags

- **diesel:**
- **diesel cli**

## Problem Description

when hitting `diesel migration generate lab` at 15:43 PM, the directory `2023-06-21-134310_lab` is generated. I assume that the timezone is wrong? exactly 2hrs before the generation time.
I am in Amsterdam tz.

Thanks guys

**Comment by czotomo** [comment]
It's not a bug, the time is in UTC timezone. You can override this by generating the time string yourself and providing it to the cli command via the `migration_version` argument.
