### ISSUE TITLE
ERROR: `relation "user" does not exist` while running `diesel migration/print-schema`

### ISSUE THREAD

**Issue by df51d** [diesel-rs/diesel#3673]
## Setup
[My pg dump](https://gist.github.com/df51d/51e5ae9b2bb52ca40014f2235a7e8c55#file-pg_dump-sql)
### Versions

- **Rust:**
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
rustc 1.70.0 (90c541806 2023-05-31)
- **Diesel:**
diesel 2.1.0
- **Database:**
postgresql 15.3-1.pgdg120+1
- **Operating System**
ArcoLinux kernel 6.3.8-arch1-1
### Feature Flags
```
cargo install diesel_cli --no-
default-features --features "postgres sqlite"
```
## Problem Description
I encountered an error while running `diesel print-schema`/`diesel migration run` on my old database after installing the diesel-cli. I was attempting to switch from a TypeScript project that utilized Prisma as the database driver to a Rust project with Diesel as the database driver. Since starting from scratch and recreating everything would be a significant amount of work, my intention was to reuse my existing database. However, I faced difficulties during the process. 
### What are you trying to accomplish?
```diesel print-schema```
### What is the actual output?
```relation "user" does not exist```
#### with prisma installed
```bash
docker pull postgres

docker run -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres

echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/db"' > .env

prisma init

echo 'model User {\n\tid Int @id @default(autoincrement())\n}' >> prisma/schema.prisma

prisma db push

diesel print-schema
```
#### without prisma installed
```bash
docker pull postgres

docker run -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres

echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/db"' > .env

diesel setup

mkdir migrations/user

echo "CREATE TABLE public.\"User\" (
    id integer NOT NULL
);
ALTER TABLE public.\"User\" OWNER TO postgres;
CREATE SEQUENCE public.\"User_id_seq\"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.\"User_id_seq\" OWNER TO postgres;
ALTER SEQUENCE public.\"User_id_seq\" OWNED BY public.\"User\".id;
ALTER TABLE ONLY public.\"User\" ALTER COLUMN id SET DEFAULT nextval('public.\"User_id_seq\"'::regclass);
SELECT pg_catalog.setval('public.\"User_id_seq\"', 1, false);
ALTER TABLE ONLY public.\"User\"
    ADD CONSTRAINT \"User_pkey\" PRIMARY KEY (id);" > migrations/user/up.sql
    
diesel migration run
```
### Temporary fix:
Making all tables lowercase seems to fix the problem:
#### working migration
```sql
--- this works just fine /migrations/user/up.sql
CREATE TABLE public."user" (
    id integer NOT NULL
);
ALTER TABLE public."user" OWNER TO postgres;
CREATE SEQUENCE public."user_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public."user_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."user_id_seq" OWNED BY public."user".id;
ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public."user_id_seq"'::regclass);
SELECT pg_catalog.setval('public."user_id_seq"', 1, false);
ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY (id);
```
#### working prisma 
```prisma
model user {
  id Int @id @default(autoincrement())
}
```
## Checklist
- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
@dsp I plan to do a patch release for this as soon as a couple of other issues are fixed as well. This includes https://github.com/diesel-rs/diesel/issues/3579 and https://github.com/diesel-rs/diesel/pull/3643. I cannot comment on how long that takes because it really depends on how much contributions there are and how much time I personally find to work on that kind of stuff. Any help there would be great.
