### ISSUE TITLE
Raw Identifiers For Column Names Apparently Not Working

### ISSUE THREAD

**Issue by Folling** [diesel-rs/diesel#3709]
### Versions

- **Rust:** 1.71.0-stable
- **Diesel:** 2.1.0
- **Database:** n.a.
- **Operating System** linux

### Feature Flags

- **diesel:** sqlite

## Problem Description

I wish to name a database column `type`, which isn't a reserved keyword in sqlite (and even if it would be, it could be escaped using backticks). Without the `Insertable` implementation this works by the way.

The error occurs in the `InsertableObject::r#type` member:
`message: 'r#type' is not a valid identifier`.
Using column name doesn't work either.
- If I specify `column_name = "type"`, it fails with:
`Expected valid identifier, found 'type'. Diesel automatically renames invalid identifiers, perhaps you meant to write 'type_'?`
- If I specify `column_name = "type_"`, it fails with:
`cannot find type 'type_' in module `objects``
- If I specify `column_name = "r#type", it fails with:
`'r#type' is not a valid identifier`

### Steps to reproduce

```rust

#[repr(i64)]
#[derive(Copy, Clone, Debug, Hash, Ord, PartialOrd, Eq, PartialEq)]
pub enum ObjectType {
    Foo = 1
}

diesel::table!(
    objects {
        id -> BigInt,
        r#type -> BigInt,
        name -> Text,
        information -> Text
    }
);

#[derive(Insertable, PartialEq, Debug)]
#[diesel(table_name = objects)]
pub struct InsertableObject<'a> {
    #[diesel(serialize_as = BigInt)]
    r#type: ObjectType,
    name: &'a str,
    information: &'a str,
}
```

And run

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
This is expected behavior. We decided not to add support for raw identifier in diesel because there were already existing solutions in place when these came up. If you generate your schema from an existing database you will automatically get something like that:

```rust

diesel::table!(
    objects {
        id -> BigInt,
        #[sql_name = "type"]
        type_ -> BigInt,
        name -> Text,
        information -> Text
    }
);
```

That's also what the error message generated by `#[column_name = "type"]` refers to. 

See the [documentation](https://docs.diesel.rs/2.1.x/diesel/macro.table.html) for some more details.
