### ISSUE TITLE
Filter table not applied on `diesel migration --diff-schema`

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#3717]
### Discussed in https://github.com/diesel-rs/diesel/discussions/3712

<div type='discussions-op-text'>

<sup>Originally posted by **forest1102** July 25, 2023</sup>
I am trying out a new option `diff-schema`.  
However, when I use the `filter` field in diesel.toml just omits tables used in other crates. `diesel migration generate edit_column_name --diff-schema` results in writing code to delete tables not listed in the filter fields. I expect migration do nothing about unlisted tables.

# Inputs

initial database info
```sql
CREATE TABLE "table_a"(
	"id" INT4 NOT NULL PRIMARY KEY,
	"code" VARCHAR NOT NULL
);
CREATE TABLE "table_b"(
	"id" INT4 NOT NULL PRIMARY KEY,
);
CREATE TABLE "table_c"(
	"id" INT4 NOT NULL PRIMARY KEY,
);
```

diesel.toml
```  :diesel.toml
[print_schema]



file = "schema_a/src/schema.rs"
filter = { only_tables = [
    "^table_a$",
] }
```

schema_a/src/schema.rs
``` diff
diesel::table! {
    table_a (id) {
        id -> Int8,
-       code -> Varchar,
+      script -> Varchar,
    }
}
```

command
```shell
diesel migration generate edit_column_name --diff-schema
```

## Actual Result

up.sql
```sql
DROP TABLE IF EXISTS "table_b";
ALTER TABLE "table_a" DROP COLUMN "code";
ALTER TABLE "table_a" ADD COLUMN "script" VARCHAR NOT NULL;
DROP TABLE IF EXISTS "table_c";
```

## Expected

up.sql
```sql
ALTER TABLE "table_a" DROP COLUMN "code";
ALTER TABLE "table_a" ADD COLUMN "script" VARCHAR NOT NULL;
```

## Version
```
diesel 
 Version: 2.1.0
 Supported Backends: postgres
```</div>

**Comment by weiznich** [comment]
The issue here is that the `diff-schema` code currently just ignores these filters. That means we need to add support for these filters at the relevant location here:

https://github.com/diesel-rs/diesel/blob/f4d5f93ccfd039702361e3a5a1b832b7be4839b8/diesel_cli/src/migrations/diff_schema.rs#L46

See the `print-schema` code for how to apply the filtering:

https://github.com/diesel-rs/diesel/blob/f4d5f93ccfd039702361e3a5a1b832b7be4839b8/diesel_cli/src/print_schema.rs#L180-L182

A fix of that issue should likely move the definition of the `Filtering` type to a share location like `config.rs`. That this code:

https://github.com/diesel-rs/diesel/blob/f4d5f93ccfd039702361e3a5a1b832b7be4839b8/diesel_cli/src/print_schema.rs#L15-L40

In addition to the actual fix we want to add at least a test case (for example the provided one) like that one here: https://github.com/diesel-rs/diesel/blob/f4d5f93ccfd039702361e3a5a1b832b7be4839b8/diesel_cli/tests/migration_generate.rs#L258-L261

(Also checkout the corresponding folder in `tests/generate_migrations` for the full setup)

**Comment by gmanninglive** [comment]
hey @weiznich I've started working on this, it's going pretty well thanks your guide above!

I have a couple of questions though:
1. Should the cli command `migration` be updated to accept the filters as in `print-schema` command? If yes then, I may have some more questions :smile:
2. Would you like a draft PR up to track progress or would you rather I wait till I believe it's ready for review?
