### ISSUE TITLE
Missing type alias OrderBy for dsl::auto_type

### ISSUE THREAD

**Issue by Elrendio** [diesel-rs/diesel#3736]
### Versions

- **Rust:** rustc --version = rustc 1.70.0 (90c541806 2023-05-31)
- **Diesel:** master
- **Database:** _
- **Operating System** Archlinux

### Feature Flags

- **diesel:** "postgres", "r2d2", "serde_json", "chrono",

## Problem Description
QueryDsl provides an alias for `order` named [`order_by`](https://docs.rs/diesel/latest/diesel/prelude/trait.QueryDsl.html#method.order_by). Therefore type generated using `#[dsl::auto_type]` is `diesel::dsl::OrderBy` which does not exists! I therefore think we should add a type alias `OrderBy` for `Order`.

I see two other alternatives:
1. Deprecate `order_by` on QueryDsl
2. Add documentation on `order_by` to indicate that it doesn't work with `dsl::auto_type` and that one should use `order` in that case.

I can provide a PR once solution has been chosen.

### What are you trying to accomplish?
Use  `#[dsl::auto_type]`

### What is the expected output?
I'd like a simplier solution to use dsl::auto_type

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting. I'm happy to accept a PR that just adds a `type Order = OrderBy` to `diesel::dsl`.
