### ISSUE TITLE
SQLite Getting started/Skeleton app

### ISSUE THREAD

**Issue by stephanbuys** [diesel-rs/diesel#376]
Hi, would it be possible to build a branch of the skeleton app that uses SQLite? It seems like low-hanging fruit for lots of additional people to get going with Diesel as fast as possible. I banged my head on trying to convert the example app to use sqlite for a while but eventually gave up due to problems with the macros, and such.

**Comment by sgrif** [comment]
Yes, it'd be good to have some example apps for both backends (probably after 0.7 releases :soon: :tm:)

**Comment by AndiDog** [comment]
I might just do a simple one, but first I need to resolve this issue:

```
.get_result(conn));
 ^^^^^^^^^^ trait `diesel::sqlite::Sqlite: diesel::backend::SupportsReturningClause` not satisfied
```

Even though it makes sense for an insert statement (since getting inserted rowid is another query), I need a solution for sqlite, e.g. `.exec(conn)` which doesn't get a "return value".

**Comment by killercup** [comment]
@AndiDog IIRC there is an `execute(&connection)` method you could use.

**Comment by rogeruiz** [comment]
I may take a crack at this with my changes to rogeruiz/tick#4 which will be using SQLite. I hope the `easy-for-newcomers` label is the true in my case. 😀

**Comment by Frederick888** [comment]
I'm new to Diesel and still a little confusing with the SQLite. I know that we could use `execute(conn)` to execute the query, but how could I retrieve the created object without `get_result()`?

**Comment by sgrif** [comment]
You'll need to manually do a second query

**Comment by Frederick888** [comment]
@sgrif So what is the equivalent call in Diesel as `sqlite3_last_insert_rowid`?

**Comment by sgrif** [comment]
We don't expose that function, as its value cannot actually be relied on in all contexts. You can approximate its behavior by doing something like `your_table.order(id.desc()).first()`, which makes the caveats of `sqlite3_last_insert_rowid` more explicit and apparent.

**Comment by killercup** [comment]
This can be solved by https://github.com/Phrohdoh/rs-diesel-sqlite/issues/2

**Comment by Eijebong** [comment]
I think this can be closed now.

**Comment by jhessin** [comment]
So, if this issue is closed, where is the example now?

**Comment by weiznich** [comment]
@jhessin Examples for sqlite are [here](https://github.com/diesel-rs/diesel/tree/master/examples/sqlite).
