### ISSUE TITLE
error: expected one of `{`, lifetime, or type, found `:`

### ISSUE THREAD

**Issue by lawchick** [diesel-rs/diesel#3790]
### Versions

- **Rust:** `rustc 1.70.0 (90c541806 2023-05-31)`
- **Diesel:** `diesel 2.1.1`
- **Database:** mysql 
- **Operating System** MacOS Ventura 13.4.1 (M2 Chipset)

### Feature Flags

- **diesel:** mysql, uuid

### What are you trying to accomplish?
I am trying to create a model to correspond with the schema generated from my migrations, following the guide [here](https://diesel.rs/guides/getting-started) but adapting the instructions for Pg to Mysql.

### What is the expected output?
The model should compile. I started with copying and pasting the attributes defined in the Getting Started guide, and then filled in the proper details for my struct according to the generated schema defined in `schema.rs`.

### What is the actual output?

```
error: expected one of `{`, lifetime, or type, found `:`
 --> server/src/database/models.rs:4:21
  |
4 | #[derive(Queryable, Selectable)]
  |                     ^^^^^^^^^^ expected one of `{`, lifetime, or type
  |
  = note: this error originates in the derive macro `Selectable` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Are you seeing any additional errors?
There is a separate but probably related error here:
```
error: proc-macro derive produced unparsable tokens
 --> server/src/database/models.rs:4:21
  |
4 | #[derive(Queryable, Selectable)]
  | 
```

### Steps to reproduce

Relevant source (lines 1-7):
```
use diesel::prelude::*;
use uuid::Uuid;

#[derive(Queryable, Selectable)]
#[diesel(table_name = crate::database::schema::account)]
#[diesel(check_for_backend(diesel::mysql::Mysql))]
pub struct Account<'n0, 'n1> {
// ... struct properties are defined here, aligning with schema.rs
}
```

While I cannot share the migration file, or the schema itself, I can point out that it uses the UUID type in MySQL and aligns that with the `Uuid` struct defined by the `uuid` package.

Segment of cargo.toml
```
[dependencies]
prost = "0.11.9"
tonic = "0.9.2"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tonic-reflection = "0.9.2"
diesel = { version = "2.1.0", features = ["mysql", "uuid"] }
dotenvy = "0.15"
uuid = "1.4.1"

[build-dependencies]
tonic-build = "0.9.2"
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by lawchick** [comment]
This error appears to be resolved when removing the lifetimes `n0` and `n1`.

**Comment by weiznich** [comment]
Thanks for reporting this bug. 

Can you provide the complete definition of the `Account` type, including all fields? That would make it much easier to reproduce the problem.
