### ISSUE TITLE
SQLite + PRAGMA foreign_keys = ON => missing error

### ISSUE THREAD

**Issue by JMLX42** [diesel-rs/diesel#3808]
### Versions

- **Rust:** 1.72.1
- **Diesel:** 2.1.1
- **Database:** SQLite
- **Operating System** Ubuntu 22.04

### Feature Flags

- **diesel:**

```rust
diesel = { version = "2.1.1", features = [
    "sqlite",
    "uuid",
    "r2d2",
    "returning_clauses_for_sqlite_3_35",
] }
```

## Problem Description

When inserting in a table with at foreign key, if the corresponding column has an invalid value (ie a key that does not exist in the foreign table):

- `INSERT` works and `RETURNING` works if and only if `PRAGMA foreign_keys = OFF`
- `INSERT` does not work, returns a value anyway and no error is returned

### What are you trying to accomplish?

`INSERT` in an SQLite table with an inconsistent `FOREIGN KEY` and:

- if `PRAGMA foreign_keys = OFF`, have a proper `RETURNING` value
- if `PRAGMA foreign_keys = ON`, have a foreign key inconsistency error

### What is the expected output?

`insert_into(table).values(values).get_result(conn)` should return an error if any foreign key is inconsistent and `PRAGMA foreign_keys = ON`

### What is the actual output?

`insert_into(table).values(values).get_result(conn)` returns `values` as if the row was actually inserted

So in the code below, `assert!(result.is_ok());` panics. But the `insert_one()...unwrap()` should have panicked even earlier.

### Are you seeing any additional errors?

No.

### Steps to reproduce

```sql
CREATE TABLE buffers (
    id TEXT PRIMARY KEY NOT NULL,
    uri TEXT,
    byte_length INTEGER NOT NULL,
    name TEXT,
    extensions TEXT,
    extras TEXT
);

CREATE TABLE bufferviews (
    id TEXT PRIMARY KEY NOT NULL,
    buffer TEXT NOT NULL,
    byte_offset INTEGER NOT NULL,
    byte_length INTEGER NOT NULL,
    byte_stride INTEGER,
    target INTEGER,
    name TEXT,
    extensions TEXT,
    extras TEXT,
    FOREIGN KEY (buffer) REFERENCES buffers(id)
);
```

```rust
diesel::table! {
    buffers (id) {
        id -> Text,
        uri -> Nullable<Text>,
        byte_length -> Integer,
        name -> Nullable<Text>,
        extensions -> Nullable<Text>,
        extras -> Nullable<Text>,
    }
}

diesel::table! {
    bufferviews (id) {
        id -> Text,
        buffer -> Text,
        byte_offset -> Integer,
        byte_length -> Integer,
        byte_stride -> Nullable<Integer>,
        target -> Nullable<Integer>,
        name -> Nullable<Text>,
        extensions -> Nullable<Text>,
        extras -> Nullable<Text>,
    }
}
```

```rust
    #[test]
    fn test_select_by_id_bufferview() {
        let database = TemporaryDatabase::new();

        let bufferview = gltf_types::bufferview::BufferView {
            id: uuid::Uuid::now_v7(),
            buffer: uuid::Uuid::now_v7(),
            byte_offset: 0,
            byte_length: 32,
            byte_stride: Some(4),
            target: Some(34962),
            name: Some("test_bufferview".to_string()),
            extensions: None,
            extras: None,
        };

        let test = database
            .insert_one::<BufferViewResource, BufferView>(bufferview.clone().into())
            .unwrap();

        let result = database.select_by_id::<BufferViewResource, BufferView>(bufferview.id);

        assert!(result.is_ok());

        let selected_bufferview = result.unwrap();

        assert_eq!(selected_bufferview.id, bufferview.id);
    }
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

Not sure about "This issue can be reproduced without requiring a third party crate", this is how my `insert_one()` looks like:

```rust
pub fn insert_one<'query, Resource, Model>(&self, resource: Resource) -> Result<Resource>
where
    Model: ResourceModel<Resource> + Insertable<Model::Table>,
    Model::Table: diesel::Table + HasTable<Table = Model::Table>,
    InsertStatement<Model::Table, <Model as Insertable<Model::Table>>::Values>:
        LoadQuery<'query, Connection, Model>,
{
    let values: Model = Model::from(resource);
    let conn = &mut self.connection().clone().get().unwrap();

    insert_into(Model::table())
        .values(values)
        .get_result(conn)
        .map(Into::<Resource>::into)
        .map_err(|err| vec![err.to_jsonapi_error()])
}
```

**Comment by JMLX42** [comment]
The simplest workaround is to use `PRAGMA foreign_keys = OFF`.

**Comment by JMLX42** [comment]
## Pure SQLite tests

Here is a pure SQLite bash command to make sure I did not make a mistake regarding the expected behavior.

### `PRAGMA foreign_keys = ON;`

Expected error, `diesel::insert_into()` is inconsistent with SQLite :x: 

```bash
$ sqlite3 test.db "
PRAGMA foreign_keys = ON;
CREATE TABLE buffers (id TEXT PRIMARY KEY NOT NULL);
CREATE TABLE bufferviews (id TEXT PRIMARY KEY NOT NULL, buffer TEXT NOT NULL, FOREIGN KEY (buffer) REFERENCES buffers(id));
INSERT INTO bufferviews (id, buffer) VALUES ('some_id', 'nonexistent') RETURNING *;
"

some_id|nonexistent
Error: stepping, FOREIGN KEY constraint failed (19)
```


### `PRAGMA foreign_keys = OFF;`

Expected return value, `diesel::insert_into()` is consistent with SQLite :heavy_check_mark: 

```bash
$ sqlite3 test.db "
PRAGMA foreign_keys = OFF;
CREATE TABLE buffers (id TEXT PRIMARY KEY NOT NULL);
CREATE TABLE bufferviews (id TEXT PRIMARY KEY NOT NULL, buffer TEXT NOT NULL, FOREIGN KEY (buffer) REFERENCES buffers(id));
INSERT INTO bufferviews (id, buffer) VALUES ('some_id', 'nonexistent') RETURNING *;
"

some_id|nonexistent
```

**Comment by weiznich** [comment]
Thanks for writing this bug report. I'm not sure how to reproduce your problem as the provided code relies on quite a lot third party functions/nested functionality. 

I've locally tried the following test as part of the diesel test suite (in `diesel_tests`):

```rust
#[test]
fn insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed() {

    let conn = &mut connection();

    let res = diesel::insert_into(posts::table)
        .values((posts::title.eq("whatever"), posts::user_id.eq(-1)))
        .returning(posts::id)
        .get_result::<i32>(conn);

    assert!(res.is_err());
}
```

I can verify that this returns an error as expected, therefore I'm not quite sure what exactly you want to report here. Maybe you can provide a self contain reproducible example of your issues?

**Comment by JMLX42** [comment]
Sorry for missing that test. That's definitely an oversight on my part.

Still, the `returning(posts::id)` might be the difference here. In [the documentation](https://docs.diesel.rs/2.1.x/diesel/prelude/trait.RunQueryDsl.html#method.get_result):

> When this method is called on an insert, update, or delete statement, it will implicitly add a RETURNING * to the query, unless a returning clause was already specified.

That's why IMHO I don't need the `returning()`, I am fine with the default `RETURNING *`. Am I correct?

> I've locally tried the following test as part of the diesel test suite (in diesel_tests):

I have added that test to `insert.rs` and I have a different result:

```bash
diesel/diesel_tests on  master is 📦 v0.1.0 via 🦀 v1.72.1 took 13s
❯ cargo test -F sqlite -F returning_clauses_for_sqlite_3_35 insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed
    Blocking waiting for file lock on build directory
   Compiling diesel_tests v0.1.0 (/home/jmlx/Downloads/diesel/diesel_tests)
    Finished test [unoptimized + debuginfo] target(s) in 8.86s
     Running tests/lib.rs (/home/jmlx/Downloads/diesel/target/debug/deps/integration_tests-ec2563d707866df5)

running 1 test
test insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed ... FAILED

failures:

---- insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed stdout ----
thread 'insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed' panicked at 'assertion failed: res.is_err()', diesel_tests/tests/insert.rs:839:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 289 filtered out; finished in 0.00s

error: test failed, to rerun pass `--test integration_tests`
```

And the behavior of the test is consistent with the bug IMO.

**Comment by weiznich** [comment]
> Sorry for missing that test. That's definitely an oversight on my part.

To be sure that test is not in the test suite. I've written that one locally to reproduce the issue.

> That's why IMHO I don't need the returning(), I am fine with the default RETURNING *. Am I correct?

That's mostly correct. It won't do a `RETURNING *` but list all columns explicitly.

> I have added that test to insert.rs and I have a different result:

That refers to my test case, right? In that case can you try updating your sqlite version?

My local version is:
```
3.40.1 2022-12-28 14:03:47 df5c253c0b3dd24916e4ec7cf77d3db5294cc9fd45ae7b9c5e82ad8197f3alt1
```

**Comment by JMLX42** [comment]
> My local version is:

I just tried with 3.43.1 and I got the same problem:

```
diesel/diesel_tests on  master [!] is 📦 v0.1.0 via 🦀 v1.72.1
❯ sqlite3 --version
3.43.1 2023-09-11 12:01:27 2d3a40c05c49e1a49264912b1a05bc2143ac0e7c3df588276ce80a4cbc9bd1b0 (32-bit)

diesel/diesel_tests on  master [!] is 📦 v0.1.0 via 🦀 v1.72.1
❯ cargo test -F sqlite -F returning_clauses_for_sqlite_3_35 insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running tests/lib.rs (/home/jmlx/Downloads/diesel/target/debug/deps/integration_tests-ec2563d707866df5)

running 1 test
test insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed ... FAILED

failures:

---- insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed stdout ----
thread 'insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed' panicked at 'assertion failed: res.is_err()', diesel_tests/tests/insert.rs:839:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    insert::insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 289 filtered out; finished in 0.01s

error: test failed, to rerun pass `--test integration_tests`
```

I would be very surprised if 3.37 did not work, and the 3.40.1 did, and then 3.43.1 did not. That *is* possible. But IMHO it's more likely I'm doing something wrong here.

Shouldn't we add the test anyway? At least the CI will give us a 3rd point of view...

**Comment by JMLX42** [comment]
Just ran in a container and it *does* work:

```bash
docker run --rm -it -v $PWD:/diesel rust:1.72.1 bash -c "
  wget https://www.sqlite.org/2023/sqlite-tools-linux-x86-3430100.zip
  unzip sqlite-tools-linux-x86-3430100.zip
  cp sqlite-tools-linux-x86-3430100/* /usr/local/bin/
  cd /diesel/diesel_tests/
  cargo test \
    -F sqlite \
    -F returning_clauses_for_sqlite_3_35 \
    insert_with_returning_should_report_an_error_on_foreign_key_constrainted_failed
"
```

So it is most likely coming from my environment.

**Comment by JMLX42** [comment]
> So it is most likely coming from my environment.

I added the following to `Cargo.toml`:

```toml
libsqlite3-sys = { version = "0.26.0", features = ["bundled"] }
```

And now my tests fail with the expected `FOREIGN KEY constraint failed` error. Which IMHO does point to my environment being the problem here.

So I suspect the build without the bundled `libsqlite3-sys` is not loading the SQLite I expect it to.

**Comment by JMLX42** [comment]
> So I suspect the build without the bundled libsqlite3-sys is not loading the SQLite I expect it to.

OK so me testing `sqlite3 --version` is dump, because of course the build is going to use the `.so`, not the binary.

```bash
gltf-server/target/debug on  13-switch-to-a-sqlite-compatible-backend [$!]
❯ ldd gltf_server
	linux-vdso.so.1 (0x00007ffd3637c000)
	libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f87526b3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f87537ef000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f87525cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8752200000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8753826000)
```

I do not want to depend on the system lib anyway, so bundled it is!
