### ISSUE TITLE
how to add filter dynamic?

### ISSUE THREAD

**Issue by Matrix-Zhang** [diesel-rs/diesel#381]
i want to select rows with much filters.

how to write the code ? because of the rust static type system, i don't know the right type of the filter

like posts.eq(1).or(posts.between(5..8))

**Comment by sgrif** [comment]
Can you give the full code that you're trying to write? Is `posts` an integer column?

**Comment by Matrix-Zhang** [comment]
posts is integer, the sever will recive the user input as filter, su as "1,2,5-8"
so, i need build the filter from the user's input

**Comment by sgrif** [comment]
http://docs.diesel.rs/diesel/prelude/trait.BoxedDsl.html will help you dynamically build the query. As for parsing the string, that's not something Diesel can help with.

**Comment by Gisleburt** [comment]
Updated link to BoxedDsl: http://docs.diesel.rs/diesel/query_dsl/methods/trait.BoxedDsl.html

**Comment by jiangxiaoqiang** [comment]
I am tried to use it but did not work, I did not know where is going wrong: https://stackoverflow.com/questions/71535350/function-or-associated-item-not-found-in-dolphin-schemainterviewtable

**Comment by jiangxiaoqiang** [comment]
> i want to select rows with much filters.
> 
> how to write the code ? because of the rust static type system, i don't know the right type of the filter
> 
> like posts.eq(1).or(posts.between(5..8))

did you fix it, what did you do to make it work?

**Comment by weiznich** [comment]
@jiangxiaoqiang Please stop to randomly ask question in old bug reports. That's not the right place for such questions. Use the gitter channel or the discussion forum for this.
