### ISSUE TITLE
Rust 1.10 stabilised {Occupied,Vacant,}Entry::key

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#388]
A comment [here](https://github.com/diesel-rs/diesel/blob/e2490c38d5c4cc38a38d31c5ff9d4272febfa8fb/diesel/src/pg/connection/stmt/cache.rs#L60) says:

> ```rust
> // FIXME: This can be cleaned up once https://github.com/rust-lang/rust/issues/32281
> // is stable
> ```

This has been stabilised in Rust 1.10 (cf. https://github.com/rust-lang/rust/pull/33699).

**Comment by cengizIO** [comment]
Hello!

I can work on this, if there's nobody already assigned.

**Comment by sgrif** [comment]
Have at it!

**Comment by cengizIO** [comment]
Hello @killercup, @sgrif 

I replaced old if block with new matchers but currently having borrowing/ownership issues.

I brought a Postgres docker instance up and fixing tests one by one.

Will submit a PR in following days.

Thanks

**Comment by gsquire** [comment]
This could help too: https://gist.github.com/sgrif/68cbba9a87084da3a2e8c42a12e7d6cf

**Comment by cengizIO** [comment]
Sorry it's been a very busy week. 

I'm back to working on this.
