### ISSUE TITLE
`#[derive(AsExpression, FromSqlRow)]` won't compile when generic bounds have a default implementation.

### ISSUE THREAD

**Issue by michaelkirk** [diesel-rs/diesel#3902]
### Versions

- **Rust:** 1.75
- **Diesel:** 2.1.4 (diesel_derives 2.1.2)
- **Database:** postgres
- **Operating System** macos

### Feature Flags

- **diesel:** ` default-features = false, features = ["postgres"]`

## Problem Description

`#[derive(AsExpression, FromSqlRow)]` won't compile when generic bounds have a default implementation.

### What are you trying to accomplish?

Here's a simplified version of the relevant code, but you can see the full thing in [this PR]( https://github.com/georust/geozero/pull/188). We modified a struct field to be generic, and for backwards compatibility, we wanted to add the previous field type as the default trait implementation.

```
#[derive(AsExpression, FromSqlRow)]
#[diesel(sql_type = Geometry)]
#[diesel(sql_type = Geography)]
pub struct Ewkb<B: AsRef<[u8]> = Vec<u8>>(pub B);
```

### What is the expected output?

I expected it to compile. 🙃 

More specifically, I expected the macro to expand to something like:
```diff
- impl<'expr, B: AsRef<[u8]> = Vec<u8>> AsExpression<Geometry> for &'expr Ewkb<B> {
+ impl<'expr, B: AsRef<[u8]>> AsExpression<Geometry> for &'expr Ewkb<B> {
   ...
}
```

### What is the actual output?

Two errors are produced by the current output:
```
error: generic parameters with a default must be trailing
  --> geozero/src/wkb/wkb_reader.rs:28:17
   |
28 | pub struct Ewkb<B: AsRef<[u8]> = Vec<u8>>(pub B);
   |                 ^
```
```
error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions
  --> geozero/src/wkb/wkb_reader.rs:28:17
   |
28 | pub struct Ewkb<B: AsRef<[u8]> = Vec<u8>>(pub B);
```

Both of these errors make sense only if you look at the expanded macro output. You see code like:

```
impl<'expr, B: AsRef<[u8]> = Vec<u8>> AsExpression<Geometry> for &'expr Ewkb<B> {
                          ^^^^^^^^^^- THIS IS A PROBLEM!!! ( my own annotation 😉 )
    type Expression = Bound<Geometry, Self>;
    fn as_expression(self) -> Self::Expression {
        Bound::new(self)
    }
}
```

### Steps to reproduce

let me know if the above isn't clear

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
I've opened https://github.com/diesel-rs/diesel/pull/3903 to fix this. Can you verify that it actually fixes your issue?

**Comment by michaelkirk** [comment]
Confirmed that I am now able to build with latest master (currently https://github.com/diesel-rs/diesel/commit/5f173aba3c82cba628336fc427909ff1ba3a43ec)

Thank you for such a fast response!
