### ISSUE TITLE
Serials keep incrementing despite begin_test_transaction

### ISSUE THREAD

**Issue by SmartMonkey-git** [diesel-rs/diesel#3905]
### Versions

- **Rust:** rustc 1.74.1 (a28077b28 2023-12-04)
- **Diesel:** 2.1.0 and diesel_async: 0.4.1
- **Database:** Postgres 15.3
- **Operating System** MacOs Sonoma 14.0 

### Feature Flags
- **diesel:** diesel_async

## Problem Description
Serial columns keep incrementing between test runs despite begin_test_transaction. 

### What are you trying to accomplish?
I'm trying to run a test in succession, that asserts the value of a serial column.

### What is the expected output?
Every time I run this test, I get the same value for that column.

### What is the actual output?
The value increments with every run of the test.

### Are you seeing any additional errors?
No.

### Steps to reproduce
- Establish connection to DB
- Run begin_test_transaction
- Insert a new instance into a table with a serial column
- Assert the value of said column
- Run the test again

## Checklist

- [ x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [ x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Can you explain: 

* Why you believe that is an issue in diesel?
* Why you believe that this would be the expected behavior?

**Comment by SmartMonkey-git** [comment]
Hey @weiznich,

> Why you believe that is an issue in diesel?

I believe that in a progressed test suite this can lead to problems, where earlier tests leave these changes in the db.

> Why you believe that this would be the expected behavior?

Because, I would expect the database to be in the same state as if I would relaunch it.

Thank you for your fast answer! It was unexpected.

**Comment by weiznich** [comment]
Closed as expected behavior as this is just how postgres handles sequences while rolling back transactions: https://www.postgresql.org/docs/current/functions-sequence.html
