### ISSUE TITLE
Source code for diesel_derives 2.1.2 not available on GitHub

### ISSUE THREAD

**Issue by mohe2015** [diesel-rs/diesel#3911]
Hi,

it seems like the source code of diesel_derives 2.1.2 (https://docs.rs/crate/diesel_derives/2.1.2/source/Cargo.toml.orig) is not available here in the GitHub repository (https://github.com/diesel-rs/diesel/blob/166b97c75f097396824002366e37298a55f14717/diesel_derives/Cargo.toml). Is there a reason for that? Also it seems like it's version got tagged in the past but that seems to have stopped at some point (https://github.com/diesel-rs/diesel/releases/tag/diesel_derives_v2.0.2).

Kind regards
Moritz

**Comment by weiznich** [comment]
`diesel_derives` is usually released together with `diesel`. In that case wo only create a single tag for that release. For version 2.1.2 that's this release: https://github.com/diesel-rs/diesel/releases/tag/v2.1.2

These releases are created from the corresponding release branch (in that case the 2.1.x branch). See here for the corresponding `Cargo.toml` https://github.com/diesel-rs/diesel/blob/2.1.x/diesel_derives/Cargo.toml
