### ISSUE TITLE
Test custom_derive integration

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#393]
Many of the `macro_rules!` macros can be used with the _custom_derive_ crate, e.g. `BelongsTo!` or `Identifiable!`. This is documented, by not tested.

We should (as a first step) add _custom_derive_ as a dev dependency and expand the documentation code blocks to actually work as doc tests.

**Comment by shssoichiro** [comment]
I'd like to work on this one.

**Comment by killercup** [comment]
@shssoichiro Oh! You might want to hold off on this one right now. There are known bugs when using `custom_derive!` and we'll probably not spend much time fixing them and instead build something using macros 1.1.

**Comment by shssoichiro** [comment]
Got it! I'll check back later if this still ends up being necessary.

**Comment by sgrif** [comment]
Closing as it turns out custom-derive is completely broken and we're just going to remove it from the docs now that Macros 1.1 is a thing.
