### ISSUE TITLE
Regression: LIKE queries on nullable fields in MySQL

### ISSUE THREAD

**Issue by thomasmost** [diesel-rs/diesel#3957]
## Setup

Install the latest version of diesel for MySQL from GitHub, i.e. 
```toml
diesel = { git = "https://github.com/diesel-rs/diesel", features = ["mysql", "extras", "chrono", "r2d2"] }
```

### Versions

- **Rust:** 1.76.0
- **Diesel:** unstable, latest
- **Database:** MySQL
- **Operating System** MacOS

### Feature Flags

- **diesel:** ["mysql", "extras", "chrono", "r2d2"] 

## Problem Description

A previously compiling query (see below) now causes the following error:

the trait `expression::operators::LikeIsAllowedForType<diesel::sql_types::Nullable<diesel::sql_types::Text>>` is not implemented for `Mysql`

```rs

#[derive(AsChangeset, Clone, Debug, Default, Deserialize, Insertable, Queryable, Serialize)]
pub struct User {
  pub id: String,
  pub name: Option<String>,
  pub email: String,
  pub email_verified: Option<chrono::NaiveDateTime>,
  pub image: Option<String>,
  pub created_at: chrono::NaiveDateTime,
  pub state: String,
}

  pub fn search_by_name(connection: &mut MysqlConnection, name: &str) -> Vec<User> {
    users::table
      .filter(
        users::name
          .like(format!("%{}%", name))
          .or(users::email.like(format!("%{}%", name))),
      )
      .load::<User>(connection)
      .expect("Error reading user")
  }

```

### What are you trying to accomplish?

Just want to give a heads-up ahead of the next release

### What is the expected output?

Should compile

### What is the actual output?
```
error[E0277]: the trait bound `Mysql: expression::operators::LikeIsAllowedForType<diesel::sql_types::Nullable<diesel::sql_types::Text>>` is not satisfied
    --> bdata/src/dal/user.rs:227:21
     |
227  |       .load::<User>(connection)
     |        ----         ^^^^^^^^^^ the trait `expression::operators::LikeIsAllowedForType<diesel::sql_types::Nullable<diesel::sql_types::Text>>` is not implemented for `Mysql`
     |        |
     |        required by a bound introduced by this call
```

### Are you seeing any additional errors?

No

### Steps to reproduce

see above

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting and good job for noticing that ~2h after the relevant change was merged :+1:

I think we just miss the relevant impl for nullable here: https://github.com/diesel-rs/diesel/blob/6ef23bd9496f14e735372c88047ed69bf08c0910/diesel/src/expression/operators.rs#L749 

I think I would likely write something like that:

```rust
impl<T, DB> LikeIsAllowedForType<crate::sql_types::Nullable<T>> for DB 
where 
    DB: Backend + LikeIsAllowedForType<T>,  
{} 
```

That also should cover `Nullable<Binary>` for the postgres backend. 

Mind sumitting a PR that adds this impl + adds a test so that we don't break it again?

**Comment by thomasmost** [comment]
Would be happy to :)

**Comment by thomasmost** [comment]
@weiznich I think I can figure out how to write the test, but can you point me to the workspace member library where the test should go?

**Comment by weiznich** [comment]
https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/filter.rs would be a good place for the test. I think the users table there already has a nullable text field.

**Comment by thomasmost** [comment]
Thank you!
