### ISSUE TITLE
[Website] Breakpoints need tweaking

### ISSUE THREAD

**Issue by hugo** [diesel-rs/diesel#396]
While shrinking the website down to fit it alongside an editor, I noticed a quirk where at a certain point you get a wider view if you make the browser window narrower.

![2016-08-05 12_05_52](https://cloud.githubusercontent.com/assets/1704089/17434893/fb8161b6-5b04-11e6-86f9-d5471b7a7a02.gif)

**Comment by sgrif** [comment]
I believe this is intentional to improve readability on tablets

**Comment by hugo** [comment]
It makes readability worse on narrow browser windows that aren't quite narrow enough, though. The full width breakpoint should be the same on desktop.
