### ISSUE TITLE
Many-To-Many Joins

### ISSUE THREAD

**Issue by Necoro** [diesel-rs/diesel#398]
Currently it seems to not be possible to use many-to-many joins in diesel. I was unable to find some out-of-the-box "many-to-many from A to B via cross-table C" -- and for manual implementation (one-to-many from  A to C, many-to-one from C to B) support for id-less tables (C obiously has a compound PK) is missing.

Thus, I wanted to open this issue as a reminder (I'm quite astonished that there is none yet :))

**Comment by sgrif** [comment]
Thanks for the issue! This pretty much falls naturally out of the current design once we add composite PK support in general, which is something I'm working on.

**Comment by cbrewster** [comment]
Hi @sgrif, is there anywhere where I can track the progress of composite PK support?

**Comment by killercup** [comment]
A bunch of stuff for composite PKs landed recently, like the annotations in
`table!`. Have a look at the release notes, or the PRs for that if the
macro docs don't include it.

Connor Brewster <notifications@github.com> schrieb am Di. 27. Dez. 2016 um
05:14:

**Comment by cbrewster** [comment]
@killercup awesome! Is there a recommended way to handle many-to-many yet or is that still in the works?

**Comment by lholden** [comment]
@cbrewster @killercup The composite stuff works... but many to many stuff is still messy by the looks of it.
An example of specifying a composite key in the table! macro:
```rust
table! {
    firsts_seconds (first_id, second_id) {
        first_id -> Integer,
        second_id -> Integer,
    }
}
```

Since we do not have explicit support for many to many... you end up having to build out an actual struct for this:

```rust
#[belongs_to(First)]
#[belongs_to(Second)]
#[table_name = "firsts_seconds"]
#[primary_key(first_id, second_id)]
#[derive(Identifiable, Queryable, Associations)]
struct FirstToSecond {
    pub first_id: i32,
    pub second_id: i32,
}
```
And then I guess you can do a join query on the firsts_seconds and seconds where the first_id matches the id of the first you are starting with.

**Comment by dumindu** [comment]
any update on this?

**Comment by Kerollmops** [comment]
Hi everybody !

Is there some news on many-to-many joins ?
I noticed that `infer_schema!` only supports _tables with primary keys_ and that's not mandatory for many-to-many joins.

Therefore I don't know how to represent simple tables joins between _Users_ and _Teams_.

Thanks ❤️
