### ISSUE TITLE
Diesel-Schema not supporting Postgres-SCHEMA

### ISSUE THREAD

**Issue by nsauwsaf** [diesel-rs/diesel#3998]
### Versions

- **Rust:** `1.77.2`
- **Diesel:** `2.1.1`
- **Database:** `postgres`
- **Operating System**: `linux/debian`

### Feature Flags

- **diesel:** `postgres`

## Problem Description

When I add a [`SCHEMA`](https://www.postgresql.org/docs/current/ddl-schemas.html) and a `TABLE` in the `up.sql`, `diesel` won't update the `schema.rs`.

### What are you trying to accomplish?

I want to add `SCHEMA`s to my database to make it more maintainable, etc. For example:

```sql
-- ...up.sql

CREATE SCHEMA documents

CREATE TABLE documents.metadata (
    document_id SERIAL PRIMARY KEY,
    document_title VARCHAR NOT NULL
)
```
```sql
-- ...down.sql

DROP SCHEMA documents CASCADE
```

### What is the expected output?

A `schema.rs` filled with a table and other stuff.

### What is the actual output?

A empty `schema.rs`:

```rust
// @generated automatically by Diesel CLI.

```

### Are you seeing any additional errors?

No.

### Steps to reproduce

1. `diesel setup`
2. `diesel migration generate documents`
3. Fill the `.sql`s with the code shown above.
4. `diesel migraton run`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

## Conclusion

I'm very new to diesel (and I really like it) and just wanted to start with some database structure, as I encountered this "bug", so I hope I'm not missing something. Also, I know that this might be more of a feature request. If you have any suggestions on how to work around this, feel free to write it, because I'm not that of a database-master.

**Comment by weiznich** [comment]
Thanks for writing this bug report.

This is expected behavior. Diesel does always only generate a `schema.rs` file for a single schema. By default that's the `public` schema, but you can configure the specified schema via the `print_schema.schema` key in your diesel.toml file. ([Documentation](http://diesel.rs/guides/configuring-diesel-cli.html)).  If you have tables in several schemas you currently need to use separate `diesel.toml` files for these schemas.
