### ISSUE TITLE
Rust-analyzer fails to autocomplete Match with diesel errors (Enum) 

### ISSUE THREAD

**Issue by rxdiscovery** [diesel-rs/diesel#4020]
Hello,

I had a strange bug with Rust-analyser and Diesel, I would like to have your opinion, I posted all the details on the git page of rust-analyser : 

https://github.com/rust-lang/rust-analyzer/issues/17215

Thank you in advance for your help.

**Comment by weiznich** [comment]
If diesel related code compiles with rustic, but has issues with rust-analyzer that is considered to be a bug in rust-analyzer. Please report these bugs in their issue tracker. There is nothing on diesels side to fix here. Therefor I'm closing this issue as not planned. 

Additionally for future bug reports: Using the issue template is mandatory. Issues that don't follow the template have a higher likelihood to be closed directly.

**Comment by rxdiscovery** [comment]
@weiznich 

Thanks for taking the time to reply, I wanted your opinion as you're in the best position to determine which internal part of Diesel's code makes rust-analyzer inconsistent.

**Comment by weiznich** [comment]
To repeat again what I've written above: As the corresponding code works with rustc there is no problematic diesel code here, only faulty rust-analyzer code. That's the official statement of the rust project on this kind of issues. 

That written: I cannot comment on which diesel part might cause this as that would require extensive research to track this down. I would welcome somebody that takes the time to track it down, but I personally won't spend my time on it as there are only marginal chances to resolve such an issue even if we would know what code cause that.

**Comment by rxdiscovery** [comment]
I fully understand your point of view, it was just a way to better guide the dev team behind rust-analyser, in any case thank you for taking the time to read my message. :+1:
