### ISSUE TITLE
`diesel print-schema > foo.rs` fails without error message if database url not set

### ISSUE THREAD

**Issue by dullbananas** [diesel-rs/diesel#4041]
### Versions

- **Rust:** 1.77
- **Diesel:** cli version 2.1.1
- **Database:**
- **Operating System**

### Feature Flags

- **diesel:** postgres, no default

### What are you trying to accomplish?
Output schema file and see why exit status is 1

### What is the expected output?
```
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.
```

### What is the actual output?
```
```

### Steps to reproduce

```
diesel print-schema --config-file=diesel.toml > tmp.schema
```

diesel.toml:
```
[print_schema]
file = "crates/db_schema/src/schema.rs"
patch_file = "crates/db_schema/src/diesel_ltree.patch"
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting.

I can reproduce the problem with the latest release, but not with the latest version from master. It was likely fixed with https://github.com/diesel-rs/diesel/pull/3897

Closed as this issue is already fixed
