### ISSUE TITLE
Question: help with foreign key

### ISSUE THREAD

**Issue by vitiral** [diesel-rs/diesel#405]
I am fairly new to SQL and rust, and am trying to make a simple test-tracking tool with a db backend (written in diesel and rust).

For an ultra simple version, my tables look like:
```
CREATE TABLE tests {
  name TEXT PRIMARY KEY,
}

CREATE TABLE runs {
  id SERIAL PRIMARY KEY,
  test_name TEXT references tests(name),
  passed bool NOT NULL,
}
```

I can't find any documentation on how to deal with foreign keys in diesel. Can I just make a struct like:
```
#[derive(Queryable)]
struct Run {
  id: i32,
  test_name: String,
  passed: bool,
}

#[insertable_into(runs)]
struct NewRun {
  test_name: String,
  passed: bool,
}
```

and diesel will handle creating a new row in `test_names` when the name doesn't exist? What is the best way to handle this?

**Comment by sgrif** [comment]
`diesel::insert(&NewRun { ... }).into(runs::table).execute(&connection)` will insert a new run. The fact that there is a foreign key will not have any impact on the flow (other than providing potential error conditions). Your `test_name` column should probably be `NOT NULL` or your field should be `Option<String>` though.

**Comment by vitiral** [comment]
Thanks a ton! Would be great if this could be incorporated into the documentation -- the fact that this is handled automagically makes diesel even more appealing :)

I imagine if I pointed to a `name_id` foreign key instead then this would be a two step process? (first create the name and/or query the id, then create the run?)

**Comment by sgrif** [comment]
> the fact that this is handled automagically makes diesel even more appealing

Not sure what you mean? We're literally not handling anything here. And yes your question about the process is correct.

**Comment by vitiral** [comment]
the fact that you are adding a row to both the `tests` table and the `runs` table at once is pretty cool IMO.
