### ISSUE TITLE
`belonging_to().inner_join()` and  `.select()` with two-item tuple causes build error on sqlite backend

### ISSUE THREAD

**Issue by khimaros** [diesel-rs/diesel#4060]
### Versions

- **Rust: 1.78.0**
- **Diesel: 2.2.0**
- **Database: sqlite**
- **Operating System: debian trixie**

### Feature Flags

- **diesel: sqlite**

## Problem Description

i'm following along with the "relations" tutorial using an sqlite database, and i'm running into a compile error when using a tuple for `.select()` as shown here: https://github.com/diesel-rs/diesel/blob/2.2.x/examples/postgres/relations/src/main.rs#L147

NOTE: i was able to workaround this issue by manually specifying the return value of the `.load()` call, as in:

```rust
let attrs = BookAuthor::belonging_to(&author)
      .inner_join(authors::table)
      .select((BookAuthor::as_select(), Author::as_select()))
      .load::<(BookAuthor, Author)>(conn);
```

**build error**

```rust
error[E0283]: type annotations needed
    --> src/main.rs:155:18
     |
155  |                 .load(conn);
     |                  ^^^^ ---- type must be known at this point
     |                  |
     |                  cannot infer type of the type parameter `U` declared on the method `load`
     |
     = note: cannot satisfy `_: FromSqlRow<(expression::select_by::SelectBy<BookAuthor, Sqlite>, expression::select_by::SelectBy<Author, Sqlite>), Sqlite>`
     = help: the following types implement trait `FromSqlRow<ST, DB>`:
               <(T1, T0) as FromSqlRow<(ST1, Untyped), __DB>>
               <(T1, T2, T0) as FromSqlRow<(ST1, ST2, Untyped), __DB>>
               <(T1, T2, T3, T0) as FromSqlRow<(ST1, ST2, ST3, Untyped), __DB>>
               <(T1, T2, T3, T4, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T7, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, Untyped), __DB>>
               <(T1, T2, T3, T4, T5, T6, T7, T8, T0) as FromSqlRow<(ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8, Untyped), __DB>>
             and 23 others
     = note: required for `(SelectBy<BookAuthor, Sqlite>, SelectBy<Author, Sqlite>)` to implement `load_dsl::private::CompatibleType<_, Sqlite>`
     = note: required for `SelectStatement<FromClause<JoinOn<..., ...>>, ..., ..., ...>` to implement `LoadQuery<'_, diesel::SqliteConnection, _>`
note: required by a bound in `diesel::RunQueryDsl::load`
```

### What are you trying to accomplish?

i'm trying to perform an `inner_join` on a many-to-many relationship with sqlite as the database engine.

### Steps to reproduce

port the `relations` postgres example directly to `SqliteConnection`, using the same schema and model and then try to build.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
I cannot reproduce this error, it just works fine for me. Anyway I've just pushed the ported example here and will merge it after the CI is run: https://github.com/diesel-rs/diesel/pull/4061
