### ISSUE TITLE
Compile Error: assertion `left == right` failed: Unexpected output from mysql_config: `-L/usr/local/mysql/lib -lmysqlclient -lssl -lcrypto -lresolv`

### ISSUE THREAD

**Issue by prodbyola** [diesel-rs/diesel#4069]
### Versions

- **Rust:*1.72*
- **Diesel:*2.2.0*
- **Database:*MySQL*
- **Operating System*MacOS 12*

### Feature Flags

- **diesel:** ["mysql", "chrono", "r2d2"]

## Problem Description
I've been using diesel for awhile with no issue. Recently I started getting this compilation error and all efforts to troubleshoot have failed, including downgrading to previous versions. This is the error:

```bash
--- stderr
  thread 'main' panicked at /Users/prodbyola/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysqlclient-sys-0.3.1/build.rs:59:9:
  assertion `left == right` failed: Unexpected output from mysql_config: `-L/usr/local/mysql/lib -lmysqlclient -lssl -lcrypto -lresolv`
    left: 5
   right: 2
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I also tried moving my project to Windows (WSL) to be sure it's not platform-specific issue. But I got very similar error. I'm not sure how to fix this please.

## Checklist

- [ ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting.
This is an issue in the mysqlclient-sys crate, not a diesel issue. The build script logic there expects a different output from the `mysql_config` tool. 

You likely can workaround this by setting the `MYSQLCLIENT_LIB_DIR` environment variable to point to the right folder.
