### ISSUE TITLE
Add support for currently unsupported range operators and methods

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#4092]
Diesel currently supports the postgres range types. We do not provide built-in support for [various operators and methods](https://www.postgresql.org/docs/current/functions-range.html) available for these types. This is a tracking issue for adding support for these operators. 

The general strategy for adding support for new operators is as following:

1. Define the operator via [`infix_operator!()`](https://docs.diesel.rs/master/diesel/macro.infix_operator.html). The RangeExtends operator  would be defined as following: `infix_operator!(RangeExtends, " &> ", backend: Pg);` These operators can be defined [here](https://github.com/diesel-rs/diesel/blob/dd5f41dc93c574077646185393cd064c7103000b/diesel/src/pg/expression/operators.rs). If there is already an existing definition, this step could be skipped.
2. Define a new helper type [here](https://github.com/diesel-rs/diesel/blob/master/diesel/src/pg/expression/helper_types.rs#L30). Helper types are a tool for diesel users to simplify type definitions. Again if there is already a matching type definition this could be skipped. 
3. Add a new method to the [`PgRangeExpressionMethods` trait](https://github.com/diesel-rs/diesel/blob/99ef8bbdee614b8eb6560b00c4c1ead88fb0e737/diesel/src/pg/expression/expression_methods.rs#L706-L758). This definition should:
    * Use the previously defined helper type
    * Contain a documentation with an example
4. If possible add a test case for the auto_type attribute [here](https://github.com/diesel-rs/diesel/blob/99ef8bbdee614b8eb6560b00c4c1ead88fb0e737/diesel_derives/tests/auto_type.rs#L277-L288). (If not possible add a documentation entry there)
5. Check if compile test output is up to date by running `TRYBUILD=overwrite cargo test` inside of `diesel_compile_tests`. (This is required if you've added a new operator based on `infix_operator!`
5. Submit a PR with the change

The general strategy for adding support for new methods is as following:

1. Define the operator via [`define_sql_function!()`](https://docs.diesel.rs/master/diesel/expression/functions/macro.define_sql_function.html). The lower method would be defined as following: `define_sql_function!(fn lower<T: RangeHelper>(range: T) -> T::Inner);` These operators can be defined [here](https://github.com/diesel-rs/diesel/blob/99ef8bbdee614b8eb6560b00c4c1ead88fb0e737/diesel/src/pg/expression/functions.rs). If there is already an existing definition, this step could be skipped. This function should have a short documentation snippet with en example
6. Check if compile test output is up to date by running `TRYBUILD=overwrite cargo test` inside of `diesel_compile_tests`. (This is required if you've added a new operator based on `infix_operator!`
5. Submit a PR with the change

Operator list:

- [x] `anyrange @> anyrange -> bool` (Does the first range contain the second?)
- [x] `anyrange @> anyelement -> boolean` (Does the range contain the element?) * 
- [x] `anyrange <@ anyrange -> boolean` (Is the first range contained by the second?)  *
- [x] `anyelement <@ anyrange -> boolean` (Is the element contained in the range?) *
- [x] `anyrange && anyrange -> boolean` (Do the ranges overlap, that is, have any elements in common?) *
- [x] `anyrange << anyrange -> boolean` (Is the first range strictly left of the second?) *
- [x] `anyrange >> anyrange -> boolean` (Is the first range strictly right of the second?) *
- [x] `anyrange &< anyrange -> boolean` (Does the first range not extend to the right of the second?) *
- [x] `anyrange &> anyrange -> boolean` (Does the first range not extend to the left of the second?) *
- [x] `anyrange -|- anyrange -> boolean` (Are the ranges adjacent?) *
- [x] `anyrange + anyrange -> anyrange` (Computes the union of the ranges. The ranges must overlap or be adjacent, so that the union is a single range (but see range_merge()).) **
- [x] `anyrange * anyrange -> anyrange` (Computes the intersection of the ranges.) **
- [x] `anyrange - anyrange -> anyrange` (Computes the difference of the ranges. The second range must not be contained in the first in such a way that the difference would not be a single range.) **

Method list:

- [x] `lower ( anyrange ) -> anyelement` (Extracts the lower bound of the range (NULL if the range is empty or has no lower bound).) *
- [x] `upper ( anyrange ) -> anyelement` (Extracts the upper bound of the range (NULL if the range is empty or has no upper bound).) *
- [x] `isempty ( anyrange ) -> boolean` (Is the range empty?) *
- [x] `lower_inc ( anyrange ) -> boolean` (Is the range's lower bound inclusive?) *
- [x] `upper_inc ( anyrange ) -> boolean` (Is the range's upper bound inclusive?) *
- [x] `lower_inf ( anyrange ) -> boolean` (Does the range have no lower bound? (A lower bound of -Infinity returns false.) *
- [x] `upper_inf ( anyrange ) -> boolean` (Does the range have no upper bound? (An upper bound of Infinity returns false.)) *
- [x] `range_merge ( anyrange, anyrange ) -> anyrange` (Computes the smallest range that includes both of the given ranges.) *
- [x] `int4range(Nullable<Integer>, Nullable<Integer>, RangeBoundEnum) -> int4range` ***
- [x] `int8range(Nullable<BigInteger>, Nullable<BigInteger>, RangeBoundEnum) -> int8range` ***
- [x] `numrange(Nullable<Numeric>, Nullable<Numeric>, RangeBoundEnum) -> numrange` ***
- [x] `tsrange(Nullable<Timestamp>, Nullable<Timestamp>, RangeBoundEnum) -> tsrange` ***
- [x] `tstzrange(Nullable<Timestamptz>, Nullable<Timestamptz>, RangeBoundEnum) -> tstzrange` ***
- [x] `daterange(Nullable<Date>, Nullable<Date>, RangeBoundEnum) -> daterange` ***

Items marked with one `*` can follow the instructions directly. For items marked with ** it might be useful to look into how to use the [existing](https://github.com/diesel-rs/diesel/tree/99ef8bbdee614b8eb6560b00c4c1ead88fb0e737/diesel/src/expression/ops) rust side operator implementations as well. For items marked with *** we need to introduce an `enum RangeBoundEnum` type (or similar named) that specifies which bound kinds should be used. That likely requires a custom sql type + implementing the relevant type mapping.

Please add a comment to this issue if you plan to work on a specific operator/method.

If there is anything unclear about how to add a support for a specific operator/method just ask and we will try to answer your questions.

**Comment by cole-wildcardsoftware** [comment]
I would like to help out with this issue. I haven't worked on diesel before so I'm currently working on building the repo locally

**Comment by guissalustiano** [comment]
Hi! I'm also interested in helping with this issue. 
It's many small issues so we can split I think, or maybe work together to discover how to do it!
We can discuss that on Matrix, I'm @guissalustiano:gitter.im on the [matrix](https://gitter.im/diesel-rs/diesel?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).

**Comment by vijairamg** [comment]
Hi! I would like to help out with this issue as well.

**Comment by vijairamg** [comment]
I can start working on the `anyrange && anyrange -> boolean`.

**Comment by ccarral** [comment]
Hi! Started working on `anyelement <@ anyrange -> boolean`

**Comment by ccarral** [comment]
> Hi! Started working on `anyelement <@ anyrange -> boolean`

Oops, It's already implemented.  I see `anyrange &< anyrange -> boolean` isn't yet so I'm working on that instead.

**Comment by vijairamg** [comment]
Hi, I can work on `anyrange << anyrange -> boolean` and `anyrange >> anyrange -> boolean` next.

**Comment by vijairamg** [comment]
I can work on `anyrange + anyrange -> anyrange`, `anyrange * anyrange -> anyrange` and`anyrange - anyrange -> anyrange` next.

**Comment by weiznich** [comment]
I've filled https://github.com/diesel-rs/diesel/pull/4151 to add the last missing operators and cleanup some minor stuff. 

Thanks to all people that contributed to this feature :tada:
