### ISSUE TITLE
Upgrade Quickcheck

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#410]
Currently, there is this FIXME in [`diesel_tests/tests/types_roundtrip.rs`](https://github.com/diesel-rs/diesel/blob/bfbe86bd60204b1904804fbe6d8e0e26befebb7f/diesel_tests/tests/types_roundtrip.rs#L125-L144):

> FIXME: Needs https://github.com/BurntSushi/quickcheck/pull/128

That PR has been merged and is part of quickcheck 0.2.27. In fact, version 0.3 of quickcheck has been released in the meantime, though I don't know what the changes are.

**Comment by shssoichiro** [comment]
Hi, I'd like to go ahead and work on this.
