### ISSUE TITLE
Use Cargo Workspaces

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#411]
This feature landed relatively recently and I _think_ it can benefit us by cutting down on test times. We should figure out how to use it and integrate it into our crates.

**Comment by killercup** [comment]
I'm not sure how to define a workspace in `/` when all crates live in `/<name>/`, most projects have one top-level crate where they define a workspace. https://github.com/matthiasbeyer/imag/pull/624 is an example of a project with not top-level crate trying to add workspaces.

**Comment by killercup** [comment]
This has been done, so I'm gonna close this issue. See #557, though.
