### ISSUE TITLE
If the object is nullable is_null() returns a nullable boolean

### ISSUE THREAD

**Issue by Sagebati** [diesel-rs/diesel#4111]
### Versions

- Diesel: 2.*

## Problem Description

When using nullable columns as inputs of `is_null` and `is_not_null()` don't take into account that the result cannot be null. 

### What are you trying to accomplish?

Example
```rust
  // This does not compile
 let r: Vec<(u64, bool)>: user::table
            .left_join(
                team_user::table.on(user::id
                    .eq(team_user::user_id)
            )
            .select((
                user::id,
                team_user::team_id.is_null(), // Here we need assume_not_null() 
            ))
```

### What is the expected output?

The code to compile, because `is_null()` normally would imply the result to be not null.

### What is the actual output?

The code doesn't compile, `team_user::team_id.is_null()` seems to return `Nullable<sql_type::Bool>` so `assume_not_null()` is needed.

**Comment by Ten0** [comment]
> When using nullable columns as inputs of is_null and is_not_null() don't take into account that the result cannot be null.

I don't understand what you mean: unless I'm mistaken, if "using nullable columns as inputs" then the result *can* be null. So we can't "take into account that the result cannot be null", as that would be *wrong*.

**Comment by weiznich** [comment]
For the record: I asked for this issue being filed, but it seems like I missed the nullable part. @Ten0 is correct here that `.is_null()` (and `.is_not_null()`) always implements `Expression<SqlType = Bool>`.  I just verified that locally with the following code:

```rust
table! {
    abc {
        id -> Nullable<Integer>,
    }
}

fn check(_: impl Expression<SqlType = Bool>) {}

fn check_2() {
    check(abc::id.is_null());
    check(abc::id.is_not_null());
}
```

which compiles fine.

What can be done as future improvements is to seek a way to allow `left_joined_column.is(_not)_null()` without calling `.nullable()` at all. After all the result there will return a not nullable boolean in every case. I'm not sure if that fits in the current diesel trait setup without running into conflicting impls.

**Comment by Ten0** [comment]
It doesn't look like that would be a breaking change: unless I'm mistaken we would just need to lighten the bounds under which SelectableExpression is implemented for this postfix operator. 
However I feel like the current version leads to more readable code: it feels like it's easier to read `table::field.nullable().is_not_null()` as "did my left join succeed? " than it would be if the `.nullable()` was not there.

**Comment by weiznich** [comment]
> It doesn't look like that would be a breaking change: unless I'm mistaken we would just need to lighten the bounds under which SelectableExpression is implemented for this postfix operator.

The breaking change label was added under the wrong assumption that `IsNull` itself would a `Nullable<Bool>` expression depending on the nullablity of the expression. I removed the labels now.
