### ISSUE TITLE
Document using in-memory SQLite databases

### ISSUE THREAD

**Issue by ElijahCaine** [diesel-rs/diesel#419]
I'm trying to use diesel with SQLite. For testing purposes it'd be great to setup and teardown `":memory:"` databases but there's not really any documentation on how to do this.

I'd love to write the docs if someone could explain how I'm supposed to A) setup a connection with a `":memory:"` database and B) Run migrations on that database. Preferably without *also* having manually setup a file-based SQLite database.

I really like diesel and would love to contribute.

Edit:

I'm aware that I can just run `SqliteConnection::establish(":memory:").unwrap()` to get an in-memory SQLite connection. What I'm really curious about is how to compile a program using diesel without a previously existing database and not getting error output like

```
   Compiling crisco v0.1.0 (file:///home/e/svc/source/crisco)
error[E0432]: unresolved import `super::schema::urls`
 --> src/database/models.rs:6:5
  |
6 | use super::schema::urls;
  |     ^^^^^^^^^^^^^^^^^^^ no `urls` in `database::schema`

error[E0432]: unresolved import `self::schema::urls`
  --> src/database/mod.rs:25:5
   |
25 | use self::schema::urls;
   |     ^^^^^^^^^^^^^^^^^^ no `urls` in `database::schema`
```

Either way I'm up for documenting this, it took a bit of digging to get as far as I have.

**Comment by sgrif** [comment]
Using an in memory database is certainly supported, but you not be able to use `infer_schema!` with an in memory database (as there's no persistent schema to infer from). You will need to either use the `table!` macro directly, or compile against an on disk database for schema inference purposes.

**Comment by sgrif** [comment]
You can run migrations against the database after establishing the connection using the [`run_pending_migrations` function](http://docs.diesel.rs/diesel/migrations/fn.run_pending_migrations.html). That function requires the migrations to be on disk in the appropriate location. If you want to avoid that constraint, use the [`embed_migrations!` macro](https://github.com/diesel-rs/diesel/tree/master/diesel_codegen#embed_migrations). I've just noticed that the documentation is a bit lacking for `embed_migrations!` (which I will fix later today) but you use it like so:

```rust
embed_migrations!();

fn establish_connection() -> Result<SqliteConnection, MigrationError> {
    let connection = try!(SqliteConnection::establish(":memory:"));
    try!(embedded_migrations::run(&connection).unwrap();
    Ok(connection)
}
```

**Comment by Thomasdezeeuw** [comment]
@sgrif your example helps a lot to understanding the `embed_migrations` macro, maybe it's worth adding it to the docs?

**Comment by Eijebong** [comment]
@Thomasdezeeuw #854 http://docs.diesel.rs/diesel/macro.embed_migrations.html ^^

**Comment by Thomasdezeeuw** [comment]
I didn't see that, I was using local (outdated) documentation. Great that it's in!

**Comment by mmai** [comment]
The link is dead. Is it possible to do this with the last stable version of diesel ?

**Comment by sgrif** [comment]
https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html

**Comment by peacememories** [comment]
It seems like having to manually write the schema when using `:memory:` makes it a lot less useful for development purposes. Would it be possible to generate the schema files even when using in-memory databases?

**Comment by weiznich** [comment]
@peacememories What's wrong with using a static database for generating the schema? (It's technically not possible to generate the schema from a in memory database generated by another tool because the database is dropped as soon as the program ends)

**Comment by tema3210** [comment]
> @peacememories What's wrong with using a static database for generating the schema? (It's technically not possible to generate the schema from a in memory database generated by another tool because the database is dropped as soon as the program ends)

Actually, you can do it with IPC.

**Comment by pickfire** [comment]
Is it possible to explain how to use sqlite and mysql database in https://diesel.rs/guides/getting-started/ and https://github.com/diesel-rs/diesel/tree/master/examples/sqlite, I need to go through the code to figure out how to use sqlite which is https://github.com/diesel-rs/diesel/blob/master/examples/sqlite/test_all#L4 `DATABASE_URL="/tmp/test_examples.db"`? It would be good to have it in a README or explain that somewhere so beginners know what to use for `DATABASE_URL` and can easily get started with other databases.

**Comment by weiznich** [comment]
@pickfire Sure that's possible. Feel free to submit a PR for that.
