### ISSUE TITLE
select query loads data incorrectly if model is 'out of order'

### ISSUE THREAD

**Issue by fuchsnj** [diesel-rs/diesel#421]
Model looks like this:

``` rust
#[derive(Queryable, Debug)]
#[insertable_into(users)]
pub struct Model{
    pub id: String,
    pub username: String,
    pub email: String,
    pub password: String
}
```

And up.sql looks like this

``` sql
CREATE TABLE users
(
  id text NOT NULL,
  username text NOT NULL,
  password text NOT NULL,
  email text NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_username_key UNIQUE (username),
  CONSTRAINT users_email_key UNIQUE (email)
)
```

When I select a user, email and password are swapped

``` rust
let mut result = try!(users::dsl::users.filter(users::dsl::username.eq(username))
    .limit(1)
    .load::<Model>(&establish_connection())
);
```

**Comment by theduke** [comment]
Stumbled over this too.

Quite a big bug / gotcha.

**Comment by TedDriggs** [comment]
I got bitten by this, and also discovered that I had to blow away my `target` directory after fixing the `up.sql` file for the Rust struct to work as expected.

**Comment by zhangsoledad** [comment]
This is big big gotcha！！

**Comment by theduke** [comment]
Could there be a compile time test or lint for this?

**Comment by killercup** [comment]
> Could there be a compile time test/lint for this?

See #573

**Comment by willmurphyscode** [comment]
I'd like to help with this, but I'm not sure exactly how to get started. @sgrif mentions in https://github.com/diesel-rs/diesel/issues/573 that we don't want to talk to the database when running the linter. Should this linter inspect the structs and the `.sql` files in the migrations? If so, will the linter need to find both `CREATE TABLE` and `ALTER TABLE` calls and figure out what the table currently looks like?

**Comment by sgrif** [comment]
I think this issue has been addressed as much as it can be.

We now have `QueryableByName` for use with `sql_query`, since order specifics are painful when writing the query by hand. I've tried to make the fact that `Queryable` cares about order as clear on this as I can be in the documentation. The only other thing we can do for this a lint, which is covered in #573.
