### ISSUE TITLE
Not possible to use Array<SomeTuple> as SqlType

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#425]
It seems not to be possible to use `Array<SomeTuple>` as SqlType.

Think of the following query:

``` sql
select a.*, array_agg(b.*),
from table_a as a 
left join table_b as b on a.id = b.table_a_id
group by a.id
```

This results in `(A::SqlType, Array<B::SqlType>)` as SqlType where `B::SqlType' is a Tuple (e.g.`(BigInt, Text, BigInt)`).

`FromSql` and `FromSqlRow` are [implemented](https://github.com/diesel-rs/diesel/blob/master/diesel/src/pg/types/array.rs#L34-L74) for `Array` for each SqlType that has a `FromSql` implementation. Tuples [implement](https://github.com/diesel-rs/diesel/blob/master/diesel/src/types/impls/tuples.rs#L36-L45) however only `FromSqlRow`

**Comment by sgrif** [comment]
We don't currently support tuple types in PG. They're not currently on the list of types that are high priority to support.

**Comment by sgrif** [comment]
Clearing out old issues....

This is basically just "we don't support PG tuples". I think support for this will probably need to come from another crate. I don't think we can make this ergonomic without variadic generics. If nothing else, the PG type `(int4, int4)` will map to `PgTuple<i32, i32>` not `(i32, i32)` if we ever support it in Diesel.

Closing, as this is not immediately actionable.

**Comment by GopherJ** [comment]
Same problem here.

**Comment by weiznich** [comment]
@GopherJ This issue is closed since nearly 2 years. Just commenting "Same problem here" won't do anything, so please do not do that on other issues. 
In general if you hit an "old" issue like this one: First of all read all responses and if it's closed read the reason why it's closed. That reason is likely still valid. If you then still think this issue remains valid opening a new issue in our bug tracker is the right way for bugs. For feature requests please write a concrete proposal explaining the use-case and possibly a potential API and a way to implement the requested feature in our forum.

**Comment by dongjian** [comment]
select a.*, array_agg(b.*),
from table_a as a 
left join table_b as b on a.id = b.table_a_id
group by a.id
-----
how do this in diesel ?

I try 
```
a::table.inner_join(b::table).select((a::all_colums,sql::<b::SqlTypes>("
array_agg(b.*)  b_
"))).group_by(a::id).load::<(A,Vec<B>)>(conn)
```
but it can not be complie.

Then I Try
```
a::table.inner_join(b::table).select((a::all_colums,sql::<sql_types::Text>("
array_to_json (array_agg(b.*))  b_
"))).group_by(a::id).load::<(A,String)>(conn)
```
i need convert the array string to Vec<B>  .

Is there a more elegant way do that?

**Comment by weiznich** [comment]
@dongjian Issues that are closed since a long time are not the right place to ask for support. Please use the forum for that and include all relevant information in your question there. This includes at least a minimal example, an description what exactly doesn't work, any relevant compiler error as emitted by rustc and relevant information about the rustc/diesel versions you are using.
