### ISSUE TITLE
"Unsupported type: serial" error in Getting Started example using `infer_schema!` with SQLite

### ISSUE THREAD

**Issue by Zarathustra30** [diesel-rs/diesel#427]
If you go through the Getting Started guide using SQLite instead of Postgres, you cannot use `infer_schema!` because it kicks you out with the error "Unsupported type: serial". The docs [do not include "serial" among supported types](http://docs.diesel.rs/diesel/types/index.html#structs), but the database was generated using `diesel setup`, so the fact that it is not supported is a bit odd.

Currently using `nightly-2016-07-07-x86_64-pc-windows-gnu`.

**Comment by sgrif** [comment]
The type is called `Integer` on SQLite

**Comment by sgrif** [comment]
You say the database was set up by diesel setup -- but that doesn't create any tables. Can you provide steps to reproduce? What you've described should not be possible without user migrations

**Comment by Zarathustra30** [comment]
Ah. I did do the migration specified in Getting Started:
```
CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 'f'
)
```
But now that I look at it, I see `serial` right there. Which I now realize needs to be an `Integer`.

Now that I have fixed it, I'm getting completely different error messages, which is always a good sign.
