### ISSUE TITLE
Identifiable!, BelongsTo!, HasMany! are brocken when used with custom_derive

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#430]
Using one of those 3 macros with custom_derive will result in the following error:

```
error: expected ident, found ,
  --> <diesel macros>:21:25
   |
21 | Identifiable ! { $ args , fields = [ $ ( $ fields ) * ] , } } ; (
   |                         ^
```

Example Code:
```rust
custom_derive! {
     #[derive(Identifiable)]
     #[table_name(users)]
     struct User {
         id: i32,
         name: String,
     }
}
```

This is most likely caused by custom_derive not passing custom attributes down to the macro. The documentation mentions clearly:

"Secondly, the macro is passed the entire item, ***sans attributes***. It is the derivation macro's job to parse the item correctly."

We should change the syntax here to something like:

```rust
custom_derive! {
     #[derive(Identifiable(table_name=users))]
     struct User {
         id: i32,
         name: String,
     }
}
```

**Comment by sgrif** [comment]
https://github.com/diesel-rs/diesel/issues/438
