### ISSUE TITLE
`DynInstrumentation` is private for version 2.2.4?

### ISSUE THREAD

**Issue by siddhantk232** [diesel-rs/diesel#4302]
I can see that the `DynInstrumentation` was made public 2 months ago and the latest release (2.2.4) was done a month ago. How's this code not part of this release? I can also not find docs for this in https://docs.rs/diesel/

**Comment by weiznich** [comment]
New features land on the master branch. They are not backported as patch release to the last released version. New features will generally be released with the next minor diesel release, so in this case with diesel 2.3.

Closed as this is not an issue.
Please use the support forum for future questions.
