### ISSUE TITLE
Diesel doesn't recognise primary key

### ISSUE THREAD

**Issue by whyando** [diesel-rs/diesel#4331]
### Versions

- **Rust:** 1.80.0
- **Diesel:** 2.2.4 (CLI + crate)
- **Database:** PostgreSQL 16.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- **Operating System** WSL2 ubuntu

### Feature Flags

- **diesel:**

### What are you trying to accomplish?
I have created the following table by issuing this exact command:
```
CREATE TABLE IF NOT EXISTS public.reindex_checkpoints_1
(
    id bigserial NOT NULL,
    clustering_id bigint NOT NULL,
    interval_identifier text COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default" NOT NULL,
    inserted_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT reindex_checkpoints_1_pkey PRIMARY KEY (id)
)
```
But then when I run `diesel print-schema` I get the following error:
```
Diesel only supports tables with primary keys. Table `reindex_checkpoints_1` has no primary key
```
Which is incorrect.

I have tried completely dropping the table and recreating it, even under a different name. I've also tried creating the table in a few different ways with slightly different syntax, and through the UI, and I get the same error from diesel.

**Comment by weiznich** [comment]
That's strange. I tested this with the provided SQL and my local setup and it seems to work there with postgres 16.3 (although on fedora and not in WSL).

Could you execute the following query manually and provide the result: 

```sql
SELECT "information_schema"."key_column_usage"."column_name" FROM "information_schema"."key_column_usage" WHERE ((("information_schema"."key_column_usage"."constraint_name" = ANY(SELECT "information_schema"."table_constraints"."constraint_name" FROM "information_schema"."table_constraints" WHERE ("information_schema"."table_constraints"."constraint_type" = 'PRIMARY KEY'))) AND ("information_schema"."key_column_usage"."table_name" = 'reindex_checkpoints_1')) AND ("information_schema"."key_column_usage"."table_schema" = 'public')) ORDER BY "information_schema"."key_column_usage"."ordinal_position";
```

(That's what diesel-cli executes internally)

**Comment by whyando** [comment]
Okay it was a permissions issue, 
`GRANT ALL ON TABLE public.reindex_checkpoints_1 TO <user>` fixed it.

**Comment by whyando** [comment]
Thank you for looking into it though. Perhaps the error response is quite misleading right now in that failure case.

**Comment by weiznich** [comment]
@whyando Thanks for this fast response and good to hear that this is sorted out now.

As for the error response: I agree with you there, but I do not see any simple solution to make it easily better. The only thing that comes to my mind is querying permissions, which sounds kind of complicated. That written: I'm certainly open to suggestions and even more implementations there.
