### ISSUE TITLE
`.eq_any([["foo"]])` on `SqlType = Array<Text>` causes runtime error on Postgres

### ISSUE THREAD

**Issue by Ten0** [diesel-rs/diesel#4349]
### Versions

- **Diesel:** ce6fa0bd93877391665254d9bdb23a9c895902ef
- **Database:** Postgres

### Feature Flags

- **diesel:** postgres

## Problem Description
`array.eq_any(array_of_array)` doesn't work on Postgres, because Postgres doesn't have such a thing as "array of array". It has 2D array but ["2-D array is a different concept"](https://pgsql-general.postgresql.narkive.com/eJuaaIgQ/could-not-find-array-type-for-data-type-character-varying#post2).
This causes an error, so we should probably use the non-specialized ANSI `IN (...)` when dealing with arrays.

### What are you trying to accomplish?
```rust
table! {
    posts (id) {
        id -> Int4,
        // ...
        tags -> Array<Text>,
    }
}

#[test]
#[cfg(feature = "postgres")]
fn filter_array_by_in() {
    use crate::schema::posts::dsl::*;

    let connection: &mut PgConnection = &mut connection();
    let tag_combinations_to_look_for: &[&[&str]] = &[&["foo"], &["foo", "bar"], &["baz"]];
    let result: Vec<i32> = posts
        .filter(tags.eq_any(tag_combinations_to_look_for))
        .select(id)
        .load(connection)
        .unwrap();
    assert_eq!(result, &[] as &[i32]);
}
```

### What is the actual output?
```
called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "could not find array type for data type text[]")
```

### What is the expected output?
Either of:
- test passes, serializing as `IN ($1, $2, $3)` with `$1 = ["foo"]`...
- Doesn't compile, requiring an explicit writing (e.g. `.eq_any(`abc`).ansi()`) to tell it to use ANSI serialization

ATM AFAICT there's no way to even tell it to use ANSI serialization because of bounds here:
https://github.com/diesel-rs/diesel/blob/ce6fa0bd93877391665254d9bdb23a9c895902ef/diesel/src/expression/array_comparison.rs#L100-L103
which forbids the use of the ANSI implementation on `Pg` `Backend` (which seems weird since ANSI should always work, no?)

(NB: All of this is useful only to the extent to which indexing will work and this behaves reasonably even if there are 500 different values in there. I recall that we did tend to prefer `= ANY` maybe because of this but I may be mistaken here, was it only for statement caching ?)

### Steps to reproduce
https://github.com/Ten0/diesel/commit/d6c93fd2a8af99df9bc8dc362144e6f599c6030c

or dedicated working branch to fixing this:
```
cd diesel
git remote add Ten0 https://github.com/Ten0/diesel.git
git checkout array_eq_any
cd diesel_tests
DATABASE_URL="..." cargo test --no-default-features --features "postgres" -- filter_array_by_in --nocapture
```

**Comment by Ten0** [comment]
`= ANY (VALUES (ARRAY['foo']), (ARRAY['bar']))` works, so serializing as a VALUES subquery in the `Many` specialization would work...

**Comment by weiznich** [comment]
I've pushed #4350 with another approach to fix that problem, but I'm open to different solutions. 

As a more general note: I wonder if it would be meaningful (and possible) to have some sort of fuzzer that takes the documentation and keeps generating queries via the DSL and then checks if they compile and if they do not return an syntax error while executing them.

**Comment by Ten0** [comment]
> As a more general note: I wonder if it would be meaningful (and possible) to have some sort of fuzzer that takes the documentation and keeps generating queries via the DSL and then checks if they compile and if they do not return an syntax error while executing them.

I feel like it's probably fine if Diesel doesn't cover for mistakes people never make, and there ought to be some of those that the type system allows but the complexity of preventing isn't worth the probability of occurrence...
If this is true, then I'm not sure what would be a strategy to create a test system that would test only "relevant" cases.
