### ISSUE TITLE
Prosgresql conflicting implementations of trait

### ISSUE THREAD

**Issue by BingoCat886** [diesel-rs/diesel#4363]
### Versions

- **Rust:** 1.82
- **Diesel:** 2.2.4
- **Database:** prosgresql
- **Operating System** macos

### Feature Flags

- **diesel:** pg sql

## Problem Description

conflicting implementations of trait `expression::AsExpression<pg::types::sql_types::Record<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)>>` for type `(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)`
overflow evaluating the requirement `<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) as expression::Expression>::SqlType == pg::types::sql_types::Record<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)>`
overflow evaluating the requirement `<PgTuple<(<_ as expression::AsExpression<_>>::Expression,

**Comment by BingoCat886** [comment]
{"$message_type":"diagnostic","message":"conflicting implementations of trait `expression::AsExpression<types::sql_types::Record<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)>>` for type `(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)`","code":{"code":"E0119","explanation":"There are conflicting trait implementations for the same type.\n\nErroneous code example:\n\n```compile_fail,E0119\ntrait MyTrait {\n    fn get(&self) -> usize;\n}\n\nimpl<T> MyTrait for T {\n    fn get(&self) -> usize { 0 }\n}\n\nstruct Foo {\n    value: usize\n}\n\nimpl MyTrait for Foo { // error: conflicting implementations of trait\n                       //        `MyTrait` for type `Foo`\n    fn get(&self) -> usize { self.value }\n}\n```\n\nWhen looking for the implementation for the trait, the compiler finds\nboth the `impl<T> MyTrait for T` where T is all types and the `impl\nMyTrait for Foo`. Since a trait cannot be implemented multiple times,\nthis is an error. So, when you write:\n\n```\ntrait MyTrait {\n    fn get(&self) -> usize;\n}\n\nimpl<T> MyTrait for T {\n    fn get(&self) -> usize { 0 }\n}\n```\n\nThis makes the trait implemented on all types in the scope. So if you\ntry to implement it on another one after that, the implementations will\nconflict. Example:\n\n```\ntrait MyTrait {\n    fn get(&self) -> usize;\n}\n\nimpl<T> MyTrait for T {\n    fn get(&self) -> usize { 0 }\n}\n\nstruct Foo;\n\nfn main() {\n    let f = Foo;\n\n    f.get(); // the trait is implemented so we can use it\n}\n```\n"},"level":"error","spans":[{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel/src/expression/mod.rs","byte_start":7735,"byte_end":7847,"line_start":223,"line_end":226,"column_start":1,"column_end":39,"is_primary":false,"text":[{"text":"impl<T, ST> AsExpression<ST> for T","highlight_start":1,"highlight_end":35},{"text":"where","highlight_start":1,"highlight_end":6},{"text":"    T: Expression<SqlType = ST>,","highlight_start":1,"highlight_end":33},{"text":"    ST: SqlType + TypedExpressionType,","highlight_start":1,"highlight_end":39}],"label":"first implementation here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel/src/pg/types/record.rs","byte_start":3195,"byte_end":3455,"line_start":85,"line_end":89,"column_start":9,"column_end":86,"is_primary":true,"text":[{"text":"        impl<$($T,)+ $($ST,)+> AsExpression<Record<($($ST,)+)>> for ($($T,)+)","highlight_start":9,"highlight_end":78},{"text":"        where","highlight_start":1,"highlight_end":14},{"text":"            $($ST: SqlType + TypedExpressionType,)+","highlight_start":1,"highlight_end":52},{"text":"            $($T: AsExpression<$ST>,)+","highlight_start":1,"highlight_end":39},{"text":"            PgTuple<($($T::Expression,)+)>: Expression<SqlType = Record<($($ST,)+)>>,","highlight_start":1,"highlight_end":86}],"label":"conflicting implementation for `(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)`","suggested_replacement":null,"suggestion_applicability":null,"expansion":{"span":{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel/src/pg/types/record.rs","byte_start":4974,"byte_end":5027,"line_start":134,"line_end":134,"column_start":1,"column_end":54,"is_primary":false,"text":[{"text":"diesel_derives::__diesel_for_each_tuple!(tuple_impls);","highlight_start":1,"highlight_end":54}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":{"span":{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel/src/pg/types/record.rs","byte_start":4974,"byte_end":5027,"line_start":134,"line_end":134,"column_start":1,"column_end":54,"is_primary":false,"text":[{"text":"diesel_derives::__diesel_for_each_tuple!(tuple_impls);","highlight_start":1,"highlight_end":54}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null},"macro_decl_name":"diesel_derives::__diesel_for_each_tuple!","def_site_span":{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel_derives/src/lib.rs","byte_start":50544,"byte_end":50609,"line_start":1369,"line_end":1369,"column_start":1,"column_end":66,"is_primary":false,"text":[{"text":"pub fn __diesel_for_each_tuple(input: TokenStream) -> TokenStream {","highlight_start":1,"highlight_end":66}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}}},"macro_decl_name":"tuple_impls!","def_site_span":{"file_name":"/Users/tianlan/Documents/zoos/diesel/diesel/src/pg/types/record.rs","byte_start":550,"byte_end":574,"line_start":17,"line_end":17,"column_start":1,"column_end":25,"is_primary":false,"text":[{"text":"macro_rules! tuple_impls {","highlight_start":1,"highlight_end":25}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}}}],"children":[{"message":"overflow evaluating the requirement `<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) as expression::Expression>::SqlType == types::sql_types::Record<(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)>`","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"overflow evaluating the requirement `<PgTuple<(<_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as expression::AsExpression<_>>::Expression, <_ as

**Comment by weiznich** [comment]
Closed due to no response from the author. Feel free to add the requested information to reopen the issue.
