### ISSUE TITLE
Update documentation around syntex

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#439]
We have received complaints and state in our getting started guide that we're incompatible with the most recent versions of serde because we don't support the most recent version of syntex. However, the standard way to use syntex no longer involves the users depending on it directly, allowing for multiple versions to be used in the same code base. We should update our docs accordingly (see serde's docs for an example)

**Comment by killercup** [comment]
Actually, we will need to update the guide on how to use the codegen crate with macros 1.1 in stable Rust 1.15 instead soon :)

**Comment by beatgammit** [comment]
Rust 1.15 should be out this week, is there any preliminary documentation?

I tried compiling on the beta branch and I get compile errors on `diesel_codegen`: ("`#[feature]` may not be used on the beta channel") using the latest diesel_codegen 0.9.0 on crates.io and beta 1.15.0-beta.5 (built Jan 19). If I build from the latest git head, I get a different compile error, but in `infer_schema!`, so I guess it's just not published yet (I can file that compile error separately if you like).

**Comment by sgrif** [comment]
You'll need to use master if you're using 1.15 beta. The guide will be updated tomorrow.

**Comment by beatgammit** [comment]
Awesome. Well a new crate be pushed soon with support for stable Rust?

**Comment by killercup** [comment]
Yep, it'll be ready with Rust 1.15, so… less than 24 hours!

Jameson Little <notifications@github.com> schrieb am Do. 2. Feb. 2017 um
02:05:
