### ISSUE TITLE
style: schema.rs doesn't comply with rustfmt

### ISSUE THREAD

**Issue by AndreCostaaa** [diesel-rs/diesel#4405]
### Versions

- **Rust:** 1.80.1
- **Diesel:** 2.2.4 (cli)
- **Database:** Postgresql
- **Operating System** Linux

### Feature Flags

- **diesel:** N/A

## Problem Description

The `schema.rs` file created by diesel-cli when running a migration doesn't always comply with rustfmt

### What are you trying to accomplish?

I'm trying to use the diesel-cli to generate the migrations and the `schema.rs` file  

### What is the expected output?

Running `cargo fmt -- --check` should produce no errors.

### What is the actual output?

Depending on the number of tables, the `schema.rs` file is not formatted properly and thus resulting in an error when running cargo fmt

### Are you seeing any additional errors?

No

### Steps to reproduce

0. Setup a basic diesel and cargo project 

1. Generate a migration

```bash
diesel migration generate migration1
```

Put the following into your `migrations/XXX_migration1/up.sql

```sql
CREATE TABLE t0 (id SERIAL PRIMARY KEY);
CREATE TABLE t1 (id SERIAL PRIMARY KEY, t0_id INTEGER NOT NULL REFERENCES t0);
```

2. Run the diesel migration

```bash
diesel migration run
```
 
3. Add this on top of your `main.rs`

```rs
mod schema;
```

4. Run cargo fmt

```bash
cargo fmt -- --check 
```

Output:
```
Diff in XXX/src/schema.rs at line 15:
 
 diesel::joinable!(t1 -> t0 (t0_id));
 
-diesel::allow_tables_to_appear_in_same_query!(
-    t0,
-    t1,
-);
+diesel::allow_tables_to_appear_in_same_query!(t0, t1,);
``` 

You can checkout a test repository [here](https://github.com/AndreCostaaa/diesel-fmt-test)

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for opening this issue. Diesel cli emits a `@generated` which should instruct rustfmt to ignore this file. If that doesn't work this seems to be more a rustfmt issue and should be reported there. 

That written: I'm open to accept a PR that emits the correct formatting in this case. For larger schemas that already works but for only a few tables that doesn't seem to be perfect.

**Comment by AndreCostaaa** [comment]
> I'm open to accept a PR that emits the correct formatting in this case

Would spawning a `rustfmt` process from the `diesel-cli` after writting the `schema.rs` file be acceptable for you?

**Comment by weiznich** [comment]
If that works reliably with the patching mechanism it would be acceptable to just use rustfmt for this as long as its failure tolerant if rustfmt is not installed.

**Comment by AndreCostaaa** [comment]
Exactly what I had in mind. Will send a PR soon
