### ISSUE TITLE
Add custom schema support

### ISSUE THREAD

**Issue by compressed** [diesel-rs/diesel#447]
As discussed on gitter, I want to use custom schemas with diesel. I am using postgresql. My use case is that the tables I want to query on aren't in the `public` schema. For example, I want to query `schema_1.table_1` and `schema_1.table_2`, however currently, `infer_schema!` doesn't find them.

**Comment by drusellers** [comment]
I also use schemas outside of `public`.

**Comment by sgrif** [comment]
Macros 1.1 took up a lot of time, but this will be in the next release.

**Comment by durango** [comment]
I'm wondering if setting the `search_path` would alleviate this issue:

```sql
SET search_path=public,tiger,postgis;
```

On that note, it would be important to specify which schemas diesel should infer (inferring `tiger` or `postgis` would be a waste)

**Comment by NilsIrl** [comment]
I ran a migration which created tables inside of a schema and my `schema.rs` file is empty. What do I need to do in order for diesel to detect the tables in the other schema? (I am using postgresql)

**Comment by weiznich** [comment]
@NilsIrl Please don't comment on old issues to ask questions. Our issue tracker is no support forum. Use the gitter channel or the discussion forum to ask questions. And please include important information about your setup there as otherwise nobody will be able to answer your questions.

**Comment by NilsIrl** [comment]
Apologies, I thought it was appropriate to ask here considering that's where the feature was requested.

I created a dicussion here: https://github.com/diesel-rs/diesel/discussions/2990
