### ISSUE TITLE
Add documentation for binding to raw queries

### ISSUE THREAD

**Issue by shssoichiro** [diesel-rs/diesel#448]
If I have a circumstance where I want or need to write a raw query, I understand that diesel allows me to do this with the `sql` function. However, the API around binding to a `SqlLiteral` is confusing and the documentation is extremely limited. It would be very helpful to add one or two examples for how to bind a parameter to a raw query.

**Comment by sgrif** [comment]
`sql` isn't intended to work with bind parameters. For any case where bind parameters are likely to appear (e.g. anywhere that isn't special syntax for an additional clause or type of query), some combination of `sql_function!`, `infix_expression!`, `postfix_expression!` and `prefix_expression!` should be sufficient. If you give more details about what you're trying to do in gitter, I can help further.
