### ISSUE TITLE
Composite primary keys

### ISSUE THREAD

**Issue by jimmycuadra** [diesel-rs/diesel#450]
The `table!` macro should support composite primary keys and/or there should be documentation on how to do composite primary keys manually. I know this is on the radar, but there isn't an issue for it, so I'm opening this just to track it.

**Comment by killercup** [comment]
We landed (simple) composite key support for `table!` in #417 (currently only in master, will be in the next release). Can you try this and see if it works for you?

**Comment by jimmycuadra** [comment]
Looks like there was already an issue for it that I missed at #42 anyway. Closing this out.
