### ISSUE TITLE
diesel_codegen_syntex fails to build

### ISSUE THREAD

**Issue by paulhandy** [diesel-rs/diesel#451]
rustc version: rustc 1.13.0-nightly (4f9812a59 2016-09-21)
cargo version: cargo 0.13.0-nightly (9399229 2016-09-14)

Cargo.toml:

> [dependencies]
> diesel = "0.7.1"
> diesel_codegen = { version = "0.7.2", features = ["postgres"] }
 

cargo build error output:
>   Compiling diesel_codegen_syntex v0.7.2
> error[E0432]: unresolved import `syntax::attr::AttrMetaMethods`
>  --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/associations/mod.rs:2:5
>   |
> 2 | use syntax::attr::AttrMetaMethods;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AttrMetaMethods` in `syntax::attr`
> 
> error[E0432]: unresolved import `syntax::attr::AttrMetaMethods`
>  --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/update.rs:2:5
>   |
> 2 | use syntax::attr::AttrMetaMethods;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AttrMetaMethods` in `syntax::attr`
> 
> error[E0432]: unresolved import `syntax::attr::AttrMetaMethods`
>  --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/util.rs:3:5
>   |
> 3 | use syntax::attr::AttrMetaMethods;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AttrMetaMethods` in `syntax::attr`
> 
> error[E0308]: mismatched types
>   --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/util.rs:42:17
>    |
> 42 |                 ast::MetaItemKind::Word(ref value) => Some(str_to_ident(&value)),
>    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `syntax::ast::NestedMetaItemKind`, found enum `syntax::ast::MetaItemKind`
>    |
>    = note: expected type `syntax::ast::NestedMetaItemKind`
>    = note:    found type `syntax::ast::MetaItemKind`
> 
> error[E0308]: mismatched types
>   --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/associations/mod.rs:57:17
>    |
> 57 |                 MetaItemKind::Word(ref name) => str_to_ident(&name),
>    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `syntax::ast::NestedMetaItemKind`, found enum `syntax::ast::MetaItemKind`
>    |
>    = note: expected type `syntax::ast::NestedMetaItemKind`
>    = note:    found type `syntax::ast::MetaItemKind`
> 
> error[E0308]: mismatched types
>   --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/insertable.rs:36:54
>    |
> 36 |             meta_items.iter().map(|i| table_name(cx, i)).collect()
>    |                                                      ^ expected enum `syntax::ast::MetaItemKind`, found enum `syntax::ast::NestedMetaItemKind`
>    |
>    = note: expected type `&syntax::codemap::Spanned<syntax::ast::MetaItemKind>`
>    = note:    found type `&syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>`
> 
> error[E0308]: mismatched types
>   --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/update.rs:37:50
>    |
> 37 |             let table_name = try!(table_name(cx, &meta_items[0]));
>    |                                                  ^^^^^^^^^^^^^^ expected enum `syntax::ast::MetaItemKind`, found enum `syntax::ast::NestedMetaItemKind`
>    |
>    = note: expected type `&syntax::codemap::Spanned<syntax::ast::MetaItemKind>`
>    = note:    found type `&syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>`
> 
> error[E0308]: mismatched types
>   --> /home/thonx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_codegen_syntex-0.7.2/src/update.rs:38:62
>    |
> 38 |             let treat_none_as_null = try!(boolean_option(cx, &meta_items[1..], "treat_none_as_null"))
>    |                                                              ^^^^^^^^^^^^^^^^ expected struct `syntax::ptr::P`, found struct `syntax::codemap::Spanned`
>    |
>    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
>    = note:    found type `&[syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>]`
> 
> error: aborting due to 5 previous errors
> 
> error: Could not compile `diesel_codegen_syntex`.

I couldn't find anything like this in the currently open issues, so please forgive me if this is something already covered.

**Comment by Eijebong** [comment]
#426 I think this is related.
http://diesel.rs/guides/getting-started/ 
You can read the latest supported nightly here. You should use the 2016-08-18 one.

**Comment by paulhandy** [comment]
Thank you. I glazed over that part about the nightly version.

**Comment by killercup** [comment]
I guess this is solved then?
