### ISSUE TITLE
How to build a conditional query

### ISSUE THREAD

**Issue by TheNeikos** [diesel-rs/diesel#455]
Due to the fact that the `filter` method returns a new type I'm unable to create a 'dynamic' query. Basically I want to do something like this:

```rust
let mut query = submissions.limit(self.settings.limit));

if let Some(user) = self.submitter {
    query = query.filter(user_id.eq(user.id));
}

if let Some(n) = self.title {
    query = query.filter(title.like(n));
}

if let Some(desc) = self.description {
    query = query.filter(description.like(desc));
}

```

This fails to compile due to the fact that query gets typed right away and it might or might not change. 
Is this something that can be addressed? I'd rather not have `N!` code paths to run through.
A macro would be a suitable replacement, however I am not knowledgeable enough to create it.

**Comment by killercup** [comment]
One way to solve this is to box the query in each branch (with
`.into_boxed()`).

Marcel Müller <notifications@github.com> schrieb am So. 2. Okt. 2016 um
05:24:

**Comment by TheNeikos** [comment]
Hm, doing that gives me this error:

```
error[E0275]: overflow evaluating the requirement `<diesel::query_builder::BoxedSelectStatement<'_, (diesel::types::BigInt, diesel::types::BigInt, diesel::types::Timestamp, diesel::types::Timestamp, diesel::types::BigInt, diesel::types::Text, diesel::types::Text, diesel::types::Nullable<diesel::types::Timestamp>, diesel::types::Integer), models::schema::submissions::table, _> as diesel::boxed_dsl::InternalBoxedDsl<'_, _>>::Output`
   --> src/models/submission.rs:389:55
    |
389 |             query = query.filter(user_id.eq(user.id)).into_boxed();
    |                                                       ^^^^^^^^^^
    |
    = note: consider adding a `#![recursion_limit="128"]` attribute to your crate

```

Adding that attribute just raises it to 256 :v

**Comment by sgrif** [comment]
Yeah, you're correct. You'll need to box it *before* the branch, but you won't need to box it again in each branch. Once it's boxed it stays boxed forever.

**Comment by pka** [comment]
After an hour or two of trying to compose a query like this, I gave up and looked through all issues finding this solution on page 15 of the closed tickets

This deserves a hint in the documentation (or a more prominent one, in case it's already documented). The ability to compose queries programmatically in a readable way is a fundamental advantage of an ORM compared to raw SQL. Thanks for this great library!

**Comment by weiznich** [comment]
> This deserves a hint in the documentation (or a more prominent one, in case it's already documented)

It is already in the docs. For example [here](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed).
Do you have any suggestion where we may add a more prominent hint?

**Comment by pka** [comment]
What about a sentence in the Getting Started guide like "In cases where you want to conditionally modify a query, use [into_boxed](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed) to box the pieces of a query into a single type."

**Comment by dessalines** [comment]
Agree, conditional queries are extremely common, and this was hard to find.

**Comment by andreievg** [comment]
This tutorial might be helpful: https://github.com/andreievg/diesel-rs-dynamic-filters
