### ISSUE TITLE
A few of our tests are quite flaky

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#475]
Specifically the tests in https://github.com/diesel-rs/diesel/blob/master/diesel_codegen_shared/src/database_url.rs are failing intermittently. The fix is likely just to make sure each test has a uniquely named environment variable that it's working with.

**Comment by cyplo** [comment]
Hi ! Is it easy to detect flakyness locally, e.g. would just rerunning the suite couple of times locally give you intermittent failures ?

**Comment by sgrif** [comment]
Running it locally a few times should show failures yes

**Comment by cyplo** [comment]
I'm interested in fixing it, will try to get a PR on the weekend possibly
