### ISSUE TITLE
Mapping a newtype to its underlying type

### ISSUE THREAD

**Issue by jonysy** [diesel-rs/diesel#483]
Is there a way to map a newtype to its underlying type?

Example:

```
struct PostId(i32);

struct Post {
    id: PostId, // == `i32` when using diesel
    title: String,
}
```

**Comment by sgrif** [comment]
No, this isn't possible at the moment. #429 goes in that direction, but we're not sure if it's the direction we will take.

**Comment by goldenMetteyya** [comment]
I think that a useful case is when you define a type 

struct Foo([u8;32])

and want to pass this type Foo to a function that takes [u8; 32] and the compiler complains that types dont match when the underlying actually does. Maybe there can be an way to mark that its safe for the compiler to infer this.

**Comment by jonysy** [comment]
Hi Sean.

Kindly clarify what you mean by:
> ..but we're not sure if it's the direction we will take.

Are you referring to that particular direction or this feature in general? Are you not sure you want to add support for this in diesel?

Thanks.
