### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by ernestas-poskus** [diesel-rs/diesel#488]
Any plans to integrate Cassandra support ? If not do you see any integration impediments ?

There are few native and wrapper drivers available:
- https://github.com/madmaxio/rustcql
- https://github.com/tupshin/cassandra-sys-rs
- https://github.com/tupshin/cassandra-rs

**Comment by sgrif** [comment]
There are no plans at this time. Diesel is designed to allow for third party adapters to be written out of tree though. Feel free to drop by our gitter room if you are interested in pursuing that.

**Comment by lmtr0** [comment]
any news on this?

**Comment by weiznich** [comment]
@lmtr0 Please do not comment on old closed issues to ask for news. There is never anything new there if there is no new comment indicating that.
As outlined above: We do not plan to add additional adapters to diesel. You can write your own backend and connection implementation outside of diesel if you are interested in diesel support for Cassandra (or whichever other database system).
