### ISSUE TITLE
Bumping diesel to 0.8.1 in dependencies

### ISSUE THREAD

**Issue by Kerollmops** [diesel-rs/diesel#490]
The `diesel` and `diesel_codegen` as been bumped to 0.8.1 but the dependencies of `diesel_codegen` remained to `0.8.0`

**Comment by sgrif** [comment]
`0.8.0` is equivalent to `^0.8.0` which will resolve to `0.8.1`.

**Comment by Kerollmops** [comment]
[It's `0.8.0` and not `^0.8.0`](https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/Cargo.toml#L15)

**Comment by killercup** [comment]
Cargo treats plain version numbers as if there was a `^` in front of it. If
you want the exact version, you need to write `=0.8.0`.

Clément Renault <notifications@github.com> schrieb am Mi. 2. Nov. 2016 um
22:45:

**Comment by Kerollmops** [comment]
Ho ! ok ! My bad ! I didn't know this thing !
