### ISSUE TITLE
Mildly confusing line in getting_started_step_1

### ISSUE THREAD

**Issue by bronson** [diesel-rs/diesel#499]
In getting_started_step_1, the instructions say to "add the following four lines to the top of src/lib.rs".  Following this literally results in an uncompilable file:

```rust
#![feature(proc_macro)]

#[macro_use] extern crate diesel_codegen;

pub mod schema;
pub mod models;

#[macro_use] extern crate diesel;
extern crate dotenv;
```

`#[macro_use] extern crate diesel;` needs to come before `#[macro_use] extern crate diesel_codegen;` of course.

I'd submit a PR to add some wording but I didn't see where the getting-started file was located.

This didn't take long to figure out, just hoping to save others the trouble.

**Comment by bronson** [comment]
And the error is pretty darned confusing:

```
error: `#[derive]` for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)
 --> src/models.rs:1:10
  |
1 | #[derive(Queryable)]
  |          ^^^^^^^^^
  |
  = help: add #![feature(custom_derive)] to the crate attributes to enable

error: aborting due to previous error

error: Could not compile `diesel_demo`.
```

**Comment by bronson** [comment]
Same thing with `src/models.rs` in step 2, "We'll want a struct to use for inserting a new record."  It's not clear that the new code should integrate with the existing.

**Comment by killercup** [comment]
@bronson sorry for the short but still delayed answer; you can find the getting started code at <https://github.com/diesel-rs/diesel/tree/master/examples> and the website text at <https://github.com/sgrif/diesel.rs-website>

**Comment by bronson** [comment]
Thank you, I'll submit PRs there.
