### ISSUE TITLE
Rust enum to sql integer how to ?

### ISSUE THREAD

**Issue by sackery** [diesel-rs/diesel#503]

**Comment by weiznich** [comment]
There is #429 open, which add support for adding custom type mapping. This could be used to map an enum to an integer.
@sgrif stated in #483 he is not sure if he want to add support for this in diesel. I've extracted the corresponding code [here](https://github.com/weiznich/diesel-custom-type) so it could be used without landing this pull-request. (If needed I could also upload it to crates.io)

**Comment by killercup** [comment]
FYI tracking issue for Postgres' custom enum types is #343

**Comment by quadrupleslap** [comment]
Pointing out the obvious, it's easy to cast it into an integer with `as` and `match` it back if you wanted to, but that removes the guarantee that values always represent the variants of the enum.

**Comment by dbrgn** [comment]
I'd also like to request some documentation on this issue. I managed to implement `FromSqlRow` for a String based enum with the help from #429, but I can't get `AsExpression` working.

**Comment by dbrgn** [comment]
Finally got `AsExpression` to work: https://gist.github.com/dbrgn/9e88f54e23b4640bb3641734277a85dd

**Comment by sgrif** [comment]
You can also see how we're handling this in crates.io -- https://github.com/rust-lang/crates.io/blob/4082d4e49c0e24a4883f301cc299360d4b828aaf/src/dependency.rs#L162-L184 https://github.com/rust-lang/crates.io/blob/4082d4e49c0e24a4883f301cc299360d4b828aaf/src/dependency.rs#L54-L65

**Comment by sgrif** [comment]
Closing for the same reasons as https://github.com/diesel-rs/diesel/issues/343#issuecomment-352206453

**Comment by unordered** [comment]
Try this!

```rust
use diesel::{
    backend::Backend,
    deserialize::{self, FromSql},
    expression::{helper_types::AsExprOf, AsExpression},
    serialize::{self, Output, ToSql},
    sql_types::*,
    *,
};
use serde_repr::*;
use std::io::Write;

#[repr(i16)]
#[derive(Debug, Copy, Clone, Serialize_repr, Deserialize_repr, PartialEq, FromSqlRow)]
pub enum OrderStatus {
    A = 0,
    B = 20,
}

impl<DB> ToSql<SmallInt, DB> for OrderStatus
where
    DB: Backend,
    i16: ToSql<SmallInt, DB>,
{
    fn to_sql<W: Write>(&self, out: &mut Output<W, DB>) -> serialize::Result {
        (*self as i16).to_sql(out)
    }
}

impl AsExpression<SmallInt> for OrderStatus {
    type Expression = AsExprOf<i16, SmallInt>;

    fn as_expression(self) -> Self::Expression {
        <i16 as AsExpression<SmallInt>>::as_expression(self as i16)
    }
}

impl<DB> FromSql<SmallInt, DB> for OrderStatus
where
    DB: Backend,
    i16: FromSql<SmallInt, DB>,
{
    fn from_sql(bytes: Option<&DB::RawValue>) -> deserialize::Result<Self> {
        match i16::from_sql(bytes)? {
            0 => Ok(OrderStatus::A),
            20 => Ok(OrderStatus::B),
            int => Err(format!("Invalid order status {}", int).into()),
        }
    }
}
```
