### ISSUE TITLE
`IN` condition in Postgres

### ISSUE THREAD

**Issue by arnau** [diesel-rs/diesel#511]
Is there a way to create a query like the one below with the query builder?

```sql
SELECT id FROM foo WHERE id NOT IN (1, 3, 5);
```

**Comment by sgrif** [comment]
Looks like I forgot to add `NOT IN` when I added `IN`. If you're on PG I'd recommend using `.ne(any(array))`. I'll add `NOT IN` for SQLite in the next version though.

**Comment by arnau** [comment]
Ah, I didn't realise I could use `.ne(any(array))`. Thanks!
