### ISSUE TITLE
[Request] MySQL Support

### ISSUE THREAD

**Issue by logannc** [diesel-rs/diesel#514]
This is by far the most ergonomic and safe ORM Rust has to offer - but it's really missing out without MySQL support. What is the timeline for that? What would be needed to make that happen?

**Comment by sgrif** [comment]
Ugh.... Fiiiiiiiine. I cave.

**Comment by sgrif** [comment]
I will try to tackle this for the release after the next, which I will work on after I get back from holiday vacation. So late January.

**Comment by logannc** [comment]
:D

I'd be happy to help if I can. I need to take some more time to look at the code, but would copying the SQLlite implementation and adjusting it to work with MySQL be a decent place to start?

**Comment by sgrif** [comment]
No, Postgres is a better place to start. SQLite is fundamentally different.

**Comment by sbditto85** [comment]
👍

**Comment by sbditto85** [comment]
Any update on what you've done @logannc? Would it help to have someone else?

**Comment by sgrif** [comment]
MySQL support has been fully implemented, and will be released with Diesel 0.11.
