### ISSUE TITLE
Refactorings using macros in type position

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#521]
Since [Rust 1.13](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1130-2016-11-10) we can use macros in type position ([RFC #873](https://github.com/rust-lang/rfcs/blob/master/text/0873-type-macros.md)). With those, we should be able to refactor a bunch of thing, e.g. the impls of [EqAll](https://github.com/diesel-rs/diesel/blob/49e3cdc079ec80eb6962bb5e6ca4e6471653327d/diesel/src/expression/expression_methods/eq_all.rs#L16-L17).

**Comment by phungleson** [comment]
Hey mate, I am trying to tackle this but it seems more complicated than I initially thought.

Do you have any other examples rather than the one in RFC873? or any simple ideas that I can refer to, like how the macro type might look like?

**Comment by sgrif** [comment]
This was implemented by #617 and we didn't like the code. Variadics will eventually make this pointless anyway.
