### ISSUE TITLE
Migrations not supported on CockroachDB

### ISSUE THREAD

**Issue by jethrogb** [diesel-rs/diesel#522]
When running `diesel setup` from the getting started example with CockroachDB beta-20161201, I get this error:

```
thread 'main' panicked at 'Error creating timestamp helper functions for Pg: DatabaseError(__Unknown, "syntax error at or near \"OR\"\nCREATE OR REPLACE FUNCTION diesel_set_updated_at() RETURNS trigger AS $$\n       ^\n")', ../src/libcore/result.rs:788
```

**Comment by sgrif** [comment]
This is because CockroachDB doesn't support stored procedures. We can probably add a `skip-timestamp-helpers` feature or something and just not generate those functions.
