### ISSUE TITLE
AsChangeset works on a struct that only consists of primary keys on nightly

### ISSUE THREAD

**Issue by Drakulix** [diesel-rs/diesel#544]
Deriving AsChangeset works with the proc-macro code-generation, but not via syntex/macro generation, if `fields` turns out to be empty. This happens if the struct contains nothing but primary keys (e.g. n:m relation tables).

Having an AsChangeset implementation on such a struct is of course not very useful and should most likely not be supported. I just noticed this inconsistency and think it should be fixed.

**Comment by Eijebong** [comment]
This can be closed now that #1074 has landed.
