### ISSUE TITLE
Full document support?

### ISSUE THREAD

**Issue by sackery** [diesel-rs/diesel#545]

**Comment by killercup** [comment]
What do you mean by this? Can you maybe describe what you want to do and how you think diesel should help you with this?

**Comment by sackery** [comment]
Document in diesel.rs is so simple and not fully, it's just a guide.

**Comment by killercup** [comment]
Oh, you mean the documentation. Yeah, the guide doesn't describe everything.

You have seen the API documentation, right? It can be confusing in the
beginning, but contains a lot of detailed information on most of diesel's
features.

What are you missing the most? What are you trying to do that is not
documented? The plan is to add more guides for specific use cases of diesel
in the future.

sackery <notifications@github.com> schrieb am So. 18. Dez. 2016 um 06:01:

**Comment by killercup** [comment]
I haven't heard back, so I'm gonna close this. I have opened a new issue for implementing `#[deny(missing_docs)]`, though: #563.
