### ISSUE TITLE
Type alias is never used in infer_schema()

### ISSUE THREAD

**Issue by freiguy1** [diesel-rs/diesel#551]
I recently updated my project to diesel 0.9 from 0.5. I've migrated successfully, as there are no errors and it's working correctly, however I'm getting one particular warning which repeats 9 times when I build:

```
warning: type alias is never used: `BoxedQuery`, #[warn(dead_code)] on by default
 --> /builds/freiguy1/proj/db/src/schema.rs:1:1
  |
1 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate
```

I apologize if I missed some documentation on this. I'm using rust nightly-2016-12-18.

Thanks!

**Comment by killercup** [comment]
This has been recently fixed in master (have a look at the last two PRs
that were merged)! Can you give it a try and see if it works for you?

Ethan Frei <notifications@github.com> schrieb am Fr. 23. Dez. 2016 um 01:30:

**Comment by freiguy1** [comment]
thank you!
