### ISSUE TITLE
::diesel::types::Inet undefined or not in scope with feature "with-syntex"

### ISSUE THREAD

**Issue by mmacedoeu** [diesel-rs/diesel#553]
I have tried a modified getting_started_step_4 example with a pg Inet data type field. It got inferred from schema but it is ultimately undefined

**Comment by sgrif** [comment]
We don't currently support the inet type. You can find a list of all types that we currently have implemented in the core crate at http://docs.diesel.rs/diesel/types/index.html and http://docs.diesel.rs/diesel/pg/types/sql_types/index.html. Support for using `infer_schema!` with types added by third party crates is tracked by #88.
