### ISSUE TITLE
Insertable should allow Option on non null fields with default

### ISSUE THREAD

**Issue by mackeyja92** [diesel-rs/diesel#554]
The `Insertable` trait currently does not allow fields that are specified as `NOT NULL` in the database but with a `DEFAULT` to have `Option` defined in the model. 

For example, this model here would fail when using a postgres backend even though the database will automatically fill in the field. 

```rust
#[table_name = "todos"]
#[derive(Queryable, Insertable)]
pub struct Todo {
    id: Option<i32>,
    pub description: String,
}
```

With the SQL definition of this

```sql
CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  description VARCHAR
);
```

The above SQL generates the following schema with the field being `NOT NULL` and having a `DEFAULT`.

```
                                                     Table "public.todos"
   Column    |       Type        |                     Modifiers                      | Storage  | Stats target | Description
-------------+-------------------+----------------------------------------------------+----------+--------------+-------------
 id          | integer           | not null default nextval('todos_id_seq'::regclass) | plain    |              |
 description | character varying |                                                    | extended |              |
Indexes:
    "todos_pkey" PRIMARY KEY, btree (id)
```

**This should work not only for PKs but also any field that has a default in the schema.**

**Comment by killercup** [comment]
We talked on Gitter about this: [logs](https://gitter.im/diesel-rs/diesel?at=5862c150af6b364a2900eb77).

**Comment by sgrif** [comment]
Hm... I feel like this used to work in the past. It definitely is meant to work (with or without a default being present, which we currently don't/can't verify)
