### ISSUE TITLE
is it a best practice to call `establish_connection` for every request?

### ISSUE THREAD

**Issue by rbalicki2** [diesel-rs/diesel#555]
Happy to take this to an IRC channel/slack group, but couldn't find one. Not sure if rust-beginners is appropriate, either.

I'm writing a web app using diesel and rocket, and in every route handler I'm calling `establish_connection` (straight from the getting started guide). Is this unnecessary overhead? Should I store a single connection to a database somewhere, and reuse that one?

**Comment by killercup** [comment]
In production, you probably want to use connection pooling. Have a look at r2d2-diesel (and lazy_static). I think there is an iron-diesel crate, maybe you can have a look at how they did it.

We have a gitter.im channel (linked in the Readme; also works via IRC) if you want to say hello :)

**Comment by rbalicki2** [comment]
thank you!
