### ISSUE TITLE
Using filter on lower-cased columns

### ISSUE THREAD

**Issue by freiguy1** [diesel-rs/diesel#560]
I'm looking to perform a query similar to 

```sql
SELECT things FROM table1 where LOWER(table1.name) LIKE '%something%';
```

In rust with diesel, I get this close:

```rust
try!(table1::table.filter(table1::name.like(query)).load::<Table1>(&conn));
```

Is there a way I can use diesel to compare with LIKE against a lower case version of the columns?  Is regex an option? I'd prefer to not have to make another column which is the lower case version of an existing column.

Thanks!

**Comment by sgrif** [comment]
We don't have the `lower` function built in yet. I'd certainly accept a pull request that adds one. We provide the [`sql_function!`](http://docs.diesel.rs/diesel/macro.sql_function.html) macro as well which would allow you to just define the function locally like so:

```rust
sql_function!(lower, lower_t, (a: types::VarChar) -> types::VarChar);

try!(table1::table.filter(lower(table1::name).like(query)).load::<Table1>(&conn));
```
