### ISSUE TITLE
How to convert PgTimestamp to JSON?

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#575]
Whats a good way to convert a diesel::data_types::PgTimestamp to JSON, since it's not RustcEncodable?

**Comment by golddranks** [comment]
I used `chrono::DateTime<UTF>`, (you might have to use `NaiveDateTime`) in my model structs. It has the `to_rfc3339()` method, which outputs strings that is easily parseable in JavaScript. The pain in the ass is that `chrono::DateTime<UTF>` doesn't serialize to the rfc3339 format by itself, so you have to have some kind of workaround: for example a struct with `chrono::DateTime<UTF>` for fetching from the database, then convert that to struct that is identical to that but stores the timestamp as `String`, and then serialize that to JSON.

**Comment by golddranks** [comment]
Btw. I've issued an issue in `chrono` repo some time ago to highlight the awkwardness of serialization to JSON. https://github.com/lifthrasiir/rust-chrono/issues/115

**Comment by Boscop** [comment]
Thanks

**Comment by Boscop** [comment]
@golddranks Is this correct?
```rust
fn time_to_json(t: NaiveDateTime) -> String {
	DateTime::<UTC>::from_utc(t, UTC).to_rfc3339()
}
```
This results in a string like `"2017-01-06T09:27:39.833109+00:00"`.
(I set the postgres timezone to UTC whenever my server starts (so that now() returns the UTC time), and I use NaiveDateTime in my ORM structs, and store all times as UTC with the `timestamp` postgres type in the db.)

And then in js:
```js
moment(new Date(timeStr)).fromNow()
```
To show a post's relative time..

**Comment by golddranks** [comment]
I prefer using `timestamptz` in my schema, so I don't have to stick the timezone later on. That looks correct but don't take my word for it :D

**Comment by marcusball** [comment]
I don't know about using rustc_serialize, but if you use serde, I think you could use t[he `#[serde(serialize_with = "path")]` attribute](https://serde.rs/attributes.html#field-attributes) to specify the function that should serialize the timestamp field. You can then use the aforementioned `time_to_json` function, or something similar, to create the string for serialization handler.

**Comment by Boscop** [comment]
@marcusball Good to know, but right now I'm converting the row struct to an api view struct anyway, because not all fields should be exposed to the json api (such as users' email).

I want `now()` to be in UTC, so I do this on the start of my server:
```rust
database::connection().get().unwrap().execute("SET TIME ZONE 'UTC';").unwrap();
```
Would it be sufficient to do it once as a migration?
Or, should I do this more often than when the server starts? 
Let's say the connection from server to db breaks down for some reason (db restarts) should I execute this upon all reconnections?

**Comment by sgrif** [comment]
Not sure if there's still a question that needs answering here, but the structs prefixed with `Pg` are always representations of how PG sends something over the wire, not structs intended for use in application code. Using `chrono` or `SystemTime` is the proper way to do this.

**Comment by golddranks** [comment]
I think that the question in a sense was: which types to use in application code models that are compatible with PgTimestamp and easily convert to JSON.

To that question the answer seems now clear: use chrono::DateTime and Swede for serializing, that works out of the box.

**Comment by golddranks** [comment]
Serde, not Swede. Damn you smartphones XD

**Comment by Boscop** [comment]
I now use NaiveDateTime and store all my times in UTC.
