### ISSUE TITLE
Setting time zone on reconnect

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#582]
I use this code for my postgres connection:
```rust
use std::env;

use diesel::pg::PgConnection;
use r2d2_diesel::ConnectionManager;
use r2d2;

lazy_static! {
    static ref CONNECTION: r2d2::Pool<ConnectionManager<PgConnection>> = {
        let database_url = env::var("DATABASE_URL")
            .expect("DATABASE_URL must be set");
        let config = r2d2::Config::default();
        let manager = ConnectionManager::<PgConnection>::new(database_url);
        r2d2::Pool::new(config, manager).expect("Failed to create pool")
    };
}

pub fn connection() -> r2d2::Pool<ConnectionManager<PgConnection>> {
    CONNECTION.clone()
}
```
And when my server starts, I do this to set the time zone to UTC, because I want to store all times as UTC in a timestamp type (without timezone):
```rust
database::connection().get().unwrap().execute("SET TIME ZONE 'UTC';").unwrap();
```
(Times are converted to the user's time zone to relative times using [moment.js](http://momentjs.com/) on the frontend. Until then, they stay in UTC.)

Since timezone is a per session setting, my question is, what if the connection between postgres and my web server breaks down (e.g. postgres is restarted). 
How can I get notified via the ConnectionManager and set the time zone to UTC again? (Since it's a new session and the timezone will be reset to the local time zone.)

**Comment by sgrif** [comment]
This is probably a question to ask on the r2d2 repo, but it looks like you can set a connection customizer in the pool's configuration. http://sfackler.github.io/r2d2/doc/v0.7.1/r2d2/config/struct.Builder.html#method.connection_customizer
