### ISSUE TITLE
Postgres ON CONFLICT DO NOTHING

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#583]
How can I do something like:
```sql
INSERT INTO tags (name) values ('foo'), ('bar'), ('baz') ON CONFLICT DO NOTHING;
```
with diesel with postgres as backend.
Basically I want to insert all except the ones that are already in the table.
Without `ON CONFLICT DO NOTHING` it would unroll and not insert any if one is already in the table.

**Comment by killercup** [comment]
@sgrif worked on supporting `UPSERT` in November (`ON CONFLICT DO UPDATE`), which turned out to be pretty tricky.

Do you expect to get a return value with all the skipped rows?

**Comment by Boscop** [comment]
Not necessary. I just want to make sure that all tags are in the table after the query.
So I can get all their ids with the next query.

**Comment by sgrif** [comment]
Duplicate of #196

**Comment by emk** [comment]
We just ran into a case where we need this for our production application using a mix of `diesel`'s PostgreSQL backend and some `postgres`. I'm probably going to have to roll back the diesel conversion of several tables that I just did. :-/

How much work would it be for me to implement this?

**Comment by Eijebong** [comment]
@emk If you really need this, you can use custom psql functions with sql_function!
