### ISSUE TITLE
Linking on Windows

### ISSUE THREAD

**Issue by Timmmm** [diesel-rs/diesel#587]
It would be nice if the Readme explained how to compile this on Windows. As it stands I either get `ld: cannot find -lpq` or and equivalent error for `pq.lib` depending on whether I'm using the `-msvc` or `-gnu` toolchains. It actually fails when compiling `diesel_codegen`.

I installed PostgreSQL using the BigSQL windows installer, and it put `libpq.a` and `libpq.dll` in `C:\Program Files\PostgreSQL\pg96\lib` but I have no idea how to tell cargo to look there and google did not help.

**Comment by Cobrand** [comment]
You should probably copy/paste libpq.a and .dll in C:\<where you installed rust>\lib\rustlib\x86_64-pc-windows-gnu\lib\
if you don't want to copy the dll, you could edit $HOME/.cargo/config so that the linker knows where to lookup your dll, or you could specify the lookup directly in your cargo command line, like so :

`cargo rustc --release -- -L C:\\Program Files\\PostgreSQL\\pg96\\lib`

I am on linux myself so I can't say that these work for sure (at least the first one should), but at least it's something

**Comment by Timmmm** [comment]
I also found that the [instructions in pq-sys](https://github.com/sgrif/pq-sys) worked, specifically set an environment variable `LIB_PQ_DIR=C:\Program Files\PostgreSQL\pg96\lib` worked. You have to do `cargo clean` after setting it.

How do I edit `.cargo/config`? Something like this?

```
[build]
rustflags = ["-L" "C:/Program Files/PostgreSQL/pg96/lib"]
```

**Comment by Cobrand** [comment]
I edited my post

**Comment by Timmmm** [comment]
Ah this did the trick:

```
[target.x86_64-pc-windows-msvc.gnu]
rustc-link-search = ["C:\\Program Files\\PostgreSQL\\pg96\\lib"]
```

No need for the `rustc-link-lib`.

**Comment by sgrif** [comment]
Looks like this has been resolved. You can also do this by adding the PG directory to your `PATH`, there's an executable in the PG install directory which does this for you as well.

**Comment by leocavalcante** [comment]
Just a heads up for people who ended here like me, `config` should be:
```toml
[target.x86_64-pc-windows-msvc.pq]
rustc-link-search = ["C:\\Program Files\\PostgreSQL\\12\\lib"]
rustc-link-lib = ["libpq"]
```
With `libpq` instead of `pq`.

**Comment by TeamDman** [comment]
Came across this trying to run

```pwsh
cargo install diesel_cli --no-default-features --features postgres
```

Adding to $env:PATH the following did NOT help

```
C:\Program Files\PostgreSQL\17\lib
C:\Program Files\PostgreSQL\17\bin
```

(I did validate that the `.lib` file it was complaining about did exist in the `lib` dir.)

Instead, I re-read the docs and just followed the instructions from there instead lol

https://diesel.rs/guides/getting-started

```
cargo install cargo-binstall
cargo binstall diesel_cli
```

**Comment by ZelCloud** [comment]
This is still an issue with postgres 17....

**Comment by weiznich** [comment]
I'm locking this issue now as this is long answered and not the right place to discuss your problems about your local development setup.
If you feel that you still have this problem I recommend rereading the [Installing Diesel CLI](https://diesel.rs/guides/getting-started.html#installing-diesel-cli) section of the getting started guide, especially the "A note on installing diesel_cli" box. If that doesn't answer your questions you are welcome to open a [new discussion thread](https://github.com/diesel-rs/diesel/discussions/new?category=q-a) in our discussion forum. Just make sure to include all details about your system setup (which operating system, which environment variables are set, how is libpq installed, how does your `Cargo.toml` file look like).
