### ISSUE TITLE
diesel::migrations::run_migrations has a weird type signature

### ISSUE THREAD

**Issue by jethrogb** [diesel-rs/diesel#593]
`List: IntoIterator<Item=M>, M: Deref<Target=Migration>` means that you can't pass in a slice of  `&Migration`. Arrays don't implement IntoIterator. This means you have to allocate a container of references, but that's not possible because references passed in need to be 'static. So, you need to pass in a container of boxes.

**Comment by weiznich** [comment]
It's working without the need of having a box. `Iterator` itself implements `IntoIterator`, therefore it is sufficient to call `.iter()` on the array.
See the [`embedded_migration`](https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/src/embed_migrations.rs#L11-L73) code for an example. (In special [line 56](https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/src/embed_migrations.rs#L56))

**Comment by jethrogb** [comment]
That only works because the references there are `'static`. The `Box` is necessary for the implicit `'static` bound on `M`.
