### ISSUE TITLE
[feature request] support domains

### ISSUE THREAD

**Issue by derekdreery** [diesel-rs/diesel#595]
Here is an [explanation of domains](https://www.postgresql.org/docs/9.1/static/sql-createdomain.html). They are used for custom data types and are constructed from existing data types with optional constraints. 

e.g. I want to use the following domain
```sql
-- Domain: public.gender

CREATE DOMAIN public.gender
  AS character(1)
  COLLATE pg_catalog."default"
  DEFAULT 'U'::bpchar
  NOT NULL
  CONSTRAINT gender_check CHECK (VALUE = 'M'::bpchar OR VALUE = 'F'::bpchar OR VALUE = 'U'::bpchar OR VALUE = 'O'::bpchar);
COMMENT ON DOMAIN public.gender
  IS 'An enum type to represent gender';

```

They provide additional consistency within a database. Currently, using `infer_schema` errors on `unresolved type 'diesel::types::Gender'` in the above example.

**Comment by derekdreery** [comment]
A first step in pseudecode would be (in infer_schema)
```
for column in columns:
    while column is domain
        column = column.base_type
    ... carry on as usual
```

**Comment by sgrif** [comment]
Certainly for the cases covered by that pseudocode this seems completely reasonable to add

**Comment by derekdreery** [comment]
I've thought about this some more and I'm not sure if what I suggested is better than implementing a custom data type (I think I saw `ToSql` and `FromSql` in the source). I'm not sure what the best solution.

**Comment by sgrif** [comment]
So I don't think I want to add support for "treat domain type as its base type". That check constraint you've provided means that the range of values that can be serialized differ from those of the base type. In this case you can create `struct MyType;`, and implement a bunch of traits [example from our test suite](https://github.com/diesel-rs/diesel/blob/adc6db3f74eedaa34a0694759cccc29b95ada052/diesel_tests/tests/custom_types.rs). This is a bit verbose right now, it's going to be a focus of 1.1. #162 is the tracking issue for that.

Types that aren't in `diesel::types` can be used in `table!` by doing:

```rust
table! {
    use diesel::types::*;
    use my_types::*;

   foo {
        id -> Integer,
        bar -> MyType,
    }
}
```
