### ISSUE TITLE
Doc contains broken links

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#600]
The [doc](http://docs.diesel.rs/diesel/index.html) contains broken links, e.g. the second link on that page for `AsChangeset` (the first one works).
Maybe others are affected too (depending on the cause).

**Comment by beatgammit** [comment]
I also noticed that the link to `update` in IncompleteUpdateStatement is broken as well (I'm guessing it should be `update_statement`? I think this one is because something was renamed.

**Comment by theduke** [comment]
I just tested the docs at http://docs.diesel.rs/diesel/index.html with a [linkchecker](https://github.com/linkcheck/linkchecker).

It reports no broken links, so I think this can be closed.

**Comment by killercup** [comment]
Nice. Thanks, @theduke!

We currently cheated this issue by using absolute URLs (well, absolute paths) in a few places. This is good for now, but we should revisit this when a better solution (e.g. <https://github.com/rust-lang/rfcs/pull/1946>) is available.
