### ISSUE TITLE
Update to serde_json 0.9

### ISSUE THREAD

**Issue by dtolnay** [diesel-rs/diesel#601]
I noticed that https://github.com/diesel-rs/diesel/pull/561 merged recently and is using serde_json 0.8. The serde_json::Value enum is much nicer to work with in 0.9, including easy indexing `value["address"]["city"]` and a `json!` macro for constructing them in a nice way.

Release notes: https://github.com/serde-rs/json/releases/tag/v0.9.0

**Comment by killercup** [comment]
Shouldn't be too much work.

cc @emk

**Comment by sgrif** [comment]
If we're able to do a version range that supports both without much additional work that would be preferable
