### ISSUE TITLE
Add #[must_use] for warnings

### ISSUE THREAD

**Issue by durango** [diesel-rs/diesel#609]
@sgrif: `I should add a #[must_use] on queries to prevent that mistake. Anyone mind opening an issue?`

@sgrif: `Making query.filter(name.like(user.name)); warn`

**Comment by alexcameron89** [comment]
I think this is fixed and good to close.

**Comment by sgrif** [comment]
Yup. Thanks!

**Comment by TimNN** [comment]
Is this really fixed? The one PR linking this issue only mentions `select` and `filter` and also states:

> But we should probably also add this to/think about insert, update and delete before we close that issue.

(I also just spend some time trying to figure out why my `update` wasn't executing until I noticed I was missing an `.execute` when adding an `diesel::debug_sql`).

**Comment by sgrif** [comment]
Looks like we need an annotation on `UpdateStatement` and friends. Feel free to open a PR

**Comment by AndrewSpeed** [comment]
I'm happy to put a PR up for this, if no one else is working on it

**Comment by weiznich** [comment]
@AndrewSpeed Feel free to take it. If there is any problem just ask here or (preferable) in our gitter channel.
