### ISSUE TITLE
Update libsqlite3-sys dependency

### ISSUE THREAD

**Issue by SergioBenitez** [diesel-rs/diesel#610]
I'd like to use the latest version of `libsqlite3-sys` alongside Diesel in a workspace. Cargo requires that only a single version of a native library be linked to at once. Because Diesel depends on `0.4` and the latest version is `0.6.2`, the workspace does not test successfully with `cargo test --all`.

Any chance Diesel could upgrade to the latest version of `libsqlite3-sys`?

**Comment by killercup** [comment]
Well, that was easy :)
