### ISSUE TITLE
Multiple foreign keys with #[belongs_to], conflicting implementations of trait

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#616]
I have a table `posts`, and every post has an author (`user_id`) and a possible parent post that it replies to:
```rust
#[derive(Queryable, Identifiable, Clone, Associations, Debug)]
#[belongs_to(User)]
#[belongs_to(Post, foreign_key="parent")]
pub struct Post {
	pub id: i64,
	pub user_id: i64,
	pub parent: Option<i64>,
	// ...
}
```
But I get:
> error[E0119]: conflicting implementations of trait `diesel::SelectableExpression<diesel::query_source::InnerJoinSource<models::schema::__diesel_infer_schema::infer_posts::posts::table, models::schema::__diesel_infer_schema::infer_posts::posts::table>, diesel::types::BigInt>` for type `models::schema::__diesel_infer_schema::infer_posts::posts::columns::id`:

What's the correct way to declare multiple foreign keys for this kind of usecase?

**Comment by Eijebong** [comment]
I don't think you can join more than 2 tables for now, have a look at #89

**Comment by sgrif** [comment]
@Eijebong You can't join to more than two tables in a single query, but having multiple associations on a single model is definitely supported. This is a bug.

**Comment by sgrif** [comment]
Ah, I see what's going on now. The issue isn't that there are multiple associations, it's that this is a self-referential association.

**Comment by Boscop** [comment]
Yeah, posts can have a parent post that they reply to.
Will it be possible in the future to write `Post::belonging_to(&post)` for a self-referential association like this?

**Comment by sgrif** [comment]
If by "Will it be possible in the future" you mean "is this a thing that I think is reasonable to do and want to support eventually?", then the answer is yes. If you mean "is this a thing you are actively working on and have a concrete timeline for?" then the answer is no

**Comment by sgrif** [comment]
As I was writing that I realized this is literally just an if statement in codegen. I'm 99% certain the only problem with it is the invocations of `select_column_workaround!`. This should be trivial to support.

**Comment by Boscop** [comment]
Yay!

**Comment by LucaCappelletti94** [comment]
I am getting this same problem in Diesel `2.1.6`, is it possible a regression happened?
