### ISSUE TITLE
infer_schema! errors when column is the same name with the table it contains

### ISSUE THREAD

**Issue by ivanceras** [diesel-rs/diesel#624]
Table which has a column name same to the table such as

```sql
CREATE TABLE message(
id serial PRIMARY KEY NOT NULL,
message character varying
);
```

will error with:

```rust
error[E0252]: a type named `message` has already been imported in this module
 --> src/schema.rs:3:1
  |
3 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | |
  | previous import of `message` here
  | already imported
```
A workaround is to simply not use a column with the same name as the table, such as
```sql
CREATE TABLE message(
id serial PRIMARY KEY NOT NULL,
body character varying
);
```
This is a minor issue, but the rust error message is a bit misleading.

**Comment by sgrif** [comment]
I think the specific source of this error is likely the `dsl` module.

```rust
mod $table_name {
    pub struct table;

    mod columns {
        // ...
    }

    mod dsl {
        pub use super::table as $table_name;
        pub use super::columns::*;
    }
}
```

In theory we could just skip generating the dsl module if there's a column with the same name as the table. That is potentially even more confusing than an error though. If nothing else, giving a more helpful error message is certainly the easiest thing to do here.

**Comment by killercup** [comment]
Hm. To solve this, you'll either need to

- adjust the `table!` macro to find—at expansion time—column names that equal the table name (not even sure if you can encode that as macro), or
- adjust the schema inference (codegen) to return an error there (or maybe rename the column).
