### ISSUE TITLE
Allow use of `uuid` 0.4.0 for compatibility with latest stable serde

### ISSUE THREAD

**Issue by emk** [diesel-rs/diesel#628]
Hello! I am working to upgrade one of our Rust projects to the latest `diesel` and `serde`, but the latest `serde` only seems to work with `uuid` 0.4.0, and `diesel` only supports `uuid` 0.3.1. I think it should just be possible to allow either version of `uuid`, but I'm not quite sure how to verify that.

**Comment by killercup** [comment]
We have a bunch of dependencies that allow ranges of versions. The easiest way is to just open a PR which increases uuid's version range to ≤0.5 and see what happens on CI :)

(I'm not sure how extensive our tests for this are. Maybe you can also add an integration tests using both serde and uuid?)

**Comment by emk** [comment]
Looks good!

I see this has been fixed on `master` and tagged for 0.10.1, but I don't think 0.10.1 has been published to crates.io yet.

**Comment by sgrif** [comment]
Whoops, I didn't think 0.10.1 affected the core crate. I will release now.

**Comment by emk** [comment]
Thank you! I've just successfully upgraded serde and it works fine with diesel's UUID support again. :+1:
