### ISSUE TITLE
Diesel not bump chrono to 0.3.0!

### ISSUE THREAD

**Issue by sackery** [diesel-rs/diesel#648]

**Comment by Eijebong** [comment]
https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L15

Yes it did :) But only on master.

**Comment by sackery** [comment]
So must to fallback to 0.2

**Comment by killercup** [comment]
I don't see anything we can do here, except release a new version soon. The reason this is not in 0.10.1 is that switching to chrono 0.3 is a breaking change for everyone who uses chrono 0.2. So, it'll end up in the 0.11 release. Until then, you'll have to depend on the git master version if diesel.

**Comment by sackery** [comment]
@killercup how to use github version

**Comment by killercup** [comment]
Like this http://doc.crates.io/specifying-dependencies.html#specifying-dependencies-from-git-repositories
