### ISSUE TITLE
Conditional order?

### ISSUE THREAD

**Issue by fivethousand** [diesel-rs/diesel#651]
Is there a way to allow for queries with a conditional order?

Example (does not compile):
```
let order = match order_string {
  "id" => id,
  "name" => name,
  "age" => age,
  _ => id
};
let results = users.order(order).load::<User>(&connection);
```

Do we really have to duplicate like this?
```
let results = match order_string {
  "id" => users.order(id).load::<User>(&connection),
  "name" => users.order(name).load::<User>(&connection),
  "age" => users.order(age).load::<User>(&connection)
  _ => users.order(id).load::<User>(&connection)
};
```

**Comment by sgrif** [comment]
You'll need to box either the order or the whole query. See the examples in the docs [here](http://docs.diesel.rs/diesel/expression/expression_methods/global_expression_methods/trait.ExpressionMethods.html#method.asc) and [here](http://docs.diesel.rs/diesel/prelude/trait.BoxedDsl.html)
