### ISSUE TITLE
Final steps for MySQL support

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#653]
We're close enough to being done and the remaining items are small/scattered enough I'd like to document them here in case anyone wants to take a swing at them.

- [x] Separate the PG/MySQL implementations of `determine_column_type` in codegen, fix the MySQL implementation to convert `int` -> `integer`, `tinyint(1)` -> `bool`, strip parens otherwise
- [x] Support MySQL in Diesel CLI
- [x] Enable MySQL on Travis
- [x] Remove the cfg flag from as many integration tests as possible that are currently not running for MySQL because they modify schema inside of a transaction
- [ ] Implement timestamp helpers
- [x] Implement prepared statement caching
- [x] Support `SystemTime` and chrono

**Comment by sgrif** [comment]
#657 fixes item 1

**Comment by sgrif** [comment]
Timestamp helpers can wait for now.

**Comment by diggyk** [comment]
I know the helpers are not ready, but can timestamp or i64 be used at all at the moment?  I'm having trouble with a struct that I want to use as Insertable:

#[derive(Insertable)]
   |          ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `i64`
