### ISSUE TITLE
Support: Unexpected null for non-null column in tutorial

### ISSUE THREAD

**Issue by Aaronepower** [diesel-rs/diesel#670]
I get "Unexpected null for non-null column" when running `diesel migration redo` after creating the migration scripts during the Getting Started tutorial.

**Comment by sgrif** [comment]
Can you be more specific? Can you give the output of `diesel --version`? Are you running against Postgres? Can you give the full error message you receive (and possibly run with `RUST_BACKTRACE=1`? Are the steps that you followed approximated by the following shell commands?

```
cargo install diesel_cli
diesel setup
diesel migration generate create_posts
echo "CREATE TABLE posts (...)" > migrations/xxx_create_posts/up.sql
echo "DROP TABLE posts;" > migrations/xxx_create_posts/down.sql
diesel migration run
diesel migration redo
```

**Comment by Aaronepower** [comment]
@sgrif I did not run `diesel migration run` the guide doesn't say to?

**Comment by sgrif** [comment]
> We can apply our new migration with diesel migration run. It's a good idea to make sure that down.sql is correct. You can do a quick sanity check by doing diesel migration redo, which will revert and reapply the latest migration.

Still, you shouldn't get an error from omitting `diesel migration run`. I'll see if I can reproduce.

**Comment by Aaronepower** [comment]
Ahh, I couldn't see the first command. With `diesel migration run` it works.

**Comment by sgrif** [comment]
I was able to reproduce the issue at least. It shouldn't error in this case. I'll open a separate issue to track.
