### ISSUE TITLE
Add support for nullable arrays with infer_schema!.

### ISSUE THREAD

**Issue by XAMPPRocky** [diesel-rs/diesel#690]
Currently `infer_schema!` generates the this schema from this psql. Which is incorrect since the elements of the array could be null.

### Sql
```
CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body timestamptz[7] NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 'f'
)
```

### Generated schema
```
table! {
    posts (id) {
        id -> Int4,
        title -> Varchar,
        body -> Array<Timestamptz>,
        published -> Bool,
    }
}
```

**Comment by sgrif** [comment]
To clarify, I want to continue to have the generated type be `Array<Timestamptz>`, but make sure that deserializing to `Vec<Option<NaiveDateTime>>` deserializes successfully. Even though considering it to be `Array<Timestamptz>` is technically incorrect, as it could in theory have a null in there, I want to provide some flexibility here. There is no way to represent whether the elements of an array can or cannot be null in postgres.

**Comment by phiresky** [comment]
Since 2.0, Arrays always generate Array<Nullable<X>>. See https://diesel.rs/guides/migration_guide.html#2-0-0-nullability-of-array-elements

**Comment by weiznich** [comment]
Thanks for the headsup. We should have closed that issue a while ago.
