### ISSUE TITLE
Feature Request: Add network address support for Postgresql

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#719]
Hi, diesel developers.
I'm using diesel at work and need to handle network addresses for better functionalities of our product.
You know PostgreSQL supports network address types. CF [PostgreSQL: Documentation: 9.6: Network Address Types](https://www.postgresql.org/docs/current/static/datatype-net-types.html).
Is it possible to support network address types on diesel? It doesn't seem MySQL and SQLite support it, so it will be a Pg only feature.

As it seems there aren't address range types neither in rust std nor crates.io, you may need to define enums such as:

```rust
use std::net::{Ipv4Addr,IpV6Addr}
enum Inet {
  Ipv4(Ipv4Addr, [u8; 4]),
  Ipv6(Ipvv6Addr, [u8; 16]),
}
```

MacAddress exits in crates.io CF https://docs.rs/eui48/0.1.0/eui48/struct.MacAddress.html .

**Comment by KeenS** [comment]
Er.. subnetmask can be represented in `u8`, no need to have the same bits as addresses.

**Comment by Eijebong** [comment]
I think everything has been implemented now :)

Feel free to reopen if we missed something

**Comment by KeenS** [comment]
No problem at all. Thank you.
