### ISSUE TITLE
Is it possible to set a column to its default value during update?

### ISSUE THREAD

**Issue by stearnsc** [diesel-rs/diesel#725]
I don't feel like this is the best place for these sorts of questions, but I'm not sure what the right place is, so feel free to redirect me.

I have a table with a column with a default value. I know on insert, I can just leave that column out of my insertable type, and it will take the default value. Is there a way to "reset" it to the default value via update?

**Comment by sgrif** [comment]
A good place to ask questions is in gitter. There's a link in the README. There's not a way to set a column to its default right now, but it's something we're exploring.
