### ISSUE TITLE
Additional issues with `r2d2-diesel` and MySQL

### ISSUE THREAD

**Issue by kardeiz** [diesel-rs/diesel#728]
Thanks for [PR 727](https://github.com/diesel-rs/diesel/pull/727) and the new release (`0.11.1`)! Your speed and willingness to help is amazing!

Unfortunately, I'm encountering further issues when using r2d2 with MySQL. Whenever I try to run a query, like:

    users::table.limit(5).load::<User>(&*conn).expect("Users load failed")

I get 

    DatabaseError(__Unknown, "Commands out of sync; you can\'t run this command now")

When I get a connection directly using `MysqlConnection::establish`, everything works fine.

I dug around a little bit, and it is definitely related to the query in the `is_valid` health check. I put together an alternate impl for `::r2d2::ManageConnection` where `is_valid` always returned `Ok(())`, and it worked fine. (Of course, that is not a viable solution for the managed connection.)

**Comment by sgrif** [comment]
I suspect we need to move https://github.com/diesel-rs/diesel/blob/2d6f6b73eb126e5716fc66d152c29b778b568450/diesel/src/mysql/connection/raw.rs#L98-L102 to https://github.com/diesel-rs/diesel/blob/2d6f6b73eb126e5716fc66d152c29b778b568450/diesel/src/mysql/connection/raw.rs#L82. Testing will be a bit of a pain. I will explore it further tomorrow.

**Comment by kardeiz** [comment]
@sgrif, I think this just has to do with not consuming/flushing the query result. If I change

    conn.execute("SELECT 1").map(|_| ()).map_err(Error::QueryError)

to

```
sql::<::diesel::types::Bool>("SELECT 1")
    .get_result::<bool>(conn)
    .map(|_| ())
    .map_err(|_| Error::QueryError)
```

it works fine.

I don't know if this is the most efficient way to do a health check. MySQL has a ping mechanism, but I don't know all the considerations around it, and it wouldn't work for a generic `Connection` in `r2d2-diesel`. 

Or maybe there is just some way to flush/drop the row/value without using it?

**Comment by Ameobea** [comment]
I'm getting this same issue; unable to perform any queries using r2d2-diesel and MySQL.  Is there a fix on the radar for this?  I've tried to look into a solution on my own but I'm very unfamiliar with diesel and databases in general.
