### ISSUE TITLE
`diesel` as a dependency does not compile when Postgres ist not installed

### ISSUE THREAD

**Issue by kud1ing** [diesel-rs/diesel#736]
I want to use Diesel with Sqlite only:

```
cargo test
   Compiling pq-sys v0.3.2
error: failed to run custom build command for `pq-sys v0.3.2`
process didn't exit successfully: `/Users/lenny/Code/ts/target/debug/build/pq-sys-ac5f013e7abb629c/build-script-build` (exit code: 101)
--- stdout
wrapper.h:1:10: fatal error: 'libpq-fe.h' file not found, err: true

--- stderr
wrapper.h:1:10: fatal error: 'libpq-fe.h' file not found
thread 'main' panicked at 'Unable to generate bindings for libpq: ()', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sgrif** [comment]
When you say "diesel" do you mean `diesel_cli`? If so, you should install it with `cargo install diesel_cli --no-default-features --features postgres`. If you're referring to the `diesel` crate itself, it doesn't rely on postgres unless you have `features = ["postgres"]` in your Cargo.toml.

**Comment by kud1ing** [comment]
Sorry, I copied the example with the Postgres feature enabled here.

**Comment by sgrif** [comment]
Sorry, I don't fully understand what you mean. Do you still need help, or did that comment resolve the issue for you?

**Comment by kud1ing** [comment]
No thanks, I am fine. The issue regarding the CLI maybe could be mentioned in the guide.

**Comment by sgrif** [comment]
Yes, we will be revamping the getting started guide so that it has a SQLite and MySQL specific page. I'll mention it once we do that.
