### ISSUE TITLE
diesel_cli fails to install

### ISSUE THREAD

**Issue by leshow** [diesel-rs/diesel#737]
I'm trying to use diesel for the first time, I didn't get very far, `cargo install diesel_cli` fails to install with

```
   Compiling aster v0.38.0
   Compiling quasi v0.29.0
   Compiling quasi_codegen v0.29.0
   Compiling bindgen v0.22.0
   Compiling mysqlclient-sys v0.1.2
   Compiling pq-sys v0.3.2
error: failed to run custom build command for `pq-sys v0.3.2`
process didn't exit successfully: `/tmp/leshow/cargo-install.8wr9zs4ecU7k/release/build/pq-sys-711360ba9ed09407/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of \'libclang.so\', set the LIBCLANG_PATH environment variable to a path where one of these files can be found"', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v0.11.0`, intermediate artifacts can be found at `/tmp/leshow/cargo-install.8wr9zs4ecU7k`

Caused by:
  build failed
```

do I need to have clang installed?

**Comment by sgrif** [comment]
Diesel CLI 0.11 requires that you have libclang and lvm installed. You can find more details [here](https://github.com/servo/rust-bindgen#installing-clang-39)

(This has also caused a ton of issues and I'll be reverting it later tonight or some time tomorrow if you don't feel like installing those)

**Comment by leshow** [comment]
Ah, thanks. I was following along in [getting started](http://diesel.rs/guides/getting-started/) and it wasn't listed there.

Out of curiousity, what are you using clang for? There's no C in the project.

**Comment by Eijebong** [comment]
pq-sys is generating bindings for postgres at compile time and uses bindgen for that. Bindgen requires clang.
