### ISSUE TITLE
Obsolete reference to TransactionError::UserReturnedError in docs

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#750]
See: https://github.com/diesel-rs/diesel/blob/6b8d35c48db7e74384af02248730262929988cfa/diesel/src/connection/mod.rs#L33-L36

Should probably also add an example when updating this.

**Comment by Eijebong** [comment]
https://github.com/diesel-rs/diesel/commit/6a932c3e2f24ced7a61906d6737376ed0218b423

This is not true anymore. We still need an example though
