### ISSUE TITLE
Add support on ColumnInformation for extracting additional information

### ISSUE THREAD

**Issue by ivanceras** [diesel-rs/diesel#769]
Add support on [`ColumnInformation`](https://github.com/diesel-rs/diesel/blob/master/diesel_infer_schema/src/data_structures.rs#L12) for extracting additional information
* default_value
* is_unique
* limit if any (ie: varchar(36) in mysql) 
* comment
* referred column(if foreign key) of the foreign table ie: `product.owner` references `users(user_id)`

### Use case:
The [database admin ui - curtain](https://github.com/ivanceras/curtain) I've been working on uses these additional information to create a generic UI for the generated fields based on the table schema.

**Comment by sgrif** [comment]
With the possible exception of limit, none of those fields are relevant to Diesel. You're certainly able to use Diesel to query `information_schema` in a similar fashion that we do internally, but the internals of `diesel_codegen` and `diesel_infer_schema` are not part of our public API and shouldn't be used directly.
