### ISSUE TITLE
Add SSL support for mysql

### ISSUE THREAD

**Issue by Kintaro** [diesel-rs/diesel#786]
At work our SQL database uses SSL certificates for the connection and I'd love to use diesel, but for the time being I have to fall back to the normal mysql crate. Adding SSL would be really beneficial.

**Comment by sgrif** [comment]
We should be preferring SSL connections already, but I agree that we should add the ability to specify `?sslmode=require` in the URL, similar to PG.

**Comment by Kintaro** [comment]
I meant more in terms of providing client certificates and keys.

**Comment by sgrif** [comment]
Yes, I will add support for that as well

**Comment by Kintaro** [comment]
Nice. Thanks a bunch. Would really help. We're building a prototype for
some financial systems and it worms at the moment with the mysql crate. But
the added readability abf exchanfabimity for pg and sqlite would really
help to put it into prod.

**Comment by marti1125** [comment]
Hello I can't connect with Heroku its required: 
All connections require SSL: sslmode=require.

**Comment by yerke** [comment]
@sgrif Hi. Thank you for creating and maintaining Diesel. Do you think you will have time to finish this soon? I do understand that MySQL is not a priority, but it would be nice to have some clarity on whether this will be solved. Thank you.

**Comment by p-alik** [comment]
@sgrif, if no one works on this issue yet, I'm willing to take over.

**Comment by weiznich** [comment]
Closed by #2491
