### ISSUE TITLE
print-schema vs. compound primary keys

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#790]
Just [saw](https://github.com/sgrif/crates.io/blob/5082c78938f2353e27c272e9eb089a8d1a62e9a1/src/schema.rs#L4-L5) this:

```rust
table! {
    badges (crate_id,
    badge_type) {
        crate_id -> Int4,
        badge_type -> Varchar,
        attributes -> Jsonb,
    }
}
```

The second like should be `badges (crate_id, badge_type) {`.

Looks like our [pretty printing](https://github.com/diesel-rs/diesel/blob/8c8c0ab9d1c877650ffcb804ac1ba6d96ed591b9/diesel_cli/src/pretty_printing.rs) code needs a few more test cases and one more special case.

**Comment by sgrif** [comment]
Not sure if I have an open issue for this or not, but it also generates incorrect code for custom schemas.

**Comment by Eijebong** [comment]
@sgrif Are you talking about the spaces around the dot ?
