### ISSUE TITLE
Appveyor has intermittent failures

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#795]
Occasionally our builds on appveyor fail before they can even download Rust.

> appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
> Error downloading remote file: One or more errors occurred.
> Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.

Would be great to figure out a way to fix this, since those builds are slow enough that "just restarting it when it happens" is pretty painful.

**Comment by cyplo** [comment]
Would caching the binary in appveyor's cache help ?
