### ISSUE TITLE
Google prefers https://diesel.rs/ (which actually has an SSL error) to http://diesel.rs/

### ISSUE THREAD

**Issue by nodakai** [diesel-rs/diesel#800]
- https://www.google.com/search?q=diesel+rs&ie=utf-8&oe=utf-8
  - --> https://diesel.rs/

Firefox ESR 45.7.0:
> diesel.rs uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

Chrome  56.0.2924.87 :
> NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by sgrif** [comment]
I don't know that we have any control over this. Presumably it's something on Github's end that is causing this to occur? @arthurnn do you know who the right person to ping about this is?

**Comment by arthurnn** [comment]
I guess you could try https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it to add ssl to diesel github pages?
@parkr will know better.

**Comment by killercup** [comment]
Should be fine now, cc #808
