### ISSUE TITLE
Set up LetsEncrypt and Cloudflare on diesel.rs

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#808]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/ makes it sound like we can use Cloudflare in front of the site to provide a valid SSL certificate without costing us money. I haven't looked into this in depth yet, but would love for someone to look into this.

**Comment by killercup** [comment]
That is what I'm doing with pascalhertleif.de and scribbles.pascalhertleif.de. It's pretty easy to do if you can set a custom name server for your domains.

**Comment by sgrif** [comment]
Yeah, we can do whatever we want with the domains they're just hosted on DNSimple.

**Comment by killercup** [comment]
Set up cloudflare. After the ns settings take effect, traffic should go through them and we'll get a valid ssl cert for free.

**Comment by killercup** [comment]
Seems to work!
