### ISSUE TITLE
Select from a sql function

### ISSUE THREAD

**Issue by fluxxu** [diesel-rs/diesel#815]
Now diesel has a sql_function! macro which allows we map a SQL function to query DSL, but I can't figure out a way to map a function to return a table.

For example, it seems that there is no way to select from this function:
```sql
CREATE TABLE tbl_function_return_data (
  id serial,
  text_value text,
  int_value integer,
  PRIMARY KEY(id)
);

CREATE FUNCTION function_return_table(v1 integer, v2 text)
  RETURNS TABLE(
    id integer,
    text_value text,
    int_value integer
  )
AS
$$
  SELECT * FROM tbl_function_return_data WHERE int_value > v1 OR text_value = v2
$$
LANGUAGE 'sql' IMMUTABLE;
```

To make diesel compiles, we can
```rust
sql_function!(function_return_table, function_return_table_t, (v1: Integer, v2: VarChar) -> (i32, String, i32));

diesel::select(tbl_function_return_data(1, "string")).load::<(i32, String, i32)>(conn);
```

But this generates a query as
```sql
SELECT tbl_function_return_data(1, 'string');
```
which returns a tuple instead of a record set, which causes a DeserializationError.
The query we actually need is:
```sql
SELECT * FROM tbl_function_return_data(1, 'string');
```
To generate this query, I tried
```
diesel::expression::SelectStatement::simple(tbl_function_return_data(1, "string")).load::<(i32, String, i32)>(conn);
```
To make this compiles, I need to impl QuerySource for function_return_table_t:
```rust
impl<A: Clone, B: Clone> QuerySource for function_return_table_t<A, B> {
  type FromClause = Self;
  type DefaultSelection = SqlLiteral<(Integer, VarChar, Integer)>;

  fn from_clause(&self) -> Self::FromClause {
    self.clone()
  }

  fn default_selection(&self) -> Self::DefaultSelection {
    SqlLiteral::new("*".to_owned())
  }
}
```
My question is should we have a macro like
```rust
sql_function_query_souce!(
  function_return_table, function_return_table_t, (v1: Integer, v2: VarChar) -> (i32, String, i32)
);
```
which impl QuerySource?
`sql_function` + impl QuerySource works, but the return type of `sql_function` is useless for this use case.

Thanks!

**Comment by sgrif** [comment]
I think for now `sql_query` is the best bet for something like this. Support for this is roughly the same as supporting selecting from a subselect, which will come at some point in the future.

**Comment by Ofenhed** [comment]
@sgrif sql_function has been reworked since this was closed. Would it be more sensible to make a sql_function into a QuerySource as it looks today?

**Comment by weiznich** [comment]
@Ofenhed Turning all the data structures generated by `sql_function!` into a `QuerySource` won't work, because that's not the case for sql functions in general. That said I'm open to someone working on this feature. I would expect first some written proposal on how the API should look like in our discussion forum. 
Additionally I should add that it's likely possible to implement something like this as third party crate with the latest release (See [here](https://github.com/weiznich/wundergraph-workshop/blob/6785ce355d9e497909832bf9be79dede4c994c08/src/diesel_ext.rs) for example.)

**Comment by thenotoriousjr** [comment]
> Now diesel has a sql_function! macro which allows we map a SQL function to query DSL, but I can't figure out a way to map a function to return a table.
> 
> For example, it seems that there is no way to select from this function:
> 
> ```sql
> CREATE TABLE tbl_function_return_data (
>   id serial,
>   text_value text,
>   int_value integer,
>   PRIMARY KEY(id)
> );
> 
> CREATE FUNCTION function_return_table(v1 integer, v2 text)
>   RETURNS TABLE(
>     id integer,
>     text_value text,
>     int_value integer
>   )
> AS
> $$
>   SELECT * FROM tbl_function_return_data WHERE int_value > v1 OR text_value = v2
> $$
> LANGUAGE 'sql' IMMUTABLE;
> ```
> 
> To make diesel compiles, we can
> 
> ```rust
> sql_function!(function_return_table, function_return_table_t, (v1: Integer, v2: VarChar) -> (i32, String, i32));
> 
> diesel::select(tbl_function_return_data(1, "string")).load::<(i32, String, i32)>(conn);
> ```
> 
> But this generates a query as
> 
> ```sql
> SELECT tbl_function_return_data(1, 'string');
> ```
> 
> which returns a tuple instead of a record set, which causes a DeserializationError. The query we actually need is:
> 
> ```sql
> SELECT * FROM tbl_function_return_data(1, 'string');
> ```
> 
> To generate this query, I tried
> 
> ```
> diesel::expression::SelectStatement::simple(tbl_function_return_data(1, "string")).load::<(i32, String, i32)>(conn);
> ```
> 
> To make this compiles, I need to impl QuerySource for function_return_table_t:
> 
> ```rust
> impl<A: Clone, B: Clone> QuerySource for function_return_table_t<A, B> {
>   type FromClause = Self;
>   type DefaultSelection = SqlLiteral<(Integer, VarChar, Integer)>;
> 
>   fn from_clause(&self) -> Self::FromClause {
>     self.clone()
>   }
> 
>   fn default_selection(&self) -> Self::DefaultSelection {
>     SqlLiteral::new("*".to_owned())
>   }
> }
> ```
> 
> My question is should we have a macro like
> 
> ```rust
> sql_function_query_souce!(
>   function_return_table, function_return_table_t, (v1: Integer, v2: VarChar) -> (i32, String, i32)
> );
> ```
> 
> which impl QuerySource? `sql_function` + impl QuerySource works, but the return type of `sql_function` is useless for this use case.
> 
> Thanks!

I found a workaround. Say you have created a function and you need the query results to have the fields but the sql function doesn't give you what you want as it doesn't select "* from" a function. Here's what I did.

```rust
sql_function! {
    fn my_function(f: Timestamptz, t: Timestamptz, i: Text, p: BigInt, tb: Text)
    -> Record<(BigInt, BigInt, Json, Json, Json, Json, Json)>;
}

sql_function! {
    fn row_to_json(my_function: Record<(BigInt, BigInt, Json, Json, Json, Json, Json)>) -> Json;
}

let data = diesel::select(row_to_json(my_function(...))).load_iter::<Value, DefaultLoadingMode>(conn)?.map(|v| MyStruct::from(v?).0).collect::<Result<Vec<Ohlcb>, CustomError>>()?;
```

You can deserialize the rows with serde into a struct

 Do note that row_to_json is a Postgres built-in function.
[https://www.postgresql.org/docs/9.5/functions-json.html#FUNCTIONS-JSON-CREATION-TABLE](url)
