### ISSUE TITLE
Cannot install diesel_cli without mysql

### ISSUE THREAD

**Issue by Gurpartap** [diesel-rs/diesel#818]
```sh
$ cargo install diesel_cli
   ...
   ...
   Compiling diesel_cli v0.12.0
   error: linking with `cc` failed: exit code: 1
   note: ld: library not found for -lmysqlclient
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```sh
$ brew install mysql
```
```sh
$ cargo install diesel_cli
   ...
   ...
   Compiling diesel_cli v0.12.0
    Finished release [optimized] target(s) in 68.30 secs
  Installing /Users/Gurpartap/.cargo/bin/diesel
```

diesel_cli v0.12.0
Rust 1.16.0
macOS 10.12.3

**Comment by Eijebong** [comment]
`cargo install diesel_cli --features postgres,sqlite` will allow you to compile diesel_cli without mysql support

**Comment by killercup** [comment]
I think you need --no--default--features as well. See cargo install -h for
more info.

Eijebong <notifications@github.com> schrieb am Mi. 22. März 2017 um 12:27:

**Comment by sgrif** [comment]
Yes. We install with all supported backends by default, you need to specify `--no-default-features --features whatever,backends` to disable certain ones. Once `compile_error!` is stable we'll probably switch to no backends by default.

**Comment by thombles** [comment]
A note for anyone finding this later—features are space-separated so the working command is:
```
cargo install diesel_cli --no-default-features --features "postgres sqlite"
```
