### ISSUE TITLE
Cannot access docs.diesel.rs from Tor

### ISSUE THREAD

**Issue by burdges** [diesel-rs/diesel#820]
Appears CloudFlare blocks access to docs.diesel.rs for Tor users.  I think you can configure Tor access in your country settings of your CloudFlare configuration.

**Comment by killercup** [comment]
Oh, sorry! I didn't know that when setting up Cloudflare. I think I whitelisted Tor traffic now. Can you try again?

**Comment by burdges** [comment]
Yup, work fine now.  Thanks!  :)
