### ISSUE TITLE
Running SQLite example fails

### ISSUE THREAD

**Issue by palango** [diesel-rs/diesel#822]
I'm trying to run the SQLite example in `diesel/examples/sqlite`. I adapted the `test_all` script to use the locally installed version, which is 0.12.

I get the following compiler errors and would be interested in any hints...

```
$ ./test_all_2
Dropping database: /tmp/test_examples.db
Creating database: /tmp/test_examples.db
Running migration 20170124012402
   Compiling diesel_demo_step_1_sqlite v0.1.0 (file:///Users/paul/Projects/rust/crates/diesel/examples/sqlite/getting_started_step_1)
error[E0432]: unresolved import `self::schema::posts::dsl::*`
 --> src/bin/show_posts.rs:9:9
  |
9 |     use self::schema::posts::dsl::*;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `posts` in `schema`

error[E0425]: cannot find value `posts` in this scope
  --> src/bin/show_posts.rs:12:19
   |
12 |     let results = posts.filter(published.eq(true))
   |                   ^^^^^ not found in this scope

error[E0425]: cannot find value `published` in this scope
  --> src/bin/show_posts.rs:12:32
   |
12 |     let results = posts.filter(published.eq(true))
   |                                ^^^^^^^^^ not found in this scope

error: aborting due to 3 previous errors

error: Could not compile `diesel_demo_step_1_sqlite`.

To learn more, run the command again with --verbose.
```

**Comment by Eijebong** [comment]
I think you didn't run the migrations so the database doesn't exist and diesel cannot infer the schema

**Comment by palango** [comment]
> I think you didn't run the migrations so the database doesn't exist and diesel cannot infer the schema

Doesn't `Running migration 20170124012402` mean that the migrations are run?

**Comment by Eijebong** [comment]
Oh, missed that :p 
I still think that the database is not in the correct state.
What did you change in the test_all script ?

**Comment by palango** [comment]
It looks like that (just removed the relative path from the `diesel` program:

```
#!/bin/sh
set -e

export DATABASE_URL="/tmp/test_examples.db"

for dir in $(find . -maxdepth 1 -mindepth 1 -type d); do
  cd $dir
  diesel database reset
  cargo build
  cd ..
done
```

**Comment by palango** [comment]
If I open the test_database.db file and look at the schema it looks right:
```sql
sqlite> .schema posts
CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0
);
```

**Comment by Eijebong** [comment]
Do you  have a .env file somewhere in there ?

**Comment by palango** [comment]
> Do you have a .env file somewhere in there ?
No

**Comment by Eijebong** [comment]
Weird then :( I don't have any more ideas maybe someone with more knowledge than me can help you, sorry

**Comment by ericho** [comment]
I can reproduce this (and possibly fix). If DATABASE_URL is not set, then you will see the error and you'll see it all the next times you run `cargo build`, without matter if DATABASE_URL is set or not. 

Try to run a `cargo clean` before running the script again. That worked for me to solve the issue.

**Comment by palango** [comment]
That helped for me as well.
