### ISSUE TITLE
When project is in cargo's workspace, infer_schema! fails for "Failed to load environment variable POSTGRES_URL: environment variable not found"

### ISSUE THREAD

**Issue by redtankd** [diesel-rs/diesel#823]
My cargo workspace's structure is below:

```
workspace/
     |----Cargo.toml
     |----mydieselproject/
                |----Cargo.toml
```

When I build or test in the dir workspace with option "--all", building is failed. The message is

```
 --> diesel/src/schema.rs:2:1
  |
2 | infer_schema!("dotenv:POSTGRES_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: "Failed to load environment variable POSTGRES_URL: environment variable not found"
  = note: this error originates in a macro outside of the current crate
```

I think it is because the .env is not in dir workspace.

**Comment by lancecarlson** [comment]
Did you figure out this issue? The error is saying it can't find your env variable, likely because you are missing your .env file as you suggested.

**Comment by namiwang** [comment]
@lancecarlson 

Hi, I've encountered the same issue. I'm not using `dotenv`, instead, I'm using
```rust
set_var("DATABASE_URL", db_path);
infer_schema!("env:DATABASE_URL");
```

Any suggestion?
