### ISSUE TITLE
Compiler warnings on compiling diesel 0.12.0 (from crates.io)

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#824]
If I try to compile diesel 0.12.0 from crates.io rustc will emit several [warnings](https://gist.github.com/weiznich/727bf056f58dd1e7cb4ac23240a09e71) with the following message:
```
warning: Quasi-quoting might make incremental compilation very inefficient: NtExpr(..)
```
Expected:
Compiling diesel from crates.io does not show any warning

Environment:
rustc 1.17.0-nightly (8c4f2c64c 2017-03-22)
export CARGO_INCREMENTAL=1 RUSTFLAGS="-Zincremental-info"

**Comment by sgrif** [comment]
This appears to be a bug in Rust, not Diesel.
