### ISSUE TITLE
"Deadlock detected" CI errors on upsert tests

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#828]
I've seen some CI run fail recently with

> called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "deadlock detected")'

For example those:

- https://ci.appveyor.com/project/sgrif/diesel/build/1.0.282/job/vn761wy7t1436l8d#L705 in `upsert_with_sql_literal_for_target `
- https://travis-ci.org/diesel-rs/diesel/jobs/214539180#L1051 in `upsert_with_no_changes_executes_do_nothing`

Two may not be a big enough sampling size, but it seems related to upserts.

**Comment by Eijebong** [comment]
Going to make a lot of coffee and try to solve this tonight

**Comment by Eijebong** [comment]
Ok, after 2 hours battling with my windows VM to install launch link postgresql...

```
INSERT INTO users (id, name) VALUES(1, 'Sean'), (2, 'Tess')   
CREATE UNIQUE INDEX ON users (name) WHERE name != 'Tess'      
```

Those are the two queries creating the deadlock

**Comment by Eijebong** [comment]
This has been fixed by https://github.com/diesel-rs/diesel/commit/523ffb39f88fb026e69fa51f848ee2de12f16dc4
