### ISSUE TITLE
No timeout when connecting to database

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#832]
It seems that PgConnection::establish(..) never times out when using it with a non-existing database, is that intended?

A (configurable) timeout would probably be needed here.

**Comment by sgrif** [comment]
You can specify the timeout in the connection URL. https://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by dbrgn** [comment]
Thanks, I wasn't aware of that.
