### ISSUE TITLE
Is `HasMany!` still required for joins?

### ISSUE THREAD

**Issue by SirRade** [diesel-rs/diesel#833]
The macro [HasMany!](http://docs.diesel.rs/diesel/macro.HasMany.html) 
- isn't documented much (Do you have to treat the participating `structs` different afterwards?)
- is [not tested anywhere in the repo](https://github.com/diesel-rs/diesel/search?utf8=%E2%9C%93&q=hasmany&type=)
- has special annotation syntax (`#[table_name(name)]` vs `#[table_name="name"]`)
- Hasn't been significantly touched in a while
- requires you to duplicate your code if you need the parent `struct` to be `pub`, e.g.
```rust
#[table_name="question"]
#[derive(Queryable, Identifiable)]
pub struct Question {
    pub id: i32,
    pub category_id: i32,
    pub text: String,
}

#[table_name="category"]
#[derive(Queryable, Identifiable, Debug)]
pub struct Category {
    pub id: i32,
    pub text: String,
}

HasMany! {
    (question, foreign_key = category_id)
    #[table_name(category)]
    #[derive(Queryable, Identifiable, Debug)]
    pub struct Category {
        pub id: i32,
        pub text: String,
    }
}
```

The last point makes me very uncomfortable with the macro, As I have many 1:n relations in my database.
Is there an alternative? 
Did I understand something wrong?

**Comment by sgrif** [comment]
> isn't documented much

It's documented at http://docs.diesel.rs/diesel/associations/index.html

> (Do you have to treat the participating structs different afterwards?)

No

> is not tested anywhere in the repo

[yes it is](https://github.com/diesel-rs/diesel/search?utf8=%E2%9C%93&q=has_many&type=)

> has special annotation syntax 

This is the same as all other derives

> Hasn't been significantly touched in a while

Unsure why this is something that you have a problem with?

> Is there an alternative?

Not using it. All `#[has_many]` does right now is enable `parent_table.inner_join(child_table)`. If you always join in the reverse direction, or use `belonging_to` and `grouped_by`, you don't need it.
