### ISSUE TITLE
Joining on arbitrary string field

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#838]
I have a table with user information and a table with a public key cache.

I'd like to join those on the user id field. There is no foreign key on the tables though, since a cached key could exist without a user, and a user could exist without a cached key.

Is there a way to join two tables on an arbitrary field name, using either the string builder or a raw query?

I tried a raw query, but didn't get it to work:

```rust
let query = sql::<(recipients::SqlType, pubkey_cache::SqlType)>(
    &format!("SELECT r.*, c.*
              FROM recipients r
              INNER JOIN pubkey_cache c ON r.user_id = c.user_id
              WHERE r.broadcast_id = {}", broadcast.id)
);
let recipients = query.get_results::<(recipients::SqlType, pubkey_cache::SqlType)>(conn)?;
```

Any pointers are warmly appreciated. I already searched through the test suite and through the issue tracker, but didn't find a working solution.

**Comment by sgrif** [comment]
I mentioned it in gitter, but your issue is that you're passing the wrong type to `get_results`. It should be the type you want to deserialize to. We already know the SQL type from the query itself.
