### ISSUE TITLE
Better handling of Numeric type

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#841]
Some operations like `avg()` on an integer field return `Numeric`, which isn't currently mapped to any Rust type. I didn't find out how to actually retrieve the resulting value. Is it even possible?

See #840.

**Comment by rubdos** [comment]
See PR #837. Would you be interested in a direct conversion to `f64`, and `f32`? If so, we should discuss whether that's a good idea or not; after all, you'd loose some data when doing the conversion, but for `avg()` it might not even be bad.

**Comment by dbrgn** [comment]
@rubdos Numeric is something like a decimal type, right? so I guess what we'd lose is precision?

**Comment by sgrif** [comment]
I'd be fine with losing precision from `avg` and friends specifically, but I don't see any way to make that happen without allowing loss of precision for all cases which is not something I'd be willing to accept.

**Comment by dbrgn** [comment]
If Numeric is a decimal type, maybe there's a loss-free decimal type available in the Rust ecosystem? Or maybe we could add our own wrapper that can be converted to a float explicitly, if desired?

**Comment by rubdos** [comment]
> If Numeric is a decimal type, maybe there's a loss-free decimal type available in the Rust ecosystem? Or maybe we could add our own wrapper that can be converted to a float explicitly, if desired?

I refer again to #837; that directly solves this issue. The loss-free decimal type in the Rust ecosystem is done by the `bigdecimal` crate, by @akubera, @iterion and me, in collaboration with the `num` crate. The `BigDecimal` type allows for a direct conversion to `float`, [which is currently in development](https://github.com/akubera/bigdecimal-rs/pull/12).

**Comment by rubdos** [comment]
`to_f64` is decently implemented now (before it only gave the integer value), and should be merged soon™.

Next up is finishing #837; I think all of what I need is available in BigDecimal or its merge requests now.

**Comment by killercup** [comment]
Alright! #837 is on master. So, the next question is: What needs to happen to make this easily usable?

- [x] Numeric ↔ BigDecimal conversion
- [ ] Full query/insert example of table using Numeric and struct using BigDecimal
- [ ] Fix [`avg` docs](https://github.com/diesel-rs/diesel/blob/e2608a4477d61787287cd0a289ed084685e90095/diesel/src/expression/functions/aggregate_folding.rs#L94-L96) (and maybe look at other functions using Numeric)

Open points from #837:

- [ ] Do we want `FromSql<>`/`ToSql<> for f64/f32`?
- [ ] Support other databases; if someone wants to help here, feel free to file pull requests to my `bigdecimal` branch on my repo.

(Do we want to make this a meta issue for all things Numeric? I can move the todo lists to the main issue descriptions. Also, feel free to add more points, or open new issues for parts of this!)

**Comment by rubdos** [comment]
> Do we want FromSql<>/ToSql<> for f64/f32?

Actually, I want to vote "no" on this. Although Rust does *very* well enforce types, I think this might confuse users. When you have Numeric in your database, you don't "just" want to read it out as `f64`/`f32` as a test. Especially since now you can just go `extern crate bigdecimal; struct A{a: BigDecimal}` and be compatible with diesel...

> (Do we want to make this a meta issue for all things Numeric? I can move the todo lists to the main issue descriptions. Also, feel free to add more points, or open new issues for parts of this!)

Good with me.

**Comment by rubdos** [comment]
> Full query/insert example of table using Numeric and struct using BigDecimal

I grant you [this](https://gitlab.com/rubdos/erp-rs/blob/ad1508b14721cb68632d3ca1274488c05784c27f/src/models/sales_invoice.rs) and [this](https://gitlab.com/rubdos/erp-rs/blob/ad1508b14721cb68632d3ca1274488c05784c27f/src/app/controllers/invoice.rs) file under both Apache 2.0 and MIT licenses; so you can use the code to put it in examples.

I don't have migrations in that project, but feel free to ask for more files if you want. There are example insertions, and example selections, and even some other fancy logic to make an invoice from them.
