### ISSUE TITLE
Arithmetic on optionals

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#842]
This does not work...

    update(posts.filter(id.eq(7)).set(read_count.eq(read_count + 1))

...if `read_count` is nullable.

According to my tests, Pg, MySQL and SQLite all return null for `SELECT NULL + 1`.

This page seems to agree: http://www-cs-students.stanford.edu/~wlam/compsci/sqlnulls

> An arithmetic operation involving a NULL returns NULL. For example, NULL minus NULL yields NULL, not zero.

I didn't check the SQL ISO standard though.

Note also that aggregation function like `SUM()` seem to ignore null values.

Maybe addition and other arithmetic operations could be implemented on `Nullable<Integer>` and others?

**Comment by sgrif** [comment]
The ISO standard is that any operation on a null value returns null. I'm fine with adding ops for nullable values (preferably as a single blanket impl if possible)
