### ISSUE TITLE
diesel_cli do nothing

### ISSUE THREAD

**Issue by AlexNav73** [diesel-rs/diesel#843]
Hi, I faced a strange issue when I try to use diesel_cli

I install latest version of `diesel_cli 0.12.0` using command: ```cargo install diesel_cli --no-default-features --features=postgres``` . Installation finished successfully, but when I try to run binary I have no output at all. I tried all subcommands and every time I haven't got any output. Binary just do nothing.

I git cloned this repo and installed `diesel_cli` dirrectly from repo. It didn't help.

Then I started puting ```println!(...)``` in src of this repo and see, what will happend. Finnaly I get ```"before find_migrations_directory"``` printed when I do this
```rust
fn run_setup_command(matches: &ArgMatches) {
    println!("before find_migrations_directory");
    return;
    migrations::find_migrations_directory()
        .unwrap_or_else(|_| {
            println!("create_migrations_directory");
            create_migrations_directory()
                .unwrap_or_else(handle_error)
        });

    println!("find_migrations_directory");
    return;
    database::setup_database(matches).unwrap_or_else(handle_error);
}
```
but if I remove first ```return``` it will do nothing again (and no output too). 

I setted up `PQ_LIB_DIR`, `DATABASE_URL`
Tested on Windows 10 and 7
```
PS D:\Programms\Rust\diesel\diesel_cli> rustc --version --verbose
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: i686-pc-windows-gnu
release: 1.16.0
LLVM version: 3.9
```

**Comment by AlexNav73** [comment]
The problem was in my PATH environment variable. When I append PATH with value of `PQ_LIB_DIR` it solved the problem.

**Comment by gheoan** [comment]
I am affected by this too. I am using MySQL. The CLI should show a message indicating that the database was not installed corectly instead just exiting with no output. Can this issue be reopen?

**Comment by yuana1** [comment]
@gheoan   Add 'C:\Program Files\MySQL\MySQL Connector.C 6.1\lib' to your PATH
![image](https://user-images.githubusercontent.com/7308509/53613812-3b17bc80-3c12-11e9-9b22-1dfcfce264b6.png)

**Comment by slhmy** [comment]
> @gheoan Add 'C:\Program Files\MySQL\MySQL Connector.C 6.1\lib' to your PATH
> ![image](https://user-images.githubusercontent.com/7308509/53613812-3b17bc80-3c12-11e9-9b22-1dfcfce264b6.png)

no use for me :sad:
