### ISSUE TITLE
macro undefined: 'infer_schema_options!'

### ISSUE THREAD

**Issue by suryakencana007** [diesel-rs/diesel#850]
When I build or test in the dir workspace with option "--all", building is failed. The message is

Running `rustc --crate-name rustweb src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=bfa9892632724e72 -C extra-filename=-bfa9892632724e72 --out-dir /Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps -L dependency=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps --extern diesel=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps/libdiesel-be0e2b3b62613036.rlib --extern hyper=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps/libhyper-a990edaaf27e9f52.rlib --extern diesel_codegen=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps/libdiesel_codegen-b9349f7ccad6c8b0.dylib --extern rustc_serialize=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps/librustc_serialize-54d2bf33b1d4b0b0.rlib --extern dotenv=/Volumes/RAID1/KERJAAN/experiment/RUST/Diesel/rustweb/target/debug/deps/libdotenv-75d8ce5725f9d0e8.rlib -L native=/usr/local/opt/postgresql/lib`
error: macro undefined: 'infer_schema_options!'
 --> src/schema.rs:1:1
  |
1 | infer_schema!("dotenv:DATABASE_URL");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate

**Comment by sgrif** [comment]
Can you run `cargo update`?

**Comment by suryakencana** [comment]
yes i can run but nothing happend
![screen shot 2017-04-08 at 7 14 48 pm](https://cloud.githubusercontent.com/assets/4660505/24828794/cec0c5ca-1c8f-11e7-9546-f5ef536f922a.png)

Here the Cargo.toml

![screen shot 2017-04-08 at 7 15 26 pm](https://cloud.githubusercontent.com/assets/4660505/24828796/de38334e-1c8f-11e7-80c6-d25e08e63a36.png)

My Rust and Cargo version
![screen shot 2017-04-08 at 7 17 28 pm](https://cloud.githubusercontent.com/assets/4660505/24828808/12786ad4-1c90-11e7-9d9d-6c7b7e715870.png)

Thank you for helping me

**Comment by sgrif** [comment]
Sorry I did not reply to this in April, this was during my parental leave when I wasn't around much. There's not enough information here to reproduce, so I'm going to close this. If you are able to reproduce this issue on Diesel 0.99 or later, please open a new issue.
