### ISSUE TITLE
Add support for Postgres encode and decode expressions

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#856]
Postgres supports string encoding and decoding (to and from `bytea` columns):

https://www.postgresql.org/docs/9.5/static/functions-string.html#FUNCTIONS-STRING-OTHER

Examples:

```sql
SELECT encode(data, 'base64') FROM blobcache;
SELECT encode(pubkey, 'hex') FROM public_keys;
```

Supported formats: base64, hex, escape.

Would be great if these were usable from diesel.

**Comment by sgrif** [comment]
You can declare any function you'd like with the `sql_function!` macro. http://docs.diesel.rs/diesel/macro.sql_function.html
