### ISSUE TITLE
Alternative output formats for print-schema

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#864]
`smag` suggested graphviz output for `print-schema` [on Gitter](https://gitter.im/diesel-rs/diesel?at=58f679cfad849bcf4298aabe), and I think this is a nice idea. I'm not entirely sure if this is something we want in diesel_cli itself or if it'd be nicer to have a new crate that does that (it could use diesel_infer_schema as a dependency).

**Comment by sgrif** [comment]
I'm pretty sure there are other tools that output database schema in graphviz. This really seems out of scope for Diesel though.
