### ISSUE TITLE
Embedded migrations: Dead code warning

### ISSUE THREAD

**Issue by dbrgn** [diesel-rs/diesel#865]
As mentioned here https://github.com/diesel-rs/diesel/pull/854#issuecomment-293825480, using embedded migrations with `run_with_output` results in a dead code warning.

```
warning: function is never used: `run`, #[warn(dead_code)] on by default
  --> src/db/mod.rs:62:1
   |
62 | embed_migrations!();
   | ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate
```

Would it be possible to add an exception for that? I didn't easily find out where to add it.

CC @Eijebong @weiznich

**Comment by killercup** [comment]
Yes, add `#[allow(unused)]` to the mods [here](https://github.com/diesel-rs/diesel/blob/3893be9194128cdaf0a3b4a317b8cfc29bbffdcc/diesel/src/macros/macros_from_codegen.rs#L107-L122).

**Comment by dbrgn** [comment]
@killercup Ok, I'll create a pull request :)
