### ISSUE TITLE
INSERT DEFAULT VALUES?

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#872]
I have this table

```sql
CREATE TABLE users
(
	id serial NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
) WITHOUT OIDS;
```

and want to create an user using default values.

I tried to define this structure:

```rust
#[derive(Insertable)]
#[table_name="users"]
pub struct NewUser {}
```

but it raises this error:

```
error: no rules expected the token `]`
  --> model/src/lib.rs:23:19
   |
23 | #[derive(Insertable)]
   |                   ^
```

It is reasonable because in SQL, inserting empty values is not allowed

```
db=# insert into users () values (); 
ERROR:  syntax error at or near ")"  
LINE 1: insert into users () values (); 
```

However, with, `DEFAULT VALUE` you can insert values with default values.

```
actcast=# INSERT INTO users DEFAULT VALUES;
INSERT 0 1
actcast=# SELECT * FROM USERS;
 id |         created_at
----+----------------------------
  1 | 2017-04-26 01:12:56.90735
(1 row)
```

How can I use this feature through diesel? Or if not supported, could you support this (feature request)?

**Comment by KeenS** [comment]
Of cause, I know I can do it with `sql` function

```rust
sql::<Integer>("INSERT INTO users DEFAULT VALUES RETURNING id")
```

**Comment by sgrif** [comment]
This is a reasonable feature, but I'm unsure what I'd like the public API for it to be. If nothing else, `#[derive(Insertable)]` with no columns should fail to compile, as we're breaking our guarantees about runtime errors.

**Comment by KeenS** [comment]
I suppose allowing empty structs to derive `Insertable` (in that case, empty structs will use `DEFAULT VALUES`) or providing another function like `insert_defaults()` will do.
