### ISSUE TITLE
save_changes is only available for types that implement Copy

### ISSUE THREAD

**Issue by White-Oak** [diesel-rs/diesel#886]
[As far as I can see](https://docs.rs/diesel/0.12.0/diesel/prelude/trait.SaveChangesDsl.html#tymethod.save_changes), `save_changes` is only available for types that implement `Copy`: `T: Copy + AsChangeset<Target=T::Table> + IntoUpdateTarget`. But for most models that would not be the case, since `String`, which is arguably one of the most common fields in models, does not implement `Copy`.

Is it possible to ease the requirements for `SaveChangesDsl`?

**Comment by sgrif** [comment]
`SaveChangesDsl` (along with `AsChangeset`, `IntoUpdateTarget`, and `Identifiable`) is implemented on a reference to your struct, not the struct itself. References always implement `Copy`. If `save_changes` isn't present, you're probably missing either `#[derive(AsChangeset)]` or `#[derive(Identifiable)]`
