### ISSUE TITLE
Schema Inference Tests

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#905]
There are several places where the schema inference is tested, e.g., in the integration tests of `diesel_tests`, or the CLI tests for `diesel print-schema`. I think it'd make sense to also add some tests that focus only on creating a table and asserting the correct `table!` call gets written.

To implement this, you'd probably start by splitting off parts of the `expand_infer_table_from_schema` function into a new fn that accepts a given connection. Then, write tests that create a table, call the new fn to get the tokens of a `table!` call, and compare this to an expected output. (Afterwards, make sure the new table has been dropped; this happens automatically when using `begin_test_transaction` with SQLite and PG but doesn't work with MySQL.)

Interesting edge cases: Unusual type combinations (e.g., arrays of network addresses), multiple primary keys (expect error on >4 with current code), huge amounts of columns.

**Comment by weiznich** [comment]
I think this is somewhat covered now with the print-schema tests in diesel-cli.
