### ISSUE TITLE
Nice codegen errors

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#920]
Make sure our codegen (`#[derive(…)]`) generates useful error messages. They should be tested by a compile-fail test.

Especially edge cases like empty structs should be caught where necessary. For example,

```rust
#[derive(Insertable)]
#[table_name="users"]
pub struct NewUser {}
```

currently fails with

> no rules expected the token `]`

It should probably say something like this instead (maybe with a link to docs or some other feature the user might've been meaning to use):

> Failed to derive `Insertable` on `NewUser` struct because it has no fields.

We already alert the user to some things, e.g. how we currently don't support generic structs, with code like [this](https://github.com/diesel-rs/diesel/blob/62dbbecc7fa689a95ded2618b9eb4cecc5051bcc/diesel_codegen/src/insertable.rs#L14-L16).

Feel free to add more examples in the comments.

**Comment by jaroslaw-weber** [comment]
Error messages in diesel look too much like tokio errors - if you mistype or make a mistake it tends to throw out very long errors. although it is scary at first, fixing wasn't that difficult (just start at the top)
Even if you can still read through messages and fix the problem, I miss the simple error messages without diesel.

**Comment by willmurphyscode** [comment]
Is there work left to be done on this issue? It looks like there are two merged pull requests, one of which specifically addresses `#[derive(Insertable)]`.

**Comment by berkus** [comment]
@willmurphyscode there's definitely more to be done:

```
error: proc-macro derive panicked
  --> src/models.rs:68:10
   |
68 | #[derive(Insertable)]
   |          ^^^^^^^^^^
   |
   = help: message: failed to parse type: failed to parse all tokens
```

in the recent diesel 1.2.2 and I have _no_ clue what it's talking about.

the struct in question for posterity:
```
#[derive(Insertable)]
#[table_name = "alerts"]
pub struct NewAlert<'a> {
    pub guid: &'a str,
    pub title: &'a str,
    #[column_name = "type"]
    pub alert_type: &'a str,
    #[column_name = "startdate"]
    pub start_date: NaiveDateTime,
    #[column_name = "expirydate"]
    pub expiry_date: Option<NaiveDateTime>,
    pub faction: Option<String>,
    pub flavor: Option<String>,
}
```

**Comment by sgrif** [comment]
Unfortunately, since syn always panics when something fails, there's nothing we can do to improve error messages as a result of giving invalid syntax. I've asked them to look into returning a result in the past (https://github.com/dtolnay/syn/issues/7), but they are uninterested in doing so. I'd open an issue over there if you want to see movement on that front. I'm open to new issues if there's any specific places we can improve the error messages, but I think this can probably be closed at this point.
