### ISSUE TITLE
Feature Request: Converting between `Interval` and `chrono::Duration`

### ISSUE THREAD

**Issue by KeenS** [diesel-rs/diesel#922]
I want to use `interval` type in PostgreSQL with diesel. The counter part sql type in diesel is `diesel::types::Interval`.
`diesel::types::Interval` can be converted only from and to `PgInterval` (CF http://docs.diesel.rs/diesel/types/struct.Interval.html) but it's not so convenient using around in the program because it cannot interact with chrono types and it seems to depends on Postgresql. 
Thus to interact with chrono types and to be independent from postgresql (and diesel itself), I want to select [`interval`](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html) type from the DB as [`Duration`](https://docs.rs/chrono/0.3.1/chrono/struct.Duration.html) type.

**Comment by Eijebong** [comment]
The question is how do you translate `'1 month'::interval` to a Duration ?

**Comment by KeenS** [comment]
Thank you for pointing the problem out. I found I confused duration with interval, it's intervals on the calendar, not time intervals. Then I close this as invalid request. I'm sorry for troubling you.

**Comment by vityafx** [comment]
I have implemented storing of chrono::Duration in the BigInt field of SQLite 3. I decided to use BigInt since it converts to i64 type which is the minimal unit the chrono::Duration. I am gonna implement it for the pgsql too tomorrow.
