### ISSUE TITLE
Rework the migration API

### ISSUE THREAD

**Issue by Eijebong** [diesel-rs/diesel#937]
See https://github.com/diesel-rs/diesel/pull/868#pullrequestreview-33957081

**Comment by sgrif** [comment]
Even though this is on the milestone, it's worth noting that we don't consider this a blocker. After some internal discussion we all agree that we would be able to continue to support the existing functions in the public API (even if deprecated) with whatever we end up with

**Comment by sgrif** [comment]
Since this didn't happen for 0.99, and I don't want to introduce any new deprecations in 1.0, I'm going to move this off the milestone. This will have to wait for at least 1.1 (and be implemented by deprecating the existing API)
