### ISSUE TITLE
Boxed queries do not work with `print_sql!` and `debug_sql!`

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#947]
This is because at the time of boxing we specify the backend. I'm actually not entirely sure how we can fix this, since we can't just take `Box<QueryFragment<DB> + QueryFragment<Debug>>`. It may be a non-issue once we get logging sorted, but it's a shame that this doesn't "just work"

**Comment by theduke** [comment]
Could `QueryFragment` have a trait bound for `Debug`?

**Comment by sgrif** [comment]
No, becuase `QueryFragment<DB>: QueryFragment<Debug>` means that `QueryFragment<Debug>: QueryFragment<Debug>` which is cyclic

**Comment by sgrif** [comment]
Fixed by #1051
