### ISSUE TITLE
[Question] whereHas, has relationship ?

### ISSUE THREAD

**Issue by kocoten1992** [diesel-rs/diesel#951]
Hi diesel,

I'm coming from Laravel web framework, in Laravel there is Eloquent ORM (https://laravel.com/docs/5.4/eloquent-relationships)

It have some kind of magic with method like ```whereHas``` ```has```

To explain, laravel allow user to define relationship before it going to be use, and ```whereHas``` is something like this:

```php
User::has('schools')->whereHas('bankAccount', function ($q) { // $q here is on bank now
    $q->where('balance', '>', '9999');
})->get();

// whereHas is a _where_ on a different table, _has_ is count on relationship have at least 1 record
```

Will feature like that gonna be implement in diesel in the future? Thank you for reading this.

**Comment by sgrif** [comment]
Our associations API is documented [here](http://docs.diesel.rs/diesel/associations/index.html). If you want to get all of the schools which have a bank account, just join between the two tables.
