### ISSUE TITLE
Contributing guide .env.example out dated.

### ISSUE THREAD

**Issue by juliusdelta** [diesel-rs/diesel#953]
It appears that [this](https://github.com/diesel-rs/diesel/blob/master/CONTRIBUTING.md#setting-up-diesel-locally) section of the contributing guide has an outdated `.env.example` link. It should be updated to `.env.sample`

`See [.env.example](.env.example)` to `See [.env.sample](.env.sample)`.

I'll submit a quick PR just to update.

I was trying to contribute and ran into that so I wanted fix it for other new comers.

**Comment by Eijebong** [comment]
Closed by #954 

Thank you
