### ISSUE TITLE
Upgrade to Chrono 0.4?

### ISSUE THREAD

**Issue by LeoTindall** [diesel-rs/diesel#964]
When trying to use diesel with the "chrono" feature, I have to use chrono 0.3.1 because that's the version Diesel uses. Would it be possible to upgrade to 0.4.0, which has much better Serde support and lots of bugfixes?

**Comment by Eijebong** [comment]
Yeah, see #960 :(

That bump is really unfortunate since it was a complete breaking change. You either need to wait for diesel 0.14 or use the master branch

**Comment by LeoTindall** [comment]
OK, gotchya, thanks! Good to know that this is done, I'll close :)
