### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by killercup** [diesel-rs/diesel#969]
I think we should ~~steal~~ copy #968's questions and make an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

@diesel-rs/contributors, what do you think?

**Comment by Eijebong** [comment]
Yeah it's pretty good but it only works for bugs, not for feature requests.

**Comment by killercup** [comment]
I actually just rediscovered we already have that written down: https://github.com/diesel-rs/diesel/blob/f7bb506ffc62ec72aafe60d7909d3614e3ff5376/CONTRIBUTING.md#submitting-bug-reports

(And guess who with their shitty memory wrote all that? xD)
