### ISSUE TITLE
Can't debug_sql! query that contains time::Timespec; trait not implemented

### ISSUE THREAD

**Issue by carols10cents** [diesel-rs/diesel#978]
### Versions

- **Rust:** stable 1.18.0
- **Diesel:** 0.13.0
- **Database:** postgres
- **Operating System** osx

### Feature Flags

- **diesel:** features = ["postgres", "serde_json", "deprecated-time", "chrono"]
- **diesel_codegen:** none

### What are you trying to accomplish?

I'm trying to debug a query in crates.io (essentially [this code](https://github.com/rust-lang/crates.io/blob/f94a74d7b0cc7ebd028cdcebeab45abc46d7b322/src/version.rs#L464-L469) but i'm changing some things for debugging), because i'm having a timezone issue:

```
    let downloads_query = VersionDownload::belonging_to(&version)
        .filter(version_downloads::date.between(
            date(cutoff_start_date)..
                date(cutoff_end_date),
        ))
        .order(version_downloads::date);

    debug_sql!(downloads_query);
```

### What is the expected output?

I expect to see a printed version of the SQL generated by this diesel code.

### What is the actual output?

I get a compilation error:

```
error[E0277]: the trait bound `time::Timespec: diesel::types::ToSql<diesel::types::Timestamp, diesel::backend::Debug>` is not satisfied
   --> src/version.rs:475:5
    |
475 |     debug_sql!(downloads_query);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `diesel::types::ToSql<diesel::types::Timestamp, diesel::backend::Debug>` is not implemented for `time::Timespec`
    |
```

### Steps to reproduce

Check out this branch of crates.io: https://github.com/integer32llc/crates.io/tree/diesel-debug-sql-error and try to build it.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by Eijebong** [comment]
Thanks for the report. It is indeed a bug (we're missing an implementation).

Here is what you would get with the `debug_sql!` function if it worked, I hope it can help you while you're waiting on this to be fixed :)

```sql
SELECT `version_downloads`.`id`, `version_downloads`.`version_id`, `version_downloads`.`downloads`, `version_downloads`.`counted`, `version_downloads`.`date`, `version_downloads`.`processed` FROM `version_downloads` WHERE `version_downloads`.`version_id` = ? AND `version_downloads`.`date` BETWEEN date(?) AND date(?) ORDER BY `version_downloads`.`date`
```
