### ISSUE TITLE
Down migrations can pollute `cargo --test` output

### ISSUE THREAD

**Issue by agersant** [diesel-rs/diesel#984]
Using Rust 1.18, Diesel 0.13.0 on Windows.

When running cargo test, the testing output gets polluted by diesel output for down migrations (if any occur during the tests). Sample output from https://github.com/agersant/polaris unit tests:

```
test config::test_clean_path_string ... ok
Rolling back migration 201706272327
test db::test_migrations_up ... ok
Rolling back migration 201706272313
Rolling back migration 201706272304
Rolling back migration 201706272129
test index::test_browse_top_level ... ok
test index::test_browse ... ok
Rolling back migration 201706250228
Rolling back migration 201706250006
test db::test_migrations_down ... ok
```

Migrations are executed via calls to `diesel::migrations::revert_latest_migration_in_directory` in some of my tests.

I thought cargo suppressed std out during successful tests so I'm unsure if this is a cargo bug or a diesel bug.

**Comment by sgrif** [comment]
This sounds like a bug in cargo or rustc. That function prints to stdout as you mentioned, which should be getting captured.
