### ISSUE TITLE
Is there any plan to support to change table name at runtime?

### ISSUE THREAD

**Issue by nottxy** [diesel-rs/diesel#988]
There are many monthly tables in our DB. Their schemas are the same.

i.e. `battle_reports_201701`, `battle_reports_201702` 

So that would be wonderful if diesel could support the table name could be assigned at runtime,  I believe that this feature will be welcomed.

Thanks you guys for amazing diesel!

**Comment by sgrif** [comment]
This isn't a feature that we're currently looking to support. You could make this work using the [`sql` function](http://docs.diesel.rs/diesel/expression/dsl/fn.sql.html).
