### ISSUE TITLE
Let's consider going back to macros for stable

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#99]
Syntex has proven to be pretty painful to track for supporting our compiler plugins on Stable. I think it's probably worth keeping support for, but we've been having issues with it causing released versions to break after the fact. I'd like to keep it as an option, but remove it by default in favor of our old "put your struct definition in these macros" solution as the "will definitely work on this version of Rust until the end of time" option.

**Comment by bjz** [comment]
The reliance on Syntex scares me, as somebody who wished to introduce Rust for one of our data analytics projects. I would have definitely been more confident if there were macro alternatives available, in lieu of the stabilization of syntax extensions :(

**Comment by sgrif** [comment]
> The reliance on Syntex scares me

I wouldn't call it reliance. Every single thing that we use syntax extensions for is completely reasonable to write by hand (which I often do when I don't want to use syntex, or can't use codegen).

**Comment by sgrif** [comment]
Putting this on the 0.7 milestone. I've been working on this for a few days now. Still need to audit a few more cases, but I'm fairly certain that every single one of our syntax extensions (with the exception of `infer_schema!` and `infer_table_from_schema!`) can be handled with a normal macro.

The overall plan is to add macros for each of our custom derive cases (all of our annotations are basically custom derive. The ones that aren't explicitly a `#[derive]` annotation are because they need arguments.) I'm thinking I'd like to structure the macros so that they are compatible with the [`custom-derive` crate](https://github.com/DanielKeep/rust-custom-derive), but I see no reason to enforce using that crate.

I think it makes sense to keep the syntax extension form, but simply have them call the macro from the main Diesel crate. Aside from the "this eventually becomes stable" argument, we can also provide *much* better error messages from a procedural macro. For example, if `Insertable` is derived on a tuple struct, all fields must be annotated with the name of the column. We simply can't communicate that effectively from a normal macro.

I plan on opening a PR moving `#[insertable_into]` over to a normal macro this weekend, and I think we should declare this as a blocker for 1.0.

**Comment by sgrif** [comment]
These have been implemented wherever possible.
