### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by differs** [diesel-rs/diesel#992]
Compiling diesel_codegen v0.14.0 (file:///home/cryptape/do/ll/diesel/diesel_codegen)
   Compiling diesel_cli v0.14.0 (file:///home/cryptape/do/ll/diesel/diesel_cli)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/cryptape/do/ll/diesel/target/debug/deps/diesel_codegen-419194587219719e.0.o" "-o" "/home/cryptape/do/ll/diesel/target/debug/deps/libdiesel_codegen-419194587219719e.so" "/home/cryptape/do/ll/diesel/target/debug/deps/diesel_codegen-419194587219719e.crate.metadata.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/home/cryptape/do/ll/diesel/target/debug/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/cryptape/do/ll/diesel/target/debug/build/backtrace-sys-1baadb2b8b21e542/out/.libs" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/cryptape/do/ll/diesel/target/debug/deps/libdotenv-89169d345b7ab505.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libregex-661140217135aecc.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liberror_chain-362b2fc39c3b64d7.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libthread_local-5da2193bb1a1b3a5.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liblazy_static-2e2526463c3ffdb8.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libunreachable-bbd49c281171350c.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libvoid-9beb42a27999bf75.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libdiesel_infer_schema-459953b398a3644f.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libsyn-98351cd6ec62b61a.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libquote-163aca5423a5f7ff.rlib" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "proc_macro-3d2207af32cd8c5f" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax-852787a0069ab941" "-Wl,-Bstatic" "/home/cryptape/do/ll/diesel/target/debug/deps/libutf8_ranges-11273e534a7127e8.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libdiesel-464cd44bec098c0e.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libserde_json-479652ae3ad9f1e1.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libdtoa-0c17e1edae412b93.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libitoa-cd4c42fd74bce3f7.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libserde-dd73a346f8ed5a0e.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libuuid-eb0253b8bdc1f0cb.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libquickcheck-40c4b8fb3fe28dc5.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libenv_logger-fed105cc817e1bc6.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liblog-2f92f93a5a011132.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libpq_sys-4dd5b9f75045876d.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liburl-cb4d686236b7f21f.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libidna-300a91d5724df3c9.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libunicode_bidi-32ec071e9b5e42a3.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libmatches-e84540bad6fb377c.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libchrono-fd719a14f27e5c00.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libtime-a04cc3cf07680fbc.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libbyteorder-b1b86eb04d218493.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libmysqlclient_sys-b691a1d178fa993e.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libpercent_encoding-284daf11c4677663.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libipnetwork-e905e34e7c5310dd.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liblibsqlite3_sys-c182c90c9f7eaca1.rlib" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "rustc_errors-8575bac255367e19" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_pos-d5705c75ee23db2a" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_data_structures-e709fc745a32da67" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "serialize-c8991e9e9e8e0650" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "term-f948a3bba7bc782d" "-Wl,-Bstatic" "/home/cryptape/do/ll/diesel/target/debug/deps/libbacktrace-83723b2e1a66afed.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libbacktrace_sys-f2a2b2b41302bd22.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/librustc_demangle-a7345c3464453eab.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libcfg_if-39ef4305d7479b5e.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libaho_corasick-d431ff4041294028.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libmemchr-9ac117511c71f722.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libregex_syntax-93cf23f8511c0ed0.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libsynom-2d0b36ff560a6993.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libunicode_xid-6ff540e8083bd6a0.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libbigdecimal-e694916100397648.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libnum-db6fcbedbb9a5ca5.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libnum_bigint-d1f6b79cea06de8b.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/librustc_serialize-2b1723f1ddfb107b.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/librand-1219910d9a3be8ab.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libnum_iter-22d079ca2dfa38ff.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libnum_integer-10c74872b9020d09.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libnum_traits-7cd66aa17e564aba.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libunicode_normalization-3629d4870a8baca6.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libregex-64f7dadf8328abf8.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libregex_syntax-c3fea401ab37c547.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libthread_local-457c1f043a3fa8de.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libthread_id-e7f44b5d490f09c6.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libaho_corasick-f977157444369c9c.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libmemchr-055a036f691b12c9.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/liblibc-ca71b4a0502f2058.rlib" "/home/cryptape/do/ll/diesel/target/debug/deps/libutf8_ranges-55a4834614b0b60c.rlib" "-L" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "std-6cb7cb2019c68540" "-Wl,-Bstatic" "/home/cryptape/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-195ad27acd4471f5.rlib" "-Wl,-Bdynamic" "-l" "pq" "-l" "mysqlclient" "-l" "sqlite3" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-shared"
  = note: /usr/bin/ld: 找不到 -lmysqlclient
          collect2: error: ld returned 1 exit status

**Comment by sgrif** [comment]
By default diesel_cli compiles with support for all supported backends. It looks like you don't have mysql installed on your machine. If you'd like to install with just support for one backend, you can do `cargo install diesel_cli --no-default-features --features "postgres"`
